### ISSUE TITLE
Multiple auto complete messages showing

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#1002]
- Your Rocket.Chat Experimental app version: 1.15.0.8836
- Your Rocket.Chat server version: 1.1.1 

![image](https://user-images.githubusercontent.com/6295044/59938206-5d805080-9422-11e9-9828-cb23231c164a.png)

**Comment by Prateek93a** [comment]
@diegolmello Can I work on this?

**Comment by diegolmello** [comment]
@Prateek93a sure

**Comment by Prateek93a** [comment]
@diegolmello Sir I tried but could not reproduce the issue, is this issue already fixed?

**Comment by wreiske** [comment]
> @diegolmello Sir I tried but could not reproduce the issue, is this issue already fixed?

I can't reproduce it currently. I think it happens randomly.... it is very possible they fixed this by switching to watermelon.

**Comment by diegolmello** [comment]
Let's close then.
@wreiske please let me know if you find this issue again.
Thanks.
