### ISSUE TITLE
Send button disappears sometimes

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#1003]
- Your Rocket.Chat Experimental app version: 1.15.0.8836
- Your Rocket.Chat server version: 1.1.1

Sometimes when typing up a message, the send button doesn't show up and makes it impossible to send a message.

![image](https://user-images.githubusercontent.com/6295044/59938363-c49e0500-9422-11e9-975c-8c66f3f6976f.png)

**Comment by Prateek93a** [comment]
Can I work on this issue if it is still persistent?

**Comment by Aaryan-kapur** [comment]
May I take this up @djorkaeffalexandre

**Comment by sarthakpranesh** [comment]
Hey @Aaryan-kapur @djorkaeffalexandre @wreiske, I was trying to reproduce this bug but wasn't able to. It looks like it has been fixed already. If not then can anyone of you provide more info on this, else the issue can be closed :smile:

**Comment by Aaryan-kapur** [comment]
It is not an issue that is persistent but one which shows up in occasions, I have been working on this, will put a PR for this tomorrow

**Comment by sarthakpranesh** [comment]
Oh great to know that :+1:

**Comment by djorkaeffalexandre** [comment]
I guess it's not happening anymore.
If it happens again, please, open a new issue.
Thanks.
