### ISSUE TITLE
Support multiple OAuth providers

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat.ReactNative#1008]
- Your Rocket.Chat Experimental app version: 3.4.2 (2070)
- Your Rocket.Chat server version: 1.1.2
- Device (or Simulator) you're running with: Android 9

If there are multiple OAuth providers defined in the server, only one of them is visible (in form of a button) in the login screen. When accessing Rocket.Chat via the web browser, the buttons for all OAuth providers are visible and selectable.

Excepted behavior: The login buttons for all of the OAuth providers are visible and selectable

**Comment by subesokun** [comment]
Do you need more information or help at reproducing this issue?

**Comment by diegolmello** [comment]
@subesokun Hi there.
This is not implemented yet.
You can track #1018 for updates.
Thanks.
