### ISSUE TITLE
[IMPROVEMENT] Unify search UX

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1010]
Our search is different across OS:

### Android
Magnifier on header
<img src="https://user-images.githubusercontent.com/804994/60052111-df82aa80-96aa-11e9-8015-c1692824cf1e.png" width="350" />

### iOS
Swipe down to show search box
<img src="https://user-images.githubusercontent.com/804994/60052154-f1fce400-96aa-11e9-8e87-adcf047acf92.png" width="350" />

### Proposed change
- We compared the same feature on other apps in different OS' and we should keep only iOS' UX.
Let's make Android work the same way as iOS.

- We should also add "Cancel" button, to stop searching state and dismiss keyboard.
<img src="https://user-images.githubusercontent.com/804994/60052353-69cb0e80-96ab-11e9-83c2-af1b55642612.png" width="350" />

**Comment by juanpetterson** [comment]
I'm working on it, and soon I'll send the PR.
