### ISSUE TITLE
Support Custom OAuth

### ISSUE THREAD

**Issue by mahal** [RocketChat/Rocket.Chat.ReactNative#1018]
**Feature Request**

We'd love to use the new ReactNative client within our project. We're using custom OAuth
to authenticate the users against our own Wordpress. We know it's on your todo list (in `README.md`) but it's the one most far down in the list. 

I kindly suggest to move **Authentication via Custom OAuth** a bit upwards, if the order is the one you're following while implementing. 

For Android, ReactNative is already better than the native Android client. 

- Your Rocket.Chat Experimental app version: 1.15.1
- Your Rocket.Chat server version: 1.1.3
- Device (or Simulator) you're running with: iPhone SE iOS 12

**Comment by diegolmello** [comment]
Hi, @mahal.
Thanks for your report.
We'll implement more OAuth options in the next months, like SAML, CAS and Custom OAuth.
I'll track Custom OAuth updates in this issue.
Cheers.

**Comment by mahal** [comment]
@jbuechele Thanks for the implementation!
