### ISSUE TITLE
Last messages is not showing on room list view

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.ReactNative#1022]
- Your Rocket.Chat Experimental app version: 0.15.0.8836
- Your Rocket.Chat server version: 0.70.4
- Device (or Simulator) you're running with: Xiaomi Mi 9 

Description:
room list view shows channels and users, but it won't show last message in conversations. 

![Screenshot_2019-06-29-00-35-10-575_chat rocket reactnative](https://user-images.githubusercontent.com/1567272/60374887-e5f48780-9a06-11e9-8631-622068f9fadd.png)

**Comment by diegolmello** [comment]
@lorek123 Can you make sure "Store Last Message" setting is set to true?

**Comment by lorek123** [comment]
@diegolmello it is:
![image](https://user-images.githubusercontent.com/1567272/60442746-03e60600-9c1a-11e9-8c19-6699d0102e51.png)

**Comment by diegolmello** [comment]
@lorek123 Just to check if never worked or it's another bug: logout from your server and login again.

**Comment by lorek123** [comment]
After relogin it's still the same

**Comment by diegolmello** [comment]
Is this still a thing?
