### ISSUE TITLE
Cannot write into "read only group" as owner

### ISSUE THREAD

**Issue by Perflyst** [RocketChat/Rocket.Chat.ReactNative#1025]
- Your Rocket.Chat Experimental app version: 1.15.0
- Your Rocket.Chat server version: 1.2.1
- Device (or Simulator) you're running with: Android 7.1

You cannot write into a read only group even if you are an admin or owner of the group.

Steps to reproduce (iOS):
* Open a channel "read only" as owner
* Try message actions on any message

### GIF
![](https://media.giphy.com/media/hSXPo9XX078nbNzJ3Y/giphy.gif)

**Comment by djorkaeffalexandre** [comment]
Steps to reproduce (iOS):
* Open a channel "read only" as owner
* Try message actions on any message

### GIF
![](https://media.giphy.com/media/hSXPo9XX078nbNzJ3Y/giphy.gif)

**Comment by ankar84** [comment]
Hi, @djorkaeffalexandre 
We are experiencing same issue with a little difference.
I'am RC **Admin** and I can write to my **Read-only broadcast** channel from **RC.ReactNative version 4.6**
But other user with **moderator rights** in that same chat **can not write messages to that Read-only broadcast channel from RC.ReactNative version 4.6**. But he easily **can do it from web version or desktop client**.
![image](https://user-images.githubusercontent.com/4023037/77739982-8540bc80-7023-11ea-9349-a509e384f288.png)
![image](https://user-images.githubusercontent.com/4023037/77740009-95589c00-7023-11ea-8638-da395de4fdfe.png)
Please fix it.
Thanks!

**Comment by djorkaeffalexandre** [comment]
@ankar84, I'll work on this today!
Probably it'll be fixed in the next beta.
Thanks!

**Comment by ankar84** [comment]
> @ankar84, I'll work on this today!
> Probably it'll be fixed in the next beta.
> Thanks!

Great news, Alexandre! 
Will be waiting.
