### ISSUE TITLE
Notifications and missing messages

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1030]
- Your Rocket.Chat Experimental app version: 1.16.0.9278
- Your Rocket.Chat server version: Open.rocket.chat on 1.3 dev I believe + 1.2.1 + 1.1.3
- Device (or Simulator) you're running with: Samsung S9

When running multiple servers the app struggles to select the correct server/channel/message when you get a taskbar notification.

This also seemed to have the effect of missing some messages eg

0900 My Message
1030 Someone else

But I knew there were 6 messages between 0900 and 1030. The channel had not synced correctly.

After a little while and trying to swap back and forth between servers the remaining messages suddenly appeared.

I am not sure the two issues are linked or not, but both exist.

**Comment by trinhpham** [comment]
I'd like to get this up, since I am facing the same issue. Both client & server are on latest version.

**Comment by B3QL** [comment]
I've also encounter problems with synchronization between platforms.
Mobile app on iOS: 4.7.2.302 
Self-hosted server version: 3.3.3

Before I flushed all the cache I was receiving Push notifications about latest messages, however I wasn't able to see them in app.
After flushing I can't sync anything  and don't receive any Push notifications.

**Comment by diegolmello** [comment]
We've been working a lot on notification lately.
I'm closing.
Let me know if it's still a thing.
Thank you.
