### ISSUE TITLE
[NFR] Backup account settings to file

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1035]
It would be extremely useful to backup account settings to a local file.

It doesn't require all the data being backed up as this will sync.

Just the account, the user, and possibly the password.

**Comment by reetp** [comment]
Oh for this feature over the last couple of months ;-)

**Comment by diegolmello** [comment]
We're going to do something similar [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2348)
