### ISSUE TITLE
Hide "Forgot password" if Accounts_PasswordReset set to False

### ISSUE THREAD

**Issue by imdario** [RocketChat/Rocket.Chat.ReactNative#1036]
- Your Rocket.Chat Experimental app version: 1.16.0
- Your Rocket.Chat server version: 1.1.3
- Device (or Simulator) you're running with: One Plus 6

On desktop and browser, Rocket.chat hides its "Forgot password" link if Accounts_PasswordReset is set to False.

It can be misleading if Rocket.chat is integrated against authentication systems as LDAP, as this reset isn't going to modify the centralized credentials but Rocket's local ones.

It is not urgent but it would be nice to have.

**Comment by diegolmello** [comment]
Hi, @imdario.
Thanks for opening this issue.
Let's keep track of the progress here.
Let me know if you want to contribute.
Cheers.

**Comment by imdario** [comment]
I would love to but I should check first the source code, as I'm React Native isn't my usual craft.

**Comment by juanpetterson** [comment]
I'm working on it, and soon I'll send the PR.
