### ISSUE TITLE
Image upload is not working on 0.70.4 server 

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.ReactNative#1042]
- Your Rocket.Chat Experimental app version: 1.16.0.9441
Your Rocket.Chat server version: 0.70.4
Device (or Simulator) you're running with: Xiaomi Mi 9

after an update to the current latest version image upload does not work. after confirmation of upload there is an error: 
``` Error uploading Filename
Try again
```
I've checked this against open.rocketchat server and it works correctly. 

I think this needs to be investigated, if we don't to support older server versions we need to pass the information to the users.

**Comment by DoM1niC** [comment]
Yep sending from files doen't work on my dev Build too, currently image/jpeg not valid file or image is to big ... :(

**Comment by DoM1niC** [comment]
![WhatsApp Image 2019-07-29 at 22 59 13](https://user-images.githubusercontent.com/1436958/62082211-98ad4500-b254-11e9-851b-5f84acab81f7.jpeg)
Still exist... :(

**Comment by diegolmello** [comment]
@DoM1niC It's fixed, but not released.
I just published on the app Google Play and submitted to App Store review.
Android version may be released in the next hours.

If the problem persists, remember to paste app version here.
Thanks.
