### ISSUE TITLE
Better SafeAreaView

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1046]
SafeAreaView is a **thing** just for iPhone devices with notch (iPhone X*).
It doesn't apply to Android.
That said, [looking at react-native-safe-area-view implementation](https://github.com/react-native-community/react-native-safe-area-view/blob/master/index.js), we can see they do a heavy job to identify the device type.

Long story short, we already have our own native implementation returning if it's iPhoneX method and we could only run `react-native-safe-area-view` only if it's true.
Return an usual `<View />` otherwise.
It wouldn't do heavy calculations unnecessary.

It needs investigation and memory debugging to confirm it really works and it does have benefits.

**Comment by weijia-yu** [comment]
@diegolmello should we add safe area for android devices too, there are more and more notch android devices
