### ISSUE TITLE
Can't connect to my server anymore in experimental Build

### ISSUE THREAD

**Issue by Jan-NiklasB** [RocketChat/Rocket.Chat.ReactNative#1052]
- Your Rocket.Chat Experimental app version: 1.16.1 (Updated 2019-07-14)
- Your Rocket.Chat server version: 1.1.3
- Device (or Simulator) you're running with: LG G5 (H850) with Resurrection Remix 7.0.2 (Android 9) 

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

I updated my OS and the R.C Experimental build a few days ago and since then I can't connect to my Server via experimental build anymore, normal build still works fine.

If I try to I get the message, that the URL is invalid.
The URL is: http://fb.bogatka.org:3000

I don't know where the Problem comes from, maybe the Server is too old, but I think in this case it should say, that the server's version is to old but not URL invalid...

Would be cool, if someone could check this.

**Comment by pranavpandey1998official** [comment]
We don't support http server please switch to https and try again

**Comment by diegolmello** [comment]
@Jan-NiklasB Can you send your log report?

**Comment by Jan-NiklasB** [comment]
@diegolmello
Sure,which one Do you need?
Server log, or App log?
in Case of App log, it would be nice if you can give me a hint where to find them if you don't mean the logcat.

**Comment by diegolmello** [comment]
@Jan-NiklasB I just tested 1.16.1 on my Android and it works.
It didn't work on iOS, because Apple rejects http calls (or enforces to do it manually).
We need more data to reproduce.

**Comment by Jan-NiklasB** [comment]
@diegolmello Well, as said I would send logs, but I doesn't know the location of them.
I just tried to get https running, but Caddy ends with Error:
<pre>Jul 15 17:03:09 Kein-PC rocketchat-server.rocketchat-caddy[2926]: Activating privacy features... 2019/07/15 17:03:09 [fb.bogatka.org] failed to get certificate: [fb.bogatka.org] error presenting token: presenting with standard HTTP provider server: Could not start HTTP server for challenge -&gt; listen tcp :80: bind: address already in use
</pre>

My setup at the moment is the following:

Linux Mint 19 with Rocket.chat server running as snap
PC is connected to the I-Net via IPFire router with port forwarding for Port 3000 to the snap
fb.bogatka.org is a dynDNS link to the PC running the server (I can enable TLS with signed certificate by the provider for this URL)

I tried to enable TLS following this guide: https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/

Maybe I'm just too dumb to find the problem, but I would be very appreciated if you may could help me.
