### ISSUE TITLE
[IMPROVEMENT] Use autoFocus rather than timeout + focus

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1067]
In some places, text input must be focused automatically on did mount, but we could do it better.
Currently, we're using a setTimeout to wait for navigation transition animation and then a `inputRef.focus()`.
`TextInput` has a `autoFocus` prop that does it.

Example: [`LoginView`](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/LoginView.js#L88)
```jsx
// We could remove this entire block and add `autoFocus` on username input and remove unnecessary ref
componentDidMount() {
	this.timeout = setTimeout(() => {
		this.usernameInput.focus();
	}, 600);
}
```

### Where to do it:
- [ ] CreateChannelView
- [ ] ForgotPasswordView
- [ ] LoginView
- [ ] NewServerView
- [ ] RegisterView
- [ ] SearchMessagesView
- [ ] SetUsernameView

**Comment by tj4752** [comment]
I'm working on this issue.

**Comment by diegolmello** [comment]
@tj4752 Sure! Let me know if you have any questions.

**Comment by tj4752** [comment]
I have a question @diegolmello . Do we want to keep setTimeout or not?

**Comment by tj4752** [comment]
Hello @diegolmello , I've submitted a pull request closing this issue. Could you please review it?

**Comment by tj4752** [comment]
Hello @diegolmello , I'm facing an error when running eslint during making a commit. Could you please help?
![Screenshot from 2019-07-24 22-23-22](https://user-images.githubusercontent.com/32940477/61813386-3541a280-ae63-11e9-8bee-ce281183cbea.png)
![Screenshot from 2019-07-24 22-23-48](https://user-images.githubusercontent.com/32940477/61813396-383c9300-ae63-11e9-9980-f3280ad7d7a0.png)

**Comment by diegolmello** [comment]
@tj4752 Hi. You don't need that `componentDidMount`.
`this.usernameInput` is created on his `inputRef`... the same way `passwordInput` does.
You can safely delete that `componentDidMount`.
