### ISSUE TITLE
Keep favorite rooms on top

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat.ReactNative#107]

**Comment by yashovardhanagrawal** [comment]
can I work on this issue?

**Comment by saketkumar95** [comment]
Go ahead ! @yashovardhanagrawal 👍

**Comment by yashovardhanagrawal** [comment]
from what I analyse this should be done in two parts
1. Add marking as favourite option
2. Moving the favourite chats to the top

about implementing the first one, should I create an option on the header inside the chat to mark as a favourite (like a star icon)?
