### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by jackyang1984** [RocketChat/Rocket.Chat.ReactNative#1074]
file path: containers/MessageActions
line: 263

text: I18n.t('Yes_action_it', { action: 'delete' }) => text: I18n.t('Yes_action_it', { action: I18n.t('delete') }),

**Comment by diegolmello** [comment]
@jackyang1984 Can you elaborate?

**Comment by jackyang1984** [comment]
Rocket.Chat.ReactNative

function handleDelete, second alert label did not use translation,

**Comment by jackyang1984** [comment]
source file src/app/containers/MessageActions.js

**Comment by diegolmello** [comment]
@jackyang1984 What language? Can you post a screenshot?
Can you create a PR?

**Comment by jackyang1984** [comment]
how can i do that? And i found some translation is not correct.

**Comment by jackyang1984** [comment]
Chinese，I just feeling some place is not correct
