### ISSUE TITLE
Cannot upload image or file

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/Rocket.Chat.ReactNative#1076]
Cannot upload image or files 
![Screenshot_20190726-062917](https://user-images.githubusercontent.com/1788360/61992692-052d1600-b094-11e9-88ca-908fbc811ff9.jpg)

**Comment by DoM1niC** [comment]
Same like this! https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1042

**Comment by diegolmello** [comment]
@ccfiel @DoM1niC can you test on beta?

**Comment by ccfiel** [comment]
@diegolmello I am already in beta

![Screenshot_20190727-230805](https://user-images.githubusercontent.com/1788360/62000431-67742e00-b109-11e9-9251-8a8e285364cd.jpg)

**Comment by DoM1niC** [comment]
@diegolmello I use the last Dev Commits & the Problem exist here too...

**Comment by diegolmello** [comment]
@ccfiel @DoM1niC Post your `File Upload` config of your server here and the image you're trying to send.

**Comment by ccfiel** [comment]
File Upload config
![Screenshot from 2019-07-29 20-07-50](https://user-images.githubusercontent.com/1788360/62047317-c2f30880-b23c-11e9-8547-79a935fb5ca4.png)

Image trying to send.
![IMG_20190726_124754](https://user-images.githubusercontent.com/1788360/62047362-ddc57d00-b23c-11e9-802a-38538bf3daf8.jpg)

**Comment by diegolmello** [comment]
@ccfiel Ok, I think I found what's going on. Thanks for reporting!

@pranavpandey1998official Can you fix it?
It seems we're not allowing to upload files if `FileUpload_MediaTypeWhiteList` is null.
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/MessageBox/UploadModal.js#L170
Thanks!

**Comment by DoM1niC** [comment]
Nice :) no Problem Bugs are still alive every day & every night ^^
