### ISSUE TITLE
[Bug] Share Media e.g. Images to File Upload -> Error

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat.ReactNative#1084]
I tried to share Images from **WhatsApp** to RocketChat Client but a Error is appear ... 
![WhatsApp Image 2019-07-30 at 03 13 23](https://user-images.githubusercontent.com/1436958/62123270-e1521600-b2c7-11e9-9baa-611af5729ad1.jpeg)
![WhatsApp Image 2019-07-30 at 03 13 23-2](https://user-images.githubusercontent.com/1436958/62123272-e1eaac80-b2c7-11e9-96c9-c6124acf8cce.jpeg)

After this the Error will not send the Content... :( 

I use last **Dev (Nightly)**, RocketChat Server is Dev Instance too....

**Comment by diegolmello** [comment]
@DoM1niC I need more info.
Server version, app version, file upload config.

**Comment by artF-Secure** [comment]
I've reproduced it on: 
Your Rocket.Chat Experimental app version: 1.17.0.10142
Your Rocket.Chat server version: 0.70.4

**Comment by lorek123** [comment]
I've reproduced it on:
Your Rocket.Chat Experimental app version: 1.17.0.10142
Your Rocket.Chat server version: 0.70.4

**Comment by diegolmello** [comment]
Does it happens when trying to upload from inside the app or only from share extension?
Does it happens only when uploading from WhatsApp?

**Comment by lorek123** [comment]
FIle upload works fine from inside the app. 
file sharing via share extensions does not. I've checked that it won't work against open rocketchat too.

**Comment by diegolmello** [comment]
@lorek123 Ok, only from WhatsApp? Does it work from Photos?

**Comment by lorek123** [comment]
Won't work from both WhatsApp and camera app.

**Comment by diegolmello** [comment]
@djorkaeffalexandre We're sending type as `undefined`.
<img src="https://user-images.githubusercontent.com/804994/62134767-7bf62900-b2b7-11e9-881a-be7f5e7724cd.png" />
