### ISSUE TITLE
Remove server directly from server's list

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.ReactNative#1087]
## Describe the bug
Current it is only possible to remove a server by logging out from it. But if the server is not available anymore (i.e.: the server has been turned off) I cannot log in into to it to log out.

## To Reproduce
1. Connect to a running server
2. Shutdown the server
3. Try remove the server from the app

## Expected behavior
A long press on the server item from server's list could show an option to remove it.

## Screenshots
![image](https://user-images.githubusercontent.com/8591547/59104206-52e49800-8907-11e9-8bc5-8c0c6bc03201.png)

There is no way no remove servers `192.168.1.x` as they are not running anymore.

## Devices and Versions

Your Rocket.Chat.Android version: 3.4.2 (2070)
Your Rocket.Chat Server version: 1.2.0-develop

Mobile device model and OS version: Mi A2 - Android 9

**Comment by andypost** [comment]
It is really confusing ... I can't remove server from list without connecting to it.
Meantime if server using basic auth there's no way to connect to it
