### ISSUE TITLE
[BUG] Unable to start new chat with directory users

### ISSUE THREAD

**Issue by justinr1234** [RocketChat/Rocket.Chat.ReactNative#1089]
- Your Rocket.Chat Experimental app version: 1.16.1.9545
- Your Rocket.Chat server version: 1.3.0-develop
- Device (or Simulator) you're running with: iPhone XS Max 12.3.1

I’m unable to create new chats with people searching by name. This works on the native iOS app but not RN.

![4C9106C3-4E88-4890-A991-0CD9289F321F](https://user-images.githubusercontent.com/7017500/62153713-cfbe3d80-b2ca-11e9-8d11-07391bcb6007.png)
![29E58950-FF52-47FE-B527-33C45B8D48A4](https://user-images.githubusercontent.com/7017500/62153714-d056d400-b2ca-11e9-95da-7770c1006a1e.png)
![1328E2A0-1FB8-401D-A65D-A14F97DB373F](https://user-images.githubusercontent.com/7017500/62153902-37748880-b2cb-11e9-9012-b91c414a12ad.png)

**Comment by diegolmello** [comment]
This is a message from Github with @rocket.cat alias.
Or `@ubergeekzone` doesn't exist or it's a different username.
And don't user `@` when searching.
<img src="https://user-images.githubusercontent.com/804994/62154252-c211b380-b2dc-11e9-8e43-743a8a6916aa.png" />

![image](https://user-images.githubusercontent.com/804994/62154456-1fa60000-b2dd-11e9-8c34-862bcb07067b.png)

**Comment by justinr1234** [comment]
It was just lagging because of connectivity, I had the issue with a full user of the server.
