### ISSUE TITLE
[FEAT] search bar for emoji picker

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.ReactNative#1090]
Your Rocket.Chat server version: 0.70.4
Device (or Simulator) you're running with: Mi 9
Your Rocket.Chat Experimental app version: 1.17.0.10142

As a user I want to search for emoji via text search (by name and alias) to speed up finding proper emoji for reaction.

**Comment by diegolmello** [comment]
@lorek123 Thanks for opening.
Yes, we already started some tasks on that way in past months, but we closed that PR to work on other features.
We're going to refactor emoji picker in mid term.
Cheers.
