### ISSUE TITLE
How is this library installed? I can't install it

### ISSUE THREAD

**Issue by yrjwcharm** [RocketChat/Rocket.Chat.ReactNative#1094]
![image](https://user-images.githubusercontent.com/34397383/62280092-d9d46d80-b47d-11e9-9ccc-f91ef6d69be7.png)

**Comment by yrjwcharm** [comment]
@rocket.chat/sdk can't be install.

**Comment by diegolmello** [comment]
@yrjwcharm Please send more info: error details, commands used, screenshots, etc.

**Comment by yrjwcharm** [comment]
@diegolmello  npm install

**Comment by diegolmello** [comment]
@yrjwcharm You have to use `yarn`
