### ISSUE TITLE
null is not an object (evaluating 'blob.data')

### ISSUE THREAD

**Issue by amirsafiallah** [RocketChat/Rocket.Chat.ReactNative#1102]
- Your Rocket.Chat Experimental app version: [1.17.0](https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/1.17.0)
- Your Rocket.Chat server version: 1.2.3
- Device (or Simulator) you're running with: Samsung Galaxy A50 (Android 9)

When I disconnect from the Internet, this error's thrown.
**It seems the `fetch` makes this error.**

![Screenshot_20190805-102600_ DEVELOP  RocketChatRN](https://user-images.githubusercontent.com/14177455/62442036-bc4c2000-b76b-11e9-93e8-239d35d17792.jpg)

**Comment by pranavpandey1998official** [comment]
Same as #938
