### ISSUE TITLE
Handle logout/session end gracefully

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.ReactNative#1111]
- Your Rocket.Chat Experimental app version: 1.18.0.10386
- Your Rocket.Chat server version: 1.4.0-develop (open.rocket.chat)
- Device (or Simulator) you're running with: ios 12 (fully patched) iphone XS

If you are logged out by your server for any reason and then you open the app.  It handles it by actually removing the server.

It should at least show a dialog saying what happened.  Ideally it would show that **and** take to login screen instead of removing the server completely. 

Easy way to test this would probably be to login as a test user.  Then in admin deactivate the user.  I believe this wipes their tokens.

**Comment by sarthakpranesh** [comment]
I tried to produce this error on the current develop branch, it looks like it is fixed :smile: can you guys verify that @geekgonecrazy @diegolmello ?

**Comment by diegolmello** [comment]
Yes, it's fixed. Thanks.
