### ISSUE TITLE
Slash command in thread is sent to parent channel

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat.ReactNative#1115]
### General info

- Your Rocket.Chat Experimental app version: 1.17.0
- Your Rocket.Chat server version: 1.4.0-develop
- Device (or Simulator) you're running with: iPhone X

### Issue description

When you try to use slash commands within a thread, the response will be posted in the parent channel and not into the thread itself:

(click screenshot below for a demo screen capture)

[![](https://i.imgur.com/NBnTLBU.jpg)](https://streamable.com/il99o)

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/15165

**Comment by sarthakpranesh** [comment]
Hey @diegolmello @frdmn, I tried to reproduce this error on the current develop branch but wasn't able too. Looks like it is fixed already. I hope this issue can be closed :smile:
