### ISSUE TITLE
[Bug/Issue] App crashed by Sharing Media like Audios / some Videos

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat.ReactNative#1119]
Image Sharing works nice but if I try to share a Voice Message e.g. from WhatsApp to this Client the Program crashed instantly, some Videos crash too from my Gallery & if I try to share from WA to React RocketChat. The Modal not appear, after this the App have to load again (I think crashed).

**Huawei Mate 20 Lite - Android 9**
**RocketChat React:** Develop Branch
**RocketChat Server:** Develop Branch

**Comment by DoM1niC** [comment]
Sending Pictures is broken here too....

**Comment by djorkaeffalexandre** [comment]
@DoM1niC can you give me Android logs?
