### ISSUE TITLE
[Build Error] react-native 0.60.4

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat.ReactNative#1120]
Since the new React changes on Android Projekt my Dev Maschine under VirtualBox says **`OutofMemory`**..
**Code** & **Dirs** are clean up before **compile** & **reopen** the **Project**...

![image](https://user-images.githubusercontent.com/1436958/62768330-e9b00b00-ba96-11e9-9484-015c5b331842.png)
**Android Studio 3.4.2**

![image](https://user-images.githubusercontent.com/1436958/62768354-f59bcd00-ba96-11e9-8d26-d69f1b6a2811.png)

**Comment by diegolmello** [comment]
@DoM1niC Try `rm -rf android/app/build` and rerun.

**Comment by DoM1niC** [comment]
> @DoM1niC Try `yarn`, `rm -rf android/app/build` and rerun android build.

This will do before I compile everytime.... :(

**Comment by diegolmello** [comment]
@DoM1niC Can you add `org.gradle.jvmargs=-Xmx2048M -XX\:MaxHeapSize\=32g` on `gradle.properties`, clean everything and try again?
RN 60 seems to be heavier than 59.

**Comment by DoM1niC** [comment]
> @DoM1niC Can you add `org.gradle.jvmargs=-Xmx2048M -XX\:MaxHeapSize\=32g` on `gradle.properties`, clean everything and try again?
> RN 60 seems to be heavier than 59.

Works Thanks :+1:
