### ISSUE TITLE
[Bug/Issue] New Reacts crashed randomly

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat.ReactNative#1126]
**Huawei Mate 20 Lite - Android 9**
**RocketChat React:** Develop Branch
**RocketChat Server:** Develop Branch

Since the new React Update my App often crashed by open Notifications or interact in some Chats.... If I take a Picture there is crashing too..... 

**Update**
Open Notification works sometimes, there is general a problem the App crashed instantly after some interactions.

**Comment by diegolmello** [comment]
@DoM1niC Always post log reports in those cases.
You're running develop branch, so your log report is only on click away.

**Comment by DoM1niC** [comment]
Seems better now Take Picture is no more crashing & the most looks more stable since recent updates !!!
