### ISSUE TITLE
Cannot click or copy links in Room Info

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1130]
- Your Rocket.Chat Experimental app version: 1.18.0.10579
- Your Rocket.Chat server version: various
- Device (or Simulator) you're running with: Samsung S9

Go to Room/Channel
Select Actions (3 dots top right)
Click the Room Info
See links in Topic but you cannot click or copy any of them

![Screenshot_20190813-200842_RocketChat Experimental](https://user-images.githubusercontent.com/3800384/62968473-67637600-be0b-11e9-99fb-5bea7ee22948.jpg)

**Comment by lucassmacedo** [comment]
I have a similar problem. Links dont work

**Comment by adrijshikhar** [comment]
@diegolmello i would like to work on this bug, can you please assign it to me?
