### ISSUE TITLE
Custom emojis not rendering

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat.ReactNative#1141]
- Your Rocket.Chat Experimental app version: 1.18.0.10607
- Your Rocket.Chat server version: 1.0.3
- Device (or Simulator) you're running with: Samsung Galaxy S9

Not sure why, but on the native app custom emojis are working. On the RN they are not.

![image](https://user-images.githubusercontent.com/1986378/63356527-543a3400-c33e-11e9-8f80-3c0d99e7f98a.png)
![image](https://user-images.githubusercontent.com/1986378/63356592-703dd580-c33e-11e9-9917-857709fb60ab.png)

**Comment by ggazzo** [comment]
@marceloschmidt are you sure you have your setting "Enable Markdown" enabled?

**Comment by rasos** [comment]
svg custom emojis seem not to work yet #1164 . I have built and tested with `develop` branch into which it had been merged https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/32a681036ea437da9704cba6545ea00ad0e23dbd

**Comment by diegolmello** [comment]
@rasos Can you create an issue for svgs custom emojis? I'm closing this issue, because it was related to markdown/joypixels. Thanks.
