### ISSUE TITLE
Custom OAuth: "undefined Error Code: -2"

### ISSUE THREAD

**Issue by mahal** [RocketChat/Rocket.Chat.ReactNative#1150]
- Your Rocket.Chat Experimental app version: 1.18.0
- Your Rocket.Chat server version: 1.2.3
- Device (or Simulator) you're running with: EMUI 9.0.1.169, iOS 12.3.1 and iOS 12.4
- Rocket Chat: https://chat.milchjugend.ch
- OAuth-Provider: https://app.milchjugend.ch/ (where everybody can create an account)
- miniOrange OAuth Server for Wordpress

Steps to reproduce:
- Update to 1.18.0 / Fresh Install 1.18.0
- Launch Rocket.Chat Experimental
- "Connect to a server"
- Connect to "https://chat.milchjugend.ch"
- Use Button "Continue with **Chat öffnen**"
- Error on iOS:
     - Domain: NSURLErrorDomain
     - Error Code: -1003
     - Description: A server with the specified hostname could not be found.

- Error on Android: 
     - Domain: undefined 
     - Error Code: -2 
     - Description: net::ERR_NAME_NOT_RESOLVED

Regression: The same OAuth-Server works with the native Android, iOS and MacOS App as well as with the webclient. 

Followup of #1018

Android Screenshots:
![Screenshot_20190826_112625_chat rocket reactnative](https://user-images.githubusercontent.com/136827/63684225-aecf0680-c7fc-11e9-9538-e7b0559f0ff0.jpg)
![Screenshot_20190826_111509_chat rocket reactnative](https://user-images.githubusercontent.com/136827/63684226-af679d00-c7fc-11e9-8099-b955c63431ff.jpg)

iPhone Screenshots:
![IMG_0107](https://user-images.githubusercontent.com/136827/63684365-07060880-c7fd-11e9-9cc9-12b87bab6beb.PNG)
![IMG_0108](https://user-images.githubusercontent.com/136827/63684372-0e2d1680-c7fd-11e9-8499-5536ee32f11f.PNG)

**Comment by mahal** [comment]
@filipedelimabrito Thanks for the fix. As I'm not fluent in React I couldn't have done it myself, really appreciate your work!

**Comment by filipedelimabrito** [comment]
You're welcome @mahal! Thanks for opening this issue!
