### ISSUE TITLE
[NEW] Go to message e-mail should launch mobile app

### ISSUE THREAD

**Issue by justinr1234** [RocketChat/Rocket.Chat.ReactNative#1158]
When you click "go to message" in an e-mail from Rocket.Chat, by default it should launch the mobile app if you have it installed.

**Comment by Prateek93a** [comment]
@diegolmello From the following gif, the deeplink opens the app if it is installed whereas the other link opens in browser, this is true for desktop as well. The deeplink opens the desktop app if installed. 
The 'Go to message' button has href of the other link, hence it always opens the browser, so by changing the href, and passing suitable `rid` and `path`, the issue can be solved. However I am unsure from where to change the href.
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/44807945/71516871-6a01cc00-28d1-11ea-85e1-902443b57bb2.gif)
