### ISSUE TITLE
Not able to upload images or files

### ISSUE THREAD

**Issue by 2disbetter** [RocketChat/Rocket.Chat.ReactNative#1167]
- Your Rocket.Chat Experimental app version: 1.18.0
- Your Rocket.Chat server version: 1.3.2
- Device (or Simulator) you're running with: Moto G7 Power / Android 9

This may be a react issue but I cannot upload images or files because it believes the file is too large regardless of the server setting or the actual file size.

**Comment by lorek123** [comment]
same here, on 1.19.0.10997 RN and 0.70.4 server

**Comment by lorek123** [comment]
It fails silently on file upload, on share it shows:
![image](https://user-images.githubusercontent.com/1567272/64495308-ac5abb00-d298-11e9-90e6-f35b8dbc6784.png).

**Comment by diegolmello** [comment]
@lorek123 Nice catch! Let's fix it!

**Comment by lorek123** [comment]
@diegolmello ping me on open if you need any details or to test fix.

**Comment by lorek123** [comment]
@diegolmello maybe this is related to 1191?

**Comment by 2disbetter** [comment]
Folks this app is so close to being completely ready. Video calling is in and it works great! Just not being able to upload and files of any kind is the only show stopper. Keep up the great work!

**Comment by diegolmello** [comment]
@2disbetter Ok, I'll try to fix in this beta. Can you send us your file upload config of your server?

**Comment by daltondiaz** [comment]
I've the problem in the lastest app for android.

![rocketchaterror](https://user-images.githubusercontent.com/3844467/72817818-2e94bc00-3c49-11ea-866d-909db95fb19b.jpeg)

This error occur only in mobile app.

Server version: 2.4.2
Android version: 9 
Smartphone: Moto g6
