### ISSUE TITLE
[IMPROVEMENT] Compress Pictures on Photo Upload

### ISSUE THREAD

**Issue by gyverchang** [RocketChat/Rocket.Chat.ReactNative#1181]
Given that mobile devices now can capture up to 40mp photos(Huawei P30 Pro, etc), it takes ages to upload photos up to RocketChat. It would be very cool to have a feature such as WhatsApp that can compress pictures on upload. Rocketchat can take this a step further by offering the user to download the compressed version or the original uncompressed version. 

Rocketchat Administrators can choose to only allow compressed versions to prevent users from filling up GridFS storage with high resolution photos.

**Comment by gyverchang** [comment]
Thank you for your clarification! Is this on the mobile client end or is this implemented on the server end? Thank you!

**Comment by diegolmello** [comment]
It's on mobile.

**Comment by diegolmello** [comment]
I'm closing this issue, ok?

**Comment by gyverchang** [comment]
Is it a planned feature to enable uncompressed uploads?
