### ISSUE TITLE
error Couldn't find the binary git

### ISSUE THREAD

**Issue by longtqdayma** [RocketChat/Rocket.Chat.ReactNative#1187]
PS E:\ReactNative\Rocket.Chat.ReactNative> yarn        
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by diegolmello** [comment]
@longtqdayma It's a connection issue on your side.
