### ISSUE TITLE
Cannot reply with thread/quote to message with image only.

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1193]
- Your Rocket.Chat Experimental app version: 1.20.0-wm.4.11189
- Your Rocket.Chat server version: 2.0.0 (open.rocket.chat)
- Device (or Simulator) you're running with: Samsung S9

Look for a message that is just an image with a comment. 

You cannot long press to reply to the message, quote, start a thread etc. The only action available is to open the image.

**Comment by lorek123** [comment]
Just checked that it works in 1.19, just press above the image. It is unintuitive though...

**Comment by diegolmello** [comment]
Yep, the image is a touchable element and it handles press before the message.
There are several ways to fix it... passing `onLongPress` down the tree, using react-native-gesture-handler, etc

**Comment by Aaryan-kapur** [comment]
If it's available may I take it up?

**Comment by djorkaeffalexandre** [comment]
It was fixed by #2082 @Aaryan-kapur.
