### ISSUE TITLE
[BUG] Custom Emoji rendering issues

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.ReactNative#1194]
- Your Rocket.Chat Experimental app version: 1.20.11229
Your Rocket.Chat server version: 0.70.4
Device (or Simulator) you're running with: Mi 9

Just pulled newest version from play store and introducing JoyPixels also introduce some issues:
1/
![image](https://user-images.githubusercontent.com/1567272/64996112-58298980-d8dd-11e9-8700-0fe9ae582e65.png)
As you can see, selecting normal emoji puts in the input box, where it is not the case for custom ones. Also custom emojis doesn't fit their boxes in picker
2/ 
![image](https://user-images.githubusercontent.com/1567272/64996194-945cea00-d8dd-11e9-802b-75d87282cc7f.png)
here you can see how emojis looks after sending the message. Notice how custom emojis are not fully visible.

**Comment by diegolmello** [comment]
@lorek123 Thanks for opening.
First error is a known issue and happens on web version as well.
It wasn't introduce on this version though. 
![image](https://user-images.githubusercontent.com/804994/64996575-ab3b1680-d8b4-11e9-94c6-9d628e4c9e0a.png)

Second error was happening on other versions as well, but it should be fixed on this one.
Let's take a look.

**Comment by diegolmello** [comment]
@lorek123 It's fixed on 1.20.0 beta, isn't? Can we close it?

**Comment by lorek123** [comment]
Lets close it, future changes about the first issue should needs to be discussed both on web and mobile version.
