### ISSUE TITLE
[CHORE] Use React Fragment shorthand

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1203]
We've been using `<React.Fragment></React.Fragment>` in some places, but we should be using its shorthand for better readability: `<></>`.

Normal usage: https://reactjs.org/docs/fragments.html#usage
Short syntax: https://reactjs.org/docs/fragments.html#short-syntax

**Comment by Prateek93a** [comment]
Hello, I am new to open source coding and would love to work on this issue, can I work on this one, if nobody's assigned already?
