### ISSUE TITLE
[iOS] Metro bundler not opening automatically

### ISSUE THREAD

**Issue by yt-dev** [RocketChat/Rocket.Chat.ReactNative#1208]
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

**Comment by diegolmello** [comment]
@yt-dev Hi there. Run `yarn start` in another terminal before running `react-native run-ios`.
Metro bundler stopped to run automatically on RN 0.60.4.
I'll take a look on this issue soon.
Thanks.

**Comment by yt-dev** [comment]
@diegolmello It works, thanks :)
