### ISSUE TITLE
[BUG] Close SortDropdown on sort select

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1222]
- Your Rocket.Chat Experimental app version: latest
- Your Rocket.Chat server version: Official Rocket.Chat server instance
- Device (or Simulator) you're running with: Samsung Galaxy J6 Android 9

In the following gif, the sorting pop up does not close after selecting a sorting scheme, so is this behaviour normal? Would not it be better if the popup closes after selecting an option?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44807945/65483070-8f3d0380-deb8-11e9-9374-7260ecd55eff.gif)

**Comment by diegolmello** [comment]
@Prateek93a I think we could close on sorting select and leave it open on grouping. Can you work on this fix? Thanks!

**Comment by Prateek93a** [comment]
Yes I would love to. I want to work on this
