### ISSUE TITLE
Add some error tracking like crashlytics or bugsnag

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat.ReactNative#123]
https://github.com/corymsmith/react-native-fabric
https://docs.bugsnag.com/platforms/react-native/

**Comment by GP-S** [comment]
Buglife : [https://www.buglife.com/](https://www.buglife.com/), might be a good idea too at least while in beta (for all graphical bugs and feature request)

**Comment by saketkumar95** [comment]
@rodrigok Can I work on this?

**Comment by saketkumar95** [comment]
@ggazzo I want to work on this. Can you help me in proceeding?

**Comment by ggazzo** [comment]
hey, @saketkumar95. yes, I can :)

**Comment by diegolmello** [comment]
Fixed on #258
