### ISSUE TITLE
Cannot remove server from list unless logged in

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1250]
- Your Rocket.Chat Experimental app version: 1.20.0.11408
- Your Rocket.Chat server version: 2+
- Device (or Simulator) you're running with: Samsung S9

Someone gave me a test login to a server. I tried to login, but couldn't.

I now cannot remove that server from the server dropdown list so it is now stuck there in perpetuity.

Only option currently is to delete all the data from the DBs/reinstall

**Comment by diegolmello** [comment]
Duplicated #1087
