### ISSUE TITLE
[NFR] "Mark as read" notifications in the Notification bar

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1251]
- Your Rocket.Chat Experimental app version: 1.20.0.11408
- Your Rocket.Chat server version: 2+
- Device (or Simulator) you're running with: Samsung S9

A lot of applications have the ability to 'Mark as read' in the dropdown at the top of the screen.

Some like Signal/Whatsapp even let you reply.

Certainly a  'Mark as Read' option would be handy.

**Comment by adrijshikhar** [comment]
@diegolmello can i implement this feature?

**Comment by TarunTomar122** [comment]
@diegolmello  hey, Is this issue still active? I want to help :)

**Comment by diegolmello** [comment]
We're going to be working on it with a different approach soon.
