### ISSUE TITLE
Channel avatars not showing after application unloads

### ISSUE THREAD

**Issue by davidlougheed** [RocketChat/Rocket.Chat.ReactNative#1259]
- Your Rocket.Chat Experimental app version: **Testflight** 1.20.0 (11407)
- Your Rocket.Chat server version: 1.2.1
- Device (or Simulator) you're running with: iPhone 8

When app is first installed, channel avatars are displayed. Eventually (e.g. after the app is closed and re-opened), these are unloaded and only are displayed when the channel receives a new message (and disappear at some point afterwards, e.g. after another restart).

<img width="200" src="https://user-images.githubusercontent.com/357970/65906256-35dd4480-e390-11e9-8aa7-5d6eaaed57b9.jpeg" /> <img width="200" src="https://user-images.githubusercontent.com/357970/65906257-3675db00-e390-11e9-83bf-b79d11c9db9e.jpeg" />

**Comment by diegolmello** [comment]
@davidlougheed Can you test on latest TestFlight version?
Does it happen on https://open.rocket.chat for you?

**Comment by davidlougheed** [comment]
I'll have to wait for the TestFlight version to come through.
It doesn't seem to happen on open.rocket.chat; there's some flickering or delayed loading at startup but they all load. I'm not in as many channels though.
