### ISSUE TITLE
Users with no display name set should display username in profile

### ISSUE THREAD

**Issue by davidlougheed** [RocketChat/Rocket.Chat.ReactNative#1260]
- Your Rocket.Chat Experimental app version: **Testflight** 1.20.0 (11407)
- Your Rocket.Chat server version: 1.2.1
- Device (or Simulator) you're running with: iPhone 8

See attached screenshot for a user without any display name set. It would be nice if this still displayed something, even Unnamed (+ username below) like the web desktop version.

![image1](https://user-images.githubusercontent.com/357970/65916127-c91f7580-e3a2-11e9-9e5e-3ae86aac990f.png)

**Comment by Prateek93a** [comment]
@djorkaeffalexandre Can I work on this ?

**Comment by shubhamofbce** [comment]
I would like to work on this issue. Can I??

**Comment by diegolmello** [comment]
@shubhamofbce Sure!

**Comment by aashaypalliwar** [comment]
@diegolmello Can I take this issue as it has very less activity from a long time?

**Comment by diegolmello** [comment]
@aashaypalliwar sure!

**Comment by aashaypalliwar** [comment]
@davidlougheed  I am unable to reproduce the issue. Whenever I try to set an empty name, the app  doesn't update the info. It is giving success message, but when I reopen the app, the previous name persists. Any luck?

**Comment by davidlougheed** [comment]
@aashaypalliwar for context, these are LDAP users who are automatically created upon first LDAP login

**Comment by adityarajsinghvi** [comment]
@diegolmello  i can work on this if it's still a open issue and no one is working on it?
