### ISSUE TITLE
Group and reply notifications

### ISSUE THREAD

**Issue by emilwojcik93** [RocketChat/Rocket.Chat.ReactNative#1262]
Is there possibility to add time of messge and how long ago this messge was send and instant reply function? Like it is in Android Native Client.

**Comment by diegolmello** [comment]
Can you explain more?

**Comment by babrums** [comment]
I'm not sure, but looks like @emilwojcik93 means Android N instant reply feature and describing how notifications from Telegram, Google Hangouts and other messengers looks like.

**Comment by diegolmello** [comment]
Oh sure. We're going to implement this soon. We'll group notifications by channel as well. Thanks.
