### ISSUE TITLE
Paste option

### ISSUE THREAD

**Issue by emilwojcik93** [RocketChat/Rocket.Chat.ReactNative#1263]
Rocket.Chat Experimental version: 1.19.0
Rocket.Chat Server version: 2.0.0 - Docker install

Phone:

Huawei P20 Lite [ANE-LX1] - EMUI 9.1.0

I don't have aby possibility to paste content of clipboard in message.

**Comment by lorek123** [comment]
duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/872
