### ISSUE TITLE
insert delete-own-message permission

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.ReactNative#1276]
see https://github.com/RocketChat/Rocket.Chat/pull/15512

**Comment by devyaniChoubey** [comment]
Can i work on this issue?

**Comment by Prateek93a** [comment]
I may be wrong but I believe this issue is solved.  The permission to delete own message is being checked here -
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/78d142cd09fd50df18f16fbc715091543d0672e8/app/containers/MessageActions.js#L204

**Comment by ggazzo** [comment]
@diegolmello could you please check?

**Comment by diegolmello** [comment]
It's not done yet.
We need to check for `delete-own-message` permission.

**Comment by ggazzo** [comment]
🤙

**Comment by adrijshikhar** [comment]
can i work on this issue?
