### ISSUE TITLE
svg custom emojis remain transparent

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat.ReactNative#1278]
Custom emojis in svg are not displayed in the app, the area remains transparent / white. 
png works fine, though.

- Your Rocket.Chat Experimental app version: 1.20

#1141       
May be related with not displaying svg inline images in markup  #302.

**Comment by diegolmello** [comment]
Related to #1466. I'm closing this in order to have the conversation there. Thanks.
