### ISSUE TITLE
Refactor RoomActionsView

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1286]
We're using `SectionList` on `RoomActionsView` and it makes it really hard to maintain.
`SectionList` requires data to be split into sections of arrays.
While this is helpful on structured data, it's unnecessary hard to read in our case with *almost* static data.

Also we're using a [`get sections`](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/RoomActionsView/index.js#L164) to work on our state, but it runs on every render. That's a bad practice.

As our data is *almost* static, we can just use a `<ScrollView>` with buttons.
Lots of `if` conditions inside of it would be much more readable.

**Comment by ghalestrilo** [comment]
Cool, I want to work on that! Do you mind if I fork the repo?

**Comment by diegolmello** [comment]
@ghalestrilo This task is already taken. I can find another one for you if you don't mind.

**Comment by ghalestrilo** [comment]
No problem, looking forward to it
