### ISSUE TITLE
[IMPROVEMENT] Respect "Hide counter" preference

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1287]
If "Hide counter" is set, we shouldn't show alerts from the channel.

- Web behaviour (correct):
![image](https://user-images.githubusercontent.com/804994/66429418-62c3d400-e9ee-11e9-8660-00bd49d7db2d.png)

- App behaviour (incorrect):
<img width="350" alt="Screen Shot 2019-10-08 at 17 08 51" src="https://user-images.githubusercontent.com/804994/66429876-58560a00-e9ef-11e9-8414-3356235560a8.png">

Look how the app is showing information in bold and blue. We should behave as if the app has nothing new (everything is read).

**Comment by diegolmello** [comment]
@ghalestrilo can you work on this one? Thanks!

**Comment by CalebeRios** [comment]
Someone already taken this issue?
