### ISSUE TITLE
[CHORE] Refactor RoomItem touchable

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1289]
RoomItem's touchable logic can be removed away into a HOC (high-order component).
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/presentation/RoomItem/index.js#L242

It'll make the component easier to read.

**Comment by Prateek93a** [comment]
@diegolmello
hoc-> https://github.com/Prateek93a/Rocket.Chat.ReactNative/blob/hoc-fix/app/presentation/RoomItem/withTouchableComponent.js

index-> https://github.com/Prateek93a/Rocket.Chat.ReactNative/blob/hoc-fix/app/presentation/RoomItem/index.js

Is this how we had to implement hoc?

**Comment by diegolmello** [comment]
@Prateek93a Cool, but I was thinking more like:
```jsx
<Touchable>
  <Content>
</Touchable>
```

instead of

```jsx
Touchable(Content)
```
