### ISSUE TITLE
Can't connect to http server

### ISSUE THREAD

**Issue by isandrade** [RocketChat/Rocket.Chat.ReactNative#1292]
- Your Rocket.Chat Experimental app version: 1.20.0
- Your Rocket.Chat server version: 0.57.2
- Device (or Simulator) you're running with: Pocophone F1

I'm trying to connect to a server hosted in the company I work for, and I'm failing to make it happen in mobile apps (React and Kotlin version).

in Ubuntu desktop version or accessing from mobile browser it's working well under the URL http://li2234:3000
![image](https://user-images.githubusercontent.com/13832752/66522072-f7980180-eac2-11e9-9c1b-cb1e0218aa11.png)

But when I try in the mobile app it fails, in react version I get this message ```The_URL_is_invalid: 'The URL you entered is invalid. Check it and try again, please!'``` :
![image](https://user-images.githubusercontent.com/13832752/66522697-6f1a6080-eac4-11e9-9cf7-8c35be4c0f83.png)

I took a look in code, then I saw it comes from getServerInfo method:
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/rocketchat.js#L88
which append the input server string with '/api/info', then I tried to run it from my device and it worked:
![image](https://user-images.githubusercontent.com/13832752/66522626-42fedf80-eac4-11e9-852b-eb8a7c0f2445.png)

so now I'm quite confused about why this behavior is happening.

**Comment by lorek123** [comment]
From Readme:
Supported Server Versions: 0.70.0+ 
Check if you can connect after update ;)

**Comment by isandrade** [comment]
Thank you, @lorek123. I looked at the code but not the readme :man_facepalming: 

Suggest: the error message could be better. It says the URL I entered is invalid, but this is not the real problem.
