### ISSUE TITLE
No send message button after Video Call with Jitsi Meet

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#1294]
- Your Rocket.Chat Experimental app version: **1.20.0.11895**
- Your Rocket.Chat server version: **2.1.0**
- Device (or Simulator) you're running with: **Xiaomi Redmi Note 4x Snapdragon**

After user made **Video call** using **Jitsi Meet**, there is no send button (blue arrow) to send messages to chat.
User can fix that by go back to home screen and to chat again. 
And choose Emoji and that back to keyboard can fix that. But sometime Emoji button doesn't work - no action on pressing smile button on left of New message field.
![image](https://user-images.githubusercontent.com/4023037/66541207-2a7bdd00-eb37-11e9-9335-0b1244b5c35d.png)

**Comment by ankar84** [comment]
Now I did reproduce that bug on **Xioami Redmi Note 5**.
Steps to reprosuce:
1. Start Video Call in personal chat in **"..." Video Call**
2. Press **red button** to end Video Call. Now you see user menu with audio and video call on top.
3. Press **left arrow** on top or **back smartphone button** to go to chat again
4. Try to write a new message. **Microphone** and **plus** icons does not desapeared, and **send** icon not shows.

Steps to fix:
1. Try to tap on **smile** icon left of new **message box**. If smile menu opened, tap on **keyboard** icon left of the new **message box**. Now you can see **send** icon (blue arrow)
2. If smile icon doesn't work (I got it for couple times), tap **left arrow** on top or **back smartphone button** to go to **home page** (where all chats and channels)
3. Go to personal chat again - now you see **send** icon

**Comment by ankar84** [comment]
Checked that bug **on iOS - no bug**, all works as it should work.

**Comment by ankar84** [comment]
Same bug on Samsung S8 on Android 9.

- Your Rocket.Chat Experimental app version: 1.20.0.11895
- Your Rocket.Chat server version: 2.1.0
- Device (or Simulator) you're running with: Samsung S8

**Comment by diegolmello** [comment]
@ankar84 Ok, we'll take a look. Thanks.

**Comment by rasos** [comment]
Confirmed on 1.20 build. Only if you leave the channel and enter it again you can send a text message, after having started a video call.
