### ISSUE TITLE
Channel Preview not updating

### ISSUE THREAD

**Issue by gyverchang** [RocketChat/Rocket.Chat.ReactNative#1295]
- Your Rocket.Chat Experimental app version: 1.20
- Your Rocket.Chat server version: 2.1
- Device (or Simulator) you're running with: Huawei P20 Pro, Android 9.

After replying or receiving a reply, the channel preview is not updated. There is no way to force this except to force close the app and open it. 90% of our user base is getting this issue, personally I get this all the time.

Attached are pictures and gifs of this issue. Both are from different time & dates and different channels.

Screenshots(Self Hosted Server)

![Screenshot_20191010_194806](https://user-images.githubusercontent.com/9399347/66570065-02bc6180-eb97-11e9-99c8-a0e4ed21e3ce.jpg)
![Screenshot_20191010_194312](https://user-images.githubusercontent.com/9399347/66570068-03ed8e80-eb97-11e9-9928-fc698e7a6621.jpg)

GIF(from official Rocket Chat channel)

![ezgif com-resize](https://user-images.githubusercontent.com/9399347/66569303-72c9e800-eb95-11e9-9390-e5ba02dfbb68.gif)

**Comment by dusatvoj** [comment]
+1

**Comment by diegolmello** [comment]
Can you try on 1.20.2.12436 (Experimental beta on Google Play) or 1.20.2.12437 (Experimental on TestFlight)?

**Comment by sarthakpranesh** [comment]
Hey @diegolmello @gyverchang , I tested this on the current develop branch it looks like this issue has been resolved :smile:
