### ISSUE TITLE
library not found for -lBugsnagReactNative with iOS

### ISSUE THREAD

**Issue by jewom** [RocketChat/Rocket.Chat.ReactNative#1297]
Hello,

I have this error when I try to compile the app for iOS : 

```
ld: library not found for -lBugsnagReactNative
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't know why...

**Comment by djorkaeffalexandre** [comment]
@jewom What is your Xcode version?

**Comment by jewom** [comment]
I have the version 11.0 of XCode

**Comment by marianotribuj** [comment]
Hello! Any updates about this issue? Facing same problem. Xcode 11.1. Thanks

**Comment by jewom** [comment]
Hi, no nothing :/

**Comment by djorkaeffalexandre** [comment]
Hi @jewom , try it https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1321#issuecomment-544695200 and let me know if works

**Comment by djorkaeffalexandre** [comment]
@jewom It was fixed for you?

**Comment by jewom** [comment]
I will try it in 5 days, I'm in holidays for the moment.

**Comment by jewom** [comment]
I have the same problem :/

**Comment by jewom** [comment]
it's working thanks!

**Comment by djorkaeffalexandre** [comment]
Nice! 😁
