### ISSUE TITLE
Notification disregard sorting settings

### ISSUE THREAD

**Issue by 2disbetter** [RocketChat/Rocket.Chat.ReactNative#1301]
- Your Rocket.Chat Experimental app version: 1.20 
- Your Rocket.Chat server version: 1.3.2
- Device (or Simulator) you're running with: Moto G7 Power (Android 9)

When tapping on a notification the sorting conditions of the chat/channel list are ignored and erased . I for example sort alphabetically, by group, by favorites, and unread on top. When I tap on a notification these settings are erased and I have to re-set them.

**Comment by soundstorm** [comment]
Also applies to iPhone. But no need to re-set them, restart of the app loads the right settings, only when opened from an notification it is temporarily sorted wrong.

**Comment by diegolmello** [comment]
We'll take a look. Thanks!

**Comment by soundstorm** [comment]
The app is not releasable for iOS with this bug. This messes everything up.
