### ISSUE TITLE
Message attachment color not showing

### ISSUE THREAD

**Issue by tctovsli** [RocketChat/Rocket.Chat.ReactNative#1313]
- Your Rocket.Chat Experimental app version: 4.0.0.2084 - Not Experimental

- Your Rocket.Chat server version: 2.1.0
- Device (or Simulator) you're running with: Samsung S8

**Message attachment color not showing**
We have alerts posted to RocketChat from various sources, which is using attachment colors to show if a problem has occured (color RED) or if it is resolved (color GREEN).
This worked on the old Android client, and on the web/desktop client, but not on React Native. There is no colors.

**Comment by devyaniChoubey** [comment]
Can I work on this issue?

**Comment by diegolmello** [comment]
@devyaniChoubey Sure, but you don't have to ask nor flood our issues. Thanks.

**Comment by bencgreen** [comment]
Is there any progress on this issue?

**Comment by diegolmello** [comment]
@bencgreen not really. Can you open a PR?

**Comment by bencgreen** [comment]
I've never worked on React Native before but I have used React - I will have a look through the code, see if I can figure it out.

**Comment by djorkaeffalexandre** [comment]
@bencgreen Start the work doing a message with colored attachments on web client and try to reproduce the same behavior of colors on mobile.
It's more a non-implemented thing than a bug
