### ISSUE TITLE
No Readme information about setting up single server

### ISSUE THREAD

**Issue by ghtjiann4321** [RocketChat/Rocket.Chat.ReactNative#1314]
- Your Rocket.Chat Experimental app version: latest
- Your Rocket.Chat server version: latest
- Device (or Simulator) you're running with: Android Studio Emulator

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by reetp** [comment]
This repo is specifically for Issues with the React Native application, not general help or support.

For the server please read here:
https://rocket.chat/docs/
https://rocket.chat/docs/getting-support/
https://github.com/RocketChat
https://github.com/RocketChat/Rocket.Chat

**Comment by djorkaeffalexandre** [comment]
Check this out https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps.
