### ISSUE TITLE
Cannot go to message from Search

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1315]
- Your Rocket.Chat Experimental app version: 1.20.1.12048
- Your Rocket.Chat server version: 2.2.0-develop
- Device (or Simulator) you're running with: Samsung S9

Actual behaviour:

Go to Channel, Actions, Search
Enter search term
Results list
Try to click or long press results in no action

Expected behaviour:

Go to Selected message 

As a side note, there probably should be some 'Back' to return to the search result in case the message chose was the wrong one.

**Comment by reetp** [comment]
Possibly linked
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1010

**Comment by devyaniChoubey** [comment]
Can I work on this issue?

**Comment by devyaniChoubey** [comment]
@djorkaeffalexandre sir  a new screen should be created for displaying the messages or I can use the roomview.

**Comment by alleait** [comment]
Any plans on fixing this?

**Comment by AgentTNT** [comment]
This should also apply to pinned messages

**Comment by ankar84** [comment]
Must have functionality for search in mobile application!
Please implement that.

**Comment by diegolmello** [comment]
@ankar84 I agree.
We've been working more on encryption lately, but this feature is for sure on our plans.
Thanks.

**Comment by ankar84** [comment]
> @ankar84 I agree.
> We've been working more on encryption lately, but this feature is for sure on our plans.
> Thanks.

Yeah, I know about plan to implement e2e encryption, and I personally wait it more then Jump to message functionality (which is pretty important in Search)
So, thanks, @diegolmello that sharing your plans!
