### ISSUE TITLE
[BUG] - Missing / Hidden messages

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat.ReactNative#1316]
### Description:

When one user in our system writes a message from android RC Experimental so some other people (don't know if all of people in specific channel) including him can't see his messages in WebUI or RocketChat desktop apps but they can see this message in RC Experimental on phone. I don't know how to reproduce it or what's wrong but it has critical severenity for us.

### Expected behavior:

Messages are shown in all of available clients

### Actual behavior:

Some messages are not shown everywhere

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0.0
- Operating System: Servers are running on debain9/10
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.13

From his phone's  RC Experimental:
![image](https://user-images.githubusercontent.com/11560794/66314446-5a976600-e914-11e9-9146-208ef43a22be.png)

From his desktop app:
![image](https://user-images.githubusercontent.com/11560794/66314547-8581ba00-e914-11e9-8642-193739ead6a5.png)

From my desktop app:
![image](https://user-images.githubusercontent.com/11560794/66314611-97635d00-e914-11e9-9065-9084ef0f9348.png)

**Comment by djorkaeffalexandre** [comment]
@dusatvoj solved it for you with the latest beta?

**Comment by dusatvoj** [comment]
It seems solved now. I forgot to close it. Thank's @djorkaeffalexandre

**Comment by djorkaeffalexandre** [comment]
Nice! You're welcome! 😁
