### ISSUE TITLE
Crash immediately after the channel list is displayed.

### ISSUE THREAD

**Issue by chicchi7tmp** [RocketChat/Rocket.Chat.ReactNative#1323]
- Your Rocket.Chat Experimental app version: 1.20.1
- Your Rocket.Chat server version: 2.1.0
- Device (or Simulator) you're running with: Android9(Sharp SH-M10)

When the application is started with the server registered, the application crashes immediately after the channel list is displayed.

This event did not occur in the kotlin version.
This phenomenon occurs even in new accounts that do not register channels or direct messages.
Occurs even when multi-byte characters are not used in the site name.

Thank you

I'm sorry if I'm rude because English is not my native language.

**Comment by djorkaeffalexandre** [comment]
Hello @chicchi7tmp , can you give-me logs? If not, can you explain more about it? Your site name have multi-byte characters?

Thanks very much! ❤️

**Comment by chicchi7tmp** [comment]
Hello djorkaeffalexandre.

I'm not an android app developer so I don't know how to get logs. I'm sorry. Please give me a hint to get the logs.

Instead, when I crashed the app several times on my device, I was able to send logs with android's feedback function. (may be a feature of google play)
The time when the feedback was sent is around 1:30 JST, 24/10/2019. I wrote the title and number of this case in the feedback field. Can you receive logs this way?

>Your site name have multi-byte characters?
I guessed it was due to the presence of multibyte characters in the site name, but it was a mistake.
After changing the site name to alphabet only, I deleted the app storage data and tried again, but it crashed.

The device system language is ja-JP.

**Comment by djorkaeffalexandre** [comment]
Hello @chicchi7tmp , your server has `subpath` on url?
E.g.: `https://server.com/subpath`

**Comment by chicchi7tmp** [comment]
Hello djorkaeffalexandre.
yes.
https://chat.server.com:10443/chat/

**Comment by djorkaeffalexandre** [comment]
Oh ok! We make a new version with fix to this problem.
When you have subpaths on url it crashes the app..
Soon we launch the 1.20.2 release version!
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1322
Thx ❤️

**Comment by chicchi7tmp** [comment]
The fix was confirmed with Rocket.Chat Version 4.0.2.2087. The app not crash.
Thank you very much!😍
