### ISSUE TITLE
Not all uploads are successful

### ISSUE THREAD

**Issue by seasick** [RocketChat/Rocket.Chat.ReactNative#1325]
- Your Rocket.Chat Experimental app version:4.0.2.2087
- Your Rocket.Chat server version: 2.0.0
- Device (or Simulator) you're running with: Google Pixel 2

Basically the same as [this issue](https://github.com/RocketChat/Rocket.Chat.Android/issues/2507) but I realized that this is a _Rocket.Chat.ReactNative_ issue, thus created it here.

Looking at `adb logcat` I found this error when uploading (or pressing "try again")

```
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: Sending exception: SyntaxError - JSON Parse error: Unrecognized token '<' parse@[native code]
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: app.bundle:1345:3424
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: p@app.bundle:430:423
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: app.bundle:430:1740
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: p@app.bundle:430:423
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: n@app.bundle:430:898
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: app.bundle:430:1047
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: f@app.bundle:166:155
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: app.bundle:166:882
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: q@app.bundle:172:623
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: x@app.bundle:172:987
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: callImmediates@app.bundle:172:3068
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: callImmediates@[native code]
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: value@app.bundle:39:3188
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: app.bundle:39:1206
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: value@app.bundle:39:2868
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: value@app.bundle:39:1176
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: value@[native code]
10-24 11:36:17.787 21885 22007 I bugsnag-react-native: value@[native code]
```

Uploading images which were sent to me via Whatsapp are uploaded successfully. Photos I took on my camera are not uploaded successfully.

**Comment by aimador** [comment]
I was told to move to the React Native section since I have the same upload problem
["old" Android App #2507](https://github.com/RocketChat/Rocket.Chat.Android/issues/2507)

**Comment by djorkaeffalexandre** [comment]
@aimador where you is uploading? Share extension or Room View?

**Comment by aimador** [comment]
Sorry, I don't really know what you're referring to. I've opened either a channel or a private conversation and used the "+" next to the input field. I assume you're referring to the room view. I did not use any share functionality so far.

**Comment by djorkaeffalexandre** [comment]
@aimador Can you give-me your username on https://open.rocket.chat if you have?

**Comment by seasick** [comment]
I tried uploading today again, and this time uploading worked. This time I also was able to test from share extension and room view.

Android App Version: 4.0.6
RocketChat Server Version: 2.2.0

**Comment by aimador** [comment]
This is still an issue for me though. I guess I'll have to open another issue then
