### ISSUE TITLE
User still seeing v3.5.1 in Play Store

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.ReactNative#1326]
I first opened https://github.com/RocketChat/Rocket.Chat.Android/issues/2503, and was told to open here, so here goes:

## Describe the bug
User still seeing v3.5.1 in Play Store, even though 4.0.0 has been out for a while.

## To Reproduce
Have that user's device and open RC in the Play Store.

## Expected behavior
v4.0.0 would be available for download.

## Screenshots
![image](https://user-images.githubusercontent.com/295571/67297061-0edae400-f4f2-11e9-8c76-67742df1e13f.png)

![image](https://user-images.githubusercontent.com/295571/67296849-b7d50f00-f4f1-11e9-8b58-be68b653b4cb.png)

## Devices and Versions

As per screenshot.

**Comment by djorkaeffalexandre** [comment]
Hi @antgel, we haven't released v4.0.0 for all users. We're making a gradual release

**Comment by antgel** [comment]
@djorkaeffalexandre Ah, okay, thanks for the explanation. When will it be fully released, and how can users know this?

**Comment by djorkaeffalexandre** [comment]
You're welcome! We'll make a release tag on this repository when it is fully launched! 😁

**Comment by antgel** [comment]
Thanks again, following. Is this going to be a regular thing or just for the initial roll-out (replacing the Kotlin app)?

**Comment by djorkaeffalexandre** [comment]
I think it is only to replacement :)

**Comment by antgel** [comment]
Okay, thanks again, looking forward to full roll-out. The UX is so much improved over Kotlin, and I remember when this project started, you've done it in a pretty short time...

**Comment by djorkaeffalexandre** [comment]
You're welcome! We're here to you always.. :)
