### ISSUE TITLE
No bundle URL present Make sure you’re running a packager server or have included a .jsbundle file

### ISSUE THREAD

**Issue by MiaoMiaoai** [RocketChat/Rocket.Chat.ReactNative#1327]
- Your Rocket.Chat Experimental app version: 1.20.1.100
- Your Rocket.Chat server version: 2.1.1
- Device (or Simulator) you're running with: Simulator iPhone X

What are the following mistakes？
react-native run-ios  error:
<img width="277" alt="截屏2019-10-24下午8 42 28" src="https://user-images.githubusercontent.com/19339100/67487047-cbbe7380-f69f-11e9-821c-53f081c27af7.png">

**Comment by djorkaeffalexandre** [comment]
Hello @MiaoMiaoai , unfortunately we have an issue with react-native script, it not run metro bundler automatically and you need to run `yarn start` on project folder..

**Comment by djorkaeffalexandre** [comment]
@MiaoMiaoai fixed?

**Comment by MiaoMiaoai** [comment]
@djorkaeffalexandre Solved

**Comment by ani4aniket** [comment]
This issue is can be solved with running `yarn start` in project directory.

**Comment by hxkdidi** [comment]
please believe me ,just add  this line "127.0.0.1 localhost"  to /etc/hosts !!!!!!!

**Comment by shayelbaz1** [comment]
`npx react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'`
Try This 
and run.

**Comment by hxkdidi** [comment]
alternative solution is delete the hide file " .wacthmanconfig ",and run "npx react-native start"

**Comment by Asad-Kabir** [comment]
i got the solution by this article 
[https://onexlab-io.medium.com/no-bundle-url-present-fixed-ca2688a80f66](https://onexlab-io.medium.com/no-bundle-url-present-fixed-ca2688a80f66)

**Comment by BulletButcher88** [comment]
None of these solutions above work for me. I am still hunting to solve it...

**Comment by phamhieu1412** [comment]
same iss on react-native: 0.70.5, macos: 13.3, xcode 14.3, on 6splus ios 13.7. any solution for my issue??

**Comment by ritsuyan** [comment]
> same iss on react-native: 0.70.5, macos: 13.3, xcode 14.3, on 6splus ios 13.7. any solution for my issue??

have u resolve ?

**Comment by jaroslav009** [comment]
same

**Comment by mzfattal** [comment]
After a hour of struggle, disconnecting and reconnecting wifi worked for me

**Comment by cmaxdev** [comment]
watchman watch-del-all
yarn cache clean
yarn start --reset-cache

Please try this command. It will working well.
