### ISSUE TITLE
Unable to debug on iOS Simulator

### ISSUE THREAD

**Issue by marianotribuj** [RocketChat/Rocket.Chat.ReactNative#1328]
- Your Rocket.Chat Experimental app version: 1.20.0
- Your Rocket.Chat server version: 2.1.0
- Device (or Simulator) you're running with: Simulator Xcode 11.1

After updating the project to version 1.20.0 (I believe it's actually related to RN update from 0.59... to 0.60...); I'm unable to debug it anymore. When I open the contextual menu and select "Debug", the app reloads, and the simulator screen gets blank.

On the bundler the output is:

 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 DELTA  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 MAP  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 INFO  Running application RocketChatRN ({
    initialProps =     {
    };
    rootTag = 11;
})

On the React Native Debugger console there's only a warning:

ExceptionsManager.js:126 Warning: AsyncStorage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage

And the other logs are:

Running application RocketChatRN ({
    initialProps =     {
    };
    rootTag = 11;
})
on setUpDeveloperTools.js:73

[React DevTools] Connected

on /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/build/standalone.js:3 

Does anybody experience it? Any ideas how to solve it?

Thanks a lot!!

**Comment by djorkaeffalexandre** [comment]
@marianotribuj We use [Reactotron](https://github.com/infinitered/reactotron) to debug our project. :)
I'll try to fix default Debug on React DevTools.
Thx. :+1:

**Comment by marianotribuj** [comment]
Just something that might help, if I run Android emulator, the debug works well.

**Comment by marianotribuj** [comment]
> @marianotribuj We use [Reactotron](https://github.com/infinitered/reactotron) to debug our project. :)
> I'll try to fix default Debug on React DevTools.
> Thx. 👍

I think it would be great for new users, to have a small onboarding document with the tools "recommended" for working with Rocket.chat by the lead developers. For example, I've been building my forked version since may; and never needed to install cocoapods (to be able to do what you've recommended a couple days ago -pod install-).
If you want, just create a bulleted list of tools, and I offer myself to complete it with links, instructions, and so.
Thanks again!!

**Comment by phamhien2102** [comment]
I also have a same issue. Anyone fixed this?

**Comment by ljcp** [comment]
same here , not working for me

**Comment by ljcp** [comment]
this problem is related to the this line https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L28

`const appGroupPath = isIOS ? `${ RNFetchBlob.fs.syncPathAppGroup('group.ios.chat.rocket') }/` : '';`

that is immediately executed on app start , i replaced for testing the RNFetchBlob.fs.syncPathAppGroup with the current string path and the debug works! ( painful work)



i opened an issue on the rn-fetch-blob library https://github.com/joltup/rn-fetch-blob/issues/489

**Comment by phamhien2102** [comment]
> this problem is related to this line https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L28
> 
> `const appGroupPath = isIOS ? `${ RNFetchBlob.fs.syncPathAppGroup('group.ios.chat.rocket') }/ : '';`
> 
> that is immediately executed on app start , i replaced for testing the RNFetchBlob.fs.syncPathAppGroup with the current string path that syncPathAppGroup returns and the debug works!
> 
> the fix will be using RNFetchBlob.fs.pathForAppGroup instead the syncPath , will take a look to see if it's feasible to do the change and may a PR

Tks for your help. I also fixed by replacing to appGroupPath = "";

**Comment by ljcp** [comment]
@phamhien2102 you should write the string output of syncPathAppGroup meanwhile and not an empty one ""

**Comment by djorkaeffalexandre** [comment]
Fixed by #2439.
Thanks to figure out the error guys! :)
