### ISSUE TITLE
iOS error:Failed to open the database. unable to open database file: file  on the Real machine

### ISSUE THREAD

**Issue by MiaoMiaoai** [RocketChat/Rocket.Chat.ReactNative#1332]
- Your Rocket.Chat Experimental app version: 1.20.1.100
- Your Rocket.Chat server version: 2.1.1
- Device (or Simulator) you're running with: iPhone 7P
Running on a real machine error:
<img width="843" alt="截屏2019-10-29下午6 52 32" src="https://user-images.githubusercontent.com/19339100/67761018-67275e00-fa7d-11e9-86f7-4fe9ea5e075a.png">
<img width="886" alt="截屏2019-10-29下午6 52 38" src="https://user-images.githubusercontent.com/19339100/67761023-6a224e80-fa7d-11e9-8af0-24c5fe26d248.png">

**Comment by djorkaeffalexandre** [comment]
@MiaoMiaoai it should fixed by https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1322 .
Can you confirm?

**Comment by MiaoMiaoai** [comment]
@djorkaeffalexandre  If I change my Bundle ID run on a real machine , I will report an error.

**Comment by MiaoMiaoai** [comment]
<img width="682" alt="截屏2019-10-29下午8 07 33" src="https://user-images.githubusercontent.com/19339100/67765854-0ea98e00-fa88-11e9-9ddd-6387d27f8463.png">
<img width="669" alt="截屏2019-10-29下午8 07 48" src="https://user-images.githubusercontent.com/19339100/67765855-10735180-fa88-11e9-8320-38522a957e0d.png">
<img width="523" alt="截屏2019-10-29下午8 07 57" src="https://user-images.githubusercontent.com/19339100/67765859-12d5ab80-fa88-11e9-981e-01cfdbe1d2b9.png">

**Comment by djorkaeffalexandre** [comment]
You need to change here to your App Group Identifier: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L28

**Comment by MiaoMiaoai** [comment]
@djorkaeffalexandre  Thank you very much for solving my problem.

**Comment by bradroid** [comment]
@djorkaeffalexandre Can you explain your solution more, why doesn't it work without this modification? Can we include the fix into the base code? Can we add this to whitelabeling documentation?

**Comment by zeeshanwarriach93** [comment]
> You need to change here to your App Group Identifier: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L28
Hi can you help me with this?
Do I have to change this
const appGroupPath = isIOS ? appGroup.path : '';
to

const appGroupPath = isIOS ? appGroup.path : 'group.com.example.app';

something like that?

**Comment by djorkaeffalexandre** [comment]
@bradroid @zeeshanwarriach93, not exactly, if you don't have an App Group configured you'll need to set App Group Path as an empty string.
Check these steps and make sure you've followed this things on the right way, so you don't need to change anything into the code.
https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#general-setup
We're reading the App Group identifier from each target `Info.plist` and generating the app group folder path based on it, this is need to the database be shared between our targets/extensions (Share Extension, Notification Extension, Main App).

**Comment by bradroid** [comment]
@djorkaeffalexandre I have followed whitelabeling guide and have app groups setup. Does that mean that I don't need to modify `app/lib/database/index.js`?

I'm getting this error:

`Fatal error: Failed to open the database. unable to open database file: file WatermelonDB/Database.swift, line 19`

**Comment by nxa127** [comment]
same problem here

> You need to change here to your App Group Identifier: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L28

@djorkaeffalexandre i having same isssue, can you show me example code for this issue ?

**Comment by bradroid** [comment]
I fixed the issue on my side. The problem for me was that my App Group Identifier definition in "Signing & Capabilities" got out of sync from the one defined in `Info.plist`. Make sure both are using the same value.

**Comment by nxa127** [comment]
@bradroid thank for your help

**Comment by raghav-khunger** [comment]
These two settings should match:

![image](https://user-images.githubusercontent.com/904902/105362040-677ebc80-5c20-11eb-88fe-ea89f1eca86e.png)


![image](https://user-images.githubusercontent.com/904902/105362100-79605f80-5c20-11eb-8b11-93c30a2999da.png)

**Comment by Salmankhan033** [comment]
@MiaoMiaoai how did you fix it?

**Comment by Salmankhan033** [comment]
> https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L28

not found 
?
