### ISSUE TITLE
Slash added at the end of CAS login URL

### ISSUE THREAD

**Issue by lucasPereira** [RocketChat/Rocket.Chat.ReactNative#1333]
- Your Rocket.Chat Experimental app version: 1.20.1
- Your Rocket.Chat server version: 0.72.3
- Device (or Simulator) you're running with: Moto G Play (Android 7.1.1)

Authentication with CAS does not work in the app. The mobile app adds a slash at the end of the CAS login URL. The slash breaks the redirection to the CAS server authentication page.

## Example:

Site URL setting: `https://myrocketchat`
CAS login URL setting: `https://mycasserver/login`
URL in web version:  `https://mycasserver/login?service=https://myrocketchat`
URL in mobile version: `https://mycasserver/login/?service=https://myrocketchat`

The slash added after `/login` in the mobile app breaks the redirection to the CAS server authentication page.

**Comment by diegolmello** [comment]
Was this fixed by #1362?

**Comment by lucasPereira** [comment]
> Was this fixed by #1362?

Yes, thank you ;-)
