### ISSUE TITLE
[TESTS] Add markdown to storybook

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1334]
We should write stories to ensure markdown is working properly.

**Comment by sarthakpranesh** [comment]
I would like to work on this issue. Can I know more about what exactly is required to be done?
Warm Regards

**Comment by diegolmello** [comment]
@sarthakpranesh You have to add all markdown variations on Storybook.

**Comment by sarthakpranesh** [comment]
Ok, so can you guide me about where should I start.

**Comment by diegolmello** [comment]
You should write tests for the [Markdown](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/markdown/index.js) similarly to what we did on Message here:
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/storybook/stories/Message.js
