### ISSUE TITLE
Clicking user avatar in thread previews crashes app

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#1348]
- Your Rocket.Chat Experimental app version: 1.20.2.12349
- Your Rocket.Chat server version: 2.3.0-develop
- Device (or Simulator) you're running with: Note 10+ 5g

**Video of the crash:**
https://open.rocket.chat/channel/react-native?msg=kc4533XKJoaQFfrMX

**Steps to reproduce:**
1. Open a channel
2. Click the discussions button to see all the threads/discussions in the channel
3. Click on a user's avatar
4. Crash

**Comment by ankar84** [comment]
I reproduced that bug. Even if user has not avatar, App will crash the same way.
