### ISSUE TITLE
Can't open #sandbox channel on open

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#1349]
- Your Rocket.Chat Experimental app version: 1.20.2.12349
- Your Rocket.Chat server version: 2.3.0-develop
- Device (or Simulator) you're running with: Note 10+ 5g

**Video of the issue:**
https://open.rocket.chat/channel/react-native?msg=W6yZmfG8GEe4pqyHY

**Steps to reproduce:**
1. Try to join #sandbox on open
2. ![wait forever](https://media.giphy.com/media/o5oLImoQgGsKY/giphy.gif)

![7ib5wxsjwF](https://user-images.githubusercontent.com/6295044/67913007-1dfd0a00-fb62-11e9-9343-490f948cc67f.gif)

**Comment by ankar84** [comment]
I do not confirm that bug.
I did successfully joined to #sandbox using Rocket.Chat Experimental app version 1.20.2.12349
And leaved a message with no problems.
Device (or Simulator) you're running with: Xiaomi Redmi Note 4x

**Comment by djorkaeffalexandre** [comment]
It doesn't looks like happens anymore.
If someone experience this, open a new issue, please.
Thanks.
