### ISSUE TITLE
HTTP redirection not supported

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat.ReactNative#1353]
- Your Rocket.Chat Experimental app version: 4.0.2
- Your Rocket.Chat server version: 1.3.2
- Device (or Simulator) you're running with: Pixel 2 / Android

App does not respect HTTP 30x redirects. For example, if I try to connect with the server URL "https://mysite.net", which we always redirect to "https://www.mysite.net", I won't be able to get past the login screen. In this case we always redirect non-www to www. The same would be the case if we redirected HTTP to HTTPS (which we do as well).

Can the app be updated to handle/support redirects based on the initial server URL?

**Comment by sistason** [comment]
I was looking for this issue and found it here...
Is there any idea on when you support this? I have a rocketchat-server I want to move to a different URL, which is apparently a thing I cannot do, as my users would just sit in front of the app not connecting and just... leave?

**Comment by JoshMcCullough** [comment]
Was this closed because it's fixed? @diegolmello
