### ISSUE TITLE
CAS Login adds / to the given login url

### ISSUE THREAD

**Issue by Kusig** [RocketChat/Rocket.Chat.ReactNative#1354]
See the following issue here as well, it is the same:  https://github.com/RocketChat/Rocket.Chat.Android/issues/2513

## Description
Connection via CAS Login page doesn't work anymore.  This was working for a long time without problems but with the newest versions of the mobile apps (Android app and Experimental app) there is a problem. 

Analysis of our experts showed that since some time, the apps seesm to add a Slash / behind the LoginUrl itself what causes the problem.

eg. in our case the forward address given on login is:  "/authservice-radius/login"

But the apps do call then:   "/authservice-radius/login/" which doesn't work. 

So it looks as within the app there is somewhere a slash added but it shouldn't.

Note that the Desktop app and as well Browser access do work without problems. this only concerns the mobile apps.

## Devices and Versions
Androis Samsung S8 with Android 9 but it is on all Android devices a problem. We don't know about iOS.

Your Rocket.Chat.Android version: 4.0.2
Experimental :   1.20.1
Your Rocket.Chat Server version:  2.2.0

## Steps to reproduce
1) Configure CAS Login on the server properly (as mentioned above, it works perfect within browser or Desktop App.

2) On Android App login with server address and choos CAS Login, this causes the problem and a error page is shown from the CAS Login server.

**Comment by diegolmello** [comment]
@Kusig Can you reach me on https://open.rocket.chat? I'm `@diego.mello`.
I'll take a look on this ASAP!

**Comment by nicolas63** [comment]
I have the same issue. When the pull request will be closed ?

**Comment by diegolmello** [comment]
@nicolas63 According to @Kusig, that PR doesn't fix the issue.
DM me and I send you a build for you to test.
Thanks.

**Comment by diegolmello** [comment]
It's fixed, according to @nicolas63.
