### ISSUE TITLE
Cannot connect to server secured with .htaccess

### ISSUE THREAD

**Issue by redw0lf** [RocketChat/Rocket.Chat.ReactNative#1355]
- Your Rocket.Chat Experimental app version: 4.0.2.2087
- Your Rocket.Chat server version: 2.1.0
- Device (or Simulator) you're running with: One Plus 6

Using the current experimental version of the app available in the Play Store I cannot connect to our server, which is behind a login with user password configured via .htaccess.
The URL I enter in the connection part is `https://username:password@serverurl.tld`

The error I get after trying to connect is: `The URL you entered is invalid. Check it and try again, please`

If I see it right, currently the regular expression for adding a new server does not accept http basic auth to be included in the URL.
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/ae949e6d681e4da35fac7066b74748eba3c8134f/app/views/NewServerView.js#L185

The following regular expression 
`(https?:\/\/)?((.+?):(.+?)@)?(((\w|[0-9-_])+(\.(\w|[0-9-_])+)+)|localhost)(:\d+)?$`

is accepting a URL with user and password information (e.g, `https://username:password@serverurl.tld`)
Hope this helps

**Comment by slimlv** [comment]
same with  Rocket.Chat Experimental app version: v4.4.0 (14335)
Basic Auth was available in Rocket.Chat.Android, see https://github.com/RocketChat/Rocket.Chat.Android/issues/1727

**Comment by djorkaeffalexandre** [comment]
Hey @slimlv and @redw0lf.
Can reach me on `https://open.rocket.chat`?
My username is `djorkaeff.alexandre`.
I'm working on it now.

**Comment by slimlv** [comment]
I would like to clarify that there may be two usage cases:
# basic auth as separate security level PRIOR rocket chat own authentication
# basic auth as native rocket chat authentication

this ticket about the first case, where basic auth is separate level of security and does not authentice into rocket.chat
