### ISSUE TITLE
Crash on scrolling back long thread

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1357]
- Your Rocket.Chat Experimental app version: 1.20.2-screens-disabled.999999999
- Your Rocket.Chat server version: open.rocket.chat - 2.3.0-develop
- Device (or Simulator) you're running with: Samsung S9

As per discussions with Diego. Bug report sent.

Go to thread
Scroll back fairly quickly
Crash.........

Here's a recent one that crashes or locks.

https://open.rocket.chat/channel/support?msg=TJbs2N7bQncyEHo8x

(4.0.2 seems to just lock)

**Comment by djorkaeffalexandre** [comment]
Can't reproduce it here anymore, if the problem persists, open a new issue.
Thanks.
