### ISSUE TITLE
[Feature] Support for fingerprint scanner

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.ReactNative#1358]
Signal and Whatsapp have a feature that allows to add additional fingerprint scan check before accessing the app. Face ID would be also a nice option if fingerprint scanner is not available. In case of loosing possibility to authenticate there should be an fallback to authenticate using PIN or user password. 

an article that I've found looking for examples is React Native: https://blog.theodo.com/2018/04/add-touch-id-react-native-app/

**Comment by ankar84** [comment]
Nice security feature, I think it worth adding.

**Comment by Prateek93a** [comment]
@diegolmello If nobody is working on this, can I take it up? I have implemented a very basic version  of the feature.

using fingerprint-->
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/44807945/69875502-4bfd7780-12e3-11ea-8f36-27575200634a.gif)


using pin-->
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/44807945/69875505-4e5fd180-12e3-11ea-9cc3-3daa303ede70.gif)

**Comment by djorkaeffalexandre** [comment]
@Prateek93a You can work on this! Very nice basic version! I liked it! :)

**Comment by Prateek93a** [comment]
@djorkaeffalexandre Thanks a lot Sir! So Sir, I was thinking that there will be an option 'Enable TouchId' in the settings menu. If user enables it then he/she will be asked to enter a Pin for fallback. That pin will be stored on the user's device itself. Am I right on this?

**Comment by diegolmello** [comment]
We're going to implement E2E encryption in a few months.
We should postpone this feature to after E2E so we can reuse the same encryption methods.

**Comment by Prateek93a** [comment]
@diegolmello Ok Sir

**Comment by Nemental** [comment]
Just to link the "old" Issues :)
https://github.com/RocketChat/Rocket.Chat.iOS/issues/2686
https://github.com/RocketChat/Rocket.Chat.Android/issues/2302
@diegolmello I am happy to hear that the implementation of E2E is not as far as I expected it to be.

**Comment by djorkaeffalexandre** [comment]
It was done by #2059.
Closing.
