### ISSUE TITLE
Running the project linking issue.

### ISSUE THREAD

**Issue by Shing-Ho** [RocketChat/Rocket.Chat.ReactNative#1364]
- Your Rocket.Chat Experimental app version: recent version. https://github.com/RocketChat/Rocket.Chat.ReactNative develop branch 2019-11-1
- Your Rocket.Chat server version: original server
- Device (or Simulator) you're running with: iPhoneX

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

I am getting issue while running the project in iOS part.

```
JitsiMeet compiled with newer version of Swift language (unknown ABI version 0x07) than previous files (unknown ABI version 0x06) file '/Volumes/DATA/Work/Mobile/ReactNative/rocket.chat.reactnative/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried like this.
git clone ...
yarn
cd ios
sudo gem install cocoapods 1.6.2
pod install
cd ..
react-native run-ios

and also bitcode is false and remove the deliver data location folder and rebuild.
But not working please anybody help me asap.
Thank you

**Comment by djorkaeffalexandre** [comment]
Hi @Shing-Ho , what is your Xcode version?

**Comment by Shing-Ho** [comment]
Xcode versino is 10.1

**Comment by djorkaeffalexandre** [comment]
Hmm ok, can you try with version 10.3 or higher?

**Comment by diegolmello** [comment]
I think it should be even 11 or higher

**Comment by Shing-Ho** [comment]
Thank you.
I think you should add this requirement into README.md
