### ISSUE TITLE
Cannot add custom rocket.chat server

### ISSUE THREAD

**Issue by gkrauze** [RocketChat/Rocket.Chat.ReactNative#137]
I have an adding server issue.
I downloaded application from Android Store and I cannot add an url to my own rocket chat server, which is perfectly working with regular - cordova application. I receive an error "is not a valid rocket chat instance". The only server that is correct is https://open.rocket.chat.

Maybe there is something that as an user I can do? Or maybe it is an issue in this app.

Regards.

**Comment by ggazzo** [comment]
hey @gkrauze, which version of rocketchat are you using?

**Comment by SimJoSt** [comment]
I have the same issue.
The server is running 0.62.2.
Rocket.Chat and Rocket.Chat+ connect to it without any problems.
But using the ReactNative app I get `is not a valid Rocket.Chat instance`

**Comment by integras** [comment]
Same here: Server 0.63.3

**Comment by seasick** [comment]
Got the same problem but was able to track it down: The `testServer` function in https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/rocketchat.js#L86 checks for `x-instance-id` header which isn't available in `response.headers`. Instead there is a `X-Instance-ID` header.

I replaced it for testing with `X-Instance-ID` and I was able to connect to our server. Not sure though if this is a problem with my development setup or our chat server setup.

**Comment by diegolmello** [comment]
@seasick Weird. Let's add Aaron to discussion.
@geekgonecrazy What do you think about these `x-instance-id` and `X-Instance-ID` string cases? Should I add another text case test, it's his server configuration or it's a RC bug?

Thanks.

**Comment by seasick** [comment]
@diegolmello, works like expected - i.e. the server is now validating correctly

**Comment by diegolmello** [comment]
@geekgonecrazy No problem. It's working now. Thanks 👊

**Comment by 1st8** [comment]
Since this issue is fairly recent, I want to add that connection to a server running under a path, e.g. `https://example.org/chat`, is not possible. It seems this is only due to the Regex.

When issuing the HEAD request to my chat url, it returns the X-Instance-ID correctly, though the app says that it is not a valid Rocket.Chat instance.

Maybe just remove `$` from the regex?

**Comment by himpierre** [comment]
Hello.

Ran into the same problem. Just tried with rocketchat 0.68.0-rc0. Header is still upper case. Workaround for my nginx setup:

```
add_header x-instance-id $upstream_http_x_instance_id;
```

**Comment by seasick** [comment]
@himpierre I believe no changes were made at RocketChat itself, only how the ReactNative client is handling the x-instance-id header.
