### ISSUE TITLE
Unable to upload avatar through the app

### ISSUE THREAD

**Issue by mar-v** [RocketChat/Rocket.Chat.ReactNative#1370]
- Your Rocket.Chat app version: 4.0.3 for official and 1.20.1-jitsi-bb12048 for Experimental
- Your Rocket.Chat server version: 2.0.0 (same with 2.2.0)
- Device (or Simulator) you're running with: HomTom HT70

Uploading a picture in the profile settings seems to do nothing. Steps to reproduce
1. Open the app -> Profile
2. Tap on the cloud icon to upload a new pic.
3. Select a pic form local directory, tap the check mark to approve the upload. 
4. Back to Profile page - nothing has changed, the button "Save changes" is greyed out.
5. Uploading using the link works just fine. 

Expected behaviour: after step 3 the button "Save changes" should be clickable and the new picture should appear as avatar, as it does on the desktop app, for example. 

Same thing with both apps (official and Experimental one)

**Comment by rasos** [comment]
This would not fix #441, but would make it less relvant.

**Comment by Aaryan-kapur** [comment]
May I work on this?

**Comment by djorkaeffalexandre** [comment]
Looks like it's working fine now, when you select a new image, the button to save is enabled. :)
Thanks @mar-v. 🤗
