### ISSUE TITLE
[Improvement][UX] Better integration of Twitter links in Rocket (server and app)

### ISSUE THREAD

**Issue by bensarthou** [RocketChat/Rocket.Chat.ReactNative#1374]
- Your Rocket.Chat Experimental app version: Rocket.Chat Experimental 1.20.2
- Your Rocket.Chat server version: 2.1.0
- Device (or Simulator) you're running with: Windows, Firefox (similar behaviour on all platforms)

I recently have gone from Slack to Rocket.Chat, and one thing that I think could be missing is proper, readable integration of tweets into channels. 

# Rocket App integration
In Rocket.Chat Experimental app (and standard one), a link of a tweet appears in the following form: 
on top, an image if one is embedded in the tweet, picture of the Twitter user if not, 
then below, in bold blue, the name of the user, and then only a small overview of the text of the tweet, **often incomplete and in gray so not really readable**

### Example of Rocket app integration
<img src="https://user-images.githubusercontent.com/37699244/68474933-09d2a000-0227-11ea-87e5-a8b7d6a3138f.jpg" width="225" height="250" />

In Web interface, the message is as such: 
Image of the user on the left, with on the right: "twitter.com" (not really useful...), the name of the account, and in grey, (incomplete) overview of the text. Furthemore, images often could not be prompted (at least on Firefox)

### Example of Rocket web integration
<img src="https://user-images.githubusercontent.com/37699244/68474934-0a6b3680-0227-11ea-93ad-ab0e7b89140f.png" width="1000" height="150" />

# Issue and solution
All those formats don't allow to read the tweet without clicking on the link and opening Twitter, which can be a pain. (idem if a video is embedded in the tweet, but I can understand that's more complicated)

If possible, integration similar to what can be found in Slack (for exemple) seems to me like a more "readable" version, avoiding Rocket users to go to Twitter. 
In a "quote-style" with a gray bar on the left: 
- user icon and user name in really small font
- full text of the tweet below
- image (if there is one) in full below

### Example of Slack App integration
<img src="https://user-images.githubusercontent.com/37699244/68474935-0a6b3680-0227-11ea-9240-a2c0528d6c7c.jpg" width="200" height="250" />

### Example of Slack Web integration
<img src="https://user-images.githubusercontent.com/37699244/68474937-0a6b3680-0227-11ea-9948-69e64e8664c2.png" width="300" height="250" />

I have to stress that Slack Twitter integration is only here as example, and better-UX integrations could be thought of, it's only here as an example of possible improvement.

**Comment by ghalestrilo** [comment]
I want to work on this. Has there been any progress yet?
