### ISSUE TITLE
Is development gonna cease for Rocket.Chat.iOS too?

### ISSUE THREAD

**Issue by EdPalmeira** [RocketChat/Rocket.Chat.ReactNative#1388]
The README file for Rocket.Chat.Android says development has ceased and Rocket.Chat mobile is moving to Reactive Native.

Are you guys gonna do the same for Rocket.Chat.iOS?

If so, when?

I am asking because I need to decide which one to adopt for a project in our company.

**Comment by diegolmello** [comment]
@EdPalmeira Yes, we are moving everything to React Native.
Check this blog post: https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/
