### ISSUE TITLE
[BUG] prune messages are still displayed

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.ReactNative#1390]
- Your Rocket.Chat Experimental app version: 4.0.5
- Your Rocket.Chat server version: 2.1.1, 2.2.0
- Device (or Simulator) you're running with: OnePlus 7 Pro (Android 10), BQ Auqaris X5 Plus (Android 7.7.1)

If all messages in a channel with `prune messages` function are completely deleted from another client (e.g. desktop client, browser), they are still displayed on the app.

Logout and re-login refreshes the room correctly.

see also https://github.com/RocketChat/Rocket.Chat.Android/issues/1754

**Comment by localguru** [comment]
And even worse: the first posted message after pruning from another client is not displayed on the mobile app. Seen on two different servers 2.1.1 and 2.2.0.

**Comment by diegolmello** [comment]
Prune is not implemented yet.

**Comment by localguru** [comment]
> Prune is not implemented yet.

Hmmm ... I thought prune is a server feature. So if I prune a channel eg. via browser the channel in the app should be updated.

**Comment by diegolmello** [comment]
Fixed by #1399
