### ISSUE TITLE
[BUG] single deleted messages are still displayed

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.ReactNative#1391]
- Your Rocket.Chat Experimental app version: 4.0.5
- Your Rocket.Chat server version: 2.1.1, 2.2.0
- Device (or Simulator) you're running with: OnePlus 7 Pro (Android 10), BQ Auqaris X5 Plus (Android 7.7.1)

Single deleted messages from another client (e.g. desktop client, browser) are still displayed on app.

Logout and re-login refreshes rooms correctly.

see also https://github.com/RocketChat/Rocket.Chat.Android/issues/1754

**Comment by diegolmello** [comment]
Fixed by #1399
