### ISSUE TITLE
Settings screen does not show server version ([missing {{version}} value])

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#1397]
- Your Rocket.Chat Experimental app version: 1.22.0.12660
- Your Rocket.Chat server version: 2.2.0
- Device (or Simulator) you're running with: Note 10+ 5G

![Screenshot_20191118-123547](https://user-images.githubusercontent.com/6295044/69076057-a142aa80-0a00-11ea-8b7a-3820b24cd974.jpg)

**Comment by localguru** [comment]
Don't see that here.

![Screenshot_20191118-201926](https://user-images.githubusercontent.com/8544984/69083014-96f4d080-0a41-11ea-92b3-4ba7a62e620e.jpg)

![Screenshot_20191118-202157](https://user-images.githubusercontent.com/8544984/69083015-978d6700-0a41-11ea-9950-1f8a36fceee5.jpg)

**Comment by localguru** [comment]
Ah, I do see that on open.rocket.chat too, right. See https://open.rocket.chat/api/info

```
{"version":"2.3.0-develop","success":true}
```
May be it's because the version number contains "-develop"

**Comment by wreiske** [comment]
![image](https://user-images.githubusercontent.com/6295044/69091497-6d737f00-0a18-11ea-8009-65b7df67c9f6.png)

This also happens on other production servers. Looks like the fix was merged in. https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1392

**Comment by localguru** [comment]
That might be a refresh problem. I do see that on my server too, if I change to open.rocket.chat and then go back to my server. Then there is no version number for my 2.2.0 server. If I close the app and restart it and then first go to my server, the version number is displayed correctly again.

**Comment by localguru** [comment]
It happens, if you switch on the app between different servers. This first server version is displayed correctly (open.rocket.chat too) and then after the first switch to another server any server is shown with a "missing" server version. Looks like a refresh bug.

**Comment by diegolmello** [comment]
Fixed by #1392
