### ISSUE TITLE
[QUESTION] Replace "Read-Unread" and "Star-Unstar" with pictograms

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.ReactNative#1405]
- Your Rocket.Chat Experimental app version: 1.24.0.12754
- Your Rocket.Chat server version: 2.2.0
- Device (or Simulator) you're running with: Xiaomi Redmi 3

Hey. When translating, I was faced with the fact that the slide menu "Read-Unread" and "Star-Unstar" look very ugly when translated into Russian (into German too). Is it possible to replace the inscriptions with pictograms, or at least make the text look more presentable?

![Screenshot_20191120-092536~2](https://user-images.githubusercontent.com/18574776/69214716-b93d3a00-0b78-11ea-8c40-64bbc6a0ea7f.jpg)
![Screenshot_20191120-092626~2](https://user-images.githubusercontent.com/18574776/69214730-be9a8480-0b78-11ea-881a-537d850689a7.jpg)

**Comment by Prateek93a** [comment]
@Pitstopper I think doing something with the text would be better because showing just pictogram might cause confusion in interpretting them.

**Comment by diegolmello** [comment]
@brunosquadros What do you think?
