### ISSUE TITLE
stable single-server release

### ISSUE THREAD

**Issue by HamzaKhait** [RocketChat/Rocket.Chat.ReactNative#1407]
Hello,

I'd like to download the latest stable **single-server** version of Rocket.Chat.ReactNative. 
Is the single-server branch up-to-date ?

Thanks
Hamza

**Comment by diegolmello** [comment]
Updated to match master on https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/b77438b79b98ec72380578019eec0d9172fcd9e7
