### ISSUE TITLE
Implement E2E encryption

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.ReactNative#141]
https://github.com/RocketChat/Rocket.Chat/pull/7181

**Comment by stukev** [comment]
Is there a reason why this isn't even listed in the "current priorities" list on the project start page? It's a pretty important feature.

**Comment by Born-of-dream** [comment]
Can y’all stop being lazy and add encryption for iOS devices. Tf is your problem?

**Comment by camillagds** [comment]
Updates? :smile:

**Comment by diegolmello** [comment]
It's planned for Q3/2020.

**Comment by hp734** [comment]
This is my #1 wished feature. Please implement soon.

**Comment by gwkerr** [comment]
Is there any way I could help implement this?
