### ISSUE TITLE
Click a notification, it didnt go to the detail (channel)

### ISSUE THREAD

**Issue by phamhien2102** [RocketChat/Rocket.Chat.ReactNative#1411]
I faced the issue that user clicks a notification, but it didn't go to detail (channel) while app is closed...I dont know everyone who face this issue? Anyone can help me? I am testing on android.

I download the latest new version of rocket chat...

**Comment by diegolmello** [comment]
@phamhien2102 App version?

**Comment by phamhien2102** [comment]
> @phamhien2102 App/server version?

My Rocket.Chat Experimental app version: 1.21.0
My Rocket.Chat server version: 2.2.0

**Comment by diegolmello** [comment]
Update your app to the latest version and try again.
