### ISSUE TITLE
Cant save Images

### ISSUE THREAD

**Issue by corincorvus** [RocketChat/Rocket.Chat.ReactNative#1416]
Hi,

If i Show in a Image and hold my Finger on it, a menu comes up to save the Image. After k click on save to Album, the Image didnt save on Smartphone.

Android Version: 4.0.6.2092
(Rocketchat and Rocketchat Experimental tested)
Server Version: Univention 2.2.0

**Comment by diegolmello** [comment]
Duplicated of #888
