### ISSUE TITLE
Android 8 &  10 - ldap - invalid credentials

### ISSUE THREAD

**Issue by CarlJKashnier** [RocketChat/Rocket.Chat.ReactNative#1421]
Server is using ldap auth. I am attempting to login via Android App 4.0.X (current version on play store).

It returns credentials invalid.

I can log in using android app 3.5.0 - I can log in with desktop app, I can log in via web access using the same credentials.

We have the latest snap (it seems to be about a month old).

It would seem that it is likely in the login authentication on the latest version of the app maybe not using the certificates correctly.

Steps to reproduce:
Attempt to login to a rocket chat with ldap server auth using current android client.

Expected behavior:
Being able to log in

Actual behavior:
Returning credentials rejected

Server Setup Information:
Version of Rocket.Chat Server: Latest
Operating System: Linux
Deployment Method: Snap
Number of Running Instances: 1
DB Replicaset Oplog: ?
NodeJS Version: ?
MongoDB Version: ?
Client Setup Information
Desktop App or Browser Version: Android App 4.0.X (current version on play store). Reproduced on Moto G5 Plus Android 8 & Pixel 4 Android 10.
Operating System: Android 8 & 10

Ref 15868 on core repo.

I will see what I can get in terms of logs - not sysadmin.

**Comment by diegolmello** [comment]
Hi, @CarlJKashnier! 
Can you reach me at https://open.rocket.chat?
I'm `@diego.mello`.
Let's fix this.

**Comment by phriedrich** [comment]
@diegolmello Did you get more details here?

We also use LDAP and have no problem logging in with the latest version of the app on Android.

**Comment by diegolmello** [comment]
@phriedrich Nope, so I'm closing now.
