### ISSUE TITLE
[Feature] Show the list of users who have read the last message

### ISSUE THREAD

**Issue by lequy1010** [RocketChat/Rocket.Chat.ReactNative#1426]
Hi,
Rocket.Chat is a good flatform for chatting,
Can Rocket.Chat add a feature that displays the list of users who have read the last message?
Example:
![image](https://user-images.githubusercontent.com/7949193/69772308-2298fa80-11c2-11ea-9299-ad73a79933d7.png)

**Comment by diegolmello** [comment]
We call it Read Receipt and it was implemented here: #975
Check the main repo to know how to enable it.

**Comment by lequy1010** [comment]
> We call it Read Receipt and it was implemented here: #975
> Check the main repo to know how to enable it.
your mean is calling to API to get the list of reas receipt?
I want to auto show the that list when have any user read message.
(same show list of reactions when have any user react)
