### ISSUE TITLE
Version 4.x regression : wrong Username displayed in all Direct Message rooms

### ISSUE THREAD

**Issue by didierm** [RocketChat/Rocket.Chat.ReactNative#1427]
(copied from issue in deprecated repo : https://github.com/RocketChat/Rocket.Chat.Android/issues/2518)

## Describe the bug
In the Android **v4.x.x** app, an identical, wrong username is displayed for all users.

Both **Android v3.5.0** and **iOS v3.5.1** display corrrect usernames.

## To Reproduce
1. Go to 'Direct Message' room
2. Click on '...' (3 dots)
3. [Name] and [Avatar] fields are correct
4. [Username] field displays an incorrect value, which is identical for all users.
5. When clicking on the Avatar, the Room Info screen displays the correct Username value

## Expected behavior
Show the correct [Username]  for all users

## Screenshots

* Actions : 

![image](https://user-images.githubusercontent.com/989004/68844283-d5009600-06c9-11ea-834d-3c69888517a3.png)

* Room Info : 

![image](https://user-images.githubusercontent.com/989004/68844514-39bbf080-06ca-11ea-8959-5db5b3f9ac86.png)

## Devices and Versions
Your Rocket.Chat.Android version: 4.0.5
Your Rocket.Chat Server version: 2.2.0

## Additional context
The issue occurs for **all** users (both LDAP & email-registered).

**Comment by Prateek93a** [comment]
@didierm Is this an issue with the react native client or the android client only , because I am not able to reproduce the issue on the experimental version of react native client.

**Comment by didierm** [comment]
@Prateek93a For testing purposes, we installed the react native client on a couple of Android clients/smartphones.

* This issue **_never_** occurs : 
   * with the Electron desktop client (latest v2.7.2, but it did not occur with previous versions either)
   * in a Web GUI session (current Rocket.Chat server backend : v2.2.0).

* This issue is _(partly, see below)_ reproducible with both : 
  * the original Android client (chat.rocket.android 4.1.0)
  * the experimental React Native client (chat.rocket.reactnative 4.2.0)

Concerning the Android clients (not tested with iOS) : 
* on one client/smartphone, it reproducibly occurs with both chat.rocket.android and chat.rocket.reactnative (with different RC accounts, and even after clearing all data of both apps and retrying) ;
* on a second client, it occurs with chat.rocket.android, but not with chat.rocket.reactnative ;
* on a third client, it currently does not occur with chat.rocket.android nor with chat.rocket.reactnative (while it did occur in the past with chat.rocket.android).

**Comment by Prateek93a** [comment]
@didierm  Ok,now I got it. Thanks for the update

**Comment by sarthakpranesh** [comment]
@Prateek93a @didierm is this issue resolved if not, can you let us know what device did you use @didierm. 
Warm regards

**Comment by didierm** [comment]
@Prateek93a @sarthakpranesh This still an issue with chat.rocket.reactnative v4.5.1, today tested with Xiaomi Mi9T.
We tested & reproduced previously with several different Android devices (see https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1427#issuecomment-568722042), and have no reason to believe this is linked to a specific device.

**Comment by djorkaeffalexandre** [comment]
Hello @didierm!
Can you reach me on `https://open.rocket.chat` with some test credentials to your server, my username is `djorkaeff.alexandre`.
We can't reproduce this here, maybe this is some configuration about usernames that not be handled yet.
Waiting your contact or more info about the username configuration of your server.
Thanks.
