### ISSUE TITLE
Xcode Build erro: error reading:"node_modules/react-native/ReactCommon/jsinspector/InspectorInterfaces.cpp"

### ISSUE THREAD

**Issue by MiaoMiaoai** [RocketChat/Rocket.Chat.ReactNative#1428]
Your Rocket.Chat Experimental app version: 1.20.1.100
Your Rocket.Chat server version: 2.1.1
Device (or Simulator) you're running with: Simulator iPhone X

<img width="1088" alt="截屏2019-11-29上午11 01 41" src="https://user-images.githubusercontent.com/19339100/69840785-b688c600-1297-11ea-9dd1-ff41ffe1f8d0.png">

New project just downloaded.

Build in Xcode 11.3 :error: error reading '/Users/hanshaobo/Desktop/Rocket.Chat.ReactNative-develop/node_modules/react-native/ReactCommon/jsinspector/InspectorInterfaces.cpp'

**Comment by diegolmello** [comment]
Update to latest version and try again.
