### ISSUE TITLE
Some words not translated when language is changed

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1433]
- Your Rocket.Chat Experimental app version:1.20.1.99999999
- Your Rocket.Chat server version:2.3.0-rc.0 open.rocket.chat
- Device (or Simulator) you're running with: Samsung Galaxy J6

The following Gif shows, 'Directory' and 'Sort by' words don't change when we change language,
although It8n is used.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/44807945/69978288-3477f600-1552-11ea-819e-d5f365bf0f07.gif)

**Comment by diegolmello** [comment]
Duplicated of #724
