### ISSUE TITLE
Password change field should be disabled, if password change is disabled

### ISSUE THREAD

**Issue by phriedrich** [RocketChat/Rocket.Chat.ReactNative#1436]
- Your Rocket.Chat Experimental app version: 1.25.0.12983
- Your Rocket.Chat server version: 2.3.0
- Device (or Simulator) you're running with: iPad w/ iPad OS 13.2.3

We get the user information via LDAP and disabled the option to change the user's password within Rocket.Chat.

On the web version, the password change field in the user's profile settings is correctly disabled and can not be selected.

In the app I can (try) to set a new password, at least I can select the field and write something. The field should be disabled if the option is not enabled.

![Password change field](https://user-images.githubusercontent.com/470153/70137727-e7e60500-168e-11ea-9d6b-ca85c9329181.png)

**Comment by ankar84** [comment]
Same case, and I totally agree with that issue!
Please fix it.

**Comment by diegolmello** [comment]
That setting is not implemented on the app yet.

**Comment by phriedrich** [comment]
Note:

With the `/api/v1/settings.public` endpoint we can get the information, which data are allowed to edit, some of them we should probably check and use to limit what the user can edit:

* Accounts_AllowPasswordChange
* Accounts_AllowRealNameChange
* Accounts_AllowUserAvatarChange
* Accounts_AllowUserProfileChange
* Accounts_AllowUsernameChange

For example it's also possible that it is not allowed to change the email address or the username.

**Comment by devyaniChoubey** [comment]
Can I work on it?

**Comment by phriedrich** [comment]
Sure, would be really nice to have this fixed.

**Comment by Prateek93a** [comment]
@phriedrich @devyaniChoubey If work is not being done on this, can I take this up?

**Comment by phriedrich** [comment]
@Prateek93a I'm not working on this, but I don't know if @devyaniChoubey did some work already. 

This ticket is also related to #1590, probably both could be fixed with one PR.

**Comment by Prateek93a** [comment]
@phriedrich Yes, #1590 will also be fixed in the similar way. In the same PR, all the above mentioned permissions can be checked and implemented accordingly. Thanks
@devyaniChoubey Are you working on this? If not, can I take it up?

**Comment by devyaniChoubey** [comment]
@Prateek93a Yes I am working on it. I will soon create a PR.

**Comment by Prateek93a** [comment]
@devyaniChoubey Ok, Great.

**Comment by phriedrich** [comment]
@devyaniChoubey Any updates on this?

**Comment by phriedrich** [comment]
This has been solved with the mentioned PR. 

Many thanks to everyone involved, especially @tanmoyopenroot and @diegolmello!
