### ISSUE TITLE
App name and version not set for Rocket.Chats internal statistics

### ISSUE THREAD

**Issue by phriedrich** [RocketChat/Rocket.Chat.ReactNative#1440]
- Your Rocket.Chat Experimental app version: 1.25.0.13047
- Your Rocket.Chat server version: 2.3.0
- Device (or Simulator) you're running with: iPad w/ iPad OS 13.2.3

The "user-agent" is working correctly (#1307) and it's showing in the webserver's log:

`"RC-RN Mobile/1.25.0 (build: 13047; os: ios 13.2.3)"`

And for comparison the old app:

`"RC Mobile; iOS 13.2.3; v3.5.2 (262)"`

But in Rocket.Chat's internal log it isn't registered correctly:

```
"uniqueDevicesOfYesterday": {
        "data": [
…
            {
                "count": 1,
                "name": "RC Mobile",
                "time": 89,
                "type": "mobile-app",
                "version": "3.5.0"
            },
…
            {
                "count": 8,
                "time": 838,
                "type": "mobile"
            },
…
```

It just shows up as type mobile without app name and version.

**Comment by phriedrich** [comment]
The statistics you can get from API: https://rocket.chat/docs/developer-guides/rest-api/miscellaneous/statistics/

**Comment by phriedrich** [comment]
To follow up with what I found out:

Rocket.Chat's statistic module specifically looks for 'RC Mobile' to recognize the app. [1] 
But Rocket.Chat.ReactNative sets 'RC-RN Mobile/…'. [2]


[1]: https://github.com/RocketChat/Rocket.Chat/blob/bb842f2e4d60bd2b0cfe136e1dceda976baba544/app/statistics/server/lib/UAParserCustom.js#L55
[2]: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/5f0389c7de4f8df5ca7ef07dfd2ff8f3b35d953d/app/utils/fetch.js#L4

**Comment by diegolmello** [comment]
@phriedrich We're cutting version 4.2 already and we're going to release it soon.
Let's try to fix this on 4.3.
Are you willing to open a PR?
Thanks!

**Comment by phriedrich** [comment]
Yes, I can try to get a PR ready for the 4.3 release.

**Comment by phriedrich** [comment]
It works now:
![Bildschirmfoto 2019-12-19 um 09 43 29](https://user-images.githubusercontent.com/470153/71158436-39bc8c80-2244-11ea-8ef1-d9fe362b1192.png)

**Comment by diegolmello** [comment]
@phriedrich Do you mean on #1482, right?

**Comment by phriedrich** [comment]
Yes, after doing the changes in #1482 yesterday, today the test shows up correctly for me in the statistics.

**Comment by diegolmello** [comment]
Nice, thanks.
