### ISSUE TITLE
How to custom 'Message Actions'

### ISSUE THREAD

**Issue by khanhbao0508** [RocketChat/Rocket.Chat.ReactNative#1441]
I dont know how to custom message action pop-up like this
![image](https://user-images.githubusercontent.com/47891357/70293789-0295b680-1814-11ea-849a-3d8805d28bf2.png)

**Comment by Prateek93a** [comment]
@khanhbao0508 I believe you are asking how to open MessageAction popup. For that, press and hold on any of the message to open Message Action popup. Hope this helps.

**Comment by khanhbao0508** [comment]
@Prateek93a I'm sorry if my question misunderstood you but I am trying to change the MessageAction design as shown above.
After all, thank you for answer my question

**Comment by Prateek93a** [comment]
@khanhbao0508 Oh, Ok, sorry for misunderstanding your question. For customization,the popup component is implemented by ActionSheet component, and it supports styling, so you can pass style props to the component.
https://www.npmjs.com/package/react-native-actionsheet#how-to-redesign-style-

**Comment by Prateek93a** [comment]
@khanhbao0508 Oh, sorry for misunderstanding your question. For customisation, popup is implemented using react-native-action-sheet lib, and it supports styling
https://github.com/yfuks/react-native-action-sheet#optional-style-customization

**Comment by diegolmello** [comment]
Dup of #759
