### ISSUE TITLE
Name instead of Username

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#1442]
- Your Rocket.Chat app version: **4.1.0.2095**
- Your Rocket.Chat server version: **2.3.0**
- Device (or Simulator) you're running with: Xiaomi Mi 9 SE

Rocket.Chat ReactNative client shows **Name** after **Name** (and it is wrong).
Rocket.Chat Election client and browser version shows **UserName** after **Name** (and this is correct)

Here is examples:
My user data 
![image](https://user-images.githubusercontent.com/4023037/70298558-171d8300-1803-11ea-958c-98947c05d628.png)
Rocket.Chat Election client and browser version
![image](https://user-images.githubusercontent.com/4023037/70298572-24d30880-1803-11ea-8ca8-d38d625e0687.png)
Rocket.Chat ReactNative client
![image](https://user-images.githubusercontent.com/4023037/70303695-4f2bc280-1811-11ea-98ec-cd22feb4c3cf.png)

Use Real Name option is enabled in Layout settings
![image](https://user-images.githubusercontent.com/4023037/70298823-03bee780-1804-11ea-8920-cffeef8254a7.png)

**Comment by aashaypalliwar** [comment]
Hi I am already looking into issue #1260 [https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1260](url) , May I also handle this as it would deal with similar things?

**Comment by diegolmello** [comment]
@aashaypalliwar sure

**Comment by ankar84** [comment]
Still in 4.7.0

**Comment by ankar84** [comment]
Still in 4.12
@diegolmello I think fix for that issue is not so hard. What do think about that?

**Comment by diegolmello** [comment]
We'll check that open PR

**Comment by ankar84** [comment]
I think I need to close that issue for a few reasons.
1. I'm not sure, but I think, that solution could be in server version or some settings, because I double checked that issue and it's solved in most places in most chats
2. Since that issue was started we changed `Name` in RC - no it includes not only user first name and surname, but also father name (in Russian it called Отчество), so because of that length of `Name` increased dramatically and almost non of then fit my smartphone screen size
3. It's continue of 1. - I see only `Name` without `Username` in my old 4.7 version and in most recent 4.12 version almost everywhere (but only almost)
4. I see that issue behavior (`Name @name`) in some chats in version 4.12 (but only in horizontal mode)

Here a screens

**Comment by ankar84** [comment]
So, @diegolmello you can close that issue, it's not in recent chats of any mobile client since 4.7

**Comment by ankar84** [comment]
I will reopen it if see that bug in recent chats in recent versions of application.
