### ISSUE TITLE
Some Uploads still don't work

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat.ReactNative#1449]
- Your Rocket.Chat Experimental app version: 1.25.0.13048
- Also Non-Experimental Version 4.1.0.2095
- Your Rocket.Chat server version: 2.3.0
- Device (or Simulator) you're running with: Nokia 8.1 (Android 9), LG G2 (Lineage 16), Huawei P20, P30 (Android 9)

As posted [here: #1325 ](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1325) (The OP closed the issue...), this is still an issue.
I've also posted this in the old android app section [#2507](https://github.com/RocketChat/Rocket.Chat.Android/issues/2507). It affects both apps and no usable debug logs are generated on the server.

This time I've tested the app versions mentioned above. JPG uploads from the channel view do not work (Error: "Try again"). Sharing from another application, e.g. gallery, doesn't work either.
Taking a picture from within the apps produces smaller picture, which uploads just fine. The taken picture can be re-uploaded from the room view via "Choose file", which works just fine.
Pictures received in Whatsapp can be uploaded as well. 

So I'm asking again: is there a hard coded size limit or something? JPG uploads (6-8 MB) from the desktop client do work, so it's not the file size limit on the server.

Anyone else with this problem?

**Comment by diegolmello** [comment]
@aimador I tried to upload a 15MB video now and it worked. Can you try uploading one 10MB+ video?

**Comment by aimador** [comment]
Tried a 42 MB video that I've just recorded. Failed in both apps.

**Comment by diegolmello** [comment]
@aimador Can you reach me at https://open.rocket.chat? I'm `@diego.mello`.

**Comment by aimador** [comment]
Hi Diego,
any news on the issue?

**Comment by dholbrook86** [comment]
Any news on this issue?

**Comment by C1ean** [comment]
Same problem

**Comment by aimador** [comment]
Sounds familiar: [#1665](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1656)

Can anyone confirm this: [#1647](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1647)
If that works, why does this not affect all other clients?

**Comment by diegolmello** [comment]
Have you tried https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1647#issuecomment-581506291?

Server uses meteor to upload files and app uses REST API.
Nginx default `client_max_body_size` is 1MB.
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

Please confirm it fixes for you and we'll add this config to the docs.

**Comment by C1ean** [comment]
Yes it works, the problem is resolved! Many thanks!

**Comment by udvarit** [comment]
Just so it's clearer for future readers, how I did this on my env:

1. Opened _/etc/nginx/sites-enabled/default_
2. Added `client_max_body_size 50M;` in the server block, after the `error_log` line
3. Restarted nginx with `# systemctl restart nginx.service`


My env: Debian GNU/Linux 10 (buster), Rocket.Chat Server version: 2.4.14, installed via snap
