### ISSUE TITLE
Changing notification preferences does not have effect

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1452]
- Your Rocket.Chat Experimental app version: 1.25.0.99999999..
- Your Rocket.Chat server version: 3.0.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Samsung Galaxy J6 Android P

Might be linked to #1443 
When I change the preferences from default to something else, the change is seen, but changing the preferences again to something else, the change is not seen. After tapping several times, the change appears.
![ezgif com-video-to-gif(8)](https://user-images.githubusercontent.com/44807945/70589891-fa17f400-1bf6-11ea-93e8-36bd6da40a0d.gif)

**Comment by diegolmello** [comment]
It's seems to happen after changing a setting and then trying to change it again.

**Comment by Prateek93a** [comment]
@diegolmello  I think the issue is related with the rnpicker itself, I put an alert statement in the  function passed to onValueChange prop of the picker such that whenever the value changes, it displays the new value, but every time I change the value, the old value is displayed, hence the old value is getting passed and hence no change is visible.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/44807945/71234477-14508100-231f-11ea-8efd-15191ab2b5e2.gif)
![Screenshot from 2019-12-20 11-42-52](https://user-images.githubusercontent.com/44807945/71235124-44991f00-2321-11ea-8b36-af699c294aa5.png)

**Comment by djorkaeffalexandre** [comment]
Closed by #2000.
