### ISSUE TITLE
bug in Preferences > Theme Automatic listed too often

### ISSUE THREAD

**Issue by foss-** [RocketChat/Rocket.Chat.ReactNative#1456]
- Your Rocket.Chat Experimental app version: 1.25.0.13047
- Your Rocket.Chat server version: 2.3.1
- Device: iOS 13.3

For me this is reproducible by:

1. going in to preferences > theme
1. going back to preferences
1. again to preferences > theme

Each time an entry is added to the list. Doesn't matter if Automatic is selected or Light or Dark, a new entry is still added for every cycle.

Expected: Should only list "Automatic" option once.

Off-topic, but while I am here, are there plans to update the changelog at https://github.com/RocketChat/Rocket.Chat.ReactNative/releases more regularly? Would be nice to have to keep track of changes.

![react automatic](https://user-images.githubusercontent.com/5708172/70651455-23fe0480-1c51-11ea-917c-d2fc5b632d57.png)

**Comment by diegolmello** [comment]
I'll take a look.

> Off-topic

Yep, too many things going on at the same time.
I'll update it in a few.
Thanks.
