### ISSUE TITLE
Use @react-native-community/async-storage 

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1463]
- Your Rocket.Chat Experimental app version: 4.2.0.99999....
- Your Rocket.Chat server version: 3.0.0-develop
- Device (or Simulator) you're running with: Samsung Galaxy J6 Android P

![Screenshot from 2019-12-12 10-31-57](https://user-images.githubusercontent.com/44807945/70684116-fce41900-1cca-11ea-8bdc-e3b6a99b60ab.png)

AsyncStorage will be removed from react-native core in a future release, so if nobody is working on updating this, can I take this up?

**Comment by diegolmello** [comment]
We might end up removing AsyncStorage completely and use only [RNUserDefaults ](https://www.npmjs.com/package/rn-user-defaults) so all settings are shared between Official and Experimental app, but thanks for your concern.

**Comment by Prateek93a** [comment]
@diegolmello  Ok Sir
