### ISSUE TITLE
Rocketchat app can’t save to the album on the phone since it was updated to 4.1.0

### ISSUE THREAD

**Issue by wlsdk0125** [RocketChat/Rocket.Chat.ReactNative#1473]
Your Rocket.Chat app version: 4.1.0.268
Your Rocket.Chat server version: 2.2.0
Device (or Simulator) you're running with: ios

**The app isn't connecting to your server?**
Nginx version is 1.16 and since updated to 4.1.0 ,click the save to the album no response,can't save to the phone,and 3.5.1 version is ok
![984509EA-98B2-49cf-BDC5-5060612B8E61](https://user-images.githubusercontent.com/50854371/70891760-e15a7480-2022-11ea-9d62-482e3936d5ef.png)

**Comment by Prateek93a** [comment]
Same as  #888

**Comment by wlsdk0125** [comment]
> 与[＃888](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/888)相同 [](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/888)


I am not a professional developer, can you tell me the specific operation process?

**Comment by Prateek93a** [comment]
@wlsdk0125 Actually a PR for solving the above issue has been made. After it gets accepted and included in the release, the issue will be solved. So till then, you probably have to wait. Thanks.

**Comment by wlsdk0125** [comment]
> @ wlsdk0125实际上已经为解决上述问题制作了PR。在它被接受并包含在发行版中之后，该问题将得到解决。所以直到那时，您可能必须等待。谢谢。

ok thank you
