### ISSUE TITLE
Make answers smaller

### ISSUE THREAD

**Issue by corincorvus** [RocketChat/Rocket.Chat.ReactNative#1474]
Hi,

it is possible to make the answers smaller or mark it better, if they are in a thread? (font size).

In a Channel with a big thread (like 10 answers) on a smartphone u cant see, its a thread, cause the info is on the top. You only see the Messages. Often other users write normally in the channel even tough they want to answer for a question in the thread.

Thread Answers have the same size, font and look like a normal channel message.

Thread example (First message and thread answers are in same size, font and look. Only on the right side you can see the cut of the message. With short messages you cant see it.):
![Screenshot_20191216-121813](https://user-images.githubusercontent.com/21257329/70903132-82830400-1ffe-11ea-95f5-0aa9f215a3ec.jpg)

If your Display is smaller or other messages added every time you need to scroll up to check, its a thread or not.
![2019-12-16 12_19_47-Fotos](https://user-images.githubusercontent.com/21257329/70903161-8f9ff300-1ffe-11ea-9a6f-f06e0199877e.png)

Best Regards

**Comment by ivans-netto** [comment]
Hi @corincorvus, how are you? :)

I'm Ivan, Designer at Rocket Chat and noticed your feedback about threaded messages. Would you like to answer a quick survey about this feature? 

https://forms.gle/RcPAjHfZigHoNvXc9

**Comment by corincorvus** [comment]
Hey,

iam done :)

**Comment by diegolmello** [comment]
@corincorvus Thanks for your thoughts.
I'm going to close this issue as we're discussing next steps on threads already.
Cheers.
