### ISSUE TITLE
Admin Panel is not visible in the Android app. 

### ISSUE THREAD

**Issue by monarkh-karina** [RocketChat/Rocket.Chat.ReactNative#1476]
- Your Rocket.Chat app version: 4.1.0.2095
- Your Rocket.Chat server version: 2.3.0
- Device (or Simulator) you're running with: Galaxy J7 SM-J700H (Android 6.0.1)

Steps to reproduce: 
1. Log into your server via an Android app (being an Admin on this server). 
2. Open the left-side menu. 
3. "Chats" "Profile" "Settings" "Logout" options are visible. 

Expected behavior: having the "Admin Panel" option visible in the left-side menu.

**Comment by diegolmello** [comment]
Yep, it seems it happens only after logging in.
It works properly after changing server or opening the app again.

**Comment by Ritesh-Ag** [comment]
Can i take up this issue?

**Comment by djorkaeffalexandre** [comment]
@Ritesh-Ag yes!

**Comment by Ritesh-Ag** [comment]
@djorkaeffalexandre Okay Sir!
