### ISSUE TITLE
Try to react-native run-android but build failed

### ISSUE THREAD

**Issue by ssbing99** [RocketChat/Rocket.Chat.ReactNative#1478]
- Your Rocket.Chat Experimental app version: 4.1.0 Master Branch
- Your Rocket.Chat server version: -
- Device (or Simulator) you're running with: android

Hi I am new to React Native and mobile app development. When i cloned this project and try to run-android, and get the below error :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :reactnativenotifications.
     Required by:
         project :app
      > Cannot choose between the following variants of project :reactnativenotifications:
          - reactNative59DebugRuntimeElements
          - reactNative60DebugRuntimeElements
        All of them match the consumer attributes:
          - Variant 'reactNative59DebugRuntimeElements' capability RocketChat:reactnativenotifications:unspecified:
              - Unmatched attributes:
                  - Found RNNotifications.reactNativeVersion 'reactNative59' but wasn't required.
                  - Found com.android.build.api.attributes.VariantAttr 'reactNative59Debug' but wasn't required.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
              - Compatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'reactNative60DebugRuntimeElements' capability RocketChat:reactnativenotifications:unspecified:
              - Unmatched attributes:
                  - Found RNNotifications.reactNativeVersion 'reactNative60' but wasn't required.
                  - Found com.android.build.api.attributes.VariantAttr 'reactNative60Debug' but wasn't required.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
              - Compatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :reactnativenotifications.
     Required by:
         project :app
      > Cannot choose between the following variants of project :reactnativenotifications:
          - reactNative59DebugRuntimeElements
          - reactNative60DebugRuntimeElements
        All of them match the consumer attributes:
          - Variant 'reactNative59DebugRuntimeElements' capability RocketChat:reactnativenotifications:unspecified:
              - Unmatched attributes:
                  - Found RNNotifications.reactNativeVersion 'reactNative59' but wasn't required.
                  - Found com.android.build.api.attributes.VariantAttr 'reactNative59Debug' but wasn't required.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
              - Compatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'reactNative60DebugRuntimeElements' capability RocketChat:reactnativenotifications:unspecified:
              - Unmatched attributes:
                  - Found RNNotifications.reactNativeVersion 'reactNative60' but wasn't required.
                  - Found com.android.build.api.attributes.VariantAttr 'reactNative60Debug' but wasn't required.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
              - Compatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

    at checkExecSyncError (child_process.js:609:11)
    at execFileSync (child_process.js:627:15)
    at runOnAllDevices (/Users/bernard/Desktop/RocketChat/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/bernard/Desktop/RocketChat/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /Users/bernard/Desktop/RocketChat/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/Users/bernard/Desktop/RocketChat/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:164:9)

Any idea ? I am not so sure what did I missed...

System:
    OS: macOS 10.15
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: 0.61.3 => 0.61.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by diegolmello** [comment]
Try running `develop` branch.
Does it work?

**Comment by ssbing99** [comment]
Hi sir, I checkout the latest develop branch, then yarn and run-android and it able to run on simulator now. Thank you.
But there is something that I am wondering, previously i was using npm install , any different between npm install and yarn for this project ? and have the error log for yarn but somehow still able to build and run

**Comment by diegolmello** [comment]
You should always follow the docs: https://github.com/RocketChat/Rocket.Chat.ReactNative#how-to-run
There are lots of differences, but they're not related to the repo.

**Comment by ssbing99** [comment]
Thank you
