### ISSUE TITLE
Searching leaves result behind

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.ReactNative#1488]
- Your Rocket.Chat Experimental app version: 4.1.0.268
- Your Rocket.Chat server version: open’s version
- Device (or Simulator) you're running with: iPhone XS

* Sort activity
* unread on top

Searching then seems to leave behind a result above unread

![BF141E15-4E5B-4C85-8875-790A56C1CFF9](https://user-images.githubusercontent.com/51996/71283841-e838fe00-2326-11ea-8585-aa721b90fba6.gif)

**Comment by aashaypalliwar** [comment]
Hi! I wish to take this up.

**Comment by devyaniChoubey** [comment]
@geekgonecrazy  can i work on this issue?

**Comment by geekgonecrazy** [comment]
I’m sure no one would object :)

Cc: @RocketChat/reactnative

**Comment by aashaypalliwar** [comment]
@devyaniChoubey @geekgonecrazy , hey ! I am working on this and would soon open a pr. Took time because of internet issues in my region.

**Comment by adrijshikhar** [comment]
@aashaypalliwar  are you still working on this?
