### ISSUE TITLE
Foss version

### ISSUE THREAD

**Issue by Bubu** [RocketChat/Rocket.Chat.ReactNative#1489]
The apk built from this repo contains a lot of google play services and firebase libraries. This can easily be check with:

` $ANDROID_HOME/tools/bin/apkanalyzer dex packages ./android/app/build/outputs/apk/debug/app-debug.apk | grep com.google.android.gms`

As these are proprietary libraries the apk cannot be distributed by F-Droid, which is therefore currently stuck on version 3.5.1: https://f-droid.org/packages/chat.rocket.android/

(It also makes the rocketchat app nonfree software :-/)

I have previously packaged the kotlin app for f-droid and worked with the developers there to provide an alternative build flavour without proprietary google libraries: https://github.com/RocketChat/Rocket.Chat.Android/pull/1585

I'd like to update the app in F-Droid, but I have no idea about react-native, so I cannot help this time.

**Comment by djorkaeffalexandre** [comment]
Hello @Bubu ! We want to distribute an APK on F-Droid.
If you want, we can work collaborate to make it!
Reach me on https://open.rocket.chat. I'm `djorkaeff.alexandre`.

Thanks a lot! ❤️

**Comment by CryptOwl** [comment]
Any update to this?

**Comment by Flam3z** [comment]
The app on f-droid hasn't been updated in months, any reason why?

**Comment by eighthave** [comment]
@Flam3z "This new version unsurprisingly contains a lot of non-free libraries again" https://gitlab.com/fdroid/fdroiddata/-/issues/1890

**Comment by djorkaeffalexandre** [comment]
Hey guys!
I'll close this and we can track the F-droid implementation here:
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2096
It's working in progress and should be launched at the next three months.
Thanks.
