### ISSUE TITLE
Can you provide a version of the realm? 

### ISSUE THREAD

**Issue by alleniver** [RocketChat/Rocket.Chat.ReactNative#1490]
Can you provide a version of the realm? Because the local application uses realm. If we use waterelmondb, we need to re integrate a new database, so the application will become more and more complex.

**Comment by djorkaeffalexandre** [comment]
Hello @alleniver ! Realm has a lot of problems with Jitsi SDK, we migrate our code base to use WatermelonDB and it works fine for us.. I think you can create a Fork and revert the watermelon PR.. Thank you!
