### ISSUE TITLE
Error when tapping on images in channel thread

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1491]
- Your Rocket.Chat Experimental app version:4.2.0.999999999
- Your Rocket.Chat server version:2.4.0-rc.0
- Device (or Simulator) you're running with: Android P Samsung Galaxy J6
![ezgif com-crop(1)](https://user-images.githubusercontent.com/44807945/71469085-1c606300-27ee-11ea-99db-8a157f02c9de.gif)

Steps to reproduce ->
-Go to any channel.
-Go to threads.
-Tap on any image or attachment

**Comment by Prateek93a** [comment]
Can I take it up?

**Comment by Prateek93a** [comment]
Can I take it up?

**Comment by djorkaeffalexandre** [comment]
@Prateek93a yes, you can.

**Comment by Prateek93a** [comment]
@djorkaeffalexandre Ok Sir
