### ISSUE TITLE
The field is resetting

### ISSUE THREAD

**Issue by ssbing99** [RocketChat/Rocket.Chat.ReactNative#1496]
- Your Rocket.Chat Experimental app version: 4.2.0
- Your Rocket.Chat server version: 2.4.0-rc.0
- Device (or Simulator) you're running with: Android & iOS

For the profile part, after I keyed-in value to the field, then it seems like is resetting automatically in awhile. 
And also for the image, i try to select image from picker and debug using Reactotron it showed there is value in the avatar object after selected, but it also seems like resetting and became empty right after.

![reset field](https://user-images.githubusercontent.com/20513589/71480568-d1b60980-2834-11ea-857f-269f5caa1b83.gif)

**Comment by djorkaeffalexandre** [comment]
Hey @ ssbing99, can you help by doing a PR?
I think it's related to this:
`` ``
componentWillReceiveProps (nextProps) {
  const {user} = this.props;
  if (user! == nextProps.user) {
    this.init (nextProps.user);
  }
}
`` ``
`user` is an object and this comparison always evaluates to` true` and redefines the fields.

**Comment by ssbing99** [comment]
I could have a try on it. I'm thinking to use a flag to determine whether it has changes in any field, so when the flag is in true state, then it should skip for updating the `user` , something like below. So if it is not have any changes, then it will still remain to update the `user` . 
Sorry for my English.
`
if(!hasChange){
			if (user !== nextProps.user) {
				this.init(nextProps.user);
			}
		}
`

**Comment by djorkaeffalexandre** [comment]
I think you not need this..
Only use:
```javascript
import isEqual from 'lodash/isEqual';
if (!isEqual(user, nextProps.user)) {
  this.init(nextProps.user); 
}
```

**Comment by ssbing99** [comment]
I see ! Many thanks ! I'll create a PR when I'm available as soon as possible.
