### ISSUE TITLE
Channels don't appear

### ISSUE THREAD

**Issue by entonio** [RocketChat/Rocket.Chat.ReactNative#1498]
- Your Rocket.Chat Experimental app version: ####
4.2.0

- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####
iPhone X

The private channels I'm subscribed to don't appear in the directory, which makes them inaccessible, as they don't appear in the history either (logout + login cleared the history, even though it's available on other devices). This has been so since iOS moved to the react app.

**Comment by novacrazy** [comment]
I have been experiencing similar since this morning.

Joined channel listings no longer load, selected a joined channel in the directory says I'm not joined, new or old messages do not display in the channel listing, etc. Upon joining the already-joined channels from the directory, I am able to send and view messages, but the channel still does not show up in the main channel index.

- Your Rocket.Chat app version: 4.2.0.13336 and 4.1.0.268
- Your Rocket.Chat server version: 1.3.0-develop-ish (latest commit https://github.com/RocketChat/Rocket.Chat/commit/2c3c2dc09d56fbedfb04d9797318c2c73d1c525f)
- Device (or Simulator) you're running with: iPhone 6 running iOS 12.4.4

**Comment by diegolmello** [comment]
How can I reproduce it?

**Comment by novacrazy** [comment]
If I knew that, I would let you know. So far it seems spontaneous and random. 

I've tried to point you in the right direction by saying the app is connected to the server, as notifications still function and accessing channels one-by-one via the directory still mostly works, but it's not retrieving a list of joined channels for some reason, so the primary index of joined channels is empty. All channels are considered unjoined, which could also be why (when there was still a main index to view), unread messages were not appearing.

**Comment by diegolmello** [comment]
@novacrazy If the same channel isn't working for more than one user, it's something there.
If that's the case, send me a test user on https://open.rocket.chat.
I'm `diego.mello`.

**Comment by novacrazy** [comment]
When I start the app, it doesn't display *any* joined channels. I can view the channel directory (which is a separate page) and access channels that way, but the app thinks they are all unjoined and prompts to join them again. I am surmising that would be why channels are not listed or updated. 

It is not a per-channel issue, it's a problem with the app not listing any joined channels nor pulling updates for them.

I don't know what caused it or what percentage of my users are affected. This morning when I noticed the app was not displaying any updates to channels, I attempted to reinstall it, which led to all the channels disappearing. I assume a cache was cleared by doing that.

Furthermore, upon rejoining the already joined channels, it does seem to cache their joined-ness and keep them around in the channel list, but reinstalling the app again can easily clear that, and once again it thinks those channels are unjoined.

The app is connected to the server, notifications still work, bots still work, the web interface still works fine, etc. The app simply is not listing or updating joined channels.

**Comment by diegolmello** [comment]
I'm not following what you're trying to say.
Try recording a video/gif.
It doesn't make any sense to me.

**Comment by novacrazy** [comment]
I'll see if I can't put together a screenshot slideshow, though I'll have to censor much for privacy.

But basically the app is failing on such a fundamental level that it can't list joined channels. It's empty. That's where my frustration comes from. There is nothing to test or reproduce, it just... doesn't.

**Comment by diegolmello** [comment]
That's the point.
It's not working for you, but it does on https://open.rocket.chat, for example.
You can talk to me there, if you want to.
I also noticed you're using an old server version. Can you update or try a new one?
Is websocket enabled?

**Comment by novacrazy** [comment]
I'm using an older version of the server because it's a fork with some visual tweaks/fixes on the web version. I haven't touched the networking stuff. And yes, websockets are enabled and were working fine up until this morning. I currently don't have time to update it to the very latest version. 

Here is a quick visual of what happens:
![rocket-bug](https://user-images.githubusercontent.com/4708645/71931606-b4057000-3163-11ea-97e9-fb7779e12602.gif)

**Comment by novacrazy** [comment]
Here is the nginx proxy config:

```
location / {
    proxy_pass http://rocket_chat_backend/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto http;
    proxy_set_header X-Nginx-Proxy true;
    proxy_request_buffering on;
    proxy_redirect off;

    proxy_cache_key "$host$request_uri";
    proxy_ignore_headers Set-Cookie;
    proxy_ignore_client_abort off;
    proxy_buffers           32 4m;
    proxy_busy_buffers_size     25m;
    proxy_buffer_size 512k;
    proxy_max_temp_file_size 0;
    client_max_body_size        32m;
    client_body_buffer_size     4m;
    proxy_connect_timeout 300;
    proxy_read_timeout 300;
    proxy_send_timeout 300;
    proxy_intercept_errors off;
}
```

**Comment by entonio** [comment]
All I know is that my company was running smoothly on the old mobile clients and since the December update to this version, it's mostly become unusable. I'm not in a position to provide you with access to our server.
To wit:
- history is empty after login, instead of syncing with what's visible in the desktop client
- (at least the) private channels don't appear anywhere
- presence change (usually) does nothing
- with the experimental version (4.2, not with 4.1), messages just aren't delivered, even though the notifications are

I understand you have your own environment and things 'work there', but if you have an experimental version then the issues that affect other installs should be solved there before replacing the old mobile clients (which worked).

**Comment by entonio** [comment]
Update: the only way to get to a private channel seems to be to receive a message from it while the app is open in the foreground.

**Comment by novacrazy** [comment]
Okay, so, for myself and my users the problem appears to have fixed itself for now. That's odd... 

Was there a non-self-hosted service Rocket.Chat relies on to have functioning apps? Was it screwed up yesterday?

**Comment by diegolmello** [comment]
@entonio If you can't post your server URL here, send me a test user on open server.
I'm `diego.mello`.
Otherwise how would I be able to fix it?
Help me help you.
Thanks.

**Comment by Eiken** [comment]
Just wanted to say we had the same issue. Updating our server instance from 2.2.0 to 2.4.0 solved it for us.
