### ISSUE TITLE
Can't change presence status

### ISSUE THREAD

**Issue by entonio** [RocketChat/Rocket.Chat.ReactNative#1499]
- Your Rocket.Chat Experimental app version: ####
4.2.0

- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####
iPhone X

Selecting a status in the menu gives no visual feedback, only returns to the previous menu, and apparently does nothing anyway, since the status doesn't change.

**Comment by sarthakpranesh** [comment]
The setting of status works on the Production version of the mobile client though :thinking:

**Comment by entonio** [comment]
Just so you know - no, it does not work in the production version. It worked for a time, maybe a month ago, but at the time you mentioned this, it had ceased working again.

**Comment by diegolmello** [comment]
@entonio Can you test it on 4.6.1?
We made some changes on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1995
