### ISSUE TITLE
App crashes clicking "Sort by activity"

### ISSUE THREAD

**Issue by programwar** [RocketChat/Rocket.Chat.ReactNative#1501]
- Your Rocket.Chat Experimental app version: 1.25.0
- Your Rocket.Chat server version: 2.3.0
- Device (or Simulator) you're running with: iPhone X 12.2 / Android 9

When you click on "Sort by activity" app crashed and shows following error:

![image](https://user-images.githubusercontent.com/3056856/71512501-cabfe300-2896-11ea-8296-6379d1ed0d45.png)

**Comment by cygnusm** [comment]
it still crashes on version 4.1.0

**Comment by diegolmello** [comment]
Can you test it on Experimental app 4.2.+?

**Comment by programwar** [comment]
It's OK 4.3.1.

Thank you so much!
