### ISSUE TITLE
[BUG] App close on push notification

### ISSUE THREAD

**Issue by mikesrus** [RocketChat/Rocket.Chat.ReactNative#1505]
- Rocket.Chat Experimental app version: 4.2.0.2096
- Rocket.Chat server version: 2.2.0
- Device running with: Honor 8x

When i receive push notofication from our chat server, app closes/crashes.
i try clear cache/data/reinstall, but nothing help.

**Comment by djorkaeffalexandre** [comment]
Hello @mikesrus , can you reach me on https://open.rocket.chat?
My username is `djorkaeff.alexandre`.
We'll find steps to reproduce your issue and fix it. :)
Thanks a lot.

**Comment by djorkaeffalexandre** [comment]
We talked about it and found that error is only to `Test Push Notification` from Server Admin Panel.
