### ISSUE TITLE
[FEATURE] Authentication via Wordpress

### ISSUE THREAD

**Issue by rsjr** [RocketChat/Rocket.Chat.ReactNative#1507]
Currently the authentication via Wordpress is not supported in the mobile apps -> https://github.com/RocketChat/Rocket.Chat.ReactNative#features

Can you please add this feature in the development roadmap? Thanks!

**Comment by sumukhah** [comment]
Hello, 
I can take this issue, 
But i need some guiding @djorkaeffalexandre

**Comment by djorkaeffalexandre** [comment]
Hello @sumukhah , I think you need start by create a Rocket.Chat server with WordPress Authentication, and understand how it works on our web client. :)
