### ISSUE TITLE
[FEATURE] Direct Message from Channel Room itself

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1511]
- Your Rocket.Chat Experimental app version: 4.2.0.99999999
- Your Rocket.Chat server version: 2.4.0 open.rocket.chat
- Device (or Simulator) you're running with: Android P

Its a feaure request. It would be helpful to be able to direct message someone from the channel room itself by tapping on his/her avatar. Right now, tapping on the avatar takes you to the user info page. So to direct message him/her, we have to search for the user first and then message. Instead, it would be helpful if there is direct messge option in the user info page like in case of web app. Or have a modal open up when avatar is tapped, showing option to direct message or view user info.

**Comment by Prateek93a** [comment]
Can I take this up?

**Comment by djorkaeffalexandre** [comment]
Yes.

**Comment by Prateek93a** [comment]
@djorkaeffalexandre Ok Sir, so what would be better, having a modal open up or having a direct message button in the user info view itself?

**Comment by djorkaeffalexandre** [comment]
I think is better if you add a button on User Info to send a new message to user.

**Comment by Prateek93a** [comment]
Ok Sir, on it.
