### ISSUE TITLE
Blank lines in messages are not rendered

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat.ReactNative#1513]
- Your Rocket.Chat Experimental app version: Not Experimental but stable 4.1.0 on Android
- Your Rocket.Chat server version: 2.1.3
- Device (or Simulator) you're running with: Apple Phones or Motorola One _(Same issue)_

How to reproduce:
 - Write a message like this
   ```
   Whatever
   <BLANK LINE>
   Whatever
   ```

PC:
![image](https://user-images.githubusercontent.com/11560794/71720082-aa58d100-2e20-11ea-9a4c-e24a7959279c.png)

Phone:
![image](https://user-images.githubusercontent.com/11560794/71720120-d411f800-2e20-11ea-9cf1-e5da6a682be7.png)

**Comment by aKn1ghtOut** [comment]
I'll take this up?

**Comment by djorkaeffalexandre** [comment]
@aKn1ghtOut yes.
