### ISSUE TITLE
Dropdown menu does not closes automatically.

### ISSUE THREAD

**Issue by Ritesh-Ag** [RocketChat/Rocket.Chat.ReactNative#1514]
- Your Rocket.Chat Experimental app version: 4.2.0.999999999
- Your Rocket.Chat server version: 2.4.0 open.rocket.chat
- Device (or Simulator) you're running with: Android P

When we search for any channel or user under directory option, the dropdown menu does not closes automatically after choosing the option. It has to be closed manually by clicking again.
![20200103_195955](https://user-images.githubusercontent.com/50779098/71729139-faf21d80-2e64-11ea-86d7-3a9d354354f7.gif)

**Comment by Ritesh-Ag** [comment]
Can I take up this issue?

**Comment by djorkaeffalexandre** [comment]
@Ritesh-Ag yes, you can! 😁

**Comment by Ritesh-Ag** [comment]
@djorkaeffalexandre Okay, sir.
