### ISSUE TITLE
Unable to go to direct message room from members list in a channel

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1517]
- Your Rocket.Chat Experimental app version: 4.2.0.9999999
- Your Rocket.Chat server version: 2.4.0 open.rocket.chat
- Device (or Simulator) you're running with: Android P

Actually it's a bug issue.  When we tap on the member, in members  list, that we didn't have conversation with before, nothing happens but when tap on the member whom we had conversation with before, then direct message screen loads up. So it is actually a bug.
![ezgif com-crop (5)](https://user-images.githubusercontent.com/44807945/71749628-f85eea80-2e9b-11ea-92f4-cde0ad52b26d.gif)

**Comment by Prateek93a** [comment]
If this feature seems useful, can I take it up?

**Comment by djorkaeffalexandre** [comment]
Yes, you can.
You not need to ask if you can take some issue, if it not has a PR opened, you can do.
We really appreciate your contributions.
Thanks.

**Comment by Prateek93a** [comment]
@djorkaeffalexandre Thanks a lot Sir :)
