### ISSUE TITLE
React native custom keyboard on ios 

### ISSUE THREAD

**Issue by khanhbao0508** [RocketChat/Rocket.Chat.ReactNative#1520]
![issues](https://user-images.githubusercontent.com/47891357/71795927-061e9680-307b-11ea-8d84-94e253d0bcc4.png)
custom keyboard emoji run on android is working normally but when i add the same keyboard on ios, so the error above
please help !

**Comment by diegolmello** [comment]
We don't have a custom keyboard on iOS.

**Comment by khanhbao0508** [comment]
But if i want to custom keyboard, so how can i working that with theme on iOS
Custom keyboard run on Android normally with theme but on iOS return error 'theme is undefined' 
Thank you for answer my question

**Comment by djorkaeffalexandre** [comment]
@khanhbao0508 probably you forgotten to pass some `theme` prop to component. ;)
