### ISSUE TITLE
Messages won't load

### ISSUE THREAD

**Issue by brittyazel** [RocketChat/Rocket.Chat.ReactNative#1521]
- Your Rocket.Chat Experimental app version: 4.2.0.13337
- Your Rocket.Chat server version: 2.4.0
- Device (or Simulator) you're running with: Android 9, OnePlus5t

On one of our channels messages stopped updating on the Android client. New messages were coming in, and we could see them from the web client, but on the mobile app the messages weren't showing. I was advised to log out and log in to clear the local database, but now none of the messages will load. It's just stuck on the loading screen:

![Screenshot_20200105-211653](https://user-images.githubusercontent.com/3747347/71797059-6ec92d00-3001-11ea-906f-a2f8cf76e5b7.jpg)

**Comment by brittyazel** [comment]
Oddly, if I click the discussions button I can see all the discussions just fine. 

![Screenshot_20200105-213404](https://user-images.githubusercontent.com/3747347/71797475-2a3e9100-3003-11ea-8642-ae0fbc84edcc.jpg)

**Comment by brittyazel** [comment]
Another note, some of our users who are experiencing this issue are reporting that it's new with the update to server 2.4.0. Perhaps that may help narrow it down

**Comment by novacrazy** [comment]
For myself and my users, messages will sometimes load/send if the channel is open. New messages don't always come through, but generally existing ones do load.

However, as of this morning the channel listing is empty and there are no unread messages. This makes the app effectively useless for actually keeping up with channels. Using the directory to visit channels shows them all as unjoined. 

**Notifications still work**, though. The app is receiving messages. It's just not displaying them, I guess.

See #1528 for my version numbers. Supposedly a few users have been experiencing this for months.

I also have a simple bot running on the server, which has not experienced any issues whatsoever receiving messages. The server is totally fine, it's just the app that's bad.

**Comment by diegolmello** [comment]
Can you give me a reproducible test or it's an issue that happens often but not always?
I need to narrow it down, because it always works for me.

**Comment by novacrazy** [comment]
Well, regarding the bot, because it replies extremely fast its messages tend to be ignored by the app more often than others. That's a notable example. 

However, since the app doesn't populate the joined channel listing or unread messages now limits my ability to test things.

The fact is shows all channels as unjoined when navigating to them via the directory, despite me being the admin and having joined literally all of them, may give you somewhere to start.

**Comment by brittyazel** [comment]
It isn't all channels, it's just particular channels. Likewise, of the two channels of mine that have experienced this issue, both were fine until 'something' triggered them. Some new message or new user induced the behavior. The behavior being 1) no new messages will load from the point when the issue occurred, and 2) if you clear the local database (by logging out and back in) no messages at all will load.

On one of my channels that this happened on, I was able to prune the entire message history and that solved the problem. However, the other channel is much more active and pruning the entire history is a non-option.

In the image below I have drawn an arrow to the first message that refused to load on mobile. I am unsure if it is helpful, but at least it gives the timeline.

![Screenshot from 2020-01-07 10-53-35](https://user-images.githubusercontent.com/3747347/71920759-53af0800-313c-11ea-92d8-ae8c7b402fc7.png)

Other than that, you can log into chat.gnome.org to see if you can verify the issue for yourself of our #general channel

**Comment by brittyazel** [comment]
> Well, regarding the bot, because it replies extremely fast its messages tend to be ignored by the app more often than others. That's a notable example.
> 
> However, since the app doesn't populate the joined channel listing or unread messages now limits my ability to test things.
> 
> The fact is shows all channels as unjoined when navigating to them via the directory, despite me being the admin and having joined literally all of them, may give you somewhere to start.

I do not experience this behavior.

**Comment by novacrazy** [comment]
Hmm. Perhaps our issues are similar but orthogonal. I was simply redirected to this issue earlier.

**Comment by diegolmello** [comment]
> I was simply redirected to this issue earlier

@novacrazy Actually, you mentioned several issues on one ticket (and dup).
That's why your issue was closed.
Let's focus on message load here, so we can get it fixed.
If you have any more issues, open new ones (but search for it first).

**Comment by diegolmello** [comment]
@brittyazel I think the issue started after that user without username joined.
Don't remove it yet.
Let me check if I can fix it quickly.

**Comment by brittyazel** [comment]
Yep I won't remove anything. We had a few other of those "<blank> has joined" just above that as well

**Comment by diegolmello** [comment]
@brittyazel And do you know how they were added blank?

**Comment by brittyazel** [comment]
I don't know. I had sent out the invite link to get people to join. The blank users weren't an issue until the invite links started going out imo

**Comment by brittyazel** [comment]
awesome! How soon will it take to roll the fix out?

**Comment by diegolmello** [comment]
@brittyazel I'm building Experimental right now.
It's going to Experimental beta today.
Official probably by Monday.

**Comment by brittyazel** [comment]
awesome! Thanks so much for looking into it! I'm happy you were able to track down the cause :-)

The GNOME Foundation thanks you :-)
