### ISSUE TITLE
app closed after click on video  call button

### ISSUE THREAD

**Issue by cygnusm** [RocketChat/Rocket.Chat.ReactNative#1522]
- Your Rocket.Chat Experimental app version: 4.2.0
- Your Rocket.Chat server version: 2.3.0
- Device (or Simulator) you're running with: huawei 7x,android 9

after click on video call, app closed.
jitsi is working good on browsers and jitsi official app and rocketchat web aaplication.
-app's log after click on video call button:

[13:28:57] E | ReactNativeJS ▶︎ TypeError: null is not an object (evaluating 'r(d[0])(r(d[1])).default.Direction')

[13:28:57] E | ReactNativeJS ▶︎ Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

@diegolmello

**Comment by diegolmello** [comment]
@cygnusm Thanks for opening this issue.
Apparently, Jitsi uses old JSC and we're introducing Hermes on 4.2.0.
We're figuring if we can fix the issue or if we should release the 4.2.0 without Hermes.

**Comment by cygnusm** [comment]
> @cygnusm Thanks for opening this issue.
> Apparently, Jitsi uses old JSC and we're introducing Hermes on 4.2.0.
> We're figuring if we can fix the issue or if we should release the 4.2.0 without Hermes.

thank you, i 'm waiting for new release

**Comment by diegolmello** [comment]
You can try our official version: https://play.google.com/store/apps/details?id=chat.rocket.android

**Comment by djorkaeffalexandre** [comment]
Fixed by #1523 .
