### ISSUE TITLE
Auto search when text changes in directory textfield

### ISSUE THREAD

**Issue by Ritesh-Ag** [RocketChat/Rocket.Chat.ReactNative#1526]
- Your Rocket.Chat Experimental app version: 4.2.0.99999999
- Your Rocket.Chat server version: 2.4.0
- Device (or Simulator) you're running with: Android P

When we search for any channel or user, we have to click the search button but the search should start automatically as the text changes.

![directory](https://user-images.githubusercontent.com/50779098/71901467-05bef200-3186-11ea-8742-eb3916b84dcf.gif)

**Comment by Ritesh-Ag** [comment]
Can I take up this issue?

**Comment by djorkaeffalexandre** [comment]
@Ritesh-Ag , yes you can, but I think you need to check if user stopped typing before search.
You not need to ask if you can take an issue, if it not has some `Assignees` or `Opened Pull Requests` you can start your work.
Thanks.

**Comment by Ritesh-Ag** [comment]
@djorkaeffalexandre Okay sir!

**Comment by Ritesh-Ag** [comment]
@djorkaeffalexandre Should I use timeout function for that. If so, how much time should be given?

**Comment by alexnaiman** [comment]
Hello! Can I try to tackle this issue for the Hacktoberfest2020? If so, can you assign it to me?

**Comment by diegolmello** [comment]
@alexnaiman I won't assign you, but I'd be happy to review your code.
