### ISSUE TITLE
iOS doesn't load channels or messages

### ISSUE THREAD

**Issue by novacrazy** [RocketChat/Rocket.Chat.ReactNative#1528]
This morning I finally upgraded to iOS 12.4.4, and it seems that was the catalyst for the iOS app to completely crap itself. 

Joined channel listings no longer load, selected a joined channel in the directory says I'm not joined, new or old messages do not display in the channel listing, etc. Upon joining the already-joined channels from the directory, I am able to send and view messages, but the channel still does not show up in the main channel index. 

As the admin of a server of 500+ people, this makes my job incredibly difficult, as the web version is too unoptimized to run in Safari.

Perhaps leave the Kotlin version up on the App Store for those of us that care about our servers? It was also terrible, but it worked.

- Your Rocket.Chat app version: 4.2.0.13336 and 4.1.0.268
- Your Rocket.Chat server version: 1.3.0-develop-ish (latest commit https://github.com/RocketChat/Rocket.Chat/commit/2c3c2dc09d56fbedfb04d9797318c2c73d1c525f)
- Device (or Simulator) you're running with: iPhone 6 running iOS 12.4.4

**Comment by diegolmello** [comment]
Transferred to the proper repo.
This issue is a duplicate from other issues like #1521 though

**Comment by novacrazy** [comment]
It appears this issue has resurfaced today, exact same behavior.

Is there some critical app infrastructure Rocket.Chat has that is not self-hosted? 

Today also happens to be when Let's Encrypt is revoking over 3 Million certs, so perhaps something has gone down elsewhere.
