### ISSUE TITLE
Need to type server url after logout on mobile device

### ISSUE THREAD

**Issue by zahaim** [RocketChat/Rocket.Chat.ReactNative#1531]
## Describe the feature you'd like

Thanks for this great product. 1 feature missing in our company is:

When logged out from the app, users would like to be able to choose previously used server name from the list. 
Users have trouble remembering chat's url in the format http://chat.company-name.com

Many thanks!

**Comment by diegolmello** [comment]
Related to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2348
