### ISSUE TITLE
'No results found' message not displayed when search don't match any room or user.

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1533]
- Your Rocket.Chat Experimental app version: 4.2.0.999999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android P

As the gif shows, when we search for something thats not available, we are not getting message like 'no results found'. Instead the initial list of rooms are displayed. 
![ezgif com-crop (9)](https://user-images.githubusercontent.com/44807945/72004702-f1582380-3271-11ea-8f1e-7b0545f2b2d2.gif)

**Comment by rheo-chiti** [comment]
Can I work on this issue?

**Comment by diegolmello** [comment]
@rheo-chiti sure!

**Comment by m1-key** [comment]
@rheo-chiti  Can I resolve this issue if you say then only

**Comment by devyaniChoubey** [comment]
@m1-key can I work on this?

**Comment by m1-key** [comment]
@devyaniChoubey  Yaa , sure

**Comment by diegolmello** [comment]
@devyaniChoubey Instead of opening a PR with the same content of #1589, review it.
Stop opening PRs just to get yourself top ranking on the leaderboard.

**Comment by devyaniChoubey** [comment]
Sorry sir ,but I thought that the issue #1589 was about the search members option in roomactions and this issue is about search chats options above directory. That's why I thought to solve this
