### ISSUE TITLE
Channel names display with '-' on mobile

### ISSUE THREAD

**Issue by msisskin** [RocketChat/Rocket.Chat.ReactNative#1535]
- Your Rocket.Chat Experimental app version: 1.7.0
- Your Rocket.Chat server version: 2.3.1
- Device (or Simulator) you're running with: Android/iOS

When displaying channels in the sideNav in the browser, channel/group names are normalized to not have spaces. E.G. "This is a channel" However, that same channel is displayed with dashes when the list of Channels is viewed on mobile. 

Per the linked conversation below, in Rocket.Chat Server, the room is being called differently than what I see in the React.Native code base. Users are asking us about labeling consistency between the browser and mobile. The behavior is similar for channel headers and Room info.  

Conversation link: https://github.com/RocketChat/Rocket.Chat/pull/14075

**Comment by diegolmello** [comment]
Can you test on a newer version of the app?

**Comment by msisskin** [comment]
Thanks for the quick response. Both my iOS sim from a develop pull on Tuesday and a quick reinstall of Rocket.Chat.Experimental on Android show the dashes in name behavior while the browser version does not.
