### ISSUE TITLE
Set a custom status message

### ISSUE THREAD

**Issue by msisskin** [RocketChat/Rocket.Chat.ReactNative#1536]
- Your Rocket.Chat Experimental app version: 1.7.0
- Your Rocket.Chat server version: 2.3.1
- Device (or Simulator) you're running with: iOS/Android

Users cannot set a custom status message on mobile like they can in the browser.

**Comment by diegolmello** [comment]
@msisskin it's not implemented yet. Some work was made on #1176

**Comment by aashaypalliwar** [comment]
I wish to work on this. Thanks!

**Comment by diegolmello** [comment]
@aashaypalliwar No need to ask. Just open a PR and we'll be happy to review it. Thanks.

**Comment by foss-** [comment]
This is now https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1811 and it's looking great. Currently in "Need Review" state. Hope RC team can find the time for review soon.
