### ISSUE TITLE
Adding a feature to pin a particular channel

### ISSUE THREAD

**Issue by Pratikrocks** [RocketChat/Rocket.Chat.ReactNative#1537]
- Your Rocket.Chat Experimental app version: 4.2.0.999999999
- Your Rocket.Chat server version: 2.5.0-develop
- Device (or Simulator) you're running with: Android P

Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.
When new messages arrives in a community channel then other channels are pushed down,It would be nice if there exists a method to pin a tab so that the pinned tab always appears at. The top of all channels ,making it possible to easily access important channels

**Comment by Pratikrocks** [comment]
Can I take this issue?

**Comment by diegolmello** [comment]
The favorite group does that.
I'm afraid we have no plans on adding another way to pin channels on top.
