### ISSUE TITLE
Emoji invisibility in Dark Mode

### ISSUE THREAD

**Issue by apshada** [RocketChat/Rocket.Chat.ReactNative#1540]
- Your Rocket.Chat Experimental app version: 4.2.0.13337
- Your Rocket.Chat server version: 2.5.0-develop
- Device (or Simulator) you're running with: Redmi 3S

Black emoji's and gif's seems to be completely invisible in Dark Mode
![WhatsApp Image 2020-01-09 at 9 04 33 PM (2)](https://user-images.githubusercontent.com/49001649/72082380-11491f00-3326-11ea-9a2a-4f534d9519c4.jpeg)
![WhatsApp Image 2020-01-09 at 9 04 33 PM (1) (1)](https://user-images.githubusercontent.com/49001649/72082387-160dd300-3326-11ea-8107-e8b280a21de1.jpeg)

**Comment by diegolmello** [comment]
I'm afraid there's nothing we can do about that.
