### ISSUE TITLE
Cursor not starting from expected position after writing a mention

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1543]
- Your Rocket.Chat Experimental app version: 4.2.1.999999999
- Your Rocket.Chat server version: 2.5.0-develop
- Device (or Simulator) you're running with: Android P

As the following gif shows, when we write mention tag, then a list of options come up, and when we select one of those and start typing again , the cursor begins from where we left instead of after the tag.
![ezgif com-crop(2)](https://user-images.githubusercontent.com/44807945/72140535-f8d51500-33b6-11ea-9e69-c897bc99894a.gif)

**Comment by ani4aniket** [comment]
Actually sometimes it is working correctly.
![in](https://user-images.githubusercontent.com/31184591/72184105-a545e400-3415-11ea-8f2c-d0e47085c35c.gif)

**Comment by Prateek93a** [comment]
@ani4aniket Thanks for testing. So the issue is not appearing on the iOS device, I guess. Can you try this on Android device also?

**Comment by aashaypalliwar** [comment]
@Prateek93a , I could reproduce the issue on android device. I wish to take this up. Thanks!

**Comment by Prateek93a** [comment]
@aashaypalliwar Ok Thanks for testing.
