### ISSUE TITLE
CAS authentication broken on new app version 4.2.1

### ISSUE THREAD

**Issue by brtptrs** [RocketChat/Rocket.Chat.ReactNative#1545]
- Your Rocket.Chat Experimental app version: 4.2.1
- Your Rocket.Chat server version: 2.3.2
- Device (or Simulator) you're running with: Fairphone 3, Android 9

Since the latest upgrade logging in via CAS is not working any more. On previous versions it was working without any problems.

The CAS login option is shown in the app, redirecting to the login page works, but after a successful login (on the authentication system)  the app just hangs.

**Comment by diegolmello** [comment]
@brtptrs How can I reproduce it?

**Comment by brtptrs** [comment]
We are using basic cas features, so I guess any cas login could be used to debug this issue. 
Unfortunately I can't provide access to our internal system. I could provide debug info, if I knew where to start digging.
