### ISSUE TITLE
'No results found' message on Directory search view not displayed

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1547]
- Your Rocket.Chat Experimental app version: 4.2.1.9999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android P

Similar as #1533 . On the directory view also, we don't get 'no results found' message.

![ezgif com-crop(3)](https://user-images.githubusercontent.com/44807945/72198595-cd553780-3455-11ea-881d-06ec08595c06.gif)

**Comment by aashaypalliwar** [comment]
Hi there! I am working on this.
