### ISSUE TITLE
When some option is clicked in sorting by activity dropdown menu it should close automatically

### ISSUE THREAD

**Issue by devyaniChoubey** [RocketChat/Rocket.Chat.ReactNative#1550]
Your Rocket.Chat Experimental app version: 4.2.1.999999999
    Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
    Device (or Simulator) you're running with: Android 9

**Comment by devyaniChoubey** [comment]
I am on it

**Comment by djorkaeffalexandre** [comment]
Closing: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1608#issuecomment-578941537
