### ISSUE TITLE
When we listen to any audio message then it will be good if the timer is displayed.

### ISSUE THREAD

**Issue by devyaniChoubey** [RocketChat/Rocket.Chat.ReactNative#1557]
when we listen to any audio message then the timer should start until the audio ends so that we can see how much audio we have listened

**Comment by devyaniChoubey** [comment]
I am on this issue

**Comment by srhughes89** [comment]
In my opinion the time should show what you have listen to. It should show the total time until you hit the play button or the slider has moved from the start. As soon as the slider has moved it should show the duration. Right now the bug fix shows the total time when its paused and the duration only when it is playing.

**Comment by Nemental** [comment]
something new here?
