### ISSUE TITLE
Sign In with OAUTH stopped working

### ISSUE THREAD

**Issue by awunder** [RocketChat/Rocket.Chat.ReactNative#1560]
- Your Rocket.Chat Experimental app version: 4.2.1
- Your Rocket.Chat server version: 2.4.1
- Device (or Simulator) you're running with: iPhone but also doesnt work under Android

the issue is that the oauth sign in does not result in an app sign in.. i open the app, sign in via oauth just fine (like before with server version 2.3.1), the sign in form disappears without any error (suggesting a successful sign in) but it does not move ahead to actually sign me in and show me the channels.

sign in itself works just fine with the browser, user and pass are def correct.

another small thing, the app still shows me a user/password field for the sign in, even though its disabled on the server side (and doesnt show up in the browser), which leads to even more confusion.

**Comment by awunder** [comment]
FWIW i have set up a custom oauth provider via my invision power board.

**Comment by diegolmello** [comment]
It's not clear what the issue is.
How can I reproduce it?

**Comment by awunder** [comment]
i could create you a user in my forum.. that way you could try to auth. and see the issue... (?)

**Comment by diegolmello** [comment]
Sure, do it

**Comment by awunder** [comment]
done and sent you an email with the details.

**Comment by awunder** [comment]
fwiw, that was an apache issue.. i had the proxy right but missed to enable the proxy_wstunnel apache module...
