### ISSUE TITLE
"No result found" message not displayed when search don't match any member of the group

### ISSUE THREAD

**Issue by devyaniChoubey** [RocketChat/Rocket.Chat.ReactNative#1561]
Your Rocket.Chat Experimental app version: 4.2.1.999999999
Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
Device (or Simulator) you're running with: Android 9

When we search for members in a room then if our search doesn't matches with any of the members of the room then "No result found" message should be displayed

**Comment by devyaniChoubey** [comment]
I am on it

**Comment by m1-key** [comment]
It is exactly similar to #1533

**Comment by aashaypalliwar** [comment]
@djorkaeffalexandre, Yes, this is a duplicate issue.

**Comment by devyaniChoubey** [comment]
![Screenshot from 2020-01-12 18-50-42](https://user-images.githubusercontent.com/52153085/72219475-8c037b80-356c-11ea-8c26-632e42313cc4.png)

**Comment by devyaniChoubey** [comment]
And i think the issue #1533 was about this search box
![Screenshot from 2020-01-12 18-50-42](https://user-images.githubusercontent.com/52153085/72219743-43998d00-356f-11ea-869c-cb6edc43f81a.png)

**Comment by devyaniChoubey** [comment]
@m1-key  correct me if I am wrong?

**Comment by m1-key** [comment]
@devyaniChoubey Basically issue #1533 is the parent issue and this one (raised by you)  is a sub-part of that as in that issue he showed only the room part not the user one in #1533 . That is what I inferred from that issue.

**Comment by devyaniChoubey** [comment]
But this was not mentioned in issue #1533.That's why I have created this issue.

**Comment by m1-key** [comment]
@devyaniChoubey Can I take this issue ?

**Comment by devyaniChoubey** [comment]
@m1-key I was working on it.

**Comment by diegolmello** [comment]
@m1-key @devyaniChoubey That's open source. There's no dibs.

**Comment by sarthakpranesh** [comment]
As no follow-up is taken on this issue, can I add my fix as a PR?
