### ISSUE TITLE
Language Change does not show proper effect.

### ISSUE THREAD

**Issue by m1-key** [RocketChat/Rocket.Chat.ReactNative#1563]
- Your Rocket.Chat Experimental app version: 4.2.1.999999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android 9

![88bI4f](https://user-images.githubusercontent.com/39923784/72222015-10aec380-3586-11ea-9d8b-d8686fe19600.gif)

Here we can see that when we change the language , it does not show any effect on RoomListView while shows effect only in sidebar. Here we need to restart the app in order to see the full effect of language change.

**Comment by m1-key** [comment]
@djorkaeffalexandre  I would like to work on this.

**Comment by diegolmello** [comment]
@m1-key You don't have to ask. Just open a PR and we'll review it and merge it if the result is satisfactory.
