### ISSUE TITLE
UI of "this room is blocked" should be changed

### ISSUE THREAD

**Issue by devyaniChoubey** [RocketChat/Rocket.Chat.ReactNative#1565]
![Screenshot from 2020-01-13 01-20-24](https://user-images.githubusercontent.com/52153085/72224717-85dcc180-35a3-11ea-937c-30e3f9e9700e.png)

It should be colored differently.

I am working on it.

**Comment by diegolmello** [comment]
It's following the web client appearance.
I'm closing this because it's not really an issue, but I would like to see the approach you've been working on.
