### ISSUE TITLE
Show background view until Avatar is loaded

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1572]
- Your Rocket.Chat Experimental app version: 4.2.1.999999
- Your Rocket.Chat server version: 2.5.0-develop
- Device (or Simulator) you're running with: Android P

As the following gif shows, when avatar has not loaded yet, there is no pre image like thing to indicate that there is an image here. After loading the avatar just pops into the display. This is more noticeable on slow internet. It would be helpful to have some background image like, to show until the actual image has loaded.
![ezgif com-crop(5)](https://user-images.githubusercontent.com/44807945/72263096-2f709100-363e-11ea-835e-66dfd0195c84.gif)

**Comment by Prateek93a** [comment]
I have the following version ready, however I am getting errors related to storybook snapshots while committing changes. 
![ezgif com-crop(4)](https://user-images.githubusercontent.com/44807945/72262876-cab53680-363d-11ea-8ea0-185b1b98ca40.gif)

**Comment by diegolmello** [comment]
@Prateek93a It's looks pretty cool.
You should change update the jest tests before submitting.
Run `yarn test-update`

**Comment by Prateek93a** [comment]
@diegolmello Thank You Sir for the review!
