### ISSUE TITLE
Make users clickable in user interaction messages

### ISSUE THREAD

**Issue by ritwizsinha** [RocketChat/Rocket.Chat.ReactNative#1573]
Your Rocket.Chat Experimental app version: 4.2.1
Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
Device (or Simulator) you're running with: Pixel 3

Currently in  the user interaction messages, we cannot click on the users , make them clickable

## Additional Context
I am working on it
**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by diegolmello** [comment]
I didn't get what you're trying to achieve here.
Can you elaborate?
Thanks.

**Comment by ritwizsinha** [comment]
In the user interaction messages like x user-added y to the room , x muted or unmuted y etc the x and y i.e the users are not clickable, it would be great if clicking on them opens the user info tab

**Comment by diegolmello** [comment]
Oh, you're right. Nice!

**Comment by ritwizsinha** [comment]
I have made the changes in the web client and thus would try to the same in the app , please assign me the issue
