### ISSUE TITLE
In #general channel on most of the messages time is hardcoded as 5:30AM

### ISSUE THREAD

**Issue by devyaniChoubey** [RocketChat/Rocket.Chat.ReactNative#1576]
Your Rocket.Chat Experimental app version: 4.2.1.999999999
    Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
    Device (or Simulator) you're running with: Android 9
![Peek 2020-01-14 03-48](https://user-images.githubusercontent.com/52153085/72297130-3cfb3a80-3681-11ea-88d6-1a6407676b4b.gif)

**Comment by diegolmello** [comment]
That's an issue on the server, that saves those attachments as 00:00.
The app just shows them to you as 05:30 because of the timezone.
