### ISSUE TITLE
When we archive a room we should not able to send messages in it.

### ISSUE THREAD

**Issue by devyaniChoubey** [RocketChat/Rocket.Chat.ReactNative#1577]
Your Rocket.Chat Experimental app version: 4.2.1.999999999
Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
Device (or Simulator) you're running with: Android 9

![Peek 2020-01-14 17-34](https://user-images.githubusercontent.com/52153085/72343735-943af280-36f5-11ea-926f-998351c9660d.gif)

**Comment by devyaniChoubey** [comment]
I would like to work on it

**Comment by diegolmello** [comment]
I think this is a collateral effect of another issue.
It looks like the `subscription.archived` is not being updated.

**Comment by luixxiul** [comment]
For me it is possible to send a message to archived *discussions* on `4.6.4.2118`.

Does `if (room.archived)` check the status of the discussions too?

**Comment by luixxiul** [comment]
The same issue as above is reproduced on `4.7.2.2126`.

Please let me know if I should open a new ticket to track the issue. Thanks!
