### ISSUE TITLE
Disable Dark levels when Light theme is selected.

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1578]
- Your Rocket.Chat Experimental app version: 4.2.1.999999999
- Your Rocket.Chat server version: 2.5.0-develop
- Device (or Simulator) you're running with: Android P

As the gif shows, when light theme is activated, we still see dark level options enabled, on which user can click as well, this might create confusion among the users. It would be helpful to have dark level options to be disabled when light theme is chosen. 

![ezgif com-crop(6)](https://user-images.githubusercontent.com/44807945/72342719-2c83a800-36f3-11ea-9524-5f946b7097a2.gif)

**Comment by diegolmello** [comment]
That feels like a bad UX.
We can discuss it further if you want to, but I'm closing it for now.
Thanks.

**Comment by Prateek93a** [comment]
@diegolmello Yes Sir, I think, there should be some indicator to indicate that the dark levels are not available for light theme, right now the dark levels are clickable for light theme as well, which might create confusion for users.
