### ISSUE TITLE
Mentions are weird 

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.ReactNative#158]
![image](https://user-images.githubusercontent.com/5263975/34311948-d220177e-e747-11e7-9820-4b5d582cc3da.png)

**Comment by geekgonecrazy** [comment]
Even weirder when this happens....

![screenshot_20180106-152110](https://user-images.githubusercontent.com/51996/34644072-6cfd6554-f2f5-11e7-8ab0-d6af277c3e94.png)

**Comment by geekgonecrazy** [comment]
I've seen the same happen for channels
