### ISSUE TITLE
[BUG] Mentions autocomplete does not work on the mobile app.

### ISSUE THREAD

**Issue by alonzzz** [RocketChat/Rocket.Chat.ReactNative#1580]
Mention autocomplete which allows the user to see a list of users in the current channel after typing @... does not pop up the users list on mobile devices, it works fine for the same user on desktop app / native web browser.

It does work on mobile only if the user has the view-d-room & view-outside-room permission but then he can see all the users on the server not only the users in the relevant channel.

How to reproduce, verify your user does not have the view-d-room & view-outside-room permission, join a channel and try to mention other users by typing @ + first letter
On desktop app/web it works as expected

![Screen Shot 2020-01-14 at 10 17 02](https://user-images.githubusercontent.com/35489192/72326340-b746b180-36b7-11ea-99a4-36541d40b2f8.png)

Try the same on mobile, does not work
![Screen Shot 2020-01-14 at 10 18 50](https://user-images.githubusercontent.com/35489192/72326375-c88fbe00-36b7-11ea-8959-a0a37eba0b56.png)

**Comment by marians** [comment]
I can confirm this for version 4.2.3 on iOS. The selection menu appears only after I enter `@` plus one additional letter, which is different from the web app, where the menu appears right after entering `@`.

**Comment by sarthakpranesh** [comment]
I would like to work on this issue!

**Comment by diegolmello** [comment]
@sarthakpranesh You don't have to ask. Just do it and open a PR if you were able to fix it. Thanks.

**Comment by sarthakpranesh** [comment]
@diegolmello just wanted to make sure no one else is working on it.
I understood the bug and it is not just restricted to @, but it is the same case with # and : too.

**Comment by alexander-potemkin** [comment]
Confirming issue. Looking forward for the correction.

**Comment by alexander-potemkin** [comment]
by the way, @diegolmello , can't help understanding why permissions not preventing user from seeing other users in channel, prevents from mentioning him/her?

**Comment by diegolmello** [comment]
@alexander-potemkin Can you give us a reproducible example and/or a video?
I didn't understand what you're talking about exactly.

**Comment by alexander-potemkin** [comment]
@diegolmello , please, find the video here: https://yadi.sk/i/LpI6ymHhL_BIYA

v4.8.0 from the appstores; same user has no issues on Mac app.

**Comment by alexander-potemkin** [comment]
@diegolmello , any updates?

**Comment by diegolmello** [comment]
@alexander-potemkin we've been working on some improvements on the server: https://github.com/RocketChat/Rocket.Chat/pull/18309
We're going to work on them soon on mobile.
Thanks.

**Comment by alexander-potemkin** [comment]
I see, thank you! Is there happens to be any time estimate?

**Comment by diegolmello** [comment]
We're still planning next release, so no.
Most probably September.

**Comment by alexander-potemkin** [comment]
Ok, thank you!

**Comment by ankar84** [comment]
> We're still planning next release, so no.
> Most probably September.

Hi, @diegolmello 
Any plans to release that feature in near future?
Thanks!

**Comment by sumukhah** [comment]
Working on the Issue 👍 
Will send a PR soon

**Comment by alexander-potemkin** [comment]
Cool, thank you!
