### ISSUE TITLE
Crash on 4.2.1 and "broken" account

### ISSUE THREAD

**Issue by rstockm** [RocketChat/Rocket.Chat.ReactNative#1582]
Rocket.Chat Version: 2.3.1 via Snap |
NodeJS Version: 8.15.1 - x64 |
MongoDB Version: 3.6.14 |
MongoDB Engine: wiredTiger

I just installed the RocketChat App 4.2.1 on my iPhone 8. It updated flawless from 4.1.0 to my account. I gave a emoticon-feedback on a posting, and the trouble started:

- the comment didn't show up (this is quite usual, it takes seconds or even minutes)
- In the overview page it read "no comment"
- The app crashed a few seconds after.
- Every attempt to restart the app: immediate crash to Springboard.
- I deletet the app an logged in again: same behavior.
- I deleted the app an logged in with a different account: success!! O__o
- On every other device the first account still works.

What went wrong, and how can I "repair" my first account (I'm admin on my own server, running a Snap install).

**Comment by phoenix-schwarz** [comment]
![2020-01-16 09 10 27](https://user-images.githubusercontent.com/10234000/72515194-c496a400-384f-11ea-9cfb-c624fc010559.png)

Ich have the same issue and got this report on my Android phone. I have the same version on iOS as well. The native desktop client works.

**Comment by rstockm** [comment]
Update: my app "repaired itself" to some degree. I can login and use most of the channels. There is still at least one channel wish triggers an instant crash to Springboard. The "posting of doom" which triggers the crash seems to be in a thread.  I'm on iOS and "report crashes" is turned on, so you should see the crash report - I just triggered a crash right now.
I updatet to 4.2.2 and can still reproduce the crash.

**Comment by rstockm** [comment]
Just to let you know: Release 4.2.3 from today did _not_ solve my "Posting of doom" Problem above. The app still crashes in one channel/thread. It may be related to a "thread within a thread" situation.
Further findings: the iPad is _not_ affected, just the iPhone app.
