### ISSUE TITLE
[BUG] SAML SSO no longer works on previous versions of rocket.chat server

### ISSUE THREAD

**Issue by ryguy222** [RocketChat/Rocket.Chat.ReactNative#1588]
- Your Rocket.Chat app version: 4.2.2.2098
- Your Rocket.Chat server version: 2.3.0 (Official docker container)
- Device (or Simulator) you're running with: Android + iOS 

When attempting to login with SAML (we use Shibboleth) users are able to tap the "Login with SSO" button and sign in, but are then redirected to a page that just says Verified. It never continues. 

This happens on both Android and iOS. This issue started to occur after the Jan 13 update. We've found that this bug is not present on 2.4.1 rocketchat server version. Users who are already authenticated with SAML are still able to use the app. 

![Screenshot_20200115-093407](https://user-images.githubusercontent.com/2319171/72452364-a9a63000-377a-11ea-878b-f6afb58d870a.jpg)

**Comment by diegolmello** [comment]
Hi, @ryguy222.
Thanks for letting us know.
We fixed a bug that was happening on server 2.3.0.
Can you update your server to latest version?
Cheers.

**Comment by ryguy222** [comment]
Unfortunately we typically test new versions of rocket chat for 1-2 weeks before we are allowed to deploy it across our business as we have been burned in the past for upgrading quickly.

**Comment by localguru** [comment]
@diegolmello I do see the same bug on server version 2.2.0. How is this possible with version 2.2.0, if the bug was only introduced with version 2.3.0.

Is that bug fixed in version 2.4.2?

**Comment by localguru** [comment]
Server version 2.4.2 works with Shibboleth login, just tested it. The new mobile clients can't handle the popup window on older server versions.
