### ISSUE TITLE
Respect Accounts_AllowUsernameChange

### ISSUE THREAD

**Issue by m1-key** [RocketChat/Rocket.Chat.ReactNative#1590]
- Your Rocket.Chat Experimental app version: 4.2.1.999999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android 9

Username once set at the time of registration should be non-editable as it will ensure that one user have one username. As currently one user can set different usernames. A warning message should pop up while confirming the username that it is non-editable in future. 
Is it a relevant issue/feature ??

**Comment by diegolmello** [comment]
There's a setting for that on admin:
![image](https://user-images.githubusercontent.com/804994/72663586-069c2300-39d3-11ea-95c4-19918eb93b48.png)

You can create a PR to check for that setting.
Thanks.
