### ISSUE TITLE
[BUG] Avatar change not working properly

### ISSUE THREAD

**Issue by m1-key** [RocketChat/Rocket.Chat.ReactNative#1591]
- Your Rocket.Chat Experimental app version: 4.2.1.999999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android 9

Avatar change is not working properly, if user have an avatar associated with his/her email already then this problem is arising.
![20200116_160615](https://user-images.githubusercontent.com/39923784/72518712-e574ee80-387b-11ea-9ddf-52bacf4ab6de.gif)

**Comment by diegolmello** [comment]
Dup of #441
