### ISSUE TITLE
Hide the pin message option

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1594]
- Your Rocket.Chat Experimental app version: 4.2.2.999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android P

It is a minor improvement. As the gif shows, the Pin message feature is not working on direct message room. I checked the web client, and it doesn't provide the Pin message feature on direct message so on mobile client also, the option should be hidden for Direct message rooms.
![ezgif com-crop(10)](https://user-images.githubusercontent.com/44807945/72526932-85874380-388d-11ea-8a0d-d457ecec794b.gif)

**Comment by sarthakpranesh** [comment]
Hey, I would love to work on this issue

**Comment by Prateek93a** [comment]
@sarthakpranesh Hi. This issue is solved.  Kindly work on other issues

**Comment by akumar1999** [comment]
hey, I was wondering if this issue is fixed or not? I would like to work on the issue and improve it.

Thanks

**Comment by diegolmello** [comment]
@akumar1999 A PR was mentioned above. It's just not merged yet.

**Comment by djorkaeffalexandre** [comment]
Closed by #2114.
