### ISSUE TITLE
Help! Newbie React Native

### ISSUE THREAD

**Issue by Conrado916645** [RocketChat/Rocket.Chat.ReactNative#1596]
Good day sir maam,

can you help me how to start running this app to vs code.

**Comment by m1-key** [comment]
You can follow ```https://github.com/RocketChat/Rocket.Chat.ReactNative#how-to-run``` this to set up the environment.
And then simply open the Rocket.Chat.ReactNative folder in VS Code. Changes made in the code will appear in the emulator once the build is successful.

**Comment by Conrado916645** [comment]
Thanks m1
