### ISSUE TITLE
Minimum password length for New Password field of Profile View is 1 

### ISSUE THREAD

**Issue by m1-key** [RocketChat/Rocket.Chat.ReactNative#1597]
- Your Rocket.Chat Experimental app version: 4.2.1.999999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android 9

On clicking the profile, we get the option for new password. And if we only enter a single character then the ```Save Changes``` button becomes active, which is not efficient. Atleast 6 characters must be present in the password so that it is a bit secure and then only the ```Save Changes``` button becomes active.

**Comment by diegolmello** [comment]
Mostly dup of #1592 
Change that issue to reflect all issues regarding password policy.
Thanks.
