### ISSUE TITLE
Getting error undefined is not an object $_require(_dependencyMap[30]," ./views/RoomView").default in Rocket chat react native

### ISSUE THREAD

**Issue by anjanaNewput** [RocketChat/Rocket.Chat.ReactNative#1604]
I am getting error when try to import Tts from 'react-native-tts' in the MessageBox/index.js 
getting error undefined is not an object $_require(_dependencyMap[30]," ./views/RoomView").default .

Please help me I am not able to add any new react native module in app.

**Comment by djorkaeffalexandre** [comment]
Probably, you need to restart your `metro bundler` or/and `rebuild` the application with `react-native run-android` because you added a new `react-native module` and it can have some native code.
