### ISSUE TITLE
App crashes when add second Server

### ISSUE THREAD

**Issue by Schrammi** [RocketChat/Rocket.Chat.ReactNative#1606]
- Your Rocket.Chat Experimental app version: Experimental: 4.2.4 , Productive 4.2.3 from Appstore
- Your Rocket.Chat server version: 2.4.1
- Device (or Simulator) you're running with: iPhone 11 Pro and no Name Android

When joining a single Server everything is fine and i can chat. Then i can add a second server and the app joins this server also fine. But when switching to the other server, the App goes back to "Join a Server"-Screen.

**Comment by djorkaeffalexandre** [comment]
Hello @Schrammi.
Can you provide more info about this?
If you prefer, you can reach me on `https://open.rocket.chat`, my username `djorkaeff.alexandre`.
I need some steps to reproduce it here and be able to fix it.
Thanks.
