### ISSUE TITLE
[BUG] Reply Message preview not updating

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1609]
- Your Rocket.Chat Experimental app version: 4.2.4.9999999999
- Your Rocket.Chat server version: 2.5.0-develop open.rocket.chat
- Device (or Simulator) you're running with:Android P

This is a bug issue. As the following gif shows, when we already have reply component on the screen, and then try to reply on some other message, the reply component is not updated, it still shows the previous message on which we used reply action. Moreover when we write a reply, it gets sent to the latest message on which we used the reply action.
![ezgif com-crop (10)](https://user-images.githubusercontent.com/44807945/72826419-d1c3f080-3c9e-11ea-9af2-b1316bb42164.gif)

**Comment by djorkaeffalexandre** [comment]
Closed by #2114.
