### ISSUE TITLE
Error uploading: invalid file type

### ISSUE THREAD

**Issue by daltondiaz** [RocketChat/Rocket.Chat.ReactNative#1611]
- Your Rocket.Chat Experimental app version: 4.2.4.13691
- Your Rocket.Chat server version: 2.4.2
- Device (or Simulator) you're running with: Moto g6 Android 9

I've the problem in the lastest app for android.

![rocketchaterror](https://user-images.githubusercontent.com/3844467/72817818-2e94bc00-3c49-11ea-866d-909db95fb19b.jpeg)

This error occur only in mobile app.

Config. from server

![screenshot_3](https://user-images.githubusercontent.com/3844467/72818754-c47d1680-3c4a-11ea-8f8a-23d2f31abb97.png)

**Comment by diegolmello** [comment]
`Leave it blank for accepting all media types`
