### ISSUE TITLE
Images are not sent

### ISSUE THREAD

**Issue by giterium** [RocketChat/Rocket.Chat.ReactNative#1647]
- Your Rocket.Chat app version: 4.2.3.273
- Your Rocket.Chat server version: 2.4.1
- Device (or Simulator) you're running with: Iphone XS

Error uploading image into direct chat or channel. From the desktop are sent.

There is no such problem with older versions of the server (0.7.4)

If the image format is png then there is no problem. Although maybe they are already reduced

**Comment by diegolmello** [comment]
How are you uploading?
Do you know the server file upload setting?
Can you reproduce it on https://open.rocket.chat?

**Comment by giterium** [comment]
In 4.3.1 this bug is not present you can close it

**Comment by giterium** [comment]
No the problem has not disappeared. One specific photo is loaded and the others are not. I didn't change the file upload settings. Docker version.

**Comment by giterium** [comment]
And I can send this one photo as many times as I want

**Comment by giterium** [comment]
Photos sent via watsapp are also transmitted

**Comment by giterium** [comment]
Probably problems with the file size

**Comment by giterium** [comment]
The only photo made on the phone that is sent weighs less than others-1107 kb, the rest is more than 1.5 mb

**Comment by giterium** [comment]
Changed to store upload files in the file system nothing has changed. Only small photos are uploaded. :(

**Comment by giterium** [comment]
No there are smaller photos that are not loaded. I don't know what's going on. :)

**Comment by giterium** [comment]
Screenshots taken from the screen uploads normally. Apparently there is a problem with heic processing.

**Comment by giterium** [comment]
Small horizontal photos are sent normally. I'm not sure of anything, though. Does anyone even care about this? :)

**Comment by giterium** [comment]
If you set the camera to save as jpg, they are not sent either

**Comment by diegolmello** [comment]
Can you upload that photo to https://open.rocket.chat?
Try sending it to me: `@diego.mello`

**Comment by giterium** [comment]
Thanks for the help. Everything was solved by setting the client_max_body_size parameter in config of nginx.
