### ISSUE TITLE
[BUG] Sometimes subscriptions aren't loaded

### ISSUE THREAD

**Issue by djorkaeffalexandre** [RocketChat/Rocket.Chat.ReactNative#1650]
- Your Rocket.Chat Experimental app version: 4.3.1
- Device (or Simulator) you're running with: iOS 13, iPhone 8

I have some subscriptions on this server, and this was cleared on database and not loaded from `rooms.get` because I sent an updated at new.

<img width="1620" alt="Screen Shot 2020-02-03 at 10 06 43" src="https://user-images.githubusercontent.com/29778115/73657755-b4fdc480-4671-11ea-8477-f5167f740d80.png">

**Comment by diegolmello** [comment]
@djorkaeffalexandre Ok, but can you reproduce it on production?
Isn't this related to RN's Fast Refresh only?

**Comment by djorkaeffalexandre** [comment]
Unfortunately, I can't reproduce it on production, but it occurred before the RN's Fast Refresh starts, my screenshot was really late, sorry.
I'll try to get some steps to reproduce.
