### ISSUE TITLE
[FEATURE] Sticky Date Header

### ISSUE THREAD

**Issue by srhughes89** [RocketChat/Rocket.Chat.ReactNative#1651]
This is a feature request. It would be nice if there was a sticky date header that stays at the top indicating when the message was sent. Similar like Telegram. Attached is an image of Telegram.

![IMAGE 2020-02-03 16:00:59](https://user-images.githubusercontent.com/37354069/73690453-5ef34600-469e-11ea-8928-ebc8e825582f.jpg)

**Comment by sarthakpranesh** [comment]
I would like to work on this feature if no one else is.

**Comment by danilaandronov** [comment]
Hello everyone, have you done this feature?
