### ISSUE TITLE
[FEATURE] Chat Tabs at the Bottom

### ISSUE THREAD

**Issue by srhughes89** [RocketChat/Rocket.Chat.ReactNative#1652]
It would be neat to implement chat tabs at the bottom of the chat view. The tabs I would like to have is Direct Message, Channels, Groups, and Favorites. I would also think it should be able to be disabled in the settings if a person doesn't want that feature.

**Comment by diegolmello** [comment]
I'll comment your suggestion with the design team.
This kind of request is more appropriate for a fork then for us to refactor our ux.
Thanks.
