### ISSUE TITLE
[Bug] No sound from voice messages

### ISSUE THREAD

**Issue by srhughes89** [RocketChat/Rocket.Chat.ReactNative#1653]
There is a bug on iOS where there is no sound that comes out when you are in silent mode. 

How to reproduce.
Flip the silent mode switch on the side of the phone and you will not get any sound.

**Comment by diegolmello** [comment]
https://github.com/react-native-community/react-native-video#ignoresilentswitch

**Comment by srhughes89** [comment]
Thank you that fixes it.
