### ISSUE TITLE
[Bug] Play multiple voice message at a time

### ISSUE THREAD

**Issue by srhughes89** [RocketChat/Rocket.Chat.ReactNative#1654]
There is a bug that it will play multiple voice messages at a time. It should only play one at a time. Also it would be neat if it will automatically play the next voice message in the view.

**Comment by hmncube** [comment]
@diegolmello When fixing this issue is it ok to fix this part only `There is a bug that it will play multiple voice messages at a time. It should only play one at a time. ` and leave out this part `Also it would be neat if it will automatically play the next voice message in the view.`

**Comment by diegolmello** [comment]
@hmncube Sure!
