### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by cdisabatino** [RocketChat/Rocket.Chat.ReactNative#1656]
## Describe the bug
I cannot upload files (documents, photos, sound) from the iOS mobile application. From the windows client and from the web interface, it works. I tested with mobile data and wifi. The rocketchat server is under docker. It is configured to accept all types of files. It is not a file size issue. The error displayed is "Error uploading, Invalid file type", while all types are authorized and work from windows or web. I have the same problem with android, I opened another ticket for android.

Thanks

## Screenshots
![rocketchat_error_upload](https://user-images.githubusercontent.com/46713357/73757654-d4781880-4769-11ea-8baa-d028ffc0145a.jpg)

## Devices and Versions
Version server (docker) : 2.4.7
Version iOS application : 4.3.1
Phone : iPhone 11 pro, iOS updated. **And other**

**Comment by diegolmello** [comment]
@cdisabatino Is this related to #1647 ?

**Comment by cdisabatino** [comment]
> 
> 
> @cdisabatino Is this related to #1647 ?

My problem is not corrected. With the windows client or the web interface, I can upload a 8.73 MB filesize. A file, photo or screenshot of less weight is refused with the android and iOS client. The same file format is accepted with the windows and web client but not android / iOS.

**Comment by diegolmello** [comment]
Ok, it seems to be a filesize issue then.
Duplicated of #1449.
Please try https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1449#issuecomment-584097599

Feel free to comment there if it's related to file size or give us more details here.
Thanks.

**Comment by cdisabatino** [comment]
The problem is not related to the file size. A file does not upload from the android application. With the same file, on the same phone from the web interface the file uploads correctly. I tested with the android application to upload the same file on the server "https://open.rocket.chat/" and it works.

My server is under docker. I don't use Nginx but a LOAD Balancer. I haven't settings like "client_max_body_size". I have no problems from the web interface and not via the Windows client either.


**Here are the logs when it works from the Windows client :**
> rocketchat_1       | UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/bCED34*****?token=*****************&progress=0.0012950272739035644
rocketchat_1       | UploadProxy ➔ debug Correct instance
rocketchat_1       | UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/bCED34*****?token=*****************&progress=0.017433071616731365
rocketchat_1       | UploadProxy ➔ debug Correct instance
rocketchat_1       | UploadProxy ➔ debug Upload URL: /ufs/FileSystem:Uploads/bCED34*****?token=*****************&progress=0.03462933282619863
rocketchat_1       | UploadProxy ➔ debug Correct instance
..............
..............
..............
rocketchat_1       | Meteor ➔ method canAccessRoom -> userId: *****************, arguments: ["**********************************","*****************"]
rocketchat_1       | Integrations ➔ Outgoing WebHook.debug Execute Trigger: fileUploaded
rocketchat_1       | Integrations ➔ Outgoing WebHook.debug Got the event arguments for the event: fileUploaded { event: 'fileUploaded',



**Here are the logs when it doesn't work from the android client :**
> rocketchat_1       | API ➔ debug GET: /api/v1/subscriptions.get?updatedSince=2020-02-10T13%3A57%3A37.217Z
rocketchat_1       | Meteor ➔ method subscriptions/get -> userId: *****************, arguments: [{}]
rocketchat_1       | API ➔ debug Success { statusCode: 200,
rocketchat_1       |   body: { update: [], remove: [], success: true } }
rocketchat_1       | API ➔ debug GET: /api/v1/rooms.get?updatedSince=2020-02-10T13%3A57%3A37.217Z
rocketchat_1       | Meteor ➔ method rooms/get -> userId: *****************, arguments: [{}]
rocketchat_1       | Meteor ➔ method UserPresence:online -> userId: *****************, arguments: []
rocketchat_1       | API ➔ debug Success { statusCode: 200,
rocketchat_1       |   body: { update: [], remove: [], success: true } }


Thank you

**Comment by diegolmello** [comment]
What type of file?
Can you post a screenshot of your file upload settings here? (suppress credentials)

**Comment by diegolmello** [comment]
> I tested with the android application to upload the same file on the server "https://open.rocket.chat/" and it works.

It's something on your server then.
Let's fix it.

**Comment by cdisabatino** [comment]
I tested with docx, ods, txt, mp4, jpg formats.
I'm using an official docker image "https://hub.docker.com/r/rocketchat/rocket.chat/tags".
I'm using the 2.4.7 tag. With the tag 1.3.2 I had the same problem.

Here are the screenshots.
![rocketchat_fileupload_conf](https://user-images.githubusercontent.com/46713357/74163229-5a8cd700-4c22-11ea-8071-b422e5955360.png)

![rocketchat_fileupload_conf2](https://user-images.githubusercontent.com/46713357/74163247-5fea2180-4c22-11ea-99c6-618bc355ee46.png)

**Comment by djorkaeffalexandre** [comment]
@cdisabatino, please, remove the `*` at `Accepted Media Types`, you need to leave it blank to accept all media types.

**Comment by cdisabatino** [comment]
Thanks, it works. It is specified to leave blank to authorize all formats. But, to configure our rocketchat server, I use docker-compose.yml and I use the attribute "OVERWRITE_SETTING_FileUpload_MediaTypeWhiteList". If I leave blank, the "empty" value is not supported and rocketchat keeps the previous value.

For example, via the web interface, if I add "image/*, audio/*" and in the docker-compose.yml I leave blank, I restart the docker instance and the previous configuration is kept with "image/*, audio/*".

After testing the Windows client and the web interface, putting "*" as the value, it works and the value is taken care of with docker-compose.yml. That's why I put "*".

Is there a way to authorize all formats via docker-compose.yml ?

Thanks for your help,
Christophe
