### ISSUE TITLE
Not sending the message in the reply section in the notification

### ISSUE THREAD

**Issue by cygnusm** [RocketChat/Rocket.Chat.ReactNative#1658]
- Your Rocket.Chat Experimental app version: 4.2.1
- Your Rocket.Chat server version: 2.3.0
- Device (or Simulator) you're running with: huawei 7x

When i reply a message from notification section, the message does not send and i can not see the massage in convesation.

**Comment by sarthakpranesh** [comment]
Hey I would like to work on this issue.

**Comment by diegolmello** [comment]
@cygnusm Try on 4.4.0 beta.

**Comment by sarthakpranesh** [comment]
Working in the latest develop branch
version: 4.5.1.9999999
server version: 3.1.0-develop
device: Redmi 5 ( Android 10 )

I think this issue can be closed @diegolmello @cygnusm
