### ISSUE TITLE
New UI design for login,signup and forgot password screen

### ISSUE THREAD

**Issue by saketkumar95** [RocketChat/Rocket.Chat.ReactNative#166]
The current UI design of login,signup and forgot password screen looks a bit outdated and have some glitches too. We should change the whole UI of these screen first.

@rafaelks @ggazzo Any suggestions with the UI? Should I start the work?

**Comment by ggazzo** [comment]
@saketkumar95 we have a designer working on new design... but it`s not ready yet =/... for now you can work to fix the bugs that you found. You can open a issue for each bug that you find...
