### ISSUE TITLE
[Bug] Disable User Join and Leave Messages

### ISSUE THREAD

**Issue by srhughes89** [RocketChat/Rocket.Chat.ReactNative#1662]
When these options are enabled it doesn't disable them on the app. It works on the web version but not the app.

Hide "User Join" messages
Hide "User Leave" messages
Hide "User Removed" messages
Hide "User Added" messages
Hide "User Muted / Unmuted" messages

**Comment by djorkaeffalexandre** [comment]
Duplicated of #1581
