### ISSUE TITLE
Cannot login to my company's server

### ISSUE THREAD

**Issue by j75** [RocketChat/Rocket.Chat.ReactNative#1665]
Login to https://rocket.oodrive.net/ works in a browser, but the Android application displays a message claiming
```
Oops!

The URL you have entered is not valid. Try again
```
(reverse  translated from French, see the attached screenshot).
![Screenshot_Rocket Chat_20200124-115039](https://user-images.githubusercontent.com/1899106/73064409-14511d00-3e99-11ea-888d-56d058c9cf0a.png)

**Comment by sarthakpranesh** [comment]
I would like to work on this issue if no one else is

**Comment by diegolmello** [comment]
@j75 You're using server version 0.59.3.
Our app supports only servers 0.70.0+.

**Comment by diegolmello** [comment]
@Foxeronie @illo86 Please open another issue or ping me on https://open.rocket.chat at `diego.mello` and I'll take a look.
Thanks.
