### ISSUE TITLE
[IMPROVEMENT] Use whole screen on onboarding

### ISSUE THREAD

**Issue by sarthakpranesh** [RocketChat/Rocket.Chat.ReactNative#1668]
- Your Rocket.Chat Experimental app version: 4.4.0.999999999
- Your Rocket.Chat server version: 3.0.0-rc.2
- Device (or Simulator) you're running with: Redmi 5

As soon as the app starts we are greeted with a "Welcome to Rocket.Chat" screen. This screen and some of the following screens aren't utilizing the mobile screen available efficiently as all the buttons, text and images are cramped towards the top and the bottom is left unutilized. It would be better if we use the whole real estate of the screen offered by the device.

![1](https://user-images.githubusercontent.com/41206172/73909176-ef659c80-48d1-11ea-8de7-6f10cb17275c.jpeg)
![2](https://user-images.githubusercontent.com/41206172/73909180-f4c2e700-48d1-11ea-81b5-1adcc446915e.jpeg)

Would I like to Work on this improvement: Yes

**Comment by djorkaeffalexandre** [comment]
Closing this because we changed all the OnBoarding screens.
I think the new onBoarding is doing a great utilization of the device screen. 😁

**Comment by sarthakpranesh** [comment]
Yeah, it definitely is :rocket:
