### ISSUE TITLE
Can't start in Android emulator

### ISSUE THREAD

**Issue by AndreyWV** [RocketChat/Rocket.Chat.ReactNative#1669]
- Your Rocket.Chat Experimental app version: 4.4.0
- Your Rocket.Chat server version: -
- Device (or Simulator) you're running with: Android Studio Pixel 2 emulator (Android 10 Q, and Android 9 Pie)

App trying to start but hangs on splash screen.
In real device starts normally.

![image](https://user-images.githubusercontent.com/29225873/73938000-6b261000-48f7-11ea-89c9-e5de1966a669.png)

Steps:
```
$ git clone git@github.com:RocketChat/Rocket.Chat.ReactNative.git
$ cd Rocket.Chat.ReactNative
$ yarn install
$ yarn global add react-native-cli
$ yarn
$ reract-native link
$ react-native run-android
$ react-native start
```

**Comment by sarthakpranesh** [comment]
@AndreyWV I think you should try running the metro bundler first.
react-native start
react-native run-android

**Comment by AndreyWV** [comment]
It works in this order, Thanks!
