### ISSUE TITLE
Random discussion room name when opened from push notification

### ISSUE THREAD

**Issue by mar-v** [RocketChat/Rocket.Chat.ReactNative#1671]
- Your Rocket.Chat app version: 4.3.1.2102
- Your Rocket.Chat server version: 3.0.0.rc2
- Device (or Simulator) you're running with: HT70 

Push notification from discussions reflect random room name in the notification, and in the app when you open the room from notification. If you find it in the channel and open from here, the room name is OK (as set in the channel). 

![Discussion_room_name](https://user-images.githubusercontent.com/47217833/73957859-b2b89600-490f-11ea-830d-6369ae370605.png)

Expected behaviour: reflecting correct discussion room name both in the notification and in the app when you open the room from the Push.

**Comment by diegolmello** [comment]
We need to fetch room title like this: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/rocketchat.js#L1128

**Comment by devyaniChoubey** [comment]
@diegolmello I am not getting push notifications in rocket.chat develop. But i was getting notifications on the app which I have downloaded from play store.Is there any problem in my development setup?

**Comment by djorkaeffalexandre** [comment]
It was fixed by #1758.
