### ISSUE TITLE
[BUG] Selecting Different Avatar under Profile does not change the Avatar

### ISSUE THREAD

**Issue by sarthakpranesh** [RocketChat/Rocket.Chat.ReactNative#1677]
- Your Rocket.Chat Experimental app version: 4.4.0.9999999
- Your Rocket.Chat server version: 3.0.0-develop
- Device (or Simulator) you're running with: Redmi 5

Bug - In the profile view, pre-existing avatars ( like profile image stored when login with Github ) on selection does not change the avatar of the account. Rather soon after selecting the desired avatar and clicking "Save Changes" the avatar shifts back to the old one.

Expected behavior: Avatar should change on the selection of different avatars available like in the web client.

Would I like to work on it: YES

**Comment by djorkaeffalexandre** [comment]
Duplicated of #441 .
