### ISSUE TITLE
Push notifications should be on by default in direct messages

### ISSUE THREAD

**Issue by brittyazel** [RocketChat/Rocket.Chat.ReactNative#1681]
By default I have my push notifications set to the default which is only when directly @ mentioned. This is perfectly fine in group chat channels, but in direct messages this rule is also used. This is an issue, because nobody @ mentions you in a direct message, and in reality every message in a direct message is an @ mention conceptually. 

I propose that direct messages should use a different ruleset for push notifications than channels. Push notifications should be on by default when directly messaged so we don't miss messages. Right now I have to go into each direct message and toggle the push notify setting to "all messages"

**Comment by diegolmello** [comment]
That's a setting on the server. You can change that default if you're admin.

**Comment by brittyazel** [comment]
Interesting. Yes I am an admin. Can you point me to where that setting is? I must have missed it
