### ISSUE TITLE
[BUG] Long pressing Images does not open Menu

### ISSUE THREAD

**Issue by sarthakpranesh** [RocketChat/Rocket.Chat.ReactNative#1683]
- Your Rocket.Chat Experimental app version: 4.4.0.9999999
- Your Rocket.Chat server version: 3.0.0-develop
- Device (or Simulator) you're running with: Redmi 5

BUG - The Web client has a menu for messages only having an image that is uploaded on the channel which includes features like delete, etc. The same or similar menu does not appear on the app on long pressing the image.

Expected Behavior - Long Pressing the message containing only an image in the channel should open a menu with relevant options related to that message

**Comment by djorkaeffalexandre** [comment]
Duplicated of #1193.
