### ISSUE TITLE
Replies/Threads enhancement to the mobile app

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat.ReactNative#1686]
- Your Rocket.Chat Experimental app version: 4.4.0.14096
- Your Rocket.Chat server version: 2.4.8
- Device (or Simulator) you're running with: Android

1) - [ ] Replies/Threads replies should be hidden from the channel/room chat (pretty much like Slack does)

I've also suggested this on [Rocket.chat#16530](https://github.com/RocketChat/Rocket.Chat/issues/16530)
Feel free to close this `task`, but I'd really like to have more input from managers and users, about these ideas i gave.

**Comment by sarthakpranesh** [comment]
This is how Slack works if we tick the "also send to channelName" box while we are replying to a thread it will get displayed with all messages and shown in the screenshot
By doing so it would be easier to keep less important replies in the thread hidden from the normal flow of messages and the once which are very important and worthy of being outside the thread are ticked while the reply is being made and they can be seen outside the thread too.

This would help us have a cleaner workplace inside the channel.
![Filename](https://user-images.githubusercontent.com/41206172/74088587-ffda6a80-4abd-11ea-907e-9c741db9e9d8.jpeg)

**Comment by diegolmello** [comment]
Both clients must follow the same behaviour.
I'm closing this in favor of https://github.com/RocketChat/Rocket.Chat/issues/16530
