### ISSUE TITLE
missing user name for status messages, like 'Has joined channel', 'Message removed' etc. 

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.ReactNative#1689]
- Your Rocket.Chat Experimental app version: 4.4.0 (and 4.3.1 stable version)
- Your Rocket.Chat server version: 2.4.5
- Device (or Simulator) you're running with: OnePlus 7 Pro (Android 10.0.3)

It would be helpful if the user name was displayed in the status messages, such as 'Has joined channel', 'Message removed'. In their current form, the status messages are not very informative.

![rc](https://user-images.githubusercontent.com/8544984/74109101-d898a180-4b80-11ea-81cd-c1dbe41752a0.png)

**Comment by youssef-md** [comment]
Thank you for the advice, I will do this.

**Comment by PeGaSuS-Coder** [comment]
Any news about this one? is #2553 WIP?
It would be really great to see the username in all the message types that this issue pointed out.

Cheers
