### ISSUE TITLE
Browser clear cache

### ISSUE THREAD

**Issue by inimatic** [RocketChat/Rocket.Chat.ReactNative#1690]
I changed an ssl certificate on my server (self sighed certificate changed to Sectigo issued certificate). But found no way to clear cache in the Android Rocket.Chat application browser to let it reload new certificate. So I couldn't login to the server at all with the error: couldn't to server.
In Chrome and other browsers alone after cache clearance they work perfect.
I tried:
Clear Rocket.Chat local server cache.
Clear cache in all standalone browsers.
Clear all android application cache.
Clear Rocket.Chat application data and cache.
Reinstall application.
AND combinations of the mentioned above without effect.

- Your Rocket.Chat Experimental app version: 4.4.0
- Your Rocket.Chat server version: 2.4.7
- Device (or Simulator) you're running with: Samsung

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by djorkaeffalexandre** [comment]
Hey @inimatic.
It shouldn't be a problem on our app when you change your SSL certificate.
Can you try on a web browser on your device, or in another device? Maybe it can be a wrong configuration on your SSL certificate.
If it doesn't work, please, reach me in `https://open.rocket.chat`, my username is `djorkaeff.alexandre`.
Thanks.

**Comment by inimatic** [comment]
I found an issl chain issue in my sertificate trying to get 
`curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: ai.stipot.com" -H "Origin: mysite.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://mysite/websocke`
So I added CA Bundle certificate text to the end of my *.crt certificate file. It fixed the issue with connecting to my server from Android and iPhone.
