### ISSUE TITLE
Choose between browser and webview when opening links. 

### ISSUE THREAD

**Issue by monarkh-karina** [RocketChat/Rocket.Chat.ReactNative#1693]
- Your Rocket.Chat Experimental app version: 4.3.1

Currently, all the links are opened in the webview with further suggestion to open them in, for example, Samsung browser (Android) or Safari (iOS): 
![links](https://user-images.githubusercontent.com/45059765/74174440-a0ef2f80-4c3c-11ea-91fa-1a92043f9c2a.png)

![links_1](https://user-images.githubusercontent.com/45059765/74174467-acdaf180-4c3c-11ea-99b3-86023b9a5327.png)

It would be great to give users the opportunity to choose between webview/browser to be a default option for opening links.

**Comment by Prateek93a** [comment]
Is something like this fine? I will change the view name and setting name if needed.
![ezgif com-crop](https://user-images.githubusercontent.com/44807945/74319749-740a5c00-4da5-11ea-93ef-5ea620822ad7.gif)

**Comment by mikelavrik** [comment]
that would be great!
