### ISSUE TITLE
Audio messages can be recorded via mobile app despite being disabled in server settings. 

### ISSUE THREAD

**Issue by monarkh-karina** [RocketChat/Rocket.Chat.ReactNative#1695]
- Your Rocket.Chat Experimental app version: 4.3.1
- Your Rocket.Chat server version: 2.3.2
- Device (or Simulator) you're running with: Samsung Galaxy J7

Steps to reproduce: 
1. Open Administration -> Message -> Audio Message -> disable Audio Recorder. 
2. Open chat -> record audio message -> send it successfully in spite of server settings. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45059765/74179444-262b1200-4c46-11ea-8dea-7a5c40fc9776.gif)

**Comment by sarthakpranesh** [comment]
What should be the possible fix like, do we want to show the recording feature irrespective of the setting is enabled and then show message feature not enabled on server or do we preferre to not show the recording mic if the setting is not enabled

**Comment by djorkaeffalexandre** [comment]
It was fixed by #1764, thanks.
