### ISSUE TITLE
[BUG] [FEATURE] @username not rendered as display name

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.ReactNative#1706]
- Your Rocket.Chat Experimental app version: 4.4.0 (and 4.3.1 stable version)
- Your Rocket.Chat server version: 2.4.5
- Device (or Simulator) you're running with: OnePlus 7 Pro (Android 10.0.3)

If a user is mentioned with @username in a channel, the @username is not translated with the display name (first name, last name). The corresponding feature on the server is activated. 

Android App:
![grafik](https://user-images.githubusercontent.com/8544984/74290939-a0859000-4d33-11ea-9584-e50ffa9ab450.png)

Desktop Client:
![grafik](https://user-images.githubusercontent.com/8544984/74291305-c3647400-4d34-11ea-9e14-c71ec809e6a9.png)

**Comment by ozata** [comment]
I am on this issue.

**Comment by diegolmello** [comment]
Fixed on #1758
