### ISSUE TITLE
[BUG] paragraphs, space lines are not rendered

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.ReactNative#1707]
- Your Rocket.Chat Experimental app version: 4.4.0 (and 4.3.1 stable version)
- Your Rocket.Chat server version: 2.4.5
- Device (or Simulator) you're running with: OnePlus 7 Pro (Android 10.0.3)

Paragraphs and space/emtpy lines are not rendered

Andriod App:
![grafik](https://user-images.githubusercontent.com/8544984/74291697-05da8080-4d36-11ea-9032-7805f685807d.png)

Desktop Client:
![grafik](https://user-images.githubusercontent.com/8544984/74292003-15a69480-4d37-11ea-9a5c-9b8c2c56b0b6.png)

**Comment by aKn1ghtOut** [comment]
Working on this

**Comment by diegolmello** [comment]
Duplicated of #1513
