### ISSUE TITLE
Add empty space when custom emoji is added

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1717]
- Your Rocket.Chat Experimental app version: 4.4.0.9999999999
- Your Rocket.Chat server version: 3.0.0-rc.8
- Device (or Simulator) you're running with: Android P
As the following gif shows, custom emojis are not displayed when there is no space between text and emoji
![ezgif com-crop(1)](https://user-images.githubusercontent.com/44807945/74443090-9fba3e80-4e98-11ea-9621-4eecbe03a545.gif)

**Comment by diegolmello** [comment]
The issue is that we should add an empty space before the custom emoji, if there's none yet.
