### ISSUE TITLE
Rocket.Chat emojis icon missing from message box

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.ReactNative#1737]
Samsung S9 with Samsung Android 10

Experimental 4.4.0.14457
Standard 4.4.0.2106

Server 2.4.8

Just noticed there is no longer a Rocket.Chat emoji button in the message box in either version.

I can still type :mycustomemoji: but the chooser icon is not there.

Standard Android emojis available via keyboard.

Not sure when this changed.

Also not sure if it is a server setting, React setting, or Android 10?

**Comment by djorkaeffalexandre** [comment]
Hello @reetp, we removed them to keep same experience of our iOS app, now to see custom emojis you need to put some `:` on the MessageBox.

**Comment by reetp** [comment]
Sorry, but that is a *real* retrograde step. Even the whatsapp piece of junk has it. And Signal. And telegram. Just not Rocket.Chat ;doh:

That's a nightmare if you don't know the emoji you want. Or if someone adds one I want to use and I don't know what it is called.

I like to look at the emojis before I send and I don't remember the names of them all.

Please make iOS like Android WAS.

Or give us a setting to enable/disable rather than just take it away thinking it is a good idea. Not everything is progress. iOS is not always right, particularly when it is wrong.  And if I really wanted an iOS experience I would buy one. I don't as I think they are awful.

Please revert this one.

**Comment by reetp** [comment]
I also looked through the release notes again and can't find this mentioned anywhere.

If you are going to make these sorts of changes which break normal behaviour you must make people aware first and look for comments.

This is **not**  Android normal behaviour.

By all means make it a switchable option but do not just turn it off just because you think it is a great idea. Not everyone loves iOS.

And personally this change is INTENSELY annoying and frustrating as I cannot remember or find my emojis because I am used to NOT having to remember them.

Please revert or make it optional thank you.

**Comment by diegolmello** [comment]
Hi, @reetp.
Don't forget this is a beta version.
We're testing new stuff.
Emoji keyboard raises some visual glitches (like messages text overlapping) we wanted to fix.
We are reverting it because we'll not remove new features like that.
Thanks for your feedback.

**Comment by reetp** [comment]
Hi @diegolmello 
> Hi, @reetp.
> Don't forget this is a beta version.

> Experimental 4.4.0.14457
> Standard 4.4.0.2106

Happens on both - please read my original comment again

> We're testing new stuff.

See above....

> Emoji keyboard raises some visual glitches (like messages text overlapping) we wanted to fix.

Yup I can see that, but simply removing it is not the way when it breaks established practice.

> We are reverting it because we'll not remove features like that.

Thank you :-)

Note things like this happen as well.... So you can't remove the emoji itself, but if you have a viewable list you don't notice some things....

https://github.com/RocketChat/Rocket.Chat/issues/16616

> Thanks for your feedback.

Always ;-)

**Comment by reetp** [comment]
Got them back in Experimental.

Ahhhhhhhhhh relief. Thank you.
