### ISSUE TITLE
Input field shows microphone and allows recording while audio messages are disabled on server 

### ISSUE THREAD

**Issue by phriedrich** [RocketChat/Rocket.Chat.ReactNative#1756]
- Your Rocket.Chat Experimental app version: 4.4.0.14681
- Your Rocket.Chat server version: 3.0.1
- Device (or Simulator) you're running with: iOS 

Input field shows microphone and allows recording while audio messages are disabled on server. 

This should be hidden if audio messages are disabled.

**Comment by diegolmello** [comment]
@phriedrich It's not implemented yet. Thanks for opening this issue.
