### ISSUE TITLE
Markdown is cutting off text

### ISSUE THREAD

**Issue by AgentTNT** [RocketChat/Rocket.Chat.ReactNative#1778]
- Your Rocket.Chat Experimental app version: 4.4.0 (stable from app sotres)
- Your Rocket.Chat server version: 3.0.1
- Device (or Simulator) you're running with: Android 10 and iOS

When markdown is disabled on both Android and iOS, we see the expected format:
![markdown-disabled](https://user-images.githubusercontent.com/29238486/75160424-f240f980-56e7-11ea-96cc-280aae1e95f2.jpeg)

However when markdown is enabled, the first line is removed and the proper markdown visualization is not honored:
![markdown-enabled](https://user-images.githubusercontent.com/29238486/75160485-100e5e80-56e8-11ea-8137-3ae7e2a5b79d.jpeg)

*edit* Additional styles
![markdown-disabled-2](https://user-images.githubusercontent.com/29238486/75183028-9ee2a180-570f-11ea-85e5-31acafe42ac5.jpeg)
![markdown-enabled-2](https://user-images.githubusercontent.com/29238486/75183034-a0ac6500-570f-11ea-84fc-6ff43d708a2b.jpeg)
![markdown-disabled-3](https://user-images.githubusercontent.com/29238486/75183040-a30ebf00-570f-11ea-9994-fd010480ca6d.jpeg)
![markdown-enabled-3](https://user-images.githubusercontent.com/29238486/75183044-a6a24600-570f-11ea-875b-b9fb22d5653e.jpeg)

**Comment by sarthakpranesh** [comment]
I found out that when the string
```line1
line2
line3```
is passed in the Parser module from commonmark inside the container/markdown then the processed result has the wrongly parsed 
string literal as
line2
line3```

The Parser.parse function is causing this issue as of my understanding.

**Comment by ankar84** [comment]
I see that it is an app issue, because web version all markdown renders correctly.
Here is an examples.
![image](https://user-images.githubusercontent.com/4023037/82630668-14211e00-9bfc-11ea-9d76-5af3229c9edd.png)
![image](https://user-images.githubusercontent.com/4023037/82630688-2307d080-9bfc-11ea-9879-ccc6e336f139.png)
and app shows that like this
