### ISSUE TITLE
Need Remote Push Notification Support For Android and IOS

### ISSUE THREAD

**Issue by anveshfactorly** [RocketChat/Rocket.Chat.ReactNative#1782]
- Your Rocket.Chat Experimental app version: 1.0
- Your Rocket.Chat server version: 
- Device (or Simulator) you're running with: iphone7

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

Hello There Thanks for providing amazing app , really appreciated your hard work and efforts I downloaded your project and setup with new bundle identifier , also setup all required one for both android and ios and sucessfully able to run the app with new setup 

Now its come to push notification - For android and IOS both are not supported remote notification For Android , i setup the FCM account and for IOS i configured with required APNS certificates But now i have questions that for android what additional thing i need to do with setup FCM , where i need to add my machine key ? or do i need to do some extra configuration ? 

For IOS i am done with setup pem and .CER file but where i can upload For push notification i refer to this documentation :https://rocket.chat/docs/administrator-guides/notifications/push-notifications/ Please help me to achieve push notification I just need your guidlines further we can do things by ourself I really appreciate your reply on this Thanks in advance

Queries
1.Does i need to setup my own server?
2.Does all setup related to socket and database i need to implement at my end ?
3.Does rocket.chat allow us to share a backend code where we setup locally and then we can setup the .CER and .PEM file to support the notification?
4.What is rocket.chat Administers ? Does it will help?
5.For Android where i can setup server key and sender id ?

Please go through my queries and share your valuable reply

**Comment by diegolmello** [comment]
Setting up push notifications is a tricky task even for experienced developers.
If you don't know how to do it, use our gateway or get help on [#jobs](https://open.rocket.chat/channel/jobs).
Thanks.

**Comment by anveshfactorly** [comment]
thanks for reply , will join there as well 
I have my own server and setup the GCM related stuff but unable to receive the Push Notifications on my android device

Can you help me or guide me how can i proceed further

Help will be really appreciate
Thanks
