### ISSUE TITLE
Run Rocket.Chat.ReactNative on Expo

### ISSUE THREAD

**Issue by jgtoriginal** [RocketChat/Rocket.Chat.ReactNative#179]
## Problem
The Rocket.Chat.ReactNative project runs the app in standalone mode, giving developers the possibility to run locally during the development process, but forcing them to run a build and push to the stores in order to share any progress with their final users. This is a huge dependency on the stores app review process, specially on iOS, which might delay several days delivering updates to end users.

## Solution
To solve this problem, Expo offers the possibility of building a wrapper app that will be pushed to the stores only once, and then the developer run hot code pushes every time they have a new update.

This not only accelerates the development lifecycle, but also saves a lot of time to everybody. Developers can deal with only one push notification server, they don't need to take care of pushing to the stores, they handle only simple pushes, etc. And users get updates every day without depending on stores approvals and so on.

## Dependencies
There's a dependency here though, Rocket.Chat.ReactNative is using [Realm](https://realm.io/), which is [not compatible with Expo yet](https://expo.canny.io/feature-requests/p/support-for-realm) --besides of not being open source-- Luckily, there's an alternative to this that is [PouchDB](https://pouchdb.com/), which does basically the same, but is open source and [compatible with Expo.](https://expo.canny.io/feature-requests/p/support-for-realm)

There's also an other thing to note. Rocket.Chat.ReactNative implements push notifications making use of the push notifications native package, which is not compatible with Expo. For which it would be necessary to swap for the [Expo push notifications](https://docs.expo.io/versions/latest/guides/push-notifications.html) for them to keep on working.

## Conclussion
Being all this said, it is also very important to mention that apart from speeding app the development lifecycle, this would make this project stand out from the other 2 Rocket.Chat+ mobile apps, because lots of Rocket.Chat users have limited resource and would rather deal with one app that is written on the same language than the rest of the backend and web interface, rather than going for different languages and so on.

**Comment by saketkumar95** [comment]
@ggazzo What are your thoughts on this?

**Comment by CandyOgre** [comment]
@jgtoriginal have you tried [Fastlane](https://fastlane.tools/)?

- https://fastlane.tools/
- https://dbanck.svbtle.com/deploying-a-react-native-app-with-fastlane
- https://www.udemy.com/automate-your-react-native-releases-with-fastlane-and-bitrise/
- https://medium.com/react-native-training/fastlane-for-react-native-ios-android-app-devops-8ca85bee614e

**Comment by jgtoriginal** [comment]
@CandyOgre yes, that's what I've been using with [Rocket.Chat.Cordova](https://github.com/RocketChat/Rocket.Chat.Cordova) at the time.
Truth is that Expo does use Faslane, so that's not a problem.
The problem here is that with Expo you do just one release in your life time, and you don't depend on the iOS store approving anything later on. Because you got the 'hot code push' feature, which basically allows you to submit updates without the need of store approval.

**Comment by CandyOgre** [comment]
@jgtoriginal you can use Fastlane without Expo and "got the 'hot code push' feature, which basically allows you to submit updates without the need of store approval"

**Comment by jgtoriginal** [comment]
@CandyOgre I was not aware of that, can you point any links?

**Comment by CandyOgre** [comment]
@jgtoriginal I sent you a few links above. Open them and follow instructions

**Comment by jgtoriginal** [comment]
@CandyOgre oh, my bad!!! sorry, checking now!

**Comment by ggazzo** [comment]
@saketkumar95... I think use codepush instead expo is better because, sometimes we will use an incompatible dependencies...

**Comment by abhishek71994** [comment]
I just did this in an application I am making. Should this be done? I can implement the feature.

**Comment by jgtoriginal** [comment]
It might be a good idea for you to go ahead @abhishek71994 
Let us know if you make any good progress.

**Comment by abhishek71994** [comment]
@jgtoriginal I had backtrack and create the whole thing from scratch as when I was working on my own project, once I added the expo feature the react-native run-ios stopped working. However, I can still try and see if this repo works well with that functionality. @ggazzo any suggestions?

**Comment by diegolmello** [comment]
@abhishek71994 @jgtoriginal I think Expo won't work with this project, because it uses native modules.
However, if you guys want to implement Code Push to distribute the app easier, it would be awesome.
