### ISSUE TITLE
Push notifications are unnecessarily received while online in the chat.

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#1794]
Push notifications are unnecessarily received while online in the chat.  Also when I have read the messages on the web and I connect with the app, all the push messages that I have already read come in.  I have a fully updated self-hosted service and the Android app is also updated.

**Comment by diegolmello** [comment]
First part of the message is related to the server, as you mentioned the other issue.
Second part of the issue is a another feature: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1099
