### ISSUE TITLE
Voice messages do not play correctly

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#1795]
Voice messages do not play correctly on Android 9 devices. The error appears when you play the audio but nothing is played and the audio timeline does not advance.  This bug was identified in 2 Xiaomi devices, the Note 6 Pro and the Note 7 Pro. It also happens with Samsung models with Android 9.

**Comment by diegolmello** [comment]
Can you give more details?

**Comment by Nemental** [comment]
> [...] the audio timeline does not advance [...]

#1557

**Comment by aleadco** [comment]
I have several users at my university who have problems playing audios.  Keep in mind that the main problems are evident when you create audio from the application, but if you do it from Windows or from the browser, they can reproduce it.  I have been able to verify the error and it must also be added that the timeline does not advance.  It also usually happens with Android 9
