### ISSUE TITLE
Trying capturing video using the front cam gives "Cannot capture video, another app may be using the mic"

### ISSUE THREAD

**Issue by superseby2** [RocketChat/Rocket.Chat.ReactNative#1797]
- Your Rocket.Chat Experimental app version: 4.5.0
- Your Rocket.Chat server version: 2.2.0
- Device (or Simulator) you're running with: Motorola G5 / Android 8.1.0

When trying to capture some video (by clicking the + button then selecting Take a video) the recording fails to start with the message  : 
"Cannot capture video, another app may be using the mic"

The recording works fine from the rear camera though (with video and sound). 

Thanx

**Comment by diegolmello** [comment]
I couldn't reproduce it.
Make sure there isn't another app using the mic.
