### ISSUE TITLE
[IMPROVEMENT] RoomMemberView and SearchMessageView should look similar

### ISSUE THREAD

**Issue by sarthakpranesh** [RocketChat/Rocket.Chat.ReactNative#1801]
- Your Rocket.Chat Experimental app version: 4.5.0.999999999
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: Redmi 5

Both Views the RoomMemberView and SearchMessageView perform a similar task but on different tables ( one searches for members and the other searches for messages ). These two components should look and feel similar because of there similarities in behavior. 

Would I like to work on this - YES 
![Screenshot_2020-02-29-11-34-05-414_chat rocket reactnative](https://user-images.githubusercontent.com/41206172/75602073-da061b80-5ae7-11ea-9b1c-4be1d159c3c8.jpg)
![Screenshot_2020-02-29-11-33-44-257_chat rocket reactnative](https://user-images.githubusercontent.com/41206172/75602075-dbcfdf00-5ae7-11ea-914a-f2313cf680db.jpg)

**Comment by akumar1999** [comment]
Hey, I would like to work on this issue. 
Thank you

**Comment by sarthakpranesh** [comment]
Hey @akumar1999, nice to see your willingness to work on this issue but I am not sure if this is a legit problem or not. I mean both components are used to search stuff. The only difference is one searches for members and the other for messages.
It's better we wait and have everyone's view on it after that you can work on this issue
@diegolmello can you through some light on this

**Comment by akumar1999** [comment]
Hey @sarthakpranesh , Thank you for letting me know. However, I did start working on this but sure. We can wait for others to view it before I make the required changes.

**Comment by diegolmello** [comment]
I can see your concern, but this is UX and it needs a feedback from our design team.
It's not something the can be fixed by their input.
They're working on something else, but I'll talk to them about it.
I'll let it open, but no need for you guys to work on it right now.
