### ISSUE TITLE
Not open after clicking on push notification

### ISSUE THREAD

**Issue by titomiky** [RocketChat/Rocket.Chat.ReactNative#1804]
- Your Rocket.Chat Experimental app version: 4.4.0
- Your Rocket.Chat server version: 3.0.2
- Device (or Simulator) you're running with: Android 9

Hello,
   We are testing Rocket chat but after clicking on a push notification (own Firebase FCM push), the app only shows splash image. I've made a video to explain it better.
Any idea?

https://drive.google.com/open?id=1DUO07I0jbjEFD0ZIEhr0M7vgw3ZChfo1

**Comment by titomiky** [comment]
It seems it's related to ROOT_URL. We set ROOT_URL environment variable to our domain, but in the push notification, the host of ejson (data payload) is always "localhost".
Any ideas? 

`root@vps784632:~# export MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01
root@vps784632:~# export MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 
root@vps784632:~# export ROOT_URL=http://chat.domain.com:3000 
root@vps784632:~# export PORT=3000
root@vps784632:~# echo $ROOT_URL
http://chat.domain.com:3000
root@vps784632:~# /usr/local/bin/node /opt/Rocket.Chat/main.js
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 174","time":{"$date":1583263852073},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
➔ System ➔ startup
➔ +------------------------------------------+
➔ |              SERVER RUNNING              |
➔ +------------------------------------------+
➔ |                                          |
➔ |  Rocket.Chat Version: 3.0.2              |
➔ |       NodeJS Version: 12.14.0 - x64      |
➔ |      MongoDB Version: 4.0.16             |
➔ |       MongoDB Engine: mmapv1             |
➔ |             Platform: linux              |
➔ |         Process Port: 3000               |
➔ |             Site URL: http://localhost/  |
➔ |     ReplicaSet OpLog: Enabled            |
➔ |          Commit Hash: 05af21bbe9         |
➔ |        Commit Branch: HEAD               |
➔ |                                          |
➔ +------------------------------------------+`

**Comment by djorkaeffalexandre** [comment]
You're using some SSL certificate? our notifications only work's fine with `https://` protocol.

**Comment by titomiky** [comment]
Thank you @djorkaeffalexandre, we are using Nginx as proxy for httpS. Our real domain is httpS://chat.domain.com, and Nginx redirects to http://localhost:3000 (we used this tutorial https://rocket.chat/docs/installation/manual-installation/centos/).

**Comment by djorkaeffalexandre** [comment]
it's really strange, if you start your server using `ROOT_URL=https://chat.domain.com meteor` it'll work, you can try use `console.log` on your browser console and then you will see that `Meteor.absoluteUrl` will return the correct url.

![Screen Shot 2020-03-03 at 16 55 07](https://user-images.githubusercontent.com/29778115/75814087-e3091e00-5d6f-11ea-9a84-4eadd42db66b.png)


And how you can see [here](https://github.com/RocketChat/Rocket.Chat/blob/8b81b17e6551ca189fa76bbd6eeef1676526db9f/app/lib/server/functions/notifications/mobile.js#L58), this value is sent as host to push notifications.

**Comment by titomiky** [comment]
Sorry for the delay...
The problem was in our installation script and the variable ROOT_URL = localhost instead of our domain.
Thank you!

**Comment by AlexKalopsia** [comment]
@titomiky I'm having the same exact issue, and same setup. 

my env looked like

```
- PORT=3030
- ROOT_URL=http://localhost:3030
- MONGO_URL=mongodb://mongo:27017/rocketchat
- MONGO_OPLOG_URL=mongodb://mongo:27017/local
- MAIL_URL=smtp://smtp.mydomain
```

I changed it to

```
```
- PORT=3030
- ROOT_URL=https://chat.mydomain.com
- MONGO_URL=mongodb://mongo:27017/rocketchat
- MONGO_OPLOG_URL=mongodb://mongo:27017/local
- MAIL_URL=smtp://smtp.mydomain
```

but the problem persists. Do you mind sharing your config?
```
