### ISSUE TITLE
Error when trying remove a single member while creating new channel

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1808]
- Your Rocket.Chat Experimental app version: 4.5.0.9999999999
- Your Rocket.Chat server version: 3.1.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android P Samsung Galaxy J6

As the gif shows, when we add members to create a channel, then if we remove them, the last one doesn't get removed. We don't get a message about why we can't remove a single member. Also if we long press on that member item, we get the following error.
![ezgif com-crop (4)](https://user-images.githubusercontent.com/44807945/75679288-5437cb00-5cb5-11ea-98a5-267eecf0ca59.gif)

**Comment by Prateek93a** [comment]
@diegolmello Hi, I have a doubt here. If we don't select any users in the select user screen and proceed to create a channel, we are able to create it, but if we have selected a user, there is a condition that maintains the minimum number to 1, I am not sure why this condition is used if we can create a new channel even without selecting any user. Thanks

**Comment by sarthakpranesh** [comment]
We shouldn't be allowed to make any new channel without any user. :thinking:

**Comment by diegolmello** [comment]
@sarthakpranesh You're making too many assumptions.
People tend to have different expectations of how a software should behave.
Creating a room without any users is a correct feature and it's available on the web client.

@Prateek93a yep, that's an issue.
You should be able to remove both users on CreateChannelView.

**Comment by Prateek93a** [comment]
@diegolmello Ok, and also along with fixing the error, shall we add a visual indicator that tapping on the member item will remove that member? I didn't know about this until I mistakenly tapped on the member item. Maybe we can have a cross button on the right side indicating that by pressing on the member item. Similarly, on the select users view, we can have a cross on the top right corner of member items on the horizontal list.

**Comment by diegolmello** [comment]
@Prateek93a Not a cross, but the same check icon as on SelectUsersView.

**Comment by Prateek93a** [comment]
Ok
