### ISSUE TITLE
[IMPROVEMENT] Add confirm password in RegisterVIew

### ISSUE THREAD

**Issue by sarthakpranesh** [RocketChat/Rocket.Chat.ReactNative#1816]
- Your Rocket.Chat Experimental app version: 4.5.0.9999999
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: Redmi 5

So I thought this is required big-time because I was making an account using the registration process and I didn't care much about what password I entered. I soon realized I made a typo and I wasn't able to login to the new account so I had to reset the password. It'll be kinda nice if we have a confirm password on the RegisterationView.

**Comment by diegolmello** [comment]
We used to have it and we removed it.

Some services confirm password when you're on desktop.
Some services have a magic link.
...

This is a long discussion, but we decided to make it easier for the user to onboard.
I'm closing this issue, but feel free to comment your view about it.

**Comment by sarthakpranesh** [comment]
My thoughts where, if we were going to have a registration form that would ask users to enter a password it's always good to keep the user in check with a confirm password. 
I agree with the fact that we have magic links and passwordless. :sweat_smile:
