### ISSUE TITLE
[BUG] Can't open attachments on Tablet (Android)

### ISSUE THREAD

**Issue by jcourcel** [RocketChat/Rocket.Chat.ReactNative#1825]
Rocket.Chat app version: 4.4.0.2107
Rocket.Chat server version: 2.4.9
Device running with: Samsung Tab A SM-T350, screen 8 inches
Android version : 7.1.1

After a touch on a picture, it is not show on the screen. It is may be related to the size of the screen. My android device has a 8 inches screen. I also try with a 10 inches screen and see the same problem.

Step to reproduce the issue : 
1 - Select a channel.
2 - Scroll until you find a picture.
3 - Touch the picture.
4 - The screen turn dark and the picture is not shown on the screen.
5 - To recover, gently move your finger right to left on the screen.

I did not have this issue with the previous version of android software.

**Comment by Badal1234** [comment]
This problem arises during navigation to 'AttachmentView'.I need more guidance and suggestions on this issue
Thanks

**Comment by djorkaeffalexandre** [comment]
Hey @Badal1234, it's exactly on the `AttachmentView`, probably it's related about some thing that we're trying to render that isn't allowed by android, try to remove things, render only void views and see if the modal is shown, after this you will find what is broken and try to understand what's happening.

**Comment by Badal1234** [comment]
Hey @djorkaeffalexandre , Thanks for the your comment.Check the commit and let me know your review
Thanks

**Comment by jcourcel** [comment]
Hi, I am happy to see you did a fix for this issue. Do you have an idea when it will be released? This issue avoid me and probably many other user to see any video clip and picture send to our tablet. Keep up the good work!

**Comment by Badal1234** [comment]
Thanks @jcourcel  for your words.
Sorry, I don't know when it will be released.

**Comment by Badal1234** [comment]
@djorkaeffalexandre ,could you review the above PR ?
