### ISSUE TITLE
Join to a channel that's mentioned in a message when tapping on it

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat.ReactNative#1826]
- Your Rocket.Chat Experimental app version: 4.5.0.15171
- Your Rocket.Chat server version: 3.0.0
- Device (or Simulator) you're running with: Huawei P20 Lite

When someone mentions a channel, tapping on it opens a preview that only shows the channel info and a avatar.

It would be nice to emulate the same behaviour of the web app (show a channel messages preview and a `Join` button) or at least a `Join` button.

That would make users life easier, because we currently need to go to the `Chat` list, open `Directory`, type the channel name, hit `Search`, tap in the channel name and then it behaves like the web app (messages preview and `Join` button).

Cheers!

**Comment by devyaniChoubey** [comment]
Can i work on this?

**Comment by diegolmello** [comment]
@devyaniChoubey Work on [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1691#issuecomment-594647334) first.

**Comment by mahal** [comment]
Please make this happen. How can we motivate the awesome Rocket.Chat mobile React Native Team to follow up on this?

**Comment by hetanthakkar1** [comment]
@diegolmello Can I work on this?
