### ISSUE TITLE
Option `Long press message > Mention user` or `double tap message` to mention a user

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat.ReactNative#1828]
- Your Rocket.Chat Experimental app version: 4.5.0.15171
- Your Rocket.Chat server version: 3.0.0
- Device (or Simulator) you're running with: Huawei P20 Lite

It would be nice to have `Long press message > Mention user` or `double tap message` to mention a user in the channel/DM.

Right now, the `@username` option sometimes shows way too many matches and we sometimes even end up writing the entire username.

Below, there's a screen record of an app used for `IRC` which have both features so it's better to understand the overall idea:

![Screen Record](https://user-images.githubusercontent.com/25697531/75916696-196e9800-5e59-11ea-83fa-5c60f80f537e.gif)

**Comment by aptvaibhav** [comment]
Hi, is this done already?
