### ISSUE TITLE
iOS app does not recognize joined channels

### ISSUE THREAD

**Issue by novacrazy** [RocketChat/Rocket.Chat.ReactNative#1834]
- Your Rocket.Chat Experimental app version: 4.4.0.14681
- Your Rocket.Chat server version: 1.3.0-develop-ish (latest commit RocketChat/Rocket.Chat@2c3c2dc)
- Device (or Simulator) you're running with: iPhone 6 running iOS 12.4.4, though other users have reporting it on their devices as well.

Joined channel listings no longer load, selected a joined channel in the directory says I'm not joined, new or old messages do not display in the channel listing, etc. Upon joining the already-joined channels from the directory, I am able to send and view messages, but the channel still does not show up in the main channel index.

This has happened before, see #1528, but it solved itself in a day or so, with no good reason.

I have shown a slideshow of the issue here: https://user-images.githubusercontent.com/4708645/71931606-b4057000-3163-11ea-97e9-fb7779e12602.gif from #1498

This event happened to coincide with Let's Encrypt revoking 3 Million certs on March 4th. Was some critical Rocket.Chat infrastructure damaged by that?

**Notifications still work** and the channels directory still works. See that GIF for more. **The server is not at fault here.**

Web version still works normally. The app did not update when this occurred.

**There is some external factor at play, and I need to know what it is**. The app should not suddenly stop functioning like this, as if it's a freaking Y2K bug.

**Comment by novacrazy** [comment]
Aaaand of course it starts working again a few minutes ago. I suppose shouting into the void is an acceptable debugging technique.

However, as this has happened twice, and resolved itself twice, both times with odd timing and with zero changes on my end at all, be it server or app, I'd still like to know what about the apps fails. What external service is used to sync up the app and my server?

**Comment by novacrazy** [comment]
Nevermind, the issue has reappeared again today with the latest experimental app update. It even broke the stable app since they used some linked state.

I suppose I'll just have to take a week out of my schedule to update my server since you all can't support anything older than six months.

**Comment by novacrazy** [comment]
You're going to close the issue here without addressing these persistent issues? 

I want to be understanding, but when things break for reasons outside of my control, I'd like some answers. Why are there days when the app simply stops functioning? Why would it start functioning again at random intervals without any intervention from myself? 

Previously, I didn't even restart the server and eventually things starting working again. Literally did nothing. Can you explain that? What outside force would cause the app to break like this?

**Comment by novacrazy** [comment]
I am still unable to use the app at this moment, whereas yesterday I could, and a couple days before that I couldn't. That is a bug. 

Why would the app not recognize what channels are joined? What part of the API has changed between the commit given and current Rocket.Chat that would cause this? 

Give me something to work with. All I've taken away from this is that you simply don't care about users.

**Comment by diegolmello** [comment]
Is websocket enabled?

**Comment by novacrazy** [comment]
Yes, in fact, I have a bot that's been connected via websocket for the past few months without failure.

**Comment by diegolmello** [comment]
Ok.
Please, create a test user on your server and send me credentials on https://open.rocket.chat.
I'm `@diego.mello`.

**Comment by novacrazy** [comment]
That cannot be done, as the server contains sensitive confidential information. 

However, since the build is on Docker, I may be able to spin up an empty clone of it soon. I could also provide you with any redacted debugging information that is requested if given instructions for how to acquire what you need or what to look for (i.e. malformed messages, etc.)

**Comment by diegolmello** [comment]
You could add the user to dummy channels.
The issue with asking you for debugging is that I would have to expect from you Android/iOS development background and environment.
