### ISSUE TITLE
Unable to set push notifications for all messages in channel

### ISSUE THREAD

**Issue by gesus14** [RocketChat/Rocket.Chat.ReactNative#1837]
- Your Rocket.Chat app version: 4.4.0.282
- Your Rocket.Chat server version: 2.4.2
- Device (or Simulator) you're running with: iPhone SE

Within a private channel I would like to get push notifications on my phone for all messages. So I open the settings dialog of the channel to select `Notifications`. Push notifications are set to `Mentions` as default. So I tap on `Mentions` to change the value to `All Messages`. The selector instantly switches back to `Mentions`. It isn't possible to select something else than `Mentions`.

How to get push notification for each and every message within that channel?

**Comment by diegolmello** [comment]
Duplicated of #1452
