### ISSUE TITLE
Wrong message pops up when we leave broadcast or private channel

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1839]
- Your Rocket.Chat Experimental app version: 4.5.0.9999999999
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: Android P

As the gif shows, when we leave a private or broadcast channel, the message comes that we were removed from the channel which is wrong message. Also the same message comes up when we delete the channel that we created ![ezgif com-crop (5)](https://user-images.githubusercontent.com/44807945/76138363-2b288900-606d-11ea-9f64-489e80fe2451.gif)

**Comment by sarthakpranesh** [comment]
@djorkaeffalexandre @Prateek93a  What is the expected behavior that we are looking for in this part of the application?

**Comment by Prateek93a** [comment]
I don't think any message should pop up since a user left the room him/herself and so it should be similar to leaving any other type of room.

**Comment by sarthakpranesh** [comment]
Ok thanks for the input :smile:

**Comment by sarthakpranesh** [comment]
I looked into it a bit
Found out that when we click `Leave channel` RoomActionVIew a function handleRoomRemoved is being called which checks `rid === this.rid` and displays this message.
