### ISSUE TITLE
[BUG] Not able to post message to broadcast channel

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1840]
- Your Rocket.Chat Experimental app version: 4.5.0.99999999
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: Android P Samsung Galaxy J6

As the gif shows, after we create a broadcast or private broadcast channel, we are redirected to the room. However, we are unable to post anything as it says that the room is read-only. We have to go back to the room view and then back to the channel to post something.

 It might be similar to #1632 but here we are able to post after reopening the channel. I believe the author of #1632 meant that they are not able to post at all.

![ezgif com-crop (6)](https://user-images.githubusercontent.com/44807945/76138470-67a8b480-606e-11ea-805f-62fd6d2b68eb.gif)

**Comment by sarthakpranesh** [comment]
I tested this on version 4.5.1.99999999
Looks like it is fixed already in the new version because I am not able to reproduce the error there :smile:
