### ISSUE TITLE
[BUG] Random id is shown in notification preferences of discussions

### ISSUE THREAD

**Issue by devyaniChoubey** [RocketChat/Rocket.Chat.ReactNative#1842]
![Screenshot_20200307-222104_RocketChat](https://user-images.githubusercontent.com/52153085/76147477-8c2e7c00-60c2-11ea-96f5-0748f6b5e431.jpg)
I am working on it

**Comment by jeevanpuchakay** [comment]
I think this issue has been resolved, I'm unable to reproduce this

**Comment by TC5022** [comment]
@diegolmello is this issue still open? I would like to work on it

**Comment by diegolmello** [comment]
@TC5022 haven't heard of it for sometime. Closing. Thanks!
