### ISSUE TITLE
Able to post message on broadcast channel

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1844]
- Your Rocket.Chat Experimental app version: 4.5.0.99999999999
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: Android P

As the gif shows, when we hide a broadcast channel, then search for it and enter the room, we are able to send a message to the room. Although the bot does show error messages, I think we should not be able to post a message in the first place because it creates confusion.
![ezgif com-crop (7)](https://user-images.githubusercontent.com/44807945/76148064-9bb0c380-60c8-11ea-8388-a7feb06087f2.gif)

**Comment by Badal1234** [comment]
Hey @Prateek93a, this error was actually in renderFooter function of  'roomView' at 
if (this.isReadOnly || !room.archived) .
In version 4.5.1.999999 this is solved as 
if (this.isReadOnly || room.archived) 

Correct my mistake if there any,
Thanks

**Comment by diegolmello** [comment]
Just a note here: 4.5.1.999999 means nothing, because it's something you're running on develop and it may point to whatever commit you're after we bumped the version to 4.5.1.

**Comment by Badal1234** [comment]
Thanks @diegolmello  for this information.I think i had mistaken it

**Comment by sarthakpranesh** [comment]
I have been looking into this and found the following
So I created a broadcast room called `testing-2201`
when the room is normally there the following is the object being received


![1](https://user-images.githubusercontent.com/41206172/77235208-e60e6600-6bd9-11ea-8f54-e8970787f6bc.png)

here we can see that the room is a broadcast room as that property is set to `true`
Now when we hide the room a POST request is made to https://open.rocket.chat/api/v1/channels.close with the roomid

After this when we search for the room then we retrieve the following object 

![2](https://user-images.githubusercontent.com/41206172/77235293-8bc1d500-6bda-11ea-9119-48f1c378ae7a.png)

Here we see that the Broadcast property of the channel is set to `null`. But if the room is not hidden then the broadcast property states `true`

I think :thinking:  this is a server-side bug, or if I am wrong please correct me @Prateek93a @Badal1234 @diegolmello
