### ISSUE TITLE
Unable to find the rejection error 

### ISSUE THREAD

**Issue by shaheem-khanzada** [RocketChat/Rocket.Chat.ReactNative#1845]
Possible Unhandled Promise Rejection (id: 1): TypeError: Cannot read property 'payload' of undefined TypeError: Cannot read property 'payload' of undefined at c (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:99476:25) at anonymous (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:99508:21) at forEach (native) at d (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:99507:163) at anonymous (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:99542:45) at tryCallOne (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:31905:16) at anonymous (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:32006:27) at apply (native) at anonymous (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:36216:26) at _callTimer (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:36105:17) at _callImmediatesPass (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:36141:19) at callImmediates (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:36361:33) at __callImmediates (native) at anonymous (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:5194:34) at __guard (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:5401:15) at flushedQueue (http://192.168.0.108:8081/index.bundle?platform=android&dev=true&minify=false:5193:21) at invokeCallbackAndReturnFlushedQueue (native)

**Comment by diegolmello** [comment]
There's not enough information to help you.
