### ISSUE TITLE
[BUG] unable to delete media files from Message

### ISSUE THREAD

**Issue by Badal1234** [RocketChat/Rocket.Chat.ReactNative#1846]
- Your Rocket.Chat Experimental app version: 4.5.0.999999
- Your Rocket.Chat server version: 3.1.0
- Device (or Simulator) you're running with: Honor 9 lite

Unable to delete media files from Message .
Step to reproduce:-
1.Go to any Channel
2.Send a file from your device or search for any media file
3.Click or Press on the file no delete option will appear

**Comment by djorkaeffalexandre** [comment]
@Badal1234, can you give more info? It seems work here:
![](https://media.giphy.com/media/h8CVbk5uhNDRkFMzgC/giphy.gif)

**Comment by sarthakpranesh** [comment]
Hey @Badal1234, the delete option is the last one when you long press.
Follow these steps
1. Upload an Image
2. Long press to open the `Message actions`
3. Scroll through the options to the last option,  it will be the delete option
4. Click on it and the image will be deleted

Please feel free to close this issue as everything is working as expected :smile:
