### ISSUE TITLE
Build failed after change bundle name

### ISSUE THREAD

**Issue by joaomarcostg** [RocketChat/Rocket.Chat.ReactNative#1852]
- Your Rocket.Chat Experimental app version: 4.5.0
- Device (or Simulator) you're running with: Xiaomi MI 9 ( android 10 )
- Ubuntu 18.04

I'm trying to changle bundle name to be able for publish the app in Play Store. So, I've trying many ways to get on it, lately I've tried to rename all references of 'chat.rocket' to 'chat.clipping' (the name of bundle that I choosed ), but I'm receiving this error message over and over, any help?
(I've already tried react-native-rename, but not worked also)

> Task :app:compileDebugJavaWithJavac FAILED
/home/joaomarcostg/Clipping/Repos/rocket-chat-clipping/android/app/src/main/java/chat/clipping/reactnative/Ejson.java:5: error: package cha
t.clipping.userdefaults does not exist
import chat.clipping.userdefaults.RNUserDefaultsModule;
                                 ^
/home/joaomarcostg/Clipping/Repos/rocket-chat-clipping/android/app/src/main/java/chat/clipping/reactnative/ReplyBroadcast.java:28: error: package chat.clipping.userdefaults does not exist
import chat.clipping.userdefaults.RNUserDefaultsModule;
                                 ^
/home/joaomarcostg/Clipping/Repos/rocket-chat-clipping/android/app/src/main/java/chat/clipping/reactnative/share/ShareApplication.java:5: error: cannot find symbol
import chat.clipping.SharePackage;
                    ^
  symbol:   class SharePackage
  location: package chat.clipping
Note: /home/joaomarcostg/Clipping/Repos/rocket-chat-clipping/android/app/src/main/java/chat/clipping/reactnative/MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 12s
874 actionable tasks: 806 executed, 68 up-to-date

**Comment by djorkaeffalexandre** [comment]
You don't need to change this on all places, you can change this only [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/android/app/build.gradle#L137).
You're changing the name of some node modules that was installed using `yarn`, so, when you try build it not will find `chat.clipping.userdefaults.RNUserDefaultsModule` because this not exists, how you can check [here](https://github.com/RocketChat/rn-user-defaults/blob/master/android/src/main/java/chat/rocket/userdefaults/RNUserDefaultsModule.java#L1).
Closing it for now, if you have more doubts, feel free to ask it here.
Thanks.
