### ISSUE TITLE
Unable to leave Public Room

### ISSUE THREAD

**Issue by sarthakpranesh** [RocketChat/Rocket.Chat.ReactNative#1854]
- Your Rocket.Chat Experimental app version: 4.5.1.9999999999
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: Redmi 5

When a user enters a Public room then even after leaving it the room does not disappear from RoomListView and the user is still allowed to send messages in the Room. Even the owner of the room cannot remove this user if they already clicked the `leave room`.

**Comment by Prateek93a** [comment]
@sarthakpranesh Also I noticed that we get same message as #1839 after leaving public room as well

**Comment by diegolmello** [comment]
I couldn't reproduce this issue.

**Comment by sarthakpranesh** [comment]
So whenever we leave the Public room such as '#sandbox', the room does not disappear from the list of rooms. Also when you re-enter that room the user is still allowed to send messages to that room and the `leave channel` button in the Room Action View also disappears. 

app version: 4.5.1.999999999
server version: 3.1.0-develop
device: Redmi 5 ( Android 10 )

**Comment by sarthakpranesh** [comment]
![image](https://user-images.githubusercontent.com/41206172/77614728-a639dc80-6f53-11ea-9c73-bf14c3987f49.png)

**Comment by djorkaeffalexandre** [comment]
@sarthakpranesh still happening to you?

**Comment by sarthakpranesh** [comment]
Hey @djorkaeffalexandre, yeah it's still happening 
current App version: 4.7.0.9999999
current Server version: 3.2.0-rc.1

I have a different test user using which I joined the `sandbox` channel. But when I use `Leave Channel` the room is not removed from the Room list and I am still allowed to send messages. Also, the `Leave Channel` button disappears after doing this.

![1](https://user-images.githubusercontent.com/41206172/80399671-38c4f700-88d7-11ea-800f-7af1e51f0d3c.png)

**Comment by djorkaeffalexandre** [comment]
Can you post some GIF?
Unfortunately I'm not able to reproduce it here.
Thanks.

**Comment by sarthakpranesh** [comment]
Yeah sure,
So I tested again, this time I made sure I have a good data connection ( last time I tested data connection was not that good ) and the `Leave Channel` option worked. But somehow my `sandbox` channel still does not show the `Leave Channel` button anymore after I clicked on it the last time.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41206172/80404989-9d844f80-88df-11ea-8164-e4c3137fae46.gif)

**Comment by sarthakpranesh** [comment]
I think the error takes place when there is a bad network connection. I was able to reproduce when my network connection was bad.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41206172/80406399-a70eb700-88e1-11ea-8464-d64446715b4c.gif)
