### ISSUE TITLE
[FEATURE] Transfer Ownership of the Channel

### ISSUE THREAD

**Issue by Badal1234** [RocketChat/Rocket.Chat.ReactNative#1864]
- Your Rocket.Chat Experimental app version: 4.5.1.9999999
- Your Rocket.Chat server version: 3.1.0-develop
 Device (or Simulator) you're running with: Honor 9 lite

There is no option for transferring ownership of the channel to another member of the channel.

**Comment by diegolmello** [comment]
Not only transfer ownership:
![image](https://user-images.githubusercontent.com/804994/76436568-275f7400-6397-11ea-89e2-2ef6950386b2.png)

We have only `mute` and `conversation` implemented yet.
