### ISSUE TITLE
Stream Room Messages subscriptions pile up

### ISSUE THREAD

**Issue by Fishbowler** [RocketChat/Rocket.Chat.ReactNative#1870]
- Your Rocket.Chat Experimental app version: 4.4.0

On entering a room, the client sends a subscribe to `stream-room-messages` over the websocket connection.
On leaving a room, the client never sends an unsubscribe, meaning the server sends (and the device receives) every message for every channel a user enters during the lifetime of the app.

Worse still, entering a room a few times will duplicate those subscriptions, leading to multiple copies of those messages being delivered.

**Comment by diegolmello** [comment]
Hi, @Fishbowler .
Thanks for opening.
Do you have more info?
I couldn't reproduce it.

**Comment by Fishbowler** [comment]
Thanks for replying!
You're right - I can't repro it either any more.
I'll close this until I can get something reliably reproducible. 👍
