### ISSUE TITLE
[FEATURE] Possibility to see everybody who reacted to a message. 

### ISSUE THREAD

**Issue by monarkh-karina** [RocketChat/Rocket.Chat.ReactNative#1877]
- Your Rocket.Chat app version: 4.4.0
- Your Rocket.Chat server version: 3.0.0
- Device (or Simulator) you're running with: Samsung Galaxy J7

Currently it's only possible to see 3 people of all those who reacted to a message/post, the rest won't be shown - would be great to have a full list available. 

Some examples:
![WhatsApp Image 2020-04-27 at 16 51 05](https://user-images.githubusercontent.com/29778115/80414519-8aee2400-88a7-11ea-803d-f0d5ff633506.jpeg)

![WhatsApp Image 2020-04-27 at 16 46 48](https://user-images.githubusercontent.com/29778115/80414514-89bcf700-88a7-11ea-8c90-99462dff7b4e.jpeg)

**Comment by vitorl-s** [comment]
I'll work on this
