### ISSUE TITLE
Unable to resolve module :reactnativenotifications

### ISSUE THREAD

**Issue by SaiAshish9** [RocketChat/Rocket.Chat.ReactNative#1883]
![error](https://user-images.githubusercontent.com/43849911/76731568-b7306400-6783-11ea-808a-2834bb338faf.jpg)

Can anyone help me sorting out this issue please?

**Comment by diegolmello** [comment]
Make sure you follow the readme.
If it keeps happening, we need more info.

**Comment by SaiAshish9** [comment]
Hi Diego,Actually I cloned this repo as I wanted to contribute here as a
GSOC participant .
I installed all the packages using the command *npm run install *
and when I tried to test the application on my android simulator using the
command
*npm run android*

It raised the following error :

Cannot choose between following variance of project
:reactnativenotifications

- reactNative59DebugRuntimeElements
- reactNative60DebugRuntimeElements

I'm trying to resolve this issue.If it gets solved I will inform you.

It would be great if you help me configuring out this issue

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative#how-to-run

**Comment by SaiAshish9** [comment]
Thank you for your response ☺️

**Comment by SaiAshish9** [comment]
I used the command yarn instead of npm. Now it worked thank you Diego
