### ISSUE TITLE
Voice messages have no audio on phone

### ISSUE THREAD

**Issue by mmnaseri** [RocketChat/Rocket.Chat.ReactNative#1885]
- Your Rocket.Chat app version: 3.5.0 (257)
- Your Rocket.Chat server version:1.0.3
- Device (or Simulator) you're running with: iPhone XS, iPhone XS Max

First of all, thank you for making such an amazing application. The client is buttery smooth and works just great.

The only problem is that voice messages, once sent on the stream, do not have any audio playback. This is different from https://github.com/RocketChat/Rocket.Chat/issues/10530

When I open the same chat on desktop in the Electron app, the audio has playback. I've tested this on my macOS, Linux Machine, and a Windows laptop.

However, the same voice message, when played back on the iPhone app just plays silent audio.

**Comment by diegolmello** [comment]
Was it fixed by #1862?
It was released as beta for 4.5.1 on TestFlight: https://testflight.apple.com/join/3gcYeoMr

**Comment by Nemental** [comment]
- Your Rocket.Chat Experimental app version: 3.5.1.15552
- Your Rocket.Chat server version: 3.0.4
- Device (or Simulator) you're running with: iPhone XS iOS 13.3.1

I also had this problem, now I can play voice messages in silent mode 👍
