### ISSUE TITLE
Option to Search for messages inside chat-rooms & threads

### ISSUE THREAD

**Issue by DinDev3** [RocketChat/Rocket.Chat.ReactNative#1889]
- Your Rocket.Chat app version: 4.4.0
- Device you're running with: iPhone X

There's no option to search for messages inside a chat-room/ thread in the mobile app. This is a functionality that would come in handy for the user since otherwise, even though there is a search option in the screen which shows the channels, that search gives results from all the channels. Since searching is meant to make things easier, it's quite inconvenient to go through all of them to find the required message.

As a quick fix, the search function outside can take in filters that would filter out the channels needed to search the required message for.

**Comment by diegolmello** [comment]
Search is available on Room > Actions.

**Comment by DinDev3** [comment]
Ohh!! Didn't notice that Actions could be accessed by touching the name of the room.
