### ISSUE TITLE
[IMPROVEMENT] Swipe to Quote functionality

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#1895]
Please add a Swipe to Quote functionality like in Telegram and WhatsApp mobile clients.
It is very convenient.
Related https://forums.rocket.chat/t/mobile-add-swipe-to-left-on-a-message-to-quickly-reply-as-used-by-telegram/2626

**Comment by djorkaeffalexandre** [comment]
I think it can be closed, we have other issue with the same proposal, #764, if you want can comment in the other issue, thanks a lot.
