### ISSUE TITLE
Login to self hosted Server not possible

### ISSUE THREAD

**Issue by hheinen** [RocketChat/Rocket.Chat.ReactNative#1903]
## Describe the bug
I've set up an own Rocket.Chat-Server. Webclient works just fine. I wanted to test the Android App. When I enter my credentials and press Login (or however it is called in the english version), it just does nothing. After a short while the Login-Button is pressable again.

I can see incoming traffic in the apache logs of my server. ^

Is there a special port i have to open so this works or anything like that?

## To Reproduce

Your Rocket.Chat.Android version: version from 10.03.2020
Your Rocket.Chat Server version: 2.4.11

**Comment by diegolmello** [comment]
Is Websocket enabled?
If so, we're going to need more info to help you.

**Comment by hheinen** [comment]
Hey, thanks for your response. I've searched the documentation of Rocket.Chat and looked into the Konfiguration of the Server. Can't find anything like that. Sorry to ask but, what exactly do you mean? 
And what Info do you need?

**Comment by hheinen** [comment]
Sorry, it was a faulty configuration server-side... I'll close the ticket. Sorry and thanks.
