### ISSUE TITLE
New Version (today update) crashes, if in background

### ISSUE THREAD

**Issue by corincorvus** [RocketChat/Rocket.Chat.ReactNative#1920]
- Your Rocket.Chat Experimental app version: 4.6.0.15775
- Your Rocket.Chat server version: 3.0.2
- Device (or Simulator) you're running with: Android 10, Oneplus 7t Pro

I updated the app today in play store. Now the app crashes while is in background. i dont get any popups or notifications. if i open the app, i see the start rocketchat logo every time. after i see many new messages.

On the last Version i didnt have this problem. the app dont show me a crash report :/

**Comment by diegolmello** [comment]
I couldn't test here on my Android 10.
Can you give us more data?
Can you install latest official app and confirm only Experimental crashes?

**Comment by corincorvus** [comment]
Official crashes too. I revert to last version and no have crashes.

If i add more servers, i have more crashes. with only one server i dont have issues. i tested it with the official rocketchat server and my server. if i only use my server all is fine. if i add a random or the official server as second, i get crashes without crash report.

**Comment by diegolmello** [comment]
We'll need more info than this.
When it crashes? Can you post a gif?
What's a crash that doesn't send a crash report?

**Comment by corincorvus** [comment]
I wrote it already. I open the App, all is fine. I minimize the App and if i open the App again after a while, the App was closed and the loadscreen is visible again.

it looks like the battery optimizing who close background Apps, but i disabled it for this Apps.

**Comment by diegolmello** [comment]
Just to be clear. What you're calling **crash** is not a crash.
You seem to be talking about the OS closing the app in background earlier than it should.
I just tested 4.6.0.15775 on an Android 10 here in background for 10 minutes.
When I resumed, it was opened.

**Comment by corincorvus** [comment]
No the OS dont close the app. I disabled the Battery optimizing for this app and while i test it, nextcloud is not optimized too and works fine in the background (you will see it in the notificationbar in this video)

i created a testuser to send me messages. I upload a video in this moment.
i opened the app, i minimized the app. with the webclient on my pc i send "test, test2 3,4,5" and on the first Test i dont get a notification. I click on the app, the loadscreen is visible, the app was closed. Test 2,3,4,5 was fine.

https://youtu.be/6XtJN9JWW08

the problem dont come often, but its a problem.

**Comment by diegolmello** [comment]
Ok. We'll take a look.
Thanks.

**Comment by corincorvus** [comment]
Meanwhile i test it with official Rocketchat App.

**Comment by corincorvus** [comment]
With official App i habe the same Symptome.
A friend was here today. I tested it with his Mi Mix 3. Same Problem with Experimental Version. The App closed randomly after minimize.

My wife dont have this Problem with her P20 pro.

**Comment by corincorvus** [comment]
Today i got the update to 4.6.0.16200
At the Moment i dont have any issues. i will test it this weekend. If i dont get the problem again, i will close this Issue.

**Comment by diegolmello** [comment]
@corincorvus Ok. Keep us posted.

**Comment by corincorvus** [comment]
It works fine since the last Update. Thank you!
