### ISSUE TITLE
 Avatar change issues

### ISSUE THREAD

**Issue by FreewheelingLive** [RocketChat/Rocket.Chat.ReactNative#1921]
- Your Rocket.Chat Experimental app version: 
- Your Rocket.Chat server version: 3.0.4
- Device (or Simulator) you're running with: android note5

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

I found two problems.

at first, Updating user images does not update other users' apps. 
Log out and log back in to get the correct image.

second is, It looks like the image has been replaced with the username. 
User a applies the image. 
Then rename it to b. 
When a new user signs up as a, the old image that b applied was displayed.
This is only happening on b's phone.

second is, It looks like the image has been replaced with the username. 
User a applies the image. 
Then rename it to b. 
When a new user signs up as a, the old image that b applied was displayed.
This is only happening on b's phone.
The new a's phone is normal.

Are you storing images on the phone itself? 
If so, how to delete it?

**Comment by diegolmello** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/441
