### ISSUE TITLE
[BUG] The ActionSheet menus don't respect theme preferences

### ISSUE THREAD

**Issue by aKn1ghtOut** [RocketChat/Rocket.Chat.ReactNative#1926]
- Your Rocket.Chat Experimental app version: 4.5.0
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: OnePlus 6 and Google Pixel 3 XL Emulator

The "ActionSheet" dialogs do not respect the theming preferences on Android. While the iOS Action Sheets are part of the system and get their colours from the OS preferences, they're a part of the application on Android and do not change colour even when the system is in "dark mode" since the module suggests changing the module code itself for those that want to change the styles.

The screenshot is shown below: 
![Screenshot_20200323-225246](https://user-images.githubusercontent.com/38764067/77344623-6f987200-6d59-11ea-9b05-bb782af9511e.jpg)

Even while the theme is dark, the dialog box is white, which interrupts the whole UI

Solution: The react-native-action-sheet module needs to be replaced with the more well-maintained [Expo/react-native-action-sheet](https://github.com/expo/react-native-action-sheet) or a forked and edited version of the current module. The expo-maintained module exposes the same options(plus customization) and is almost completely interchangeable with the currently used module while only having to add a HOC.

I'm working on a PR

**Comment by djorkaeffalexandre** [comment]
Closed by #2114.
