### ISSUE TITLE
[BUG] Mobile application doesn't honor Default Directory Listing setting

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#1932]
- Your Rocket.Chat Experimental app version: 4.6
- Your Rocket.Chat server version: 3.0.3
- Device (or Simulator) you're running with: Xiaomi Mi9 SE

Our users complain about other users search in mobile application.
By default, when you try to search **Directory** it searched **Channels**. But our users much more often are searching other users to communicate.
So, could you please set **Users by default**. Or remember last user search (if users last search users, it will be Directory - Users, If user last search Channels it will be Directory - Channels).

**Comment by ankar84** [comment]
Server improvement was implemented in https://github.com/RocketChat/Rocket.Chat/pull/11965
And now in web version and desktop client it works very well.
Here is our current setting in Admin US - Accounts:
![image](https://user-images.githubusercontent.com/4023037/77503909-ea53b100-6e6f-11ea-9748-3834be1dae7a.png)
So, now I thinks, that problem is that mobile application doesn't honor that setting.
@diegolmello @djorkaeffalexandre could you fix it, please.
Thanks a lot!

**Comment by diegolmello** [comment]
Good to know.
Thanks for opening, @ankar84 :)

**Comment by GOVINDDIXIT** [comment]
@diegolmello I would like to work on this
