### ISSUE TITLE
[Bug] Images in attachment files view not loading

### ISSUE THREAD

**Issue by regalstreak** [RocketChat/Rocket.Chat.ReactNative#1936]
- Your Rocket.Chat server version: 12.14.0 
- Device (or Simulator) you're running with: Android 10 Emulator

<img src="https://user-images.githubusercontent.com/7759208/77446074-e98d3180-6e13-11ea-938c-3b0eab898988.png" width=300 />

Can anyone reproduce?

**Comment by Prateek93a** [comment]
@regalstreak Not able to reproduce it

**Comment by djorkaeffalexandre** [comment]
@regalstreak maybe you’re with the basic auth activated, or not? I can’t reproduce here.

**Comment by regalstreak** [comment]
Yeah basic auth was on. I'll test with a clean setup again

**Comment by slimlv** [comment]
the app is not passing basic auth credentials when make requests for attached files

**Comment by slimlv** [comment]
@diegolmello @djorkaeffalexandre  
this bug still not resolved in Rocket.Chat Experimental v4.11.0.20703
Should I open new one ?

**Comment by djorkaeffalexandre** [comment]
@slimlv, WDYT about create a new issue with all the points where HTTP Auth Basic is not working?
So, when we go to work on this, we can track what's missing.

**Comment by igalic** [comment]
it seems that only user uploaded attachments cannot be viewed
other things like Avatars are no problem

**Comment by slimlv** [comment]
indeed /pre/code formatted strings sometimes not displayed as well with app 4.11.0 20775
cant find any correlation, all requests processed with http 200.

**Comment by igalic** [comment]
> indeed /pre/code formatted strings sometimes not displayed as well with app 4.11.0 20775
> cant find any correlation, all requests processed with http 200.

that should be a separate bug.
I'm pretty, and sure, it has nothing to do with basic auth
