### ISSUE TITLE
Slow load audio

### ISSUE THREAD

**Issue by lucasOlivio** [RocketChat/Rocket.Chat.ReactNative#1943]
- Your Rocket.Chat Experimental app version: 4.3.1
- Your Rocket.Chat server version: 2.2.0
- Device (or Simulator) you're running with: Android Samsung J7 NEO

Opening here because didn't find any issue similiar.

When I send an audio of more than 2 minutes takes too long to load on the messages, tested in different internets and devices and always the slowness to load bigger audios, also the timer gets stuck at "00:00" until the audio is loaded giving the impression that the audio is crashed or something. Would be nice a loading icon for waiting the audio and optimizing this loading if possible

**Comment by aleadco** [comment]
I have several users at my university who have problems playing audios.
Keep in mind that the main problems are evident when you create audio from
the application, but if you do it from Windows or from the browser, they
can reproduce it.  I have been able to verify the error and it must also be
added that the timeline does not advance.  It also usually happens with
Android 9

https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1795
