### ISSUE TITLE
Users will not logout automat when Login Expiration in Days is set

### ISSUE THREAD

**Issue by djnews24** [RocketChat/Rocket.Chat.ReactNative#1944]
- Your Rocket.Chat Experimental app version: 4.5.0
- Your Rocket.Chat server version: 2.4.11  
- Device (or Simulator) you're running with: Device

Hey guys,

currently we set our Login Expiration in Days to 7 on Rocket.Chat self hosted server.
Users are LDAP Based.

Now we got the Problem thats the User dont see if the Token is expired.
So the App itself just looked like it work but not sync anymore.
Should it not logout the Users on the App or ask about the user and password again like on the OSX App? Anything we could do?

best and stay healthy,
Dennis

**Comment by sarthakpranesh** [comment]
hey @djnews24, as far as I understand the app should automatically log out as soon as the user token expires and the app is restarted :thinking:

**Comment by djnews24** [comment]
Yep but it looks like it do not work.

**Comment by diegolmello** [comment]
@djnews24 we'll take a look

**Comment by mddvul22** [comment]
Will this preserve a message that the user is typing, if they get logged out, in the middle of typing the message?  When a user is logged out because of the timer, any message they are in the middle of typing should be saved as a draft.
