### ISSUE TITLE
Unable to Upload Pictures taken with Camera but Screenshots work.

### ISSUE THREAD

**Issue by ymybe** [RocketChat/Rocket.Chat.ReactNative#1957]
- Your Rocket.Chat app version: 4.5.1 (iOS -Store & Android - Git Release Downloads  latest release as of 28. March 2020)
- Your Rocket.Chat server version: 3.07
- Devices you're running with: iPhone SE 13.4 & Nexus 5 7.12 /e/

When trying to upload camera Pictures from library the app fails to upload them, i get an error message.

When uploading screenshots it works on both systems.

**Comment by shash137** [comment]
It's working fine in my device, I tried sending the image through camera and picture library it's working.

Device: Asus_X00TD
Android version: 9

**Comment by mors1eska** [comment]
I have the same problem
server 3.0.10
klient 4.5.2.286

**Comment by ymybe** [comment]
turns out in my case it was  limited by Nginx.  => Close.
