### ISSUE TITLE
How to delete configured servers?

### ISSUE THREAD

**Issue by stefanandres** [RocketChat/Rocket.Chat.ReactNative#1962]
- Your Rocket.Chat Experimental app version: 4.5.2
- Your Rocket.Chat server version: 3.0.1
- Device (or Simulator) you're running with: iPhone 8

I've added multiple test servers to the iOS App. How can I remove them?
I didn't find any way to trigger a delete action.

**Comment by diegolmello** [comment]
Duplicated #1087 

Currently, you can remove it only on logout.

**Comment by stefanandres** [comment]
Thanks for the quick reply!
Stupid question, but how do I logout of a server? I cannot seem to find this action either.
Also I have added a "New Server" and did not configure it and this is stuck with the standard open.rocket.chat (where I do not have an account). So I am not even logged in there, how do I log out there and remove of from the server list?

**Comment by diegolmello** [comment]
How to logout:
 - On our sidebar, Settings > Logout (you have to scroll down).

I didn't understand your app state.
If you're not logged in, you should be able to select the server you want.
Try clearing your app data (via your OS) and installing it again.
