### ISSUE TITLE
[NEW] KaTeX Support

### ISSUE THREAD

**Issue by jGleitz** [RocketChat/Rocket.Chat.ReactNative#1973]
Rocket.Chat supports posting [KaTeX](https://github.com/Khan/KaTeX), which will get rendered nicely in the conversation. For us, this is an outstanding feature.

Unfortunately, when posting KaTeX in the native app (e.g. `$x$` or `\[x\]`), it is *not* rendered as KaTeX but stays as it is.

**Comment by diegolmello** [comment]
Hey, I transferred this issue to the new repo.

**Comment by raffaeler** [comment]
Is this feature working on any client? I can't make it work on any client (web, desktop and android)
TIA

**Comment by phriedrich** [comment]
@raffaeler Yes, it's working for me in the web version. (It has to be enabled in the settings under messages.)

But it's _not_ supported in the mobile app.

**Comment by raffaeler** [comment]
thank you @phriedrich. The option is enabled in Messages but I can't make it work from the web.
Could you please type here an example so that I am not misunderstanding the KaTex syntax?
Thank you

**Comment by phriedrich** [comment]
The example up in this thread here works for me with the same syntax:

![Bildschirmfoto 2020-05-28 um 14 44 02](https://user-images.githubusercontent.com/470153/83143455-477b1580-a0f2-11ea-9798-0b82d8961134.png)
But it's also possible to set the syntax from `\[KaTeX Block\]` to `$$KaTeX Block$$`:
![Bildschirmfoto 2020-05-28 um 14 45 05](https://user-images.githubusercontent.com/470153/83143404-329e8200-a0f2-11ea-85f8-c61f0e5587b6.png)

If you can't get KaTeX working at all, this is probably more a question for Rocket.Chat itself, and not for the mobile app.

**Comment by raffaeler** [comment]
Thanks but the syntax with the square bracked does not work.
I enabled the Dollar syntax and it works.
The strange thing is that when I enable the Dollar syntax the square bracket syntax gets swallowed.

It may be a bug. I am using version 3.2.2

**Comment by KokosnussDEV** [comment]
Upvoting this for implementation

**Comment by no-trick-pony** [comment]
I am a bit confused: Why would you implement this and display it in the UI directly below the chat input at the same level as bold, italic or inline code when it is basically broken in all of your own mobile clients?

**Comment by johncrisp** [comment]
Hi,

So the situation here is complex.

First thing to note is that the mobile app is not 'broken'. However, the specific functionality you require is not yet implemented.

It's not implemented because Katex uses web stuff to render the math operations.

As a result we'd need to either create a native module to do that, or try to embed a webview into the message component.

It is on our long term road map to look at this, but it is not at top of the list for priority right now I'm afraid.

I'll leave this issue open accordingly.

Thanks.

**Comment by 66Leo66** [comment]
> As a result we'd need to either create a native module to do that, or try to embed a webview into the message component.

There's modules that could render KaTeX without using webview but svg instead. Check https://www.npmjs.com/package/react-native-math-view

By the way, as this issue causes a mess on native clients when reading messages with KaTeX, why is it "not at top of the list for priority right now "?

Looking forward to a fix!

**Comment by ankar84** [comment]
Still not implemented in latest Rocket chat React Native mobile app
Web client
![image](https://user-images.githubusercontent.com/4023037/165437614-607a6928-61c1-4c2e-b9ec-58c1e1fb18ce.png)
Mobile client
![image](https://user-images.githubusercontent.com/4023037/165437653-db5ee78b-97e1-4c91-9938-3e05ea080c10.png)

**Comment by ankar84** [comment]
@GleidsonDaniel hey!
Strange, but looks like Katex still not supported in new 4.29 version
Mobile cleint 4.29.0.34197 (iOS)
![image](https://user-images.githubusercontent.com/4023037/180124320-f9cc0b3d-1190-49d5-b2e4-3f465a7802cb.png)
Web client
![image](https://user-images.githubusercontent.com/4023037/180124410-791bff8b-03f0-4919-ba7c-c87cf776cb5e.png)

**Comment by diegolmello** [comment]
Possibly related to https://github.com/RocketChat/fuselage/issues/775?

**Comment by GleidsonDaniel** [comment]
It's working, you're probably just using an outdated version, given that PR was merged 16 hours ago and version 4.29.0.34197 came out 3 days ago...
![Screen Shot 2022-07-21 at 10 14 35](https://user-images.githubusercontent.com/18687097/180222899-11a5b63a-a166-4bce-a11f-c8640e63e21c.png)

Yes, it will be available in the next version.

**Comment by pegonma** [comment]
I am using the RocketChat Android app (version 4.35.1.37443) and latex formulas are not rendered on the map (neither with the syntex \( \) nor with \[ \]). While it is rendered on the web app, so this does not seem to a problem with the setting of our server (provided by our university).

@GleidsonDaniel I am confused, which app/device are you using?

**Comment by GleidsonDaniel** [comment]
> I am using the RocketChat Android app (version 4.35.1.37443) and latex formulas are not rendered on the map (neither with the syntex ( ) nor with [ ]). While it is rendered on the web app, so this does not seem to a problem with the setting of our server (provided by our university).
> 
> @GleidsonDaniel I am confused, which app/device are you using?
> 
> (My server is chat.univ-lille.fr and the server version is 3.15.2).

@pegonma the problem in your cause is probably your server version.

**Comment by pegonma** [comment]
@GleidsonDaniel Is it really possible? That the server allows the desktop client to render KaTeX formulas but not the mobile app? Can you tell me what is the latest server version? So I can ask the IT of my uni to update it.

**Comment by GleidsonDaniel** [comment]
> @GleidsonDaniel Is it really possible? That the server allows the desktop client to render KaTeX formulas but not the mobile app? Can you tell me what is the latest server version? So I can ask the IT of my uni to update it.

@pegonma After version 5.0 of the server we changed the way messages are rendered and tagged and in this version we added support for katex.
Before that the app never had katex support.

So, as I said, to work katex in the mobile app you must have a server running above version 5.0 and as your server is in version 3.15.2 it will not work.

**Comment by pegonma** [comment]
@GleidsonDaniel thank you very much for your answer!
