### ISSUE TITLE
Cannot Post on Readonly channel with post readonly permission

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat.ReactNative#1977]
- Your Rocket.Chat app version: 4.5.2.286
- Your Rocket.Chat server version: 1.3.3
- Device (or Simulator) you're running with: Apple IOS

**Comment by diegolmello** [comment]
There's a work in progress at https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1951

You're running a very old version of the server btw.
