### ISSUE TITLE
Password Policy of server is not being followed

### ISSUE THREAD

**Issue by Albert88406** [RocketChat/Rocket.Chat.ReactNative#1979]
- Your Rocket.Chat Experimental app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by Albert88406** [comment]
Currently it just accept any password even 1 digit

**Comment by diegolmello** [comment]
Duplicated of #1592
