### ISSUE TITLE
Able to Post in the threads of a channel without joining the channel

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1983]
- Your Rocket.Chat Experimental app version: 4.6
- Your Rocket.Chat server version: 3.1.0-develop open.rocket.chat
- Device (or Simulator) you're running with: Android P Samsung Galaxy J6

As the Gif shows, we are able to post on the threads of a channel, without joining the channel.

Steps to reproduce ->
- Go to a channel which you have not joined
- Look for a thread and press reply
- You are able to post reply without joining the room 

![ezgif com-resize(3)](https://user-images.githubusercontent.com/44807945/78391815-c24d1600-7604-11ea-9b84-51c26dc6cc21.gif)

**Comment by Badal1234** [comment]
@Prateek93a ,
I think this behavior is supported in web client.Check there once.

**Comment by Prateek93a** [comment]
@Badal1234 Hi, actually when on web client, you have to join the room first, only then the message is sent. When try you to reply in a thread, you are automatically made the member and then the message gets sent
