### ISSUE TITLE
Stuck on splashscreen when edit code

### ISSUE THREAD

**Issue by alfinurhakim** [RocketChat/Rocket.Chat.ReactNative#1984]
* Your Rocket.Chat Experimental app version: 4.6
 * Your Rocket.Chat server version: 3.0.3
 * Device (or Simulator) you're running with: iPhone 8 Plus

I'm trying install rocket chat react native and its so successfully. But when I edit the code it's a bit like adding a space anywhere and it doesn't affect the code ... the application is directly stuck on the splashscreen on android or ios and doesn't raise any errors in debugging.

![image](https://user-images.githubusercontent.com/48195224/78394810-8753de00-7616-11ea-8e19-923f7f427335.png)

please help me to overcome this problem..thank you :(

**Comment by alfinurhakim** [comment]
@djorkaeffalexandre  I'm very confused :(, why is this happening ... because the bundle shows it works and I've tried repeating that shortcut

![image](https://user-images.githubusercontent.com/48195224/78396365-76589c00-7619-11ea-958e-1aefd424d4ab.png)

**Comment by alfinurhakim** [comment]
Oke i will check again and try install nvm ..thank you for your answer @djorkaeffalexandre

**Comment by djorkaeffalexandre** [comment]
Closed due to inactivity from the author.
