### ISSUE TITLE
Switching between servers - automatically logged out

### ISSUE THREAD

**Issue by bestog** [RocketChat/Rocket.Chat.ReactNative#1985]
I am automatically logged out when I switch between my servers. This is really strange. 🤔

**Comment by djorkaeffalexandre** [comment]
@bestog can you please add more info? Like the app version, servers version, etc.
Thanks.

**Comment by bestog** [comment]
App Version: 4.5.2.286
App Platform: iOS (iPhone X)
Server Version: 2.4.1
Same in the Other Server. 

When i Click on a other Server in the header list. I Switch to the new Server and See for <1sec the channellist/chats. And then a Dialog is showing. Logout please wait. (And Hoppla...)

**Comment by djorkaeffalexandre** [comment]
Thanks!
I'm found something like this on my latest PR, #1981, that will turn users able to change their server while connecting, I found an issue that are saving wrong information sometimes when you change from one server to another and I think that is your problem.
It’s happening always or only sometimes?
You know if your connection are really good?

**Comment by bestog** [comment]
I tried Rocket.Chat in TestFlight and the experimental. Deleted the App completely and add the two Server. The Same Problem appears. 

The Problem exists always in every Situation. :/

**Comment by toshanmugaraj** [comment]
Still the issue exists. Getting logged out when choosing the server suggestion list in login screen.

**Comment by diegolmello** [comment]
@toshanmugaraj I think you're talking about a different issue. Can you elaborate?

**Comment by toshanmugaraj** [comment]
@diegolmello 
It happens in Android device, build from development branch.

1. Join your workspace with one server URL.
2. Login once and Logout.
3. Now join the workspace with another server URL.
4. Login to the app.
5. Close application.
6. Receive push notification for any new message.
7. Select the notification from notification bar.

Now the application keeps login and logout on infinite loop. Seems to be some routing loop bug.

**Comment by diegolmello** [comment]
@toshanmugaraj it's unrelated. Can you open a new issue? Thank you.

**Comment by diegolmello** [comment]
@djorkaeffalexandre @bestog Can we close this issue? I was never able to reproduce it and it's stale since April.
