### ISSUE TITLE
[Bug] Crash on threads tap

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#1988]
- Your Rocket.Chat Experimental app version: 4.6.0.16200
- Your Rocket.Chat server version: 3.1.0
- Device (or Simulator) you're running with: Xiaomi Mi 9 SE

Tap on threads icon in chat makes app to crash. open.rocket.chat has that bug.
![Отчет](https://user-images.githubusercontent.com/4023037/78450197-1a3c5900-76a7-11ea-9bce-bd90ae3931b8.gif)

**Comment by ankar84** [comment]
**4.2 - all fine
4.6.0.16200 - app crash**

@diegolmello @djorkaeffalexandre please look at that bug, IMHO, it's critical.

**Comment by diegolmello** [comment]
Duplicated of #1970
