### ISSUE TITLE
Jitsi connection issues

### ISSUE THREAD

**Issue by loopway** [RocketChat/Rocket.Chat.ReactNative#1993]
- Your Rocket.Chat Experimental app version: 4.5.2.286 for iOS
- Your Rocket.Chat server version: 3.0.4
- Device (or Simulator) you're running with: iPhone XR on iOS 13.3.1
- Jitsi Server: docker-jitsi-meet stable-4101-2

Trying to join a Jitsi video chat results in a spinning wheel which eventually times out. On the firewall dropped connections to tcp port 443 are logged. Desktop clients on MacOSX and Linux can successfully connect to the chats.

Our Jitsi server is using tcp port 8443 instead of the standard 443 port for the Jitsi web interface. Could it be that the mobile client does not read the rocket.chat Jitsi domain setting correctly?

**Comment by djorkaeffalexandre** [comment]
Hey @loopway, I think we're setting the Jitsi domain correctly, can you reach me on `https://open.rocket.chat`?
My username is `djorkaeff.alexandre`.
Maybe this can be a problem with the jitsi-sdk.
Thanks in advance.

**Comment by fuckreligious** [comment]
> Hey @loopway, I think we're setting the Jitsi domain correctly, can you reach me on `https://open.rocket.chat`?
> My username is `djorkaeff.alexandre`.
> Maybe this can be a problem with the jitsi-sdk.
> Thanks in advance.

Hi, please come in just a little questions, thanks

**Comment by loopway** [comment]
After setting up a test installation I could verify that it works with jitsi-web listening on port 443, but not on port 8443.

**Comment by loopway** [comment]
works now in combination of newer versions:

- Your Rocket.Chat Experimental app version: 4.7.2 for iOS
- Jitsi Server: docker-jitsi-meet stable-4627-1
- Your Rocket.Chat server version: 3.0.4
