### ISSUE TITLE
Jitsi using http basic authentication

### ISSUE THREAD

**Issue by aminvakil** [RocketChat/Rocket.Chat.ReactNative#2002]
## Describe the bug
I've created the jitsi docker and change nginx configuration and set a username/password basic authorization, then I've changed jitsi domain in rocket chat administration to username:password@myjitsi.com and everything works well in rocket chat linux and windows clients.

But I can't start a voice / video call or join a voice / video call from android client. I'm using latest beta version from Google Play Store.

I've checked and android version works OK if I disable basic authorization.

## To Reproduce
Enable basic authorization in front of your jitsi like this for example:

```
auth_basic "Use Rocket.Chat";
auth_basic_user_file /config/nginx/auth/.htpasswd;
```
Change jitsi domain in rocket chat administration from myjitsi.com to username:password@myjitsi.com

Try to start a voice/video call from android client.

## Expected behavior
Work like it does without basic authorization.

## Devices and Versions
- Your Rocket.Chat Experimental app version: 4.5.2.2110
- Your Rocket.Chat server version: 3.0.7
- Device (or Simulator) you're running with: Mi A2 Lite - Android version 9

## Additional context
I'm not an android expert and I don't know how to see what happens behind network of rocket chat when I enable basic authorization, but I assume it has something to do with http client that rocketchat uses.

**Comment by djorkaeffalexandre** [comment]
You basic auth is the same of your server?
We can use same credentials to login into your jitsi?
If yes, we can use the basicAuth headers along your app before start a new call and it'll works fine.

**Comment by aminvakil** [comment]
> You basic auth is the same of your server?
I'm using username and password correctly if that's what you mean.
> We can use same credentials to login into your jitsi?
It's credentials of nginx actually, so yes if I browse the url on any browser and use the credentials I can login.
> If yes, we can use the basicAuth headers along your app before start a new call and it'll works fine.
That's the problem I think, android version doesn't basicAuth headers even I've put jitsi url in rocketchat administration as this:
username:password@examplejitsi.com

**Comment by djorkaeffalexandre** [comment]
@aminvakil, we never save your combination of username and password on headers, I want to understand how is configured your proxy, if your basic authorization is the same on your server and jitsi, you use the same user to login into your server and on your jitsi?

**Comment by aminvakil** [comment]
Jitsi itself is not using any authentication, it's deployed using https://github.com/jitsi/docker-jitsi-meet repo.

This repo has a docker named web which is basically an nginx, I've changed the nginx configuration as I've said previously like this:
```
auth_basic "Use Rocket.Chat";
auth_basic_user_file /config/nginx/auth/.htpasswd;
```

Then in rocketchat Administration > Video Conference > Jitsi > domain section:

Instead of meet.example.com I've put username:password@meet.example.com, Enabled SSL, Check Always Open In New Window, Enable in Channels.

If I've used meet.example everything works great, on both rocketchat pc (linux & windows) and rocketchat android.

But if I put username:password@meet.example.com android version doesn't work, and exits with a error which starts with You have been disconnected...

It comes and goes very fast, I cannot read the rest of it.

**Comment by djorkaeffalexandre** [comment]
Oh, thanks about that info! Maybe it can be a problem with the jitsi sdk! I'll investigate soon!
If as possible, can you reach me on `https://open.rocket.chat`?
My username is `djorkaeff.alexandre`.
If you give me some test credentials on your server it'll be more fast.
Thanks in advance.

**Comment by aminvakil** [comment]
https://github.com/jitsi/jitsi-meet/issues/5419

As it has been said on this issue I've successfully enable jwt authentication using https://github.com/jitsi/docker-jitsi-meet and have set it in my rocketchat as well, now android and desktop version both work correctly.

Although it would be great if http basic authentication works as well, but for now jwt does the job.
