### ISSUE TITLE
Cannot login on my Rocket.Chat server using iOS app

### ISSUE THREAD

**Issue by ziorufus** [RocketChat/Rocket.Chat.ReactNative#2005]
- Your Rocket.Chat app version: 4.6.0.289
- Your Rocket.Chat server version: 3.0.12
- Device (or Simulator) you're running with: iPhone 8

I installed Rocket.Chat on my server and it seems to work perfectly except from iOS app.
I can login to it from web, Android app, and macOS app.
When I try to login from iOS app I got… nothing! I am asked to insert login and password, I click on the blue button, I see the three dots for a couple of seconds and then nothing happens. Note that if I use a wrong password I received the wrong password message.
Is there a way to see logs? On the admin page on the web version nothing appears.

Address: https://rocket.apnetwork.it/

Apache log file:

```
SSLEngine on

ServerAdmin     alessio@localhost
ServerName      rocket.apnetwork.it

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://localhost:3000/$1 [P,L]

SSLProxyEngine on
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/

ErrorLog        /data/log/apache2/rocket.error_log
CustomLog       /data/log/apache2/rocket.access_log combined

SSLCertificateFile /usr/share/tomcat6/.acme.sh/rocket.apnetwork.it/fullchain.pem
SSLCertificateKeyFile /usr/share/tomcat6/.acme.sh/rocket.apnetwork.it/privkey.pem
```

Video showing the problem: https://www.youtube.com/watch?v=Yktvp-gx0uw

**Comment by diegolmello** [comment]
I transferred this issue to the correct repo, since iOS repo is deprecated: https://github.com/RocketChat/Rocket.Chat.iOS#important---please-read-this-first

WebSocket seems to be off: 
![image](https://user-images.githubusercontent.com/804994/78701795-00388b80-78de-11ea-9281-d24a7b1334cf.png)

**Comment by ziorufus** [comment]
Thank you very much for your answer. What do I need to do to turn ws on?

I tried different Apache configurations, but I continue to get the error.

```
    SSLEngine on

    ServerAdmin     sysop@fbk.eu
    ServerName      rocket.apnetwork.it

    RewriteEngine On
#    RewriteCond %{HTTP:Upgrade} =websocket [NC]
#    RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
#    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
#    RewriteRule /(.*)           http://localhost:3000/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} =websocket
    RewriteRule /(.*)           ws://localhost:3000/$1 [P,QSA,L]
    RewriteCond %{HTTP:Upgrade} !=websocket
    RewriteRule /(.*)           http://localhost:3000/$1 [P,QSA,L]

    ProxyPreserveHost On
    ProxyRequests Off

    SSLProxyEngine on
    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/

    ErrorLog        /data/log/apache2/rocket.error_log
    CustomLog       /data/log/apache2/rocket.access_log combined

    SSLCertificateFile /usr/share/tomcat6/.acme.sh/rocket.apnetwork.it/fullchain.pem
    SSLCertificateKeyFile /usr/share/tomcat6/.acme.sh/rocket.apnetwork.it/privkey.pem
```

**Comment by ziorufus** [comment]
Update: if I use http://rocket.apnetwork.it:3000 everything is ok, but I cannot login from iOS because it does not allow connections that are not on SSL

**Comment by diegolmello** [comment]
Ok. Closing then.
