### ISSUE TITLE
Login fails (empty site) after workspace URL

### ISSUE THREAD

**Issue by robinreinhardt** [RocketChat/Rocket.Chat.ReactNative#2006]
### Description:

App Login isn't possible anymore.
After entering the rocketchat server address no login fields are visible, just an empty site

### Steps to reproduce:

1. Click "Join a workspace"
2. Enter your workspace URL
3. only an empty site is visible

### Expected behavior:

Normal login screen with username and password field

### Actual behavior:

After entering the workspace URL only a empty site is visible
![Screenshot_2020-04-07-20-49-57-978_chat rocket reactnative](https://user-images.githubusercontent.com/47597962/78709565-27aa4b00-7914-11ea-965a-3ac53a2eec86.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: **2.4.11**
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 5
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.17.0
- MongoDB Version: 3.6.16

### Client Setup Information:

Affected App versions:

Android: 4.6.0.16200, 4.6.1.16337
iOS: 4.6.1.290

### Relevant logs:

There is no server log about it

**Comment by diegolmello** [comment]
Send me your server URL at https://open.rocket.chat.
I'm `@diego.mello` there.
Thanks.

**Comment by robinreinhardt** [comment]
> Send me your server URL at https://open.rocket.chat.
> I'm `@diego.mello` there.
> Thanks.

I'm registered on open.rocket.chat, but cannot find you in the search

**Comment by robinreinhardt** [comment]
With the help of @diegolmello we fixed the problem:

In the settings under `General` -> `REST API` an incorrect value was set at `Default Count`
After I set the value from `1` to `50` (default value) the app login was possible again.

The problem is solved and the issue closed.
