### ISSUE TITLE
Making video calls after Video conference being disabled on the server

### ISSUE THREAD

**Issue by monarkh-karina** [RocketChat/Rocket.Chat.ReactNative#2010]
- Your Rocket.Chat app version: 4.5.2 (+ 4.6.0 Experimental)
- Your Rocket.Chat server version: 3.0.2
- Device (or Simulator) you're running with: Samsung Galaxy J7

Steps to reproduce: 
1. Disable video conference on the server. 
2. User 1 enters the chat with User 2, navigates to the user info and click on "Video call" -> User 2 gets push notification about the call and joins the call. 
3. User 2 can do the first call to User 1 from his side as well. 
4. On the second try, User 1 still can click on "Video call" and initiate a call with User 2 -> User 2 won't receive any notification/message about the call -> User 1 will be the only one on the call. 
5. Same for User 2 on the second try (he's the only one on the call).

**Comment by jsalatiel** [comment]
It would be nice to remove the Call Button from UserInfo if Video Conference is disabled on the server.

**Comment by jsalatiel** [comment]
btw, that video call button uses anny VC backend available ? ( both jitsi or BBB )

**Comment by diegolmello** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2292
