### ISSUE TITLE
emoji ignored in POST to /api/v1/chat.postMessage

### ISSUE THREAD

**Issue by nexus166** [RocketChat/Rocket.Chat.ReactNative#2015]
hi!

POSTing a message to `/api/v1/chat.postMessage` and including an Emoji/avatar for the message, the emoji is visible in web interface but not from mobile - I see the original avatar of the user/bot the token used to authenticate the HTTP request are associated with.

- Your Rocket.Chat Experimental app version: 4.6.0 / android 9
- Your Rocket.Chat server version
```json
  "version": "3.0.10",
  "os": {
    "type": "Linux",
    "platform": "linux",
    "arch": "x64",
    "release": "4.19.0-8-cloud-amd64",
    "uptime": 236054,
    "loadavg": [
      0.07763671875,
      0.18310546875,
      0.2373046875
    ],
    "totalmem": 10482647040,
    "freemem": 7498309632,
    "cpus": [
      {
        "model": "Common KVM processor",
        "speed": 3400,
        "times": {
          "user": 44628000,
          "nice": 0,
          "sys": 27278200,
          "idle": 2244832800,
          "irq": 0
        }
      },
      {
        "model": "Common KVM processor",
        "speed": 3400,
        "times": {
          "user": 41160800,
          "nice": 16100,
          "sys": 27354100,
          "idle": 2257292000,
          "irq": 0
        }
      },
      {
        "model": "Common KVM processor",
        "speed": 3400,
        "times": {
          "user": 40843800,
          "nice": 17800,
          "sys": 26948400,
          "idle": 2249069600,
          "irq": 0
        }
      }
    ]
  },
  "process": {             
    "nodeVersion": "v12.14.0",
    "pid": 1,                 
    "uptime": 235876.26382856       
  },                           
  "deploy": {                
    "method": "docker-official",
    "platform": "selfinstall"
  },
```

- Device (or Simulator) you're running with: kubernetes KVM worker

**Comment by nexus166** [comment]
same with RocketChat Server v3.0.12. About to upgrade to 3.1.0, will post info on that.

**Comment by nexus166** [comment]
same on 3.1.0 server

**Comment by diegolmello** [comment]
Hi! I didn't get what do you mean by `emoji/avatar`.
Can you give us an example of what's not working?
Screenshots?
It's working on our [server](https://open.rocket.chat)

**Comment by nexus166** [comment]
@diegolmello I mean the `emoji` field in the POST endpoint documented at https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/. It says: 
> If provided, this will make the avatar on this message be an emoji.
But this is only true on web client: on mobile I see the original avatar of the bot/user POSTing the message through /api/v1/chat.postMessage

**Comment by nexus166** [comment]
**web**
![2015-web](https://user-images.githubusercontent.com/9354925/79120264-cc081380-7d92-11ea-8e9b-cc4e7a1248b0.png)

**mobile**
![2015-mobile](https://user-images.githubusercontent.com/9354925/79120268-cd394080-7d92-11ea-8108-1cfccdcd8bec.jpg)

sorry for kindergarten editing - am a backend guy

**Comment by diegolmello** [comment]
Got it. Thanks.

**Comment by nexus166** [comment]
[this](https://github.com/nexus166/rocketchat_post/blob/master/main.go) is the "client code" by the way
