### ISSUE TITLE
[BUG] Version 4.6.1 drops Jitsi call right after start

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2016]
- Your Rocket.Chat Experimental app version: 4.6.1.16337
- Your Rocket.Chat server version: 3.0.3
- Device (or Simulator) you're running with: Xiaomi Mi9 SE

We have Jitsi integration at our on-premise RC server.
Version 4.6.0 works great with our Jitsi - call starts fine.
But newest version 4.6.1.16337 drops Jitsi call right after successfully created it ("Click to Join" button appear in channel).
One second you can see an error:
![image](https://user-images.githubusercontent.com/4023037/78854681-9da0d600-7a2a-11ea-899b-888f9c8cac54.png)
Did a little research in Jitsi log files and found that RC Deployment ID undefined in version 4.6.1.16337
Here example on Jitsi log of successful call with version 4.6.0
```
Jicofo 2020-04-09 05:27:48.329 INFO: [30] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@2adbcc65 member=ChatMember[rocketchatsarzherbsqpolu33kgyfnydxfwddom9jeriode4twmg4i729goh@muc.meet.jitsi/00466832, jid: 00466832-995b-477b-96b9-54c1a3ca7a65@meet.jitsi/-baxH2rl]@31548258]
```

And here Jitsi log of failed call with version 4.6.1.16337
```
Jicofo 2020-04-09 05:28:06.727 INFO: [30] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@64ee0e5b member=ChatMember[rocketchatundefinedgyfnydxfwddom9jeriode4twmg4i729goh@muc.meet.jitsi/93f23472, jid: 93f23472-9da1-475c-b7e3-7a6519fd65fd@meet.jitsi/jhM0ijN_]@1332074379]
```
As you can see ChatMember in successful call is rocketchat**sarzherbsqpolu33k**gyfnydxfwddom9jeriode4twmg4i729goh
And ChatMember in failed call is rocketchat**undefined**gyfnydxfwddom9jeriode4twmg4i729goh
sarzherbsqpolu33k is our RC deployment ID
![image](https://user-images.githubusercontent.com/4023037/78855061-9201df00-7a2b-11ea-9517-774f78d3737c.png)

So, I can say now, that the root cause of that bug is new version 4.6.1.16337 do not send RC Deployment ID to Jitsi.

**Comment by ankar84** [comment]
@djorkaeffalexandre resolved that issue to me at open.rocket.chat and will resolve it for everybody with this fix https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2017/
Root cause, that default count of results of REST API is set to 50 and now there is 52 settings that mobile application get, so `uniqueID` was cut.
Workaround for that is to set default count for REST API more then 52,for example 60
![image](https://user-images.githubusercontent.com/4023037/78856494-98925580-7a2f-11ea-9474-f827047c1849.png)
Now new version 4.6.1.16337 works really good!

**Comment by diegolmello** [comment]
@ankar84 We're going to merge and release it asap!
