### ISSUE TITLE
[BUG] Critical - Keep crashing in the room with addSectionBlock UIKit

### ISSUE THREAD

**Issue by JuzSer** [RocketChat/Rocket.Chat.ReactNative#2019]
- Your Rocket.Chat Experimental app version: 4.6.0.289
- Your Rocket.Chat server version: 3.0.10
- Device (or Simulator) you're running with: iOS 13

I'm developing some apps for Rocket.Chat but there is a critical issue with Block UIKit. 

The app keeps crashing when you open a room that contains the BlockBuilder there is addSectionBlock (I will tell you more details below). And so on, you will **never** be able to connect to that room again via the app. 

The problem appears when you use block.addSectionBlock but **without** using any other `add...` functions on a messageBuilder.
For example if you use: `block.addSectionBlock(...).addContextBlock(...)` so it's fine. 
But if you only use `block.addSectionBlock(...)` so it's crashed. 

So I think this is because of missing a close tags or something related with the renderer.

**Comment by djorkaeffalexandre** [comment]
Hey @JuzSer, can you contact me on `https://open.rocket.chat/direct/djorkaeff.alexandre`?
If you provide some app with these issue I can debug it more easy.
Thanks in advance.

**Comment by JuzSer** [comment]
Hi, 
I tried to connect to your rocket but my network is very slow to load. 
I've created an app and attached here, so it may help you to see the bug. 

The flow is: 
- Install app
- Type `/mobile-test`
- So the app will send you a message (that only contains the addSectionBlock). 
- You can open rocket via mobile to run the command or just type it on desktop and check on mobile.
- Then the app's crashed. 

[mobile-test.zip](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/4459679/mobile-test.zip)

P/S: I've just figured out one more thing, when you only use addSectionBlock in **modal**, so it's also crash, not only the message.

**Comment by JuzSer** [comment]
Thank @djorkaeffalexandre 👍 
One more thing, can you check the submit button in modal too? 
When I provide the close button without submit button in modal, it's also crashed.

**Comment by djorkaeffalexandre** [comment]
Fixed here https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2022/commits/16f74fc6ca83111d017d4f9b8e8bcd093f0c0c84 😄
