### ISSUE TITLE
Apk size too big

### ISSUE THREAD

**Issue by farfromrefug** [RocketChat/Rocket.Chat.ReactNative#2021]
Right now you seem to be releasing universal apks which means kind of a huge app.
Could you please switch to aab ?

Our planet will thank you ;)

**Comment by diegolmello** [comment]
We use [Hermes](https://hermesengine.dev/) to improve our app's performance, but it [doesn't support App Bundles yet](https://reactnative.dev/docs/hermes#note-about-android-app-bundles)
