### ISSUE TITLE
Broken CAS Authentication on iOS

### ISSUE THREAD

**Issue by pmayer** [RocketChat/Rocket.Chat.ReactNative#2023]
- Your Rocket.Chat Experimental app version: 4.6.1 (16339)
- Your Rocket.Chat server version: 3.0.4
- Device (or Simulator) you're running with: iPhone 8

CAS Authentication doesn't work anymore in 4.6.1 (16339) - after logging in the WebView stays open and nothing happens. It worked fine in 4.6.0 (16245) and before.

**Comment by djorkaeffalexandre** [comment]
Hey @pmayer, can you contact me on `https://open.rocket.chat/direct/djorkaeff.alexandre`, or provide more info about how looks your CAS url while the oauth webview is opened?
Thanks in advance.

**Comment by brtptrs** [comment]
This seems to also be a problem on Android. Am I correct that the standard Android app is now based on this ReactNative code?
It shows version 4.6.3 in the android Play Store, and login via CAS shows the same error described above. For our iOS users the latest 4.6.4 version does sove the problem.

**Comment by djorkaeffalexandre** [comment]
Yes @brtptrs, you're right, Android and iOS apps use the same code base in React Native now, so, it was fixed to both.
Thanks.
