### ISSUE TITLE
Error showing the members of a channel or group.

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#2028]
- Your Rocket.Chat Experimental app version: ####
- Your Rocket.Chat server version: 3.1.0
- Device (or Simulator) you're running with: Android 8.0.0

The option to show the members of a channel or group does not work, Those who are online are not shown and neither are all the channel members

![Screenshot_20200412-200632_RocketChat](https://user-images.githubusercontent.com/35962168/79086769-3bd2bb80-7d0b-11ea-9105-e182ce9ad970.jpg)

**Comment by Krinkle** [comment]
I'm having the same issue on iOS. The channel panel says there are 5 members, but then pressing that shows an empty list (the web interface shows 2 active users in the equivalent interface). Pressing "All" shows a spinner for a second but the list remains empty.

|…|…
|--|--
| ![IMG_4042](https://user-images.githubusercontent.com/156867/79226834-eb687480-7e56-11ea-8e73-ce682cc4c47d.PNG) | ![IMG_4043](https://user-images.githubusercontent.com/156867/79226876-fb805400-7e56-11ea-91eb-7e80644fb413.PNG)

**Comment by jnoorul** [comment]
Able to reproduce the issue in iOS and found that method call "getUsersOfRoom" returns below error,

{"isClientSafe":true,"error":500,"reason":"Internal server error","message":"Internal server error [500]","errorType":"Meteor.Error"}

Server side issue?
