### ISSUE TITLE
Unable to use "Add users"

### ISSUE THREAD

**Issue by Krinkle** [RocketChat/Rocket.Chat.ReactNative#2033]
- Your Rocket.Chat app version: 4.6.3.294.
- Your Rocket.Chat server version: 3.1.0.
- Device: iPhone running iOS 13.4.

**Steps**:
1. In a channel, press "Add users". (I used a private channel, not sure if specific to that.)
2. Observe the initial list of users based on your past interactions.
3. User the input field to type the name of a user not yet in the channel and not in the initial list.

**Expected**
To see their name in the list and be able to select it.

**Actual**
Nothing happens. I press "Next" and the Rocket logo shows up, and it remains this way indefinitely. No timeout either? Also the initial list of 1 name, does not match the input, and yet remains shown. Given that initial list seems to be stored locally, having that filtered locally as well to get started might make sense.

<img alt="" width="200" src="https://user-images.githubusercontent.com/156867/79227715-38007f80-7e58-11ea-8492-c9893a212423.PNG"/>

**Comment by djorkaeffalexandre** [comment]
Hey @Krinkle, what I'm doing different here? It worked fine for me.
![](https://media.giphy.com/media/KBPrPhu15Y0RWDURI3/giphy.gif)

**Comment by Krinkle** [comment]
The username I added started with a capital letter, and I used copy/paste to insert it.

I copied "Hello SomeNameHere" and pasted it there, then removed "Hello " from the start.

I don't know if that made a difference :)

**Comment by djorkaeffalexandre** [comment]
@Krinkle I think it's not create any difference, can you please create a GIF and post here to I see more details?
Thanks in advance.

**Comment by Krinkle** [comment]
I've seen restarted my phone for other reasons and am now unable to replicate the issue. I'll re-open if it happens again.
