### ISSUE TITLE
Broken CAS Authentication on Android

### ISSUE THREAD

**Issue by brtptrs** [RocketChat/Rocket.Chat.ReactNative#2036]
- Your Rocket.Chat Experimental app version: 4.6.1 and 4.6.3
- Your Rocket.Chat server version: 3.0.3
- Device (or Simulator) you're running with: Android 9

The bug from https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2023 seems to also affect Android devices.

Am I correct that the standard Android app is now based on this ReactNative code?

It shows version 4.6.3 in the android Play Store, and login via CAS shows the same error described in the iOS bug report. For our iOS users the latest 4.6.4 version does solve the problem.

**Comment by djorkaeffalexandre** [comment]
@brtptrs it was fixed to android and iOS, wait the 4.6.4 version be launched on Android, you can try to join our beta program, follow README.
