### ISSUE TITLE
Feature Request - Logout from other logged in locations

### ISSUE THREAD

**Issue by AgentTNT** [RocketChat/Rocket.Chat.ReactNative#2041]
Please implement the "Logout From Other Logged In Locations" under the profile section within the mobile app to match the desktop/web versions of the app.

**Comment by ankar84** [comment]
That button in mobile app will be awesome!

**Comment by saurabhshah-sudo** [comment]
I shall be happy to add this feature.

**Comment by diegolmello** [comment]
@saurabhshah-sudo go for it (:
