### ISSUE TITLE
The entire history is not loaded in the public channels.

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#2042]
When you try to load the history only the last two messages are loaded. In previous versions this error did not happen.

**Comment by djorkaeffalexandre** [comment]
@aleadco can you please provide more info like your app and server version?
Thanks in advance.

**Comment by aleadco** [comment]
Excuse me, here I leave the data ...

Version: 4.6.4.16459
Server Version: 3.1.0

**Comment by djorkaeffalexandre** [comment]
@aleadco you have some gif or steps to reproduce it?
Unfortunately I can't reproduce it here.

**Comment by aleadco** [comment]
In the first GIF I show how to clean the cache, in the second I go to the Cujae Community channel and the third is a sample from the browser where you can see the messages of the channel, you will see that not all messages were loaded.  For example, pay attention to the order in which it appears in the audio message and all the messages that were stopped and were before.

![20200416_110750](https://user-images.githubusercontent.com/35962168/79475476-b898ba80-7fd5-11ea-8119-5ce4e696d475.gif)

![20200416_110824](https://user-images.githubusercontent.com/35962168/79475531-c8b09a00-7fd5-11ea-801d-2d0c8b96dcf3.gif)

![20200416_111732](https://user-images.githubusercontent.com/35962168/79475569-d403c580-7fd5-11ea-9709-cbee75ac50b3.gif)

**Comment by djorkaeffalexandre** [comment]
@aleadco Can you please contact me on `https://open.rocket.chat/direct/djorkaeff.alexandre`?
Thanks.

**Comment by ankar84** [comment]
@djorkaeffalexandre 
Actually I can confirm that bug. I'm sure, I saw it on 4.6.0, now I see it on 4.6.1 and 4.6.4
My read-only channel with more then 20 messages, and I can scroll only couple.
And some links in post do not colored - whey work, but user will not see, that it's a link
Server version 3.0.3

**Comment by ankar84** [comment]
I think only unread messages are loaded. And previous messages not.

**Comment by ankar84** [comment]
Definitely that bug persist in 4.7.0 and server 3.1.1
And yes, **Hide system messages** is enabled on system level and channel level.

**Comment by ankar84** [comment]
Fix works great!
Now I successfully scrolled to very top of my read-only channel without any problems.
Thanks @djorkaeffalexandre @diegolmello
