### ISSUE TITLE
some (iOS?) Clients can not use Jitsi - "undefined" in headline

### ISSUE THREAD

**Issue by User35123** [RocketChat/Rocket.Chat.ReactNative#2044]
Hello Team!

- Rocket.Chat App Version 4.6.3
- Rocket.Chat server version: 3.1
- Device (or Simulator) you're running with: iPhone SE, iPad 2017 on iOS 13.4.1

It is absolutely not possible to create or join a Jitsi session with some iOS Clients - but not with all. I have a iPhone X Client (Logged in with Account A) and everything works. But it does not work an a iPhone SE and iPad 2017 (Both using Account B). Account B works fine on a iMac.

When connecting or creating a Jitsi session you can see in the headline of die client "<RocketchatURLprefix> + undefined + <random id>"
This Client is always alone. If you connect to its created session following the link in rocket.chat you are in a other room without the "undefined" part. If the client connects to a already existing session using the link in rocket.chat then the client is also alone in a channel with the "undefined" part. Everything seems to work except seeing other people.

The Problem is similar with this one; 
https://github.com/RocketChat/Rocket.Chat/issues/9419
but it doesn't seem to be a general URL error because other people get a working link. Only the iOS Client get a broken URL. Not sure if this a Client or Server side error.

Stay healthy

**Comment by diegolmello** [comment]
Is this still a thing?
