### ISSUE TITLE
There is no option to remove user or set the user as owner

### ISSUE THREAD

**Issue by Albert88406** [RocketChat/Rocket.Chat.ReactNative#2046]
- Your Rocket.Chat Experimental app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by diegolmello** [comment]
Duplicated of #1864
