### ISSUE TITLE
facebook , google login ( internal server error )

### ISSUE THREAD

**Issue by eig0r** [RocketChat/Rocket.Chat.ReactNative#2051]
- Your Rocket.Chat Experimental app version: 4.6.4
- Your Rocket.Chat server version: 2.4.9
- Device (or Simulator) you're running with: huawei nova3i

after return from facebook  or google login its open use-name page then internal server error
any help please ?
 register  work normal  ( google, fb) from web
register 
![Screenshot_20200420_184942_chat rocket reactnative](https://user-images.githubusercontent.com/27245642/79777677-e2384580-8337-11ea-9dbe-cef9cc0c986b.jpg)
 with user , pass , mail work normal

**Comment by eig0r** [comment]
please some help here ..  i cant login with google or facebook from experment app for any server versions local or cloud

**Comment by diegolmello** [comment]
There's an open PR. We're going to release a beta this week.

**Comment by eig0r** [comment]
when i try to login for open.rocket.chat  with google its working but for  any other servers ( self hosted or cloud free ) i get the same error
