### ISSUE TITLE
Code Blocks on Mobile Phones are not rendered correctly

### ISSUE THREAD

**Issue by MatthiasHertel** [RocketChat/Rocket.Chat.ReactNative#2052]
#### - Your Rocket.Chat Experimental app version: 

Version: 4.6.4.295

#### - Your Rocket.Chat server version: 
```
 λ curl -s https://chat.example.de/api/info | jq .                                            
{
  "version": "3.1.0",
  "success": true
}
```

#### - Device (or Simulator) you're running with: 

ios 13.3.1

#### Problem / Description

rendered code blocks in a message are not shown correctly on mobile clients.
a user wrote the a message with two code blocks (delimitted with three backtics - multiline)
inside the browser the message is shown as below:

![image](https://user-images.githubusercontent.com/8426566/79826868-27429300-839d-11ea-8cb2-fcf8fcf4caba.png)

but on mobile client the delimitting working not correctly , it shows textblocks as code and codeblocks as textblocks:

![image](https://user-images.githubusercontent.com/8426566/79826853-1bef6780-839d-11ea-8b3c-c069aa61c435.png)

**Comment by MatthiasHertel** [comment]
additionally the original raw-text-message ... 

![image](https://user-images.githubusercontent.com/8426566/79827105-c9627b00-839d-11ea-91e6-bc7f5b12e8b2.png)

**Comment by sarthakpranesh** [comment]
Hey @MatthiasHertel, it looks like this issue does not exist anymore on the latest experiment app ( version: 4.7.0.9999999 )

Screenshot attached below
![2](https://user-images.githubusercontent.com/41206172/80400860-074d2b00-88d9-11ea-876c-90be6dbd0af3.png)

**Comment by MatthiasHertel** [comment]
@sarthakpranesh 
yes it looks so ... but how can i get the latest build ( version: 4.7.0.9999999 ) on ios ?
if i visit the app store on ios i can not update to 4.7.xxx i am still on Version: 4.6.4.295

**Comment by sarthakpranesh** [comment]
@MatthiasHertel hey sorry for replying late :sweat_smile: . So we tested this out on the latest build ( version: 4.7.0.9999999 ) and we were able to recreate the error. It seems this only happens when we send a code block from IOS but does not happen when we use Android to send the code block and view it on iPhone. We'll fix it and get back here :fire:
