### ISSUE TITLE
app crashes on connection to Rocket.Chat Server 3.1.1

### ISSUE THREAD

**Issue by photoninger** [RocketChat/Rocket.Chat.ReactNative#2054]
- Your Rocket.Chat Experimental app version: 4.6.4
- Your Rocket.Chat server version: 3.1.1
- Device (or Simulator) you're running with: Android and iOS devices

The app crashes on connection, stack trace starts with
```
com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'length' of null

This error is located at:
  in k
  in s
  in RCTView
  in Unknown
  in Unknown
  in S
  in RCTView
  in RCTView
  in o, js engine: hermes, stack:
getRoomAvatar@1:1525521
....
```
With Rocket.Chat server version 3.0.12 the app was working.
The older version of the app (4.5.1) works also with Rocket.Chat server version 3.1.1.

I suspect the change in https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1958 is the culprit: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/2b3ccf4df57b9479928a19de8355938ded009cf4/app/lib/rocketchat.js#L1238

Screenshots of the full stack trace:
![Clipboard - April 22, 2020 4_11 PM](https://user-images.githubusercontent.com/6586391/79997479-ef7d3d80-84b9-11ea-8cdc-32fd29b57016.png)
![Clipboard - April 22, 2020 4_11 PM(1)](https://user-images.githubusercontent.com/6586391/79997501-f73ce200-84b9-11ea-8385-b430e3ece6ed.png)
![Clipboard - April 22, 2020 4_11 PM(2)](https://user-images.githubusercontent.com/6586391/79997521-fc019600-84b9-11ea-87d4-459cd99cab7c.png)

**Comment by steschuser** [comment]
See this as well after update
Is there a way to insert the missing room.uids?
