### ISSUE TITLE
Update JitsiMeetSDK

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2058]
- Your Rocket.Chat Experimental app version: 4.6.4
- Your Rocket.Chat server version: 3.0.3
- Device (or Simulator) you're running with: Xiaomi Mi9SE

We have a lot of our user complaining issues with Jitsi video call experience. 
Disconnects, audio problems and other.
I see, that JitsiMeetSDK in RocketChat.RN application was[ updated 7 month ago](https://github.com/RocketChat/Rocket.Chat.ReactNative/tree/develop/ios/Pods/JitsiMeetSDK)
Since that time, there is a lot of JitsiMeetSDK updates ([most recent is 3 days ago](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#280-2020-04-21))
@djorkaeffalexandre @diegolmello  please consider to update JitsiMeetSDK for iOS and Android ReactNative Application.
Thanks a lot!

**Comment by diegolmello** [comment]
It's going to be updated on #2008.
I'll continue working on it next week.
Thanks.

**Comment by ankar84** [comment]
> It's going to be updated on #2008.
> I'll continue working on it next week.
> Thanks.

Great news, Diego!
Thanks for your good work!!

**Comment by ankar84** [comment]
Updated in 4.7.0
Thanks, @diegolmello !!
