### ISSUE TITLE
What need for notification on Android and iOS?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2061]
Hi all.

I have own RC Server (3.0.12) and last from google play Rocket Chat Mobile.
What i need for notification on Android and iOS?
I need push gateway? But I wouldn't want to use a public gateway server.

Any way for this?

Thank you

**Comment by diegolmello** [comment]
It's a work in progress, but you can rely on this doc for now: https://docs.google.com/document/d/17ib2Le_SH6U2gP0sEuKapF2J-WgqZxPFMRRVUSofz7Y/edit
