### ISSUE TITLE
1000 limit push for Rocket.Chat free version

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2070]
Hi all!

I see https://rocket.chat/pricing 1000 monthly for push notifications for free.
This is for public Rocket.Chat push gateway?

If i want used my custom apps with my FCM and APN - this is was unlimited or too 1000 limit?

**Comment by diegolmello** [comment]
This is related to the main repo https://github.com/RocketChat/Rocket.Chat
Can you open an issue there?
Thanks.
