### ISSUE TITLE
Show a list of channel users and bug of theme 

### ISSUE THREAD

**Issue by rau-alvin** [RocketChat/Rocket.Chat.ReactNative#2074]
Hello!

Thank you four your great progect!

My desktop apps show a list of channel users, but Android apps don’t.
What is the problem?

![Screenshot_2](https://user-images.githubusercontent.com/62691026/80575656-9a3ab200-8a0c-11ea-8e96-f33e4b10f52c.jpg)

![3](https://user-images.githubusercontent.com/62691026/80575677-a0c92980-8a0c-11ea-89d8-e9de0871e7f2.png)

Also i have  an interesting bug of theme. In the dark theme don't show advanced info for users, but in white theme ok.

![4](https://user-images.githubusercontent.com/62691026/80576398-ca368500-8a0d-11ea-87ac-adf72f0dc321.png)

![5](https://user-images.githubusercontent.com/62691026/80576435-d91d3780-8a0d-11ea-9492-f99679114f10.png)

- 
- Rocket.Chat app version: 4.6.4.2118
- Rocket.Chat server version: 3.2.0
- Device (or Simulator) you're running with: phone on Andoid 10, pc on Windows 10

**Comment by diegolmello** [comment]
Duplicated of #2028 
We're going to release a fix in the next days.

Note: Remember to open one issue per subject. If you're still having trouble with theme, open another one.

Thanks.
