### ISSUE TITLE
e2e tests not working on v4.6+

### ISSUE THREAD

**Issue by bodrak** [RocketChat/Rocket.Chat.ReactNative#2086]
Hello,

I noticed that in the version 4.6+ of Rocket.Chat, e2e tests were not working any more. Are you planning to readapt them, and if yes when approximately ?

Thanks

**Comment by diegolmello** [comment]
Since a few updates, Detox (the lib we've been using for e2e tests) stopped working properly and we thought too cumbersome to maintain it working.
Even when it worked, it wasn't completely reliable and we never made it to work on Android.
That's why we're analysing other options, like Appium.

**Comment by bodrak** [comment]
ok, thanks for your answer !
