### ISSUE TITLE
GSoC20: Create F-Droid Build for RN Android

### ISSUE THREAD

**Issue by GOVINDDIXIT** [RocketChat/Rocket.Chat.ReactNative#2096]
## SubTasks
- Integrate Fastlane to the android module and configure CI to use Fastlane
 **PR** #2100 (Merged)
- Create Play and Foss builds for android app  **PR** #2171 (Merged)
- Update CI Config to separately build foss and play version for android client  **PR** #2366 (Merged)

**Comment by GOVINDDIXIT** [comment]
Hi @webmind The work is completed, you can expect to have the latest version of RC on the Fdroid by very next release.

**Comment by elmanytas** [comment]
I don't find the rocketchat package in f-droid and apk installed from releases page does not install in lineageos without google apps.
