### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#210]
- [ ] Add custom icons
- [ ] Apply custom icons on entire project
- [ ] Remove react-native-vector-icons from project

**Comment by saketkumar95** [comment]
@diegolmello  Will you be working on this?

**Comment by diegolmello** [comment]
I don't know. Talk to Gazzo.

**Comment by lucasOlivio** [comment]
@diegolmello any news on this? I really needed to make some alterations and add some new icons in my project here.
