### ISSUE TITLE
[IOS]: Do not show the progress bar when uploading files> 50MB in size

### ISSUE THREAD

**Issue by xuanduyrn** [RocketChat/Rocket.Chat.ReactNative#2108]
- Your Rocket.Chat server version: new verison
`"react-native": "0.62.2",`

Issue upload video:
- `src / views / UploadProgress` When uploading a file video with size > 50mb, the progress bar is not visible, the video is still uploaded normally but it must be out of the room and re-visited to see the video I uploaded. `Android works normally`
- I think there is a problem in lib @ nozbe / watermelondb

**Comment by diegolmello** [comment]
App version?
Do you mean it doesn't work on iOS only?
It doesn't seem to be related to local db, since the video isn't stored there.

**Comment by xuanduyrn** [comment]
> App version?
> Do you mean it doesn't work on iOS only?
> It doesn't seem to be related to local db, since the video isn't stored there.

![image](https://user-images.githubusercontent.com/31473225/81783257-47411e80-9525-11ea-8dd2-4402968d1148.png)
- App version: I am testing the app on testflight with version 1.0.51 and always merge your code with the latest updates.
Yes, it does not work on iOS
This is the progress I got when I was uploading files on Android, it was always updated in the render () component UploadProgress.js size> 50mb, while iOS mostly it only returned progress for size <50mb, also> 50mb do not work.
Tks

**Comment by xuanduyrn** [comment]
Sorry, The problem has been resolved 😅
