### ISSUE TITLE
[Cross Post] Disparity between Web and Mobile apps

### ISSUE THREAD

**Issue by AgentTNT** [RocketChat/Rocket.Chat.ReactNative#2112]
Posting this issue here as well for visibility, as this will require a combined effort to get the two offerings in a synced state. Should all be minor changes required in the ordering/wording of the menus. Should also help with bringing a solid "united standards" to the product. 

https://github.com/RocketChat/Rocket.Chat/issues/17606

**Comment by diegolmello** [comment]
We can discuss that on the comments, but currently we opted to not sync it, because they are different use cases.
The same user can opt to have unread on top on the web client and iPad, but disable it on the mobile (because of the smaller screen).
I'm happy to discuss pros and cons below.
Thanks.
