### ISSUE TITLE
False positive on Android Official App: Login screen pops up even when logged in

### ISSUE THREAD

**Issue by avimanyu786** [RocketChat/Rocket.Chat.ReactNative#2113]
- Rocket.Chat Official app version: 4.6.4
- Rocket.Chat server version: 3.1.1
- Device running with: Android 10

The rocket chat login screen pops up even when logged-in to the android app. Closing them twice brings back the logged-in session.

**Comment by ankushdas9** [comment]
@geekgonecrazy  I can confirm this.

It's happening on Android. 

Whenever we receive a notification, and we click on it to open the app, it just logs out.

If we launch the app separately without clicking on the notification received, no log out issues.

Downloaded via Play Store. App version: 4.6.4.2118.

**Comment by geekgonecrazy** [comment]
@diegolmello your team have any idea on this?

**Comment by diegolmello** [comment]
@avimanyu786 @ankushdas9 Can you ping me on https://open.rocket.chat?
I'm `@diego.mello`.
We'll have to test on your end.
Thanks.

**Comment by avimanyu786** [comment]
Many thanks for the assist @diegolmello ! Thank you too @geekgonecrazy and @ankushdas9 !

The issue was around an `http` URL inside **`Admin Panel`** > **`General`** > _`Site URL`_. Changing it to `https` fixed it. 

Sometimes the trickiest issues do have simple solutions!

**Comment by geekgonecrazy** [comment]
Didn’t even think of that causing it.  Cool!  :)
