### ISSUE TITLE
User status become offline (invisible) on application starts after it was explicitly closed

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2123]
- Your Rocket.Chat Experimental app version: 4.7.0.17013
- Your Rocket.Chat server version: 3.1.1
- Device (or Simulator) you're running with: Xiaomi Mi 9SE

User status become offline (or invisible - gray dot) on application starts after it was explicitly closed (by memory clean or swipe out from launched apps)
![status](https://user-images.githubusercontent.com/4023037/82072945-ae67fa00-9702-11ea-8c54-3db57b2a9a7e.gif)
On app close in Websocket of another user I see:
![image](https://user-images.githubusercontent.com/4023037/82073617-b3797900-9703-11ea-80ff-8c26e2946ee3.png)
`a["{\"msg\":\"changed\",\"collection\":\"stream-notify-logged\",\"id\":\"id\",\"fields\":{\"eventName\":\"user-status\",\"args\":[[\"gYFnyDxfwdDom9jeR\",\"karlanaat01\",0,\"Тестируем РокетЧат\"]]}}"]`
And on start after close I see (status 1, but apps shows gray dot):
![image](https://user-images.githubusercontent.com/4023037/82073690-cb50fd00-9703-11ea-9f3d-ae707387d601.png)
`a["{\"msg\":\"changed\",\"collection\":\"stream-notify-logged\",\"id\":\"id\",\"fields\":{\"eventName\":\"user-status\",\"args\":[[\"gYFnyDxfwdDom9jeR\",\"karlanaat01\",1,\"Тестируем РокетЧат\"]]}}"]`

And after lock-unlock smartphone  (or minimize-maximize app) I see 
![image](https://user-images.githubusercontent.com/4023037/82073834-04896d00-9704-11ea-89e1-8795c1f4102c.png)
and status become normal (previous installed status)

**Comment by ankar84** [comment]
open.rocket.chat with 3.3.0 not affected with that issue. So for now that bug appears on 3.1.1

**Comment by diegolmello** [comment]
It was something on the server, right?
I'm closing.
