### ISSUE TITLE
Omnichannel Toggle

### ISSUE THREAD

**Issue by AgentTNT** [RocketChat/Rocket.Chat.ReactNative#2124]
- Your Rocket.Chat Experimental app version: 4.7.0.17013
- Your Rocket.Chat server version: 3.2.1
- Device (or Simulator) you're running with: Samsung Note10+

With the addition of omnichannel in the mobile app (which is awesome btw), can you please implement the toggle to allow the agent to enable/disable the acceptance of new chats?

Also are there plans to implement the queue viewing feature within the mobile app, if new chats are not auto assigned?

**Comment by diegolmello** [comment]
Omnichannel is a whole new world, so we're implementing it in parts.
We plan to implement all features :)
