### ISSUE TITLE
Adding a new field does not work, requiring logout and login again.

### ISSUE THREAD

**Issue by xuanduyrn** [RocketChat/Rocket.Chat.ReactNative#2127]
- Your Rocket.Chat Experimental app version: 4.6.4.295

- Hi, I am having problems with the fields adding new to the database. Can you explain more to help me how it works and how to optimize the field when adding a field to the local database?
- This is my problem:
 + I added a new field location to the application, updated the field into `tableSchema ``/app/lib/database/schema/servers.js.`
But I have to logout and login to see this field?
Do you have a way of dealing with not logging out and still getting new fields added? 
 + I tried to set the function to call that new field in another function that didn't have to be logged in, but most of the database couldn't be updated either, forcing me to logout and login again.
Tks

**Comment by diegolmello** [comment]
https://nozbe.github.io/WatermelonDB/Advanced/Migrations.html

**Comment by xuanduyrn** [comment]
@diegolmello tks :D
