### ISSUE TITLE
System-wide "Hide system messages" settings are partly ignored in App

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2128]
- Your Rocket.Chat Experimental app version: 4.7.0.17013
- Your Rocket.Chat server version: 3.1.1
- Device (or Simulator) you're running with: Xiaomi Mi9SE

I configured **Hide System Messages** settings like this:
![image](https://user-images.githubusercontent.com/4023037/82185973-bc7c6d00-98f2-11ea-846b-08c77af45dbb.png)
And Web versions works perfect - no any system messages about join, leave, add and remove users to chat.
But mobile application still show that messages in some circumstances and on refresh hide them.
![image](https://user-images.githubusercontent.com/4023037/82186888-3b25da00-98f4-11ea-9306-b47b4a7e5fae.png)
![Filename (1)](https://user-images.githubusercontent.com/4023037/82186958-555fb800-98f4-11ea-91bb-bfcde33058af.gif)
But when I set hide system messages in a chat, like this for example
![image](https://user-images.githubusercontent.com/4023037/82187361-f5b5dc80-98f4-11ea-8a63-ce5334274b03.png)
System messages do not appears anymore.

**Comment by djorkaeffalexandre** [comment]
@ankar84 can you describe "some circumstances"?
I'm not able to reproduce tis behavior here.

**Comment by ankar84** [comment]
New version works perfect!
Thsnks @djorkaeffalexandre @diegolmello
