### ISSUE TITLE
No signal when starting voice call

### ISSUE THREAD

**Issue by giterium** [RocketChat/Rocket.Chat.ReactNative#2129]
- Your Rocket.Chat Experimental app version: 4.6.4.295
- Your Rocket.Chat server version: 3.0
- Device (or Simulator) you're running with: any

There is no ring sound played when a video call is started. is there a way to activate this or add this feature?
In direct chats. In mass conferences this probably doesn't make sense

**Comment by diegolmello** [comment]
It's not implemented yet.

**Comment by poorhoseini** [comment]
Any Good News?

**Comment by ankar84** [comment]
Users ask for it in DMs a lot.

**Comment by ankar84** [comment]
Hi, @diegolmello 
[Here](https://github.com/jitsi/jitsi-meet/issues/8436#issuecomment-762825745) @saghul answered:

> I think this can be implemented outside of Jitsi, in the embedding app. The next SDK version (3.0) will have participant joined / left events, so you'd be able to start a ringtone when conference is joined, while there is no other participants.

Can that feature be implemented by this issue? Or I need to make another issue?
Thanks!

**Comment by diegolmello** [comment]
@ankar84 I guess it does but we have other priorities right now.
If this is important to your team, can you hire a freelancer (upwork or any other site) to do it?
I'd make sure it is released ASAP.
Thanks.

**Comment by ankar84** [comment]
> @ankar84 I guess it does but we have other priorities right now.

Yeap, I know it.

> If this is important to your team, can you hire a freelancer (upwork or any other site) to do it?

I don't think it's a critical issue for us, just would be nice if it's implemented in RCRN.

**Comment by t2hieu91** [comment]
Any Good News?

**Comment by rfakit** [comment]
anyone there?

**Comment by Yakusari** [comment]
This should really be added, as it is now it makes the calling option pretty much useless

**Comment by solutionprovider9174** [comment]
this will work like telephone ringtone when some other user give his call to someone?
I am waiting for ringtone issue fixing on react native app.
how can i fix it by myself?

**Comment by solutionprovider9174** [comment]
Hello, I have fixed these issues with my developer team.
My skype is this : live:.cid.a3e05258f0b595aa
