### ISSUE TITLE
[Auto-Translate]: The auto translate function is off but the toggle button is still ON

### ISSUE THREAD

**Issue by xuanduyrn** [RocketChat/Rocket.Chat.ReactNative#2134]
- Your Rocket.Chat Experimental app version: 4.6.4.295

Hi, I have a question that may be silly, but I still haven't investigated the cause.
If you help me, it will be faster.
**Step**:

1. When entering the chat room
 2. Go to room actions
 3. Select translate function
 4. Enable translate (work)
 5. Disable translate (no work)
 6. clear cache (translate disable)

Can you explain me the mechanism when turning on translate? Where is it stored? Why is disabled, its state cannot be updated!

I'm still investigating, Tks!

**Comment by xuanduyrn** [comment]
@diegolmello Can you help me? :D

**Comment by diegolmello** [comment]
@xuanduyrn I didn't understand the issue.
Can you give us more details?
Maybe a gif?

**Comment by xuanduyrn** [comment]
![Hnet-image](https://user-images.githubusercontent.com/31473225/82514863-00fd4800-9b41-11ea-8fbb-fd26191912ea.gif)
Turning off translate doesn't work! @diegolmello

**Comment by xuanduyrn** [comment]
![RPReplay-Final1590048323](https://user-images.githubusercontent.com/31473225/82537957-22782700-9b75-11ea-89ed-54de7da02623.gif)
GIF: 28s
Translation is turned off, but the button switch is ON until the clear cache :+1:  @diegolmello help

**Comment by t2hieu91** [comment]
same issue +1
@diegolmello Does Bro have a solution to this problem?

**Comment by xuanduyrn** [comment]
@EzequielDeOliveira work, tks <3

**Comment by EzequielDeOliveira** [comment]
@xuanduyrn  YW <3
