### ISSUE TITLE
[i18n] Arabic language (RTL)

### ISSUE THREAD

**Issue by olafdev** [RocketChat/Rocket.Chat.ReactNative#2140]
Does it support RTL language?
I can't find Arabic. Would you help me?

**Comment by diegolmello** [comment]
@expert-group you can help us reviewing this PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1941

**Comment by expert-group** [comment]
Thank you @diegolmello . Btw could you tell me how can I integrate arabic lanauge and RTL view on latest version? Thank you.

**Comment by diegolmello** [comment]
@expert-group It's not implemented yet, but it should be straight forward.
Here's an attempt: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/856

**Comment by expert-group** [comment]
@diegolmello When will it be implemented? Is it planned?

**Comment by diegolmello** [comment]
@expert-group It's not planned. Can you do the translations and open a PR?

**Comment by expert-group** [comment]
@diegolmello I think view is not ready for RTL yet

**Comment by expert-group** [comment]
@diegolmello How can I make view for RTL?

**Comment by diegolmello** [comment]
@expert-group Can you at least check #856?

**Comment by bhanujggandhi** [comment]
@diegolmello Is this issue resolved?

**Comment by diegolmello** [comment]
@bhanujggandhi it is. Thanks.
