### ISSUE TITLE
Missed locales in Screen Lock menu

### ISSUE THREAD

**Issue by IhorNykyha** [RocketChat/Rocket.Chat.ReactNative#2145]
- Your Rocket.Chat Experimental app version: 4.7.0
Missed values in locales in Screen Lock menu
![Screenshot 2020-05-26 at 16 50 58](https://user-images.githubusercontent.com/46314384/82912724-15dd3f80-9f76-11ea-8731-94897e046c80.png)
![Screenshot 2020-05-26 at 16 52 40](https://user-images.githubusercontent.com/46314384/82912728-170e6c80-9f76-11ea-9052-2455b0287a86.png)
![Screenshot 2020-05-26 at 16 54 07](https://user-images.githubusercontent.com/46314384/82912731-170e6c80-9f76-11ea-8550-7afa7f636128.png)

**Comment by diegolmello** [comment]
Can you tell more info about it?
Are you running from a store?
Are you running from develop branch?

**Comment by IhorNykyha** [comment]
I get source code from this 
https://github.com/RocketChat/Rocket.Chat.ReactNative/archive/4.7.0.zip

**Comment by IhorNykyha** [comment]
Sorry its my mistake
