### ISSUE TITLE
Some settings from desktop version don't work in app

### ISSUE THREAD

**Issue by lpilz** [RocketChat/Rocket.Chat.ReactNative#2148]
- Your Rocket.Chat Experimental app version: 4.7.0.17188
- Your Rocket.Chat server version: 3.2.2
- Device (or Simulator) you're running with: Samsung Galaxy Note 8

There are several settings which don't seem to apply to the app. Examples are:
1. messageViewMode (Thread replies are not properly hidden from channel when "value" is 3)
2. hideUsernames and UI_use_real_name (usernames are shown instead of real names for reactions)
3. Notification sound can't be disabled

**Comment by diegolmello** [comment]
There are several settings we didn't implement yet.
Can you open one issue per setting so we can track the development?
I would be happy to review your contributions (:

Closing this one. Thanks.
