### ISSUE TITLE
Save workspace info

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat.ReactNative#2149]
- Your Rocket.Chat Experimental app version: 4.7.0
- Your Rocket.Chat server version: self-hosted 3.2.1
- Device Android 10/IOS

Every time the user is logged out when token expires he has to fill in the worskspace name again. 

It would be great to save the workspace name to only have username/password to fill in after logout.

Thanks for the job done !

**Comment by mddvul22** [comment]
We are now logging our users out every day, for security reasons.  This bug is frustrating.

**Comment by diegolmello** [comment]
Let's keep the conversation on #2348
