### ISSUE TITLE
Empty Notifications on Android

### ISSUE THREAD

**Issue by markuspi** [RocketChat/Rocket.Chat.ReactNative#2150]
Message notifications only contain the user handle. User display name and message content is missing.

- Your Rocket.Chat Experimental app version: 4.7.0.17188
- Your Rocket.Chat server version: 3.0.12
- Device (or Simulator) you're running with: Honor 10 (COL-L29) Android 9

![photo_2020-05-28_12-17-07](https://user-images.githubusercontent.com/22451745/83129775-97031680-a0dd-11ea-9e25-e16fbcc66ac0.jpg)

**Comment by diegolmello** [comment]
Can you check these settings on Admin > Push?
![image](https://user-images.githubusercontent.com/804994/83139329-914c0780-a0c2-11ea-99ef-892080df3e0f.png)

**Comment by markuspi** [comment]
Ah, I didn't know it is actually a privacy feature! Since it's an enterprise environment, I unfortunately don't have influence over the server. But that answers my question, thanks!
