### ISSUE TITLE
Threads are not properly hidden

### ISSUE THREAD

**Issue by lpilz** [RocketChat/Rocket.Chat.ReactNative#2151]
- Your Rocket.Chat Experimental app version: 4.7.0.17188
- Your Rocket.Chat server version: 3.2.2
- Device (or Simulator) you're running with: Samsung Galaxy Note 8

The setting `messageViewMode` 3 (compact layout) is ignored in the app, it always displays in cozy layout (2).

**Comment by dkoo761** [comment]
Since there is no longer an option to choose compact vs cozy layout, I think the new problem is now:

The user preference "Show thread messages in the main thread" is being ignored.

**Comment by diegolmello** [comment]
We're going to implement new threads version on a future release.

**Comment by diegolmello** [comment]
Let's track on #2387
