### ISSUE TITLE
Updated usernames don't show in app

### ISSUE THREAD

**Issue by lpilz** [RocketChat/Rocket.Chat.ReactNative#2153]
- Your Rocket.Chat Experimental app version: 4.7.0.17188
- Your Rocket.Chat server version: 3.2.2
- Device (or Simulator) you're running with: Samsung Galaxy Note 8

When updating usernames, old usernames (e.g. in reactions) are not updated to match the new one.

**Comment by lpilz** [comment]
Since this is a bug, which also occurs in the desktop version as I just found out, I'll close it here and open an issue in the main repo.

**Comment by djorkaeffalexandre** [comment]
@lpilz, it's probably related a something like the auto-translate messages, the messages that are saved at your database not will be updated when you change the username, maybe if you clean your cached database it requests the messages with the right name.
Thanks anyway.

![Screen Shot 2020-05-28 at 11 39 20](https://user-images.githubusercontent.com/29778115/83155712-e7777580-a0d7-11ea-9429-eefc77df20f7.png)

**Comment by lpilz** [comment]
Auto-Translation is off for us

**Comment by djorkaeffalexandre** [comment]
@lpilz, yes, I'm just saying that is the same thing of the auto-translate case, messages already saved at Database.
I'm saying about the client-side, just clean your cache at our mobile app at settings screen and see if it's fixed. :)

**Comment by lpilz** [comment]
Ah, I found out that it's the import, which is not working correctly, so somehow the link between `old reactions -> _id -> (current) username` seems to be broken

**Comment by djorkaeffalexandre** [comment]
Sure @lpilz, if you want to open an issue at our main repository, don't forget to explain this point.
Thanks.
