### ISSUE TITLE
Dependency not found during yarn or npm install

### ISSUE THREAD

**Issue by kscryoice** [RocketChat/Rocket.Chat.ReactNative#2155]
- Nodejs version: 12.17.0
- Npm version: 6.14.5
- Yarn: 1.22.4
- Windows 10 v1909

Rocket.Chat.ReactNative branch [develop](https://github.com/RocketChat/Rocket.Chat.ReactNative) on latest version [594e598](https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/594e598167b0ace43ed15410191a32bf59ae22b3)

I clone the repository and tried to install dependency with yarn, but it has error "Couldn't find the binary git" like in the picture below.

![image](https://user-images.githubusercontent.com/53338982/83241930-c8efa800-a1c5-11ea-8730-15b0e49c186d.png)

I also tried to use npm install, which reveal that the npm not being able to find the library [https://github.com/RocketChat/commonmark.js.git](https://github.com/RocketChat/commonmark.js.git). The link itself is correct and redirect to the correct page, but when I npm install it shows the error like in the picture below.

![image](https://user-images.githubusercontent.com/53338982/83242462-ab6f0e00-a1c6-11ea-9309-f631dc37c4f0.png)

**Comment by diegolmello** [comment]
Not related to this repo.
If you Google it, you find this issue on yarn: https://github.com/yarnpkg/yarn/issues/2083
