### ISSUE TITLE
Real Name search doesn't work in Add Users form

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2158]
- Your Rocket.Chat Experimental app version: 4.7.0.17188
- Your Rocket.Chat server version: 3.1.1
- Device (or Simulator) you're running with: Xiaomi Mi 9 SE

Search for users works perfectly in Directory Search. It does search by username and which is really much important for me and my users it does search by Real Name (which in my deployment almost always Cyrillic and not English names)
Here is example of Cyrillic search in mobile application on open.rocket.chat 
![Screenshot_2020-05-30-20-49-56-608_chat rocket reactnative](https://user-images.githubusercontent.com/4023037/83330123-5b23a900-a2b7-11ea-9ef2-451156d9574f.jpg)

And here is an example of how Cyrillic search doesn't work in Add Users form (when private chat owner need to add users to his chat)
![Screenshot_2020-05-30-20-50-18-213_chat rocket reactnative](https://user-images.githubusercontent.com/4023037/83330133-65de3e00-a2b7-11ea-8c07-36faddc3af7e.jpg)
So, please, fix that search form and search in mobile application will be consistent and convenient for users.

**Comment by djorkaeffalexandre** [comment]
Thanks for opening this @ankar84, we'll try to add this as a fix at our 4.8.0 release, this will probably be launched at end of June.

**Comment by giterium** [comment]
is there any news?
The same problem is found in chat search...

**Comment by refactor-droidyy** [comment]
@ankar84  @giterium can i work on this?

**Comment by ankar84** [comment]
> @ankar84 @giterium can i work on this?

I'm not a developer, to my deep regret.

**Comment by diegolmello** [comment]
@refactor-droidyy sure :)

**Comment by shobhi1310** [comment]
Has a pull request been made for this issue, and is it closed, or else can I work on it ?

**Comment by ankar84** [comment]
@diegolmello hi! Can you take a look at that issue?

**Comment by ankar84** [comment]
> Has a pull request been made for this issue, and is it closed, or else can I work on it ?

Please work on that issue if you can. There is no ready pr for that.

**Comment by diegolmello** [comment]
@ankar84 I created the following user:
```
real name: d098
username: diego.mello1409
```

and searched by real name
<img src="https://user-images.githubusercontent.com/804994/93091182-2542de80-f674-11ea-8b6a-86168ea3e227.png" width="350" />

The issue is just the duplicated username?
Or is there something else?

**Comment by ankar84** [comment]
> The issue is just the duplicated username?
> Or is there something else?

No.
Issue is about search users with non English real name (Cyrillic as example) in add users and magnifying glass tool.
Directory search works fine on Cyrillic Real Name (first screen) but when you try to add user yo some channel by Cyrillic Real Name - search results are not correct. And magnifying glass too search by Cyrillic Real Name not correct.

**Comment by diegolmello** [comment]
Can you create a reproducible example on open server?

**Comment by ankar84** [comment]
> Can you create a reproducible example on open server?

Yes. All screens from open.rocket.chat
Try to find Антон in Directory search and with magnifying glass tool.

**Comment by ankar84** [comment]
@diegolmello I just tested that updates and it much more better than before, but still small amount of search results
Here is same search for `Антон` with Magnifying glass tool
