### ISSUE TITLE
[Page Files in Room]: Error paging data

### ISSUE THREAD

**Issue by xuanduyrn** [RocketChat/Rocket.Chat.ReactNative#2159]
- Your Rocket.Chat Experimental app version: 4.7.0

![026E105B-7F40-4A30-B775-3B9E262BF187](https://user-images.githubusercontent.com/31473225/83384230-098f3180-a411-11ea-9d7f-f569d0905de4.gif)

- When I go to Page Files I try to scroll down to download more data according to the paging you are doing, but the paginated data is currently being duplicated.
- Do you have any PR for this issue?
@EzequielDeOliveira @diegolmello

**Comment by djorkaeffalexandre** [comment]
Hey @xuanduyrn, we don't have a PR to this issue yet.
If you want to fix, feel free to open that.
Thanks in advance.

**Comment by AligDanish** [comment]
@djorkaeffalexandre I want to solve this issue for study purpose if you allow me.

**Comment by djorkaeffalexandre** [comment]
@AligDanish sure, go ahead! 😀

**Comment by xuanduyrn** [comment]
@AligDanish Do you have a solution to this problem? I still haven't had time to look into this issue, if you fixed it, please let me know <3 tks u
