### ISSUE TITLE
Mobile uploads: names of files are not saved not correctly in non-latin alphabet (Russian, Arabic, Chinese)

### ISSUE THREAD

**Issue by lelvisl** [RocketChat/Rocket.Chat.ReactNative#2160]
- Your Rocket.Chat Experimental app version: 4.7.0.300
- Your Rocket.Chat server version: 3.3.0
- Device (or Simulator) you're running with: iOS & Android
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1952 - in those fix you are encoding and decoding filename in view. 

This works only for photos. When i uploading file from mobile -  i see
![IMAGE 2020-06-02 9:10:28 PM](https://user-images.githubusercontent.com/9326764/83554476-7f7cc100-a515-11ea-8169-478a3e5b2a5e.jpg)
And with photos, when i watch preview - i see filename correctly. But on download - photo's file name is lost. 
I don't think that this is correct behaviour. 

On desktop app i can upload any file with non-latin alphabet. May be you should use algorithm from desktop app?

**Comment by maxsaleev** [comment]
@djorkaeffalexandre maybe this problem comes from rn-fetch-blob ? And using encodeURI() is not a good idea for rocket.chat ? 

I have found something similar there https://github.com/joltup/rn-fetch-blob/issues/254 
> you can use encodeURI() on the filename before uploading then downloading the file should be fine

It seems they also have problems with Russian Arabic Chinese

**Comment by djorkaeffalexandre** [comment]
Hey guys! I think an `encodeURI` should resolve our issue.
If someone of you can give a try, feel free to open a pull request.
I'll try to take a look ASAP, if nobody take this.
Thanks.

**Comment by imrishabh18** [comment]
@djorkaeffalexandre Is this resolved yet? If not can I get some directions on how to resolve this thing.

**Comment by billypon** [comment]
@imrishabh18 

The filename was encoded, and had been saved to db, I think the simply way is decode the file name when the `loadHistory` API is calling, or do decode on both app and web client.

View template on app is `Rocket.Chat.ReactNative/app/views/MessagesView/index.js`, and on web is `Rocket.Chat/app/message-attachments/client/messageAttachment.html`.

**Comment by billypon** [comment]
I want to drop the bad PR([[FIX] Allow special chars in Filename](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2020)), I decode filename on `sendFileMessage` Meteor method, so that I can solve this issue temporary without compile app. Because I don't need the 'special chars'

**Comment by djorkaeffalexandre** [comment]
> And with photos, when i watch preview - i see filename correctly. But on download - photo's file name is lost.
I don't think that this is correct behaviour.

@lelvisl We're generating a new filename to each image before save it to the device, your suggestion is about use the original filename?
If yes, can you create a new issue? Each GH issue should refer to a specific problem.
Thanks.
