### ISSUE TITLE
/usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by wahdatjan** [RocketChat/Rocket.Chat.ReactNative#2161]
Cloned the Rocket chat react native repo then try to **yarn install** . but getting _/usr/bin/env: ‘node’: No such file or directory
_ because i have rocket chat web app running for which i removed node , mongodb and etc because rocketchat doc says meteor installs node internally , you dont need to install seperately . Now how would i manage to run both web app with meteor and reactnative app with node .?

**Comment by diegolmello** [comment]
You have to install node.
You can find more info here: https://reactnative.dev/docs/environment-setup

**Comment by wahdatjan** [comment]
@diegolmello will installing node hamper me from running rocket chat web app using meteor
??
