### ISSUE TITLE
[Bug] RoomsListView become not actual in some moment - only clear cache helps

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2164]
- Your Rocket.Chat Experimental app version: 4.7.0
- Your Rocket.Chat server version: 3.1.1
- Device (or Simulator) you're running with: Xiaomi Mi 9 SE

Majority of our users are complaint about **room (or chat) list become not actual in some moment** and pull to refresh do not refresh anything, but **clear cache does solve that problem** - all chats, that was in web version appears in mobile application. People complains that they miss important calls and messages because of that bug. 
Yesterday I experienced it by myself - I got push notification, tap on it, application opened, but there is not chat from push in list. I cleared cache and chat was appeared in moment.

**Comment by diegolmello** [comment]
Is this still a thing?
I'm closing and you can open (if needed) following the new issue template, ok?
Thanks :)
