### ISSUE TITLE
Missing documentation: Configuring mobile client for single-server

### ISSUE THREAD

**Issue by Rhywden** [RocketChat/Rocket.Chat.ReactNative#2172]
This is the paragraph about single-server for a custom-built mobile app in README.md:
> Running single server
If you don't need multiple servers, there is a branch single-server just for that. Readme will guide you on how to config.

I switched to the single-server branch but the Readme did not guide me (because it was the same as for the master branch). Which "Readme" is meant precisely by this paragraph?

**Comment by diegolmello** [comment]
Docs aren't merged yet.
You can refer to our draft here: https://docs.google.com/document/d/17ib2Le_SH6U2gP0sEuKapF2J-WgqZxPFMRRVUSofz7Y/edit
