### ISSUE TITLE
Attachment.actions not rendering

### ISSUE THREAD

**Issue by nishantt12** [RocketChat/Rocket.Chat.ReactNative#2174]
I am trying to render action buttons and send message based on the action click, but these buttons are not getting rendered in the UI, how can I render the Action buttons in our app?

```
"attachments":[{
  "button_alignment": "horizontal",
  "actions": [
    {
      "type": "button",
      "text": "Daily Nakshatra (English)",
      "msg": "dailyhoroscope english",
      "msg_in_chat_window": true
    },
    {
      "type": "button",
      "text": "Daily Nakshatra (Telugu)",
      "msg": "dailyhoroscope తెలుగు",
      "msg_in_chat_window": true
    },
    {
      "type": "button",
      "text": "Numerology",
      "msg": "Numerology english",
      "msg_in_chat_window": true
    },
    {
      "type": "button",
      "text": "MatchMaking",
      "msg": "Matchmaking english",
      "msg_in_chat_window": true
    }
  ],
  "fields": [
    
  ],
  "attachments": [
    
  ]
}]
```

**Comment by 1rV1N-git** [comment]
Hello @diegolmello 
Can you fix it?

**Comment by diegolmello** [comment]
@nishantt12 You should use UIKit for that.
Try `/poll` app: https://github.com/sampaiodiego/rocket.chat.app-poll
It renders buttons dinamically.

**Comment by JargeZ** [comment]
Hello
UIKIT is definitely good and I use it
But now there is a problem that it is impossible to implement navigation in bots like hubots, botkits, botpress and others.
I use command buttons for navigation, but they only work on the desktop version
This function in the current implementation is quite enough for the implementation of navigation, for everything else, UIKIT is used in apps

I want to know if it is possible to add support for buttons only for sending a command for easy navigation and consistency with desktop version?
I apologize for the question in a closed issue
But unfortunately there is no way to switch to full use of the application engine for complex bots with integrations of other company services

**Comment by djorkaeffalexandre** [comment]
Hey @JargeZ, can you open an issue describing these things and provide an app that has this behavior, so we can try it here?
Thanks.

**Comment by JargeZ** [comment]
@djorkaeffalexandre I think there is no need to create a separate issue because the current one is about this problem

The problem is that when sending a message as in the example below to the api address `http://localhost:3000/api/v1/chat.sendMessage`
```
{
   "message": {
      "rid": "upmtL9Qhk8rMNSYSp",
      "attachments": [{
            "color": "#ff0000",
            "text": "Test buttons",
            "button_alignment": "horizontal",
            "actions": [
                {
                    "type": "button",
                    "text": "Daily Nakshatra (English)",
                    "msg": "dailyhoroscope english",
                    "msg_in_chat_window": true
                }
            ]
      }]
  }
}
```
On the desktop version, buttons are displayed:
![ex](https://imgur.com/tqfN35v.png)
But not on mobile:
![Imgur](https://imgur.com/vpjB8jl.png)
the same problem with table fields :'(\
\
Mobile client version: 4.12.0.2140
Server version: 3.7.1

**Comment by 1rV1N-git** [comment]
@djorkaeffalexandre can you fix this issue?

**Comment by bart11064** [comment]
Having the same issue here, and interested in getting it working in the mobile app.

**Comment by yash-rajpal** [comment]
I would be glad to take up this issue, can anyone please brief me what has to be done here?
