### ISSUE TITLE
Can i get notification when started Video call jitsi?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2176]
Hi all.

Can i get notification when started Video call jitsi?

**Comment by ankar84** [comment]
There is notifications in fact. But there in no text in that notification #17496
Check you notifications preferences #17689 #17844

**Comment by diegolmello** [comment]
We receive a notification, but it doesn't really enters the call.
Although that's not what we want anyway.
We're going to implement Jitsi as a caller soon.
So the call is going to start the app as if you're receiving a call.
