### ISSUE TITLE
App freezes/crashes when opening a channel

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat.ReactNative#2183]
- Your Rocket.Chat Experimental app version: 4.7.0.2123
- Your Rocket.Chat server version: 3.2.2
- Device (or Simulator) you're running with: Android 10

Since recently, we have the issue that the mobile app freezes/crashes when opening a certain channel. On Android, you're able to open the channel but once you try to reload it the app becomes unresponsive and there is a permanent loading spinner visible on the bottom (the spinner is moving). 

We got also reports from iOS users that the app crashes completely as soon as they're opening the channel.

This freeze/crash happens only on a certain channel, not all. The affected channel is probably the largest one on our server (number of messages), maybe that could be a reason for the app freeze/crash.

As the affected channel is our most active one, this issue is quite critical to us.

Is there a way to debug this? In our server logs, I can't find any suspicious error logs.

**Comment by subesokun** [comment]
@diegolmello I've found now the message that breaks the app. It's also very easy to reproduce. Just insert in a thread message a table and the app will crash. E.g.

```
| Test |
| - |
| Value |
```

**Comment by djorkaeffalexandre** [comment]
Hey @subesokun, what I'm doing different here?
It's not crashing for me.
![Screen Shot 2020-06-15 at 18 13 48](https://user-images.githubusercontent.com/29778115/84706806-011c1800-af34-11ea-8fe5-de8ef06bf599.png)
![Screen Shot 2020-06-15 at 18 13 51](https://user-images.githubusercontent.com/29778115/84706815-037e7200-af34-11ea-84a4-b927ffa57658.png)

**Comment by subesokun** [comment]
@djorkaeffalexandre As far as I can tell you've started a discussion and not a thread. Please try inserting the table in a thread message.

**Comment by djorkaeffalexandre** [comment]
@subesokun it not was a discussion, was a thread, but I recorded it again, so you can see that is not crashing here, can you record a GIF with this exactly example that you provide crashing at your app?
Thanks.

![](https://media.giphy.com/media/YSGDAk0vrLmMPn24lY/giphy.gif)
![](https://media.giphy.com/media/SXrxI6O9MGJCbMChyu/giphy.gif)

**Comment by subesokun** [comment]
Luckily, it seems like the bug has been solved implicitly by the latest app release. In the previous version `4.7.0.2123`, I think the rendering of the threads looked different and only the text `Test Value` was displayed and not `| Test | | - | | Value |`. Maybe the term "crash" was misleading. I've observed only that the app freezed (no UI interactions were possible anymore) when opening a channel with a table inside of a thread. But now with the latest version `4.7.2.2126`, I couldn't reproduce it too. I'll do some more testing and then close the issue if I still can't reproduce it. 

Out of interest, can you try to reproduce the bug wit the version `4.7.0.2123`?

**Comment by subesokun** [comment]
Can't reproduce it too in our environment. Closing this issue. If I have the same problem again, I'll reopen it.
