### ISSUE TITLE
Can not see back/home buttons on the light theme at the bottom.

### ISSUE THREAD

**Issue by AmatorPhasma** [RocketChat/Rocket.Chat.ReactNative#2186]
- Rocket.Chat server version: 3.3.0
- Rocket.Chat App version: 4.7.0.xxxx (Also on Experimental App 4.7.1.17491)
- Device (or Simulator) you're running with: **Huawei Honor 6+ / Android 6**

here two images with dark and light theme:
![001](https://user-images.githubusercontent.com/49910825/84524294-05e58f80-acda-11ea-983f-12e755b8e363.png)

![002](https://user-images.githubusercontent.com/49910825/84524300-0847e980-acda-11ea-8d8a-c5a923e6a7bf.png)

**Comment by diegolmello** [comment]
That's actually related to the navigation bar lib.
Does it happen still or was it fixed after the new releases?
