### ISSUE TITLE
Give any indication when the server is offline

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat.ReactNative#2189]
- Your Rocket.Chat Experimental app version: 4.7.2
- Your Rocket.Chat server version: 3.2.2
- Device (or Simulator) you're running with:Oneplus

Please give any indication in the app when the server is offline. Currently, if the server is down for any reason, there will be no indication on the app. Add some message , toast or icon saying that the "server is currently offline" or "can not connect to the server".

**Comment by diegolmello** [comment]
On the newest versions we started to show the offline status on the header.
