### ISSUE TITLE
The user's avatar is not displayed correctly after login with OAuth

### ISSUE THREAD

**Issue by tiagomartines** [RocketChat/Rocket.Chat.ReactNative#2196]
I am sending the address of the image on the return of the endpoint /me, and the fields are configured correctly in the admin, but the app displays the initial of the user name.

**Comment by djorkaeffalexandre** [comment]
Hey @tiagomartines, can you reach me on `https://open.rocket.chat/direct/djorkaeff.alexandre` to a more direct conversation about how can I configure my server to test/implement this?
Thanks. 🤗
