### ISSUE TITLE
 Invalid URL or unable to establish a secure connection

### ISSUE THREAD

**Issue by NeK000** [RocketChat/Rocket.Chat.ReactNative#2198]
- Your Rocket.Chat Experimental app version: ####
4.7.2.302
- Your Rocket.Chat server version: ####
3.3.3
- Device (or Simulator) you're running with: ####
Iphone 7

Hi there, I am new to Rocket.Chat but have a quick question regarding an issue I am seeing on the IOS app " Invalid URL or unable to establish a secure connection. Contact your sever admin " My current setup is running behind a letsencrypt reverse proxy and I am using cloudflare as name servers in order to resolve a DNS challenge.

I am able to make secure connection from an Android phone Rocket.Chat application.

The issue started appearing on IOS after I changed my domain to use the cloudflare name servers and use the DNS challenge.

**Comment by diegolmello** [comment]
iOS is more strict on SSL than Android.
Can you check your server on https://www.ssllabs.com/ssltest/?

**Comment by NeK000** [comment]
![Screenshot from 2020-06-18 14-00-34](https://user-images.githubusercontent.com/26298182/85017663-25623980-b16c-11ea-9480-0091d0ca36c9.png)

**Comment by NeK000** [comment]
After looking over apple specifications => 

"TLS server certificates and issuing CAs must use a hash algorithm from the SHA-2 family in the signature algorithm. SHA-1 signed certificates are no longer trusted for TLS."

My cert from cloudflare is using SHA-1 with RSA Encrypion version 3 and this is probably the reason failing.

**Comment by NeK000** [comment]
https://support.apple.com/en-us/HT210176

After looking into those requirements I believe the issued certificate from cloudflare shoud be enough for IOS.  Also at the bottom of the article it says that the Safari might also refuse it however I am able to access the Rocket.Chat instance from Safari

**Comment by NeK000** [comment]
I reverted only using letsencrypt with http challenge and I have an A score now. However result is still the same.
![image](https://user-images.githubusercontent.com/26298182/85027692-7aa54780-b17a-11ea-998a-004a5fd2cb96.png)

**Comment by NeK000** [comment]
@diegolmello any other suggestions in order to resolve the ssl issue on the IOS app
