### ISSUE TITLE
Android push Notifications are not working

### ISSUE THREAD

**Issue by fasalsh** [RocketChat/Rocket.Chat.ReactNative#2205]
Hello,

We have recently upgraded our RocketChat instance to the latest v3.3.0 version. Everything works perfectly fine after the upgrade except the Android application push notification. No settings were changed after the upgrade, it was working fine before the upgrade.

Please shed some light on this situation, and advise how we could sort this out.

**Comment by fasalsh** [comment]
Here is the details:

RocketChat version: v3.3.0
RocketChat Android App: 4.7.2.2126


OS Type | Linux
linux   x64
kernel 3.10.0-1062.9.1.el7.x86_64
Node v12.16.1
Mongo 4.0.19

**Comment by diegolmello** [comment]
Are you using our gateway for push notifications?

**Comment by ankar84** [comment]
> Please shed some light on this situation, and advise how we could sort this out.

Turn on **debug** for push notifications in **Admin UI - Push** and after server restart check logs for errors and show then here
![image](https://user-images.githubusercontent.com/4023037/85289068-83aa5780-b49f-11ea-83f7-38d6c06e2c90.png)

**Comment by fasalsh** [comment]
I have this resolved after rebooting chat server, and guessing there might had a kernel update or something which corrected the situation.

Anyway, everything works fine as before. Thanks :)
