### ISSUE TITLE
can't login with iOS app

### ISSUE THREAD

**Issue by jazzman-qp** [RocketChat/Rocket.Chat.ReactNative#2207]
Hi!
app ver. 4.7.2.302
server 3.2.2 (ubuntu snap)
iPhone 7 iOS 13.5.1
self-signed rootCA on local server, works well on any other platform, even in Safari on this very iPhone
it connects actually, allows you to register new user and says if you misspell password but do nothing when credentials are good
in logs https://my_rocket_chat_server/api/v1/login
{"status":"error","message":"API endpoint does not exist"}
seems like my fault but I can't figure it out. help pls-_-

**Comment by naoki0719** [comment]
I have the same problem.

**Comment by djorkaeffalexandre** [comment]
Hey guys! Can you reach me on https://open.rocket.chat/direct/djorkaeff.alexandre providing a test user to reproduce it here?
Thanks in advance.

**Comment by battosai30** [comment]
Hi, same issue, try everything I could wirh no result ... Did you fixed it ?
Regards
