### ISSUE TITLE
How get last version app in single-server branch?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2209]
Hi all
How get last version app in single-server branch?

Thank you advanced

**Comment by ankar84** [comment]
I think you need to build it by yourself using that great [documentation](https://docs.google.com/document/d/17ib2Le_SH6U2gP0sEuKapF2J-WgqZxPFMRRVUSofz7Y/edit)

**Comment by djorkaeffalexandre** [comment]
@magicbelette `single-server`  branch contains the `4.7.0` version as you can check [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/single-server/ios/RocketChatRN/Info.plist#L22), we update the single server branch on each official release of our apps.

**Comment by diegolmello** [comment]
I messed up on the [Android version](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/single-server/android/gradle.properties#L29), but the code is the same as 4.7.0.

**Comment by diegolmello** [comment]
Closed due to inactivity from the author.
