### ISSUE TITLE
Unable receiving push notification in Android platform

### ISSUE THREAD

**Issue by affandymurad** [RocketChat/Rocket.Chat.ReactNative#2210]
- Your Rocket.Chat Experimental app version: 4.6.0.999999999
- Your Rocket.Chat server version: 3.0.9
- Device you're running with: Nokia 6 TA-1021 Android 9

**The app isn't connecting to your server?** No, it's has been connected with our server

I already built customized Rocket Chat RN as our requirement (app package and its display name) and works well. But we face trouble when configured Push Notification (in case Android version). I have created new project in Firebase console to obtain both Server Key (GCM API Key) and Sender ID (GCM Project Number) based on this guide:  https://docs.rocket.chat/guides/administrator-guides/notifications/push-notifications.

![Screen Shot 2020-06-23 at 16 33 20](https://user-images.githubusercontent.com/4674855/85387769-6e9cf980-b56f-11ea-95e6-3d64f965725d.png)

I also added meta-data android:name="com.wix.reactnativenotifications.gcmSenderId" in the Android Manifest manually since the project already integrated with react-native-notifications based on this instruction: https://github.com/RocketChat/react-native-notifications/blob/master/docs/installation.md

![Screen Shot 2020-06-23 at 16 38 00](https://user-images.githubusercontent.com/4674855/85388161-f8e55d80-b56f-11ea-8ad8-759ced387af7.png)

![Screen Shot 2020-06-23 at 16 44 00](https://user-images.githubusercontent.com/4674855/85388879-db64c380-b570-11ea-8c58-42fc4c9bd223.png)

To ensure the app has been connected with Firebase FCM service, we try to send dummy push notification by sending Cloud Messaging in Firebase Console Dashboard under related project and the app has successfully received the notification (I tried release version using gradle command).

![2020-06-23 16 42 11](https://user-images.githubusercontent.com/4674855/85388687-980a5500-b570-11ea-86ad-8df32f81c297.jpg)

But unfortunately, even the server already restarted, the app still didn't get the push notification after sending any messages to other user in idle status (as the notification should work as our expected, notify when getting new messages even the app is located in behind). I also unable to  send push notification to all users from admin panel dashboard.

![Screen Shot 2020-06-23 at 16 49 25](https://user-images.githubusercontent.com/4674855/85389373-870e1380-b571-11ea-9393-0fd19d180535.png)

I also unable to join the open RocketChat forum because never getting any verification message to my own email address to carry on the registration process. It doesn't allow me to enter any input to change the password even I never input my own password. I have no idea regarding this case.

![Screen Shot 2020-06-23 at 16 55 00](https://user-images.githubusercontent.com/4674855/85389982-5e3a4e00-b572-11ea-9587-2b92fdeec44b.png)

So, what should I do to implement the push notification properly using FCM service? Are there missing steps to proceed it? Kindly assist me to solve this issue since I'm beginner in React Native platform. Thank you.

**Comment by affandymurad** [comment]
Dear all, this issue was solved when I type CREATE_TOKENS_FOR_USERS=true in server terminal then restart the service. Thank you for your kindness!

**Comment by xtilyn** [comment]
Did you set 'Enable Gateway' to false under Push config?
