### ISSUE TITLE
lastest single-server branch crash on iPhone simulator

### ISSUE THREAD

**Issue by zhuyuan2016** [RocketChat/Rocket.Chat.ReactNative#2214]
- Your Rocket.Chat Experimental app version: 4.7.0
- Your Rocket.Chat server version: unknow
- Device (or Simulator) you're running with: ios 13.5 iphone 11 simulator

I forked the lastest single-server branch. It works on my Android simulator correctly.But it's dosen't work on my iphone 11 simulator(ios 13.5),It just show a logo on a white background page then crash suddenly when I run 'npx react-native run-ios'.
Does anyone has the same problem?How should I resolve the issue?

**Comment by djorkaeffalexandre** [comment]
Did you make some change to the code?
Can you confirm if the [Metro bundler](https://github.com/facebook/metro) is running correctly?

**Comment by zhuyuan2016** [comment]
> Did you make some change to the code?
> Can you confirm if the [Metro bundler](https://github.com/facebook/metro) is running correctly?
> Check if you added a `GoogleService-Info.plist` to your iOS application and make sure you have added this to `RocketChatRN` target.
> ![Screen Shot 2020-06-24 at 12 01 16](https://user-images.githubusercontent.com/29778115/85580943-8aa5a700-b612-11ea-85da-09eb9e4c1c02.png)

I did't change any code and be sure running the bundle server,I'll be try later according to your third point. Thank you!!

**Comment by djorkaeffalexandre** [comment]
@zhuyuan2016 can you let me know if this worked? So we can close this issue. :)
Thanks in advance.

**Comment by zhuyuan2016** [comment]
> @zhuyuan2016 can you let me know if this worked? So we can close this issue. :)
> Thanks in advance.

It works for me when I add this file named ''googleService-Info'',Thank you!!   ^o^
