### ISSUE TITLE
I change all images ic_launcher. But after build i see old blue icon. Why?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2215]
Hi all!

1. I clone repo
2. checkout single-server
3. in android\app\src\main\res i change all imanges ic_launcher.
4. build release apk
5. install
6. see old blue rocket icons(((
Why? How fix it?

Thank you

**Comment by diegolmello** [comment]
Follow Android's docs: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
