### ISSUE TITLE
Video Playback on iOS

### ISSUE THREAD

**Issue by ferkawi** [RocketChat/Rocket.Chat.ReactNative#2218]
- Your Rocket.Chat Experimental app version: 4.7.0
- Your Rocket.Chat server version: 3.2.2
- Device (or Simulator) you're running with: iPad 13.3.1 / iPhone 6 12.4.3

Hey guys! First thank you for the great App! So we have a Problem with the Videos. When we send a Video to a User, the User can´t play the video in App, stay all the time the Loading gear on the Screen. Really strange because in Android & Webbrowser play it without problems and bei iPhone/iPad can also save it in my Gallery.

Hope you can help me!

Thanks, Nando

**Comment by djorkaeffalexandre** [comment]
Hey @ferkawi, can provide for us the extension and the size of this video?
Maybe it's not supported by our iOS player.
Thanks in advance.

**Comment by ferkawi** [comment]
Thank you for the fast answer! So we tried with MP4, MOV and self recorded MOV with the iPhone & ipad. The size always less than 1MB.

Thank you in advance!

**Comment by djorkaeffalexandre** [comment]
Can you provide one of these videos at some link to test it here?

**Comment by ferkawi** [comment]
So hier you go: https://www.icloud.com/photos/#0V6AoshVzxanjhHpDTQ_z9wRw

The video was taken with my iPad

**Comment by djorkaeffalexandre** [comment]
wow, that's really weird, since it's working fine for me, can you provide me a test user that have the video not working at some room, or you can try to send me this directly at https://open.rocket.chat/direct/djorkaeff.alexandre.
Maybe it's a problem with your upload server, we need to investigate.
![](https://media.giphy.com/media/S3oC9ldydYic4QRHuz/giphy.gif)

**Comment by ferkawi** [comment]
You were right! There was a Problem with the Upload Configuration, really weird..so the File-Upload was in Proxy. Just deactivate it and worked! Thank you!

**Comment by djorkaeffalexandre** [comment]
@ferkawi nice! So I'll close this, thanks. :)
