### ISSUE TITLE
[HELP WANTED] How we can enable emoji option on IOS ?

### ISSUE THREAD

**Issue by shaheem-khanzada** [RocketChat/Rocket.Chat.ReactNative#2219]
![image](https://user-images.githubusercontent.com/37620819/85803134-f5182d80-b75f-11ea-8ee1-0355d97aed8a.png)

**Comment by diegolmello** [comment]
You'll have to change a few places: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/MessageBox/index.js#L195
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/MessageBox/RightButtons.android.js

Reference: https://github.com/wix/react-native-keyboard-input
