### ISSUE TITLE
[iOS] Improve openLink util

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#222]
Add https://github.com/naoufal/react-native-safari-view to support SFSafariViewController and open links as a modal.

**Comment by saketkumar95** [comment]
@diegolmello I implemented this but Is this really required? I mean the previous one was way better than this. What do you think?

**Comment by diegolmello** [comment]
@saketkumar95 I disagree.

RN's Linking always opens links on Safari.
That means users leaving Rocket Chat.

react-native-safari-view opens links on a Safari modal inside Rocket Chat.

 Did you open a PR?

**Comment by saketkumar95** [comment]
@diegodorgam Yup now I have opened the PR. Do review it.
