### ISSUE TITLE
Guideline for commit file?

### ISSUE THREAD

**Issue by haripermadi** [RocketChat/Rocket.Chat.ReactNative#2220]
- Your Rocket.Chat Experimental app version: 4.7.0
- Your Rocket.Chat server version: not sure
- Device (or Simulator) you're running with: ios 13.5

Hi, I forked the latest version for personal use. I want to commit the file to my forked project but got an error. Is there a guideline on how to commit the file. Thank you in advance.
Here is the error screenshot from my terminal:

<img width="645" alt="Screen Shot 2020-06-26 at 17 48 56" src="https://user-images.githubusercontent.com/33610044/85849984-259aae80-b7d6-11ea-9b2b-29976044814c.png">
<img width="640" alt="Screen Shot 2020-06-26 at 17 55 44" src="https://user-images.githubusercontent.com/33610044/85850077-49f68b00-b7d6-11ea-9b84-9f04f4bbef8f.png">

**Comment by diegolmello** [comment]
Those are lint errors.
If you scroll through the stack trace, you'll see some `warning` and `errors`.
Those errors prevent you from commit your code.
It might be a unused variable, a trailing comma, etc.

**Comment by haripermadi** [comment]
Ok, I will check again. I thought I should set something. 
Thank you for the response @diegolmello , really appreciated.
