### ISSUE TITLE
Message / Files Sharing

### ISSUE THREAD

**Issue by ferkawi** [RocketChat/Rocket.Chat.ReactNative#2224]
- Your Rocket.Chat Experimental app version: 4.7.0
- Your Rocket.Chat server version: 3.2.2
- Device (or Simulator) you're running with: iPad 13.3.1 / iPhone 6 12.4.3

Hello guys! I have a Question (maybe it´s a Issue, im not sure). So when I share a message, for example #general -> right click -> permalink and I copy the perma in a message to another account (have also access to #general), open the other account and click it, the App open the link in a browser. Expecting: go directly to the message inside the App.

Maybe there´s another method to share a message / Files but i didn´t find it.

I hope you can help me with that ( share content and when the users click it in the App, open the content in the App and not in a browser, just to be sure the question is clear :D )

Best,
Nando

**Comment by diegolmello** [comment]
Similar to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1315
