### ISSUE TITLE
Can't add firebase analytics

### ISSUE THREAD

**Issue by stacksideflow** [RocketChat/Rocket.Chat.ReactNative#2226]
- Your Rocket.Chat Experimental app version: 4.8.0.999999999
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: Android, Motorola G8, other devices - most likely hardware independent issue

Following official rocket chat guide for adding push notifications (https://docs.rocket.chat/guides/administrator-guides/notifications/push-notifications) I've created a new firebase project and after following instructions in firebase wizard ( adding firebase analytics dep `implementation 'com.google.firebase:firebase-analytics:17.2.2'` to `<project>/<app-module>/build.gradle`, updating `google-services.json` and `google-services.prod.json`) and launching app (tried reinstalling apk on multiple devices) firebase wizard cannot detect analytics connection.
Moreover, I noticed that current firebase deps on `develop` branch are quite outdated
```
    implementation "com.google.firebase:firebase-messaging:18.0.0"
    implementation "com.google.firebase:firebase-core:16.0.9"
    implementation "com.google.firebase:firebase-perf:17.0.2"
```
in comparison to current versions firebase prompts to install in its wizard.

Is there any step that I'm missing here to make firebase analytics work with build on `develop` branch? I'm assembling apk via ` ./gradlew assembleRelease` if that matters.

**Comment by diegolmello** [comment]
Follow our whitelabel docs https://github.com/RocketChat/Rocket.Chat.ReactNative/tree/single-server#running-single-server

**Comment by stacksideflow** [comment]
@diegolmello thanks for this! It'd be helpful to blend this into documentation, as now it's really hard to find IMO

**Comment by diegolmello** [comment]
@stacksideflow It's a wip. It's going to be merged soon.
