### ISSUE TITLE
[BUG] Zoomed in images do not reposition - Android

### ISSUE THREAD

**Issue by AgentTNT** [RocketChat/Rocket.Chat.ReactNative#2227]
- Your Rocket.Chat Experimental app version: 4.8.0.17856
- Your Rocket.Chat server version: 3.3.3
- Device (or Simulator) you're running with: Android 10 / Note10+

After updating to the latest Experimental release, once you enlarge a photo in chat you are no longer able to move the photo to view a different area after it has been zoomed in.

**Comment by ankar84** [comment]
Can you attach a screencast please, I could not reproduce that or I did not understand right your issue.
In my case in 4.8.0.17856 all zoom in and zoom out correctly.

**Comment by AgentTNT** [comment]
Perhaps bad phrasing on my end. Zooming in and out works fine. However when zoomed in and you try to reposition the image once zoomed, the image is stationary. Zoom in on the bottom left and try to move to tyr top right while still zoomed in.

**Comment by ankar84** [comment]
> However when zoomed in and you try to reposition the image once zoomed, the image is stationary. Zoom in on the bottom left and try to move to tyr top right while still zoomed in.

I confirm that - you swipe on image that was zoomed in and nothing happens - image not moving.
As a workaround I can suggest zoom out and zoom in to spot that you need.

**Comment by AgentTNT** [comment]
Funny enough, this functionality still works when you are selecting an image from file or library on android, just not after its been sent.

**Comment by AgentTNT** [comment]
This behavior is not experienced on the iOS version of the experimental version of the app.
