### ISSUE TITLE
Whitelabel app crashes 

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat.ReactNative#2228]
- Your Rocket.Chat Experimental app version: 4.7.0
- Your Rocket.Chat server version: 3.3.3
- Device (or Simulator) you're running with: Iphone SE (2nd gen)

**The app compiles, but crashes when I set workspace to: "Legacy Build System"**
The app compiles and runs and then crashes with the following message:
            fatalError("Failed to open the database. \(fmdb.lastErrorMessage())")

**The app fails to compile if I set workspace to: "New Build System"**

Multiple commands produce '/Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Products/Debug-iphonesimulator/Clarapy.swiftmodule/x86_64.swiftdoc':
1) Target 'RocketChatRN' (project 'RocketChatRN'): Ditto /Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Products/Debug-iphonesimulator/Clarapy.swiftmodule/x86_64.swiftdoc /Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Intermediates.noindex/RocketChatRN.build/Debug-iphonesimulator/RocketChatRN.build/Objects-normal/x86_64/Clarapy.swiftdoc
2) Target 'ShareRocketChatRN' (project 'RocketChatRN'): Ditto /Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Products/Debug-iphonesimulator/Clarapy.swiftmodule/x86_64.swiftdoc /Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Intermediates.noindex/RocketChatRN.build/Debug-iphonesimulator/ShareRocketChatRN.build/Objects-normal/x86_64/Clarapy.swiftdoc

**If I use npx react-native run-ios I get the following error:**

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RocketChatRN.xcworkspace.

**Everything works great on Android.**

**Comment by djorkaeffalexandre** [comment]
@Syirrus probably you forgot to add a AppGroup at your `Info.plist` file.
Follow these [instructions](https://docs.google.com/document/d/17ib2Le_SH6U2gP0sEuKapF2J-WgqZxPFMRRVUSofz7Y/edit).

**Comment by Syirrus** [comment]
> @Syirrus probably you forgot to add a AppGroup at your `Info.plist` file.
> Follow these [instructions](https://docs.google.com/document/d/17ib2Le_SH6U2gP0sEuKapF2J-WgqZxPFMRRVUSofz7Y/edit).

@djorkaeffalexandre I have followed the instructions. :(. Is there something I'm missing?

**Comment by djorkaeffalexandre** [comment]
Check your App Group, if it's not accessible [this line](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L30) will fail.
If you already have an app group configured you maybe forgot to change this line to your own app group.

**Comment by Syirrus** [comment]
> Check your App Group, if it's not accessible [this line](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L30) will fail.
> If you already have an app group configured you maybe forgot to change this line to your own app group.

I will give that a shot and thank you.  Am I able to just replace with the /ios directory with a new one effectively overwriting the old ios directory in my project?  I have made a few changes to the react project and I don't want to have to reapply those changes again if I can help it.

**Comment by Syirrus** [comment]
@djorkaeffalexandre sorry if I pinged you twice.

**Comment by djorkaeffalexandre** [comment]
@Syirrus yes, you can, make sure that you follow all the instructions steps.

**Comment by Syirrus** [comment]
> @Syirrus yes, you can, make sure that you follow all the instructions steps.

@djorkaeffalexandre I've tried and I believe I have followed the whitelabel direction to a "T".  I'm not sure why, but I keep getting the following error when I run npx react-native run-ios:

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RocketChatRN.xcworkspace. Run CLI with --verbose flag for more details.

Any ideas?

**Comment by djorkaeffalexandre** [comment]
@Syirrus which version of Xcode are you using?
Can you try to run the project directly at Xcode instead of use the CLI?

**Comment by Syirrus** [comment]
> @Syirrus which version of Xcode are you using?
> Can you try to run the project directly at Xcode instead of use the CLI?

@djorkaeffalexandre I'm using Xcode Version 11.5 (11E608c)
If I try to run via command line: **npx react-native run-ios** then I get that error. 
If I try to run it via Xcode, I get the following error:

Multiple commands produce '/Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Products/Debug-iphonesimulator/Clarapy.swiftmodule/x86_64.swiftmodule':
1) Target 'RocketChatRN' (project 'RocketChatRN'): Ditto /Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Products/Debug-iphonesimulator/Myapp.swiftmodule/x86_64.swiftmodule /Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Intermediates.noindex/RocketChatRN.build/Debug-iphonesimulator/RocketChatRN.build/Objects-normal/x86_64/Myapp.swiftmodule
2) Target 'ShareRocketChatRN' (project 'RocketChatRN'): Ditto /Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Products/Debug-iphonesimulator/Clarapy.swiftmodule/x86_64.swiftmodule /Users/john/Library/Developer/Xcode/DerivedData/RocketChatRN-blkqoaqdvkjuwhfopsqeamjhifwp/Build/Intermediates.noindex/RocketChatRN.build/Debug-iphonesimulator/ShareRocketChatRN.build/Objects-normal/x86_64/Myapp.swiftmodule

These errors I think are the same.

**Comment by djorkaeffalexandre** [comment]
Try to clean (Command + Shift + K) your build and run it again.

**Comment by Syirrus** [comment]
> Try to clean (Command + Shift + K) your build and run it again.

@djorkaeffalexandre I tried that and I have the same issue :(
If I go to "file" -> "workspace settings" -> "legacy build system" then it will compile and runs, but crashes with unrecognized font family 'custom'

hmmmmm

**Comment by Syirrus** [comment]
@djorkaeffalexandre Thank you for helping me with this. It seems like the app works, but I keep getting the following error:

https://drive.google.com/file/d/1cW6j_7UfRHui14HKFO3U6KFu6QUxm_Gw/view?usp=sharing

Bypassing this error I get:
https://drive.google.com/file/d/1kYMqBYRs1wtXk8gwdbrlH4Yr6smxqE2C/view?usp=sharing
 
Note the missing icon

**Comment by djorkaeffalexandre** [comment]
Make sure that you have the `custom.ttf` resource and it's checked to RocketChatRN target.
![Screen Shot 2020-06-30 at 16 19 15](https://user-images.githubusercontent.com/29778115/86167826-9bac5780-baed-11ea-8ab4-37f46dc2bd97.png)

**Comment by Syirrus** [comment]
@djorkaeffalexandre 
Dude, thank you so much. It appears to be working now! I so really appreciate you taking the time to help me. There are so many "gotchas" when compiling this for iOS and Android. I still need to get push notifications to work, but that shouldn't be so bad like it used to be.  

Once again, thank you thank you, thank you!

:)

**Comment by djorkaeffalexandre** [comment]
@Syirrus you're welcome :)
