### ISSUE TITLE
rocketchat app ios or android does not appear livechat channels

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat.ReactNative#2233]
I am using the latest version of the app I have already tested the Iphone and Android, the internal channels work perfectly but the channels created in livechat do not appear

**Comment by diegolmello** [comment]
We do have support for livechat and I just tested it.
Are you sure the user is a livechat agent?

**Comment by josep112** [comment]
Yes, I'm sure, among the agents I can send and receive messages but not on livechat

**Comment by diegolmello** [comment]
I'll have more info than that in order to reproduce the issue.
Can you record videos or send me a test user?

**Comment by josep112** [comment]
Yes I can create a user for you, can I send it in your email?

**Comment by diegolmello** [comment]
Sure.
