### ISSUE TITLE
Error 400: Push Notifications Not Working for iOS

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat.ReactNative#2235]
- Your Rocket.Chat Experimental app version: Development branch (latest)
- Your Rocket.Chat server version: 3.4.0
- Device (or Simulator) you're running with: Ipad Pro (for push notification test)

**Got error code 400 for token 23022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959d**

I have followed the Whitelabeling guide to the best of my ability. Android push notifications work flawlessly. iOS notification simply are not working for me. In the RocketChatRN project in xcode, push notification are enabled. I have a created all the certificates that I need to as well twice. I 'cat' the contents of each file entirely into the appropriate fields and nothing. 

Check out the log file below:

Meteor _ method push_test -> userId: somehGwwHnDADeoj6, arguments: []
Push _ debug Sending notification {
  createdAt: 2020-07-02T09:17:43.241Z,
  createdBy: '<SERVER>',
  sent: false,
  sending: 0,
  from: 'push',
  title: '@John',
  text: 'This is a push test message',
  userId: 'somehGwwHnDADeoj6',
  sound: 'default',
  apn: { text: '@John:\nThis is a push test message' }
}
Push _ debug send message "@John" to userId somehGwwHnDADeoj6
Push _ debug send to token {
  apn: '23022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959d'
}
Push _ debug send to token {
  apn: '23022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959d'
}
Push _ debug Sent message "@John" to 1 ios apps 0 android apps
Push _ debug GUIDE: The "appTokensCollection" - No GCM clients have registered on the server yet...
Push _ debug Got error code 400 for token 23022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959d
Push _ debug Removing token 23022cbeeeaf458e71419ba7d7cf8e83ce34ac3360e9b583cd787a6dec72959d
SyncedCron _ info Starting "Generate download files for user data".
SyncedCron _ info Finished "Generate download files for user data".

I've also tested each certificate (dev and production) via: https://github.com/raix/push/blob/master/docs/IOS.md

Any ideas?

**Comment by diegolmello** [comment]
Refer to these docs: https://docs.google.com/document/d/17ib2Le_SH6U2gP0sEuKapF2J-WgqZxPFMRRVUSofz7Y/edit

**Comment by northway** [comment]
I'm having the same issue with a similar deployment.

* Version of Rocket.Chat Server: 3.17.0
* Operating System: Ubuntu Linux
* Deployment Method: Docker
* Number of Running Instances: 2
* DB Replicaset Oplog: y
* NodeJS Version: v12.22.1
* Apps Engine Version: 1.27.1
* MongoDB Version: 4.0.26 / wiredTiger (oplog Enabled)

```
server.js:204 Push ➔ debug Sent message "@USERNAME" to 1 ios apps 0 android apps
server.js:204 Push ➔ debug Got error code 400 for token 0105d6917cb2b7b4ded1190244b79fbbc59d3cf4e696b33520a735798e382eb0
server.js:204 Push ➔ debug Removing token 0105d6917cb2b7b4ded1190244b79fbbc59d3cf4e696b33520a735798e382eb0
```

**Comment by urmamb** [comment]
strange that rocket chat didn't explained it why this 400 error happens it now 2023.

**Comment by urmamb** [comment]
> I'm having the same issue with a similar deployment.
> 
> * Version of Rocket.Chat Server: 3.17.0
> * Operating System: Ubuntu Linux
> * Deployment Method: Docker
> * Number of Running Instances: 2
> * DB Replicaset Oplog: y
> * NodeJS Version: v12.22.1
> * Apps Engine Version: 1.27.1
> * MongoDB Version: 4.0.26 / wiredTiger (oplog Enabled)
> 
> ```
> server.js:204 Push ➔ debug Sent message "@USERNAME" to 1 ios apps 0 android apps
> server.js:204 Push ➔ debug Got error code 400 for token 0105d6917cb2b7b4ded1190244b79fbbc59d3cf4e696b33520a735798e382eb0
> server.js:204 Push ➔ debug Removing token 0105d6917cb2b7b4ded1190244b79fbbc59d3cf4e696b33520a735798e382eb0
> ```

have you found solution to it?

**Comment by RKDEVSYS** [comment]
> I'm having the same issue with a similar deployment.
> 
> * Version of Rocket.Chat Server: 3.17.0
> * Operating System: Ubuntu Linux
> * Deployment Method: Docker
> * Number of Running Instances: 2
> * DB Replicaset Oplog: y
> * NodeJS Version: v12.22.1
> * Apps Engine Version: 1.27.1
> * MongoDB Version: 4.0.26 / wiredTiger (oplog Enabled)
> 
> ```
> server.js:204 Push ➔ debug Sent message "@USERNAME" to 1 ios apps 0 android apps
> server.js:204 Push ➔ debug Got error code 400 for token 0105d6917cb2b7b4ded1190244b79fbbc59d3cf4e696b33520a735798e382eb0
> server.js:204 Push ➔ debug Removing token 0105d6917cb2b7b4ded1190244b79fbbc59d3cf4e696b33520a735798e382eb0
> ```

I have the same problem. Did you manage to get any solution?

**Comment by BjornSodenberg** [comment]
I have the same problem. Did you manage to get any solution?

**Comment by acsdeveloper** [comment]
Any update?

**Comment by Rohit3523** [comment]
Can you provide me your server url and account so I can try to debug the issue and create a fix for it.

I don't want to host a server because it's time consuming and never hosted before

**Comment by Rohit3523** [comment]
Please do not share your server url here, if you are ready to provide me the details, let me know so I am going to share my email here so you can mail me.
