### ISSUE TITLE
Urgent help needed for push notification

### ISSUE THREAD

**Issue by dollah-singh** [RocketChat/Rocket.Chat.ReactNative#2239]
Hi Everyone,
I really appreciate your contribution to Rocket.Chat react native app.
I have a problem while working on this app customization.
I cloned Rocket.Chat react native app and I changed the app name and app id (package name) accordingly. 
Also I included my latest google_services.json to the Android Project.
The problem is that Push notification is not working at all for Android for this build and I am not sure what's wrong with it.
Would you please give me some advice? I have checked the Rocket Chat server and Firebase GCM Settings and they all look fine.
Do I need to make additional configuration to the app project?
Please help me.
Thanks.

**Comment by diegolmello** [comment]
Refer to these docs: https://docs.google.com/document/d/17ib2Le_SH6U2gP0sEuKapF2J-WgqZxPFMRRVUSofz7Y/edit
