### ISSUE TITLE
[BUG] Sort by activity does not sort by recent posts, instead sorts seemingly arbitrarily

### ISSUE THREAD

**Issue by sephwalker56** [RocketChat/Rocket.Chat.ReactNative#2243]
- Your Rocket.Chat Experimental app version: 4.8.0.2127 (and current non-beta release version, and current beta release version)
- Your Rocket.Chat server version: 3.4.1
- Device (or Simulator) you're running with: Pixel 3a XL on Android 11 beta and another on Android 10 & iPhone 8, iOS 13.5.1

### Description:

This bug occurs on Android 11 beta, Android 10, and iOS 13.5.1, across many devices and all available versions (including beta) of RocketChat in the app stores.

When sorting by "Activity," regardless of grouping options or unread on top being ticked or not, the list does not sort by recent activity and instead appears to be arbitrarily sorting the channels.

Sorting by activity, reported to me by one of my users (as in, I've not personally verified as I'm not at a computer), to work just fine on the PC desktop app and web version.

### Current Behaviour

Sorting by "activity" shows channels in a seemingly random order.

![Screenshot_20200703-233346](https://user-images.githubusercontent.com/50584992/86506626-feb81b80-bd85-11ea-91cc-1a665707b4c7.png)

### Expected Behaviour

Channels should be listed in order of last message. For example, in that screenshot, those last four should have sorted to: Thread examples, Video Games, Announcements, Help. The channel with the most recent reply should be at the top.

### Additional Info

I suspect this has something to do with threads, although I've no evidence for this. Either that, or the admin panel option that allowed non-alphanumeric characters in channel names. This was only recently brought to my attention from one of my users, so unfortunately I've no way of knowing how long this has been behaving this way or if it correlates with the non-alphanumeric characters, which have been in use practically since day 1 of using RocketChat. 

Let me know if you need any further details! Thanks. ☺️

**Comment by diegolmello** [comment]
I think it's really related to new threads.
It's planned to release support for it on 4.9.0.
Thanks.

**Comment by diegolmello** [comment]
Let's track the work on #2387
