### ISSUE TITLE
Creating discussion not working with long-press menu anymore

### ISSUE THREAD

**Issue by Kimpfimp** [RocketChat/Rocket.Chat.ReactNative#2244]
Your Rocket.Chat Experimental app version: 4.8.0.17969

Your Rocket.Chat server version: 3.2.2

Device (or Simulator) you're running with:
Moto G7 Plus with Android 10 (Lineage OS 17.1)

### Description: 
Clicking on "Create discussion" from the menu when long pressing on a message does not generate discussion. It seems to not do anything at all.

This only happens in the long press menu, creating a discussion from the + menu works as intended.

### Current Behaviour
Nothing happens when on clicking on "create discussion" when starting it directly from message.

 
### Expected Behaviour
Create discussion menu to pop up and linking to message.

 
### Additional Info

**Comment by diegolmello** [comment]
Thanks for reporting.
I was able to reproduce it.
In the meantime we work on a fix, you can create discussions from the `Create` button from the rooms list and then `Create Discussion` or tapping the `plus` icon on the channel and then `Create Discussion`.
