### ISSUE TITLE
Error "Call Already Ended" when i click button "Click to join"

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2245]
Hi all!

I get error "Call Already Ended" when i click button "Click to join".
I try this on 5 Android devices.
1. Samsung S7 - Error "Call Already Ended", But when i go to "User menu > VideoCall" i success connect to Video Call Jitsi
2. Samsung Note 9 - Error "Call Already Ended"
3. Xiaomi Mi 8 - OK
4. Xiaomi Mi A2 - OK
5. Samsung S8 - OK

Problem with button "Click to join"?
How fix it?
Thank you advanced

RocketChat App - Last version branch single-server.
RocketChat Server Version 3.4.1

**Comment by aleadco** [comment]
Hi, I can confirm this, the same thing happens in our instance. I don't think it's the app, I think it's related to the communication between jitsi server and rocketserver. In our case, the error came from the web, desktop app, mobile app. Regards

**Comment by ankar84** [comment]
Here is a main issue https://github.com/RocketChat/Rocket.Chat/issues/11649

**Comment by diegolmello** [comment]
Ok, closing.
Thanks for investigating.

**Comment by aleadco** [comment]
I currently keep this error in 3.4.2

An alternative solution that I have found is to press the same call button and not the one that appears in the chat window.
