### ISSUE TITLE
App does not prompt user to enter password for password protected channels

### ISSUE THREAD

**Issue by joernal** [RocketChat/Rocket.Chat.ReactNative#2258]
- Your Rocket.Chat Experimental app version: 4.6.4
- Your Rocket.Chat server version: 3.1.1
- Device (or Simulator) you're running with: iPhone 11 (iOS 13.5 - Simulator)

App does not prompt user for password when joining password-protected channels. User is unable to join the room with the following response (/api/v1/channels.join):

`{
	"success": false,
	"error": "Invalid Room Password [error-code-invalid]",
	"errorType": "error-code-invalid",
	"details": {
		"method": "joinRoom"
	}
}`

![Simulator Screen Shot - iPhone 11 - 2020-07-08 at 13 22 23](https://user-images.githubusercontent.com/5616030/86950393-201a5e00-c11e-11ea-97bc-7115fc9febd4.png)

**Comment by diegolmello** [comment]
@joernal Yeah, it's not implemented yet.
Let me know if you want to contribute.
Thanks for reporting.

**Comment by imrishabh18** [comment]
Hi @diegolmello , I am quite new to react-native. Can you guide me to resolve this issue? 😀

**Comment by djorkaeffalexandre** [comment]
Hey @imrishabh18,
  You should implement something like a text input to enter the join code of protected rooms, and send this code on the join method like the documentation explains https://docs.rocket.chat/api/rest-api/methods/channels/join.
  Remember that should appear only if the room needs a join code.
Thanks.

**Comment by djorkaeffalexandre** [comment]
This is how it looks like on our web client:
![Screen Shot 2020-09-16 at 9 19 33 AM](https://user-images.githubusercontent.com/29778115/93336179-cc06b680-f7fd-11ea-936f-e160f5856092.png)

**Comment by joernal** [comment]
Hi @djorkaeffalexandre, 

I implemented something similar to the web experience.
If it's something similar to what you're looking for, I'd be happy to open a PR for it (and possibly coordinate with @imrishabh18). 

![Simulator Screen Shot - iPhone 11 - 2020-09-16 at 15 06 39](https://user-images.githubusercontent.com/5616030/93381681-06d51280-f82f-11ea-9797-eb56fc26c001.png)

**Comment by djorkaeffalexandre** [comment]
Hi @joernal, it looks good!
Feel free to open a PR, it would be awesome.
