### ISSUE TITLE
CircleCI builds should be optimised on Mac runners

### ISSUE THREAD

**Issue by Fishbowler** [RocketChat/Rocket.Chat.ReactNative#2267]
CircleCI has a maximum of 1 macOS runner, so it's important that we optimise running time.

Expensive operations:

- iOS builds
- iOS test runs
- Brew update

We could use something like [folder-hash](https://www.npmjs.com/package/folder-hash) and [storing artifacts](https://circleci.com/docs/2.0/artifacts/) to see if anything important has changed and, if not, save rebuilding by using a previously built iOS app. We might be able to optimise further on branch name or something?

Similarly, could brew caches be preserved between pipeline runs? Rather than going zero -> latest every time, maybe this could be quicker if we're updating from something more recent? It's an external dependency, so branch doesn't matter.

**Comment by diegolmello** [comment]
We save brew cache [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/.circleci/config.yml#L80), but I'm happy to hear more about all of these optimisations (:

**Comment by Fishbowler** [comment]
Better than a folder-hash would be to use the existing git hash for a folder along with the hash for the dependencies. If the source hasn't changed and the node_modules haven't changed, no need to rebuild?

https://stackoverflow.com/a/47721593/399007
