### ISSUE TITLE
(BUG) Sending Image/File with description is hidden on iOS upon sent

### ISSUE THREAD

**Issue by hengsok** [RocketChat/Rocket.Chat.ReactNative#2276]
- Your Rocket.Chat Experimental app version: ####
4.8.0
- Your Rocket.Chat server version: ####
3.4.1
- Device (or Simulator) you're running with: ####
iPhone 11 Pro Max device

As you can see in the picture below, we downloaded the official RocketChat from iOS store with the latest version 4.8.0 and when we upload a new photo with description, the description became hidden below the MessageBox.

We have spent a lot of time trying to debug this and realised that the KeyboardAccessoryView in
app/containers/MessageBox/index.js has a param "requiresSameParentToManageScrollView" and this seems to cause
issue as it modifies the same flatlist that displays the messages in RoomView. Not sure whether resetTracking() is for what purpose but that did not helps in setting the correct content offset for the flatlist that contains the messages.

We also noticed that as long as after we uploaded an image/file and tap on the MessageBox input and even we close the ShareView without uploading any files, the flatlist displaying the messages will have the bottom hidden under the MessageBox.

This bug is introduced after the [NEW] Send multiple attachments (#2162) commit which changes to use MessageBox component.

![IMG_2089](https://user-images.githubusercontent.com/3071383/87132242-c8b3f380-c2bf-11ea-8b95-cc211a52ce07.jpg)

**Comment by diegolmello** [comment]
Here's a pic I've sent just now.
![image](https://user-images.githubusercontent.com/804994/87154595-e49fa100-c28f-11ea-949e-5c8cf7d24d29.png)

This issue is not related to the feature and may happen once in a while.
We have never been able to reproduce it regularly, so we've never been able to fix it.
Can you open an issue if you manage to fix it?
Thanks.

**Comment by hengsok** [comment]
Hi @diegolmello 

Thank you so much for replying.

Upon further investigation after hours and hours of debugging, I found out that if I set in the file KeyboardTrackingViewManager, there is this method below and it seems that in some instances, we fall into the second case below. And that is the reason why we have the content hidden behind the MessageBox differently across different devices. Your devices may not exhibit this issue but I am sure many others will depending on the keyboardState.
If I set _bottomViewHeight = kBottomViewHeight; for the second case below too, everything is working fine. But will this cause other issues? What do you think?


****
 else if (_observingInputAccessoryView.keyboardState != KeyboardStateWillHide) {
        _bottomViewHeight = 0;
    }
****

as in this method here

#pragma mark - ObservingInputAccessoryViewDelegate methods

-(void)updateTransformAndInsets
{
    CGFloat bottomSafeArea = [self getBottomSafeArea];
    CGFloat accessoryTranslation = MIN(-bottomSafeArea, -_observingInputAccessoryView.keyboardHeight);
    
    if (_observingInputAccessoryView.keyboardHeight <= bottomSafeArea) {
        _bottomViewHeight = kBottomViewHeight;
    } else if (_observingInputAccessoryView.keyboardState != KeyboardStateWillHide) {
        _bottomViewHeight = 0;
    }
    [self updateBottomViewFrame];
    
    self.transform = CGAffineTransformMakeTranslation(0, accessoryTranslation);
    [self _updateScrollViewInsets];
}

**Comment by hengsok** [comment]
Ok above is definitely a good clue to solving this problem and I found the solution with minimal changes!! 

The thing is, since
_observingInputAccessoryView.keyboardHeight <= bottomSafeArea
We need to make sure the keyboard height is less than the bottom area which is the MessageBox in our case. 
If we set height of the View encompassing the bottom area to something larger than the keyboard height (56+ as I found out) to something like 60, this problem will be solved. But that leaves a white ugly gap.

Then when I just comment out the borderTopWidth line in style.js of MessageBox, the problem went away. I believe the borderTopWidth made the value of the height of bottom area smaller somehow. It is strange.

Comment out the line in file
`borderTopWidth: StyleSheet.hairlineWidth,`
in
app/containers/MessageBox/styles.js

as shown below

```
composer: {
		flexDirection: 'column',
		//borderTopWidth: StyleSheet.hairlineWidth,
	},
```

**Comment by hengsok** [comment]
Ok above is definitely a good clue to solving this problem and I found the solution with minimal changes!! And you wouldn't believe it is that simple to fix which has caused me days to debug this!

The thing is, since
_observingInputAccessoryView.keyboardHeight <= bottomSafeArea
We need to make sure the keyboard height is less than the bottom area which is the MessageBox in our case. 

The value of StyleSheet.hairlineWidth appears to be different on different devices and hence, this caused the issue randomly. (I also don't understand why)


Change the line
`borderTopWidth: StyleSheet.hairlineWidth,`
in 
app/containers/MessageBox/styles.js

to set a fix a fixed number rather than using hairlineWidth.

as shown below

```
composer: {
		flexDirection: 'column',
		borderTopWidth:1, //can be any other larger number and the problem is still fixed
	},
```

**Comment by diegolmello** [comment]
What?
No way! 😄
Can you open a PR setting it to 1?
Thanks! 👏👏👏

**Comment by hengsok** [comment]
Sure!  Thanks for contributing so much to this project too! You did a great job for this open source project! @diegolmello
