### ISSUE TITLE
MarkDown rendering for code view different on mobile app

### ISSUE THREAD

**Issue by pokapow** [RocketChat/Rocket.Chat.ReactNative#2279]
On mobile, markdown rendering of "```" tags is different than on web.

For this message:
![Capture du 2020-07-11 12-41-13](https://user-images.githubusercontent.com/30467320/87222553-af20b380-c374-11ea-9efb-d0d79f991da9.png)

Rendering on the web:
![Capture du 2020-07-11 12-41-44](https://user-images.githubusercontent.com/30467320/87222559-ce1f4580-c374-11ea-8807-576bc10caf4a.png)

Rendering on mobile app:
![Capture du 2020-07-11 12-41-57](https://user-images.githubusercontent.com/30467320/87222565-e42d0600-c374-11ea-9f54-a0c5e357ee98.png)

**Comment by AgentTNT** [comment]
This is a duplicate issue - https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1778
