### ISSUE TITLE
No avatar in Jitsi call in mobile application when Block Unauthenticated Access to Avatars is enabled

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2286]
- Your Rocket.Chat Experimental app version: 4.8.1.18375 - 4.16.2
- Your Rocket.Chat server version: 3.7.1 - 3.14.0
- Device (or Simulator) you're running with: Xiaomi Redmi Note 5

According to https://github.com/RocketChat/Rocket.Chat/issues/18117 we need to enable **Block Unauthenticated Access to Avatars** in **Admin UI - Accounts**
Desktop application and web version after that work fine - user appears in Jitsi call with their avatars.
But mobile version shows only user initials instead of avatar.
Mobile version
![image](https://user-images.githubusercontent.com/4023037/87401767-42e7bf00-c5c3-11ea-9e34-5846c370efb9.png)
Desktop version
![image](https://user-images.githubusercontent.com/4023037/87401822-54c96200-c5c3-11ea-9a04-48135ae6bb24.png)

**Comment by ankar84** [comment]
@diegolmello @djorkaeffalexandre can you take a look at that issue?

**Comment by ankar84** [comment]
I think it could be resolved in 4.12
Did a couple test and it looks like there is avatars in 4.12 with **Block Unauthenticated Access to Avatar**s enabled.
But I also checked it 4.7 - and same - there is avatars. So maybe server version 3.7.1 matters in that case.

**Comment by diegolmello** [comment]
@ankar84 is this still an issue?

**Comment by ankar84** [comment]
> @ankar84 is this still an issue?

Hi, @diegolmello 
I need your help in reproducing steps for that issue.
Last week I did try to reproduce that on 4.12 and got strange results. 
One user saw my avatar, but other is not.
I think it could be some cache. Users, that I talked previously have my avatar in application cache maybe.
So, I need a proper way to check if that issue is resolved in 4.12.1, can you help me with that?

**Comment by diegolmello** [comment]
I see.
4.12 had Jitsi issues (not only voice related, but image related) and we solved them on 4.12.1.
Can you make sure everyone is up-to-date and try again?
Thank you.

**Comment by ankar84** [comment]
> Can you make sure everyone is up-to-date and try again?

Just tested 4.12.1 with **Block Unauthenticated Access to Avatars** enabled and saw users avatars.
So, I think that issue is resolved!
Thank you!

**Comment by ankar84** [comment]
> Just tested 4.12.1 with **Block Unauthenticated Access to Avatars** enabled and saw users avatars.

Hey, @diegolmello 
I believe I was wrong in that.
I just enabled **Block Unauthenticated Access to Avatars** on our server and **reinstall RCRN app** - **no avatars as a result**! So, my previous successful experience definitely was **cache related**.
I did try 4.13.1 and 4.16.2 - both has no avatars after application reinstall. **In-app clear cache is not enough**.
Web version is still works perfect with that option!
So, I guess that issue can be solved if Jitsi activity would have authenticated state in Rocket Chat (cookie or something like this).

**Comment by ankar84** [comment]
I'm try to dig in that bug a little and it's very strange.
I see that mobile client makes proper request to avatar like this: `https://rc.compamy.com/avatar/ankar84/?format=png&size=100&rc_token=some_token&rc_uid=some_uid&etag=some_etag`
I thinks that it is asking RCRN client because of this User-Agent `RC Mobile; android 9; v4.13.1 (10)`
But still no avatars in Jitsi call in RCRN, but all perfect in Web version and Electron version.

Sometimes I see this User-Agent `okhttp/3.12.12` and request like `https://rc.compamy.com/avatar/ankar84/`
Sometimes I see this User-Agent `okhttp/3.12.12` and request like `https://rc.compamy.com/avatar/username?format=png&width=100&height=100&rc_token=token&rc_uid=uid`
But every time no avatars in Jitsi call with  **Block Unauthenticated Access to Avatars** enabled.

I did try to open `https://rc.compamy.com/avatar/username?format=png&width=100&height=100&rc_token=token&rc_uid=uid` in Chrome (in Incognito mode) and avatar was opened without any problems!

**Comment by ankar84** [comment]
Still an issue at 4.19.0
![44ce290a8599ec48c75903534601f088dada5e1891cd5ac118d715fecffbcbf8](https://user-images.githubusercontent.com/4023037/132082645-feea3c18-ffdc-4d71-98c2-8cd7ad803058.jpeg)
![e3d38be38d39f4928ae2439e1c4cc16d85e3eb39e5f5b16944f4123de29d6718](https://user-images.githubusercontent.com/4023037/132082646-e1ceaf44-62f0-45e0-a078-5a782b087568.jpeg)

**Comment by ankar84** [comment]
Version 4.24 issue is still here

**Comment by shiryov** [comment]
Still issue on 4.43 with RC version 6.5.0
But in the desktop Chrome in the calling tab, the avatar is loaded.

**Comment by pierre-lehnen-rc** [comment]
https://github.com/RocketChat/Apps.Jitsi/blob/master/src/videoConfProvider.ts#L134
