### ISSUE TITLE
files attachment duplicate when pagination

### ISSUE THREAD

**Issue by kieran-william** [RocketChat/Rocket.Chat.ReactNative#2287]
- Your Rocket.Chat Experimental app version: 4.8.0

![image](https://user-images.githubusercontent.com/40080911/87452360-5464b180-c62b-11ea-864f-c34a5b42017f.png)
It looks like the data is being duplicated when scrolling to the bottom of the page.
I have just accessed rocketchat code so I can't fix it yet.
Can someone help stop this fix so I can learn.
thanks

**Comment by refactor-droidyy** [comment]
@kieran-william  @diegolmello  can I work on this ?

**Comment by diegolmello** [comment]
@refactor-droidyy go for it :)

**Comment by xuanduyrn** [comment]
@refactor-droidyy If there is PR please let me know :heart:
