### ISSUE TITLE
Read Receipts don't open in new Action Sheet on tablet

### ISSUE THREAD

**Issue by phriedrich** [RocketChat/Rocket.Chat.ReactNative#2295]
- Your Rocket.Chat Experimental app version: 4.9.0.308
- Your Rocket.Chat server version: 3.4.2
- Device (or Simulator) you're running with: iPad iOS 13.6

When trying to open the read receipts on iPad, they don't open, the action sheet just closes.

The same app version on iPhone works.

![IScreenshot of action sheet](https://user-images.githubusercontent.com/470153/87673208-774ead00-c774-11ea-870a-5792a1980e87.jpeg)

**Comment by diegolmello** [comment]
It looks like an issue.
We're just trying to navigate [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/MessageActions/index.js#L204), but tablet uses a master detail layout and it should be done like [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/MessageActions/index.js#L121)

**Comment by phriedrich** [comment]
@diegolmello Excellent hint! I got it working on the simulator and created a PR.

**Comment by phriedrich** [comment]
No it works for both.
