### ISSUE TITLE
"Message" button does not initiate DM from User Info 

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat.ReactNative#2298]
- Your Rocket.Chat Experimental app version: 4.8.1
- Your Rocket.Chat server version: 2.4.9
- Device (or Simulator) you're running with: iOS 13.3, iPhone 8

When you click a user to bring up their profile (User Info) and click on the "Message" button, the expectation is a direct conversation starts, but currently nothing happens when you click it. 

I see the render() is being called twice. componentDidMount() is modifying the state which is probably causing this (?). during the first render() call, the room is populated as expected, but the second time there is no rid or other information besides "t" set in the room. I expect that's what's causing the button to be non-operational.

**Comment by cprice-kgi** [comment]
I believe I have fixed this, but would appreciate confirmation from the RC team. It seems to work as expected with the following change to /app/views/RoomInfoView/index.js:

In the loadUser method, I changed line 188 from:
`this.setState({ roomUser: user, room: { ...roomState, rid: room.rid } });`

to:
`this.setState({ roomUser: user, room: { ...roomState, rid: this.rid } });`

**Comment by diegolmello** [comment]
@cprice-kgi If you fixed it, open a PR and we can review it.
