### ISSUE TITLE
Admin Panel - inconsistent behavior

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat.ReactNative#2299]
- Your Rocket.Chat Experimental app version: 4.8.1
- Your Rocket.Chat server version: 2.4.9
- Device (or Simulator) you're running with: iOS 13.3, iPhone 8

Clicking "Admin Panel" asks to re-authenticate (we are using an external user store/IdP). Once re-authenticated, a page appears reading "Login completed. Click here to close this window.", but clicking on the link does not close out the page. Clicking back to other areas of the app and then returning to "Admin Panel" still shows the page with the "Login completed" message, with no way to really get rid of it (or access the Admin Panel for real).

**Comment by diegolmello** [comment]
I'm unable to reproduce here.
Send me a test user at https://open.rocket.chat. I'm `@diego.mello`.
