### ISSUE TITLE
Username shown in files section instead of Realname

### ISSUE THREAD

**Issue by refactor-droidyy** [RocketChat/Rocket.Chat.ReactNative#2313]
- Your Rocket.Chat Experimental app version: 4.9.0
- Your Rocket.Chat server version: 3.5.0
- Device (or Simulator) you're running with: POCO X2

When the user navigates to the view Room message it can be seen that the real name is shown for that particular message send by other users which is correct

<img src="https://user-images.githubusercontent.com/44283521/87856076-0e189680-c93a-11ea-8359-91111265b6a4.jpg" width="300" height="600">

but as you navigate to files sections of that room you can see that the username is shown instead of the real name for that particular attachment.

<img src="https://user-images.githubusercontent.com/44283521/87856083-1f61a300-c93a-11ea-88e7-0b8b03e27f87.jpg" width="300" height="600">

**Comment by refactor-droidyy** [comment]
@diegolmello @djorkaeffalexandre if this issue is valid can I work on this?

**Comment by diegolmello** [comment]
@refactor-droidyy sure
