### ISSUE TITLE
Cannot login with custom OAuth on iOS

### ISSUE THREAD

**Issue by nexus166** [RocketChat/Rocket.Chat.ReactNative#2315]
- Your Rocket.Chat Experimental app version: app store's latest
- Your Rocket.Chat server version: 3.4.2
- Device (or Simulator) you're running with: iphone XR

Login button opens up Safari browser to continue login, but once finished nothing happens.

Expected behavior: at completed login should return to RocketChat app to finish process

**Comment by diegolmello** [comment]
Is it working on your web client?
It's most likely a configuration issue.
I can't help you without specific information.

**Comment by nexus166** [comment]
my RocketChat instance has ~15 users using both web clients and mobile, the only iOS user is experiencing the reported issue

**Comment by diegolmello** [comment]
Ok, but that's not enough info.
Can you send me a test user at https://open.rocket.chat?
I'm `@diego.mello`.
Thanks.

**Comment by nexus166** [comment]
issue disappeared with 3.6.0!
