### ISSUE TITLE
Screen freeze caused by RocketChat/commonmark.js

### ISSUE THREAD

**Issue by mk0116** [RocketChat/Rocket.Chat.ReactNative#2316]
Since RocketChat/commonmark.js has been updated, the roomview freezes and nothing is clickable but only scroll action works.

I checked that the code set a week ago works perfectly fine.
(I've had the previous version of rocket chat react native so I was able to find that old package in node_modules)

There were 24 messages.
All the messages in the list do not have any link or some special characters but emojis.

When I scroll a little bit up then all the buttons stop working.(scrolling works)
Hardware back button and the back button in top navigation bar don't work too.

The devices get really hot so I assumed that some kind of thread is running hardly so the UI thread couldn't get any resource(not sure why scrolling worked tho).

**Comment by djorkaeffalexandre** [comment]
Hey! Can you provide more info like which message is causing this freeze, or send a test user for us enter this channel?
https://open.rocket.chat/direct/djorkaeff.alexandre
Thanks in advance.

**Comment by refactor-droidyy** [comment]
@djorkaeffalexandre ui freezing only happens in sandbox room and for other rooms it work fine.

**Comment by diegolmello** [comment]
It looks like two different issues.
@refactor-droidyy Can you create a new one for the sandbox channel?
You can link this one as similar though.

**Comment by diegolmello** [comment]
@refactor-droidyy @mk0116 You guys were right about commonmark update.
Let's revert it and try updating again later.
Thanks for investigating.
