### ISSUE TITLE
Push Message Encryption

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat.ReactNative#2322]
- Your Rocket.Chat Experimental app version: All Versions
- Your Rocket.Chat server version: 3.4
- Device (or Simulator) you're running with: Any

Hi,

since RC will be enforcing the registration for the ability to use the push gateway, we were generally wondering if the push notifications are actually encrypted, besides TLS. Our users depend on the message content being sent as a payload. Turning that off for privacy reasons is not really an option.
So, if there is no further encryption implemented, we would like to add this as a feature request.

Thank you in advance and have a nice day.

**Comment by diegolmello** [comment]
Hi!
We're going to implement push notification encryption soon, but we're already finishing a similar feature we called [Push Notification Privacy](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2213)
The [server PR](https://github.com/RocketChat/Rocket.Chat/pull/18254) was merged a few hours ago.

It's not an encryption yet, but the info isn't going to be sent to Apple/Google anymore.

Quick explanation:

#### Push notification encryption

Whole notification needs to be encrypted on the server and decrypted on the app before displaying it.

#### Push notification privacy

The server sends only the `message id` on the push notification and the app fetches the rest of content from the server before displaying it.

---

Push Notification Privacy is planned to be released in August.

Thanks.

**Comment by ankar84** [comment]
> Push Notification Privacy is planned to be released in August.

Sound like a wonderful feature!
Will wait it a lot!

**Comment by kosmonavtika** [comment]
> Hi!
> We're going to implement push notification encryption soon, but we're already finishing a similar feature we called [Push Notification Privacy](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2213)
> The [server PR](https://github.com/RocketChat/Rocket.Chat/pull/18254) was merged a few hours ago.
> 
> It's not an encryption yet, but the info isn't going to be sent to Apple/Google anymore.
> 
> Quick explanation:
> 
> #### Push notification encryption
> Whole notification needs to be encrypted on the server and decrypted on the app before displaying it.
> 
> #### Push notification privacy
> The server sends only the `message id` on the push notification and the app fetches the rest of content from the server before displaying it.
> 
> Push Notification Privacy is planned to be released in August.
> 
> Thanks.

You forgot to mention that push notification data privacy is only available to paying customers, breaking GDPR compliance rendering Rocket.Chat push notifications unlawful in the EU.

**Comment by la-coste** [comment]
> Hi!
> We're going to implement push notification encryption soon, but we're already finishing a similar feature we called [Push Notification Privacy](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2213)
> The [server PR](https://github.com/RocketChat/Rocket.Chat/pull/18254) was merged a few hours ago.
> 
> It's not an encryption yet, but the info isn't going to be sent to Apple/Google anymore.
> 
> Quick explanation:
> 
> #### Push notification encryption
> Whole notification needs to be encrypted on the server and decrypted on the app before displaying it.
> 
> #### Push notification privacy
> The server sends only the `message id` on the push notification and the app fetches the rest of content from the server before displaying it.
> 
> Push Notification Privacy is planned to be released in August.
> 
> Thanks.


You forgot to mention that push notification data privacy is only available to paying customers, breaking GDPR compliance rendering Rocket.Chat push notifications unlawful in the EU.

**Comment by diegolmello** [comment]
@la-coste I understand your concern, but that's not up to this repo nor this issue.
I'm marking as off-topic as it's not related to Push Message Encryption.
