### ISSUE TITLE
single-server branch specific issue - App doesn't use white-labeled icon in WorkspaceView.

### ISSUE THREAD

**Issue by BizClimb** [RocketChat/Rocket.Chat.ReactNative#2327]
- Your Rocket.Chat Experimental app version: 4.9.0.1
- Your Rocket.Chat server version: 3.4.2
- Device (or Simulator) you're running with: Android

When using the single-server branch, after installing the android version, it loads the Your workspace page (app/views/WorkspaceView/) but uses the default RocketChat logo, even if you adjusted your server's 512px icon, and if you have set the logo and splash screen image files accordingly in /android/app/src/main/res.

**Comment by diegolmello** [comment]
Actually, we're using the image set on your server's settings: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/WorkspaceView/index.js#L73

Change it on Admin > Settings > Assets and try again.

**Comment by BizClimb** [comment]
Every asset is set in the Admin > Settings > Assets (as mentioned in my original post above), even tried to do a re-cache and cleared all cache/storage in the android app, still continues to load the wrong image. I suspect it's loading the faivcon from another workspace (maybe the default rocket workspace) even though I have my workspace as the server in the app.json for single server branch.

I've tried with both Enable SVG Icon on and off, same result.

**Comment by BizClimb** [comment]
Perhaps this is a problem with assets not saving correctly more so then the react native branch?

Just tried to load: /images/logo/android-chrome-512x512.png in the web browser and it is showing the rocket chat default logo regardless of my logo in the assets being shown as the 512 android chrome image..

**Comment by diegolmello** [comment]
Yeah, it looks like an issue on the main repo.
Can you create an issue there?
I'm closing this one.
Thanks.
