### ISSUE TITLE
Unable to join workspace Android App 

### ISSUE THREAD

**Issue by IEthMiner** [RocketChat/Rocket.Chat.ReactNative#2337]
### Description:

I have logged out of the app this morning and have been unable to get back in.

I'm able to connect to the workspace enter my user and pass then I see this

![image](https://user-images.githubusercontent.com/42719736/87851325-9d4c8c80-c8ef-11ea-9525-ce3f62faa885.png)

### Steps to reproduce:

1.  Join workspace 
2. Click the login button
3. Select Continue with Join the Social hub
4. Enter Username and password
5. Black screen (shown above in pic)

### Expected behavior:

To log in 

### Actual behavior:

Shown above, blank screen 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Android 10.0.0.161

### Additional context

Weirdly even when I delete all saved info on my device and cache, then uninstall Rocket Chat - When I reinstall the app It automatically logs me into the app??? Then instantly logs me out

I've spoken to a number of other users and they have had no trouble (they are testing via iPhone)

**Comment by djorkaeffalexandre** [comment]
@IEthMiner do you know if social hub is a iFrame authentication or which type of authentication it's using?
Can you send me a test user on https://open.rocket.chat/direct/djorkaeff.alexandre?
Thanks in advance.

**Comment by IEthMiner** [comment]
@djorkaeffalexandre it's using oauth connected to auth0. 

Not quite sure what you're looking for via that link? Are you wanting me to sign up or? 

Thanks

**Comment by djorkaeffalexandre** [comment]
@IEthMiner yeah, if you can register to our open server we can have a more directly conversation, and you can provide me test credentials to your server, so, I can reproduce this error here and find the error.
Without this info, I can't understand what can be happening.

**Comment by IEthMiner** [comment]
This has now been resolved - Not sure what it was but gave my account details to @djorkaeffalexandre and he was able to log in from another location.

After uninstalling the app on my end and logging in I went straight in with no issues 

Great support 👍

**Comment by djorkaeffalexandre** [comment]
We've tried again and it just worked :)
Probably an instability with their server or social hub oauth.
Thanks.
