### ISSUE TITLE
Show/Hide option in password input

### ISSUE THREAD

**Issue by saketkumar95** [RocketChat/Rocket.Chat.ReactNative#234]

**Comment by abhishek71994** [comment]
Can I work on this? I can get the app set up and contribute in a couple of days. As soon as I get a good internet connection.

**Comment by saketkumar95** [comment]
Hi @abhishek71994 , Thanks for your interest on working on this. I completed this issues an will send the PR today. You can check other issues to work on. :)

**Comment by ggazzo** [comment]
@abhishek71994 feel free to try... :)

**Comment by abhishek71994** [comment]
@ggazzo isn't @saketkumar95 already working on this?

**Comment by ggazzo** [comment]
@abhishek71994 I dont think so, but even so you can do... and I will see which is better and merge...(or merge both)
