### ISSUE TITLE
Iframe Authentication Redirection fro mobile APP

### ISSUE THREAD

**Issue by didacroyo** [RocketChat/Rocket.Chat.ReactNative#2342]
**Description:**
We are using iframe authentication, on the iframe we show a button so the user can go to our website, use the different login options and once the user is logged in is redirected back to RocketChat. At this point RocketChat uses the SSO endpoint to get the login information and the user gets logged into the chat. This works properly on the browser but not on the mobile application because **it loads the RocketChat web version inside the webview**.

**Steps to reproduce:**
Implement Iframe Authentication
Redirect the user to your website, not within the iframe, would be like a target="_top" link
Log the user in
Go back to RocketChat

**Expected behavior:**
In mobile, after going back to the RocketChat url, close the webview and load the mobile app

**Actual behavior:**
In mobile, after going back to the RocketChat url, **the RocketChat web app is loaded in the webview.**

- Your Rocket.Chat Experimental app version: 4.9.0.2132
- Your Rocket.Chat server version: 3.4.2
- Device (or Simulator) you're running with: iPHONE & ANDROID!

**Comment by djorkaeffalexandre** [comment]
Hey @didacroyo, can you provide a test account?
So, we can reproduce it here.
https://open.rocket.chat/direct/djorkaeff.alexandre
Which of these approaches are you following?
https://docs.rocket.chat/guides/developer/iframe-integration/authentication#iframe-url

**Comment by djorkaeffalexandre** [comment]
It was fixed following the docs: https://docs.rocket.chat/guides/developer/iframe-integration/authentication#iframe-url
😄
