### ISSUE TITLE
[BUG] "Unread" counter badge not updated in iOS app home screen

### ISSUE THREAD

**Issue by christoph2806** [RocketChat/Rocket.Chat.ReactNative#2343]
- Your Rocket.Chat Experimental app version: 4.9.0.308
- Your Rocket.Chat server version: 2.4.11
- Device (or Simulator) you're running with: iOS 13.5.1 on iPhone 7

The homescreen icon does not properly show the unread count.
See screenshots: I have rooms with unread messages but the icon does not show the unread counter.
Of course I've checked all notification settings but I've not found a way to activate the counter.

I've tested this on iOS 13.5.1 but users with Android have reported this behavior as well.

![rocketchat1](https://user-images.githubusercontent.com/431015/88553534-ac38ea80-d025-11ea-94ba-aec6b9f11aa8.png)
![rocketchat2](https://user-images.githubusercontent.com/431015/88553060-25840d80-d025-11ea-912e-62e5eb6287a7.png)

**Comment by diegolmello** [comment]
Hey, @christoph2806.
Is this still a thing?
I wasn't able to reproduce here.
Thanks.

**Comment by fc757** [comment]
Greetings. Me and my users with iOS devices  are having the same issue as Christoph. Push notifications work fine. But the app icon  never shows an unread # badge. If there is any way to fix this it would be greatly appreciated. I can provide info and assist in troubleshooting efforts to try and resolve this.

**Comment by d3hof** [comment]
Having the exact same issue. Sometimes it works then it stops working. Only restart of the app fixes this.

**Comment by jbuechele** [comment]
@diegolmello I can confirm that. It seems that only unread messages from a direct message are displayed. Messages from a channel or thread are not displayed.

In the render method from the [RoomItemContainer](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/presentation/RoomItem/index.js) the `item.unread` is 0 for channels. Where does the attribute "unread" come from? from the server?

**Comment by diegolmello** [comment]
@jbuechele You might be talking about a different thing.
They are talking about the push notification _badge_ on iOS on home screen, which is sent from the server (a calc based on a summary of unread messages and notifications settings for reach room).

`item.unread` is room specific and only to be displayed on the rooms list.

**Comment by jbuechele** [comment]
Okay thanks. I meant the same. There is a `NotificationsIOS.setBadgesCount(count);` method and I thought the same attribute is used for that.

Could you reproduce it?

**Comment by diegolmello** [comment]
I couldn't focus on that yet, but I think it's refreshed (and the badge is displayed) when a push notification is received.
When the app is open or restored, the badge is cleared.

**Comment by jbuechele** [comment]
I tried to debug the server code and I think its not a bug. There is a comment that the unread counter is only for mentions and direct messages ([notifyUsersOnMessage](https://github.com/RocketChat/Rocket.Chat/blob/857e21eaa7c8d38c1b52736495470ea72d8a7edd/app/lib/server/lib/notifyUsersOnMessage.js#L83)). The unread counter is then used to calc the badge count ([mobile.js](https://github.com/RocketChat/Rocket.Chat/blob/157b882d38b34b7b79dea527316554fe33f70891/app/lib/server/functions/notifications/mobile.js#L16))

So, if I mention someone in a channel, the iOS badge counter is displayed correctly

**Comment by fidelsam1992** [comment]
The unread counter settings can be changed from the RocketChat Admin
Administration -> Settings -> General -> Unread Count

The default is that the badge only counts the messages for direct/mentions only

**Comment by cjhille** [comment]
I'm currently facing the same problem. The counter doesn't get updated although there are no unread message. 

For testing I sent myself 4 message from a second account. The counter went up to 4. I read als those message. The UI marks them as read. However, iOS badge stays at 4 unread items.

Logging out and clearing local cache didn't help.

**Comment by GleidsonDaniel** [comment]
> I'm currently facing the same problem. The counter doesn't get updated although there are no unread message.
> 
> For testing I sent myself 4 message from a second account. The unread badge counter went up to 4. Then open the app to read those messages. The UI marks them as read. However, iOS badge stays at 4 unread items.
> 
> Logging out and clearing local cache didn't help. Closing and opening the app either.

Related to #4151

Update to last version 4.27.1
