### ISSUE TITLE
Push notifications are sent after auth token is invalidated

### ISSUE THREAD

**Issue by pbenkoe** [RocketChat/Rocket.Chat.ReactNative#2346]
- Your Rocket.Chat Experimental app version: 4.9.0.308
- Your Rocket.Chat server version: 3.5.0-develop
- Device (or Simulator) you're running with: iOS

**Steps to reproduce:**
Login user via iFrame authentication (postMessage API).
Invalidate auth token via REST API (either logout or users.removeOtherTokens call).
User will actually get logged out - this part works.

**Expected behavior:**
You shouldn't receive any push notifications after auth token is invalidated and you are logged out of the server.

**Actual behavior:**
At least sporadically, push notifications still get sent to the app after the user is logged out.

**Comment by diegolmello** [comment]
This is an issue on the server, which doesn't link session to push token.
Tranferring.
