### ISSUE TITLE
[IMPROVEMENT] Save Server URL

### ISSUE THREAD

**Issue by aimador** [RocketChat/Rocket.Chat.ReactNative#2348]
- Your Rocket.Chat Experimental app version: 4.9.0.2132
- Your Rocket.Chat server version: 3.4.2
- Device (or Simulator) you're running with: Any

Hi,

I'm not sure if this was requested specifically for the mobile app already, but could you maybe implement a possibility to save the server URL on the login screen?
Our users are already unhappy about the forced logout every X days. Additionaly they have to type in the URL every single time they get logged out. 
I'm not asking for anything fancy. Just a checkbox "save URL" or something on the login screen. Would be great :)

Thank you in advance

**Comment by idominiki** [comment]
It's seems to be reentered after each app update.

**Comment by didierm** [comment]
Re-adding the server URL after each logout is also in our organization a major hurdle for end-user acceptance : 

* URL's are difficult to enter on a mobile screen keyboard, leading to end-user errors ;
* URL's are difficult to remember, leading to end-user errors.

Requiring to re-enter the URL every few days is currently a major source of frustration.

Is this an intended modus operandi, or a fixable oversight ?

**Comment by diegolmello** [comment]
There's a setting on Admin's side to limit auth token's lifetime that may be causing this or maybe a misconfiguration of SSO.
Anything else is a bug and I would appreciate a reproducible example so we can fix the cause and not the collateral effect.

That said, I agree with you that we can think in a better UX for re-entering server URLs.
I'll talk to our design team.
Thanks.

**Comment by mddvul22** [comment]
@diegolmello We have our max login time set to 1 day on the servers. As for requesting a reproducible example, how are you wanting that provided?

**Comment by diegolmello** [comment]
Thanks, @mddvul22.
The setting is enough.
I asked for a reproducible example just to make sure there isn't a bug on the app, but a feature needing implementation.

**Comment by didierm** [comment]
@diegolmello Not entirely sure what you're asking for, but : 
* our authentication is primarily LDAP_based (with some local accounts for external guests) ;
* login expiration (Administration > Accounts > Login Expiration in Days) is set to "7 days".


_(possibly unrelated note : even after being forcibly logged out on our mobiles due to account expiration, we still receive push notifications without having logged in again)_

**Comment by didierm** [comment]
@diegolmello Thank you !
