### ISSUE TITLE
[Question] How to build own application version for own push notifications

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.ReactNative#2350]
- Your Rocket.Chat Experimental app version: 4.9.0
- Your Rocket.Chat server version: 3.0.12
- Device (or Simulator) you're running with: ####

Hi due to official app push notification limit from 14.08.2020 I want to build own app with own keys.
There is official document https://docs.rocket.chat/guides/administrator-guides/notifications/push-notifications#self-configured 
but is not sufficient for me.
I have created Firebase project but is not clear what to do next.
Do you have any step by step instruction where keys should be placed in code and how to build application.
Another question, is it mandatory to put my version of application in Google Play/App store or I can put it somewhere and let users to download and install it?

**Comment by diegolmello** [comment]
@emikolajczak hey!
Follow this https://github.com/RocketChat/Rocket.Chat.ReactNative/tree/single-server#running-single-server
Let me know if you manage to get it working.
Thanks!

**Comment by emikolajczak** [comment]
Hi, 
Thanks for this manual.
I try to build app form `single-server` branch, but when I run `gradlew assemblerelease` build hangs after 0.5h on `:app:bundleReleaseJsAndAssets`. Could you help me what can be wrong?

**Comment by diegolmello** [comment]
That's the more expensive task on the build. Depends on your machine.
Maybe clean your Android build and try again.

**Comment by emikolajczak** [comment]
Thanks for the answer.
From your experience how long it typically takes?
I have core i5 (8th gen) with 16GB of ram.

**Comment by emikolajczak** [comment]
I have restarted PC and now `:app:bundleReleaseJsAndAssets` finish with error `Error: EACCES: permission denied, lstat 'C:\...\Rocket.Chat.ReactNative\ios\Pods\Headers\Private\CocoaLibEvent\evdns.h'`
I am trying on Windows 10.

**Comment by emikolajczak** [comment]
Finnaly I have build apk. But after i install and run on Phone error occured. Oops! Invalid URL or unable to establish a secure connection.

**Comment by diegolmello** [comment]
It's trying to connect to the server on app.json.
Note: localhost doesn't work on the device.

**Comment by hkpanchani** [comment]
I tried to build release version it throws the following error.
Execution failed for task ':app:processExperimentalPlayReleaseGoogleServices'.
> No matching client found for package name 'my-package-name-in-gradle'
