### ISSUE TITLE
App freezes on status "updating" cannot open messages or channels (Android and apple)

### ISSUE THREAD

**Issue by caesarcxiv** [RocketChat/Rocket.Chat.ReactNative#2362]
- Your Rocket.Chat Experimental app version: Android 4.9.0 and apple
- Your Rocket.Chat server version: 3.5.0
- Device (or Simulator) you're running with: 100+ devices

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

Websocket is running / desktop app and browser work

This is a major issue for us, all of our mobile device apps stoped functioning.

App opens, says updating ... Once in a while it updates the channel list. Clicking a channel or DM does not open. 

Once in a while throughout the day the app will work for 5-30 minutes.

**Comment by caesarcxiv** [comment]
@diegolmello emailed you

**Comment by ankar84** [comment]
I have the same issue with app version 4.10.0.19273 and open.rocket.chat (3.6.0-develop)
I did try to clear cache and logoff. Now I can't login - it holds on login process

**Comment by djorkaeffalexandre** [comment]
@ankar84 are you using some OAuth client to login into open server?

**Comment by ankar84** [comment]
Hi, Alexandre!
No, I'm using simple login and password with 2fa (Google authenticator)

сб, 1 авг. 2020 г., 04:07 Djorkaeff Alexandre <notifications@github.com>:

**Comment by ankar84** [comment]
Today with same application version open.rocket.chat works fine 
I successfully login and all update events works perfect. All chats are available.

**Comment by diegolmello** [comment]
@caesarcxiv is this still a thing?

**Comment by caesarcxiv** [comment]
> @caesarcxiv is this still a thing?

It has not reoccurred.
