### ISSUE TITLE
The application is unable to show group chat.

### ISSUE THREAD

**Issue by fniko** [RocketChat/Rocket.Chat.ReactNative#2367]
- Your Rocket.Chat Experimental app version: 4.9.0.2132
- Your Rocket.Chat server version: 3.4.2 (managed)
- Device (or Simulator) you're running with: Xiaomi Mi 9T (MIUI 12.0.2 Stable)

The application is unable to show one group chat. The chat is displayed for a second and then app crashes.
Error:
```
com.facebook.react.common.JavascriptException:
TypeError: Cannot read propery 'username' of Null	
```

full bug report here
https://pastebin.com/Nur4gCRX

**Comment by diegolmello** [comment]
@fniko I was unable to reproduce here.
Can you record a video/gif?

**Comment by fniko** [comment]
@diegolmello Yes, link below. It is only one specific group... but no one has access to it using a mobile app.

https://photos.app.goo.gl/gNENAoLgHPkVoBRh8

**Comment by diegolmello** [comment]
Oh, I think I got it.
Thanks for reporting.
