### ISSUE TITLE
Stuck on splash screen when tapping on push notification

### ISSUE THREAD

**Issue by AlexKalopsia** [RocketChat/Rocket.Chat.ReactNative#2369]
- Your Rocket.Chat Experimental app version: 4.10.0.19273
- Your Rocket.Chat server version: 3.5.1
- Device (or Simulator) you're running with: Sony Xperia 1 II

I am running RocketChat on Docker, reverse-proxied with LetsEncrypt's nginx. 
It works perfectly fine from desktop and mobile, and I connect to it on `http://myip:3030` or `https://chat.mydomain.com`

The only issue I am having is that whenever I get a notification and I tap on it, the app opens up but it stays on the splash screen. The only way to read the message is to close the app and then open it again manually. 

I found this very similar issue, but it's closed and I am not sure what the policy here is: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1804

Below my config.

nginx config:

```
# Upstream definition

upstream backend {
    server 192.168.1.200:3030;
}

# http to https redirection
server {
	listen 80;
	server_name chat.mydomain.com;
	rewrite ^ https://$server_name$request_uri? permanent;
	client_max_body_size 512M;
}

# HTTPS Server
server {
    listen 443;
    server_name chat.*;
    error_log /var/log/nginx/rocket-chat.access.log;
    ssl on;
    include /config/nginx/ssl.conf;
    client_max_body_size 512M;

    location / {
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}
```

and this is the `docker-compose`:

```
rocketchat:
    container_name: rocketchat
    image: rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3030
      - ROOT_URL=https://chat.mydomain.com
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.mydomain
#       - HTTP_PROXY=http://proxy.domain.com
#       - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3030:3030
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: chat.mydomain.com"
```

Any idea what could be the cause of this?

**Comment by diegolmello** [comment]
Hey, @AlexKalopsia!
We released a new version yesterday and it should be available for you already: 4.10.0.19550
It has a PR that was merged 5 days ago here: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2359

Usually this kind of issue is related to a misconfiguration of the Site URL pointing to a different URL used as main server.
e.g. the user uses https://chat.mydomain.com but the server has `Site_Url` configured as http://chat.mydomain.com (note the insecure protocol)

What we started to do from that PR on is to override the protocol every time.

**Comment by AlexKalopsia** [comment]
Hi @diegolmello, thank you so much for the quick reply. 

The new version did, in fact, fix the issue!

Out of curiosity, what's the correct way to fix `Site_Url` for a docker installation?

**Comment by diegolmello** [comment]
> Hi @diegolmello, thank you so much for the quick reply.

👊 

> Out of curiosity, what's the correct way to fix Site_Url for a docker installation?

I don't know :(
@geekgonecrazy can you help? :)

**Comment by geekgonecrazy** [comment]
Just go into UI under general and fix.

If you just must fix via docker you can set OVERWRITE_SETTING_Site_Url=url and will force it on startup to that value
