### ISSUE TITLE
App crash during server create

### ISSUE THREAD

**Issue by tonobo** [RocketChat/Rocket.Chat.ReactNative#237]
I've installed the app from play store right now and it will always crash on opening server add dialog.

**Comment by ggazzo** [comment]
hey @tonobo thanks for writing, actually I think, we know this problem, we believe updating react-native to 0.53+ will fix it, could you try use your phone on landscape (just until get logged), and let me know if "solves"?

**Comment by tonobo** [comment]
Oh nice, this will fix it ;)

**Comment by ggazzo** [comment]
@tonobo could you try again? :)

**Comment by tonobo** [comment]
Im unable to reproduce it, because im already logged in

**Comment by tonobo** [comment]
But i,ve triggered another crash on loading a chat history. I've reported tge feedback. Hope it helps. :)

**Comment by ggazzo** [comment]
Thanks @tonobo I will close this issue because I`m confident we fixed this problem. :) thanks for the feedback

**Comment by tonobo** [comment]
Is there any possibility to easily get the application stack trace if it crashes?
