### ISSUE TITLE
Huawei push notifications

### ISSUE THREAD

**Issue by trollqaa** [RocketChat/Rocket.Chat.ReactNative#2384]
### Description:
New Huawei / Honor smartphones do not have Google services, and as a result, PUSH notifications sent via GCM do not work

### Steps to reproduce:

1.  Use huawei/honor 2019/2020 years w/o gApps
2.  Install .apk Rocket.Chat
3.  Push not received and show message "app need google services"... :(

### Expected behavior:
i expect working push notify

### Actual behavior:
- push not working
- app send me alert "gapps not found"

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.0  
- Operating System: Omnibus
- Deployment Method:  docker
- Number of Running Instances: 2 
- DB Replicaset Oplog: yes
- NodeJS Version: 12
- MongoDB Version: 4.2

### Client Setup Information

- Desktop App or Browser Version: mobile app
- Operating System: Android 10

### Additional context

- problem not server, only client-side

### Relevant logs:

-

**Comment by diegolmello** [comment]
You'll have to download the F-Droid build.
Push notification aren't going to work though.
I'm closing this so we can focus on the work being done on https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2096
