### ISSUE TITLE
No push notification : I dont receive notifications if the app is not running

### ISSUE THREAD

**Issue by nixxou** [RocketChat/Rocket.Chat.ReactNative#2385]
I don't know if that's a normal behavior. With apps like whatsapp, when i reboot my phone, dont launch the app and i receive a private message, i get the notification, but the same does not apply with rocketchat android app (both reactNative and the old one).

I'm on Android 9.

I only get notification after i launch the app, if i swipe out the app in the list of active app, i don't receive notifications anymore.

I did try in my own server, i try with the "test push notification" on the admin settings page and i make some try with the public open workspace with two accounts (one on my desktop, one on my mobile).

I didn't get any success. The only notifications i can receive is when the app is runing (front or in the background)
I tried everything, disabled anything related to battery optimisation for the app, but nothing so far.

Is that a normal behavior ?

**Comment by st1gok** [comment]
I also have similar behavior.  I dont receive notifications if stopped application in Options->Applications. 
Tried sending push from admin interface and as user message.

Android 9
App 4.9.0.2132
Server 3.5.1

**Comment by diegolmello** [comment]
Can you test that on https://open.rocket.chat?
We're using it on this server and it works.

**Comment by nixxou** [comment]
> Can you test that on https://open.rocket.chat?
> We're using it on this server and it works.

Like i said, i did exactly that.
Two account on the open rocket chat server, one with my desktop, one with my android.
If i launch the mobile app, press home (so the app still runing in the background), and send a private message from my computer account to my mobile account i get the notification.
But if i swipe out the app in the list of active app, and then send a private message from my computer, i receive no notifications.
The same happen if i reboot my phone and dont launch rocket chat : i will not receive any notifications.

**Comment by diegolmello** [comment]
It's hard to guess what's happening, as it's working on the phone on my desk.
What's you Android device?
Can you share a log report?

**Comment by nixxou** [comment]
My phone is a Black Shark 2, runing a close to stock Android 9.
I tried to disable all battery optimisations options for Rocket.chat application, but that dont change anything.
How can i produce a log report ?

**Comment by diegolmello** [comment]
https://developer.android.com/studio/debug/bug-report

**Comment by nixxou** [comment]
I'm not confortable posting a log report on a public page, can i send it to you as a private message ?

I captured debug data while sending a "test push notification" on my server, with my android app swiped out.
And indeed, i see on the debug log : 

08-12 10:26:41.061 10222 30453 31121 D ReactNativeNotifs: New message from FCM: Bundle[{soundname=default, google.delivered_priority=normal, google.sent_time=1597220801545, google.ttl=2419200, google.original_priority=normal, from=673693445664, title=@Administrateur, google.message_id=0:1597220801550281%a859fc92f9fd7ecd, message=This is a push test message, google.c.sender.id=673693445664}]

But i didn't see a notification on my phone.

**Comment by nixxou** [comment]
Ok, so my last issue was related to this : https://github.com/RocketChat/Rocket.Chat/issues/18541
And i manage to fix it.

But right now, i'm back to step one, and i still only get notification if my app is active (or runing in background).

@diegolmello Can i send you a bug report in a private message ?

**Comment by diegolmello** [comment]
@nixxou sure! https://open.rocket.chat/
I'm `@diego.mello`

**Comment by nixxou** [comment]
Ok, i send you a private message in the rocket chat open workplace.

**Comment by nahid** [comment]
I am facing the same issue from couple of days

**Comment by diegolmello** [comment]
@nahid @nixxou is this still happening for you?

**Comment by gamingumar** [comment]
I am not able to login at https://cloud.rocket.chat/

**Comment by diegolmello** [comment]
@gamingumar Ask on https://open.rocket.chat/channel/support

**Comment by nixxou** [comment]
@diegolmello yes, i still have the issue

**Comment by nahid** [comment]
@diegolmello yes I still facing this issue

**Comment by wolfcreative** [comment]
@diegolmello I have this problem.
Moreover, my users with Huawei and Xiaomi do not receive ANY notifications.

**Comment by aleadco** [comment]
This happens with the latest version of the stable app 4.11.0.2137, in the experimental version it works correctly.

**Comment by wolfcreative** [comment]
@aleadco 
As it turned out, the problem was in the Android system settings. Some users didn't have notifications enabled by default, while others did the opposite.

**Comment by aleadco** [comment]
@wolfcreative In the Push notifications settings in the user's profile "Default" is set, so according to the server settings all the notifications sent to the private chats should reach me, as happens in the experimental version of rocket.  However I changed the setting to "Mentions" and if I receive notifications in that regard.  With these it is possible to assume that with the last update the default settings are not being read correctly.  It is unquestionably an application problem.

**Comment by diegolmello** [comment]
Is it still valid?

**Comment by azhinu** [comment]
@diegolmello yes.
Android 12 and Android 13 on Pixel. Sometimes I receive a notification with a big delay and only if application is running.

**Comment by diegolmello** [comment]
Thanks, @azhinu.
We're going to investigate Pixel devices.
In the meantime, please create two accounts on https://open.rocket.chat and send messages between them to test if notifications are going to work on your device.

If anyone else has issues with push notifications, please list your affected devices and OS versions.

**Comment by azhinu** [comment]
@diegolmello, I tried that you wrote.
When I just switched to another app, I receive push within 20-30 seconds after i send a message. But when i swapped off rocket chat from recent apps or waited for a few hours, i doesn't receive a push.
