### ISSUE TITLE
[CHORE] Upgrade to latest React Native 0.63.2

### ISSUE THREAD

**Issue by hengsok** [RocketChat/Rocket.Chat.ReactNative#2395]
### Description:

React Native 0.63.2 fixed several bugs and improvements. Any plans to upgrade this project to latest React native version?
I'm not familiar of the changes in the patch file for 0.63.1, so it would be nice for someone familiar with those changes to perform the upgrade.

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name: 
- OS Version: 

### Steps to reproduce:

1. 
2. 
3.

**Comment by diegolmello** [comment]
Several bugs?
Are you looking for a specific bug that affect us now and will stop happening after the update?

**Comment by diegolmello** [comment]
@hengsok cool
I'm closing and we're going to update to when 0.64 is released, which is going to happen in a couple of weeks.
