### ISSUE TITLE
No push notification in official rocket.chat Android app: I dont receive notifications if the app is not running

### ISSUE THREAD

**Issue by antoniomorais360** [RocketChat/Rocket.Chat.ReactNative#2397]
### Description:

No push notification in official rocket.chat Android apps (including experimental).
I dont receive notifications if the app is not running.  If I open the app, the notification comes instantly... but there are no notifications if I am in any other app.

### Environment Information:

- Rocket.Chat Server Version: 3.4.2
- Rocket.Chat App Version: 4.10.0.2135
- Device Name: Galaxy A30 and Galaxy A50
- OS Version: Android 10

### Steps to reproduce:

1. Goto to Administration > Push notifications
2. Send a test push to my user

### Expected behavior:
A push notification in my mobile phone

### Actual behavior:
Nothing happens. If I open the app, the notification comes instantly... but there are no notifications if I am in any other app.

**Comment by ankar84** [comment]
You need to use gateway to get push notifications work with official application.

**Comment by antoniomorais360** [comment]
![image](https://user-images.githubusercontent.com/2750015/90115368-fd352800-dd21-11ea-96f3-f612708b8f6a.png)

Should be this one?

**Comment by ankar84** [comment]
> Should be this one?

Yes. Settings looks fine.

**Comment by antoniomorais360** [comment]
![image](https://user-images.githubusercontent.com/2750015/90116990-4b4b2b00-dd24-11ea-90bb-8e7439f5b1f9.png)
![image](https://user-images.githubusercontent.com/2750015/90117073-64ec7280-dd24-11ea-971f-0d133cb48efc.png)

I don't know what could be missing :(

**Comment by ankar84** [comment]
> It works for some time, but suddenly stopped.

Oh, so maybe this is the root cause https://forums.rocket.chat/t/update-on-registration-requirement-to-utilize-push-gateway/7733

**Comment by antoniomorais360** [comment]
Hello @ankar84 , thanks for your help.

I was registered, but disconnected here. I reconnect and works! The problem now is the 2 minutes delay.
![image](https://user-images.githubusercontent.com/2750015/90250250-ccc8b900-de09-11ea-991e-601050513e5d.png)
