### ISSUE TITLE
Unable to npm install

### ISSUE THREAD

**Issue by procnedev** [RocketChat/Rocket.Chat.ReactNative#2398]
### Description:

I've just do a "git clone" and run an "npm install".
The last command is unable to install/found all modules.

### Steps to reproduce:

1. git clone https://github.com/RocketChat/Rocket.Chat.ReactNative.git
2. npm install

### Actual behavior:

Error: Command failed: git submodule update -q --init --recursive
fatal: No url found for submodule path 'original/LokiJS' in .gitmodules

at ChildProcess.exithandler (child_process.js:295:12)
at ChildProcess.emit (events.js:210:5)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
cwd C:\Mobile\Rocket.Chat.ReactNative
Windows_NT 10.0.19041
argv "C:\\_env\\nodejs\\node.exe" "C:\\_env\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
node v12.14.0
npm  v6.13.4
error code 128
Command failed: git submodule update -q --init --recursive
fatal: No url found for submodule path 'original/LokiJS' in .gitmodules

**Comment by Fishbowler** [comment]
This repo uses `yarn` rather than `npm install`. Give that a go and report back if that solves your problem.

**Comment by procnedev** [comment]
Yes it solved the issue.
Thank you.
