### ISSUE TITLE
[i18n] Add Trad Chinese

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat.ReactNative#2402]
### Environment Information:

- Rocket.Chat Server Version: 3.5.0
- Rocket.Chat App Version: 4.10.0.2135
- Device Name: HTC
- OS Version: Android 9

### Steps to reproduce:

1. Settings
2.  Language
3.  It's not Trad.Chinese

### Expected behavior:

I has translate all rocket.chat string for trad.chinese .But it's not add to android or ios system.Please add it.Thanks a lot.

**Comment by diegolmello** [comment]
hey, @akong77!
Can you open a PR adding it?
Copy, rename this file to `zh_TW.js` and translate all appropriate strings: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/i18n/locales/en.js

Add `zh_TW` [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/LanguageView/index.js#L23) and [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/i18n/index.js#L17)

I'd be glad to review your PR.
Thanks!
