### ISSUE TITLE
[BUG] Jitsi call crash Rocket.Chat ReactNative application on smartphone rotate

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2410]
### Description:

Jitsi call crash Rocket.Chat ReactNative application on smartphone rotate. Mostly on Android.

### Environment Information:

- Rocket.Chat Server Version: 3.1.1
- Rocket.Chat App Version: 4.10.0.19667
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 10

### Steps to reproduce:

1. Start Jitsi call in Rocket.Chat ReactNative
2. Rotate your smartphone horizontally and vertically few times (less with video in call, more in just audio call)  
3. Rocket.Chat ReactNative application crash

### Expected behavior:

User rotate smartphone as hi wants and Jitsi call do not crash Rocket.Chat ReactNative application

### Actual behavior:

![20200819_112231](https://user-images.githubusercontent.com/4023037/90592361-9aef9200-e20f-11ea-8018-9aa9046a6d54.gif)

### Additional context:

That problem is most Android related, I could not reproduce that on iPhone.

**Comment by diegolmello** [comment]
It seems to be related to Jitsi itself.
Thanks for linking it.

**Comment by ankar84** [comment]
> It seems to be related to Jitsi itself.
> Thanks for linking it.

Hi, Diego!

Today I tested that issue on Jitsi Meet version 20.4.1 and it looks much stable - I did 50-70 rotates without any crash.
So, maybe that issue is resolved in [SDK 2.10.0](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#2100-2020-09-15)
Tested on Redmi Note 5 Android 9 and Samsung S8 Android 9
So, please in future versions (I believe 4.12) update Jitsi SDK to latest available.

**Comment by ankar84** [comment]
4.12 issue is still here, unfortunately.

**Comment by ankar84** [comment]
Actually as you can see in first post of that issue previous version crashed after a few rotates.
Yesterday it took me a 5 minutes or so to reproduce that bug. And it's really good stability improvement.
But unfortunately I found another big bug in Jitsi in 4.12, will report as separate issue.

**Comment by ankar84** [comment]
Works perfect in 4.12.1
Thanks @djorkaeffalexandre and @diegolmello

**Comment by ankar84** [comment]
Unfortunately that bug come back in 4.19.0 version on Android (iOS rotates without any issues).
Tested on Xiaomi Mi 9SE and Samsung S8

**Comment by diegolmello** [comment]
Is it valid?

**Comment by ankar84** [comment]
> Is it valid?

Fixed since you removed Jitsi SDK from Android version
