### ISSUE TITLE
Any way to override codes rather than replacing them?

### ISSUE THREAD

**Issue by Bob7rm** [RocketChat/Rocket.Chat.ReactNative#2411]
Hi 
I'm wondering what is the best way to customize the app, is there any process to override mobile app views or a standard for that?
Generally is there any document for application customization like adding custom oauth services alike amazon cognito?

**Comment by diegolmello** [comment]
I didn't get what you're trying to get help here, but here's the whitelabel doc https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps

If you're trying to get help related to Custom OAuth, ask on our server repo: https://github.com/RocketChat/Rocket.Chat
