### ISSUE TITLE
[BUG] Workspaces are lost and hang after upgrade to 4.11

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2417]
### Description:

Today my experimental application was updated to version 4.11.0.19927 and first what I saw when I opened it was screen of adding first workspace. Before update my application was configured with 2 workspaces.
When I add my workspace - right after login application stuck on undless load. I cleared cache and that immediately helped.

### Environment Information:

- Rocket.Chat Server Version: 3.1.1
- Rocket.Chat App Version: 4.11.0.19927
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 10

### Steps to reproduce:

1. Update application to version 4.11.0.19927
2. All your workspaces are gone

### Expected behavior:

All my data should remain safe during all updates

### Actual behavior:

Stuck on login
![image](https://user-images.githubusercontent.com/4023037/90851772-5cc4b080-e37e-11ea-8468-dbdb09bb1f45.png)

**Comment by ankar84** [comment]
Maybe related to https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2247 as additional encryption of all user data.

**Comment by dario-petrovic** [comment]
Hi,

Same is seen on Android Rocket Chat Experimental app v4.1120023 as well as on Rocket Chat app.

Rockrt Chat server v3.6.0 (latest).

**Comment by dario-petrovic** [comment]
Rocket Chat app (not Experimental) v4.10.0.2135 works fine.

Can it be investigated what is the diff?

**Comment by ankar84** [comment]
I think it reproduced on 4.10 and 4.6.0
![Screenshot_2020-09-13-16-42-09-330_chat rocket android](https://user-images.githubusercontent.com/4023037/93015058-5b368300-f5e0-11ea-8125-70b4856d33ef.jpg)
![Screenshot_2020-09-13-16-42-16-716_chat rocket android](https://user-images.githubusercontent.com/4023037/93015060-5d004680-f5e0-11ea-85cd-51a23ad3a7a6.jpg)

**Comment by diegolmello** [comment]
That's probably related to database migrations.
Every release has some database migrations for the next features (adding columns, tables, etc).
That's why it works after clearing cache, which deletes the whole database instead of just migrating it.
I'm going to close this one, because we need to proper test it after we have a release candidate of 4.11.
There's no point to tracking errors before finish the implementation of the features.
Thanks.
