### ISSUE TITLE
How build .ipa RocketChat for apple enterprise?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2437]
Hi all

I succesfull build and run ios on emulator in xcode.
But i need build .ipa for my apple enterprise program.
How can i do this?
In xcode not available "archive" in RocketChat project.

Thank you

**Comment by emikolajczak** [comment]
Hi, check in Xcode if in **"Devices"** menu you have selected **"Generic iOS Device"**

**Comment by diegolmello** [comment]
That's a StackOverflow question.
