### ISSUE TITLE
iFrame SSO Authentication not working

### ISSUE THREAD

**Issue by pbenkoe** [RocketChat/Rocket.Chat.ReactNative#2438]
### Description:

When I try to log in via iFrame, in about 90% of the cases the javascript code to log the user in doesn't seem to be executed correctly, but is just being displayed as html. In about 10% of the cases, the user is logged in after relaunching the app, although the UI didn't indicate login success.

### Environment Information:

- Rocket.Chat Server Version: 3.5.3
- Rocket.Chat App Version: 4.10.0
- Device Name: any Android or iOS Device
- OS Version: Android & iOS

### Steps to reproduce:

1. Log in via iFrame SSO with custom rocket.chat instance URL

### Expected behavior:

User is logged in and redirected to chat overview screen.

### Actual behavior:

The javascript code to log the user in is being displayed as html on screen (see attached screenshot). The weird thing is, that it seems to be working occasionally when trying to log in 5-10 times or so.

This also happens on desktop app at the moment. Another weird thing is, that this used to work in the setup I have just a couple weeks ago. Not sure if this is a client or server issue?

Thank you for your help!

### Additional context:

![88ED943B-069E-4ED9-8133-384C92E0929F](https://user-images.githubusercontent.com/2855761/91618987-cb86a880-e940-11ea-9b73-5a60faea2162.png)

**Comment by djorkaeffalexandre** [comment]
Hey @pbenkoe, looks like something is going wrong with your iFrame, not with the app, but if possible give me some test credentials on https://open.rocket.chat/direct/djorkaeff.alexandre and I'll take a look ASAP.
Thanks.

**Comment by pbenkoe** [comment]
Thank you very much @djorkaeffalexandre ! I'll reach out via PM 🙏
