### ISSUE TITLE
How to divide the conversation into left and right sides?

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat.ReactNative#2441]
### Environment Information:

- Rocket.Chat Server Version: 3.5.4
- Rocket.Chat App Version: 2.17.11
- Device Name: PC
- OS Version: Win10

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

At present, the content of the conversation will be on the left, but when there are many messages, it will be very slow to find someone or the message will become very slow, and it is not easy to distinguish which one is a friend’s message and which one is sent by oneself, whether it is possible to combine all the messages of a friend Displayed on the left, and self-posted messages on the right?

**Comment by diegolmello** [comment]
Wrong repo.
You're looking for https://github.com/RocketChat/Rocket.Chat.
I'm closing this issue and the others you've opened.
Make sure to open an issue on the correct repo and to follow the template.
Thanks.
