### ISSUE TITLE
Could show unread message count at channel?

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat.ReactNative#2442]
### Environment Information:

- Rocket.Chat Server Version: 3.5.4
- Rocket.Chat App Version: 2.17.11
- Device Name: PC
- OS Version: Win10

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:
If I have unread direct message it's will show unread message count.But the channel only highlight.Could show unread message count at channel?

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2441#issuecomment-684794028
