### ISSUE TITLE
The release 4.10.0 is same to 4.9.0.

### ISSUE THREAD

**Issue by bingluen** [RocketChat/Rocket.Chat.ReactNative#2443]
### Description:

The release 4.10.0 is same to 4.9.0.

Is there mistake on add tag ?

Just see https://github.com/RocketChat/Rocket.Chat.ReactNative/compare/4.9.0...4.10.0

**Comment by diegolmello** [comment]
Hey, @bingluen.
That was my bad.
It should be all good now.
Thanks for reporting.
