### ISSUE TITLE
Could set message on top

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat.ReactNative#2444]
### Environment Information:

- Rocket.Chat Server Version: 3.5.4
- Rocket.Chat App Version: 2.17.11
- Device Name: PC
- OS Version:  Win10

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Could set message always on top?The pinned message or my favorites message can't do it.

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2441#issuecomment-684794028
