### ISSUE TITLE
App Installation Issue on Android Emulator - Gradle Build Failed

### ISSUE THREAD

**Issue by krutik710** [RocketChat/Rocket.Chat.ReactNative#2453]
react-native run-android 
Throws this error - 
* What went wrong:
Task 'installDebug' not found in project ':app'.

Find the traceback below - 
warn Package @react-native-community/cookies has been ignored because it contains invalid configuration. Reason: Cannot find module '@react-native-community\cookies\package.json'
Require stack:
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\runServer.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\start.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\cli.js
- C:\Users\DELL\AppData\Roaming\npm\node_modules\react-native-cli\index.js
warn Package react-native-config-reader has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-config-reader\package.json'
Require stack:
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\runServer.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\start.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\cli.js
- C:\Users\DELL\AppData\Roaming\npm\node_modules\react-native-cli\index.js
warn Package react-native-mmkv-storage has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-mmkv-storage\package.json'
Require stack:
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\runServer.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\start\start.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\cli.js
- C:\Users\DELL\AppData\Roaming\npm\node_modules\react-native-cli\index.js
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 2598 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Launching emulator...
info Successfully launched emulator.
info Installing the app...

> Configure project :app

Installing unimodules:
 unimodules-core@5.3.0 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@unimodules\core
 unimodules-react-native-adapter@5.4.0 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@unimodules\react-native-adapter
 expo-av@8.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-av
 expo-constants@9.1.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-constants
 expo-file-system@9.0.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-file-system
 expo-haptics@8.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-haptics
 expo-image-loader@1.1.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-image-loader
 expo-keep-awake@8.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-keep-awake
 expo-local-authentication@9.2.0 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-local-authentication
 expo-permissions@9.0.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-permissions
 expo-video-thumbnails@4.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-video-thumbnails
 expo-web-browser@8.3.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\expo-web-browser
 unimodules-app-loader@1.2.0 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-app-loader
 unimodules-barcode-scanner-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-barcode-scanner-interface
 unimodules-camera-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-camera-interface
 unimodules-constants-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-constants-interface
 unimodules-face-detector-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-face-detector-interface
 unimodules-file-system-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-file-system-interface
 unimodules-font-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-font-interface
 unimodules-image-loader-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-image-loader-interface
 unimodules-permissions-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-permissions-interface
 unimodules-sensors-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-sensors-interface
 unimodules-task-manager-interface@5.2.1 from C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\unimodules-task-manager-interface
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\analytics\package.json
:react-native-firebase_app package.json found at C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_analytics:firebase.bom using default value: 25.7.0
:react-native-firebase_analytics package.json found at C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\analytics\package.json
:react-native-firebase_analytics:version set from package.json: 7.6.1 (7,6,1 - 7006001)
:react-native-firebase_analytics:android.compileSdk using custom value: 29
:react-native-firebase_analytics:android.targetSdk using custom value: 29
:react-native-firebase_analytics:android.minSdk using custom value: 21
:react-native-firebase_analytics:reactNativeAndroidDir C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:firebase.bom using default value: 25.7.0
:react-native-firebase_app:play.play-services-auth using default value: 16.0.1
:react-native-firebase_app package.json found at C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:version set from package.json: 8.4.1 (8,4,1 - 8004001)
:react-native-firebase_app:android.compileSdk using custom value: 29
:react-native-firebase_app:android.targetSdk using custom value: 29
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\android

> Configure project :react-native-firebase_crashlytics
:react-native-firebase_crashlytics package.json found at C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\crashlytics\package.json
:react-native-firebase_app package.json found at C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_crashlytics:firebase.bom using default value: 25.7.0
:react-native-firebase_crashlytics package.json found at C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\crashlytics\package.json
:react-native-firebase_crashlytics:version set from package.json: 8.4.2 (8,4,2 - 8004002)
:react-native-firebase_crashlytics:android.compileSdk using custom value: 29
:react-native-firebase_crashlytics:android.targetSdk using custom value: 29
:react-native-firebase_crashlytics:android.minSdk using custom value: 21
:react-native-firebase_crashlytics:reactNativeAndroidDir C:\Users\DELL\Desktop\Temp\Rocket.Chat.ReactNative\node_modules\react-native\android

> Configure project :rn-root-view
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 54s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

**Comment by djorkaeffalexandre** [comment]
use `$ yarn android`, we've updated the documentation and it'll be merged soon, see #2450.
