### ISSUE TITLE
How do I change bundle id of the mobile app?

### ISSUE THREAD

**Issue by degodfather** [RocketChat/Rocket.Chat.ReactNative#2457]
All I can see is chat.rocket.whitelabel. How will I change the bundle id to something like com.mycompany.chat ?

**Comment by diegolmello** [comment]
https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps

**Comment by degodfather** [comment]
@diegolmello I've seen this page, but it doesn't show how to change the bundle id. Should I use tools like `react-native-rename` or something like that?
