### ISSUE TITLE
Trello links in messages

### ISSUE THREAD

**Issue by dev-manager-uk** [RocketChat/Rocket.Chat.ReactNative#2461]
### Description:

Enable Trello links to open the Trello app.

### Environment Information:

- Rocket.Chat Server Version: All
- Rocket.Chat App Version:: All
- Device Name: All 
- OS Version: All

### Steps to reproduce:

1. Receive a trello link in your Rocket.Chat mobile app
For example: https://trello.com/c/m7mFrJK4

2. Click link in your Rocket.Chat mobile app

### Expected behavior:

It should open the link into the Trello app that's installed on the device

### Actual behavior:

1. It opens the link in the embedded browser in Rocket.Chat for mobile
2. Trello is not logged in so you get a 'Card Not Found' error
3. There is no way to open the card in the Trello app

**Comment by diegolmello** [comment]
That needs to be implemented as a Rocket.Chat app: https://docs.rocket.chat/guides/rocket-chat-apps

**Comment by dev-manager-uk** [comment]
Why wouldn't you support this for all users?

**Comment by diegolmello** [comment]
Who said that?
That's exactly the way we handle Atlassian: https://docs.rocket.chat/guides/rocket-chat-apps/atlassian
Trello is part of Atlassian now btw.
It shouldn't be that hard to implement.

**Comment by dev-manager-uk** [comment]
We're using Rocket.Chat cloud.  We don't have a custom server/client.  

You seem to be saying that to solve this small but really annoying problem we should build our own custom client?

As you said 'It shouldn't be that hard to implement'

All I'm asking is to open a trello link, sent via Rocket.Chat, in the trello app, instead of the Rocket.Chat inbuild browser.

Are you saying you're not willing to do this in the main app?

**Comment by diegolmello** [comment]
Oh, that's actually my bad.
I thought you wanted to show Trello preview on the app.
You can just change the default browser of the app on `Settings > Default browser` to Safari or other one (I can't say because you didn't follow the issue template).

**Comment by dev-manager-uk** [comment]
OMG That worked perfectly!!!!!!!!!!

🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳

Thank you :-)
