### ISSUE TITLE
Problema para acessar APPs Rocket.Chat

### ISSUE THREAD

**Issue by Graciela-Zaffari** [RocketChat/Rocket.Chat.ReactNative#2467]
### Description:

 Membro da equipe não consegue utilizar o APP (tanto no PC quanto no celular), apenas o navegador. Restante da equipe utiliza sem problemas os APPs

### Steps to reproduce:

1.  coloco endereço do servidor
2.  coloco dados da pessoa (e-mail e senha)
3.  e recebo uma mensagem assim: Suas credenciais foram rejeitadas. Tente novamente por favor!

### Actual behavior:

 mensagem de erro descrita acima

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: Linux
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 
- Operating System: 

### Relevant logs:

![e2db2e84-266f-4da1-a6e5-726150c6e066](https://user-images.githubusercontent.com/71288811/93128966-ab781880-f6a6-11ea-8cf1-4e22108d1717.JPG)

**Comment by diegolmello** [comment]
Oi, @Graciela-Zaffari.
Tudo bem?
Esse é um erro de usuário e senha mesmo.
Confirma se o email e a senha estão corretos.
Tu pode clicar naquele ícone de olho na direita da senha pra mostrar a senha informada.

**Comment by Graciela-Zaffari** [comment]
Oi, bom dia,
Sim, estão corretos, mas não encontrei ícone do olho ao lado da senha.
De qualquer forma, tentamos resetar a senha para ver se resolvia, mas não
teve forma de receber o e-mail pro resert mesma, mesmo ele estando certo.

--
*Estamos trabalhando em home office temporariamente na prevenção ao
COVID-19. Se necessário, entre em contato por e-mail ou WhatsApp.*
Atenciosamente,


Graciela Zaffari | Arquiteta

+ 55 51 3346 5900 | ramal 212

Av. Sen. Tarso Dutra 605 / 1303

Porto Alegre - RS - CEP: 90690-140 www.verazaffari.com.br



Em ter., 15 de set. de 2020 às 10:47, Diego Mello <notifications@github.com>
escreveu:

**Comment by diegolmello** [comment]
Estranho.
Me chama no https://open.rocket.chat/direct/diego.mello?

**Comment by diegolmello** [comment]
We solved the issue on DM.
Thanks.
