### ISSUE TITLE
Can't work with jitsi when host port isn't 80/443

### ISSUE THREAD

**Issue by billypon** [RocketChat/Rocket.Chat.ReactNative#2470]
### Environment Information:

- Rocket.Chat Server Version: 3.6.1
- Rocket.Chat App Version: 4.10.0.310
- Device Name: iPhone 7 Plus
- OS Version: 13.3.1

### Steps to reproduce:

1. Create direct message channel with someone
2. Start video meeting
3. Try to connect meeting server, and then auto quit

### Expected behavior:

Start video meeting

### Actual behavior:

It just work fine on PC, fail to start video meeting on Android/iOS, and auto quit

### Additional context:

My jitsi server is `http://jitsi.domain.com:1234`, and I  set jitsi's domain to `jitsi.domain.com:1234`(Video Conference -> Jitsi)
If I change port to 80, and set domain to `jitsi.domain.com`, it works find on both PC and Android/iOS

**Comment by djorkaeffalexandre** [comment]
hey @billypon we've a old issue with a similar problem, can you take a look?
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1993

**Comment by billypon** [comment]
@djorkaeffalexandre I'm sorry, I can see the issue is solved, but how to do? All software versions are up to date, still can't work with port 8443
