### ISSUE TITLE
Custom channel avatars don't appear in the app

### ISSUE THREAD

**Issue by robertfromont** [RocketChat/Rocket.Chat.ReactNative#2477]
### Description:

In the browser interface, it's possible to set the avatar of a channel to a custom image, and these appear in the browser chat client instead of the big letter. But they *don't* appear in the mobile client.

### Environment Information:

- Rocket.Chat Server Version: 3.6.1
- Rocket.Chat App Version: iOS 4.10.0.310 (and also Android 4.10.0.2135)
- Device Name: iPad Air 2 (and also Pixel 1)
- OS Version: iOS 13.7 (and also Android 10)

### Steps to reproduce:

1.In the Browser version, set a custom avatar image on any channel
2. Open the mobile app and observe the list of channels

### Expected behavior:

The channel with the custom avatar has that avatar displayed.

Like it does in the browser:

![RocketChatChannelAvatarBrowser](https://user-images.githubusercontent.com/1911137/93724216-758dd500-fb7b-11ea-9e8f-3adfbfc5ee5c.png)

### Actual behavior:

The channel with the custom avatar has a letter as an avatar.

![RocketChatChannelAvatarAndroid](https://user-images.githubusercontent.com/1911137/93724397-02855e00-fb7d-11ea-9d95-07a577f339de.png)

**Comment by EzequielDeOliveira** [comment]
Hi @robertfromont  I'm working on this feature, soon we'll see custom avatars on the channels in the mobile app. take a look here #2454 :)
