### ISSUE TITLE
Scrollview and FlatList not scrolling to bottom on ios when keyboard open

### ISSUE THREAD

**Issue by shaheem-khanzada** [RocketChat/Rocket.Chat.ReactNative#2478]
### Description:

Scrollview and FlatList not scrolling to bottom on ios when keyboard open

### Environment Information:

- Rocket.Chat Server Version: 3.5.4 and 3.0.7
- Rocket.Chat App Version: 4.10.0
- OS Version: iOS

### Steps to reproduce:

1. you can add more item like button on any screen using ScrollView or flat list try to focus input to open the keyboard and when you scroll the view cut the bottom or top and user cannot able to scroll

### Expected behavior:

ScrollView Or FlatList Scroll Smoothly without cutting or the Ui.

### Actual behavior:

Scrollview and FlatList not scrolling to bottom on ios when keyboard open

**Comment by diegolmello** [comment]
Please, follow the template.

**Comment by shaheem-khanzada** [comment]
@diegolmello added
