### ISSUE TITLE
IOS application (single-server) crashes after tapping a new push notification

### ISSUE THREAD

**Issue by ntrsboy** [RocketChat/Rocket.Chat.ReactNative#2479]
### Description:

IOS application (single-server) crashes after tapping a new push notification

### Environment Information:

- Rocket.Chat Server Version: 3.6.2
- Rocket.Chat App Version: iOS 4.10.0 (single-server)
- Device Name: iPhone
- OS Version: 14.0

### Steps to reproduce:

1. Receive a push notification from a new message in a channel or a private message while the app is not in the foreground.
2. Tap the notification

### Expected behavior:

I expect the app to not crash.

### Actual behavior:

Application crashes.

![IMG_9404](https://user-images.githubusercontent.com/71639700/93757590-ab0ede80-fbcc-11ea-92c4-b2c3a687477e.PNG)

![IMG_9405](https://user-images.githubusercontent.com/71639700/93757613-b5c97380-fbcc-11ea-8ef0-65220d10568e.PNG)

![IMG_9406](https://user-images.githubusercontent.com/71639700/93757643-c11c9f00-fbcc-11ea-923d-e28a0c1ee797.PNG)

### Additional context:

Built with Xcode 12.0 (12A7209), ran on IOS 14.0. Sometimes, maybe 2-3 out of every 10 push notifications do not crash the app. This was not happening on the previous IOS version and the previous Xcode version, so it may be related to the new IOS or Xcode.

**Comment by aprocom** [comment]
Hi! Have any new about this problem? We have the same problem..

**Comment by gadiatskyi** [comment]
Hi, I have the same problem. Is it possible to vote for prio here?

**Comment by gadiatskyi** [comment]
Hi! Any news on this topic? Probably, this could be a fix? https://github.com/wix/react-native-notifications/pull/625
Unfortunately, it is not merged to react-native-notifications version 2.1.7 which is used in rocket.chat.  Is there any plan to use react-native-notifications of version 3.3.4, which has this fix?

**Comment by diegolmello** [comment]
We updated single-server branch yesterday and tested all use cases.
We followed [our whitelabel docs](https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps) and everything worked fine.
