### ISSUE TITLE
IOS application (single-server) always logout

### ISSUE THREAD

**Issue by ferkawi** [RocketChat/Rocket.Chat.ReactNative#2482]
### Description:

All my clients who upgraded to ios14, logged in, used the application and then put it in the background, were logged out

### Environment Information:

- Rocket.Chat Server Version: 3.4.2
- Rocket.Chat App Version: 4.8.0
- Device Name: iphone
- OS Version: 14

### Steps to reproduce:

1. Go to Rocket Chat
2. Log in
3. Use the App normally
4. Put the App in the Background

### Expected behavior:

Go back and continue logged in

### Actual behavior:

The application self-logged out

**Comment by devZer0** [comment]
did they need to re-enter the workspace url, too ?

**Comment by ferkawi** [comment]
No they don´t need it! After speaking with my Boss, was a human error... some Problems with username´s. So I´ll close this thread, thank you anyways
