### ISSUE TITLE
[BUG] HTTP basic auth broken in android Rocket.Chat Experimental v4.11.0 (20594)

### ISSUE THREAD

**Issue by slimlv** [RocketChat/Rocket.Chat.ReactNative#2489]
### Description:
in latest android Rocket.Chat Experimental v4.11.0 (20594) HTTP basic auth is broken.
HTTP  basic auth was introduced in https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1753
Looks like  this brings regression https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1936
there is a log of rocket chat server protected by basic auth (username is "user"):
`10.10.10.2 https://chat.XXX.co - [24/Sep/2020:21:23:27 +0300] "GET /api/info HTTP/1.1" 401 392 "-" "okhttp/3.12.1" "-"`
`10.10.10.2 https://chat.XXX.co user [24/Sep/2020:21:23:27 +0300] "GET /websocket HTTP/1.1" 101 265 "-" "RC Mobile; android 10; v4.11.0 (20594)" "-"`
The first request failed as no user/password passed by the app followed by "This is not Rocket.Chat server" message of the app.
### Environment Information:

    Rocket.Chat Server Version: 2.4.12
    Rocket.Chat App Version: 4.11.0 (20594)
    Device Name: Android
    OS Version: 10

### Steps to reproduce:
  use workspaec URI with base auth like
  https://user:pass@chat.XXX.co

### Expected behavior:
  rocket chat login prompt
### Actual behavior:
  "This is not Rocket.Chat server" error, no username passed to the "GET /api/info" request

**Comment by djorkaeffalexandre** [comment]
Thanks for your report @slimlv! Fix on the way :)
