### ISSUE TITLE
[single-server] Android build failed

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.ReactNative#2492]
### Description:

During build `single-server` for Android an error occured

```
Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [org.jitsi.react:jitsi-meet-sdk:2.10.0] /root/.gradle/caches/transforms-2/files-2.1/2380349aa37c21db01753313dbadf084/jitsi-meet-sdk-2.10.0/AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="org.jitsi.meet.sdk" to force usage (may lead to runtime failures)
```

### Environment Information:

- Rocket.Chat Server Version: 3.0.12
- Rocket.Chat App Version: 4.10.0 (single-server)
- Device Name: Samsung Galaxy A20e
- OS Version: 9.0

### Steps to reproduce:

1. Try to build single server Android app

### Expected behavior:

Build success

### Actual behavior:

Build finished error

**Comment by prajyot-naik** [comment]
change minSdkVersion = 21 to minSdkVersion = 23 inside build.gradle of the project. This should fix the issue.

**Comment by diegolmello** [comment]
Fixed here https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/709c7aaaea5815fcd60579c6d9390be0baf5a229
We'll update `single-server` branch in a couple of weeks, after 4.11 is released.
