### ISSUE TITLE
Markdown - code is not visible as long as there is no 3x ` at the end

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.ReactNative#2495]
### Description:

When \``` markdown code is used in the message then mobile app displays it only when is wrapped properly between \``` and \```.
Otherwise app shows empty code container.

### Environment Information:

- Rocket.Chat Server Version: (3.6.3, 1.0.3)
- Rocket.Chat App Version: Android, iOS, all versions
- Device Name: Android
- OS Version: not relevant

### Steps to reproduce:

1. Write message: "\```this is my code" and send
2. Code container shows up but without content
3. Write next message: "\```this is my code\```" and send
4. All works

### Expected behavior:

Display markdown code correctly

### Actual behavior:

It's broken

**Comment by piotrkochan** [comment]
may be related to #1778 somehow

**Comment by diegolmello** [comment]
Duplicated
