### ISSUE TITLE
The icons are superimposed on the name.

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#2497]
Hi friends, in the experimental version the icons are superimposed when the name is long.  This happens after putting the directory button at the top.
![Screenshot_20200925-172107_RocketChat Experimental.jpg](https://user-images.githubusercontent.com/35962168/94317789-fcb0c380-ff54-11ea-87c7-19ed76bf2dd7.jpg)

**Comment by aenonGit** [comment]
the PR 2503 should fix this
