### ISSUE TITLE
[ANDROID] Can no longer connect to intranet rocketchat (HTTP)

### ISSUE THREAD

**Issue by LeeThompson** [RocketChat/Rocket.Chat.ReactNative#2500]
### Description:

When attempting to connect to our intranet rocketchat server (which uses http not https) the error message appears:

"OOPS!

CLEARTEXT communication to (intranet address) not permited by network security policy.""

### Environment Information:

- Rocket.Chat Server Version: 3.6.3
- Rocket.Chat App Version: 4.11.0.2136
- Device Name: Samsung Galaxy S20
- OS Version: Android 10?

### Steps to reproduce:

1. Connect to http intranet server
2. Or rather, don't

### Expected behavior:

It to connect.

### Actual behavior:

It doesn't connect.

### Additional context:

This is due to a recent update.  If it's set by "network security policy" please let us know where that is set.

**UPDATE:** I set up a quick & dirty IIS reverse proxy with a self signed certificate.  Installed it on the Android device.  Tested with Chrome on the device (showed a lock in the address bar), now RocketChat says "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."  Which is crap, the CA is a Windows Domain Controller on the intranet.

So you guys have now turned our intranet chat system useless for Android devices.

**Comment by diegolmello** [comment]
@LeeThompson We're following [Android's security best practices](https://developer.android.com/topic/security/best-practices). We won't rollback, because we've been working on increasing the security of our app.
You can open an issue on the main repo or on the forums if you need help setting up SSL.
