### ISSUE TITLE
[RangeError: Maximum call stack size exceeded.]

### ISSUE THREAD

**Issue by prajyot-naik** [RocketChat/Rocket.Chat.ReactNative#2501]
### Description:

Build is successful and also the app is getting installed, but when I enter the username and password and click on the login button. I get <b>"[Mon Sep 28 2020 14:33:10.170]  ERROR    [RangeError: Maximum call stack size exceeded.]"</b> I get this inside the server terminal. There is no message or prompt on the app side.

### Environment Information:

- Rocket.Chat Server Version: 2.4.11
- Rocket.Chat App Version: 4.10.0 (single-server)
- Device Name: Nokia 5.1 plus 
- OS Version: Android 10

### Steps to reproduce:

1. Click on login button
2. Enter username and password
3. Click the login button

### Expected behavior:

Login should happen.

### Actual behavior:

Nothing happens

**Comment by diegolmello** [comment]
Does it happen on develop branch?
We need more info than that to help you.

**Comment by prajyot-naik** [comment]
No it doesn't happen on develop branch. I am able to login using the develop branch. 

See I get the first screen, where the server url is displayed i.e set by me inside app.json. Then when I click on login button, the second screen opens up. I enter the username and password and then click on login button but nothing happens. No message is shown on the app side. But when I check the terminal it shows <b>"ERROR [RangeError: Maximum call stack size exceeded.]"</b>

**Comment by diegolmello** [comment]
We updated single-server yesterday and we tested everything.
Pull changes and try again.

**Comment by RaviGaruda** [comment]
@prajyot-naik have your issue solved? i similar issue got in version 4.14.0.1
