### ISSUE TITLE
[Jitsi] Mobile application ignores Enable room name hash server option

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2505]
### Description:

https://github.com/RocketChat/Rocket.Chat/pull/17481 introduced new feature in Rocket Chat that enable simple Jitsi room names (not hashed abracadabra) but RC RN mobile app not support that and create room name in old fashion.
I think, that RC RN mobile app just ignores **Enable room name hash** option.
@diegolmello @djorkaeffalexandre please add support of that setting to RC RN mobile app, because if admin enable that feature (Turn Off **Enable room name hash** which is enabled by default to backward compatibility) Web version and Mobile version will create different rooms and users will not meet each other.

### Environment Information:

- Rocket.Chat Server Version: 3.6.3
- Rocket.Chat App Version: 4.10
- Device Name: iPhone 8
- OS Version: iOS 14

### Steps to reproduce:

1. Admin UI and Turn Off **Enable room name hash** setting
2. Create call in private group or DM in Web version
3. Click on button Click to Join in Mobile version - you create another Jitsi room with old style name (hashed style starting with RC Deployment ID)

### Expected behavior:

RC RN mobile app use same Jitsi room name as Web version with **Enable room name hash** turned off setting

### Actual behavior:

Mobile application doesn't support **Enable room name hash**  option

### Additional context:

No.

**Comment by djorkaeffalexandre** [comment]
Thanks for your report @ankar84.
Let's do this ASAP, if someone from community wants to pick this, is just to copy the exact logic of web client. :)
Thanks.

**Comment by imrishabh18** [comment]
@djorkaeffalexandre I will take this  🙂

**Comment by clpacheco90** [comment]
I'm getting the same issue.
rocket chat version:3.7.1
app:4.11.0.2137

**Comment by cmdares** [comment]
I'm getting the same issue.

**Comment by ankar84** [comment]
@djorkaeffalexandre @imrishabh18 @diegolmello Hello, guys!
Can fix for that issue be included in 4.13 version?

**Comment by skug67** [comment]
Seems to still be a problem in 4.13.  Definitely interferes w/making Rocket/Jitsi interoperable on mobile devices.

**Comment by ankar84** [comment]
@djorkaeffalexandre @diegolmello hey guys!
That issue looks like easy to fix but no one from community took it. So, please fix it by yourself.
Thanks!
