### ISSUE TITLE
Gitlab url hardcoded

### ISSUE THREAD

**Issue by dmavrin** [RocketChat/Rocket.Chat.ReactNative#251]
- Your Rocket.Chat.Android app version: latest
- Your Rocket.Chat server version: 0.62.2

Gitlab OAuth is limited only to gitlab.com, becouse url is hardcoded (https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/LoginView.js#L109)

Because of my limited knowledge in react-native (and JS), I wasn't able to fixed this issue.

On server add action, server returns all settings. Among these settings, there is one like this:
```
{
"_id":"API_Gitlab_URL",
"value":"https://gitlab.example.com/",
...
}
```

Could someone please look into this and implements different urls for gitlab oauth?

Thanks.

**Comment by ggazzo** [comment]
hey @dmavrin thanks for writing... sure we will fix it :)

**Comment by mmnaseri** [comment]
Any updates? I'm having the exact same problem.

**Comment by lolimay** [comment]
> Any updates? I'm having the exact same problem.

Currently Working on this :)
