### ISSUE TITLE
[Bug] System messages lift channels up in Room List if sorting by activity despite they are disabled in system or channel level

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2518]
### Description:
System messages lift channels up in in Room list Mobile application if sorting by activity despite they are disabled in system and channel level

[Here](https://github.com/RocketChat/Rocket.Chat/issues/16931#issuecomment-651740101) @rodrigok announced great improvement in my opinion

> only update the room's activity when the system message is visible, so if you configure to hide the system message it will not update the room and it will not move up in your list.

And I see in web and desktop version that it's true
But not in Mobile application, even 4.11

### Environment Information:

- Rocket.Chat Server Version: 3.6.3
- Rocket.Chat App Version: 4.11.0.20775
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 10

### Steps to reproduce:

1. Hide system messages (join\leave room) on system level or\and channel level
2. Set Room List sorting by activity
3. If someone join or leave channel with no new messages - it will lift up in Room list. Without system message even appearing on screen

### Expected behavior:

Like web version - if user don't see system message - silent chat shouldn't lift up in Room list sorted by activity

### Actual behavior:

Silent chats appears in up of Room List as if new messages there.
It's true for default read only channels for example.

### Additional context:

No

**Comment by diegolmello** [comment]
Can you reproduce it on 4.12?
Can you reproduce it on web client?

**Comment by ankar84** [comment]
> Can you reproduce it on web client?

As I stated in first message, web version fixed since some version. Maybe 3.6 or recent 3.7. and that really awesome.




> Can you reproduce it on 4.12?

I just checked on 4.12 and it looks like issue fixed in that version. I need more time to tell you for sure.

**Comment by ankar84** [comment]
Did some manual tests and yes, 4.12 has a fix for that issue
