### ISSUE TITLE
Rocket.chat mobile application does not mark channels as read

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat.ReactNative#2519]
### Description:

Recently we've had a constant issue that on both iOS and Android mobile app does not mark any new unread channels as read after visiting them in the mobile client. The situation gets fixed either by closing the app from the history, or clearing its local cache.

### Environment Information:

- Rocket.Chat Server Version: 3.6.3
- Rocket.Chat App Version: 4.11 and 4.10
- Device Name: Android and iOS
- OS Version: latest

### Steps to reproduce:

1. Go to RC app and sort messages by activity and unread on top.
2. Click any new unread channels under unread list.
3. Go back to channels view
4. Also try marking unread channel as read

### Expected behavior:

A read channel should be removed from the list of unread channels

### Actual behavior:

A read channel stays under unread channels list

### Additional context:

We have noticed this issue with two separate RC server instances / workspaces. Both of them have push notifications disabled, so it might be related to late changes to notification handling on the mobile client.

Other possible triggering factor could be changes in the app to cache more data locally on the client end.

**Comment by diegolmello** [comment]
It might be related to new threads support.
We're going to implement it on 4.12.0.

**Comment by ankar84** [comment]
> It might be related to new threads support.
> We're going to implement it on 4.12.0.
> 
> I'm marking as a bug anyway, because I might be wrong and it's something else.

I think you rigth. I see this with new threads on 3.6.3 server

**Comment by bestog** [comment]
We have the Same Problem.

**Comment by zaphod534** [comment]
Same problem here: 

- Server version: 3.0.10

- App version: 4.11

The only way to mark a channel as read is to close and reopen app.

**Comment by zaphod534** [comment]
Update:
I notice that when a new message is sent on a channel, it is marked as unread, but it not appears in unread group. If I toggle "Unread on top" option twice the channel correctly goes in the unread list.

**Comment by Gummikavalier** [comment]
Hi! This issue seems still to be active in 4.12; read messages still stay under `Unread` header. I can see that the font loses bolding (not very easy to spot with this font), but they don't clean up immediately. Possibly when checking new messages few minutes later they have moved away from the Unread.

**Comment by diegolmello** [comment]
@Gummikavalier Can you post a gif/video?

**Comment by zdumitru** [comment]
@diegolmello Yes, I also confirm that behaviour. Tested on 4.12.0.21382 version.

![Screenshot_20201109-130150_RocketChat Experimental](https://user-images.githubusercontent.com/11751017/98539392-865deb80-228c-11eb-8b14-9590c42b4e98.jpg)

If you look on the screen, the top channel has been read, but still stays in the "Unread" section. Even though it is not bold anymore. This is a bug and the issue should be reopened. Or a new issue opened.

**Comment by Gummikavalier** [comment]
@diegolmello Yes, exactly how @zdumitru has it in his pic. The message does get marked as read, but it just doesn't disappear from under the Unread.

**Comment by Gummikavalier** [comment]
Confirmed working, thanks a lot! :+1:

**Comment by bestog** [comment]
Good Job. Thank you. :)
