### ISSUE TITLE
the mobile app doesn't work login on iphone7

### ISSUE THREAD

**Issue by webstar1987923** [RocketChat/Rocket.Chat.ReactNative#2525]
## My Setup

- Operating System: iOS 13.7
- App Version: 4.10.0.310
- Installation type: 

- [x] I have tested with the latest version
- [ ] I can simulate the issue easily

## Description

I cannot join workspace

**Comment by diegolmello** [comment]
@webstar1987923 Can you add detailed info or change your description to follow our issue template?
Thanks.

**Comment by wolfcreative** [comment]
After entering your username and password, the app freezes. You can't open settings @diegolmello
