### ISSUE TITLE
Bundle shows white screen / Integrate in existing app

### ISSUE THREAD

**Issue by cremfert** [RocketChat/Rocket.Chat.ReactNative#2526]
### Description:

Hi there, I tried to integrate the JSBundle generated by metro to load with RCT View Controller in my existing native App. My aim is to integrate Rocket.Chat into one of my employee apps, which also provides other functions beside chatting via Rocket.Chat. However, I do not succeed. I copied all the Pod instructions to my XCode project, did ```pod install``` and made it build. I also set environment variables for WatermelonDB (and the appgroups), so that database could initialize and also called Firebase initialization. I get the same messages in XCode console as when I run the single-server-build, but I only see a white screen. Is there any chance to get Rocket.Chat to be integrated in another, existing native app? React Native describes it as possible here (https://reactnative.dev/docs/integration-with-existing-apps), but I don't have luck with Rocket.Chat. Could you help me?

### Environment Information:

- Rocket.Chat Server Version: 3.6.3
- Rocket.Chat App Version: develop branch / but also with stable branch (4.10)
- Device Name: iOS Simulator
- OS Version: 13.7

### Steps to reproduce:

1. Create a new XCode project
2. Import pod file entries from Rocket.Chat.ReactNative and do ```pod install```
3. Add AppGroup in XCode
4. Import React Native Headers and Framework
5. Put JSBundle in main project folder
6. Load bundle as mentioned here: https://reactnative.dev/docs/integration-with-existing-apps

### Expected behavior:

Rocket.Chat should show up in a new ViewController

### Actual behavior:

New ViewController comes up, but keeps blank. No error messages in XCode console

### Additional context:

Does also not work when loading directly from metro bundler - same behaviour (ATS is configured correctly).

This way would enable people to integrate Rocket.Chat into existing apps and this would be really cool!

**Comment by diegolmello** [comment]
In theory, it's possible, but we never did it.

**Comment by cremfert** [comment]
I will try to work on this further, but do you have any idea, why nothing happens or can give me a tip on how to debug? Even if I put a console.log message the main function, I cannot see it in the Xcode console. This makes it really hard to make a step forward.

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md#how-to-inspect-the-app

**Comment by cremfert** [comment]
Thanks, I will try that. Hopefully, it’ll brings some insights. I will share my results.

**Comment by diegolmello** [comment]
Cool, I'm closing since it's not really an issue.
Feel free to continue the discussion and we'll try to help you.
Thanks!

**Comment by cremfert** [comment]
Hi @diegolmello 
I'm still working on this - unfortunately, as soon as I try to integrate the Pods to my custom project to allow the integration of the RC RN bundle, it deletes some of the Pods, as they are not listed in the Podfile. When I copy the office Podfile of RC RN to my project, as well as the Pods dir, and run ```pod install``` it says:
```
Downloading dependencies
Removing Firebase
Removing FirebaseAnalytics
Removing FirebaseCore
Removing FirebaseCoreDiagnostics
Removing FirebaseCrashlytics
Removing FirebaseInstallations
Removing GoogleAppMeasurement
Removing GoogleDataTransport
Removing GoogleDataTransportCCTSupport
Removing GoogleUtilities
Removing JitsiMeetSDK
Removing MMKV
Removing MMKVCore
Removing PromisesObjC
Removing SDWebImage
Removing SDWebImageWebPCoder
Removing TOCropViewController
Removing libwebp
Removing nanopb
Generating Pods project
Integrating client project
Pod installation complete! There are 71 dependencies from the Podfile and 62 total pods installed.
```
When I now start to run the app, it says "Missing MMKV.h" as this Pod is removed. Looks like the Podfile of RC RN is not complete, otherwise I would expect ```pod install``to install all dependencies.

Could you have a look on this and help me here?
Thanks a lot and best regards!

**Comment by DiamoandDog** [comment]
> Hi @diegolmello
> I'm still working on this - unfortunately, as soon as I try to integrate the Pods to my custom project to allow the integration of the RC RN bundle, it deletes some of the Pods, as they are not listed in the Podfile. When I copy the office Podfile of RC RN to my project, as well as the Pods dir, and run `pod install` it says:
> 
> ```
> Downloading dependencies
> Removing Firebase
> Removing FirebaseAnalytics
> Removing FirebaseCore
> Removing FirebaseCoreDiagnostics
> Removing FirebaseCrashlytics
> Removing FirebaseInstallations
> Removing GoogleAppMeasurement
> Removing GoogleDataTransport
> Removing GoogleDataTransportCCTSupport
> Removing GoogleUtilities
> Removing JitsiMeetSDK
> Removing MMKV
> Removing MMKVCore
> Removing PromisesObjC
> Removing SDWebImage
> Removing SDWebImageWebPCoder
> Removing TOCropViewController
> Removing libwebp
> Removing nanopb
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 71 dependencies from the Podfile and 62 total pods installed.
> ```
> 
> When I now start to run the app, it says "Missing MMKV.h" as this Pod is removed. Looks like the Podfile of RC RN is not complete, otherwise I would expect ```pod install``to install all dependencies.
> 
> Could you have a look on this and help me here?
> Thanks a lot and best regards!

Have you successfully achieved this goal, can you provide some suggestions or clarifications? Thanks so much！

**Comment by cremfert** [comment]
Hi @DiamoandDog,

no, unfortunately, I didn't make any progress. I was able to integrate React Native, set up a Dev Server to deliver the app, but I always only see a white screen without any error message. I tried to strip out the share extension and all other stuff which is not related to the "core", but it didn't help. I gave up in the end.
