### ISSUE TITLE
EmojiKeyboard cannot work properly after the fresh install

### ISSUE THREAD

**Issue by Godman-quake** [RocketChat/Rocket.Chat.ReactNative#2528]
# Description:

The EmojiKeyboard cannot work properly after the fresh install on Android 5/7/9, but, when I close the app by pressing the BackButton and re-enter the app, the EmojiKeyboard is working fine.
What's the problem?

### Environment Information:

- Rocket.Chat Server Version: 1.4.0
- Rocket.Chat App Version: 2.+
- Device Name: 
- OS Version:

**Comment by diegolmello** [comment]
Please follow our template.
Also, we don't have version 2.
