### ISSUE TITLE
[Improvement] Mention suggestions on Real Name like in Web version

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2529]
### Description:

Web version since some 3 server version improved mention suggestions significantly. One of my favorite improvement is now suggestions works not only on Username, but on Real Name too.
Please add that functionality to mobile application.

### Environment Information:

- Rocket.Chat Server Version: 3.6.3
- Rocket.Chat App Version: 4.11
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 9

### Steps to reproduce:

1. Try to mention user with his Real Name
2. Get nothing

### Expected behavior:

Suggestions on Real Name like in Web version

### Actual behavior:

Web version 
![image](https://user-images.githubusercontent.com/4023037/95283458-8e2d0900-0864-11eb-9987-80890547816f.png)
Mobile version (no suggestion)
![image](https://user-images.githubusercontent.com/4023037/95283668-03004300-0865-11eb-985a-ebdceded074b.png)

### Additional context:

My Username **KarlanAA**
My Real Name **Карлан Антон Андреевич**

**Comment by diegolmello** [comment]
Duplicated #1580
