### ISSUE TITLE
Periodically check for new messages

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat.ReactNative#253]
Rocket.Chat.Android app version: 1.1

Rocket.Chat server version: 0.62.1

Is there a way to get new messages without push notifications and manually check the apps ?

I'd like to avoid the use of Google services and I didn't find a way to periodically pull new messages.

Riot for Android do it with a warning about battery life :
https://matrix.org/docs/guides/faq.html#i-installed-riot-via-f-droid-why-is-it-draining-my-battery

I asked the same question on the Rocket.Chat.Android project but there is no plan for such a feature.
(https://github.com/RocketChat/Rocket.Chat.Android/issues/945)

Cheers

**Comment by diegolmello** [comment]
I think we could do this in the future, but right now we're just developing the main features.

**Comment by ggazzo** [comment]
@magicbelette actually we don't use push notifications to get new messages, we
 use just to show notifications and when you open your app we get using websockets/ddp... Maybe for now you should fork your code and remove the push code until we find a better way... Any question or problem feel free to ask :)
