### ISSUE TITLE
[BUG] App isn't showing message for PDF/file uploads

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#2531]
### Environment Information:

- Rocket.Chat Server Version: any
- Rocket.Chat App Version: 4.11.0
- Device Name: any
- OS Version: any

### Steps to reproduce:

1. Upload a pdf with a message
2. It's not going to show the message on the app, but it'll show on the web client

#### Mobile
<img src="https://user-images.githubusercontent.com/804994/95380760-99605300-08bd-11eb-8de0-01477c0814d7.png" width="350" />

#### Web client
![Screen Shot 2020-10-07 at 16 55 17](https://user-images.githubusercontent.com/804994/95381127-1390d780-08be-11eb-8608-b054b5c81266.png)

### Expected behavior:

Mobile client should show the message as well.

### Actual behavior:

Mobile doesn't show the message.

**Comment by saket-m0** [comment]
Heyy, I am new to opensource and would like to try on work on it.
I have setup the codebase in my local system already.

**Comment by diegolmello** [comment]
@saket-m0 go for it

**Comment by saket-m0** [comment]
Hello, I have added a pull request. The pdfs now show messages. I ran the tests locally with 'yarn test -u' and the tests were successful.

On the pull request it is showing 2 check have been failed. `iOS Detox / detox-build (pull_request)` and `ci/circleci: lint-testunit` have been failed and I dont know why. Please help me.

**Comment by refactor-droidyy** [comment]
@saket-m0 are you working on this?

**Comment by saket-m0** [comment]
> @saket-m0 are you working on this?
> 

Yes. I have already opened a PR and am waiting for approval.

**Comment by dudanogueira** [comment]
Can we close this issue? Looks like it was fixed already.
