### ISSUE TITLE
Admin Panel is unreached

### ISSUE THREAD

**Issue by johnypeterson** [RocketChat/Rocket.Chat.ReactNative#2532]
### Description:

When trying to open the Admin Panel from an Android device, it switches to the weird-looking interface which resembles the desktop version. And it is impossible to do anything as admin.

### Environment Information:

- Rocket.Chat Server Version: 3.7.0
- Rocket.Chat App Version: 4.11.0
- OS Version: Android 9, 10

### Steps to reproduce:

1. Log into your server via an Android app (being an Admin on this server).
2. Open the left-side menu.
3. Сlick on Admin Panel

### Expected behavior:

The application should open the appropriate Admin panel and the user should be able to take actions as an admin

### Actual behavior:

The application opens the interface of the desktop version and moreover, clicking on any menu item sends you to the search field. The user is unable to take action as an admin.

**Comment by tandamadril** [comment]
I have noticed such behavior since version 3.6.0
Is this going to be fixed? This is very critical for us

**Comment by diegolmello** [comment]
@ggazzo Are you aware of this issue?
Should we transfer to the server repo?

**Comment by IhorNykyha** [comment]
The same behavior. @diegolmello Do you have any information about that?

**Comment by diegolmello** [comment]
We use the embed webview version of admin on mobile.
That's kind of junky, but it works for me.
Drawer doesn't work like usual mobile drawer, so you have to tap on the backdrop to close it.
Open an issue on the server repo if you still can't use it.
Thanks.
