### ISSUE TITLE
Version in F-Droid cannot connect to server

### ISSUE THREAD

**Issue by mirabilos** [RocketChat/Rocket.Chat.ReactNative#2539]
### Description:

I have a problem connecting to my employer’s server using the latest version shipped in F-Droid, that is, [3.5.1](https://f-droid.org/en/packages/chat.rocket.android/).

Wanting to report that as an issue here, I see that you changed repositories. So it’s natural that the F-Droid autobuilder doesn’t pick up the new versions.

Please ensure that the version in F-Droid is up-to-date again by fixing the [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/chat.rocket.android.yml) and ensuring it builds, works and gets shipped.

### Environment Information:

- Rocket.Chat Server Version: I have no idea, but I can ask the company admins if needed
- Rocket.Chat App Version: 3.5.1
- Device Name: Galaxy Xcover 4s
- OS Version: 10

### Steps to reproduce:

1. enter the server name
2. hit the connect button
3. see it just pulse dots

### Expected behavior:

login

### Actual behavior:

just dots pulse, but I can add a screencast if needed

### Additional context:

See above.

**Comment by diegolmello** [comment]
Waiting review https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7516

**Comment by mirabilos** [comment]
Aaaand fixed.
