### ISSUE TITLE
[New] Add all available in web version channel actions to mobile application

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2545]
### Description:

I can't find how to remove user from channel in mobile application, i see only mute/unmute in long tap menu.

### Environment Information:

- Rocket.Chat Server Version: 3.6.3
- Rocket.Chat App Version: 4.11
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 10

### Steps to reproduce:

1. Go to chat
2. Open chat members list
3. Long tap on user
4. No remove from chat menu item

### Expected behavior:

Ability to remove user from chat on mobile application

### Actual behavior:

![IMG_20201011_111317](https://user-images.githubusercontent.com/4023037/95670233-d0cb4a00-0bb2-11eb-9137-c223b96e27a4.jpg)

### Additional context:

Please consider to add all available in web version chat actions
![image](https://user-images.githubusercontent.com/4023037/95710490-7e009980-0c69-11eb-971e-df12bf8b5b5d.png)
Green - Available in RCRN application
Red - Unavailable in RCRN application

**Comment by diegolmello** [comment]
We'll do it soon.
Thanks.

**Comment by ankar84** [comment]
Fix in https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2644
