### ISSUE TITLE
Changing password in unlock with password should verify the owner first

### ISSUE THREAD

**Issue by refactor-droidyy** [RocketChat/Rocket.Chat.ReactNative#2561]
### Description:
While changing a passcode it eventually prompts to enter the new passcode without verifying that user

### Environment Information:

- Rocket.Chat Server Version: 3.7.0
- Rocket.Chat App Version: 4.11.0
- Device Name: POCO X2
- OS Version: Android 10

### Steps to reproduce:

1.  Navigate to Setting Section -> Screen Lock
2.  Now change the passcode you can see there is no password verification

### Expected behaviour:

After changing 

The app should first verify that its the owner who is changing the passcode.

### Actual behaviour:
No such verification is done instead it allows to enter the new passcode

I am attaching a gif for the same.
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/44283521/96082275-8d394e80-0ed8-11eb-92cd-0437ad99f6cb.gif)

**Comment by refactor-droidyy** [comment]
@diegolmello is this a valid issue?

**Comment by diegolmello** [comment]
I'm not sure I got it.
If you're talking about asking the current password before the new one, I agree.

**Comment by refactor-droidyy** [comment]
> I'm not sure I got it.
> If you're talking about asking the current password before the new one, I agree.

@diegolmello yes you are right.

**Comment by saket-m0** [comment]
Hello, Can I work on this?

**Comment by saket-m0** [comment]
I have opened a PR fixing this issue. Please review it.
