### ISSUE TITLE
Notificações antigas

### ISSUE THREAD

**Issue by italossousa** [RocketChat/Rocket.Chat.ReactNative#2563]
Boa tarde, 

Uso esse sistema na empresa que eu faço parte, usamos no dia a dia o Rocket.Chat via PC e durante a noite no celular.

Sempre que lemos alguma mensagem no PC, o celular ainda fica alertando como uma nova mensagem em formas de notificações no celular e de momentos em momentos o app do celular apresenta todos os alertas de todas as mensagens e conversas que fizemos durante o dia como se fossem novas mensagens.

Alguém já passou por isso ?

Att,
Ítalo Sousa

**Comment by aleadco** [comment]
We have this same problem, and it really is a big problem in user experience. The flow of information in our entity is similar to the one you propose.
This problem directly influences the push counter where you only have a small limit of 1000 push per month.

**Comment by diegolmello** [comment]
This PR might fix it https://github.com/RocketChat/Rocket.Chat/pull/19061

> This problem directly influences the push counter where you only have a small limit of 1000 push per month.

Not really. Push notifications are sent immediately, but the device might not be showing them because they are received as not priority.

**Comment by aleadco** [comment]
Hi @diegolmello I understand that the push is sent immediately but I consider that if we are working on the web, or in the desktop applications those push should not be sent unless the system detects that the user is not active in the browser or in the desktop applications.
I put a practical example: I am working an 8 hour workday where I do not have my mobile connected to the network.
If the system detects that I am active and reading the messages, I do not think it is necessary for the push to be sent to my mobile. Specifically, the big problem is that if I have already seen those messages, you must find a way to cancel the push and not accumulate in a queue waiting for the mobile client to connect to be sent.
I have been reading the PR that supposes the solution and according to what it raises I do not think that it will solve the problem.
Stay tuned to any comments. Greetings

**Comment by diegolmello** [comment]
@aleadco Understood. That's not something to be addressed on mobile, but to the sender. Can you search on the server repo? I think that's a common question.

**Comment by aleadco** [comment]
@diegolmello I agree, I think it is a more chord problem on the server side

**Comment by diegolmello** [comment]
We just changed our push gateway to send high priority push notifications.
Can you guys check how it behaves in the next days and reach me back in any case?

**Comment by aleadco** [comment]
@diegolmello Ok, I will be aware of the behavior, I will comment in the next few hours

**Comment by aleadco** [comment]
@diegolmello the changes made offer a better user experience in relation to this topic.  I have done some tests and it is very positive.  For my part, this ticket can be closed and if necessary it can be reopened.  A greeting.

**Comment by diegolmello** [comment]
Thanks for testing. Let us know about anything odd on push notifications.
