### ISSUE TITLE
TypeError: Cannot read property 'FDROID_BUILD' of null, js engine: hermes

### ISSUE THREAD

**Issue by huytx0909** [RocketChat/Rocket.Chat.ReactNative#2565]
### Environment Information:

- Rocket.Chat Server Version: 3.7.0
- Rocket.Chat App Version: 4.11.0
- Device Name: Samsung A50
- OS Version: Linux Ubuntu 18.04

### Steps to reproduce:
I followed the guide: https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps, and successfully built the iOS version of the app.
- For the Android build: 
1. I changed the icons and added the `google-services.json` file. 
2. when I run `yarn` and `yarn android`, the following issues come up: 
`TypeError: Cannot read property 'FDROID_BUILD' of null, js engine: hermes`
`TypeError: Cannot read property 'default' of undefined, js engine: hermes`

### Actual behavior:
This is a picture of what showed up: 
On the console: ![image](https://user-images.githubusercontent.com/29868399/96211756-6003a380-0f9f-11eb-8581-8a4d2dcad0a7.png)

On the device: 
![1602821650129](https://user-images.githubusercontent.com/29868399/96212388-f5536780-0fa0-11eb-84d1-b442183a4641.JPEG)
![1602821650070](https://user-images.githubusercontent.com/29868399/96212389-f6849480-0fa0-11eb-81bd-e9bce0e0be7c.JPEG)
![1602821650162](https://user-images.githubusercontent.com/29868399/96212390-f71d2b00-0fa0-11eb-9972-5bcd9d269cb1.JPEG)

### Expected behavior:
The app builds normally

**Comment by hadiidbouk** [comment]
I face the same error, I changed the import in the environment.js to this :

```
const RNConfigReader = require("react-native-config-reader");

export const isFDroidBuild = RNConfigReader.FDROID_BUILD;
```

Somehow the `react-native-config-reader` module isn't imported correctly.


However, the new update ruin the `single-server` branch

<img width="367" alt="Screen Shot 2020-10-16 at 2 58 33 PM" src="https://user-images.githubusercontent.com/19314956/96255796-2f803180-0fc0-11eb-963d-80d6548f7910.png">

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2548
