### ISSUE TITLE
Icons Not Showing in Mobile App

### ISSUE THREAD

**Issue by BitFlexFinTech** [RocketChat/Rocket.Chat.ReactNative#2569]
Hi Guys we've set up our server and customized it and the Icons for the rooms are showing on the web but are not loading on the Mobile App (see attached) 

MOBILE APP
![image](https://user-images.githubusercontent.com/68299707/96462584-02cd5380-1226-11eb-9fa1-8355285d7ea8.png)

WEB/DESKTOP APP
![image](https://user-images.githubusercontent.com/68299707/96462757-3dcf8700-1226-11eb-9c0e-d64afddb1eaa.jpeg)

**Comment by diegolmello** [comment]
Duplicated #2477
It's going to be fixed on #2504
