### ISSUE TITLE
Android high does not connect to the workspace

### ISSUE THREAD

**Issue by 0xss** [RocketChat/Rocket.Chat.ReactNative#2572]
### Environment Information:

- Rocket.Chat Server Version:3.6.2
- Rocket.Chat App Version:4.11.0.2137
- Device Name: Android
- OS Version: Android 9.0

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Connect work area

### Actual behavior:

cleartext communication to  111.118.20.111 not permitted by network security policy

### Additional context:
Maybe the Android version is too high, but it can be solved by code. Can you update it?

**Comment by diegolmello** [comment]
Hey, @0xss.
We started following [Android's security best practices](https://developer.android.com/topic/security/best-practices) of not accepting insecure connections recently (it was enforced on iOS already).
It will work on your browser, but it won't on your devices (iOS and Android).
You can read more about it [here](https://koz.io/android-m-and-the-war-on-cleartext-traffic/).

You have two options:
- configure HTTPS on your server
- whitelabel your app to support insecure insecure connections for your server: https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps
