### ISSUE TITLE
Exit video call when pull down the view

### ISSUE THREAD

**Issue by billypon** [RocketChat/Rocket.Chat.ReactNative#2574]
### Description:

I'm on video call via Jitsi, and I will exit the call after I pull down the view.
Can I pull down the view, back to Rocket channel and keep video call, so that I can send messages.

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.11.0
- Device Name: iPhone 7 Plus
- OS Version: 13.3.1

### Steps to reproduce:

1. Go to channel, and start Jitsi video call
2. Pull down the video call view

### Expected behavior:

Keep the call

### Actual behavior:

The video call will be end

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2178
