### ISSUE TITLE
Android App: Channel messages not displaying Name or Username?

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat.ReactNative#2577]
### Description:

Channel messages not displaying name or username?

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.11.0.2137
- Device Name: Samsung Galaxy Tablet
- OS Version: Unknown

### Steps to reproduce:

1. Open a channel
2. Look for channel notification messages such as "User has joined the channel" etc

### Expected behavior:

Name or Username is displayed, e.g. "Joe has joined the channel."

### Actual behavior:

No name or username is displayed:

![Screenshot_20201023-1014442](https://user-images.githubusercontent.com/1122344/96986641-a80d6200-156d-11eb-9bb2-17f2e8007ae0.jpg)

![Screenshot_20201023-102148](https://user-images.githubusercontent.com/1122344/96986666-ae034300-156d-11eb-8cae-f14f1fd1a897.jpg)

### Additional context:

Not at the moment.

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1689
