### ISSUE TITLE
[Feature] Continue playback of audio messages in the background

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2578]
### Description:

Currently the playback of an audio message stops whenever the app goes into the background. I.e. when listening to a 5 minute audio message, the app must stay in the foreground all the time.

Other apps like WhatsApp etc. continue the active playback even when the app is in the background, which allows the use of other apps during playback.

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.11.0
- Device Name: iPhone 11 Pro MAX
- OS Version: IOS 14.0.1

### Steps to reproduce:

1. Start the playback of an audio message
2. Put the app in the background
3. The playback of the audio message immediately stops

### Expected behavior:

The playback should continue in the background until the playback is complete or stopped back in the RC app.

### Actual behavior:

The playback stops as soon as the app goes into background.

**Comment by pratyaksh123** [comment]
Hey, I would like to Work on this!

**Comment by diegolmello** [comment]
Awesome. Go for it.

**Comment by pratyaksh123** [comment]
I have implemented this feature, but I am not able to commit my changes because of a failed pre-commit hook.

**Comment by diegolmello** [comment]
@pratyaksh123 this is our pre-commit hook https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/package.json#L16

You can run locally in order to check what's wrong with your changes.

**Comment by pratyaksh123** [comment]
This needs to be tested on iOS devices ( unfortunately I don't have a mac ), I have tested on android and it works.

**Comment by jacotec** [comment]
Closed with #3373
