### ISSUE TITLE
Push notifications arrive with the session closed.

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#2581]
Despite having the session closed in the experimental application, notifications are coming in.

![Screenshot_20201025-111626_GitHub.jpg](https://user-images.githubusercontent.com/35962168/97111205-e6ad3480-16b3-11eb-9b8e-5bab891696a7.jpg)

Server version: 3.7.1
![Screenshot_20201025-112142_RocketChat Experimental.jpg](https://user-images.githubusercontent.com/35962168/97111270-515e7000-16b4-11eb-88da-9fa8a6758bd4.jpg)

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1878
