### ISSUE TITLE
Whitelabeled app: push notification click handling

### ISSUE THREAD

**Issue by bradroid** [RocketChat/Rocket.Chat.ReactNative#2582]
### Description:

Clicking the push notification does not open conversation screen. Blank screen is opened instead.

### Environment Information:

- Rocket.Chat Server Version: don't know, I think it doesn't matter, if it's relevant I'll look it up
- Rocket.Chat App Version: it's a whitelabeled app created from single-server branch
- Device Name: Huawei P30
- OS Version: Android 10

### Steps to reproduce:

**Setup:**
Device A with app active with user John logged in, on direct messages screen with user Joe.
Device B with app inactive (killed) with user Joe logged in.

**Action:**
User John sends a direct message to user Joe.

**Observed:**
Device B recieves a push notification. When push notification is clicked, the blank screen is opened (see screenshot below).

### Expected behavior:

I would expect that clicked notification opens the conversation screen.

### Actual behavior:

Blank screen is opened.

![device-2020-10-25-182732](https://user-images.githubusercontent.com/11940407/97114337-40335480-16f0-11eb-9c89-e5766e4f0247.png)

### Additional context:

I created a whitelabeled Android application, from `single-server` branch, using your guide:
https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps

I configured push notifications and they are arriving to the device successfully.
To send a push notification, I installed the app on two different devices and I'm using two different users and I'm sending the messages between them.

I can see that AppLaunchHelper.getLaunchIntent is called but I don't see a logic there for handling the notification.

**Comment by diegolmello** [comment]
Make sure the server received from the push notification exists on local database here https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/sagas/deepLinking.js#L74

**Comment by bradroid** [comment]
@diegolmello 
I set my server in app.json as instructed in whitelabeling documentation. Is that enough for my server to be persisted in serversDB? I guess not, so where should I add code for adding my server to DB manually?

**Comment by ssachan** [comment]
same issue. Kindly address.

**Comment by acuconfdev** [comment]
I was trying to implement custom push notifications for RC react native app. I am using RC version 3.6.2 (snap).
I have created GCM account and re-built the app and also updated the server with GCM credentials (Not tried APN though as I was trying with android app). As per the documentation, I have disabled the rocketchat gateway too. But I could not get the notifications working for the app.
[ For testing purpose, I have enabled notifications for all messages too]. Am I missing any settings ? Could anybody please suggest ?

**Comment by ssachan** [comment]
Notifications seem to be working fine. 
But clicking on the message leads to a blank screen. It doesnt take you to the message directly.

**Comment by diegolmello** [comment]
@ssachan did you compare the existing server on local database against the server url returned by the push notification? https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2582#issuecomment-716493462

Make sure `Site_Url` setting from the server is correct.

@acuconfdev it's a misconfiguration on your end and unrelated to this issue.

**Comment by bradroid** [comment]
@diegolmello 

I compared the URL from
`Administration->General->Site URL` with the one defined in the `app.json` and figured out the issue.

One of the URLs had a slash (`/`) at the end while the other one didn't.

Thanks for the help!
