### ISSUE TITLE
Suffix not applied when using jitsi-meet in Android Client

### ISSUE THREAD

**Issue by theoneandonly-vector** [RocketChat/Rocket.Chat.ReactNative#2585]
### Environment Information:

- Rocket.Chat Server Version: 3.6.2
- Rocket.Chat App Version: 4.11.0.2137 (Playstore) + Experimental 4.11.0.20775
- Device Name: tried multiple ones
- OS Version: Android 9/10

### Steps to reproduce:

1. Select custom server in jitsi integration.
2. define prefix and suffix for meeting-rooms.
3. start new jitsi-meeting through "Videocall"
4. join through website on chrome
5. join using App on Android

### Expected behavior:

jitsi-integration runs on custom jitsi server.

### Actual behavior:

jitsi-integration creates a room with prefix and suffix when connecting using chrome.
jitsi-integration creates a room with prefix but no suffix when connecting using Android-App.

## 
Already deleted App & tried experimental Version. also tried on different device.

**Comment by djorkaeffalexandre** [comment]
Hey @theoneandonly-vector, this looks weird since we use a custom server on `https://open.rocket.chat` and it never redirects to `meet.jit.si`.
Can you provide more info about how jitsi is configured on your server?
A screenshot hiding sensitive info sounds good.
Thanks.

**Comment by theoneandonly-vector** [comment]
![image](https://user-images.githubusercontent.com/10380051/97308590-53b1fd00-1861-11eb-91cb-1e879c30a678.png)

**Comment by djorkaeffalexandre** [comment]
@theoneandonly-vector this looks right, can you provide me some test credentials to your server?
So I can debug it here.
Thanks.

https://open.rocket.chat/direct/djorkaeff.alexandre

**Comment by theoneandonly-vector** [comment]
your server is open for registration?


> @theoneandonly-vector this looks right, can you provide me some test credentials to your server?
> So I can debug it here.
> Thanks.
> 
> https://open.rocket.chat/direct/djorkaeff.alexandre

sent you an email

**Comment by djorkaeffalexandre** [comment]
@theoneandonly-vector yep, it's open to registration, you should just confirm your account on your email.
If you prefer, send me the test credentials to: `djorkaeff.alexandre@rocket.chat`

**Comment by djorkaeffalexandre** [comment]
We've found the cause of the problem, that is the `jitsi suffix` that was not implemented on mobile apps yet, so, when he tries to create a new call, it was pointing to a wrong url.

**Comment by ankar84** [comment]
Pretty much related to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2505
