### ISSUE TITLE
In IOS RocketChat/react-native-keyboard-input  "this.trackingViewRef.resetTracking is not a function."

### ISSUE THREAD

**Issue by JiangKzar** [RocketChat/Rocket.Chat.ReactNative#2588]
package.json

    ...
    "react-native-keyboard-input": "RocketChat/react-native-keyboard-input",
    "react-native-keyboard-tracking-view": "^5.7.0",
    ....

<img width="414" alt="스크린샷, 2020-10-28 오후 9 38 51" src="https://user-images.githubusercontent.com/56865797/97438602-f8b2ff80-195f-11eb-9093-61c340d9f42b.png">

**Comment by djorkaeffalexandre** [comment]
@JiangKzar check if this patch was applied
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/patches/react-native-keyboard-tracking-view%2B5.7.0.patch
