### ISSUE TITLE
Mobile Notifications No Longer Show Content Preview

### ISSUE THREAD

**Issue by MrSerth** [RocketChat/Rocket.Chat.ReactNative#2590]
After updating the mobile Rocket.Chat app from version 4.10 to version 4.11, notifications do not contain a content preview anymore. For every message (whether it is a private message or a channel message), the same text "You have a new message" is displayed.

### Description:

Mobile Notifications received with the newest version of the iOS app no longer show the content of the message. While some team members noticed the issue with the newest release, other team members with older versions of the mobile app (but the same server) still received the content preview. Once the update to 4.11 was installed, the content was no longer shown for all devices. Signing out and re-signing in didn't solve the problem, nor clearing the cache and even uninstalling and reinstalling the app didn't change anything.

### Environment Information:

- Rocket.Chat Server Version: 3.7.0
- Rocket.Chat App Version: 4.11.0.313
- Device Name: iPhone12,3 (iPhone 11 Pro)
- OS Version: iOS 14.1 (18A8395)

### Steps to reproduce:

1. Sign in to a server
2. Ensure to receive mobile notifications
3. Either close the app completely or bring it to the background
4. Get a message from a colleague

### Expected behavior:

I would like to see a preview of the message in the notification.

### Actual behavior:

The static text "You have a new message" is displayed for each new message. 

![IMG_5441](https://user-images.githubusercontent.com/7300329/97697737-b98fc600-1aa7-11eb-8664-0685bc30e39e.PNG)

### Additional context:

- The iOS device is unlocked and other notifications are shown as expected.
- Multiple iOS devices show the same behavior.

**Comment by djorkaeffalexandre** [comment]
Hey @MrSerth, does your server have "Push request content from server" enabled?
Is it possible to provide a test user on `https://open.rocket.chat/direct/djorkaeff.alexandre`?
So, we can try to debug it here, I've tried this feature some days ago with 4.11 and worked like a charm.
Thanks.

**Comment by MrSerth** [comment]
Thanks for your suggestion, @djorkaeffalexandre!

We checked the server settings, they show the following:

<img width="899" alt="Bildschirmfoto 2020-11-02 um 18 17 16" src="https://user-images.githubusercontent.com/7300329/97990175-cf6ef500-1ddf-11eb-83ca-6b03a1f3c2d5.png">

I currently try to find out how we can proceed here.

**Comment by MrSerth** [comment]
Disabling the "Fetch full message content from the server on receipt" option, which only works for Enterprise servers, solved my issue.
