### ISSUE TITLE
Unable to log back in via iframe after token expires

### ISSUE THREAD

**Issue by pbenkoe** [RocketChat/Rocket.Chat.ReactNative#2593]
### Description:

After a session expires, the user gets logged out correctly - yet, there is no way for the user to log back in. When clicking 'Join a workspace' on the initial screen, there is no way to select a new workspace (might be a separate issue), but the 'Login' button for the previously selected server shows up (one should actually be able to enter a server URL here). Anyways, when clicking 'Login', one does NOT get redirected to the iframe URL, but instead the rocket.chat login screen is visible (which should never be the case for iframe logins). Obviously a login via the rocket.chat UI fails, since the iframe workflow is being ignored.

### Environment Information:

- Rocket.Chat Server Version: 3.7.0
- Rocket.Chat App Version: 4.11.0
- Device Name: any
- OS Version: any

### Steps to reproduce:

1. Log in to a server via iframe auth
2. Let the session token expire
3. Go back to the app and take any action to get logged out
4. Try to log back in by clicking 'Join a workspace'
4a. Notice, that one cannot select a new server/add a new server URL
5. Click 'Login' (now being in the environment of the previously entered domain)
5. Find, that you don't get redirected to the iframe URL and are not able to log back in

### Expected behavior:

After being logged out, one should get redirected to the iframe URL specified in the rocket.chat server backend.

### Actual behavior:

One gets redirected to the rocket.chat login UI, which obviously doesn't work for iframe auth configuration.

### Additional context:

Step 1: Initial screen - then tap 'Join a workspace'
![1](https://user-images.githubusercontent.com/2855761/97789597-ecf15400-1b7e-11eb-8acf-17d02023c9cd.png)

Step 2: Instead of actually being able to select a new workspace URL, one gets taken to the overview page of the previously logged in domain - then tap 'Login'
![2](https://user-images.githubusercontent.com/2855761/97789598-ef53ae00-1b7e-11eb-9316-9f62a7df11c5.png)

Step 3: Instead of being redirected to the iframe url, the rocket.chat login UI shows up and breaks login, since the iframe auth flow is being ignored - one cannot log back in.
![3](https://user-images.githubusercontent.com/2855761/97789599-efec4480-1b7e-11eb-942f-da2bf6d0acbf.png)

**Comment by djorkaeffalexandre** [comment]
Hey @pbenkoe,
Can you provide some test credentials on `https://open.rocket.chat/direct/djorkaeff.alexandre`?
I've tried to reproduce it here but not was possible, I followed what you've said:
1. login using iframe
2. expires token
3. logged out
4. login again works as expected
