### ISSUE TITLE
Gradle bundleRelease Failed

### ISSUE THREAD

**Issue by hoesein** [RocketChat/Rocket.Chat.ReactNative#2595]
### Description:
i get this error while trying to build release version of **Rocket.Chat App**. i have already follow your documantion and react native official documantion.

### Environment Information:
- Rocket.Chat Server Version: 3.0.12 (not sure)
- Rocket.Chat App Version: 4.11.0 (single-server)
- Device Name: Android Emulator
- OS Version: Android 9.0

# Steps
- generate upload key and set it in gradle.properties
- cd/android && gradlew bundleRelease
- Task :app:bundleFossReleaseJsAndAssets FAILED

### Additional context:
![image](https://user-images.githubusercontent.com/38109319/97812526-2f667e00-1cb0-11eb-94aa-7e9b7040de11.png)

**Comment by diegolmello** [comment]
We have more than one build flavor, so `bundleRelease` won't work.
Run `bundlePlayRelease` for Google Play version or `bundleFossRelease` for FOSS.
