### ISSUE TITLE
I can see some users when inviting user into a group despite having no privilege in the desktop version

### ISSUE THREAD

**Issue by David-Tsui** [RocketChat/Rocket.Chat.ReactNative#2597]
### Description:

Differenct privilege from Rocket.Chat desktop version.

If I have no privilege of inviting **user into a group** in desktop version, no user will be seen;
however, I can see **every user I have interactived** with in mobile version 

### Environment Information:

- **Desktop(meteor version)**: 3.7.1, I think it doesn't matter.
- **Mobile(RN version)**: 4.10.0, I am waiting for stable 4.12.0(Version 4.11.0 has too many problems to be used).

### Steps to reproduce:

1. In desktop version, cancel A's privilege of inviting user into a group.
2. Relaunch the mobile version, login with A, and try to invite user into a group.

### Expected behavior:

No user can be seen.

### Actual behavior:

Every user I have interactived will show in the list.

**Comment by diegolmello** [comment]
> I am waiting for stable 4.12.0

*Right now* is the best time to test 4.12.0.
We're on a beta phase and we're waiting for your feedbacks so we can fix issues before they land final release.

> Version 4.11.0 has too many problems to be used

What issues?

>In desktop version, cancel A's privilege of inviting user into a group.
Relaunch the mobile version, login with A, and try to invite user into a group.

It worked for me. Can you record a video?
