### ISSUE TITLE
there is no option to jump on messages in search

### ISSUE THREAD

**Issue by hmn566** [RocketChat/Rocket.Chat.ReactNative#2599]
### Description:

there is no option to jump on messages in search

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version: 4.11.0.2137
- Device Name: Mobile android
- OS Version: 10

### Steps to reproduce:

1. Go to rooms
2. search for a word
3.  there is no option to jump on messages in search

### Expected behavior:

 What you expect to be an option to jump on message

### Actual behavior:

there is no option

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1315
