### ISSUE TITLE
The application closes after updating to experimental version 4.12.0

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#2613]
### Description:

The application closes after updating to experimental version 4.12.0. I've already tried clearing the app data, completely uninstalling, and reinstalling.
The application opens, but after you log in it automatically closes.
The older version without that problem.

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.12.0 Version Experimental
- Device Name: Samsung Galaxy S7 Edge
- OS Version: 8.0.0

**Comment by ankar84** [comment]
For me all works good with server 3.7.1 and 4.12 Experimental version.

**Comment by diegolmello** [comment]
Can you share a log report?

**Comment by aleadco** [comment]
@diegolmello when the application closed send the application log, I imagine that will get to you.  I tried to copy the that log being sent but didn't get any option to do so.  Or is it you mean the server log?  Excuse me. How can I give you the information you need?

**Comment by djorkaeffalexandre** [comment]
@aleadco we've found an error related to `es` language, let's check if #2616 fixes your problem, it will be launched on beta soon.
Thanks for your report.

**Comment by aleadco** [comment]
@djorkaeffalexandre ok, I will be aware.  Regards my friend.

**Comment by aleadco** [comment]
@diegolmello and @djorkaeffalexandre update 4.12.0 RC.01 resolves the bug.

**Comment by diegolmello** [comment]
@aleadco Awesome. Thanks for the feedback.
