### ISSUE TITLE
Broken German translation in 4.12.0 (Profile --> Settings --> Notifications)

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2625]
### Description:

When opening the menu, "Profil", "Settings" in 4.12.0 when the language is set to German ...

![image](https://user-images.githubusercontent.com/3321655/98731070-741fa280-239d-11eb-8f4f-c7064f0bc66d.png)

Instead of showing "Benachrichtigungen" (German Translation of "Notifications"), it shows this:

![image](https://user-images.githubusercontent.com/3321655/98731187-a29d7d80-239d-11eb-8cce-ceb0bc3964f0.png)

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.12.0 Single-Server
- Device Name: iPhone 11 Simulator
- OS Version: IOS 14.1

### Steps to reproduce:

See above

### Expected behavior:

The correct string "Benachrichtigungen"

### Actual behavior:

The strange output from the screenshot above

### Additional context:

The translation is there and correct in /app/i18n/locales/de.js

**Comment by ankar84** [comment]
Same with other languages.
![image](https://user-images.githubusercontent.com/4023037/98773460-06559400-23fa-11eb-9a6c-b112c85eaf8c.png)
