### ISSUE TITLE
What the difference between bundlePlayRelease and bundleFossRelease? Push notifications work in both cases?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2627]
Hi all!

Tell me please.
What the difference between bundlePlayRelease and bundleFossRelease? Push notifications work in both cases?

I build single-server with my google-service and i want build 4.12

Thank you advanced

**Comment by diegolmello** [comment]
- Play: Google Play version
- Foss (free and open source software): F-Droid store version
  * Push notifications won't work

**Comment by arpsyapathy** [comment]
@diegolmello 
How build apk with push?
When i bundlePlayRelease i get aab. But i need build apk with push for my users.

**Comment by diegolmello** [comment]
You have to use `assemble` instead of `bundle` if you want to generate APK.

https://developer.android.com/studio/build/building-cmdline
