### ISSUE TITLE
4.12.0 IOS can't build(WatermelonDB not installed)

### ISSUE THREAD

**Issue by David-Tsui** [RocketChat/Rocket.Chat.ReactNative#2628]
### Description:

Can't build IOS from release tag 4.12.0-rc.1, show IWatermelonDB not installed in Xcode.

### Environment Information:

- Rocket.Chat App Version: 4.12.0-rc.1
- Device Name: Emulator IPhone 11(ios 14.0)

### Steps to reproduce:

1. Clone your repo, checkout to tag 4.12.0-rc.1
2. yarn
3. Xcode, build and run.

### Expected behavior:

Can build.

### Actual behavior:

Can't build.

### Additional context:

I tried some watermelonDB install instruction below.
![image](https://user-images.githubusercontent.com/8610682/98796593-8570b980-2446-11eb-9fc7-14f78382786b.png)
Even after ```pod install```, it didn't work.

Error message: 
```
clang: error: no such file or directory: '/Users/bcreator/Library/Developer/Xcode/DerivedData/RocketChatRN-benudnatcoemreadanformnxvzyf/Build/Products/Debug-iphonesimulator/libWatermelonDB.a'
```

**Comment by diegolmello** [comment]
Does latest commit from `develop` branch work for you? https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md#how-to-run

**Comment by David-Tsui** [comment]
@diegolmello Yes
