### ISSUE TITLE
Wrong styling on E2E banner

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#2629]
### Environment Information:

- Rocket.Chat Server Version: any
- Rocket.Chat App Version: 4.12
- Device Name: any
- OS Version: any

### Steps to reproduce:

1. Have e2e banner displaying (just login)

### Expected behavior:

Banner's style should follow `Sorting` alignment.
![Screen Shot 2020-11-11 at 10 44 49](https://user-images.githubusercontent.com/804994/98819174-4ffaaa80-240b-11eb-8fad-6f5e776948a9.png)

### Actual behavior:

It's misaligned.
![Screen Shot 2020-11-11 at 10 45 17](https://user-images.githubusercontent.com/804994/98819167-4e30e700-240b-11eb-8fd3-28bc657936d9.png)

**Comment by yash-rajpal** [comment]
I can do this and make another pull request, can you please elaborate on all the changes to be done?
I see the current Pull request needs some changes.
Thanks.

**Comment by diegolmello** [comment]
@rogerioo are you going to do the requested changes?

**Comment by rogerioo** [comment]
@diegolmello yes, I will! I'm just in a rush with the end of semester in my University. By the weekend I believe I'd have finished!

**Comment by yash-rajpal** [comment]
@rogerioo Okay, Goodluck with the end of semester exams. I will try to fix some other beginner level issues.

**Comment by rogerioo** [comment]
Thanks @yash-rajpal !

**Comment by benndip** [comment]
Hello I've just resolved the alignment issue now. Can I make a pull request for it?
