### ISSUE TITLE
The release 4.12.0 is same to 4.11.0.

### ISSUE THREAD

**Issue by bingluen** [RocketChat/Rocket.Chat.ReactNative#2632]
The release 4.12.0 is same to 4.11.0.

Is there mistake on add tag ?

Just see 4.12.0...4.11.0

![圖片](https://user-images.githubusercontent.com/6832868/98892713-d979ad80-24db-11eb-9e7c-718ab9617a21.png)

**Comment by David-Tsui** [comment]
It should be a mistake, the 4.12.0-rc.1 is the latest.

**Comment by diegolmello** [comment]
That's a mistake.
I'm going to fix it on #2635 and create a new release tag.
Thanks for pointing it out.

**Comment by diegolmello** [comment]
Fixed.
