### ISSUE TITLE
Messages overlap in thread

### ISSUE THREAD

**Issue by hungntq** [RocketChat/Rocket.Chat.ReactNative#2633]
### Description:

Messages overlapping after switch between 2 thread

### Environment Information:

- Rocket.Chat Server Version: 3.5.3
- Rocket.Chat App Version: 4.12.0.214
- Device Name:  Samsung A30 (Android)
- OS Version: Android 10

### Steps to reproduce:

1. Click to open a chat room
2. Click on thread 1 => Display thread 1
3. Back to open room view, then click on thread 2 => Display thread 2
4. Repeat step 2, 3 then messages in thread overlap

### Expected behavior:

Messages in thread displayed normally

### Actual behavior:

![ezgif-5-c40badccf3fb](https://user-images.githubusercontent.com/56143751/98909370-5153d200-24f4-11eb-8260-d70fbb4a3424.gif)

**Comment by diegolmello** [comment]
This is a long time known issue, but it's hard to reproduce.
It's finally planned to be fixed on 4.13 and I'll try using your example.
Thank you.
