### ISSUE TITLE
iOS Project error

### ISSUE THREAD

**Issue by pritamye77** [RocketChat/Rocket.Chat.ReactNative#2634]
iOS project error

error: /Users/neural/Desktop/Rocket Chat/Rocket.Chat.ReactNative/node_modules/react-native/React/AccessibilityResources/en.lproj: No such file or directory (in target 'React-Core-AccessibilityResources' from project 'Pods')

**Comment by David-Tsui** [comment]
Have you try version 4.12.1?

**Comment by pritamye77** [comment]
Yes

**Comment by pritamye77** [comment]
Not yet...I have to check

Thanks

**Comment by roaring-b** [comment]
I'm still seeing this with 4.17.0

**Comment by jhassler1031** [comment]
I am having this issue as well.  What was the resolution?

**Comment by VinodComlink** [comment]
I am having the same issue. Please share how it can be fixed.
