### ISSUE TITLE
Rocket.Chat 4.12.1 crashes on start on Android

### ISSUE THREAD

**Issue by igalic** [RocketChat/Rocket.Chat.ReactNative#2642]
### Description:

since the upgrades this night, the app crashes on startup

### Environment Information:

- Rocket.Chat Server Version: TODO
- Rocket.Chat App Version: 4.12.1 
- Device Name: One Plus 5t
- OS Version: 10

### Steps to reproduce:

1. Open App
2. It crashes

I've done this a few times, and "sent Feedback" but i have no idea if this arrives at anyone who cares

### Expected behavior:

that it doesn't crash

### Actual behavior:

but it does

### Additional context:

i wish i could copy paste the stacktrace from the feedback form

**Comment by urosino** [comment]
The same for me. 

Android 11.

**Comment by diegolmello** [comment]
@igalic "Send Feedback" from Android doesn't land anywhere we can see.

Please, grab a log report and send to us.
Feel free to contact me on https://open.rocket.chat/direct/diego.mello

Thank you.

**Comment by diegolmello** [comment]
Ok, we have a fix and we're releasing a new build in the next hours.

**Comment by diegolmello** [comment]
Released new beta on 4.12.1.2143 on Google Play.
Let me know if it's still happening.
Thanks.

**Comment by igalic** [comment]
thank you very much! works!
