### ISSUE TITLE
iOS crash - MMKV Error

### ISSUE THREAD

**Issue by jfredsilva** [RocketChat/Rocket.Chat.ReactNative#2643]
The app is crashing on MMKV migration.
Error: "Getting a multi-process MMKV migration without setting groupDir makes no sense"

I followed the tutorial but I didn't found any mention about setting the groupDir for MMKV.

**Comment by djorkaeffalexandre** [comment]
Did you configured `App Group` string on each target `Info.plist`?
Main App/Share Extension/Notification Service

**Comment by jfredsilva** [comment]
Thanks, I missed one .plist

**Comment by djorkaeffalexandre** [comment]
You're welcome..
