### ISSUE TITLE
Reply Messages from Notifications not being sent

### ISSUE THREAD

**Issue by zeeshanwarriach93** [RocketChat/Rocket.Chat.ReactNative#2645]
Unable to start receiver chat.rocket.reactnative.ReplyBroadcast: java.lang.NullPointerException: value for name x-user-id == null
![Screen Shot 2020-11-15 at 2 37 50 AM](https://user-images.githubusercontent.com/74134024/99157565-d0f7c180-26eb-11eb-84c2-8f4846390638.png)

**Comment by diegolmello** [comment]
@zeeshanwarriach93 Can you follow the issue template so we can reproduce it and help you?
Thanks.

**Comment by zeeshanwarriach93** [comment]
I had problem with host path, I have resolved the issue.
Thanks
