### ISSUE TITLE
[Feature] Custom audio alert for Voice / Video calls.

### ISSUE THREAD

**Issue by toshanmugaraj** [RocketChat/Rocket.Chat.ReactNative#2648]
### Description:

It would be better if we can have different audio notification alert, like 30 seconds audio alert ringtone when there is notification with `messageType` is `jitsi_call_started`. This alert can be Audio ringtone / Call Vibration / Silent based on the device sound mode.

### Environment Information:

- Rocket.Chat Server Version: 3.8.0
- Rocket.Chat App Version: 4.12.0
- Device Name: Iphone / Android
- OS Version: iOS / Android all versions

### Steps to reproduce:

1.  Make a end2end encrypted chat room.
2.  Keep the application in background mode.
3.  Let the other user make a voice/video call.
4. Now the user in background mode, getting called will get a normal message notification.

### Expected behavior:

The user in background mode and getting called should have 30 seconds ringtone alert  or vibration alert or silent based on the sound mode in device.

### Actual behavior:

Now we treat all notifications as message notification, and just play simple chime alert. This will not differentiate the user that there is a call.

**Comment by diegolmello** [comment]
We're going to take a look at Jitsi notifications soon, but we might use OS' call system instead so a Jitsi call would behave as any phone call.

**Comment by solutionprovider9174** [comment]
this will work like telephone ringtone when some other user give his call to someone?
I am waiting for ringtone issue fixing on react native app.
how can i fix it by myself?

**Comment by solutionprovider9174** [comment]
Hello, I have fixed these issues with my developer team.
My skype is this : live:.cid.a3e05258f0b595aa

**Comment by diegolmello** [comment]
@solutionprovider9174 can you contribute back with a pull request?

**Comment by solutionprovider9174** [comment]
i fixed this. but when i trying with old version of rcrn, apk doesn't open when i generate apk from it.
I found that rocketchat is upgraded for version. so i am doing again now.
