### ISSUE TITLE
Only the last new message is visible

### ISSUE THREAD

**Issue by amahbadi** [RocketChat/Rocket.Chat.ReactNative#2650]
### Description:

When the number of messages sent to a user exceeds 1 message, only the last one is displayed in the mobile application. This problem is not seen in the web application.

### Steps to reproduce:

1. Notification arrives 
2. Open Mobile app
3. Find user and open chat with this user

### Expected behavior:

 All new messages from this user loaded and shown

### Actual behavior:

Only the last new message is visible

### Server Setup Information:

- Version of Rocket.Chat Server: rocketchat/rocket.chat:latest
- Operating System: ubuntu server 20.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: mongod
- NodeJS Version: -
- MongoDB Version:mongo:latest

### Client Setup Information

- Desktop App or Browser Version: 4.12.0 on iOS
- Operating System:iOS 13 

### Additional context
docker-compose.yml config:

services:
   db:
     image: mongo
     volumes:
       - ./data/runtime/db:/data/db
       - ./data/dump:/dump
     command: mongod --oplogSize 128 --bind_ip_all --replSet rs1
     restart: unless-stopped

   rocketchat:
     image: rocketchat/rocket.chat:latest
     environment:
       - MONGO_URL=mongodb://db:27017/rocketchat
       - ROOT_URL=my_url
       - MONGO_OPLOG_URL=mongodb://db:27017/local?replSet=rs01
       - Accounts_UseDNSDomainCheck=True
     depends_on:
       - db
     ports:
       - 3000:3000
     restart: unless-stopped
     command: >
       bash -c
         "for i in `seq 1 30`; do
           node --max_old_space_size=4096 main.js &&
           s=$$? && break || s=$$?;
           echo \"Tried $$i times. Waiting 5 secs...\";
           sleep 5;
         done; (exit $$s)"

   hubot:
     image: rocketchat/hubot-rocketchat:latest
     environment:
       - ROCKETCHAT_URL=ip:port
       - ROCKETCHAT_ROOM=GENERAL
       - ROCKETCHAT_USER=someuser
       - ROCKETCHAT_PASSWORD=somepassword
       - BOT_NAME=botname
       - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
     links:
       - rocketchat:rocketchat
     ports:
       - 7000:8080

**Comment by pratyaksh123** [comment]
That is the same behaviour on web app too, Could you please clarify a bit more

**Comment by diegolmello** [comment]
Hey, @amahbadi.
I'm sorry about the delay.
I've been trying to reproduce that, but I can't.
Can you give us more details and tell us if you reproduce it on https://open.rocket.chat?
Thank you.

**Comment by grahhnt** [comment]
I believe I'm having the same issue above, it tends to happen when one (or more) of the following events occur with the channel:
- over 150k messages exist in the channel
- a high amount of messages sent per minute

it also sometimes occurs when the app is put into the background or closed completely (but this may just be the above events occuring)

I've noticed that it does load properly once the app is installed fresh or you switch to another version of the app (appstore, testflight or single-server)

**Comment by grahhnt** [comment]
@diegolmello I'm not that familiar with the mobile app flow, what endpoints does the app try and load before a room is rendered?
