### ISSUE TITLE
iOS: Updated new avatar not refreshed in hamburger menu when user relogin

### ISSUE THREAD

**Issue by ramdeveloperbh** [RocketChat/Rocket.Chat.ReactNative#2655]
### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.12.1
- Device Name: iPhone 11
- OS Version: 13.6.1

### Steps to reproduce:

1. Login the mobile app.
2. Choose the profile option from hamburger menu.
3. Upload/Update new avatar in Profile screen.
4. Save Changes.
5. Update avatar will refresh in hamburger menu, Profile screen and Direct/Group chat conversations.
6. Choose the logout option from hamburger menu.
7. Re-login the mobile app.
8. Check avatar in hamburger menu, Profile screen and Direct/Group chat conversations.

### Expected behavior:

Updated new avatar should refresh in hamburger menu, Profile screen and Direct/Group chat conversations.

### Actual behavior:

Updated new avatar not refreshed in hamburger menu.

<img width="1655" alt="Screen Shot 2020-11-19 at 1 17 31 PM" src="https://user-images.githubusercontent.com/74710223/99653233-d34e7880-2a69-11eb-956e-780eb88b7490.png">

**Comment by MrWillTurner** [comment]
+1

**Comment by nmplcpimenta** [comment]
I'd like to take on this issue; if anyone has anymore information, I'd be thankful =)
