### ISSUE TITLE
horizontal line not showing rocketchat mobile

### ISSUE THREAD

**Issue by helicrenz** [RocketChat/Rocket.Chat.ReactNative#2661]
### Description:

 RocketChat mobile app not showing horizontal line.

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.12.1.2143
- Device Name:  Android
- OS Version: Android 10

### Steps to reproduce:

1. send message on rocketchat ****
2. check rocketchat mobile app its blank

### Expected behavior:

Have the same display on rocketchat web and desktop app

### Actual behavior:
**Rocketchat Web and Desktop**
![image](https://user-images.githubusercontent.com/42835226/99785418-1850d880-2b58-11eb-91ac-54d408ffd177.png)

**Rocktet Chat Mobile**
![image](https://user-images.githubusercontent.com/42835226/99785171-c0b26d00-2b57-11eb-8dd4-a9e329d0993b.png)

**Comment by diegolmello** [comment]
I didn't get what's the message content

**Comment by helicrenz** [comment]
Hello @diegolmello ,
Thanks for you reply. In Markdown Style guide when sending message **** this will create horizontal line. Like picture above in rocketchat desktop and web. When checking my phone i don't see any horizontal line i can just see blank message.

**Comment by diegolmello** [comment]
What's your markdown configuration on the admin?

**Comment by helicrenz** [comment]
@diegolmello 
![image](https://user-images.githubusercontent.com/42835226/99801115-7984a600-2b70-11eb-9609-f246b5ca109a.png)

**Comment by diegolmello** [comment]
I see.
There are some rules missing implementation on our mobile apps.
I'm marking as `improvement`.
PRs appreciated.
Thank you.
