### ISSUE TITLE
the Android app Rocketchat returns an error CLEARTEXT

### ISSUE THREAD

**Issue by fenrirus86** [RocketChat/Rocket.Chat.ReactNative#2662]
### Description:

the Android app Rocketchat returns an error CLEARTEXT communication to x.x.x.x not permited by network security policy.

### Steps to reproduce:

install app rocketchat
Enter workspace URL
Tap Connect

### Expected behavior:

Connect to local server

### Actual behavior:

the Android app Rocketchat returns an error CLEARTEXT communication to x.x.x.x not permited by network security policy.
The server is your own and working. Mobile Devices on the local network.
Version 3.8.0.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0
- Operating System: Ubuntu 18
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version:4.0.21

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by diegolmello** [comment]
Do you have SSL configured on your server?
If so, send me a DM: https://open.rocket.chat/direct/diego.mello

**Comment by bodyionita** [comment]
I seem to be having a similar issue on my new phone. Had a Samsung Galaxy J4+ and worked just fine on it. When trying it on a Redmi Note 9 Pro I get the same error: "cleartext communication to...".

No SSL on the server as far as I know. The server is hosted at work so I do not know much about it.

**Comment by diegolmello** [comment]
This is the correct behavior.
We're following Google recommendation of disallowing insecure connections.

**Comment by Kyogre** [comment]
But how we can test our http (not https!) rocket chat server from mobile? For example: we deployed our rocket chat server on the http (e.g. http://123.10.10.111:3000/), but we won't buy SSL certificate until we test it, so we can't afford https on that step.
Thus it would be great to create special developer version of the mobile app, that has no such restriction.

**Comment by cherepanov** [comment]
no option to disable this?

**Comment by diegolmello** [comment]
We have no plans on making our app insecure.
If you want to test your HTTP without adding a certificate, you can build the app yourself [by enabling cleartextTrafficPermitted](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/53eb251476f76afa460f7e4ede6e9409b6e1445e/android/app/src/main/res/xml/network_security_config.xml#L3).

The other option would be to add a certificate for free to your server with [Let's Encrypt](https://letsencrypt.org/)
