### ISSUE TITLE
server/workspace url gone after auth-token timeout/reset - please improve ui

### ISSUE THREAD

**Issue by devZer0** [RocketChat/Rocket.Chat.ReactNative#2665]
hello, 

we are using wechange, which is a community platforum with rocketchat as messaging tool.

from time to time, people get disconnected from the rocketchat mobile app and need to re-enter the workspace url.

it's hard enough to get them to use wechange/rocketchat and we are having a hard time to get people to use rocketchat - so imho, it's absolutely damaging for communities , if it's not trivial for users to re-enter rocketchat after token/auth-timeout.

for now, you need to klick into workspace url edit field to see the former value. it's better than nothing, but it keeps people away in an unnecessary way. 

i think jon and jane doe (i.e. non technical users) are totally overchallenged with this, because it's not obvious to click into an edit field to see it's former value - they will see "enter workspace url" and think "huh? i don't remember, will need to ask...."

i have never seen a chat app or any other app which needs a user to re-enter or select server information more then once, i guess it would not be to hard to do to enhance this for more user-friendliness.

thank you

**Comment by diegolmello** [comment]
Follow the issue template with proper version and reproducible descriptions.
We fixed this a while ago and we need to make sure we're talking about the same thing or if it's an edge case.
Thank you.

**Comment by devZer0** [comment]
after reset, it looks like this:

<img width="281" alt="grafik" src="https://user-images.githubusercontent.com/3506105/99919424-aaeea480-2d1d-11eb-9c3f-443df5b82ccc.png">
<img width="280" alt="grafik" src="https://user-images.githubusercontent.com/3506105/99919429-b215b280-2d1d-11eb-9b94-bc7f5a1fb4ed.png">

it's absolutely NOT obvious to any end-user that you need to click into workspace url input fielt to get the former entry shown

**Comment by wellemut** [comment]
Why does this app throw me out anyway?? WhatsApp/Telegramm never log me out.
Its so unnessesary. If people feel more secure, if they get logged out after a while, they should get an option to activate it, but by default it stops those users, who feel afraid of apps and password anyway...

**Comment by diegolmello** [comment]
@devZer0 @wellemut There's a setting on the admin panel under "Accounts" to set session length.
![image](https://user-images.githubusercontent.com/804994/99960405-70abf400-2d6b-11eb-9b1e-cc878b610e32.png)
All users tokens are expired after that and it's pretty common for admins to set it to 1~2 days.

Can you take a look if that's the case?
Even if that's the case, the app should redirect you to the right server after an expiration, so it might be a bug.
We just need to be able to reproduce so we can fix it.
Thank you.

**Comment by devZer0** [comment]
yes, i know that you can set this at server level, but i have no influence on the rocket server settings. 

i only see that the community i'm in does not accept rocketchat as communications tool. 

they switch to telegram and all sorts of other group messengers, so i think it's important to be sensitive and to fix "every spoke put in the wheels" of average end-users.

>Even if that's the case, the app should redirect you to the right server after an expiration

you mean at token expiration i should be redirected automatically to the "last" server, without explicitly need re-selecting it in the url input field ?

**Comment by diegolmello** [comment]
> you mean at token expiration i should be redirected automatically to the "last" server, without explicitly need re-selecting it in the url input field?

Yes. If everything works correctly, the app should still log you out and redirect you to the server correct server, so you can enter your credentials again.
That's why it might be a bug.

**Comment by devZer0** [comment]
ok, thanks.

why is it needed to re-enter credentials? thats totally unfavourable on a mobile device

**Comment by diegolmello** [comment]
If the admin asks for it, there's nothing we can do.

**Comment by Alexdc-12** [comment]
Is the user recieving a message that they have been logged out and need to log back in?

**Comment by wellemut** [comment]
> 
> 
> @devZer0 @wellemut There's a setting on the admin panel under "Accounts" to set session length.
> All users tokens are expired after that and it's pretty common for admins to set it to 1~2 days.
> 

This was set to 90 days, so it can not be the problem.
I am the admin of it

**Comment by wellemut** [comment]
> 
> 
> Is the user recieving a message that they have been logged out and need to log back in?

Of course they just see that they are logged out

**Comment by mz-aimcom** [comment]
Hi @diegolmello,
As I think that I am experiencing the same issue: Is there a fix or do I have to live with the fact that I have to re-enter the workspace URL everytime I close and re-open the app?
