### ISSUE TITLE
Mobile version doesnt recognize backslash escaping

### ISSUE THREAD

**Issue by b90g** [RocketChat/Rocket.Chat.ReactNative#2666]
### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.12.1.317
- Device Name: iPhone SE (1stgen)
- OS Version: 14.2

### Steps to reproduce:

When escaping star (*) and other signs with a backslash  (`\*`) the star will be  displayed including the backslash in the mobile version, while the Browser just displays the star.

### Expected behavior:

`*` inside the mobile app

### Actual behavior:

`\*` inside the mobile app
### Additional context:

none

**Comment by pratyaksh123** [comment]
Hey, I'd like to work on this. Can you explain how escaping is done on the web app, I'm not able to escape characters on the web app as well ( backslash is also getting displayed ).

**Comment by diegolmello** [comment]
@b90g it might be based on the markdown settings from admin panel. Can you share with us?

**Comment by b90g** [comment]
mostly i have no access to the admin settings. i am just a support clerk  trying to send issues when the amount of certainty is big enough.

if there is a markdown add-on for rocketchat i can asked if it is enabled.

when i write `test*ing while test*ing` inside rocketchat (via Browser) i get a cursive  `ing while test` 

if i write  `test\*ing while test\*ing` i will get  `test*ing while test*ing` 

most common way to attempt a gender inclusive writing in german.

**Comment by b90g** [comment]
lmk if translation is need for german settings panel


![Clipboard - 14  Dezember 2020 09 14](https://user-images.githubusercontent.com/63392812/102056742-18f22d00-3ded-11eb-8747-e04808c21126.png)

**Comment by diegolmello** [comment]
The whole `Marked` md parser isn't implemented on mobile apps.
You might switch to `Original` (or contribute back if it's important to your company).
Thanks.
