### ISSUE TITLE
Rocket.Chat status depends on first opened client?

### ISSUE THREAD

**Issue by jhjacobs81** [RocketChat/Rocket.Chat.ReactNative#2667]
so, some of our users noticed something "odd"

When they open the client on their mobile phone, and then on their desktop, their status gets set to "Away" when they quit the mobile app. even though the desktop app is still open.

When they open the desktop app first nothing happens when they open and close the mobile app.

Is there a way to make the status "dependable" on the last opened client?

**Comment by diegolmello** [comment]
Is this still an issue?
We fixed a status issue on 4.13.0.
