### ISSUE TITLE
[Bug][Jitsi][Android] No one hears the user of Rocket.Chat in Jitsi call with third-party recording application installed

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2669]
### Description:

I have a few users of my RC server owners of Xiaomi Mi A1 and they all complaining same issue - no one can hear them when they in Jitsi call.
We did try 4.7 whitelabel verion and 4.12.1 play market version - all same, no luck

### Environment Information:

- Rocket.Chat Server Version: 4.12.1
- Rocket.Chat App Version:3.7.1
- Device Name: Xiaomi Mi A1
- OS Version: Android 9

### Steps to reproduce:

1. Go to Jitsi call
2. Try to say something
3. No one can hear you

### Expected behavior:

All participants of call hear all each other

### Actual behavior:

No

### Additional context:

No

**Comment by djorkaeffalexandre** [comment]
@ankar84 I've tested this with a Xiaomi Readmi note 9 and can't reproduce the same behavior, can you try to see if the users have permitted the access to microphone and try to reinstall the app?
Thanks.

**Comment by ankar84** [comment]
> @ankar84 I've tested this with a Xiaomi Readmi note 9 and can't reproduce the same behavior, can you try to see if the users have permitted the access to microphone and try to reinstall the app?

Hi, @djorkaeffalexandre 
Actually I can't reproduce that bug on a bunch of Android smartphones - all works just fine.
On my personal Xiaomi Mi 9 SE all works perfect.
User said, that all permissions are granted and he did a reinstall of applications with no luck.

Can some other applications cause that problem? Like [CallU](https://play.google.com/store/apps/details?id=com.smsrobot.callu&gl=US) which is also installed on problem smartphone.

**Comment by ankar84** [comment]
> Can some other applications cause that problem? Like [CallU](https://play.google.com/store/apps/details?id=com.smsrobot.callu&gl=US) which is also installed on problem smartphone.

Yeap, just test it on my Mi 9 SE - when start recording in CallU - no one can hear me anymore.
User said, that all other applications like WhatApp, Telegram and Skype works fine with that call recorder app.
It would be great if RC will compatible with that.
But anyway, now we know the root cause of that problem, and it's not in RC or Jitsi. It incompatibility between Jitsi and CallU.

**Comment by djorkaeffalexandre** [comment]
@ankar84, does the Jitsi App also have this incompatibility?
If so, can you open a problem in the Jitsi repository? So, when it is fixed, we just update the SDK and that's it.

**Comment by ankar84** [comment]
> @ankar84, does the Jitsi App also have this incompatibility?
> If so, can you open a problem in the Jitsi repository? So, when it is fixed, we just update the SDK and that's it.

Actually, I didn't test that. It could be Jitsi or CallU issue. I don't think it really important, so I just advice user to delete that application to use rc and Jitsi in it.
You can close that issue

**Comment by ankar84** [comment]
> @ankar84, does the Jitsi App also have this incompatibility?
> If so, can you open a problem in the Jitsi repository? So, when it is fixed, we just update the SDK and that's it.

I just did a test Jitsi meet application with that CallU application and can say, that Jitsi meet mobile not involved by that issue.
CallU doesn't show on top of Jitsi Meet like it did with RCRN. So, I think Jitsi Meet mobile application have some protection against such applications like CallU.
Here is a screen of Jitsi Meet application
![image](https://user-images.githubusercontent.com/4023037/101449249-78f25a80-3939-11eb-8501-ad6f7f855fb8.png)
And here is a screen of RCRN application
![image](https://user-images.githubusercontent.com/4023037/101449296-8f98b180-3939-11eb-9756-ad6e400ce49a.png)

**Comment by ankar84** [comment]
Another application that causing same issue -[CallRecorder](https://play.google.com/store/apps/details?id=com.appstar.callrecorder)

**Comment by diegolmello** [comment]
Is this still a thing?

**Comment by ankar84** [comment]
Let's close that!
