### ISSUE TITLE
[Bug] Retention policy breaks sorting by activity by prune chat messages

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2673]
### Description:

We implemented Rocket Chat Retention Policy in our deployment and now have an issue with sorting by activity on mobile client, web version works good.
As I get - prune messages process updates chats timestamps and it gets upper in Chat List sorted by activity. But in fact, there is no new messages in that chats and they shouldn't appear on top in sort by activity.
I think web version Sidebar works different with chats activity timestamps (more correct, IMHO)

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.12.1
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 10

### Steps to reproduce:

1. Enable Retention Policy to prune messages in all chats once a day
2. Set sorting by activity
3. Web version sorting is correct, but mobile version sorting broken.

### Expected behavior:

Sort by activity on Mobile should be same as on Web

### Additional context:

No

**Comment by ankar84** [comment]
That that appears only in mobile version and not in Web or Desktop version, so as a workaround now I hide that old chats with **Swipe left - Hide**.

**Comment by diegolmello** [comment]
Hey, @ankar84 .
I'm not sure it's a fix, but a new patch with https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2763 just landed Google Play (iOS to be approved by Apple).
Can you test it?
Thanks!

**Comment by ankar84** [comment]
> Hey, @ankar84 .
> I'm not sure it's a fix, but a new patch with #2763 just landed Google Play (iOS to be approved by Apple).
> Can you test it?
> Thanks!

Yeah, @diegolmello 
Looks like #2763 solved that issue and chat list in RCRN experimental application version 4.13.1.22186 without empty chats from far past.
Thanks for your great job, Diego!
