### ISSUE TITLE
[BUG] JITSI access token not generated from mobile when making calls.

### ISSUE THREAD

**Issue by toshanmugaraj** [RocketChat/Rocket.Chat.ReactNative#2693]
### Description:

When `JWT auth` is enabled in JITSI call settings of Rocket chat server, and user tries to call from android to iOS user .
The iOS user is prompted with `username \ password` screen to join the call.

### Environment Information:

- Rocket.Chat Server Version: 3.9.0
- Rocket.Chat App Version:  4.12.1
- Device Name: iPhone 11
- OS Version: 14.2

### Steps to reproduce:

1.  Rocket chat server ->  Adminstration -> Video Conference -> JITSI -> Enable JWT auth
2.  Keep the iOS device in background mode.
3.  Call from Android device to iOS device.
4. Call started notification received in iOS device.
5. Click notification to join the call.
6. Now we get `username/password` alert screen inside JITSI meet.

### Expected behavior:

User should not be prompted with credentials to join JITSI calls, when JWT token in enabled and configured in server.

### Actual behavior:

User is prompted with credentials to join JITSI calls, when JWT token in enabled and configured in server.

### Additional context:

`methodCallWrapper` is undefined.

[Unable to generate jwt token](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/c9c8bdecd05b5f049e88791aca9fb752aa71e851/app/lib/methods/callJitsi.js#L25)

**Comment by djorkaeffalexandre** [comment]
Hey @toshanmugaraj, can you open a PR fixing the problem?
It's just this import line
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/sagas/deepLinking.js#L18
We shouldn't import `callJitsi` directly from `/lib/methods`.
We should use `RocketChat.callJitsi` here
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/sagas/deepLinking.js#L57

**Comment by sumukhah** [comment]
Can i work on this? @toshanmugaraj @djorkaeffalexandre ?

**Comment by djorkaeffalexandre** [comment]
@sumukhah go ahead

**Comment by ankar84** [comment]
Yeah, I saw when I tap push notification about call started I was join to call as guest, without JWT authentication.

**Comment by toshanmugaraj** [comment]
@djorkaeffalexandre @sumukhah Have tested the fix now JWT based authentication is working !!

**Comment by toshanmugaraj** [comment]
@diegolmello
