### ISSUE TITLE
blue circled number next to channel that doesn’t go away

### ISSUE THREAD

**Issue by mirabilos** [RocketChat/Rocket.Chat.ReactNative#2695]
I see, next to a channel, a blue circle with the number 1 next to it that doesn’t go away even if I read the messages in the channel. The time-of-day (which for some unknown reason uses US-American format) is also blue. When I go into the channel, the speech bubble icon on top-right also has this number.

### Description:

I have no idea what this means. Documentation is silent about this.

### Environment Information:

- Rocket.Chat Server Version: no idea
- Rocket.Chat App Version: 4.12.1
- Device Name: Samsung Galaxy XCover 4s
- OS Version: 10

### Steps to reproduce:

1. Start Rocketchat
2. See the channels list

### Expected behavior:

That this is somewhere documented.

### Actual behavior:

No idea.

### Additional context:

No idea.

**Comment by diegolmello** [comment]
This is an issue we've been working to fix.
Those blue indicators are there when chats are unread (but they aren't really).
Can you tell us the steps you did to reproduce it?

Workaround for you: Open sidebar, Settings > Clear local server cache.

**Comment by mirabilos** [comment]
Diego Mello dixit:

>Those blue indicators are there when chats are unread (but they aren't really).

I figured so, but they’re staying.

>Can you tell us the steps you did to reproduce it?

Unfortunately not.

I think I had two earlier, but the other went away when I
read the things in the channel.

>Workaround for you: Open sidebar, Settings > Clear local server cache.

Hmm, it’s still there afterwards once things have loaded again.

So perhaps it’s a genuinely unread message I cannot figure out
how to find in order to read it?

**Comment by diegolmello** [comment]
You have a `magnifier` and  a `threads` icon on top right.
Tap on threads one and check if there's any unread conversation.

**Comment by mirabilos** [comment]
Diego Mello dixit:

>You have a `magnifier` and  a `threads` icon on top right inside the channel.
>Tap on threads one and check if there's any unread conversation.

The speech bubble?

It shows a huge list of things, basically everything
that’s in the channel, just in a different order.

**Comment by diegolmello** [comment]
Fixed already.
