### ISSUE TITLE
Password in clear letters for rocket.chat in source code?

### ISSUE THREAD

**Issue by dkdndes** [RocketChat/Rocket.Chat.ReactNative#2698]
Please check:
* https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/13985cf724fa145f6ffc9b452c17d9ccde221da6/e2e/data/data.cloud.js#L5

* https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/13985cf724fa145f6ffc9b452c17d9ccde221da6/e2e/data.js#L5

https://www.buymeacoffee.com/dkdndes

**Comment by diegolmello** [comment]
Hey, @dkdndes.
It's just for e2e testing and it's not really an admin.
It has access to create other users, but so does any users to that server.
Thanks for you concern.
