### ISSUE TITLE
[Bug][Jitsi] Users can't login Jitsi call with 20+ participants since 4.12.1 version

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#2699]
### Description:

Users can not join any big Jitsi call since 4.12.1
Using `Jitsi meet` applications they can join

### Environment Information:

- Rocket.Chat Server Version: 3,7,1
- Rocket.Chat App Version: 4.13.0.21833
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 10

### Steps to reproduce:

1. Create 20+ participants Jitsi call in Google Chrome using Invite more people feature and copy and paste call URL multiple times to new tabs
2. Click `Click to Join` button in RC RN applications
3. Application become unresponsive, all buttons and menu are unresponsive, you can hear sounds like someone joins call, but you can't, you stuck 

### Expected behavior:

Users need to connect to any Jitsi call using RC RN application.

### Actual behavior:
![20201208_120623](https://user-images.githubusercontent.com/4023037/101442450-f58f3400-394d-11eb-9141-d6404e4f14c1.gif)

Old RCRN 4.7 version (whitelabel) still joins that big calls without any troubles. 
And I did try `Jitsi Meet` application to join call by link - success!
![2020-12-08T05_12_14](https://user-images.githubusercontent.com/4023037/101442887-3fb3ed80-392d-11eb-95ce-de649ae0c033.gif)

But Rocket Chat React Native application can not join to that big call for some reason.

### Additional context:

I think, it may be related to **default** `Tile View` since some Jitsi server version and some Jitsi SDK version.
Old 4.7 still using `Stage View` and connects without any issues.

And if I somehow can join call using RCRN application - it doesn't work well.
I enabled camera and see myself on smartphone, others see my user with connection issues:
![image](https://user-images.githubusercontent.com/4023037/101451707-a3dead80-393d-11eb-90e9-13e014cf1a27.png)
![image](https://user-images.githubusercontent.com/4023037/101451780-c53f9980-393d-11eb-91db-dba27829f565.png)
Buttons in that case are working for others - if I turn mic off - all other users see mic crossed icon, and camera same:
![image](https://user-images.githubusercontent.com/4023037/101451900-f91abf00-393d-11eb-98f1-756705c4e67e.png)
And one more strange thing here.
I connected to that call using Jitsi meet mobile application and both mobile clients (RCRN 4.12.1 and Jitsi Meet) see each other video and hear voices. Bot mobile clients in same WiFi network. when all calls web clients in a different network. And web clients see only video by Jitsi Meet clent.

**Comment by AmatorPhasma** [comment]
Same reports on this issue from multiple users in our school, without changing anything except the app version.

**Comment by ankar84** [comment]
> Same reports on this issue from multiple users in our school, without changing anything except the app version.

Can you please give more details (Jitisi server info, mobile clients info) and screenshots?
Developers could not reproduce that issue on their [Jitsi server ](https://jitsi.rocket.chat/)

**Comment by AmatorPhasma** [comment]
> > Same reports on this issue from multiple users in our school, without changing anything except the app version.
> 
> Can you please give more details (Jitisi server info, mobile clients info) and screenshots?
> Developers could not reproduce that issue on their [Jitsi server ](https://jitsi.rocket.chat/)

Yeah... that's the nasty kind of bugs.

Jitsi-Server:
```
dpkg -l | grep jitsi
ii  jitsi-meet                    2.0.5076-1                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody            1.0.4428-1                   all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-turnserver         1.0.4428-1                   all          Configures coturn to be used with Jitsi Meet
ii  jitsi-meet-web                1.0.4428-1                   all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config         1.0.4428-1                   all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2            2.1-351-g0bfaac1c-1          all          WebRTC compatible Selective Forwarding Unit (SFU)

uname -a
Linux xxx 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```
is not the latest 2.0.5142 version because of this bug: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1919

RocketChat App Version: 4.12.1 (mostly... I also have some users with a fairly lower update priority....)
It only happened for iOS/Android App users not on Linux/Mac/Windows - and also not with the Jitsi app.

I already tested this for a couple of days without token-auth, and it didn't matter whether the server was running 10 conferences with a total of ~340 participants or 2 with only ~50 participants.

The RocketChat App show the same behaviour as in your GIF, never ending loading screen...

**Comment by diegolmello** [comment]
@AmatorPhasma Can you see if you're able to reproduce it on https://open.rocket.chat or send me your server via DM?
We tried on our server and it always works.
https://open.rocket.chat/direct/diego.mello
Let's fix it.
Thanks.

**Comment by ankar84** [comment]
> is not the latest 2.0.5142 version because of this bug: [RocketChat/Rocket.Chat.Electron#1919](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1919)

I think I have same Jitsi server version because same bug in Electron app!
```
dpkg -l | grep jitsi
ii  jitsi-meet-prosody                     1.0.4428-1                                      all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-tokens                      1.0.4428-1                                      all          Prosody token authentication plugin for Jitsi Meet
ii  jitsi-meet-web                         1.0.4428-1                                      all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                  1.0.4428-1                                      all          Configuration for web serving of Jitsi Meet
```

@diegolmello what is your versions on `jitsi.rocket.chat`?
By the way, Jitsi calls do not work from web and desktop on open.rocket.chat so I can't check if it involved in https://github.com/RocketChat/Rocket.Chat.Electron/issues/1919 bug

**Comment by ankar84** [comment]
Just tested that issue with new updated version of Jitsi https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md#205390-21-01-12 and it's look pretty good.
@AmatorPhasma can you try it?

**Comment by ankar84** [comment]
Closing that issue because with new Jitsi server 2.0.5390 modern RCRN versions are working pretty stable.

**Comment by ankar84** [comment]
I must reopen that issue - proof of bug is sent to Diego at open server.

**Comment by diegolmello** [comment]
Hey, @ankar84.
We weren't able to reproduce it.
We've tried with 30+ participants and everything worked fine.
Different than the usual video conferencing, Jitsi decodes videos on the clients rather than the server, so it takes a higher amount of memory and CPU.
Next time you see this error, capture a [bug report](https://developer.android.com/studio/debug/bug-report) and send us.
With that in hands, we'll be able to inspect if it's a memory overflow or something else.
Thanks!

**Comment by ankar84** [comment]
> We weren't able to reproduce it.
> We've tried with 30+ participants and everything worked fine.
> Different than the usual video conferencing, Jitsi decodes videos on the clients rather than the server, so it takes a higher amount of memory and CPU.
> Next time you see this error, capture a [bug report](https://developer.android.com/studio/debug/bug-report) and send us.
> With that in hands, we'll be able to inspect if it's a memory overflow or something else.
> Thanks!

Hi, Diego!
I will send you a report for sure.
But I think it's a code related issue, but not hardware related.
iOS don't have that issue - iOS code implementation is better then Android
Consecutive successful test with **Jitsi Meet** mobile app right after failed **RCRN app** on same call on same device pointes to code, not hardware.

**Comment by ankar84** [comment]
For some reason on Android RCRN thinks that there is a network failure.
https://github.com/jitsi/jitsi-meet/blob/9f9e192c3ca795826b08e0bfca79a2ea081844e5/react/features/overlay/components/AbstractPageReloadOverlay.js#L150

**Comment by ankar84** [comment]
@diegolmello Sent you bug report to DM at open server
Hope it help you

**Comment by ankar84** [comment]
Hey, @diegolmello 
Now I'm testing on new Jitsi server, but Android issue still here.
But I did a few experiments and pretty sure that client disconnected from call right after 1 minute.
I checked the time between user from Android appears in call and disappeared from call and it's always 1 minute!
May be in Jitsi SDK there is some time-out constants and one of them is 1 minute. And if we increase it to 2 minutes that issue can be resolved?
What do you think?

**Comment by ankar84** [comment]
@AmatorPhasma Do you still experience that problem?
@jacotec Hello! Can you share your experience, do you have problem client connects to big room from Android with your whitelabel app?

**Comment by jacotec** [comment]
@ankar84 I don't have / use big Jitsi rooms. Biggest was 5 people and that worked fine.

**Comment by ankar84** [comment]
> Biggest was 5 people and that worked fine.

Yeah, up to 15-20 people works pretty well, agree.

**Comment by jacotec** [comment]
If I'd need to run such a big meeting I'd not run it on Jitsi either ... I'd use my BigBlueButton server for that.

**Comment by ankar84** [comment]
> I'd use my BigBlueButton server for that.

A few people already recommended me BBB for big calls.
But we still need access from smartphones.

**Comment by ankar84** [comment]
@diegolmello hey!
Now that issue can be truly closed with this workaround https://github.com/jitsi/jitsi-meet/issues/9060#issuecomment-828204875
But update of Jitsi SDK is still complete solution for that problem.
