### ISSUE TITLE
OAUTH is missing 

### ISSUE THREAD

**Issue by adam-kulagowski** [RocketChat/Rocket.Chat.ReactNative#270]
- Your Rocket.Chat.Android app version: latest from Google Play
- Your Rocket.Chat server version: 0.63.1
- Device model you're running with: BQ M5 + Lineage OS based on Android 7.1

- Steps to reproduce:
Adding codilime.rocket.chat server. Expected to see social logins (Google/custom OAUTH).

**Comment by tiagoefreitas** [comment]
Still missing. And custom oauth ts also not working in the Rocket.Chat.Android 3.2.0 version, so there is currently no android app that works...

**Comment by diegolmello** [comment]
@tiagoefreitas Yes, it's not implemented yet.

**Comment by tiagoefreitas** [comment]
May want to fix it first in the current android app before implementing here then...its not working there neither.

**Comment by lorek123** [comment]
I think this can be closed because of https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1093
