### ISSUE TITLE
[Feature] Ability to hide (channel & dm) avatar on mobile apps

### ISSUE THREAD

**Issue by joe733** [RocketChat/Rocket.Chat.ReactNative#2711]
### Description:

Well, I guess the heading speaks for itself.

### Environment Information:

- Rocket.Chat Server Version: 3.9.1
- Rocket.Chat App Version: 4.12.1.2143
- Device Name: itelA46 L5503
- OS Version: android 9

**Comment by pratyaksh123** [comment]
But you can already do that right? From Profile-> Avatar

**Comment by joe733** [comment]
![WhatsApp Image 2020-12-14 at 12 17 37](https://user-images.githubusercontent.com/38415384/102154191-e274ea80-3e9e-11eb-8b86-d3434c6e34df.jpeg)

@pratyaksh123, I want those `D`, `A` etc. to be hidden with only `#default` or `#announcements` being shown. I don't this that's possible yet.

**Comment by diegolmello** [comment]
@joe733 That should be a setting on the server.
Can you add this feature request there? https://github.com/RocketChat/feature-requests
In order to hide the avatars, we need to redesign all layouts properly instead of showing an empty space.
