### ISSUE TITLE
RocketChatRN-Swift.h file not found

### ISSUE THREAD

**Issue by granttoday** [RocketChat/Rocket.Chat.ReactNative#2713]
### Description:

I'm building the app following the Whitelabel guide and I get this error:

![image](https://user-images.githubusercontent.com/46821216/102170476-b97a3880-3e51-11eb-9746-a7df483e2158.png)

### Environment Information:

- Rocket.Chat Server Version: N/A
- Rocket.Chat App Version: single-server
- Device Name: N/A
- OS Version: N/A

### Steps to reproduce:

1. Follow whitelabel guid
2. Build app

### Expected behavior:

The app to build

### Actual behavior:

Doesn't build

**Comment by GustavoEdinger** [comment]
+1

**Comment by diegolmello** [comment]
That file is auto-generated by Xcode.
Check if this is correct for you.
![image](https://user-images.githubusercontent.com/804994/102388348-61a61380-3fb0-11eb-8b45-3ff459ae8836.png)

**Comment by granttoday** [comment]
> That file is auto-generated by Xcode.
> Check if this is correct for you.
> ![image](https://user-images.githubusercontent.com/804994/102388348-61a61380-3fb0-11eb-8b45-3ff459ae8836.png)

it defaulted to `$(SWIFT_MODULE_NAME)-Swift.h` which used my app's name + Swift.h, by changing it to RocketChatRN-Swift.h it successfully built

**Comment by granttoday** [comment]
It builds, but react errors with

```
Invariant Violation: "RocketChatRN" has not been registered.
```

Is this a related issue, or should I create a new issue regarding this

**Comment by diegolmello** [comment]
It's not really an issue.
Whitelabel docs are dedicated to intermediate devs, who'd be able follow it without any error.
These are questions for StackOverflow.
You most probably changed the app name and Xcode updated this value somewhere else.

**Comment by granttoday** [comment]
> It's not really an issue.
> Whitelabel docs are dedicated to intermediate devs, who'd be able follow it without any error.
> These are questions for StackOverflow.
> You most probably changed the app name and Xcode updated this value somewhere else.

ok thanks anyway!

**Comment by diegolmello** [comment]
Let us know on the comments what's your fix.
I drafted the updated version of the docs and this error never happened btw.

**Comment by granttoday** [comment]
> Let us know on the comments what's your fix.
> I drafted the updated version of the docs and this error never happened btw.

I have figured out what triggered the error. I misread the whitelabel documentation and changed the `name` & `displayName` in app.json, which caused it to build with the wrong name.
