### ISSUE TITLE
4.12.1 cannot be build

### ISSUE THREAD

**Issue by procnedev** [RocketChat/Rocket.Chat.ReactNative#2720]
Greetings,
I started trying RockerChat for the first time but:

- using latest Commit: there is an Error in Runtime when do Login (I can understand that latest commit could broken something)
- using 4.12.1 Release (commit 5cc0856750c24d0fabcf204c1657a6f0da62b4ca) it cannot be build because build procedure stucks in one of Gradle tasks about "playDebug" variant

I should admit that I don't understand why 4.12.1 was marked as "Released" (and it seems the same version uploaded to Google Play Store) if it cannot be built.....

**Comment by diegolmello** [comment]
I didn't get what's going on and the app is on production for a while.
If you need help, you should send more info and follow our issue template.

**Comment by procnedev** [comment]
I do a Clone of repository, a "yarn" command for download all modules/packages and then build the solution using "npx react-native run-android --variant=playDebug" found in package.json file.
After few minutes the build procedure stucks in Gradle task.
This is the console log:

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 3011 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Configure project :@react-native-firebase_analytics
:@react-native-firebase_analytics package.json found at C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\analytics\package.json
:@react-native-firebase_app package.json found at C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\app\package.json
:@react-native-firebase_analytics:firebase.bom using default value: 25.5.0
:@react-native-firebase_analytics package.json found at C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\analytics\package.json
:@react-native-firebase_analytics:version set from package.json: 7.3.1 (7,3,1 - 7003001)
:@react-native-firebase_analytics:android.compileSdk using custom value: 29
:@react-native-firebase_analytics:android.targetSdk using custom value: 29
:@react-native-firebase_analytics:android.minSdk using custom value: 23
:@react-native-firebase_analytics:reactNativeAndroidDir C:\ReactNative\Rocket.Chat.ReactNative\node_modules\react-native\android

> Configure project :@react-native-firebase_app
:@react-native-firebase_app package.json found at C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\app\package.json
:@react-native-firebase_app:firebase.bom using default value: 25.5.0
:@react-native-firebase_app package.json found at C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\app\package.json
:@react-native-firebase_app:version set from package.json: 8.2.0 (8,2,0 - 8002000)
:@react-native-firebase_app:android.compileSdk using custom value: 29
:@react-native-firebase_app:android.targetSdk using custom value: 29
:@react-native-firebase_app:android.minSdk using custom value: 23
:@react-native-firebase_app:reactNativeAndroidDir C:\ReactNative\Rocket.Chat.ReactNative\node_modules\react-native\android

> Configure project :@react-native-firebase_crashlytics
:@react-native-firebase_crashlytics package.json found at C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\crashlytics\package.json
:@react-native-firebase_app package.json found at C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\app\package.json
:@react-native-firebase_crashlytics:firebase.bom using default value: 25.3.0
:@react-native-firebase_crashlytics package.json found at C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@react-native-firebase\crashlytics\package.json
:@react-native-firebase_crashlytics:version set from package.json: 8.1.2 (8,1,2 - 8001002)
:@react-native-firebase_crashlytics:android.compileSdk using custom value: 29
:@react-native-firebase_crashlytics:android.targetSdk using custom value: 29
:@react-native-firebase_crashlytics:android.minSdk using custom value: 23
:@react-native-firebase_crashlytics:reactNativeAndroidDir C:\ReactNative\Rocket.Chat.ReactNative\node_modules\react-native\android

> Configure project :app

Installing unimodules:
 unimodules-core@5.3.0 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@unimodules\core
 unimodules-react-native-adapter@5.4.0 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\@unimodules\react-native-adapter
 expo-av@8.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-av
 expo-constants@9.1.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-constants
 expo-file-system@9.0.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-file-system
 expo-haptics@8.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-haptics
 expo-image-loader@1.1.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-image-loader
 expo-keep-awake@8.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-keep-awake
 expo-local-authentication@9.2.0 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-local-authentication
 expo-permissions@9.0.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-permissions
 expo-video-thumbnails@4.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-video-thumbnails
 expo-web-browser@8.3.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\expo-web-browser
 unimodules-app-loader@1.2.0 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-app-loader
 unimodules-barcode-scanner-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-barcode-scanner-interface
 unimodules-camera-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-camera-interface
 unimodules-constants-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-constants-interface
 unimodules-face-detector-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-face-detector-interface
 unimodules-file-system-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-file-system-interface
 unimodules-font-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-font-interface
 unimodules-image-loader-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-image-loader-interface
 unimodules-permissions-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-permissions-interface
 unimodules-sensors-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-sensors-interface
 unimodules-task-manager-interface@5.2.1 from C:\ReactNative\Rocket.Chat.ReactNative\node_modules\unimodules-task-manager-interface
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :rn-root-view
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergePlayDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:playDebugRuntimeClasspath'.
   > Could not resolve project :reactnativekeyboardinput.
     Required by:
         project :app
      > No matching configuration of project :reactnativekeyboardinput was found. The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'RNNotifications.reactNativeVersion' with value 'reactNative60', attribute 'type' with value 'play', attribute 'com.android.build.gradle.internal.dependency.AndroidTypeAttr' with value 'Aar', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:2.10.2-rc.
     Required by:
         project :app > project :react-native-jitsi-meet
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:2.10.2-rc.
         > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.10.2-rc/jitsi-meet-sdk-2.10.2-rc.pom'.
            > Could not GET 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/2.10.2-rc/jitsi-meet-sdk-2.10.2-rc.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 56s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installPlayDebug -PreactNativeDevServerPort=8081

error Command failed with exit code 1.

**Comment by diegolmello** [comment]
The error says it's a Jitsi issue.
It was fixed on `develop` branch, but not released yet.
Release is planned to happen next Monday.
Can you try that branch?

**Comment by procnedev** [comment]
I found "_fix.jitsi-notification_" branch but it generates a 4.13.xxxx version and not a 4.12.

I would like to understand why on Google Play Store I found a compiled and working 4.12.1 if the specific commit (5cc0856750c24d0fabcf204c1657a6f0da62b4ca) cannot be built successfully.
