### ISSUE TITLE
iOS Project error when run 

### ISSUE THREAD

**Issue by vantudinh** [RocketChat/Rocket.Chat.ReactNative#2725]
error: Build input file cannot be found: '/Users/tudv/Documents/Documents - Tu’s MacBook Pro/ClickStaff/Rocket-Chat-ReactNative/node_modules/react-native/ReactCommon/yoga/yoga/log.cpp' (in target 'Yoga' from project 'Pods')

Please help me !!!

**Comment by darenceang** [comment]
Try launching a terminal and issue the following

```
rm -rf $TMPDIR/"react-*"
rm -rf $TMPDIR/"metro-*"
rm -rf $TMPDIR/"haste-*"
watchman watch-del-all
npm cache clean --force
npm cache verify
rm -rf Rocket.Chat.ReactNative/ios/build
rm -rf Rocket.Chat.ReactNative/ios/node_modules
```

After which, do a yarn && yarn ios again...  
Should then fix the error...

**Comment by vantudinh** [comment]
Trying it!
Thanks you
