### ISSUE TITLE
Android gradle sync failed on single-server

### ISSUE THREAD

**Issue by sadeghpro** [RocketChat/Rocket.Chat.ReactNative#2730]
### Description:
Android gradle sync and also yarn android failed on single-server branch with error:
```
A problem occurred evaluating project ':app'.
> No signature of method: build_9su1sax1oamyt1xqgxd00k8ze.android() is applicable for argument types: (build_9su1sax1oamyt1xqgxd00k8ze$_run_closure1) values: [build_9su1sax1oamyt1xqgxd00k8ze$_run_closure1@7710e97e]
```
It's work with master branch but I have this issue with single-server

**Comment by tymothytym** [comment]
Change line 146 of /android/app/build.gradle (single-server branch)

from

``versionCode VERSIONCODE``

to

``versionCode VERSIONCODE as Integer``

Fixed it for me

**Comment by arsalan-arshad** [comment]
project is totally messed up not working

**Comment by diegolmello** [comment]
@arsalan-arshad If you have an issue, please report it.
I'm marking your comment as disruptive, because I won't tolerate this kind of behaviour.

**Comment by arsalan-arshad** [comment]
@

> @arsalan-arshad If you have an issue, please report it.
> I'm marking your comment as disruptive, because I won't tolerate this kind of behaviour.

i follow all the points from docs

npx react-native run-android --variant=experimentalPlayRelease

not working throwing this error
Task 'experimentalPlayRelease' not found in project ':app'.

**Comment by diegolmello** [comment]
@arsalan-arshad Can you open a new issue?
Your question might not be related to this one.
