### ISSUE TITLE
Consecutive uploads are failing with 4.13.0

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2733]
### Description:

After opening the app I can do one upload (photo, voice message etc.) into a chat. Every following upload does not work, the "Uploading ..." message at the top of the chat stays forever. Leaving the chat and rejoining it gives the same issue, in this case the banner mentions that the upload has failes, a retry gives the same issue (no upload happening).

The app must be force closed to re-enable uploads

### Environment Information:

- Rocket.Chat Server Version: 3.9.3
- Rocket.Chat App Version: 4.13.0
- Device Name: iPhone 11 Pro Max
- OS Version: 14.3

### Steps to reproduce:

1. Join any chat
2. Upload an attachment (photo, video) or record a voice message
3. The upload works fine
4. Upload another attachment
5. The "Uploading ..." banner stays forever and the upload does not work anymore
6. The app must be force-closed and re-opened to allow another upload, the issue continues then (so also in this case you can do only one upload)

### Expected behavior:

Any number of uploads should work

### Actual behavior:

See description above

**Comment by AmatorPhasma** [comment]
Same here:

Rocket.Chat Server Version: 3.9.3
Rocket.Chat App Version: 4.13.0
Device Name: iPad (Gen. 7)
OS Version: 14.3

also other apps can not share data to Rocket.Chat app anymore.
For example: Photo and Safari.
After selecting Rocket.Chat as share destination a empty dialog opens.

**Comment by yash-rajpal** [comment]
Seems like a bug on ios version. I tried on Android device and was able to upload multiple image one after another without any issues.

**Comment by AmatorPhasma** [comment]
> Seems like a bug on ios version. I tried on Android device and was able to upload multiple image one after another without any issues.

Had some checks here:
```
iOS 14.2 + App 4.12.1 = works
iOS 14.3 + App 4.12.1 = works

iOS 14.2 + App 4.13.0 = dosen't work
iOS 14.3 + App 4.13.0 = dosen't work
```

And yes no share problems on Android 7,8,9 (no version 10 available for me)

**Comment by diegolmello** [comment]
I'll take a look and release a 4.13.1 when fixed.

**Comment by AmatorPhasma** [comment]
> I'll take a look and release a 4.13.1 when fixed.

Thank you for the fast response!

**Comment by diegolmello** [comment]
@jacotec @AmatorPhasma #2738 fixes this issue, but there's not enough time to make a patch on App Store.
If you have a whitelabeled app and can't wait, apply the PR changes manually.
I'm going to create a patch as first thing on 2021.

**Comment by jacotec** [comment]
@diegolmello I'll check the fix and will report back. Thanks for your fast fix! :-)

**Comment by jacotec** [comment]
I can confirm your fix solves the issue!

**Comment by AmatorPhasma** [comment]
> @jacotec @AmatorPhasma #2738 fixes this issue, but there's not enough time to make a patch on App Store.
> If you have a whitelabeled app and can't wait, apply the PR changes manually.
> I'm going to create a patch as first thing on 2021.

Can I ask you carefully if there is an ETA for this Patch?

**Comment by diegolmello** [comment]
@AmatorPhasma It's live on Google Play already.
It's waiting for review on App Store.

**Comment by jacotec** [comment]
@diegolmello Ahm, did I overlook something? I'm also waiting for the 4.13.1 as there are a couple of issues fixed to build my 4.13 app version, but I don't see anything in the relases here. If it's already waiting for review why can't I see the release here?

**Comment by diegolmello** [comment]
It's because Apple's review is a process bottleneck.
We have to wait for their approval before starting other tasks (GH release, merge master, docs, etc), because Apple can reject us and all work is going to be lost.

**Comment by jacotec** [comment]
OK, I did not know that you'll merge after the review ;-) Good point! (And agree regarding the bottleneck)
