### ISSUE TITLE
I setup single-server branch and failed to run

### ISSUE THREAD

**Issue by arsalan-arshad** [RocketChat/Rocket.Chat.ReactNative#2740]
I followed all the points from docs

npx react-native run-android --variant=experimentalPlayRelease

not working throwing this error
Task 'experimentalPlayRelease' not found in project ':app'. (and it's having in gradle but not picking)

**Comment by diegolmello** [comment]
@arsalan-arshad What's the commit you're using?
You might want to `git pull` first.
Maybe even clone the repo again.

**Comment by arsalan-arshad** [comment]
> @arsalan-arshad What's the commit you're using?
> You might want to `git pull` first.
> Maybe even clone the repo again.

sir did it but now leave this issue I fixed it. not the other issue is coming when app runs its saying appregistery is not connect it...

**Comment by arsalan-arshad** [comment]
![Uploading Screenshot_1608730902.png…]()

**Comment by diegolmello** [comment]
Follow the docs.
You shouldn't be changing AppRegistry.

**Comment by arsalan-arshad** [comment]
> Follow the docs.
> You shouldn't be changing AppRegistry.

I didn't change yet
