### ISSUE TITLE
4.13.0 IOS - Can't store pictures in gallery

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2741]
### Description:

Tapping on a picture in a chat in IOS, then tapping the "Download" symbol in the upper right always gives "Error saving to gallery". Works flawlessly in 4.12.1.

### Environment Information:

- Rocket.Chat Server Version: 3.9.3
- Rocket.Chat App Version: 4.13.0
- Device Name: iPhone 11 Pro Max
- OS Version: IOS 14.3

### Steps to reproduce:

1. Tap on a picture in a chat to maximize it
2. Tap on the "download" icon in the top right
3. "Error saving to gallery"

### Expected behavior:

The picture should be stored in photo gallery

### Actual behavior:

The picture is not stored, I see the error message mentioned above. Also happening at the official 4.13.0 app of RC.

**Comment by yash-rajpal** [comment]
I can test this on Android version and its working fine. The save to gallery header is rendered from /app/views/AttachmentView.js and earlier we were using FileSystem from react-native-unimodules, but recently we changed to RNFetchBlob to save the attachment to device storage. Can this change cause an issue on ios devices? 
@diegolmello 
Should I revert back changes and make a PR?
Thanks.

**Comment by diegolmello** [comment]
@yash-rajpal do you have iOS to test it?

We can't revert to Expo, because we changed to rn-fetch-blob to be able to use SSL Client Certificate.

**Comment by yash-rajpal** [comment]
@diegolmello no I cant test on ios.
Also I checked, we can directly pass imageurl to cameraRoll.save to save to device for ios.

example :-
`CameraRoll.save(imageurl,{ album: 'Rocket.Chat' })`
