### ISSUE TITLE
Wrong username in push notifications

### ISSUE THREAD

**Issue by Bestoloch** [RocketChat/Rocket.Chat.ReactNative#2744]
### Description:
Get wrong usernames in push notifications

### Environment Information:
- Rocket.Chat Server Version: 3.9.0
- Rocket.Chat App Version: 4.12.1 - 4.13.0
- Device Name: OnePlus 8, OnePlus 8T
- OS Version: Android 11

### Steps to reproduce:
1. Go to private/open **group** chat
2. Send messages from different users
3. Get push notifications on your OnePlus

### Expected behavior:
I can understand who send message in group chat
For example. What I should see:
![image](https://user-images.githubusercontent.com/43439825/103124800-f805c380-4699-11eb-9534-68be2adaca04.png)

### Actual behavior:
I can't understand who send message in group chat

What I see on OnePlus:
![image](https://user-images.githubusercontent.com/43439825/103124857-300d0680-469a-11eb-88ef-5ccaf3101c35.png)

**Comment by Habbie** [comment]
Also observed with:

    RocketChat client 4.13.0.22100
    Server Version 3.9.1
    Nokia 6.1 phone (Model TA-1043, Hardware version 5.0)
    Android 10
    security patch level 1 December 2020
    Google Play system update 2020-10-01

(messages were in a thread)

**Comment by gerzonc** [comment]
I'll be working with this.

**Comment by ankar84** [comment]
I definitely saw similar issue on Android device with version 4.12.1
There was one push notification grouped 3 different messages of 2 different users.
All 3 messages was named by one person (his message was last in that group)
But all users have their own avatars.
So - only names was wrong.
