### ISSUE TITLE
iOS upload fails on second image sent to a channel/DM

### ISSUE THREAD

**Issue by rnsc** [RocketChat/Rocket.Chat.ReactNative#2745]
### Description:

Not sure when this bug appeared, but I've noticed it after upgrading my server to 3.9.3
I can only upload one image with the iOS client and then it fails on the subsequent images uploads.
If I force quit the app, I can re-upload again, but only image, and then, subsequent uploads are left hanging.

### Environment Information:

- Rocket.Chat Server Version: 3.9.3
- Rocket.Chat App Version: 4.13.0.22082
- Device Name: iPhone
- OS Version: 14.3

### Steps to reproduce:

Not sure if this can be reproduced but here's how it goes:
1. Pick one or more photos to upload
2. Only one will be uploaded and the others will fail
3. Force quit the app and you can upload one more, etc...

Not sure if it's related, but trying the share option directly from the Photos app brings up a blank screen when selecting Rocket.Chat.

### Expected behavior:

I used to be able to bulk uploads pictures on my server.

### Actual behavior:

I can only upload one image at a time (with force quits in between).
The upload hangs like this:
![Screenshot 2020-12-25 at 16 49 06](https://user-images.githubusercontent.com/1765108/103138292-500bec80-46d1-11eb-9e50-db6153188a6a.png)
I have to switch conservations to see that it failed:
![Screenshot 2020-12-25 at 16 49 30](https://user-images.githubusercontent.com/1765108/103138295-513d1980-46d1-11eb-9b3d-f24a6b82bf79.png)

**Comment by pastgift** [comment]
I have the same problem.
But uploading file by desktop app and web browser is OK.
This problem only appears on my phone (iPhone 12 Pro Max, 14.2.1)

**Comment by bla55e** [comment]
Same problem. Also, when I’m trying to share pictures straight from my photo roll and choose rocket chat, the next screen with contacts won’t appear. iPhone 11 Pro, iOS 14.3, the same problem was observed on 14.2. On iPhone 7 and iOS 14.1, no problems were observed.

Server version 
2.4.14

I’m using a rocket for many years without any issues. Already tried to reinstall the app, also download the beta version - without success.
--

**Comment by diegolmello** [comment]
Duplicated of #2733
