### ISSUE TITLE
Task :app:mergeDexExperimentalFossRelease FAILED

### ISSUE THREAD

**Issue by huytx0909** [RocketChat/Rocket.Chat.ReactNative#2750]
### Environment Information:

- Rocket.Chat Server Version: 3.9.1
- Rocket.Chat App Version: 4.13.0
- Device Name: 
- OS Version: Linux Ubuntu 18.04

### Steps to reproduce:

1. 
I checked out the `single-server` branch, followed the instructions here: 
https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#general-setup-1

2. 
When I want to generate the app.aab file, I ran this: 
```
cd android
./gradlew bundleRelease
```

### Expected behavior:

The app.aab file is generated

### Actual behavior:

This error appears: 
```
> Task :app:mergeDexExperimentalFossRelease FAILED

FAILURE: Build failed with an exception.
```

### Additional context:
![image](https://user-images.githubusercontent.com/29868399/103282785-6d122980-4a09-11eb-8109-00fd01930df9.png)
![image](https://user-images.githubusercontent.com/29868399/103282831-86b37100-4a09-11eb-9782-54f921517a1b.png)

My version of `react-native`: 
![image](https://user-images.githubusercontent.com/29868399/103282880-a9de2080-4a09-11eb-808e-e6d0a4ad41a6.png)

Please help me resolve this

**Comment by toshanmugaraj** [comment]
Duplicate issue #2721
