### ISSUE TITLE
Notifications never registering

### ISSUE THREAD

**Issue by granttoday** [RocketChat/Rocket.Chat.ReactNative#2753]
### Description:

Push notifications don't register on whitelabel iOS. On first run, app asks for notification permission but doesn't notify server about deviceID and after digging around the app doesn't appear to register itself.

Do I need to import anything into xcode to get notifications working? I've created all of the certificates and uploaded them to my RC instance and added them to my keychain.

### Environment Information:

- Rocket.Chat Server Version: 3.9.1
- Rocket.Chat App Version: 4.12.1.1 (single-server)
- Device Name: ios
- OS Version: 14.3

### Steps to reproduce:

1. 
2. 
3.

**Comment by diegolmello** [comment]
Follow the docs https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps

**Comment by granttoday** [comment]
To anyone else that runs into this issue, remote notifications _do not work_ on the iOS simulator.
