### ISSUE TITLE
Refactor code to remove deprecated componentWillReceiveProps() lifecycle function

### ISSUE THREAD

**Issue by ARKEOLOGIST** [RocketChat/Rocket.Chat.ReactNative#2754]
### Description:

Multiple files in the project use the componentWillReceiveProps() lifecycle method which should be replaced.

### Additional context:

componentWillReceiveProps() is a legacy lifecycle method and has been deprecated according to the official React docs (https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops). It's better to replace it with componentWillUpdate() wherever possible or rewrite the sections using it to remove the need for using it.

**Comment by yash-rajpal** [comment]
I agree, we can also use getDerivedStateFromProps() along with componentWillUpdate() instead of componentWillReceiveProps(). Are you working on this? If not, I would love to work on it.

**Comment by ARKEOLOGIST** [comment]
@yash-rajpal I'll be working on this, but I would definitely love to collaborate with you for the code migration.

**Comment by yash-rajpal** [comment]
Sure, I am happy to collaborate. Can you ping me at https://open.rocket.chat/direct/yash_rajpal, so that we can talk this through.
Thanks.

**Comment by diegolmello** [comment]
Thanks, guys. Just don't forget that `componentWillUpdate` is also deprecated.

**Comment by ARKEOLOGIST** [comment]
@diegolmello Should I open a new issue for that or consider it to be a part of this only?

**Comment by diegolmello** [comment]
No, it's fine
