### ISSUE TITLE
Not showing users and statuses in direct messages between multiple users

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat.ReactNative#2756]
### Environment Information:

- Rocket.Chat Server Version: 3.10.0-rc.2
- Rocket.Chat App Version: 4.13.1.22127
- Device Name: Samsung S20
- OS Version: Android 11

### Steps to reproduce:

1. Log in to the app.
2. Create a conversation between multiple users
3. Click on the top conversations title
4. Click `Members` --> nothing is shown
5. Click `All` --> nothing is shown

![image](https://user-images.githubusercontent.com/11751017/103539492-7b909300-4e98-11eb-8bf4-b797bd3b0bbf.png)

### Expected behavior:

Users that are online are shown when clicking `Members` link.
All users in the conversation are shown when clicking `All` link.

### Actual behavior:

Neither online, nor all users are listed in the Members section for direct messages between multiple users.

### Additional context:

Might be dependent on https://github.com/RocketChat/Rocket.Chat/issues/20040

**Comment by diegolmello** [comment]
@zdumitru You're right.
It's requiring a change on the backend.
Thanks.

**Comment by zdumitru** [comment]
@diegolmello Backend part has been fixed [here](https://github.com/RocketChat/Rocket.Chat/pull/21452) and on desktop is shown status for all users when having direct messages between multiple users. So I believe that this issue for mobile part is ready to be worked on.

**Comment by diegolmello** [comment]
Awesome.
I'll bring it up on next sprint planning.
Thanks for letting us know.

**Comment by chaitanyareddy02** [comment]
**Environment Information:**

Rocket.Chat Server Version: 4.6.0
Rocket.Chat App Version: 4.26.2
Device Name: Realme 3pro
OS Version: Android 11

I had checked its showing the user profiles

https://user-images.githubusercontent.com/96861060/163785347-3c5ea1fb-2f36-4aa4-9187-30f843c6709a.mp4

**Comment by diegolmello** [comment]
@zdumitru is this fixed?

**Comment by chaitanyareddy02** [comment]
yes i think, because its working as expected behaviour,for online people its not showning the active circle if it added then it would be good in the view of ux.
