### ISSUE TITLE
[Bug] Videos do not play on iOS devices

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat.ReactNative#2759]
### Description:
Videos do not play on iOS devices at all.

### Environment Information:

- Rocket.Chat Server Version: 3.9.3 (Snap)
- Rocket.Chat App Version: 4.13.0.22082
- Device Name: iPhone 6s
- OS Version: iOS 13.7

### Steps to reproduce:

1. Shoot video on phone and upload to Rocket Chat

### Expected behavior:
Video plays fine for self and other users

### Actual behavior:
Video does not play but it works okay on Desktop and Web app.

### Additional context:
N/A for now.

**Comment by diegolmello** [comment]
What happens when you try to play the video?
Does the app crashes? Does it hang?
Can you try on https://open.rocket.chat?

**Comment by nooblag** [comment]
No crashes as far as I know (which is little). But the app seems to hang if you tap the video to play. This is what happens:

https://user-images.githubusercontent.com/1122344/103729273-31dcaf80-5034-11eb-8254-176b6570a24a.mp4

I tried same on open.rocket.chat but there doesn't seem to be an issue there.

https://user-images.githubusercontent.com/1122344/103729410-7e27ef80-5034-11eb-8d7b-7d28dd3c9b21.mp4

**Comment by diegolmello** [comment]
It could be an issue with your file storage service taking too long to load the file.
We've been using S3 on open.
If you let the app load the video for 5~10 minutes, does it load?
Can you debug the app and make sure the URL is properly set on your server?

**Comment by nooblag** [comment]
I'm not sure it's a file system speed issue if the video loads fine on Desktop and Web versions of the app? But I will test your suggestions and get back to you.

As to the second part, how do I "debug the app"?

Also, for some more context, this issue has appeared for me on two separate RC installs that both use Snap on Ubuntu 20. Could there be a problem there?

**Comment by nooblag** [comment]
Here is another run, leaving it sit for over 8 minutes. It does not play.

https://user-images.githubusercontent.com/1122344/103875645-cc1d2000-5126-11eb-9f84-8ef0366115ae.mp4

**Comment by diegolmello** [comment]
Ok.
If it works on open server, then we need to check what might be happening on your server.
Can you create a test user there and send me on https://open.rocket.chat/direct/diego.mello?
Thanks.

**Comment by nooblag** [comment]
Sure, thanks.

**Comment by nooblag** [comment]
Issue persists in 3.10.3.

**Comment by hungnb94** [comment]
It may issue involve storage type.
Let's change Storage Type to GridFS then try upload another video file.
I change to GridFS then my server work well. Hope this help you

![Screen Shot 2021-01-21 at 13 59 27](https://user-images.githubusercontent.com/30073979/105314983-418df380-5bf1-11eb-8ec0-59e3b0eeab93.png)

**Comment by nooblag** [comment]
Thanks @hungnb94, playback and uploads seem okay now on iOS with GridFS as the Storage Type!

I wonder why the problem with FileSystem however?

**Comment by hungntq** [comment]
@nooblag It's is bug from server.
For more detail you can check [here](https://stackoverflow.com/a/42244954).

Currently Rocket.Chat server does not support http request with by range 0-1 for FileSystem. It always return response code 200. But on iOS it need response code 206 to stream video.
I will try to create pull request for this bug on server

**Comment by diegolmello** [comment]
That's huge, @hungntq.
Thanks a lot from your response.

I'm closing this issue here until we have a fix on the server and we're sure there's something to be done on mobile, ok?

**Comment by hungntq** [comment]
Chan Shing Kit already created a [pull request](https://github.com/RocketChat/Rocket.Chat/pull/20203) to fix this issue on server.
I think it will be merge soon. I hope it will help you fix problem
