### ISSUE TITLE
SSO login (SAML with optional mutual TLS) doesn't work in the Android app

### ISSUE THREAD

**Issue by jangaraj** [RocketChat/Rocket.Chat.ReactNative#2761]
### Description:

SSO login doesn't work in the Android app.

### Environment Information:

- Rocket.Chat Server Version: 3.5.1
- Rocket.Chat App Version: 4.13
- Device Name: Xperia XZ1
- OS Version: Android 9

### Steps to reproduce:

Try to login with offered preconfigured IDP (SAML based SSO) - white screen with SSO title is displayed.

### Expected behavior:

IDP login screen (IDP html login page) should be displayed - it works fine in the previous releases, e.g. 4.1.1 

### Additional context:

IDP offers optional mutual TLS (IDP server sends which CA certs are accepted during TLS handshake), so root cause can be this PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2624
SSO login works in the browser and in the most recent Windows App. Only the most recent Android app has a problem. Nothing useful in the Android logs. I don't have access to server logs. Previous version of Android app 4.12.1 works fine. Android itself doesn't have any user certs installed - I don't want to use mutual TLS, but I want standard username/password for my SSO login.

**Comment by faffeldt** [comment]
This issue also appears on an OnePlus 5T with Android 10 for the same target Rocket.Chat Server which @jangaraj is trying to use. Some additional info is that the IDP only accepts client certificates which are issued by specific CAs. So it would be interesting to know what the HTTP Header `ssl-client-cert` looks like in case there is no specfic client certificate on the device. Is it not set, missing or does Android provide a default Client Certificate based on the Google Account and the devices TPM capabilites?

**Comment by diegolmello** [comment]
Thanks for opening, @jangaraj .
Can you reach me on https://open.rocket.chat/direct/diego.mello?
I need to test it on your server.

**Comment by jangaraj** [comment]
It looks like there is no IDP request if client certs are enabled on the IDP, so only blank SSO page is generated for the Android app user. It can be tested with `openssl s_client -connect <idp hostname:port>` - there will be `Acceptable client certificate CA names` if client certs are enabled.

**Comment by diegolmello** [comment]
Duplicated of #2452
