### ISSUE TITLE
Jitsi Chat is not available on IOS in Single-Server

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2780]
### Description:

During a Jitsi Video call, in the Android app I have the chat symbol left from the microphone button. I can join the Jitsi chat with this button and participate.

In the IOS version this symbol ist just not there and I have no ability to join the Jitsi chat during a video call.

### Environment Information:

- Rocket.Chat Server Version: 3.9.4
- Rocket.Chat App Version: 4.13.1
- Device Name: iPhone 11 Pro Max
- OS Version: IOS 14.3

### Steps to reproduce:

1. Participate in a Jitsi Video call on an iPhone
2. You don't see any notifications if someone writes into the Jitsi Chat
3. There is no chat symbol left from the microphone button like in the Android version, nor any other GUI Element to join the Jitsi chat.

### Expected behavior:

Should be par with Android and the Web app where the Jitsi chat can be used during a video call

### Actual behavior:

There is no way to join the Jitsi chat during a video call in IOS

**Comment by ankar84** [comment]
Not confirm for iOS RCRN application version 4.13.1.22188
Chat button exist and works fine

**Comment by jacotec** [comment]
OK ... double checked and it's there in the official app but not in my whitelabeled version built from the official 4.13.1 release.

So the issue might be just in the single-server branch.

**Comment by diegolmello** [comment]
@jacotec clear all single-server build cache and try again.
Remove `ios/build`, `ios/Pods` and `node_modules`.

**Comment by jacotec** [comment]
@diegolmello The

```
yarn remove react-native-jitsi-meet
yarn add RocketChat/react-native-jitsi-meet
```

I needed to build Android also fixed this issue. I'll close the issue (but will open a new one I've discovered in the Jitsi chat ;-) ).
