### ISSUE TITLE
Jitsi Chat - Sending with "paper plane" icon in the message bar is not working properly

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2782]
### Description:

When you use the Jitsi Chat in a video call, there are two options to send what you have typed:
- The blue "Send" key in the keyboard
- The "paper plane" symbol right from the message entry box

The keyboard button usually works, but when you press the "paper plane" icon to send something, in most cases the complete chat slips behind the keyboard, so that the lower half of the conversation is not visible anymore. Also the message you've sent with the paper plane icon is not there!
You need to leave and rejoin the chat to see the full chat again.

https://user-images.githubusercontent.com/3321655/104192125-b0fc2a00-541e-11eb-993a-e906bb6d6d57.mov

### Environment Information:

- Rocket.Chat Server Version: 3.10.3
- Rocket.Chat App Version: 4.13.1
- Device Name: iPhone 11 Pro Max
- OS Version: IOS 14.3

### Steps to reproduce:

1. Join a Jitsi chat in a video call
2. Send your text not by the keyboard button but with the "paper plane" icon in the message box
3. The chat "slips" behind the keyboard which is still in the foreground
4. The text which was sent by the paper plane icon is missing in the chat

### Expected behavior:

The paper plane icon should work the same way than the "send" button of the keyboard.

### Actual behavior:

See above

**Comment by diegolmello** [comment]
That's related to the Jitsi repo.
