### ISSUE TITLE
[IMPROVEMENT] 'New Message' text should be greyed out

### ISSUE THREAD

**Issue by ArchdukeTim** [RocketChat/Rocket.Chat.ReactNative#2784]
### Description:

In the rocket chat iOS app, the 'New Message' placeholder text is the same color as regular text, making it hard to distinguish as a placeholder.  The text should be greyed out, similar to the desktop app. 

### Environment Information:

- Rocket.Chat Server Version: 3.9.4
- Rocket.Chat App Version: 3.12.1
- Device Name: iPhone 11
- OS Version: iOS 14

### Expected behavior:

Placeholder text has different text color than regular text

### Actual behavior:

Placeholder text color is the same as regular text

**Comment by adityarajsinghvi** [comment]
@diegolmello is this issue resolved or can i take it?
