### ISSUE TITLE
app exit when you start direct messaging under E2E model

### ISSUE THREAD

**Issue by liushmh** [RocketChat/Rocket.Chat.ReactNative#2787]
### Environment Information:

- Rocket.Chat Server Version: 
- Rocket.Chat App Version: 4.13.xx
- Device Name: android / iphone
- OS Version: android 10 / ios 13.7

### Steps to reproduce:

1. Turn on E2E at server administration
2. Change your E2E password
2. Go to NewMessageView
3. find a new user to start a new conversation
4. input some content and send

### Expected behavior:

content is encrypted and delivered

### Actual behavior:

app exit

**Comment by liushmh** [comment]
I found the reason
when you do change E2E password, it calls

```
const publicKey = await UserPreferences.getStringAsync(`${ server }-${ E2E_PUBLIC_KEY }`);
await RocketChat.e2eSetUserPublicAndPrivateKeys(EJSON.stringify(publicKey), encodedPrivateKey);
```

the publicKey is a pure string, not a json object, 
after EJSON.stringify, it will add some escape char, such as " and \

server gets the E2E public key string and save it into the database, 
the E2E public key in db will be a string with lots of " and \ 

when you create a new direct message, the app will call function encryptRoomKeyForUser
inside the function, it will call EJSON.parse
`
const userKey = await SimpleCrypto.RSA.importKey(EJSON.parse(publicKey));
`
but since the E2E public key string contains " and \ , it will cause an unexpected token error and exit the app.


Remove EJSON.stringify() of this code
`await RocketChat.e2eSetUserPublicAndPrivateKeys(EJSON.stringify(publicKey), encodedPrivateKey);`

could fix the issue.

**Comment by diegolmello** [comment]
@liushmh Can you open a PR?

**Comment by diegolmello** [comment]
I wasn't able to reproduce this issue.
Can you try it on latest server and app version?
