### ISSUE TITLE
App doesn't respect jitsi server settings: startWithAudioMuted and/or startWithVideoMuted

### ISSUE THREAD

**Issue by AmatorPhasma** [RocketChat/Rocket.Chat.ReactNative#2796]
### Description:

App doesn't respect jitsi server settings: startWithAudioMuted and/or startWithVideoMuted

### Environment Information:

- Rocket.Chat Server Version: 3.9.4
- Rocket.Chat App Version: 4.13.1.22188 (iOS) / 4.13.1.22189 (Android)
- Device Name: iPad (Gen8) / Android (Emulator)
- OS Version: iOS 14.3 / Android 7,8,9,10

### Steps to reproduce:

1. Setup Jitsi with:
```
  startWithAudioMuted: true,
  startWithVideoMuted: true,
```
2. Start jitsi call with app or join one with this settings active.

### Expected behavior:
Same as [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron) or any browser (Firefox, Chrome, Opera) start call without active audio or video.

### Actual behavior:
- Voicecall: starts with audio enabled, ignores jitsi settings
- Videocall: starts with audio and video enabled, ignores jitsi settings

**Comment by ankar84** [comment]
Could be that JitsiSDK just not support that settings.
You better ask about that in Jitsi repo first.
