### ISSUE TITLE
Rocket chat whitelabel - cannot login to workspace

### ISSUE THREAD

**Issue by C1ean** [RocketChat/Rocket.Chat.ReactNative#2803]
### Description:
Problem only for whitelabel build (from develop branch), app from appstore is work correct

The login to the workspace does not work - the button does not respond to any input data.
https://user-images.githubusercontent.com/3279295/104205920-01d04a80-5440-11eb-9678-76f142f48c12.mp4

After building the last build of Rocket Chat repo for ios (4.13.1) 
and creating the archive and distribute ipa - the problem still exists, and after installing the application, 
I think this is an build problem, it does not depend on the device (tried it on 3 different ones)

But, on Debug Build - everything works correctly

The problem appeared after 4.10. + Version. (last work version 4.7.)
I can't understand what's going on.

by the way, may be the problem appeared after the improvement to save the history of the entered urls..
p.s I also tried to change the applcation_id - so that the assembly was clean, it did not help.

As I understand it, in the case of the debug version, the code is collected when starting from the jsbundle, in the case of the release version - it has already been minified and built. Perhaps this could be the problem? Some time ago, I build bundle before release with
`react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`
I don’t do this now, but with this approach the result is the same now :(

### Environment Information:

- Rocket.Chat Server Version: 3.5.1
- Rocket.Chat App Version: 4.13.1
- Device Name:  Iphone 11 Pro 
- OS Version: 14.2

### Steps to reproduce:

1. Open app
2. Click Join a workspace
3. Try to enter workspace URL and click Connect

### Expected behavior:

See a login screen

### Actual behavior:

Nothing happens

### Additional context:
App from AppStore is work correct
App wich build with Debug works perfect too..

**Comment by playing771** [comment]
I had similar problem in IOS (4.13.1 single-server branch). 

After entering any valid credentials and pressing login button i cant proceed further to the next screen.

After debugging a bit i noticed catched error "key does not present".
In my case the problem was in UserPreferences storage and setStringAsync method. 

removing line ".withEncryption()" solved my issue...

**Comment by C1ean** [comment]
Yes, it's very strange, but it helped me too...
remove .withEncryption() from userPreference.js

@diegolmello what do you think about this?

**Comment by diegolmello** [comment]
Maybe updating react-native-mmkv-storage fixes it.
Reference:
- https://github.com/ammarahm-ed/react-native-mmkv-storage/issues/31#issuecomment-678605383
- https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/ios/Podfile.lock#L187

Can you guys test if it's the case?
We don't want to disable encryption for user credentials and we'd appreciate PRs.
Thanks!

**Comment by C1ean** [comment]
@diegolmello  yes, it works for me!! thanks!
PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2846

**Comment by diegolmello** [comment]
@C1ean is this related to #2533

**Comment by amoebav** [comment]
I have this issue in iOS, but not in Android.
v4.14.0

**Comment by RaviGaruda** [comment]
i have same issue in android app, i also update react-native-mmkv-storage to latest version 0.4.3 but still i'm can't login

**Comment by amoebav** [comment]
I updated react-native-mmkv-storage and that fixed it for me as well for the iOS app.

**Comment by newmanw** [comment]
I am seeing the same thing on both iOS and Android, with the exception that neither debug nor release seems to work.  I am currently running single-server branch after 4.15.0 release. 

I have tried updating MMKV on the iOS side, still the issue persists.  Although since I am seeing this on Android as well, something else must be going on.

**Comment by DiamoandDog** [comment]
Try uninstalling the app and then reinstall it, which is how I solved it

**Comment by amoebav** [comment]
I just compiled and tested for iOS mobile app on v4.36.0.1 and this is still an issue. I tried to login, but it just sits there and spins.  

I will try updating react-native-mmkv-storage again to see if it fixes like last time.

**Comment by amoebav** [comment]
> Is this still valid? We updated MMKV (as on #2846) on #3634

I just compiled v4.36.0.1 for iOS and got this issue. However, this time, when I press login I see the spinning indicator acting like it's doing something, but it never logs in.
