### ISSUE TITLE
Bug on Android: Notification only shows one name

### ISSUE THREAD

**Issue by jeyemwey** [RocketChat/Rocket.Chat.ReactNative#2806]
### Description:

This issue is in regards to the grouped notification that you get from Android if someone wrote in a channel that you monitor.

![Screenshot_20210115-231320~2](https://user-images.githubusercontent.com/2796271/104785346-91e8f980-578a-11eb-90f7-439648754d85.png)

This conversation had two people, but only one of the authors was attributed correctly. Also, the avatar image only shows the image of the first person.

If I see it correctly, the account displayed can change if many messages are combined in one notification. I am however not sure if the name is the one of the first, first of stack or last user that has sent a message.

### Environment Information:

- Rocket.Chat Server Version: 3.9.3 (hosted on *.rocket.chat)
- Rocket.Chat App Version: 4.13.1.22189
- Device Name: Google Pixel 3a
- OS Version: Android 11

### Steps to reproduce:

1. Have a channel with you and at least two other accounts.
2. Log in to your account with your android phone and activate notifications.
3. Go offline and wait for incoming messages in this channel that are pushed with a notification and grouped.

### Expected behavior:

I would expect to see both usernames attributed correctly.

### Actual behavior:

This is how the chat actually looked like:

![Screenshot_20210115-232422](https://user-images.githubusercontent.com/2796271/104785577-205d7b00-578b-11eb-8344-e8c94c5298ac.png)

As you can see, the conversation is partly attributed to the wrong people.

**Comment by ankar84** [comment]
I definitely saw similar issue on Android device with version 4.12.1
There was one push notification grouped 3 different messages of 2 different users.
All 3 messages was named by one person (his message was last in that group)
But all users have their own avatars.
So - only names was wrong.

**Comment by gerzonc** [comment]
This is a duplicate issue (See #2744). I'm closing it.

**Comment by jeyemwey** [comment]
Yes, thanks for noticing!
