### ISSUE TITLE
Make Jest reporting cleaner

### ISSUE THREAD

**Issue by pratyaksh123** [RocketChat/Rocket.Chat.ReactNative#2810]
### Description:

Jest prints all console messages, whether from our own code, third-party framework code, or the test runner itself, so It's easy to lose actually important warnings among the noise. 

We can use [jest-clean-console-reporter](https://github.com/jevakallio/jest-clean-console-reporter) , it collects all console messages written by the test process and allows you to group them by known error warning types, or ignore them outright.
![image](https://user-images.githubusercontent.com/55044774/104948273-0d44e800-59e3-11eb-8259-013b7b8ae81b.png)

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name: 
- OS Version: 

### Steps to reproduce:
Run Jest

**Comment by diegolmello** [comment]
@pratyaksh123 That would be awesome to have!
Can you work on it?

**Comment by pratyaksh123** [comment]
Yeah sure, but can you tell me which warnings or errors should we group? 
I see a lot of `PropTypes` and `react-test-renderer` warnings. I'm not sure which warnings or errors are redundant.
