### ISSUE TITLE
in iOS devices, Able to receive Firebase direct notifications but NOT able to receive rocketChat messages when app is in background mode. 

### ISSUE THREAD

**Issue by rajkumarbhaji** [RocketChat/Rocket.Chat.ReactNative#2814]
I pulled latest release 4.13.1 and made all the settings related to PushNotifications and Firebase as below documentation. 
https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps

Now the problem is: in iOS devices, We are not able to receive the Chat messages when the application is NOT in foreground / in Background.
However, when we push some messages directly from Firebase console, then the push notification is working fine in iOS devices. 

Note: Everythings is working fine in Android. But iOS we are unable to get messages when app is in background mode.

**Comment by JakobZeller** [comment]
I got the same or at least a similar issu. I configured the app according to the documentation but push notifications for iOS don't seem to work. Android works fine but iOS won't show any push notification, neither from chatting nor from Firebase console.

The in-app "notifications" are working on android and iOS.

**Comment by diegolmello** [comment]
iOS app uses APNS, not Firebase.

**Comment by rajkumarbhaji** [comment]
@diegolmello Thank you. Could you please post any documentation to setup APNS ??

**Comment by diegolmello** [comment]
https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#configuring-ios

**Comment by JakobZeller** [comment]
I configured my app step by step following exactly this documentation.

**Comment by rajkumarbhaji** [comment]
@diegolmello I just did once again by following the documentation step by step. Still I am not able to receive the chat messages when app is in background.

**Comment by rajkumarbhaji** [comment]
@JakobZeller Is it working fine for you??

**Comment by JakobZeller** [comment]
@rajkumarbhaji It's the same issue I described in my first post and you are experiencing. 

@diegolmello I am using the single-server branch and set a breakpoint in NotificationService.swift line 10. The breakpoint is never reached.
