### ISSUE TITLE
npm ERR! ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by raghav-khunger** [RocketChat/Rocket.Chat.ReactNative#2816]
### Description:
Getting the following error while running npm install: 

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rocket-chat-reactnative@0.0.1
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"RocketChat/react-native#0.63.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@">=0.57 <=0.62" from @react-native-community/cameraroll@4.0.1
npm ERR! node_modules/@react-native-community/cameraroll
npm ERR!   @react-native-community/cameraroll@"^4.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/raghavkhunger/.npm/eresolve-report.txt for a full report.
```

### Environment Information:

- Rocket.Chat Source:  4.13.1 source code from master branch
- OS Version: macOS Big Sur, Version 11.1
- Machine: MacBook Air (Retina, 13-inch, 2020) 
- Editor: VSCode, Version: 1.52.1

### Steps to reproduce:

1. Clone the project from master branch
2. Run npm install

### Expected behavior:
npm install should have worked

### Actual behavior:
npm install throwing error

### Screenshot

![image](https://user-images.githubusercontent.com/904902/105169547-b0ac0f00-5b41-11eb-9d35-158f75456fda.png)

### Log

**0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.6.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@7.4.0
2 info using node@v15.6.0
3 timing config:load:defaults Completed in 4ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
5 timing config:load:builtin Completed in 4ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/raghavkhunger/GitProjects/Rocket.Chat.ReactNative/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/raghavkhunger/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 17ms
19 verbose npm-session 42a6f9806217656c
20 timing npm:load Completed in 40ms
21 timing arborist:ctor Completed in 1ms
22 timing arborist:ctor Completed in 1ms
23 timing idealTree:init Completed in 964ms
24 timing idealTree:userRequests Completed in 0ms
25 silly idealTree buildDeps
26 silly fetch manifest @codler/react-native-keyboard-aware-scroll-view@1.0.1
27 http fetch GET 304 https://registry.npmjs.org/@codler%2freact-native-keyboard-aware-scroll-view 930ms (from cache)
28 silly fetch manifest react-native@https://codeload.github.com/RocketChat/react-native/tar.gz/616299bbc01eeb56cb7d5b52e543051e1ad2d136
29 http fetch GET 304 https://codeload.github.com/RocketChat/react-native/tar.gz/616299bbc01eeb56cb7d5b52e543051e1ad2d136 2193ms (from cache)
30 silly fetch manifest react@16.13.1
31 http fetch GET 304 https://registry.npmjs.org/react 93ms (from cache)
32 silly fetch manifest @nozbe/watermelondb@0.19.0
33 http fetch GET 304 https://registry.npmjs.org/@nozbe%2fwatermelondb 310ms (from cache)
34 silly fetch manifest @react-native-community/art@1.2.0
35 http fetch GET 304 https://registry.npmjs.org/@react-native-community%2fart 275ms (from cache)
36 silly fetch manifest @react-native-community/async-storage@1.11.0
37 http fetch GET 304 https://registry.npmjs.org/@react-native-community%2fasync-storage 97ms (from cache)
38 silly fetch manifest @react-native-community/blur@3.6.0
39 http fetch GET 304 https://registry.npmjs.org/@react-native-community%2fblur 279ms (from cache)
40 silly fetch manifest @react-native-community/cameraroll@4.0.1
41 http fetch GET 304 https://registry.npmjs.org/@react-native-community%2fcameraroll 271ms (from cache)
42 timing idealTree Completed in 9932ms
43 timing command:install Completed in 9966ms
44 verbose stack Error: unable to resolve dependency tree
44 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:25)
44 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1041:36)
44 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:796:11)
44 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
44 verbose stack     at async Promise.all (index 1)
44 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:124:5)
44 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
45 verbose cwd /Users/raghavkhunger/GitProjects/Rocket.Chat.ReactNative
46 verbose Darwin 20.2.0
47 verbose argv "/usr/local/Cellar/node/15.6.0/bin/node" "/usr/local/bin/npm" "install"
48 verbose node v15.6.0
49 verbose npm  v7.4.0
50 error code ERESOLVE
51 error ERESOLVE unable to resolve dependency tree
52 error
53 error While resolving: [1mrocket-chat-reactnative[22m@[1m0.0.1[22m
53 error Found: [1mreact-native[22m@[1m0.63.4[22m[2m[22m
53 error [2mnode_modules/react-native[22m
53 error   [1mreact-native[22m@"[1mRocketChat/react-native#0.63.4[22m" from the root project
53 error
53 error Could not resolve dependency:
53 error [35mpeer[39m [1mreact-native[22m@"[1m>=0.57 <=0.62[22m" from [1m@react-native-community/cameraroll[22m@[1m4.0.1[22m[2m[22m
53 error [2mnode_modules/@react-native-community/cameraroll[22m
53 error   [1m@react-native-community/cameraroll[22m@"[1m^4.0.1[22m" from the root project
53 error
53 error Fix the upstream dependency conflict, or retry
53 error this command with --force, or --legacy-peer-deps
53 error to accept an incorrect (and potentially broken) dependency resolution.
53 error
53 error See /Users/raghavkhunger/.npm/eresolve-report.txt for a full report.
54 verbose exit 1
**

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md#how-to-run

Docs advise you to use `yarn`.
