### ISSUE TITLE
In iPad mini 5th generation can't share photo from the Files or Photos app to chat

### ISSUE THREAD

**Issue by ronakT-addweb** [RocketChat/Rocket.Chat.ReactNative#2819]
### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name:  iPad mini 5th generation 
- OS Version: 14.2

### Steps to reproduce:

1.  Go to 'Photos' 
2. Click on 'share icon'
3. Select Rocket Chat 

### Expected behavior:

 What we expect to happen
It souls share the photo with the chat in Rocket chat. and should open chat list in dialog.
### Actual behavior:

What actually happens with SCREENSHOT

http://prnt.sc/xcj627

**Comment by diegolmello** [comment]
What's your app version?
Did you see https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2760#issuecomment-764460416?
