### ISSUE TITLE
iPhone 12 can't use the share option in iOS (Safari or Photos App), blank window shows up

### ISSUE THREAD

**Issue by User6554** [RocketChat/Rocket.Chat.ReactNative#2822]
### Description:

Unable to use the iOS share feature to send attachment via Rocket.Chat
### Environment Information:

- Rocket.Chat Server Version: 3.9.3
- Rocket.Chat App Version: 4.14.0.22470 (Beta right now, 2021-01-21)
- Device Name: iPhone 12 256GB
- OS Version: iOS 14.3

### Steps to reproduce:

1. Click on the share icon on iOS (tested in Safari and Photos App)
2. Select Rocket.Chat App

### Expected behavior:

It should open Rocket.Chat to share the file

### Actual behavior:

A blank window opens (refer to the screenshot below)
![IMG_5955AD2AE7CC-1](https://user-images.githubusercontent.com/77775128/105396080-c1cb4d80-5c1f-11eb-9336-b87dad942f55.jpeg)

### Additional context:

The same procedure was performed, with the same server and application versions, on an iPad Pro 2nd gen. I was not able to share the content. The same blank window came up.

**Comment by ankar84** [comment]
Same on iPhone 8
Could be fixed by https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2788

**Comment by diegolmello** [comment]
He tested new beta, but the error persists https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2760#issuecomment-764834058
We'll have to plan a deep refactor to the share extension.
Sadly, we don't have control over memory and it's really limited on iOS for share extensions.

**Comment by jacotec** [comment]
Unfortunately many users told me that my most hated app (the data vac named WhatsApp) does not seem to have any limitations to send pix and vids via share extension. What magic do they use?

**Comment by diegolmello** [comment]
> Unfortunately many users told me that my most hated app (the data vac named WhatsApp) does not seem to have any limitations to send pix and vids via share extension. What magic do they use?

Unlimited resources 🤷‍♂️

**Comment by jacotec** [comment]
> Unlimited resources 🤷‍♂️

lol :-) 
What I've meant is that they should run into the same IOS limits for the share extensions, or am I doing wrong here?

**Comment by diegolmello** [comment]
No, you're kind of right.
Besides the team size (e.g. they can afford to have a squad focused on share extension), they are a native app (advanced memory management) and aggressive compress media (larger the media, larger memory to be held).
But we still have a few techniques to fix this :)

**Comment by User6554** [comment]
@diegolmello That sound promising, a fix for it would be really great. To those trying to fix it, I really appreciate it! Thank you very much.

**Comment by serge-petrov** [comment]
I have the same issue. 
Two identical servers Ubuntu 20.04:
Version
3.14.4
Apps Engine Version
1.25.0
Node Version
v12.22.1
Database Migration
222 
MongoDB
3.6.14 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (ba6337c2b)
Branch: HEAD

First one works fine but the second one causes blank screen while sharing attachment from another app. I use the same iPhone SE2 and Rocket 4.16.2.23928 for both cases.
