### ISSUE TITLE
Not able to load script from metrobundler.

### ISSUE THREAD

**Issue by dev7050** [RocketChat/Rocket.Chat.ReactNative#2829]
Hello Team,

### Description:

After installing node_modules and pods, The project (debug) successfully builds on simulator but it stuck on splash screen. Actually after launch the app doesn't loads scrips from metro bundler. Any help will be appreciated.

### Environment Information:

- Rocket.Chat App Version: Current Develop branch
- OS Version: 10.15.7
- Xcode Version: 12.3

### Expected behavior:

App should load scripts

### Actual behavior:

Stuck on splash and doesn't load scripts

### Additional context:

Tried changing ports and available solutions but no luck .

**Comment by yash-rajpal** [comment]
Can you please provide more description?

A video would be great.

**Comment by dev7050** [comment]
> Can you please provide more description?
> 
> A video would be great.

Added Description

**Comment by yash-rajpal** [comment]
Are you using yarn ios command to start app??

**Comment by dev7050** [comment]
> Are you using yarn ios command to start app??

Building from xcode

**Comment by yash-rajpal** [comment]
> > Are you using yarn ios command to start app??
> 
> Building from xcode

Can you please elaborate your way? I don't think thats the right way to do it. Use `yarn ios` command to run the project.
Refer readme file for develop guides.

**Comment by dev7050** [comment]
> > > Are you using yarn ios command to start app??
> > 
> > 
> > Building from xcode
> 
> Can you please elaborate your way? I don't think thats the right way to do it. Use `yarn ios` command to run the project.
> Refer readme file for develop guides.

I didn't find a readme doc to run project. So, what I did is -

- yarn install
- pod install
- Selected xcode debug scheme
- Build the project (Metro bundler launched)
- App is on simulator but stuck on splash.
- Scipts not loaded from metro bundler

**Comment by dev7050** [comment]
Tried your way to run project but same. Any link to readme doc which I may have missed will be appreciated.

**Comment by yash-rajpal** [comment]
[Refer here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md)

Run `react-native start` on one terminal instance in project's root directory. In other terminal instance run `yarn ios`.
