### ISSUE TITLE
Background messages are not able to receive in iOS when app is in background mode.

### ISSUE THREAD

**Issue by rajkumarbhaji** [RocketChat/Rocket.Chat.ReactNative#2831]
Hi 
I followed exactly the same steps as the below URL to set iOS APNS settings.
https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#configuring-ios

But still, the iOS app is not able to receive the message notifications when the app is in background mode.

**Comment by jacotec** [comment]
I guess you've missed something. APN-Key, APN-Cert and APN-Passphrase entered in the Admin section "Push Messages" of your RC server? Switch "Activate Gateway" switches to off? Restarted RC server after these changes?

I'm using a whitelabel app by myself and don't see any issues with push notifications.

The app itself is unfortunately not updated in the background when the push arrives. You get the push, but the app will update the messages when you open it.

**Comment by rajkumarbhaji** [comment]
@jacotec Thank you for your response. I follow the exact steps mentioned in the documentation, but I couldn't receive any message notifications on my iOS device. 

I also observed that the app is not showing an alert dialog to accept the Notifications when I launch the app for the first time.

**Comment by rajkumarbhaji** [comment]
@diegolmello @jacotec 
Just I observed that, If I send the message from General Channel, then only the notification / background messages are appearing, but if I send to direct user then the notification are not comming.

**Comment by diegolmello** [comment]
@rajkumarbhaji That's not related to the app itself.
It depends on the preferences you configured.

**Comment by rajkumarbhaji** [comment]
@diegolmello configuration where?? I dint configured any to particular channel settings though??

**Comment by jacotec** [comment]
@rajkumarbhaji Check the presets for mobile notifiactions in Settings --> Accounts

![grafik](https://user-images.githubusercontent.com/3321655/105863234-f6a91d00-5ff0-11eb-97f3-01cf0ad6d242.png)

However, every user can override these settings in his account settings:

![grafik](https://user-images.githubusercontent.com/3321655/105863389-222c0780-5ff1-11eb-9b3c-6a561dfb6143.png)

**Comment by rajkumarbhaji** [comment]
@jacotec Thank you , all the settings are normal, but still not getting the direct message notifications.

**Comment by Salmankhan033** [comment]
@rajkumarbhaji  have you fixed the issue?
I have the same issue, please look at the below image that I configure it correctly or not.
Thanks in advance 
<img width="1273" alt="Screenshot 2022-10-11 at 3 39 26 PM" src="https://user-images.githubusercontent.com/58082294/195070377-5bc7b59b-3006-48e1-90e4-316064f3aae1.png">
