### ISSUE TITLE
DM rooms show typing status from last group room

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#2832]
### Description:

I just clicked on a user avatar in a group message and then clicked "message" to go to their DM room... I then saw another user was typing from the DM room that was in the group room. I think there's a bug there!

### Environment Information:

- Rocket.Chat Server Version: 3.10.3
- Rocket.Chat App Version: 4.14.0.22464
- Device Name: Samsung Galaxy Note 10+ 5G
- OS Version: Android

### Steps to reproduce:

1. Go to a group room
2. Click on a user's avatar
3. Click message to go to their DM room
4. Have someone in the group room start typing
5. Typing status shows up for that user even though they aren't in the DM room.

### Expected behavior:

Don't show anyone is typing.

### Actual behavior:

Shows that someone is typing.

**Comment by pratyaksh123** [comment]
I'll check this out...

**Comment by sumukhah** [comment]
Hello @pratyaksh123, Are you working on this issue?
If not can I take it?

**Comment by pratyaksh123** [comment]
Yeah go ahead, but do confirm this issue is still happening, maybe the team fixed it in some release.

**Comment by diegolmello** [comment]
Fixed on #2878
