### ISSUE TITLE
Cannot build the single-server branch for version 4.14.0.1

### ISSUE THREAD

**Issue by huytx0909** [RocketChat/Rocket.Chat.ReactNative#2835]
### Environment Information:

- Rocket.Chat Server Version: 3.10.0
- Rocket.Chat App Version: 4.14.0.1
- Device Name: iphone 11 Simulator XCode
- OS Version: 

### Steps to reproduce:

1. Follow
https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps
### Expected behavior:

App loads into the login screen

### Actual behavior:

App loads with a blank white screen, and stays there

![image](https://user-images.githubusercontent.com/29868399/105826665-910a6000-5ff3-11eb-8759-1ec0dce3db36.png)

**Comment by ealbers** [comment]
How did you solve this problem? I am experiencing the same thing.
