### ISSUE TITLE
[Bug] iOS has no 'OK' button when logged out from other locations (devices)

### ISSUE THREAD

**Issue by pechqwer** [RocketChat/Rocket.Chat.ReactNative#2847]
### Description:

[Bug] iOS has no 'OK' button when logged out from other locations (devices)

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.14.0.22701
- Device Name: iPhone 12
- OS Version: iOS 14.4 

### Steps to reproduce:

1. User tried to "logged out from other locations" on mobile application (iOS) 
2. Pop Up 'Are you sure?' has shown but has only 'Cancel' button (according to the screenshot) while the pop up on android has shown both 'OK' & 'Cancel' button

### Expected behavior:

Pop up on iOS application appears both 'OK' & 'Cancel' button like android

### Actual behavior:

Nothing happens.
![S__58982418](https://user-images.githubusercontent.com/45811671/106231004-440cd080-6223-11eb-93de-9a77db57daf1.jpg)

### Additional context:

Working !!

**Comment by ARKEOLOGIST** [comment]
I'd be happy to tackle this, but I don't have a Mac to test the changes.
