### ISSUE TITLE
Cant build iOS

### ISSUE THREAD

**Issue by Conrado916645** [RocketChat/Rocket.Chat.ReactNative#2848]
help can't run iOS
The following build commands failed:
	PhaseScriptExecution [CP-User]\ [RNFB]\ Crashlytics\ Configuration /Users/Human/Library/Developer/Xcode/DerivedData/RocketChatRN-fzqgznnolygdwhdpgohdropilzjp/Build/Intermediates.noindex/RocketChatRN.build/Debug-iphonesimulator/ShareRocketChatRN.build/Script-C77883A80C5B024875754F94.sh
(1 failure)

**Comment by eliKeetch** [comment]
Is this still active?
