### ISSUE TITLE
Changing orientation inside a room doesn't update keyboard bounds

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#285]
![apr-26-2018 10-45-57](https://user-images.githubusercontent.com/804994/39309719-167d2188-493f-11e8-90a7-1afef664de40.gif)

**Comment by diegolmello** [comment]
Hi, @harshit98. Of course, you can!
If you have any questions, just reply here 👊

**Comment by harshit98** [comment]
@diegolmello While working on this issue, I've observed that if I refresh the app in my simulator (device being in horizontal position) then the message box appears in full-width equal to screen-size of the device and when I rotate the screen to vertical position, the message box covers the full-bottom width of the device but buttons like _microphone and '+' sign (to add files)_ get out of the screen (or hides away)

![simulator screen shot - iphone 6 - 2018-05-10 at 23 40 57](https://user-images.githubusercontent.com/22245418/39886478-3082cee2-54ad-11e8-8501-00c1faa7041c.png)
![simulator screen shot - iphone 6 - 2018-05-10 at 23 41 50](https://user-images.githubusercontent.com/22245418/39886483-33007d90-54ad-11e8-8cfc-3870e069f354.png)

Looks like the code which is already written is working fine. It can be problem with the Xcode simulator for iPhone 6 11.2 (maybe). Suggestions are welcomed :)

**Comment by diegolmello** [comment]
@harshit98 Yes, I already opened an issue on wix/react-native-keyboard-input about it.
I wanted your opinion before I tell you.
Can you investigate iOS code?

I already made a fork for Wix's library here: https://github.com/RocketChat/react-native-keyboard-input

**Comment by harshit98** [comment]
@diegolmello I can't investigate the iOS code because I'm not familiar with Objective-C. But yes, I can help the team with other issues under this repository. ✨

**Comment by diegolmello** [comment]
@harshit98 Thanks, man.

**Comment by diegolmello** [comment]
Fixed here: https://github.com/wix/react-native-keyboard-input/issues/49#issuecomment-389850990
