### ISSUE TITLE
how to run project

### ISSUE THREAD

**Issue by adrastest** [RocketChat/Rocket.Chat.ReactNative#2864]
the latest(4.14.0) versions don't have (how to run) in readme file .
we request you add it if possible.

**Comment by ARKEOLOGIST** [comment]
First install the dependencies using 'npm install' in project folder.
Then type in 'npm run android' or 'npm run ios' in the project folder depending on the platform you want to run the project on.
I'll send in a PR soon that will address these changes if the owners are fine with it.

**Comment by yash-rajpal** [comment]
@ARKEOLOGIST I think we use yarn for this project Instead of npm.

Steps would be install dependencies by running yarn command and building project using yarn android or yarn ios command.

**Comment by ARKEOLOGIST** [comment]
Yes, my mistake. We use yarn in this project.

**Comment by adrastest** [comment]
when I run yarn command in the root folder of project it show me  (command 'yarn' not found) .

**Comment by yash-rajpal** [comment]
@adrastest Yes, you have to install yarn first in order for it to work.

**Comment by diegolmello** [comment]
> Refer to React Native environment setup to make sure everything is up and running

**Comment by adrastest** [comment]
when i run rocket chat react-native 4.14.0
its going on when its reach to 99% Executing then its stack without any error.
first I start server with (react-native start)
then run yarn Android command.
