### ISSUE TITLE
Some deleted messages still appear on iOS

### ISSUE THREAD

**Issue by miamiautumn** [RocketChat/Rocket.Chat.ReactNative#2865]
### Description:

If a message is deleted on the MacOS app while the iOS app is open (but the channel with the deleted message is not open), then the message will not appear on MacOS but will still appear on iOS when the channel with the deleted message is open. 

### Environment Information:

- Rocket.Chat Server Version: 3.10.4
- Rocket.Chat App Version: 4.14.0
- Device Name: iPhone 
- OS Version: iOS 14.4

### Steps to reproduce:

1. Open the Rocket.Chat app on iOS, and do not enter into the channel that is being tested in.
2. Open the Rocket.Chat app on MacOS, and send a message in a test channel. 
3. Delete the message from the MacOS app. 
4. Open the test channel on the iOS app.

### Expected behavior:

The message should not be visible on MacOS or on iOS after it has been deleted.

### Actual behavior:

The message is not visible on the MacOS app but is still visible on the iOS app after it has been deleted.

View on MacOS app: 
![View on MacOS](https://user-images.githubusercontent.com/78466520/106712486-ec8aae00-65f0-11eb-81f9-cc9589487404.jpg)

View on iOS app: 
![View on iOS](https://user-images.githubusercontent.com/78466520/106712300-a7667c00-65f0-11eb-9a11-897e05052516.jpg)

### Additional context:

While I only have the ability to test this on iOS, other members in my server have reported the same issue on the Android app.

**Comment by kresnaputra** [comment]
Hey, I tried to reproduce the bug. But I don't get issue here. Can you explain more or you can attach some video.

**Comment by miamiautumn** [comment]
I just tried to reproduce it again myself, and it appears to no longer be an issue. I will close this then.
