### ISSUE TITLE
Improve feedback to user when loading conversation after clicking the push notification

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat.ReactNative#2868]
### Description:
When the user receives a push notification from some user, and clicks it, rocketchat app will open that conversation but it will only refresh the conversation with the new message after a few seconds. ( Sometimes over 10 seconds to refresh). While the message is not refreshed, it would be nice if the user had that refresh icon spinning on the screen, so he could be sure new messages will eventually appear. People is used to whatsapp when they click a received push and the message is already there, but in RocketChat, when they click the push and open the app and there is nothing there, they leave the app without waiting for the message to appear.

### Environment Information:

- Rocket.Chat Server Version: 3.8.4
- Rocket.Chat App Version: 4.14
- Device Name:  OnePlus
- OS Version: Android 8

### Steps to reproduce:

1. Receive a Push with several messages 
2.Click the push notification
3. App will load the conversation, but it has been a few minutes since you last entered the app, there will be a delay before the message appear ( due rocketchat app connecting and updating from the server)

### Expected behavior:

EIther the message should be "downloaded" in background as soon as the post is received or a refresh icon should be spinning in the conversation window while the app connects to the server.

### Additional context:

It would be a great improvement to the usability.

**Comment by diegolmello** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1432
