### ISSUE TITLE
The app crash when we start the video call on android,I try to record the log and got the error "java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so",but it works on ios, anyone face same issue?

### ISSUE THREAD

**Issue by zhuyuan2016** [RocketChat/Rocket.Chat.ReactNative#2874]
### Description:

We use 2.1.0 jitsi SDK on android,check all the android config include 'build.gradle' and 'app\build.gradle'
![QQ截图20210205104407](https://user-images.githubusercontent.com/14816152/106982502-31ecde00-679f-11eb-85ff-4e36f6ffa105.png)
![QQ截图20210205104421](https://user-images.githubusercontent.com/14816152/106982509-34e7ce80-679f-11eb-8b9f-e75a3bdd9d6e.png)
![微信图片_20210205104152](https://user-images.githubusercontent.com/14816152/106982305-c9056600-679e-11eb-87f2-3829f5358721.png)

### Environment Information:

- Rocket.Chat Server Version: unknow
- Rocket.Chat App Version: 4.7.0
- Device Name: google pixel 2
- OS Version: Android 6

### Steps to reproduce:

1.  In the roomview page
2.  Click 'join jitsi'
3.  Then crash, we show the log Detail

### Expected behavior:
jitsi meet can work well on android

**Comment by diegolmello** [comment]
We're on 4.14.0 already.
Update your app and try again.

**Comment by zhuyuan2016** [comment]
> We're on 4.14.0 already.
> Update your app and try again.

But I make some DIY on the 4.7.0 branch, so I can't update directely,do you know the crash reason in that version, please help me ,Thank you very much!!

**Comment by kudaikoko** [comment]
> > We're on 4.14.0 already.
> > Update your app and try again.
> 
> But I make some DIY on the 4.7.0 branch, so I can't update directely,do you know the crash reason in that version, please help me ,Thank you very much!!

hi did you found any solution?
