### ISSUE TITLE
[RangeError: Maximum call stack size exceeded.]

### ISSUE THREAD

**Issue by RaviGaruda** [RocketChat/Rocket.Chat.ReactNative#2876]
### Description:

I Build app successfully and app is getting installed, but when I enter the username and password and click on the login button. I get **"[FRI Feb 05 2021 14:33:10.170] ERROR [RangeError: Maximum call stack size exceeded.]"** I get this inside terminal. There is no message or prompt on the app side.

### Environment Information:

- Rocket.Chat Server Version: 3.10.5
- Rocket.Chat App Version:  4.14.0.1 (single-server)
- Device Name: Samsung gallaxy M20
- OS Version: Android 10

### Steps to reproduce:

1. Click on login button
2. Enter username and password
3. Click the login button

### Expected behavior:

User should Login.

### Actual behavior:

Nothing happens with correct username and password, if enter wrong credentials message is displayed. 

### Additional context:

#2501 
![Screenshot (40)](https://user-images.githubusercontent.com/73194430/107023314-7478df80-67cc-11eb-8c8f-8463661c68c1.png)

**Comment by Yacobus** [comment]
Same issue here

**Comment by ambegossi** [comment]
I had this error when I was trying to use the server url with `http://`

Using `https://` everything happened normally
