### ISSUE TITLE
iOS App Version 4.14.1 - Dialog for Sharing Files is blank

### ISSUE THREAD

**Issue by User6554** [RocketChat/Rocket.Chat.ReactNative#2877]
### Description:

Eventought this issue was solved for some, it still keeps happening to me:
When using the option for sharing files on iOS with the updated version (4.14.1) of the Rocket.Chat App, a blank dialog appears (refer to the video below). 

### Environment Information:

- Rocket.Chat Server Version: 3.9.7
- Rocket.Chat App Version: 4.14.1.22787
- Device Name: iPhone 12 256GB
- OS Version: iOS 14.4

### Steps to reproduce:

1. Open any App on iOS which lets you use the share option (I tested it with Photos and Safari)
2. Click on the iOS share icon 
3. Click on the Rocket.Chat App

### Expected behavior:

One would expect Rocket.Chat to open to share the content. 

### Actual behavior:

Unfortunately only a blank dialog appears (refer to video below). 
Actual Behaviour:

https://user-images.githubusercontent.com/77775128/107050570-accbee00-67cb-11eb-92e5-4a3462304c17.mp4

### Additional context:

I performed a restart of my iPhone after updating the App to Version 4.14.1. This did not solve the issue. 
Refer to the initial issue #2760 where the problems seemed to get solved for some users.
Thank you in advance!

**Comment by AmatorPhasma** [comment]
Same on:
- iPad: gen6, gen7, gen8
- iOS version 14.4

Note: 
It works in the beta versions from the testflight app: 4.13.1, 4.14.0, 4.14.1

**Comment by MBraunshausen** [comment]
+1

iPad Air 4. Gen with iOS 14.4
and iPhone X with iOS 14.4

**Comment by avmentzer** [comment]
Same here, waiting since one month for an answer from Support. 
![Uploading D9454332-6BBD-4C22-8F33-7943A6939165.jpeg…]()

**Comment by avmentzer** [comment]
![3110CCEF-6B51-40E6-91B9-89185208129E](https://user-images.githubusercontent.com/74241215/115965545-12598c00-a52a-11eb-8780-441b097f644c.png)

**Comment by serge-petrov** [comment]
I have the same issue.
Two identical servers Ubuntu 20.04:
Version
3.14.4
Apps Engine Version
1.25.0
Node Version
v12.22.1
Database Migration
222
MongoDB
3.6.14 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (ba6337c2b)
Branch: HEAD

First one works fine but the second one causes blank screen while sharing attachment from another app. I use the same iPhone SE2 and Rocket 4.16.2.23928 for both cases.
