### ISSUE TITLE
The application automatically closes after 30 minutes of inactivity in multitasking mode.

### ISSUE THREAD

**Issue by AndreySemenov1** [RocketChat/Rocket.Chat.ReactNative#2882]
### Description:
The application automatically closes after 30 minutes of inactivity in multitasking mode.

### Environment Information:

- Rocket.Chat Server Version: 3.10.5
- Rocket.Chat App Version: 4.13.1.3
- Device Name: iPhone 11
- OS Version: 14.3

### Steps to reproduce:

1. Launch the Rocket app
2. Open your browser
3. Use a browser
4. Lock your device
5. After 30-40 minutes of inactivity, unlock the device, return to the Rocket.Chat application

### Additional context:

Some info from AppCrash report:

https://pastebin.com/bTxEmqv7

**Comment by Bestoloch** [comment]
The same issue. When the app is in the background for a while, it crashes after returning.

**Comment by AndreySemenov1** [comment]
Hi All!

Any luck ?

**Comment by AndreySemenov1** [comment]
update to new version resolved problem.
