### ISSUE TITLE
Blank screen when trying to login w/ OAuth provider

### ISSUE THREAD

**Issue by newmanw** [RocketChat/Rocket.Chat.ReactNative#2883]
### Description:

When launching an OAuth authentication page, the view is blank.

![Screen Shot 2021-02-08 at 9 32 26 AM](https://user-images.githubusercontent.com/3382274/107249431-98b50600-69f0-11eb-8aea-ed8faaacccd4.png)

Fired up an emulator and seeing this in the console, not entirely sure its pointing out a problem, but seems related:

`2021-02-08 09:25:26.570 19777-19777/chat.rocket.reactnative E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (20829) crash detected (code -1).`

### Environment Information:

- Rocket.Chat Server Version: 3.0.5
- Rocket.Chat App Version: Android 4.14.0 from play store.  Also reproduced on develop branch running on an emulator.
- Device Name: Android (physical Google Pixel 4 and emulator)
- OS Version: Android 11

### Steps to reproduce:

1. Attach to a server using oauth 
2. click login with oauth button

### Expected behavior:

3rd party oauth web page should be visible.

### Actual behavior:

See screenshot in description.

**Comment by newmanw** [comment]
Digging more the blank screen looks to be coming from a failure in a regex test here:

https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/AuthenticationWebView.js#L125

Is this possibly an in compatibility problem with server version 3.0.5?

**Comment by cprice-kgi** [comment]
I had the same problem, but it was likely due to the fact that I was trying to run in an Android simulator on my M1 mac mini. Once I tested the same .apk on a simulator running on my intel-based macbook, it worked fine. In my case, OAUTH worked fine on ios, but I was having the same issue you described. The issue seems to be with WebView not being able to render on the M1 Android simulator.

**Comment by deprov447** [comment]
Exact same issue with me also, using Github OAuth (although I'm not using any emulator, but a real device).

**Device details:**

> Redmi Note 7s
> Android 11
> LineageOS: 18.1-20211019-NIGHTLY-lavender
> Kernel version: 4.4.283-lineageos-g99f28a9f6efe

I found a workaround though, If anyone else came facing same issue:
- Setup ADB
- Inspect Rocket.chat's OAuth tab using chromium's remote debugging tool
- Entering the details on mirrored preview.

Screenshots:
![Screenshot_20211205_155319](https://user-images.githubusercontent.com/57551996/144744026-05ed55ac-91f4-444b-9bf0-5cb81b80d7d6.png)
![Screenshot_20211205-155301_Rocket Chat](https://user-images.githubusercontent.com/57551996/144744034-5182c8e6-ebfb-4df3-9c68-517acf2656d8.png)

**Comment by nicolamori** [comment]
Any progress on this? I am still experiencing this problem on Android with Rocket.Chat 4.26.2.
