### ISSUE TITLE
Login with google redirects back to login screen on successful login

### ISSUE THREAD

**Issue by banditAman** [RocketChat/Rocket.Chat.ReactNative#2889]
### Description:

The Rocket Chat apps (Android and iOS) are 

### Environment Information:

- Rocket.Chat Server Version: 3.11.0
- Rocket.Chat App Version: iOS & Android [Latest Build from App Store]
- Device Name: iPhone 6s, iPhone 11
- OS Version: DockerImage

### Steps to reproduce:

1. Open the app
2. Enter the workspace URL
3. Since my org only allows login with google, only that option is presented to the user( refer to the screenshot below)
4. click that and follow the google login flow
5. after the login with google flow finishes the user is directed to the login with google page again (screenshot below)

### Expected behavior:

The user is logged in to the RC App

### Actual behavior:

User is redirected back to the login page with login with google option

![screenshot](https://i.imgur.com/LU7L4ES.jpeg)

### Additional context:

I deployed another test RC instance and had a normal username: password setup, the same app is letting me log in and the app works fine with that.

**Comment by diegolmello** [comment]
Are you able to login via Google on https://open.rocket.chat?

**Comment by banditAman** [comment]
I checked and it works fine with [open.rocket.chat](open.rocket.chat) ! What could be the issue here? Because login with google for rocket chat works fine in the browser.

**Comment by diegolmello** [comment]
It might be a misconfiguration on your admin panel.
You can ask for help on https://open.rocket.chat/channel/support or on https://github.com/RocketChat/Rocket.Chat
