### ISSUE TITLE
Minimum bandwidth required for text, voice and video for P2P 

### ISSUE THREAD

**Issue by adrastest** [RocketChat/Rocket.Chat.ReactNative#2890]
anyone tell how much internet speed or bandwidth is required for point to point connectio.?

**Comment by diegolmello** [comment]
For text is really low, but for video/voice you can rely on Jitsi forum questions like this https://community.jitsi.org/t/jitsi-users-recommended-bandwidth-perf-for-a-jitsi-meet-server/12900
