### ISSUE TITLE
App won't build with Android Studio

### ISSUE THREAD

**Issue by danfelbm** [RocketChat/Rocket.Chat.ReactNative#2904]
### Description:

I'm trying to build the app through Android Studio and I followed the guide in the Docs. However when trying to build a signed APK via Android Studio (using the official play debug variant), although the build is successful, the app won't run. Giving the error:

`Unable to load script. Make sure you’re either running a Metro server….`

### Environment Information:

- Rocket.Chat Server Version: 3.10.5
- Rocket.Chat App Version: 4.14.1
- Device Name: not in device
- OS Version: appetize android 8.1

### Steps to reproduce:

1. Follow the instructions at https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps
2. Yarn
3. Start Android Studio
4. Start metro server through npx react-native start
5. Build signed APK through Android Studio

### Additional context:

![2021-02-13_15h26_41](https://user-images.githubusercontent.com/11007879/107860998-e4144d80-6e10-11eb-8dbe-a0fa74b6f10d.png)

![2021-02-13_15h27_44](https://user-images.githubusercontent.com/11007879/107861003-e8d90180-6e10-11eb-8f52-788f3243a1be.png)

**Comment by pratyaksh123** [comment]
Did you try `adb reverse tcp:8081 tcp:8081`

**Comment by danfelbm** [comment]
Hi @pratyaksh123 thank you for your response. I just tested:
1. `adb reverse tcp:8081 tcp:8081`
2. npx react-native start
3. Android Studio - Build signed apk.
And unfortunately it didn't work. _Same_ error.

If I go to localhost:8081 I see that the metro server is running. So I wonder why Android Studio can't make use of it.
![2021-02-15_07h46_55](https://user-images.githubusercontent.com/11007879/107948545-02d62980-6f62-11eb-808d-3ad0c0307408.png)

**Comment by danfelbm** [comment]
For anyone experiencing the same issue, it seems the metro server had to be running inside Android Studio (its terminal) or from the android folder. And now it works.

**Comment by Salmankhan033** [comment]
same issue.
Have you solved the problem?
