### ISSUE TITLE
Push Notifications lead to incorrect discussion / group discussion

### ISSUE THREAD

**Issue by 2disbetter** [RocketChat/Rocket.Chat.ReactNative#2910]
### Description:

Since 14.4 push notifications for specific discussions or group discussion do not function correctly. When the notification is tapped on, it will go to the correct discussion but after loading, another discussion will open which is not correct. 

### Environment Information:

- Rocket.Chat Server Version: current snap 
- Rocket.Chat App Version: 4.14 / 4.14.1
- Device Name: Fairphone 3
- OS Version: Android 10 (/e/ OS)

### Steps to reproduce:

1. receive push notification and tap on notification
2. rocket chat opens and goes to the correct discussion relevant to the notification
3. after loading fully, the client then goes to a different discussion that is not relevant. It appears, at least that the same incorrect discussion is loaded each time. 

### Expected behavior:

The discussion containing the push notification message would get loaded and stay loaded until user actions make it otherwise. 

### Actual behavior:

See above

### Additional context:

As mentioned, the incorrect discussion / group chat that loads afterwards is always the same. If I had to guess, there is some kind of hanging notification in the app, that keeps triggering the incorrect room to open.

**Comment by C1ean** [comment]
Is it similar to  https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2870 ?

**Comment by 2disbetter** [comment]
It could be, but I have no notice that pattern of use.

**Comment by jsalatiel** [comment]
I also noticed that. If i receive a notification from a discussion, the app is not opening on the discussion, instead opens in the last chat i had.
