### ISSUE TITLE
[Bug] The Online Status has changed into offline when switch the application / lock the screen

### ISSUE THREAD

**Issue by pechqwer** [RocketChat/Rocket.Chat.ReactNative#2911]
### Description:

[Bug] The Online Status has changed into offline when switch the application / lock the screen

### Environment Information:

- Rocket.Chat Server Version: 3.7.1
- Rocket.Chat App Version: 4.14.0.22701
- Device Name: iPhone 12
- OS Version: iOS 14.4

### Steps to reproduce:

1. Users login to the RocketChat on mobile application (which is connected with the website and the status on the website will turn online when login and the status will turn offline when logout only)
2. Users check on the website to check their status right after they login on the RocketChat
3. Users found out that the status is in offline mode

### Expected behavior:

 When login / online on mobile application, the status must be online even when the users switch the application or lock the screen.
### Actual behavior:

The status will be offline automatically when switch the application / lock the screen (sometimes)

### Additional context:

Working !!

**Comment by diegolmello** [comment]
Fixed on 4.15
