### ISSUE TITLE
Launcher icon not changed - 4.14.1 Android Single-server

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.ReactNative#2916]
### Description:

Hi, I try to compile `single-server` version 4.14.1. The issue is Android launcher icon not changed to custom. I have replaced all below files (marked blue)
![image](https://user-images.githubusercontent.com/50440047/108343822-ae8aae00-71dc-11eb-883d-d6a98237b31b.png)
But after build and install icon still is
![image](https://user-images.githubusercontent.com/50440047/108343987-e0037980-71dc-11eb-9738-e497c263ca4e.png)

Could you help me what can be wrong?

### Environment Information:

- Rocket.Chat Server Version: 3.9.7
- Rocket.Chat App Version: 4.14.1 `single-server`
- Device Name: Samsung e20e
- OS Version: Android 9

### Steps to reproduce:

1. Build `single-server` Android app with custom icons

### Expected behavior:

App has custom icon after install

### Actual behavior:

App has default icon

**Comment by diegolmello** [comment]
Hey, @emikolajczak.
[Documentation says:](https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#general-setup-1)
> Generate a new image asset for ic_launcher and target experimental

We use [Adaptive Icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive), so you should create a new image asset from Android Studio.
