### ISSUE TITLE
Blocked users' messages are still viewable on mobile

### ISSUE THREAD

**Issue by sys-3** [RocketChat/Rocket.Chat.ReactNative#2920]
### Description:

When blocking someone using the web client, the messages are not hidden on the mobile app.

### Environment Information:

- Rocket.Chat Server Version: 3.11.0
- Rocket.Chat App Version: 4.14.1.22782
- Device Name: LG Stylo 5
- OS Version: Android 10

### Steps to reproduce:

1. Go to 'User Page'
2. Click on 'Block'
3. Open Mobile App
4. View their messages in a public channel

### Expected behavior:

For their messages to be hidden.

### Actual behavior:

Their messages are still viewable like a unblocked user.

### Additional context:

I am running the experimental version as for some reason it's less buggy than the regular version.

**Comment by aKn1ghtOut** [comment]
This does not appear to be the blocking policy that Rocket.Chat follows. The app seems to be consistent with the web client here. You might want to open an issue at RocketChat/Rocket.Chat instead
