### ISSUE TITLE
Notification not working when app is not running.

### ISSUE THREAD

**Issue by adrastest** [RocketChat/Rocket.Chat.ReactNative#2929]
I use Rocket Chat React-native android app (4.14.0) in my local rocket-chat server (3.10.5)
everything working fine but notification alert not working when app is not ruuning or app is in recent list
anyone help us?

**Comment by ankar84** [comment]
Did you enabled Push Gateway in Admin Panel of your RC Server?
Native (market) applications with work with push only via gateway.
