### ISSUE TITLE
[BUG] Jitsi shared screen not visible on Android

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.ReactNative#2937]
### Description:

When I join to Jitsi video call via Android app and someone share a screen from desktop app, is not visible.
On iOS app everything is fine, is possible to see shared screen.

### Environment Information:

- Rocket.Chat Server Version: 3.9.7
- Rocket.Chat App Version: 4.14.1
- Device Name: Samsung A20e
- OS Version: Android 9

### Steps to reproduce:

1. Join to Jitsi video call via Android app
2. Someone share screen from desktop app
3. Screen is not visible on Android 

### Expected behavior:

Shared screen is visible on Android device as on iOS

### Actual behavior:

Screen is not visible on Android

**Comment by ankar84** [comment]
Hi, @emikolajczak
What is your Jitsi server version?

**Comment by emikolajczak** [comment]
Hi @ankar84 
Prosody, Jicofo - stable-5142-4
Web - stable-4548-1
Videobrige 2

**Comment by ankar84** [comment]
![Screenshot_2021-02-25-14-49-09-354_chat.rocket.reactnative.jpg](https://user-images.githubusercontent.com/4023037/109120619-c3d18080-7778-11eb-980f-0ac22e559c38.jpg)

**Comment by emikolajczak** [comment]
Could you share your Jitsi versions?

**Comment by ankar84** [comment]
> Could you share your Jitsi versions?

```
$ dpkg -l | grep jitsi
ii  jitsi-meet-prosody                     1.0.4628-1                                      all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-tokens                      1.0.4628-1                                      all          Prosody token authentication plugin for Jitsi Meet
ii  jitsi-meet-web                         1.0.4628-1                                      all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                  1.0.4628-1                                      all          Configuration for web serving of Jitsi Meet

$ dpkg -l | grep jitsi
ii  jitsi-videobridge2                     2.1-416-g2f43d1b4-1                             all          WebRTC compatible Selective Forwarding Unit (SFU)
```
