### ISSUE TITLE
[Issue] Jitis call - lower voice quality

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.ReactNative#2938]
### Description:

When I join Jitsi call via Android client voice quality is lower than desktop app or iOS app. Volume is significantly lower.

### Environment Information:

- Rocket.Chat Server Version: 3.9.7
- Rocket.Chat App Version: 4.14.1
- Device Name: Samsung A20e
- OS Version: Android 9

### Steps to reproduce:

1. Join to Jitsi call via Android device
2. Voice quality is lower than desktop app or iOS app

### Expected behavior:

Voice quality is same as desktop or iOS

### Actual behavior:

Voice quality is lower than desktop app or iOS app

**Comment by ankar84** [comment]
Hi, @emikolajczak
What is your Jitsi server version?

**Comment by emikolajczak** [comment]
Hi @ankar84 
Prosody, Jicofo - stable-5142-4
Web - stable-4548-1
Videobrige 2

**Comment by diegolmello** [comment]
We just updated Jitsi on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4823
