### ISSUE TITLE
How to customize and run compile this for my site?

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat.ReactNative#295]
Hi,
I want to compile this app for my RC site for both Android and iOS, I want to customize server url, localization strings, some logo and splash, app name, push notification, ...

Can you guide me or refer me to some part of docs?

**Comment by diegolmello** [comment]
@mnlbox Localization are not available yet, but it's very simple to change the appearance of the app.
You will need some React Native experience though.

**Comment by mnlbox** [comment]
@diegolmello I see i18n PR merged and thanks about this.
Can you guide me about how we can embed my server url in app and change landing page from **add server** page to login (or signup)
I want to prevent user to add new server and embed my server url to my app.

**Comment by ggazzo** [comment]
hey @mnlbox we dont have this feature "done" but its a good opportunity to extend your application to allow customizations and whitelabels, what do you think help us with this? I can try guide you and at the end you could open a(or many) PR!!

look here `app/lib/realm.js`
you can add at the end of the file 
```javascript
database.databases.serversDB.write(() => {
	database.databases.serversDB.create('servers', { id: "yourserver.com", current: true }, true);
});
```

and create a global to hide "Add server" from menu... it`s a beginning.. good luck :P

**Comment by irepan** [comment]
Hi @ggazzo I have tried this app/lib/realm.js editing solution and it does not work for me at all, probably I'm missing something here, what I did was to add the lines you suggested to the very end of the file, and the response I get is "Can't find the variable database".

**Comment by diegolmello** [comment]
@mnlbox @irepan I created a branch `single-server` to cases like yours.
Check it out.

**Comment by mnlbox** [comment]
@diegolmello Thanks man. I saw that and it seems that it's awesome.
Is it hard to add this as an option? So we can switch between `single-server` and `multi-server` by simple `flag` option set like: `single-server: true`.

**Comment by diegolmello** [comment]
@mnlbox It can be made, but it's not in our plans to do it right now since we've lots of features to develop.
Are you willing to help us?

**Comment by mnlbox** [comment]
@diegolmello I want to help but I think we need more expert developers for doing this or If you have a little time please guide me to how to do this to contribute. :wink:
