### ISSUE TITLE
[BUG] Google OAuth and password login fail with white-label and official client

### ISSUE THREAD

**Issue by ArnavKaushik** [RocketChat/Rocket.Chat.ReactNative#2952]
### Description:

I followed the guide on the documentation ([located here](https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps)) and when I ran the app (on both iOS and Android) after assigning a custom server in `app.json`, I tried to login with Google OAuth. An OAuth screen pops up, and when I login it disappears and nothing happens. I enabled password login and I tried it again, with no success. 

I then tried to use the AppStore version (on iOS) and I still wasn't able to login. I looked into the logs and noticed that there were several `prop type` errors.

### Environment Information:

- Rocket.Chat Server Version: 3.11.1
- Rocket.Chat App Version: 4.14.1
- Device Name: iPhone
- OS Version: 14.4

### Steps to reproduce:

1. Download the official Rocket.Chat app on the AppStore or use the guide mentioned above to download and run the app.
2. Assign a custom server (preferably with OAuth capabilities, but password also doesn't work). 
3. Attempt to login

### Expected behavior:

The user should be redirected to the next page in the app.

### Actual behavior:

The OAuth screen dismisses or in the case of a password login, the app does nothing.

### Additional context:

I haven't added a BugSnag api key to the custom app.

**Comment by darthShadow** [comment]
Is there any temporary workaround or solution available?

**Comment by diegolmello** [comment]
Google dropped support for OAuth on embedded browsers https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html

The workaround I can think of is implementing it using Google's native signin https://github.com/react-native-google-signin/google-signin
We can't do it on our apps, because we need to support multiple Google configurations, but it should work perfectly for whitelabels (one server only).

**Comment by ArnavKaushik** [comment]
Thank you for the quick response! I'll definitely look into this.

Would it be possible to get a basic implementation example of this?

**Comment by diegolmello** [comment]
> I'm still not sure why the basic username/password auth isn't working,

@ArnavKaushik It can be a lot of reasons. Can you debug and check for logs?

**Comment by ArnavKaushik** [comment]
Yeah I figured it would be a vague issue. I checked the logs with debug mode on and it seems that the API request is going through, but I don't see any response in the logs. For example, when logging in on mobile with my username/password, I see this in the log: `server.js:204 API ➔ debug POST: /api/v1/login` and that's it. When I login through the web or desktop app, the logs show everything correctly. Please let me know if there are other options I should check, I understand that this is a pretty broad issue.

**Comment by diegolmello** [comment]
Can you debug the app? There's probably an error happening somewhere, but it doesn't tell the server about it.

**Comment by ArnavKaushik** [comment]
After running the app on an iOS simulator and monitoring the console, I found the following errors:

```
RangeError: Maximum call stack size exceeded
    at trackProperties (trackForMutations.js:16)
    at trackProperties (trackForMutations.js:32)
    ....
```

and when I expanded the error, I saw this:
```
reactConsoleErrorHandler @ ExceptionsManager.js:179
r @ backend.js:32
registerError @ LogBox.js:148
errorImpl @ LogBox.js:59
console.error @ LogBox.js:33
(anonymous) @ WebSocket.js:265
```

Could this be related to a WebSocket error?

Thank you for the help!

**Comment by diegolmello** [comment]
It doesn't look right.
Follow [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md#how-to-inspect-the-app) and try to login on https://open.rocket.chat
You'll see the calls to REST API and how the app behaves.
Then test it on your server and check what's going on after `/login` is called.

**Comment by ArnavKaushik** [comment]
Thanks for the guide! I followed it and found some more details.

When I logged into the the https://open.rocket.chat server, everything worked as expected. When I logged into my custom server, I found that the login request was returning the correct information (it returned my user data). However, I noticed that there was an error that occurred after the app received my information successfully.

The order in the logs looks like this:
1. `LOGIN_REQUEST` the user and password are correct
2. `POST /api/v1/login` the user data returned is correct
3. `METEOR_DISCONNECT` not sure if this has any relevance, but it's between the two errors (also shows up numerous other times)
3. `LOGIN_FAILURE` received bad response code from server 500
4. `LOGIN_REQUEST in 367ms` shows the saga of the login request
5. `['connect error', {...} ]` also received bad response code from server 500

I'm not sure where the failure came from, because the login api is returning the data correctly.

**Comment by diegolmello** [comment]
`connect error` is usually something related to socket issues.
Is socket configured on your server?
On your browser, if you open your server url with developer console opened, do you see something?

**Comment by ArnavKaushik** [comment]
It was a socket issue! Turns out the Apache configuration in the documentation ([located here](https://docs.rocket.chat/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-an-apache-ssl-reverse-proxy)) didn't include this line:

`RewriteCond %{HTTP:CONNECTION} Upgrade [NC]`

before the other `RewriteCond` for the websocket. I've attached my current rewrite rules for future reference.

Definitely a sneaky issue, but the mobile app is now working. It also looks like the Google issue resolved itself (the blog post you sent earlier said it would stop working on Jan 4, 2021, but it seems to still work).

Thank you for all of your help!


-- **Rewrite Conditions** --
```
    RewriteEngine On
    RewriteCond %{HTTP:CONNECTION} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /(.*)           http://localhost:3000/$1 [P,L]
```

**Comment by diegolmello** [comment]
Awesome, @ArnavKaushik!
Thanks for debugging and finding the issue.
Can you open a PR improving our documentation? https://github.com/RocketChat/docs/blob/1f7f71edbf65f68e80ff47c0451bb3d710ba1306/installation/manual-installation/configuring-ssl-reverse-proxy.md#running-behind-an-apache-ssl-reverse-proxy

**Comment by ArnavKaushik** [comment]
Sure thing! I'll get it done ASAP.
