### ISSUE TITLE
Notification delayed from FCM (ReactNative - Android)

### ISSUE THREAD

**Issue by mobinpatel1** [RocketChat/Rocket.Chat.ReactNative#2955]
There is delay in notification from rocket chat, sometime the delay exceeds 20 min. 

 Chat server used **3.11.1** then also having delay in notification.

Please suggest solution.

Thank you

**Comment by hungnb94** [comment]
Android phone just receive notification and show it. So this is not mobile's problem.
You should check problem on server & FCM.
I try to improve notification  a couple times but it still not working perfect.

**Comment by diegolmello** [comment]
@mobinpatel1 A couple questions:
Are you using our gateway?
What device is having this issue? https://dontkillmyapp.com/
How can we reproduce it?

**Comment by songoten28** [comment]
- same problem
- I try to set up firebase messaging for another app with "Test" name.
Push notification from FCM dashboard to Rocketchat first, and then push for "Test" name after. 

The "Test" name will get FCM after 2~3 seconds but Rocket chat got this one more than 1~2 mins.
