### ISSUE TITLE
how we close the app without logout ? 

### ISSUE THREAD

**Issue by sergiomb2** [RocketChat/Rocket.Chat.ReactNative#2957]
After open rocket chat until reboot the device, rockterchat is always on , without option to close without logout, i.e. don't have to login again write the password , every time , I want close de app . 

### Environment Information:

- Rocket.Chat Server Version: 3.0.4
- Rocket.Chat App Version: 4.14.1.22788
- Device Name: ZTE Blade A6
- OS Version: Android 7.1.1

### Steps to reproduce:

1. 
2. 
3.

**Comment by ankar84** [comment]
I don't have that issue.
Check **Forget User Session on Window Close** setting in **Admin UI - Accounts** 
![image](https://user-images.githubusercontent.com/4023037/109927717-ae5ada00-7cd5-11eb-9b6d-c9dbda49e5c4.png)
Or something else related to user session length

**Comment by sergiomb2** [comment]
I think I don't have this option on my android 

Thank you

**Comment by diegolmello** [comment]
@sergiomb2 It's on Admin panel > Accounts.
