### ISSUE TITLE
iOS issue with RSA

### ISSUE THREAD

**Issue by Spyspyspy** [RocketChat/Rocket.Chat.ReactNative#2959]
Hello, i can not compile app, because of stack in RSAUtils.swift

I have this error and I don't know what to do next

Value of type 'OpaquePointer' has no member 'pointee'

**Comment by Earvonio** [comment]
Hi, I have the same error

**Comment by Earvonio** [comment]
@diegolmello Do you have some insights to resolve this problem? Actually, I can't run the project with XCode due this problem...

**Comment by djorkaeffalexandre** [comment]
Which version of Xcode are you using?

**Comment by djorkaeffalexandre** [comment]
Do you have made any changes in the source code?

**Comment by djorkaeffalexandre** [comment]
Have you tried to close-reopen xcode?
It's hard to track if one of your changes are causing this behavior.
I'm using the same Xcode version of you and already clone and build the project 3 or more times this week.

**Comment by Earvonio** [comment]
Yes, I closed and reopened XCode, I cleaned the build folder too. My problem is related to RCTRsaUtils.swift file and I didn't touch something in the pod file or in the project section. The error appear after a yarn -> pod install commands. I think that is related to react-native-simple crypto library.

**This is the error that appears:**

<img width="901" alt="Screenshot 2021-03-10 at 19 35 03" src="https://user-images.githubusercontent.com/23032552/110680226-9ce36780-81d8-11eb-89ae-e1b93057167c.png">

**Comment by djorkaeffalexandre** [comment]
<img width="682" alt="Screen Shot 2021-03-10 at 3 46 29 PM" src="https://user-images.githubusercontent.com/29778115/110680786-d061ca00-81b7-11eb-8563-de131e505685.png">
<img width="642" alt="Screen Shot 2021-03-10 at 3 45 59 PM" src="https://user-images.githubusercontent.com/29778115/110680794-d35cba80-81b7-11eb-9742-a027a09caba3.png">
<img width="1512" alt="Screen Shot 2021-03-10 at 3 45 54 PM" src="https://user-images.githubusercontent.com/29778115/110680797-d3f55100-81b7-11eb-9bcf-fb2872f1dd54.png">

As you can see, I'm using the same Xcode version of you, it's not a problem with the react-native-simple-crypto library itself.

**Comment by jim0020** [comment]
Having the same problem here.  Did anyone find the cause?

**Comment by jim0020** [comment]
@Earvonio Make sure your Pods are all being included.  I had lots of warnings about the iOS Deployment Target being too low and not supported.  To get to those, click on the Pods project file, then you'll see the list of all the podfile targets, for each one in Build Settings check the setting for iOS Deployment Target.  I set each of mine which was < 9.0 to 9.0.  There's a lot of them so I modified my Podfile to do it.  At the end of the Podfile, there is a post_install block.  I added a check in there to update the iOS Deployment Target to 9.0 if it was below that.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'

      # update the iOS Deployment Target setting if less than 9.0
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_i < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "9.0"
      end

    end
  end
  flipper_post_install(installer)
end
```

**Comment by Earvonio** [comment]
@jim0020 thank you for your explanation! It was very useful!

**Comment by cakesoft-rajesh** [comment]
I'm still having the same issue. 
Xcode: 12.4
Pod: 1.10.1

**Comment by rajesh-puranik** [comment]
I'm still having the same issue.
Xcode: 12.4
Pod: 1.10.1

**Comment by rajesh-puranik** [comment]
I found solution by changing this line it works => use_flipper!({ 'Flipper-Folly' => '2.2.0' }) because it need OpenSSL-Universal (1.0.2.19)
