### ISSUE TITLE
OmniChannel Queue does not appear in the Mobile APP

### ISSUE THREAD

**Issue by brunohl91** [RocketChat/Rocket.Chat.ReactNative#2962]
### Description:
I was conducting some tests with the APP and the OmniChannel service queue does not appear. When the service is transferred directly to my user, I can answer it, but when it comes in a queue, I can't get it through the APP, either using normal or experimental.

### Environment Information:

- Rocket.Chat Server Version: 3.12.0
- Rocket.Chat App Version: 4.14.1.22788
- Device Name: Android
- OS Version: Android 10

### Steps to reproduce:
1. Start a livechat call for the department the attendant is logged in to
2. Watch the queue on the web
![image](https://user-images.githubusercontent.com/4510277/109979164-5aec8a00-7cdd-11eb-8a1b-e5dd75d127c5.png)
3. See that there is no queue on Mobile
![image](https://user-images.githubusercontent.com/4510277/109979415-a3a44300-7cdd-11eb-8dd7-dd1998527ca8.png)

### Expected behavior:
Queue is expected to appear on mobile for customer service

### Actual behavior:
No queue is generated on the mobile
![image](https://user-images.githubusercontent.com/4510277/109979415-a3a44300-7cdd-11eb-8dd7-dd1998527ca8.png)

### Additional context:
If you pull the service through the web or the transfer goes directly to the user and not to the department, the service works.

**Comment by giterium** [comment]
The same problems. I don't know exactly from which version :(

**Comment by diegolmello** [comment]
It's an enterprise feature and it requires a license.
We're updating our pricing to mention it.
Thank you.
