### ISSUE TITLE
Android: No message recording button

### ISSUE THREAD

**Issue by arielsagaut** [RocketChat/Rocket.Chat.ReactNative#2967]
### Description:

Android: No message record button, neither on the message screen nor on the "+"

### Environment Information:

- Rocket.Chat Server Version: 3.9.7
- Rocket.Chat App Version: 4.14.1 and Experimental 4.15.0
- OS Version: Android 10 & 8.1

### Expected behavior:

An audio Button to record messages
![image](https://user-images.githubusercontent.com/80109234/110129531-d1a18a00-7da6-11eb-8a0c-bf793d800239.png)

### Actual behavior:
![WhatsApp Image 2021-03-05 at 11 22 56 (3)](https://user-images.githubusercontent.com/80109234/110128574-b7b37780-7da5-11eb-876f-12fa0d78a9ea.jpeg)
![WhatsApp Image 2021-03-05 at 11 22 56 (2)](https://user-images.githubusercontent.com/80109234/110128646-cdc13800-7da5-11eb-8815-ef79ac381290.jpeg)

### Additional context:

On the desktop App in Windows and Web app, the recording button is showing up .

**Comment by shrinish123** [comment]
@arielsagaut do you mean that the recording button doesn't appear when in dark mode?

**Comment by diegolmello** [comment]
There should be a `microphone` button at the right side of `+`.

**Comment by arielsagaut** [comment]
@shrinish123, No, there is no microphone in light mode either.

**Comment by arielsagaut** [comment]
@diegolmello, no, there is no microphone to the right of the + and no blue markings
![chrome_2021-03-12_09-28-53](https://user-images.githubusercontent.com/80109234/110940829-47ad7000-8316-11eb-9f9c-15d242fb3c40.png)

**Comment by diegolmello** [comment]
@arielsagaut There's a setting to show/hide that https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/MessageBox/index.js#L897
It's `Message_AudioRecorderEnabled`.
Can you check it on Admin Panel?

Also, you can try https://open.rocket.chat to check if the button is there and make sure it's a setting config on your server.
