### ISSUE TITLE
Make Bugsnag optional for privacy requirements

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2971]
### Description:

Got the following message from Apple:

> When you submitted your app, you answered questions about your app's privacy practices in App Store Connect. There are possible issues with the information you gave. You indicated that your app does not collect or track device or user data. However, your app integrates code from or communicates with third-parties that appear to collect and track this data, including, but not limited to, Bugsnag.
> 
> You need to provide accurate information about your app’s privacy practices, including the practices of all the third-party partners your app interfaces with, like ad networks, analytics tools, and SDKs. Doing so will help you avoid rejections on future submissions. If you don't know what data your third-party partners collect or if they track your users, please contact them or refer to the documentation they've made available. 

Promising to every user that RC is a fully GDPR compliant and highly privacy respecting solution, ticking several points in the privacy disclaimer as recommended by Bugsnag is not the best solution, especially as Bugsnag does not give me any useful information.

Therefore Bugsnag should be fully optional to use and for privacy reasons you should be able to exclude it from the builds of whitelabeled app versions for IOS and Android. It's more useful to app developers.

### Environment Information:

- Rocket.Chat Server Version: 3.12.1
- Rocket.Chat App Version: 4.14.0
- Device Name: iPhones, iPads
- OS Version: IOS 14.4.1

**Comment by diegolmello** [comment]
I see your point.
Bugsnag is important not only for our apps, but for yours.
When you whitelabel our app, you may change something (add new features) or you might have done something wrong in the process.
If a crash/bug happens and you have no error monitoring tool, you won't be aware of it.
A crash report from Bugsnag would help you figure our or even help us solving your own issue.

In addition, there's no way to disable it without removing it completely, so it's not easy to maintain.

If this is something you still need, it's quite easy to remove from your project.
Just undo the steps from docs: https://docs.bugsnag.com/platforms/react-native/react-native/legacy/
