### ISSUE TITLE
listening to and searching in audiofiles with mobile clients

### ISSUE THREAD

**Issue by MonsieurKoZo** [RocketChat/Rocket.Chat.ReactNative#2985]
### Description:

Impossible to listen to entire audio files (maybe a limit on file size or audio length), to search in a file. Counter is stuck at 00:00.

### Environment Information:

- Rocket.Chat Server Version: 3.8.4
- Rocket.Chat App Version: 4.14.1.22787
- Device Name: iPhone
- OS Version: 14.4.1

### Steps to reproduce:

1. Upload a audio file (WAV, MP3, ....)
2. Click on play
3. It's a bug, right ? ;)

### Expected behavior:

Audio files play entirely, we can search in audio files (move forward, etc...), counter should move too.

### Actual behavior:

Files don't play until the end, impossible to move the cursor to search the file, counter is stuck to 00:00

### Additional context:

I have this issue on my iPhone, but friends have the same issue under Android phones.
For the context, we are a music group and use Rocket.Chat a lot more with the lockdown, so we exchange files to move on with the recordings of our songs...
RC is installed on a RPI 4 4Go under 64 bits OS (diet pi) and it works like a charm, except for that audio issue which very annoying for us.

Thanks
Greg

**Comment by jacotec** [comment]
Could be related to #2586 

What storage do you use for attachments? File system gave me a 0 length for audio messages with all kinds of trouble, changing to GridFS at least brought stupid lengths with less trouble.

I hope this will be fixed one day.

**Comment by MonsieurKoZo** [comment]
Hi jacotec,
I use indeed File System, but I do not think I can change it as it is running on a Raspberry PI, so GridFS is not advised.

But it works with the browser, so I would suggest issue comes from the mobile apps.

**Comment by MonsieurKoZo** [comment]
Hi guys,
Just to inform you. I upgraded to the last available version on RPI (3.12) and it still does not work.
Though, I tested on my mobile and connected to the Open RC server and it works (version is 3.13). So I think @jacotec may be right about the storage issue...

It doesn't look good to me as under a RPI I cannot use GridFS, and there is no way I use Google or Amazon services.

**Comment by diegolmello** [comment]
Looks like an issue on backend.
