### ISSUE TITLE
Badge number getting cleared on app background

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#3009]
### Description:

The badge number at the app icon is often not properly updated. This issue was introduced in 4.15.0

### Environment Information:

- Rocket.Chat Server Version: 3.12,1
- Rocket.Chat App Version: 4.15.0
- Device Name: iPad, iPhone
- OS Version: IOS 14.4.1

### Steps to reproduce:

1. Use your RC app
2. Have all your messages read
3. Sometimes the badge is still showing a number of unread messages which you can't get rid of

### Expected behavior:

The badge should always show the real number of unread messages

### Actual behavior:

Wrong badge number indicating unread messages which aren't there

### Additional context:

- Clearly introduced in 4.15.0
- Sometimes force-quit and restart the app solves the wrong badge display, but not always

**Comment by diegolmello** [comment]
That's not a proper reproducible example.
"Clearly introduced" implies you're certain about how to reproduce and that it doesn't happen on previous versions.
If that's the case, just update your description.
Thanks.

**Comment by jacotec** [comment]
Clearly, because it never happened at any user before 4.15.
Since 4.15, I have 5 users with 9 iDevices in my direct "access" where it happens, plus a number of complaints from others.

I am not sure how it can be reproduced ... it happens quite often when you exit the app with all messages read that the badge still shows a number of unread messages. Just re-opening the app and close it again, it still does not change to the state that no unread messages are there.

**Comment by diegolmello** [comment]
Understood.
The badge number on app icon is sent on the push notification from the server.
We didn't change anything related to that on the app to clear or update it.
I'm closing until someone can add more info.

**Comment by jacotec** [comment]
@diegolmello OK, I did some more tests and can reproduce it now - and I confirm what you've written above.

The badge **is** updated with push messages, correct. But cleaning it "away" when you close the app with all messages read seems to be what broke.

Test procedure:

- Having my iPhone here with all read messages and no badge icon. Logged in to my account, lets say account "A". App is in background.
- Logging into a different accound on the PC, Account B
- Sending a message from account B to account A. Push and notification at iPhone, badge is updated to "1"
- Sending a second message from B to A. Push and notification at iPhone, badge is updated to "2"
- Sending a third message from B to A. Push and notification at iPhone, badge is updated to "3"
- Opening the app at the iPhone. Reading my messages. Returning from the chat to the overview, no unread threads shown in the app. All is read.
- Returning to springboard at the iPhone (so app is put into background)
- At this point the app before 4.15 did update the badge so the badge was reset to 0 (and was not visible). In 4.15, the badge remains showing "3" at this point!
- Sending another message from B to A - Push and notification at iPhone, badge is updated from "3" to "1".

So the update to the correct number at the badge is working when a push message was received. The issue is that the badge seems not to be updated when the app is swiped back into backfround after the messages have been read (at this point there is no updating push at the server).

**Comment by jacotec** [comment]
See below a video of the test above. The app is the second from the left in the bottom row (Icon: JC)

The bug might be related to the single-server version as I can't reproduce it with the official RocketChat app on a test server!

(As the screen video is too big for GitHub please find it here: https://jaycloud.de/s/NTHwnZRcJ9zZ784 )

**Comment by jacotec** [comment]
@diegolmello Can we agree to reopen this issue as I can fully reproduce it and have posted an evidence that the issue is existing?

I'm getting complaints from nearly all my IOS users regarding this, because they miss messages (if the badge always stays at "1" after a message was read, it stays also "1" when a new message was received) and I'm thinking about reverting my app to 4.14.1 as long as no fix is available.

**Comment by diegolmello** [comment]
@jacotec Makes sense. Can you contribute with a fix? Thank you.

**Comment by jacotec** [comment]
@diegolmello Unfortunately not as I have no clue of react native programming. I would immediately if I could!

**Comment by jacotec** [comment]
@diegolmello Do you have any idea here? It's still happening on 4.16 and users are not getting aware of new messages due to the wrong badge number display after closing the app into background.

**Comment by jacotec** [comment]
I finally identified that this regression seems to be dependent on the node version. Updated my dev environment to node version 15.14.0, npm 7.9.0 and yarn 1.22.10, recompiled the app and the issue is gone.

Sorry for the noise!
