### ISSUE TITLE
Mentioning a user, joins the mentioned user to the group

### ISSUE THREAD

**Issue by sumukhah** [RocketChat/Rocket.Chat.ReactNative#3019]
### Description:
Take for example a user 'A' who is not already a member of a group "Group A". Mentioning user "A" makes the user to join the group.

### Environment Information:

- Rocket.Chat Server Version:3.13
- Rocket.Chat App Version:4.15
- Device Name: IOS & ANDROID
- OS Version: 13.7

### Steps to reproduce:

1.  Go to a group/channel.
2. Mention a user who is not already in the group.
3. Mentioned user will be added (BY YOU)

### Expected behavior:
The user should not be added like that!

### Actual behavior:
Mentioned user will be added to the group.

https://user-images.githubusercontent.com/23723464/112478766-55dda080-8d9a-11eb-8d13-a7a2d8a401ab.mov

### Additional context:

**In webapp, this wont happen.**

**Comment by sumukhah** [comment]
I'll give it a try fixing this bug.

**Comment by diegolmello** [comment]
That's not an issue. It's a setting.

**Comment by sumukhah** [comment]
@diegolmello, Where would I get that setting?

**Comment by diegolmello** [comment]
I don't recall, but you can test if it's an issue in the app by sending a similar message from the web client.
You'll see that the user is going to be added to the channel.
