### ISSUE TITLE
iOS 4.16.0 broke channel menu (actions)

### ISSUE THREAD

**Issue by AmatorPhasma** [RocketChat/Rocket.Chat.ReactNative#3054]
### Environment Information:

- Rocket.Chat Server Version: 3.13.1
- Rocket.Chat App Version: 4.16.0
- Device Name: iPad Gen 8
- OS Version: 14.4.2

### Steps to reproduce:

1. Click in any channel on the name at th title bar

### Expected behavior:
At least: users can leve the channel there...

### Actual behavior:
broken menu:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/49910825/114464031-84a2a600-9be5-11eb-8ce8-d890d852bc96.png">

**Comment by jacotec** [comment]
I can confirm this! Also for the official RC app.
