### ISSUE TITLE
SSO - SAML Login does not work 

### ISSUE THREAD

**Issue by b90g** [RocketChat/Rocket.Chat.ReactNative#3059]
### Description:

Loging in via SAML doesnt work, always thrown back to Login button.
### Environment Information:

- Rocket.Chat Server Version: 3.12.1
- Rocket.Chat App Version: 4.16
- Device Name: Apple Iphone SE (1)
- OS Version: 14.4.2

### Steps to reproduce:

1. Entering Server Domain 
2. Clicking Login-Link on Server Page 
3. Loging in via SAML 

### Expected behavior:

The App saves the session and I am connted to the Server
### Actual behavior:

I get back to the Login button which should send me to SAML, a loop.

**Comment by northway** [comment]
I have the same issue on Android with Rocket.Chat `3.12.3`.

**Comment by emikolajczak** [comment]
Hi, same issue with Custom Oauth (Keycloak). But not for all users. In server logs no entries about problems with login.

**Comment by AvTopo** [comment]
Addition to issue owner (on same server)
Same issue with:
    Device Name: Apple iPhone Pro 11 Max
    OS Version: 14.4.2

**Comment by skudi** [comment]
same issue, server 3.12.0, android app 4.15.0 is working, 4.16.0 is looping, however sometimes, after few tries it starts.
We are using jasig CAS and CAS3.0.

**Comment by b90g** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2978/files - sus.

**Comment by diegolmello** [comment]
Can someone send me a test user to https://open.rocket.chat/direct/diego.mello?
It's working on my SAML servers.
Thanks.

**Comment by emikolajczak** [comment]
In my case login working for new created user and some existing. But some users can't log in. After authorization in oAuth (keycloak), back to oAuth button, and after click again, back again to button.

**Comment by diegolmello** [comment]
I'm still trying to reproduce it, but it's working.
If you have a reproducible user, send me.
I can release a patch right away.

**Comment by diegolmello** [comment]
Got a reproducible example.
I'm on it and I'll keep you posted.
Thanks!
