### ISSUE TITLE
Fatal bug - Android v. 11 (Samsung Galaxy S20+) - after upgrade on weekend (10-11. April 2021)

### ISSUE THREAD

**Issue by Skywalker1-CZ** [RocketChat/Rocket.Chat.ReactNative#3069]
Dear Rocket.chat team,
we've been upgrading our Rocket.Chat client this past weekend (10th - 11th April) and unfortunately uncountered critical issue in the mobile client. I'm using Samsung Galaxy S20+ and the Rocket.chat client 4.16.0.

I've been unable to successfully start the client as it seems to freeze on the Rocket.Chat logo. The client only start if I clear cache and data first but this "fix" helps only for a single use, once I close the client and try to start it again, the issue reappears.

I've also discussed this with my colleagues and they encountered exactly the same issue on various versions or even different OS (ie. Android 11 or even iOS with the latest update), so this is not an isolated issue bound to a single device. Seeing the latest feedback on Google Play, I'd say that this is not even an issue with our company settings as many other users seem to be experiencing this issue.

Thank you in advance for investigating this.

Kind regards

Filip Langer
Linux support L2
NETHOST s.r.o.

**Comment by lumitor2** [comment]
Hello, 
we have same problem with Rocket.chat mobile apps from this weeks start. Many colleagues with Android and IOS are unable to log-in with same freeze and same problem after cache clearing.

Thanks for help, Lubomir

**Comment by vargatamas86** [comment]
We have also experienced the issue. Setting the language to English in the profiles of the affected users seems to be a workaround.

**Comment by tomtomas99911** [comment]
This workaround unfortunately is not working for us.

**Comment by vargatamas86** [comment]
Steps to reproduce our workaround: 
1) Setting language to en or default in user profile (My Account) on the web UI.
2) Reinstall mobile application.
3) Login in mobile application.

We use LDAP authentication and our affected users had two factor authentication turned off.

**Comment by diegolmello** [comment]
How can we reproduce this issue?
It looks similar to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3055, but we tried reproducing it by setting my language to German and it worked.
Let us know and we can work on a patch right away.

**Comment by vargatamas86** [comment]
Our affected users had the Hungarian language set up before the workaround.

**Comment by diegolmello** [comment]
The bug was introduced _probably_ on this PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3014
Sadly, I'm not being able to reproduce the issue, so I don't feel comfortable to rollback blindfolded.

**Comment by diegolmello** [comment]
Ok, I might have got it.
The RC account must be configured to use an unsupported app language (like Hungarian) and fallback won't work.
I was trying to fallback to default from OS.
I'm working on a fix and I'm going to release a patch right away.
I'll keep you posted.
Thank you all.

**Comment by diegolmello** [comment]
Building 4.16.2

**Comment by diegolmello** [comment]
It's live on Google Play. Requesting review on App Store in a bit.

**Comment by diegolmello** [comment]
Released! https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/4.16.1

**Comment by lumitor2** [comment]
We have working mobile apps now! Thank you.
