### ISSUE TITLE
Missing NL translation in the onboarding & join workspace screen

### ISSUE THREAD

**Issue by MrDiba** [RocketChat/Rocket.Chat.ReactNative#3075]
### Description:

There are NL translations missing for the onboarding & join workspace screens.

### Environment Information:

- Rocket.Chat Server Version: N/A
- Rocket.Chat App Version: 4.16.0.23725
- Device Name: iPhone 11
- OS Version: 14.4.2

### Steps to reproduce:
1. Download the app on a iPhone configured with the Netherlands language.
2. Open the app.

### Expected behavior:

Nice looking buttons

### Actual behavior:

Not so nice looking buttons.
![IMG_1266](https://user-images.githubusercontent.com/37332424/115008942-0592c380-9eac-11eb-95f8-0afe282db37b.PNG)
![image0](https://user-images.githubusercontent.com/37332424/115008960-09bee100-9eac-11eb-9abb-9bc5e396256a.png)

### Additional context:
Maybe related with #3066 ?

**Comment by hrahul2605** [comment]
Hi @MrDiba the locale doesnt seem to have these translations as seen from this file
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/i18n/locales/nl.json

Can I take up this issue?

**Comment by MrDiba** [comment]
Hi @hrahul2605, I have no problem if you take this issue. 

If you need someone to translate, or to verify the translations, I can do that.

**Comment by hrahul2605** [comment]
Cool thanks, I'll open a PR please do verify the same.

**Comment by hrahul2605** [comment]
@MrDiba Please verify the translations in the linked PR #3076 :)

**Comment by MrDiba** [comment]
@hrahul2605 I have checked and added some comments, looking very good! Thank you for you work.
