### ISSUE TITLE
File sharing from Android Gallery/Photos doesn't share

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat.ReactNative#3077]
### Description:

Sharing a photo from the Gallery/Photos app on Android 10, in some cases, sends nothing.

### Environment Information:

- Rocket.Chat Server Version: 3.6.0
- Rocket.Chat App Version: 4.9.0
- Device Name:  Pixel 3a
- OS Version: Android 10/11 

### Steps to reproduce:

1. Go in Gallery/Photos
2. Double-click an image to bring up the full screen preview
3. Click the "share" icon at the bottom of the preview and pick RC
4. Choose a channel or person to share with
5. Click send

<img width="363" alt="test" src="https://user-images.githubusercontent.com/56982873/115057722-69b88600-9eb2-11eb-830f-b733257c633f.png">

### Expected behavior:

Photo will be shared with channel/person in RC.

### Actual behavior:

Nothing is sent. If you modify the steps by typing in a caption or description during the share, that caption will be shared, but the photo will not be sent along with it.

### Additional context:

This exact scenario works fine on Android 11.

Sharing the same photo (or any other) by using "+" within RC works OK on both Android 10/11. Sharing the same photo (or any other) using the "Files" app on Android 10/11 works fine as well. It seems to be only when sharing using the steps above, and I'm not really sure what makes that scenario unique, but it seems to be the case.

I was able to "fix" this by ensuring build.gradle uses targetSdkVersion = 28 (previously we were building with targetSdkVersion = 29). In this case, things work fine on Android 10 and 11 across the board. Unfortunately, the Google Play Store complains about uploading anything built with targetSdkVersion < 29.

Any thoughts on how to remediate this issue would be greatly appreciated. Thanks.

**Comment by diegolmello** [comment]
Update your app
