### ISSUE TITLE
Adding (and excluding) a chat to the favorites section on the chats list does not work

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3080]
### Description:

Adding (and excluding) a chat to the favorites section on the chats list does not work
In the version 4.7.0 of the application and the version 3.5.1 of the server, this functionality works correctly

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1.23838
- Device Name: Iphone 11 pro max
- OS Version: ios 14.4.2

### Steps to reproduce:

1. Go to sorting panel
2. Click on "Group favorites"
3. Swipe to the left on any chat in the chat list
4. Click "Favorite"
5. Nothing happened
6. Swipe right on any chat that was previously added to the favorites list
7. Nothing happened

### Expected behavior:

5. Сhat added to the favorites section on the chats list
7. The chat has been removed from the favorites section on the chats list

### Actual behavior:

5. Nothing happened
7. Nothing happened

**Comment by sumukhah** [comment]
I reproduced this issue. can you verify this @rocketbughunter 
If you add a channel to your favorite, then close the app (also remove from the recent app).
Again open the app. Can you see the favorite sections?
In my case, I can see it. I think the home screen does not update right a way on adding favorite item

**Comment by rocketbughunter** [comment]
@sumukhah Yes, if I add a chat to favorites and then restart the application (with removal from memory) - then when I start it again, I see the chat in favorites.
The same thing happens with exclusion from favorites - restarting the application helps me see the changes in the favorites.

**Comment by sumukhah** [comment]
Working on the issue 👍

**Comment by gdeusdara** [comment]
@sumukhah I just solved this problem. I will make the pull request correctly in the morning
