### ISSUE TITLE
Update Jitsi SDK to current version

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3086]
### Description:

Current Jitsi SDK version in RCRN application is 2.10.2, but most recent stable Jitsi SDK is [3.4.0](https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#340-2021-04-20) with lots of improvements and new features like screen sharing.

We have a long term bug https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2699 and I made an issue in Jitsi repo about that https://github.com/jitsi/jitsi-meet/issues/9060 but Jitsi team will not try to fix that bug in very old SDK version. And in Jitsi Meet application for Android (which is a wrapper for Jitsi SDK) no such problem.

So, I really believe that update Jitsi SDK in RCRN application can fix my critical problem and give other users fresh JItsi interface and a lot of new features!

### Environment Information:

- Rocket.Chat Server Version: 3.14.0-rc0
- Rocket.Chat App Version: 4.16.1
- Device Name: Xiaomi Mi9 SE
- OS Version: Android 10

### Steps to reproduce:

1. Launch RCRN application
2. Start Jitsi call
3. It's have outdated interface and don't have screen sharing 

### Expected behavior:

RCRN application have all Jitsi SDK recent features

### Actual behavior:

New interface is modern and looks good
![image](https://user-images.githubusercontent.com/4023037/115838142-097d9300-a422-11eb-89c4-4adc581de03b.png)

### Additional context:

@diegolmello Please, take it in your team roadmap.

**Comment by johncrisp** [comment]
Anton, as advised on open.rocket.chat this is extremely complicated. It isn't just as simple as 'change the SDK' - if it was it would have been done by now!

Devs are aware and it has been on the map for a long time but this is not going to get fixed any time soon. Opening new issues and tagging people hoping for a response will not change this.

Thank you for your patience.

**Comment by ankar84** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3292 will fix that.
I will close that issue after intensive testing of all Jitsi functionality.

**Comment by ankar84** [comment]
That issue is totally solved by 4.19.0 release https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/4.19.0
