### ISSUE TITLE
Sharing content results in Black screen 

### ISSUE THREAD

**Issue by avmentzer** [RocketChat/Rocket.Chat.ReactNative#3088]
### Description:

Sharing anything via Rocket.Chat results in a black screen 

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1
- Device Name:  IPhone XR
- OS Version:  14.4.2

### Steps to reproduce:

Share anything via Rocket.Chat 

### Expected behavior:

No blank screen 

### Actual behavior:

blank screen 
![DA009225-D901-4DAB-94CF-A678ECABC37A](https://user-images.githubusercontent.com/74241215/115965829-3b2e5100-a52b-11eb-967d-8e0767c6fa92.jpeg)
![300DF5B1-55C4-4B47-9ECE-6E4BEDFC6659](https://user-images.githubusercontent.com/74241215/115965830-3cf81480-a52b-11eb-90c8-c13a58a8ae20.png)

**Comment by sumukhah** [comment]
Hello @avmentzer, I tested this with (app: 4.17, server: 3.14), but could not reproduce the issue. Can you share a video record it the error still exist? 
Thank you

**Comment by avmentzer** [comment]
I already provided a Video to official support.
As you can see @ the Screenshot the screen stays blank, if I try to share sth via Rocket.Chat (the red button)

Von meinem iPhone gesendet

**Comment by cprice-kgi** [comment]
I ran into this same issue when testing 3.14. I looked into it and it appears the server setting for mobile screen lock is causing this issue. When it is turned on, I also get the black screen when sharing. I fixed it in my code and will open a PR for the fix.

If you have screen lock enabled on the server side, this could be the issue you are seeing as well.
