### ISSUE TITLE
There is no date (there is only time) on the "Read receipt" screen

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3096]
### Description:

on the "Read receipt" screen there is no reading date and only time. if the message was read on a different date, it cannot be seen (screenshot 1)

in the web version there is a date and you can see if the message was read on another day (screenshot 2)

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1.23838
- Device Name: Iphone 11 pro max
- OS Version: ios 14.4.2

### Steps to reproduce:

1. go to "Read receipt" screen for any message
2. do not see the date 

### Expected behavior:

2. we see the date and time

### Actual behavior:

2. we only see time

**Comment by rocketbughunter** [comment]
![1](https://user-images.githubusercontent.com/82801688/116387149-2d2a4a00-a823-11eb-9f46-1585e596c3dc.jpeg)

**Comment by rocketbughunter** [comment]
![2](https://user-images.githubusercontent.com/82801688/116387208-3fa48380-a823-11eb-8cf7-2ecea220149b.jpg)

**Comment by Geetsharma2000** [comment]
is this issue still open??. I am new to open source so can you please guide me .
