### ISSUE TITLE
iOs app not playing video from Filesystem ony from Gridfs

### ISSUE THREAD

**Issue by poltrian** [RocketChat/Rocket.Chat.ReactNative#3097]
### Description:

Hi,

video playing is only from Gridfs possible. Android is no problem and it works

Server: 3.13,2
iOS App: 4.16
Rocketchat runs as snap

Can someone me help please?

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16
- Device Name: 
- OS Version: Ubuntu Snap

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

It looks like the Videos will start but nothing happend

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2759
