### ISSUE TITLE
Crash after UserProfile on admin

### ISSUE THREAD

**Issue by DYG-GP** [RocketChat/Rocket.Chat.ReactNative#3098]
### Description:

Crash after click on user who joined the channel from any channel while logged in as admin.

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.13.1.1
- Device Name: xiaomi mi 10 lite
- OS Version: android 10

### Steps to reproduce:
1. Login as administrator
2. Go to 'Chats' 
3. Go to 'general' 
4. Click on 'any user who joined the channel'

![εικόνα](https://user-images.githubusercontent.com/70523946/116404969-d11df080-a837-11eb-9856-db53d75b72b0.png)

### Expected behavior:

Go to User Profile

### Actual behavior:

![εικόνα](https://user-images.githubusercontent.com/70523946/116405145-fdd20800-a837-11eb-8894-55d968b470e9.png)

**Comment by diegolmello** [comment]
Can you try on latest version? We're on 4.16.2 already.

**Comment by DYG-GP** [comment]
I tried with 4.16.1 same thing.
