### ISSUE TITLE
Error on npm run android

### ISSUE THREAD

**Issue by cyrilmarceau** [RocketChat/Rocket.Chat.ReactNative#3101]
Hello,

During the npm run android I have an error:

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 2820 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

I have tried with several versions and it is always the same error which returns.

Any idea why it's not working ?

I am on **mac** with **android studio.**

Thanks,

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md#how-to-run
