### ISSUE TITLE
the thread is not removed from unread immediately after reading

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3104]
### Description:

There is an unread thread in the channel. I go to the  "Threads" section and filter by "Unread". I see this thread. I fall into the thread and read it. I go back to the "Threads" section through the "Back" button - the thread is still in the Unread list. I change the filter to "All". Then again I change it to "Unread" - now there is no thread here.

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1.23838
- Device Name: Iphone 11 pro max
- OS Version: ios 14.4.2

### Steps to reproduce:

1. find an unread thread in a channel
2. go to the  "Threads" section and filter by "Unread"
3. fall into the thread and read it
4. go back to the "Threads" section through the "Back" button
5. the thread is still in the Unread list
6. change the filter to "All"
7. again I change it to "Unread"
8. there is no thread in the Unread list

### Expected behavior:

5. there is no thread in the Unread list

### Actual behavior:

5. the thread is still in the Unread list

**Comment by gdeusdara** [comment]
Hey! I did a pull request solving this problem, please check it out (: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3112
