### ISSUE TITLE
Application extensions and any libraries they link to must be built with the `APPLICATION_EXTENSION_API_ONLY` build setting set to YES.

### ISSUE THREAD

**Issue by shaheem-khanzada** [RocketChat/Rocket.Chat.ReactNative#3106]
i am using new M1 chip apple pro with 12.5 xcode and when ever i build latest develop branch of RC i get this error
Application extensions and any libraries they link to must be built with the `APPLICATION_EXTENSION_API_ONLY` build setting set to YES.

**Comment by diegolmello** [comment]
https://github.com/facebook/react-native/issues/31179
