### ISSUE TITLE
can't close the keyboard after entering data in one text box on the screen "Room Info Edit"

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3113]
### Description:

I go to the "Room Info Edit" screen. Tap on the  "Name" field - the keyboard appears and I enter the text. After entering the text, it is not possible to remove the keyboard - tap outside the input field does not remove it, pressing return on the keyboard also does not remove it, but transfers the input focus to the next text field. But I wanted to change only the "Name" field and did not want to change the rest of the fields, but I cannot remove the keyboard until I click the focus on all text fields

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1.23838
- Device Name: Iphone 11 pro max
- OS Version: ios 14.4.2

### Steps to reproduce:

1. go to the "Room Info Edit"
2. Tap on the  "Name" field and edit it
3. try to remove the keyboard with a tap outside of the input field
4. the keyboard cannot be closed

### Expected behavior:

4. the keyboard is closed when tapping outside the input field area

### Actual behavior:

4. the keyboard cannot be closed

**Comment by matheus-rn** [comment]
i will work on it
