### ISSUE TITLE
error when disabling system notifications in chat

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3115]
### Description:

trying to disable system notifications in chat. select all available items and get an error while saving. there is no such error in the web version and it is successfully saved there

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1.23838
- Device Name: Iphone 11 pro max
- OS Version: ios 14.4.2

### Steps to reproduce:

1. go to "Room info edit"
2. turn on "Hide system messafes"
3. select all available items
4. I press the save button
5. I get an error saving settings (video 1).

### Expected behavior:

5. successful saving of settings

### Actual behavior:

5. I get an error saving settings

**Comment by rocketbughunter** [comment]
https://user-images.githubusercontent.com/82801688/117297730-38165780-ae7f-11eb-94f7-d91aedb86811.mp4

**Comment by ARKEOLOGIST** [comment]
This error particularly happens when one tries to set the Hide "Was Set Role" messages or Hide "Role No Longer Defined" messages. One can enable the other messages without getting an error.
