### ISSUE TITLE
function "Unarchive" the channel does not work

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3118]
### Description:

I archive the channel, the "Unarchive" button appears, but it does not work

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1.23838
- Device Name: Iphone 11 pro max
- OS Version: ios 14.4.2

### Steps to reproduce:

1. archive channel
2. "Unarchive" button appears
3. tap "Unarchive" but nothing happens (video 1).

### Expected behavior:

3. "Archive" button appears and the channel comes back

### Actual behavior:

3. tap "Unarchive" but nothing happens

**Comment by rocketbughunter** [comment]
https://user-images.githubusercontent.com/82801688/117309921-8fbac000-ae8b-11eb-9bf8-cada028cc047.mp4

**Comment by ARKEOLOGIST** [comment]
Is this unique to iOS? I couldn't reproduce it in an Android environment.

**Comment by rocketbughunter** [comment]
I checked now on an android device - the behavior is exactly the same. It is possible to archive, but the Unarchive button does not work

**Comment by diegolmello** [comment]
Maybe server version or permission related
