### ISSUE TITLE
Search on the screen "Members" do not cut off spaces at the beginning and at the end of the search phrase

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3122]
### Description:

Search on the screen "Members" do not cut off spaces at the beginning and at the end of the search phrase. "user" - finds, " user" - does not find, "user " - does not find
search in the  "Directory" and on the chat list - cuts off spaces at the beginning and at the end of the search phrase

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.1.23838
- Device Name: Iphone 11 pro max
- OS Version: ios 14.4.2

### Steps to reproduce:

1. go to the section "Members"
2. search by "user" - successfully finds a user
3. search by " user" - does not find
4. search by "user " - does not find

### Expected behavior:

3. search by " user" - successfully finds a user
4. search by "user " - successfully finds a user

### Actual behavior:

3. search by " user" - does not find
4. search by "user " - does not find

**Comment by ARKEOLOGIST** [comment]
@diegolmello I'd like to work on this.
