### ISSUE TITLE
Can not send any message after open Rocket Chat over Notification

### ISSUE THREAD

**Issue by Zeromax** [RocketChat/Rocket.Chat.ReactNative#3136]
### Description:

This bug occures when a push notification was recieved and the app will be opend with this push notification. Then a message can not be send due to an error. The App has to be closed and reopend again to send any message.

### Environment Information:

This App is a single server Version but updated to the latest rocket chat version. So far no other modifications are made.

- Rocket.Chat Server Version: 3.14.0
- Rocket.Chat App Version: 4.16.2 (created from single server branch)
- Device Name: Pixel 4
- OS Version: Android 11

### Steps to reproduce:

1. The app was already opened on user B device and moved to Background
2. Login as User A and send a message to user B
3. On the User B device click on the Notification to open the app
4. Direct insert a reply after the chat was opend
5. You will see an Error that the message was not send
6. Go to any other chat / channel and try to send a message: It will always look the same

### Expected behavior:

User B is able to send messages without an error and should not restart the app.

### Actual behavior:
A is User A.
And the one, with the picture is user B.
![grafik](https://user-images.githubusercontent.com/1867177/118176157-578a2300-b431-11eb-9f84-579a36c86770.png)

### Additional context:

Bugsnag Error:
![grafik](https://user-images.githubusercontent.com/1867177/118176355-9a4bfb00-b431-11eb-8883-ca370066d338.png)

[bugsnag_error_stacktrace_TypeError_event_609d7a00007bed81f8270000.txt](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/6480532/bugsnag_error_stacktrace_TypeError_event_609d7a00007bed81f8270000.txt)

**Comment by diegolmello** [comment]
@Zeromax Thanks for reporting.
Reply from notification doesn't use JS code.
It's done from the native side https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/android/app/src/play/java/chat/rocket/reactnative/ReplyBroadcast.java#L58
I'm interested to know how did you get to that bugsnag report though.

**Comment by Zeromax** [comment]
We are currently going to run our own RocketChat server and therefore we compiled the apps by our own as single-server edition (like described in the docs) There it is described to insert a Bugsnag API Key and I have created my own account.

If you need any further Information, let me know. We have this bug also on a samsung device.

When opening the app via Notification from the background then the bugsnag event I posted occures. I believe it has somthing to do with getting the app back from background.

**Comment by diegolmello** [comment]
Oh, I misunderstood your issue.
I thought it was replying from notifications, but it's actually resuming the app from notification and establishing the socket connection back.
Does it happen all the time or it's after some time in background?

**Comment by Zeromax** [comment]
When reporting I had this Issue all the time. But when testing again, it workes sometimes. So it is hard to say how long it should stay in the background.  Also I was not able to reproduce this in my Emulator. Only on real devices.

**Comment by diegolmello** [comment]
Ok.
What happens is the OS starts to disable some features from the apps in background after some time in order to free memory and battery consumption.
Some manufacturers are more aggressive than others.
The method you've found is in charge of check that and reopen the socket connecting if necessary.
When we implemented it we had to leave the app in background for 10~30 minutes to be able to reproduce it, so it's unreliable to reproduce.
We're going to take a look on it.
Thanks!

**Comment by diegolmello** [comment]
Can you reproduce it on the official version of the app and let us know?

**Comment by Zeromax** [comment]
Yes I will try. Thanks for all your effort.

**Comment by Zeromax** [comment]
Ok, that is weird. I can not reproduce it with the official App. Using https://open.rocket.chat/

I tryed it like I am able to get the Issue for my App. But it seems that there is something different.

**Comment by diegolmello** [comment]
Ok, removing the bug label for now. Let us know if you can reproduce it.

**Comment by Zeromax** [comment]
Do you think it can be an Issue inside the single-server branch? If I compare develop with single-server branch there are a lot of differnces. I thought that there aren't that much 😉.

I will try to use the develop branch in the evening to check if it works fine then. IMO this Issue only occures when using the single-server branch. But let me check this out.

**Comment by diegolmello** [comment]
Ok. Feel free to open a PR to `single-server` if you find the issue.

**Comment by tpat2** [comment]
I can confirm this on my single-server app version as well, version 4.16.1.3

**Comment by Zeromax** [comment]
@diegolmello We are currently testing a fix. I will provide a PR as soon as we can verify that the problem is gone. But it looks really good!

**Comment by diegolmello** [comment]
Awesome, @Zeromax! :)

**Comment by Zeromax** [comment]
Fixed with #3145
