### ISSUE TITLE
Two serious E2E  problem

### ISSUE THREAD

**Issue by amandajulia** [RocketChat/Rocket.Chat.ReactNative#3142]
### Environment Information:

- Rocket.Chat Server Version: 3.12.5
- Rocket.Chat App Version: 4.16.2
- Device Name: samsung
- OS Version: android 10

### Steps to reproduce:

First Serious E2E Problem
1. Create Private Channel & Encrypted
2. Add users
3. User Join
4. Message Upload
5. The rocketchat app is infinitely loaded and crash down

Second Serious E2E Problem
1. Create Direct Messages
2. Can't Encrypted for Direct Messages Room 

Third Serious E2E Problem
1. Create Private Channel
2. Add users
3. User Join
4. Message Upload
5. Channel Encrypted
6. After that, user can't input message and can't see new message but channel owner works well

### Additional context:

First Serious E2E Problem( One case that works normally )
1. Create Private Channel & Encrypted
2. Add users
3. **The channel owner first uploads a message before the user join**
4. User Join
5. works normally
**Please solve this three serious E2E problem**

**Comment by diegolmello** [comment]
Hey, @amandajulia.
Try to open separate issues for separate bugs.
This way two different developers can work on a fix and we can talk about each one separately.
Thank you.
