### ISSUE TITLE
 Can't encrypt direct messages room( Slide button not work )

### ISSUE THREAD

**Issue by amandajulia** [RocketChat/Rocket.Chat.ReactNative#3144]
### Environment Information:

- Rocket.Chat Server Version: 3.12.5
- Rocket.Chat App Version: 4.16.2
- Device Name: samsung
- OS Version: android 10

### Steps to reproduce:

1. Create Direct Messages
2. Can't encrypt direct messages room( Slide button not work )

**Comment by fidelsam1992** [comment]
You need to set the "Toggle Room E2E Encryption" permission to the user role
