### ISSUE TITLE
Build fail on Xcode 12.5 with OpenSSL 1.1.x

### ISSUE THREAD

**Issue by bingluen** [RocketChat/Rocket.Chat.ReactNative#3146]
In order to support Xcode 12.5, flipper have to upgrade to new version.  [1][2][3]

Unfortunately, the version 1.1.x of OpenSSL is need by the new versions of flipper (such as 0.87.0) that support Xcode 12.5. [4]

`react-native-simple-crypto`[5], dependency of Rocket.Chat.ReactNative, using OpenSSL 1.0.x APIs, but there are some breaking change between 1.0.x and 1.1.x. [6]

<img width="799" alt="image" src="https://user-images.githubusercontent.com/6832868/118815342-bc3af700-b8e3-11eb-9e9f-cdb37a31c362.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/6832868/118815385-c78e2280-b8e3-11eb-823e-08dfdcc0c072.png">

Ref:
[1] https://github.com/facebook/flipper/issues/2215
[2] https://github.com/facebook/folly/issues/1527
[3] https://stackoverflow.com/questions/66019068/event2-event-config-h-file-not-found
[4] https://github.com/facebook/flipper/blob/v0.87.0/iOS/Podspecs/Flipper-Folly.podspec#L19
[5] https://github.com/RocketChat/react-native-simple-crypto/blob/master/ios/RCTCrypto/RCTRsaUtils.swift
[6] https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes#Compatibility_Layer

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3106#issuecomment-831372760

**Comment by diegolmello** [comment]
@bingluen It's a known issue on React Native with Xcode 12.5.
Can you contribute with a fix based on the comment above?

**Comment by bingluen** [comment]
@diegolmello
I am not familiar with developing cocoapod.
But I will try my best to do this.

**Comment by brijpatel6080** [comment]
![Screenshot 2021-05-21 at 2 24 21 PM](https://user-images.githubusercontent.com/31682945/119299309-4c7a9280-bc7c-11eb-9af7-441f5b75c1d7.png)



I face this error until last 6 to 7 days any one help me out for the successfully done this project

**Comment by rajesh-puranik** [comment]
Same issue in Xcode: 12.4.

**Comment by rajesh-puranik** [comment]
I found solution by changing this line it works => use_flipper!({ 'Flipper-Folly' => '2.2.0' }) because it need OpenSSL-Universal (1.0.2.19). Tested on Xcode 12.4

**Comment by diegolmello** [comment]
@rajesh-puranik Can you contribute back with a PR?

**Comment by rajesh-puranik** [comment]
@diegolmello created PR https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3163

**Comment by salmankhadim36** [comment]
<img width="853" alt="118815385-c78e2280-b8e3-11eb-823e-08dfdcc0c072-2" src="https://user-images.githubusercontent.com/53314237/121078736-c2d9d180-c7f2-11eb-8c16-2cbecdc7fe7e.png">

Build fail on Xcode 12.5

**Comment by uluzox** [comment]
> I found solution by changing this line it works => use_flipper!({ 'Flipper-Folly' => '2.2.0' }) because it need OpenSSL-Universal (1.0.2.19). Tested on Xcode 12.4

This did not work for me. I am seeing
```
react-native/Libraries/LinkingIOS/RCTLinkingManager.mm:102:27: error: 'openURL:options:completionHandler:' is unavailable: not available on iOS (App Extension)
  [RCTSharedApplication() openURL:URL options:@{} completionHandler:^(BOOL success) {
```

**Comment by ferkawi** [comment]
Same here! Xcode 12.5 and M1

**Comment by diegolmello** [comment]
I don't recommend using Xcode 12.5 (you can download 12.4) or new Flipper versions yet (I'm running v0.57 fine here).
I've been working updating all libs and noted this as an issue.
OpenSSL 1.1 changed a lot and we'll have to tweak react-native-simple-crypto to make it work.
I might have a fix in a few weeks (or sooner 🤞 ).

**Comment by ferkawi** [comment]
I will give a try! thank you @diegolmello !

**Comment by ferkawi** [comment]
So after a lot of tries, is working now, after a fresh clone. Xcode 12.4 Mac Mini M1. 

Maybe help somebody: if u get "build commands failed": CompileSwift and CompileSwiftSources just add in the root a new Swift File and include it to all Targets. The file should have only the import Foundation. After that clean the Project (Product->Clean) and rebuild!

**Comment by ferkawi** [comment]
So after a lot of tries, is working now, after a fresh clone - without change Flipper. Xcode 12.4 Mac Mini M1.

All the Problems are because of the M1... The Solution...Cocoapods doesnt work with M1 so we should install it with a Rosetta Terminal and exclude arm64 architectur for the project. I excluded it an all Targets and Pod file. Here more:

https://narlei.com/development/apple-m1-xcode-error-when-build-in-simulator/
https://narlei.com/development/apple-m1-install-cocoapods/

After that, I can build without problems in both Terminals(Rosetta and arm64)

**Comment by diegolmello** [comment]
Fixed by #3245

**Comment by uluzox** [comment]
This fix is not part of the `single-server` branch yet, is it? 
When will it be merged to the `single-server` branch?

**Comment by diegolmello** [comment]
No, it's not released yet.
We still need to battle test everything because it was a huge change and the release is going to happen ~Aug 23.
That's when we merge develop into main and we update single-server and whitelabel docs.

**Comment by uluzox** [comment]
Will there be any announcement of this being merged into single-server?

**Comment by diegolmello** [comment]
We update `single-server` branch to match `master` every release.
https://rocket.chat/blog/product/mobile-app-4-19/
