### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.ReactNative#315]
- [ ] Roomlist
- [ ] RoomView
- [ ] Pinned/Starred/Search

![image](https://user-images.githubusercontent.com/5263975/40721307-856528f0-63ef-11e8-8716-5343752e4208.png)

**Comment by Prateek93a** [comment]
@ggazzo Can you please ellaborate on the issue ?

**Comment by diegolmello** [comment]
@ggazzo I think we don't need this anymore.
