### ISSUE TITLE
[Jitsi] ScreenSharing drops in RCRN when using recent versions of Jisti server

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3158]
### Description:

First of all and most important thing - I'm creating that issue not for devs fix that immediately, no!
I'm making that issue to inform dev and all users of possible problems with recent Jitsi server versions and current RCRN applications and publish a workaround for that problem.
Main issue for all Jitsi problems is https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3086 and I know devs aware about that and Jitsi SDK update is in a long-term milestone.
I'm not try to rush something in that theme with that issue, it's just a report.

We see that issue on two last releases of Jitsi servers:
https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md#205765-21-04-15 and this https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md#205870-21-05-12 (which is looks like a bug fix for BWE stuff)

There was a [bug](https://github.com/jitsi/jitsi-meet/issues/7227#issuecomment-832765808) in version 2.0.5870 with BWE that lead to ScreenSharing was dropped for all clients after period of time. And here is a solution for that [bug](https://github.com/jitsi/jitsi-videobridge/pull/1643).

And before bug fix version 2.0.5765 was released there was one workaround to fix that issue on involved version - is to [set](https://github.com/jitsi/jitsi-meet/issues/7227#issuecomment-776078011) trust-bwe to false (disable BWE).

So, now I can describe  RCRN issue. 
When you Jisti server is on version 2.0.5870 or 2.0.5765 you can experience unexpected stop of ScreenSharing on RCRN application.
Workaround for this issue is to set inside of the existing videobridge { ... } structure in jvb.conf

```
    cc {
        trust-bwe=false
    }
```
Why I'm claiming that is only RCRN problem? Because Jitsi Meet application (which is on updated Jitsi SDK) don't have that problem - ScreenSharing not disappear.

### Environment Information:

- Rocket.Chat Server Version: 3.14.0
- Rocket.Chat App Version: 4.16.2
- Device Name: Xiaomi Mi 9 SE (but lot of iPhone and iPad users complaining about that issue)
- OS Version: Android 10

### Steps to reproduce:

1. Start Jitsi call on computer with ScreenSharing
2. Join on RCRN app
3. Check that ScreenSharing not shows

### Expected behavior:

ScreenSharing should work stable - it's really critical feature for users.

### Actual behavior:

ScreenSharing now shows

### Additional context:

We have workaround for that issue.

**Comment by diegolmello** [comment]
Thanks, Anton.
We're finishing Full Support to Teams and Jump to Message.
The next thing I'll try to assign to me is update libs :)
If it happens, I'm probably going to start working on it in June.
Besides Jitsi, there're cool new updates on React Native, react-navigation, reanimated, etc that improves the performance a lot!
Let's hope nothing else comes in the way 🤞

**Comment by ankar84** [comment]
That is a very good news, Diego, indeed!
My finger crossed!
Hope you'll get it!

**Comment by ankar84** [comment]
Testing early beta on 4.19 with `trust-bwe=true` and ScreenSharing looks good and stable.
I will continue testing and close that issue when be 100% sure it solved by new Jitsi SDK in 4.19.
Thanks, Diego!

**Comment by ankar84** [comment]
I can close that issue only after we build whitelabel application based on 4.19.0 and test it with `trust-bwe=true` in detail.

**Comment by ankar84** [comment]
Lets close it
