### ISSUE TITLE
Scrolling "Files" always crashes after a few seconds

### ISSUE THREAD

**Issue by slajerek** [RocketChat/Rocket.Chat.ReactNative#3167]
### Description:

Go to channel, open "Files", scroll down a while - it always crashes, and issue there is for some quite long time already.

### Environment Information:

- Rocket.Chat Server Version: 3.11.1
- Rocket.Chat App Version: 4.16.2.23928
- Device Name: iPhone7
- OS Version: 14.5

### Steps to reproduce:

1. Click on channel name
2. Select to view "Files"
3. Scroll, scroll. Often after 1-2 seconds of scrolling it crashes, sometimes a bit more.

### Additional context:

Could be that the crash is related to a specific file, but there are mainy photos/images and videos in the channel as far as I know (can't confirm now because app crashes)

**Comment by milton-rucks** [comment]
Not possible to reproduce
