### ISSUE TITLE
When replying with a quote to a message with an attachment, only the name of the user who sent the attachment is displayed as a quote

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3168]
### Description:

When replying with a quote to a message with an attachment, only the name of the user who sent the attachment is displayed as a quote. And it is not clear to other users which attachment it was a reply with a quote to.

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.2.23928
- Device Name: Iphone 11 pro max
- OS Version: ios 14.6

### Steps to reproduce:

1. send an attachment to the chat with a text description to it
2. select a "Quote" through the context menu for this message and reply with a quote
3. as a quote in the chat, only the name of the user who sent the attachment was displayed and it is not clear to other users which attachment it was a reply with a quote to

### Expected behavior:

3. the text description of the attachment or the attachment itself is displayed as a quote

### Actual behavior:

3. as a quote in the chat, only the name of the user who sent the attachment was displayed

**Comment by diegolmello** [comment]
Duplicated #704
