### ISSUE TITLE
Setting the duration of notifications does not work

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3170]
### Description:

I set different duration of notifications on the "Notification Preferences" screen, but the duration of the notification is still standard

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.2.23928
- Device Name: Iphone 11 pro max
- OS Version: ios 14.6

### Steps to reproduce:

1. On the "Notification Preferences" screen set any duration for notification
2. Notifications keep coming with standard ios duration

### Expected behavior:

2. Notifications keep coming with standard ios duration

### Actual behavior:

2. Notifications keep coming with standard ios duration

**Comment by diegolmello** [comment]
That's under "Desktop Options"
