### ISSUE TITLE
setting off "Show Unread Counter" does not work

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3180]
### Description:

On the "Notification Preferences" screen there is a setting "Show Unread Counter". 
if I turn it off, the unread count is still displayed

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.2.23928
- Device Name: Iphone 11 pro max
- OS Version: ios 14.6

### Steps to reproduce:

1. go to direct correspondence with any user
2. on the "Notification Preferences" screen turn off the setting "Show Unread Counter"
3. I receive messages from this user and the unread counter in the circle to the right of the chat is still displayed on the chat list

### Expected behavior:

3. unread counter is not displayed

### Actual behavior:

3. unread counter is displayed

**Comment by diegolmello** [comment]
Does it still happen after closing and reopening the app?

**Comment by rocketbughunter** [comment]
Yes, after closing and reopening the app the unread counter in the circle to the right of the chat is still displayed on the chat list
