### ISSUE TITLE
in the android application there is no red circle with the number of unread messages on the rocket chat icon on the desktop

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3191]
### Description:

in the android application there is no red circle with the number of unread messages on the rocket chat icon on the desktop

### Environment Information:

- Rocket.Chat Server Version: 3.13.2
- Rocket.Chat App Version: 4.16.2.23928
- Device Name: Iphone 11 pro max
- OS Version: ios 14.6

### Steps to reproduce:

1. send several messages from another account in a direct, or @here or @all in the chat
2. in the ios application on the rocket icon on the desktop there is a red circle with the number of unread messages
3. in the android application on the rocket icon on the desktop there is no a red circle with the number of unread messages

### Expected behavior:

3. in the android application on the rocket icon on the desktop there is a red circle with the number of unread messages

### Actual behavior:

3. in the android application on the rocket icon on the desktop there is no a red circle with the number of unread messages

**Comment by diegolmello** [comment]
The badge depends on Android manufacturer to implement badge feature.
You didn't specify which Android device you have, so I can't tell.
Closing for now.
We can reopen if it's the case.

**Comment by rocketbughunter** [comment]
Sorry, I mistakenly indicated an ios device instead of an android

Device Name: Xiaomi Redmi Note 8 Pro
OS Version: android 10

I do not have a new message icon on this device
