### ISSUE TITLE
Unable to switch to channel in which a thread was previously selected

### ISSUE THREAD

**Issue by leitmori** [RocketChat/Rocket.Chat.ReactNative#3193]
### Description:

It is not possible to switch to a channel in which a thread was previously selected.

### Environment Information:

- Rocket.Chat Server Version: 3.15.0
- Rocket.Chat App Version: 4.16.2
- Device Name: iPad Air 4
- OS Version: iOS 14.6

### Steps to reproduce:

1. Select a thread in Channel A
2. Switch to Channel B
3. Try to switch back to Channel A

### Expected behavior:

Channel A is displayed

### Actual behavior:

Nothing happens

https://user-images.githubusercontent.com/29522608/121018800-20dcc980-c79f-11eb-995e-ceafb9a6c49b.mp4

**Comment by OneTwoBarbecue** [comment]
Facing the same problem here.
Server Version is Snap 3.15.0, App-Version is 4.17.0 on IPad/IOS.
Additionally when entering a discussion in a channel via the blue button in the messages-view on the right there is no way back to the parent channel.
Inside a discussion no move-back-arrow is shown in the discussion header (as is when entering threads).
Clicking on the parent channel in the channel-list also shows no reaction.
Both issues might be connected.
Kind regards, Marco

**Comment by reinaldonetof** [comment]
Thanks for the report! We will work on that!

**Comment by leitmori** [comment]
It is once again not possible to switch to a channel in which a thread was previously open.
https://user-images.githubusercontent.com/29522608/145264988-6a452174-c196-4fda-b5de-a320a0d90817.mov
