### ISSUE TITLE
livechat dialogs never loads any message (well once messages was loaded successfully)

### ISSUE THREAD

**Issue by cypa** [RocketChat/Rocket.Chat.ReactNative#320]
- Your Rocket.Chat.Android app version: I've not found version on any screen, in Play Market it's version 1

- Your Rocket.Chat server version: ####

- Device model (or emulator) you're running with: HUAWEI  T1-701u android 4.4.2
- Steps to reproduce:
open app and try to read chat with cyrillic name - it never loads any message

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by cypa** [comment]
sorry, correction:
livechat messages load take 10+ minute whatever cyrillic or latin name

**Comment by ggazzo** [comment]
@cypa is it just for livechat messages? the another messages are loading fast?

**Comment by cypa** [comment]
#name channels and privat chats mostly OK, but transient problems exist
livechat dialogs have the problem always with rare exceptions

**Comment by ggazzo** [comment]
we will check your problem... :)

**Comment by cypa** [comment]
you need any debug info?
