### ISSUE TITLE
[BUG] Discussion title shown incorrectly

### ISSUE THREAD

**Issue by aKn1ghtOut** [RocketChat/Rocket.Chat.ReactNative#3200]
### Description:

The Discussion name shown in the header does not match what was entered, neither does the testID being passed in the header.
https://user-images.githubusercontent.com/38764067/121415491-6b1f9f80-c985-11eb-845d-c6a3af249b54.mp4
### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version: Latest develop
- Device Name: Pixel 3
- OS Version: Android 9

### Steps to reproduce:

Create a new discussion as shown in the video above. Name entered above= "wxphrfbvkrowafuawmk Discussion NewMessageView"

### Expected behavior:
The title to match what was entered.

### Actual behavior:

Random string/Id being shown instead.

### Additional context:

Might be related to #1842

**Comment by diegolmello** [comment]
We updated the server. Can you try again?

**Comment by aKn1ghtOut** [comment]
Correctly showing now! Thanks Diego!
