### ISSUE TITLE
Android App Bug Turkish lang

### ISSUE THREAD

**Issue by gencay99** [RocketChat/Rocket.Chat.ReactNative#3203]
Hello… While using the Phone Language Turkish in the android application, the process of sending picture, video or audio file from the application fails. It gives a try again warning. I don’t have this problem when I change the language of the phone to English. seamless file, image, etc. transfer operations are working smoothly. I have installed and tried all versions of your Android application one by one, but I do not have this problem with your version 4.9.0.2132.

Server Status:
Deployment

Sürüm

3.15.0

Dağıtım kimliği

jFtqcD22wr34nHvRu

Uygulamalar Motoru Sürümü

1.26.0

Node versiyonu

v12.22.1

Veritabanı Geçişi

225 (Haziran 7, 2021 20:20)

MongoDB

4.0.24 / mmapv1 (oplog Etkin)

Commit Details

HEAD: (55457025d)
Branş: HEAD

PID

800

**Comment by diegolmello** [comment]
Duplicated #3040
