### ISSUE TITLE
iOS APN push not working

### ISSUE THREAD

**Issue by alananayaa** [RocketChat/Rocket.Chat.ReactNative#3209]
### Description:

iOS Rocket Chat native APN for push notifications not working for white label app, FCM is working correctly

### Environment Information:

- Rocket.Chat Server Version: 3.14.4
- Rocket.Chat App Version: 4.16.2
- Device Name: iPhone 12
- OS Version: 14.6

### Steps to reproduce:

1. Register APN keys to admin on RocketChat server
2. Send test push notification

### Expected behavior:

Get a push notification on iPhone 

### Actual behavior:

Not getting a push notification

**Comment by pritamye77** [comment]
Hi, i'm not getting push notification in ios...please help what you have done to fix it ?
