### ISSUE TITLE
Unable to login to self-signed server with iOS client. Cert problem.

### ISSUE THREAD

**Issue by wtwangcb** [RocketChat/Rocket.Chat.ReactNative#3216]
### Environment Information:

- Rocket.Chat Server Version: 3.15.0
- Rocket.Chat App Version: Updated to latest version in App Store
- Device Name: iPhone 12
- OS Version: iOS 14

### Steps to reproduce:

1. 
Generate self-signed certificates and setup nginx reverse proxy according to the offical docs located here:
https://developer.rocket.chat/guides/developer/mobile-apps/supporting-ssl-for-development-on-rocket.chat
2. 
Put the generated CA-root certificate .crt file on a local server accessible from iPhone. Download it with Safari.
Install it via Settings and enable the certificate in the "About Device"
3. 
Update the Rocket.Chat client to the latest version available. In the "Open Workspace", type in my self deployed
server address, and click enter. A dialog pops up complaining "An error occurred while establishing SSL 
and a secure connection to the sever cannot be made."
4. I also tried using "Apply certificate" located on the bottom of the screen and navigate to the certificate location.
But the cert. file is all grayed out. What's the use for "Apply certificate"??
5. The same self-deployed server works perfectly on Android platform. But on iOS it keeps getting errors.

### Expected behavior:

Should be login in to server
### Actual behavior:

A dialog pops up complaining "An error occurred while establishing SSL 
and a secure connection to the sever cannot be made."

**Comment by wtwangcb** [comment]
I just looked at the source sslPinning.js and found that it requires certificate in p12 format.
I then convert my cert to p12 with OpenSSL， and now the "Apply Cert" function works and successfully applied 
my root certificate. But upon typing in my server and  click connect. The dialog pops up again. Same error as before.
"An error occurred while establishing SSL and a secure connection to the sever cannot be made."

**Comment by wtwangcb** [comment]
Any ideas on how to solve this/??

**Comment by johncrisp** [comment]
Hi,

github is for proven bugs and not general support

Please follow up on your thread in open.rocket.chat here and we will try and assist you. If we discover a bug we can re-open this.

https://open.rocket.chat/channel/react-native?msg=NgUNbckLqlKusnAuH
