### ISSUE TITLE
Unable to build iOS app on single-server branch

### ISSUE THREAD

**Issue by uluzox** [RocketChat/Rocket.Chat.ReactNative#3220]
### Description:
I checked out the `single-server` branch of your project, and I am unable to build the ios app.

The build fails with
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RocketChatRN.xcworkspace. Run CLI with --verbose flag for more details.
```
verbose build log:
[build.log](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/6668510/build.log)

It seems that some expected method is not available:
```
react-native/Libraries/LinkingIOS/RCTLinkingManager.mm:102:27: error: 'openURL:options:completionHandler:' is unavailable: not available on iOS (App Extension)
  [RCTSharedApplication() openURL:URL options:@{} completionHandler:^(BOOL success) {
  ```
 
### Environment Information:
- OS Version: macOS Big Sur Version 11.2.1
- XCode
```
xcodebuild -version
Xcode 12.5
Build version 12E262
```

### Steps to reproduce:
```
yarn
npx pod-install
yarn ios
```
### Expected behavior:
App is build.

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3146#issuecomment-844079442

**Comment by ferkawi** [comment]
Hey @uluzox did you solve this issue? I was 3 days just trying a lot of "Solutions" but nothing solved the issue... Also Xcode 12.5 with an M1..thank you!
