### ISSUE TITLE
4.17.0: Share extension on IOS not working anymore in many apps

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#3221]
### Description:

With the share extension I was able to also share i.e. pictures from other apps. This does not work anymore with 4.17.0. Usage of the share extension in the picture gallery is still working.

### Environment Information:

- Rocket.Chat Server Version: 3.15.0
- Rocket.Chat App Version: 4.17.0
- Device Name: iPhone 11 Pro Max
- OS Version: IOS 14.6

### Steps to reproduce:

1. Open the Signal app
2. Tap on any picture in a chat
3. Tap on the share extension icon
4. RocketChat is not in the list of the target apps and can't be added

### Expected behavior:

The RC app should show up as a destination for the sharing

### Actual behavior:

The official RC app and my whitelabeled app completely disappeared from the sharing dialog. In 4.16.x all was working!

![image](https://user-images.githubusercontent.com/3321655/122402024-68244080-cf7d-11eb-8e48-3841b2d0a89c.png)

**Comment by diegolmello** [comment]
I could not reproduce, but I saw that happening to some other apps on iOS.
It looks like an issue on iOS 14 https://developer.apple.com/forums/thread/662671
