### ISSUE TITLE
Collapsed and markup language on attachments

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat.ReactNative#3224]
### Description:

Android mobile app does not parse attachments as expected ( like in electron or webapp )

### Environment Information:

- Rocket.Chat Server Version: 3.14.5
- Rocket.Chat App Version: 4.17.0
- Device Name: Oneplus
- OS Version: 10

### Steps to reproduce:

1. Create a simple incoming webhook
2. Send the following example as data
```
{
  "text": "Mensagem padr\u00e3o (0 objects)",
  "attachments": [
    {
      "color": "#00FF00",
      "text": "**Attachment 1 in Bold text.**<br>Line 1 no formatting applied<br><em>Line 2 italic</em><br>Line 3",
      "collapsed": true,
      "title": "Log output collapsed"
    }
  ],
  "emoji": ":white_check_mark:"
}

```
### Expected behavior:

I was expecting to see the same behaviour I see on web and electron app. When the message arrive it would be collapsed and I would have to click to see the full log:
![image](https://user-images.githubusercontent.com/5522389/122564837-331afb00-d01c-11eb-94f0-65e25d0d7f02.png)

After expanding , I would see the text formatted like this:
![image](https://user-images.githubusercontent.com/5522389/122564902-429a4400-d01c-11eb-93de-eea2ab69e513.png)

### Actual behavior:

This is what I see:
![image](https://user-images.githubusercontent.com/5522389/122565052-6b223e00-d01c-11eb-8b74-ffb82e26f406.png)

### Additional context:
I understand that maybe it is not easy to respect the collapse property, but wrong formatting makes output hard to read.

**Comment by diegolmello** [comment]
Can you give us more info and follow the issue template?

**Comment by jsalatiel** [comment]
> Can you give us more info and follow the issue template?

Sorry about that, @diegolmello . I created the issue on github mobile and it does not show the issue template.

Hope now it is a lot better to understand =)
