### ISSUE TITLE
click to enter, there is no response.

### ISSUE THREAD

**Issue by jianghuac** [RocketChat/Rocket.Chat.ReactNative#3226]
### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name: 
- OS Version: 

### Steps to reproduce:

1. 
2. 
3. 

### Additional context:

Fill in the domain name can login, but, after entering the account password, click to enter, there is no response.

**Comment by johncrisp** [comment]
Hi, we can't help you without all the correct details.

Github is for bugs and we can see no errors here.

Please ask for support in https://open.rocket.chat/ #support
