### ISSUE TITLE
Links do not work if protocol is not set in URL prefix

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#3231]
### Description:

Links do not work if protocol is not set in URL prefix

When you send a link in example.com format the address is highlighted and the hyperlink is created but when you try to click it does not react.

I think that's what was meant in #3226

### Environment Information:

- Rocket.Chat Server Version: 3.15
- Rocket.Chat App Version: 4.17
- Device Name: Xiaomi - Samsung
- OS Version: Android 8 and 9

### Steps to reproduce:

1. Send link in example.com format
2. Click
3. Does nothing

### Expected behavior:

Open the link

### Actual behavior:

Hyperlink function does not react

### Additional context:

The links sent with the established protocol without working correctly for example http://example.com

**Comment by RcleydsonR** [comment]
Is this bug still happening ?
