### ISSUE TITLE
[Security Issue] Access token revealed in uploaded file url. Access to the files not properly checked

### ISSUE THREAD

**Issue by spdreg** [RocketChat/Rocket.Chat.ReactNative#3236]
### Description:

On iOS RocketChat app users can acquire  full url link to uploaded file in channel. 
This url contains userid and access token. 
user can send this link to someone else which will revel his userid and access token
Access token as I understood do not have expiration time

So by sending such url user in fact 1) will send permanent link to the file
and 2) the ability to get access to rocketchat server impersonating that user. 
3) potentially have access to any file on RocketChat server

### Environment Information:

- Rocket.Chat Server Version: 3.15.0
- Rocket.Chat App Version: 4.17.0.24389
- Device Name: iPhone 8
- OS Version: 14.6

### Steps to reproduce:

1. Click on file in the channel conversation
2. File will be open
3. Click the Share button at the bottom (one with up arrow) and select Copy
4. Paste somewhere and you have full url to the file with user id and token

### Expected behavior:

users should not be ably to have access to links containing non expiring access tokens
It's either should be temporary access token to required file only
or at least send it in POST request so user won't have access to it.

### Actual behavior:

User can have access to urls like this:

https://<rocketchat_address>/file-upload/<file_id>/<actual_filename>?rc_uid=<user_id>&rc_token=<access_token>

The same thing also possible  for Android mobile app with slightly different manipulations 

### Additional context:

By having userid and token it is possible to get access to any file on the RocketChat server. 
Access to the files is not checked against who can access it. 
If you have fileid (with is always 17 symbols long containing A-Z,a-z,0-9) you can open any file with any userid/token combination.

I've verified such scenario:

user1 sends file to user2 in direct message
user3 (not in that direct message conversation) using his userid and access token able to have access to that file if he knows fileid
by accessing url like this

https://<rocketchat_address>/file-upload/<file_id>/?rc_uid=<user_id>&rc_token=<access_token>

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3210

**Comment by spdreg** [comment]
You really need take security issues more seriously  and address it more quickly with high priority. 
you are making a lot of noise  about how secure rocket chat is.  While the core element of messaging - mobile client have such security flaw.
