### ISSUE TITLE
Not getting a push notification on IOS 

### ISSUE THREAD

**Issue by pritamye77** [RocketChat/Rocket.Chat.ReactNative#3238]
Description:
iOS Rocket Chat native APN for push notifications not working ios app

Environment Information:
Rocket.Chat Server Version: 3.15.1
Rocket.Chat App Version: 4.14.0.1
Device Name: iPhone 11
OS Version: 13.5
Steps to reproduce:
Register APN keys to admin on RocketChat server
Send test push notification
Expected behavior:
Get a push notification on iPhone

Actual behavior:
Not getting a push notification

Additional context:

**Comment by johncrisp** [comment]
Hi,

Github is for actual bugs in the software.

There is insufficient information in your issue to be able to debug anything. You must properly fill out the bug reporting template.

When opening issues please make sure you give a through break down of the steps you have taken eg are you running https correctly, is this the standard gateway, are you building your own app etc etc

You will need to provide some error logs too.

You have question here - I am closing this for now as I suspect this is a support issue - if you provide evidence there is a bug then we can re-open this

https://open.rocket.chat/channel/support?msg=bnh72G8zoCFj3pkXb
