### ISSUE TITLE
Attachment picture from permanent link doesn't show at mobile client

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3239]
### Description:

Attachment picture from permanent link doesn't show at mobile client
Works good on desktop application and web version.

### Environment Information:

- Rocket.Chat Server Version: 3.15.0
- Rocket.Chat App Version: 4.17.0
- Device Name: Xiaomi Mi 9se
- OS Version: Android 10

### Steps to reproduce:

1. Send a message with picture
2. Get permanent link for message with picture
3. Paste permanent link in other chat
4. Mobile client do not show picture

### Expected behavior:

Mobile client should show picture from attachment of permanent link

### Actual behavior:

Web client
![image](https://user-images.githubusercontent.com/4023037/123368843-3a468980-d585-11eb-9314-456cff153ec2.png)

Mobile client
![image](https://user-images.githubusercontent.com/4023037/123368936-67933780-d585-11eb-811e-83e64d317208.png)

**Comment by diegolmello** [comment]
#2853 #2836
