### ISSUE TITLE
Full synchronization of read message status with web client

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3246]
### Description:

Now, when I have unread messages, I have unread indicator on RCRN application icon. But if I read all unread messages on web client, that unread indicator remain on  RCRN application icon, which is wrong in that case.

And optional (I don't know if it doable or not) - if I have unread push notification on smartphone and then I read that message on web client - it would be so good if that unread push notification disappear immediately after message was read on web client. 

### Environment Information:

- Rocket.Chat Server Version: 3.15.0
- Rocket.Chat App Version: 4.17.0
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 10

### Steps to reproduce:

1. Get unread message in web client and mobile client
2. Check if mobile client have unread indicator in it's icon (it should have it)
3. Read that unread message on web client
4. Unread indicator remain on mobile application icon

### Expected behavior:

1. Unread indicator should disappear from RCRN application icon if all messages are read
2. Unread push notification should disappear if that message was read on web client

**Comment by diegolmello** [comment]
> it would be so good if that unread push notification disappear immediately after message was read on web client.

It was possible a few years ago through voip notifications. It's not anymore. Read: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1099#issuecomment-818713858

The other topic is dup of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2343
