### ISSUE TITLE
Whitelabel branch build failed for android

### ISSUE THREAD

**Issue by hkpanchani** [RocketChat/Rocket.Chat.ReactNative#3250]
### Description:

Release Build failed with following error
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'npx.cmd'' finished with non-zero exit value 1

### Environment Information:

- Rocket.Chat Server Version: 3.15.0
- Rocket.Chat App Version: 4.17.0
- Device Name: Oneplus 6t
- OS Version: Android 10

### Steps to reproduce:
./gradlew assembleRelease

### Expected behavior:
Successfully build APK 

### Actual behavior:

Failed with Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'npx.cmd'' finished with non-zero exit value 1

**Comment by hkpanchani** [comment]
Was managed to generate apk with
`gradlew app:assembleRelease -x bundleReleaseJsAndAssets`

but the apk doesnt work on any android.
![image](https://user-images.githubusercontent.com/35301566/124427125-9761ec80-dd88-11eb-9df8-716dc5e23bbe.png)

![image](https://user-images.githubusercontent.com/35301566/124427153-a2b51800-dd88-11eb-9354-86aaab819776.png)

**Comment by hkpanchani** [comment]
Someone please update whitelabel branch and package dependancies for this branch

**Comment by diegolmello** [comment]
Follow the docs https://developer.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#running-the-app-1

**Comment by hkpanchani** [comment]
> 
> 
> Follow the docs https://developer.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#running-the-app-1

Yes I am able to build single-server app.
But I am interested in multi-server app.. As our departments uses different instance of rocketchat server so they can utilise single mobile app for 2 servers.

**Comment by hkpanchani** [comment]
I am also able to build app from whitelabel brach but it does not work with multi server

**Comment by diegolmello** [comment]
We don't have specific docs for your use case.
You can read parts of the docs for whitelabel to learn how to build and configure your app and apply it to `master` branch (so you can have multi server)

**Comment by hkpanchani** [comment]
> .
@diegolmello 
Thank you I was able to build the successful. If the requirement of these use case rise, I can try publishing documentation for this kind of cases on separate branch.

**Comment by Salmankhan033** [comment]
> Follow the docs https://developer.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#running-the-app-1

**Page not found** 
please Provide us with an updated link

**Comment by GleidsonDaniel** [comment]
> > Follow the docs https://developer.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#running-the-app-1
> 
> **Page not found** please Provide us with an updated link

The comment is only one year old lol, that's why the link doesn't work, but if I had searched on the same page in the search box I would have found the link.
https://developer.rocket.chat/mobile-app/mobile-app-white-labelling
