### ISSUE TITLE
when you enter the chat on a notification of a new message - a scroll is triggered and the message is out of sight

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3257]
### Environment Information:

- Rocket.Chat Server Version: 3.15.1
- Rocket.Chat App Version: 4.17.0.24389
- Device Name: Iphone 11 pro max
- OS Version: ios 14.6

### Steps to reproduce:

1. Get notified of a new message
2. enter the application via tap on the notification
3. when entering the chat, a scroll was triggered and a new message was out of sight, to see it you have to scroll the screen with your finger up

### Expected behavior:

3. when I enter the chat, I immediately see a new message

### Actual behavior:

3. when entering the chat, a scroll was triggered and a new message was out of sight, to see it you have to scroll the screen with your finger up

**Comment by diegolmello** [comment]
Might have been fixed by https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3225/files#diff-044c49956355a45706300a80d7956a16854cec536c8981c91c940885c3d7cd63R272
It's going to land on 4.18.0.
Please reopen if you see it.
Thanks.
