### ISSUE TITLE
wrong icon for "unread on top" on the sorting bar

### ISSUE THREAD

**Issue by rocketbughunter** [RocketChat/Rocket.Chat.ReactNative#3259]
### Description:
on the sorting panel the "unread on top" item has an eye icon and there should be a flag icon

### Environment Information:

- Rocket.Chat Server Version: 3.15.1
- Rocket.Chat App Version: 4.17.0.24389
- Device Name:  Iphone 11 pro max
- OS Version: ios 14.6

### Steps to reproduce:

1. open sort panel
2. "unread on top" has an eye icon (screenshot 1)
3. but this is an icon to "hide" (screenshot 2)
4. "unread..." there should be a "flag" (screenshot 3)

### Expected behavior:

2. "unread on top" has an flag icon

### Actual behavior:

2. "unread on top" has an eye icon

**Comment by rocketbughunter** [comment]
![1](https://user-images.githubusercontent.com/82801688/124893619-8e208c00-dfe3-11eb-84b4-a1bf879346f9.jpeg)

**Comment by rocketbughunter** [comment]
![2](https://user-images.githubusercontent.com/82801688/124893669-98db2100-dfe3-11eb-840a-8344baf31663.jpeg)

**Comment by rocketbughunter** [comment]
![3](https://user-images.githubusercontent.com/82801688/124893704-a0022f00-dfe3-11eb-9a79-89aec01b336e.jpeg)

**Comment by diegolmello** [comment]
Nice catch! We're going to redesign some things and I'll make sure to raise this one. Thank you!
