### ISSUE TITLE
No bundle URL present.

### ISSUE THREAD

**Issue by pritamye77** [RocketChat/Rocket.Chat.ReactNative#3262]
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0

IOS Version 4.16.2

**Comment by diegolmello** [comment]
Not enough info. Please follow template.

**Comment by pritamye77** [comment]
Description:
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

Environment Information:
Rocket.Chat Server Version: 3.15.1
Rocket.Chat App Version: 4.16.1
Device Name: Iphone 11 
OS Version: ios 14.6.0



After running the build gives this error
