### ISSUE TITLE
No bundle URL present.

### ISSUE THREAD

**Issue by pritamye77** [RocketChat/Rocket.Chat.ReactNative#3266]
Description:
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

Environment Information:
Rocket.Chat Server Version: 3.15.1
Rocket.Chat App Version: 4.16.1
Device Name: Iphone 11
OS Version: ios 14.6.0

After running the build gives this error
### Steps to reproduce:

After successful build 

Run

Give this error after loading javascript

![Simulator Screen Shot - iPhone 11 - 2021-07-09 at 19 39 05](https://user-images.githubusercontent.com/36439395/125152981-47ab6880-e16e-11eb-8621-0d520e2cb546.png)

**Comment by diegolmello** [comment]
That's a RN issue.
Metro bundler is not open.
