### ISSUE TITLE
 Showing All Messages Application extensions and any libraries they link to must be built with the `APPLICATION_EXTENSION_API_ONLY` build setting set to YES.

### ISSUE THREAD

**Issue by 3990995** [RocketChat/Rocket.Chat.ReactNative#3268]
### Environment Information:

- Rocket.Chat Server Version: 
- Rocket.Chat App Version:develop
- Device Name: simulator
- OS Version: macos big sur

### Steps to reproduce:

1. 
2. 
3.

**Comment by diegolmello** [comment]
We need more info and please follow the template.
