### ISSUE TITLE
Notification preferences menu shows nothing

### ISSUE THREAD

**Issue by xcme** [RocketChat/Rocket.Chat.ReactNative#3274]
Hi,

Not sure if it's a really bug or just wrong settings somewhere, but I can't get access to notification settings on my Android apps. I don't want to use push because of Google and trying to enable App-In notification, but these setting are unavailable.

### Environment Information:

- Rocket.Chat Server Version: 3.16.1, on my own server in docker container
- Rocket.Chat App Version: 4.17.0, from google play
- OS Version:  Android 6, Android 10

### Steps to reproduce:

1. Open **Profile** on android app
2. Open **Preferences** at the right button
3. Open **Notifications**

And I see this:
![image](https://user-images.githubusercontent.com/10675508/125749622-13be1a20-9298-411b-8e7e-ccbeec946c66.png)

And it never stops. But I expect something like this -> #1452 (it has the screenshot)

Thanks for any ideas

**Comment by xcme** [comment]
Hi. No response so far. It supposed to be a simple question, I was thinking...

**Comment by NoxInmortus** [comment]
Same issue here

**Comment by diegolmello** [comment]
Great!
I was able to reproduce it on a fresh account.
I'm going to move this forward so we can work on a fix.
Thanks!
