### ISSUE TITLE
Better message actions

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#329]
https://github.com/beefe/react-native-actionsheet works fine on iOS, but is very ugly and performs poorly on Android.
Maybe switch it by https://github.com/yfuks/react-native-action-sheet.
![image](https://user-images.githubusercontent.com/804994/41488835-1a268444-70c4-11e8-87ac-61626a8157d2.png)

**Comment by saketkumar95** [comment]
@diegolmello How about using https://github.com/expo/react-native-action-sheet this ?

**Comment by diegolmello** [comment]
@saketkumar95 Hey, man. Expo's version uses a JS based implementation on Android and need a wrapper around entire app in order make it work.
I think it's a little weird.

https://github.com/yfuks/react-native-action-sheet is native (iOS/Android) and needs no render component on the tree. Still needs a work to see if works properly, but it sounds a better choice.
What do you think?
Do you want to contribute?

**Comment by diegolmello** [comment]
@saketkumar95 Are you still working on this? It's been 15 days since your last commit and your PR still doesn't pass on lint.

**Comment by reduxsaga** [comment]
i want to work on this.

**Comment by diegolmello** [comment]
@reduxsaga There's an open PR here #567.
It's already approved and it'll be merged soon.
If you still want to help, you can find out what's happening on connect/login: #571 and #581.
