### ISSUE TITLE
最新代码在 XCODE 12（Version 12.5 (12E262)）编译失败

### ISSUE THREAD

**Issue by 3990995** [RocketChat/Rocket.Chat.ReactNative#3296]
### Description:

我 clone 了最新的 develop 分支的代码，执行了yarn && yarn ios 
最后打开 RocketChatRN.xcworkspace 然后执行 CMD+B 就报错了

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version: develop branch
- Device Name: Simulator iPhone11 
- OS Version:  ios14.2

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

我认为可以正常编译

### Actual behavior:

编译错了
UMCore/UMDefines.m
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```objc
- (UIViewController *)currentViewController
{
  id<UMUtilService> utilService = [_moduleRegistry getSingletonModuleForName:@"Util"];

  if (utilService != nil) {
    return [utilService currentViewController];
  }

  UIViewController *controller = [[[UIApplication sharedApplication] keyWindow] rootViewController];
  UIViewController *presentedController = controller.presentedViewController;
  
  while (presentedController && ![presentedController isBeingDismissed]) {
    controller = presentedController;
    presentedController = controller.presentedViewController;
  }
  return controller;
}
```
<img width="2033" alt="截屏2021-07-26 上午10 21 32" src="https://user-images.githubusercontent.com/1081005/126924713-192a1884-8120-4658-a2b6-035dcbbab831.png">
<img width="2033" alt="截屏2021-07-26 上午10 22 53" src="https://user-images.githubusercontent.com/1081005/126924720-3a19f981-05ac-4a61-a463-286537c3f282.png">

**Comment by diegolmello** [comment]
Make sure to pull latest changes, clean and try again.
It should have been fixed by #3245
