### ISSUE TITLE
Bugsnag error when running the project

### ISSUE THREAD

**Issue by lucalves** [RocketChat/Rocket.Chat.ReactNative#3299]
### Description:

I cannot run the project after the `yarn` and `yarn android` command. The error is from project execution.

### Environment Information:

- Device Name: Pixel 3a
- OS Version: Android Emulator with API 30

### Steps to reproduce:

1. Just clone the repository with: `git clone git@github.com:RocketChat/Rocket.Chat.ReactNative.git`.
2. Go to the folder with `cd Rocket.Chat.ReactNative`.
2. Install dependencies with `yarn`.
3. Run `yarn android` command.

### Expected behavior:

I expected the project to run without errors, according to the [CONTRIBUTING](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md) guide.

### Actual behavior:

I'm having the following error:

![rchat-error](https://user-images.githubusercontent.com/17712401/127026354-5a274e04-4574-4390-aba5-0a5b27351bbc.png)

**Comment by diegolmello** [comment]
I'm working on a fix. Thanks.

**Comment by lucalves** [comment]
> I'm working on a fix. Thanks.

Any workarounds I can do to run the app?

**Comment by diegolmello** [comment]
Remove Bugsnag completely.
