### ISSUE TITLE
Content-encoding gzip broken

### ISSUE THREAD

**Issue by malikkirchner** [RocketChat/Rocket.Chat.ReactNative#3306]
### Description:

The client sends Accept-Encoding: gzip, but does not actually work with Content-Encoding: gzip. With gzip enabled, the client cannot connect to the server anymore.

### Environment Information:

- Rocket.Chat Server Version: 3.15.0
- Rocket.Chat App Version: 4.18.0
- Device Name: OnePlus 7 Pro
- OS Version: Android 11

### Steps to reproduce:

1. Setup Rocket.Chat server behind a reverse proxy (e.g. Envoy)
2. Enable gzip response compression in the reverse proxy

### Expected behavior:

Mobile client can handle `Content-Encoding: gzip`

### Actual behavior:

Mobile client **cannot** handle `Content-Encoding: gzip`

### Additional context:

It would be sufficient to remove gzip from the Accept-Encoding request header.

**Comment by diegolmello** [comment]
Can you follow the issue template giving us a proper reproducible example and a detailed stack trace? Thanks!

**Comment by malikkirchner** [comment]
> Can you follow the issue template giving us a proper reproducible example and a detailed stack trace? Thanks!

The mobile Github client does not offer the issue template. I have no public _proper example_ or stack trace.
