### ISSUE TITLE
Error type 3 Error: Activity class {chat.rocket.whitelabel/chat.rocket.reactnative.MainActivity} does not exist.

### ISSUE THREAD

**Issue by khalednailigit** [RocketChat/Rocket.Chat.ReactNative#3315]
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=chat.rocket.whitelabel/chat.rocket.reactnative.MainActivity }
Error type 3
Error: Activity class {chat.rocket.whitelabel/chat.rocket.reactnative.MainActivity} does not exist.

**Comment by diegolmello** [comment]
https://developer.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#running-the-app-1
