### ISSUE TITLE
[bug] Mentions not working for Thread Reply message its showing user name

### ISSUE THREAD

**Issue by shaheem-khanzada** [RocketChat/Rocket.Chat.ReactNative#3317]
![IMG_1653](https://user-images.githubusercontent.com/37620819/128371337-a2673537-0428-45bb-afc7-f212a8692066.jpg)

### Description:

Mentions not working for Thread Reply message its showing user name but we need to show as we show mention for other messages

### Steps to reproduce:

1. Long press on a mention message and select replay.
2. when u send that message u will see like this @furqankhanzada but it shoud show like this Admin or what ever the name is of that user

**Comment by reinaldonetof** [comment]
Thanks for your report, @shaheem-khanzada ! We will evaluate this issue in our next sprint!
