### ISSUE TITLE
How to change android notification small icon? [whitelabeling rocket chat]

### ISSUE THREAD

**Issue by MuhammadAliGabol** [RocketChat/Rocket.Chat.ReactNative#3321]
![image](https://user-images.githubusercontent.com/58255871/128596069-9bd985af-babe-4a46-862d-fbdb92a6688f.png)

### Description:

I want to change this small icon which appears in the notification in android. I have tried but haven't found anything.
Is there any way to change it?
if there is then how can I change this icon?

[NOTE] I am whitelabeling the rocket chat app

### Steps to reproduce:

Just send a notification in your RC App and check in Android Device

**Comment by diegolmello** [comment]
That's `ic_notification` https://developer.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#general-setup-1

**Comment by stydeveloper** [comment]
PLease guide How to change notification icon on android?
