### ISSUE TITLE
Login with SAML sends user in a loop with no error message.

### ISSUE THREAD

**Issue by b90g** [RocketChat/Rocket.Chat.ReactNative#3326]
### Description:
User is entering server URL, clicks connect and nothing happens. This has been tried with WLAN and direct mobile internet connections.
### Environment Information:

- Rocket.Chat Server Version: 3.17.0
- Rocket.Chat App Version: 4.18.0
- Device Name: MI ?
- OS Version: MIUI 12.5 (Android 11)

### Steps to reproduce:

1. enter servername (chatbegruenung.de)

### Expected behavior:

the server is recognized to use SAML SSO and redirects to SAML page 

### Actual behavior:

nothing happends and you can push the connect button over and over. no error message given

### Additional context:

not sure if this is a network issue, an app issue, but the app doesnt really tell me whats happening, maybe be a bit more verbose?

**Comment by reinaldonetof** [comment]
Hi, @b90g! Thanks for your report! I tried to reproduce the error, but I could connect to the server and open the SAML page. Could you try again? I tested with a Redmi Note 9, MIUI 12.0.7, and is connecting properly to the server.

**Comment by b90g** [comment]
user noted it works since yesterday, sorry for the disturbance :)
