### ISSUE TITLE
Biometric lock preference not preserved upon logout

### ISSUE THREAD

**Issue by cprice-kgi** [RocketChat/Rocket.Chat.ReactNative#3331]
### Description:

On the Admin > Security and privacy > Screen lock screen, choosing a biometric lock preference will save for the duration of your session, but when you logout of the app (and select either option for clearing cookies), the preference is cleared and reset to the default value.

### Environment Information:

- Rocket.Chat Server Version: 3.14.0
- Rocket.Chat App Version: 4.17.0
- Device Name: iPhone12 simulator
- OS Version:  

### Steps to reproduce:

1. Go to Admin > Security and privacy > Screen lock
2. Toggle unlock with FaceID or unlock with TouchID ON
3. Come back to the Admin > Security and privacy > Screen lock screen after using the app. Observe the selection is still saved.
4. Logout of the app and pick either option for clearing cookies
5. Return to Admin > Security and privacy > Screen lock and notice it's back to OFF

### Expected behavior:

I would expect this to save, as it seems (to me) to be a user preference as opposed to a server-specific value that gets cleared upon logout. I would expect it to operate more like the Log analytics events and Send crash report options, which do get preserved, because they are stored in Async Storage.

### Actual behavior:

Value is not preserved upon logout

**Comment by cprice-kgi** [comment]
Happy to work on this and convert to an Async Storage property; however, I wanted to get confirmation that it, in fact, should be operating as a user preference, and that the current behavior is not the intended one.

**Comment by gerzonc** [comment]
Fixed on #3331

**Comment by cprice-kgi** [comment]
great, thank you!
