### ISSUE TITLE
[New] Implement webrtc with (callkit and connection service)

### ISSUE THREAD

**Issue by shaheem-khanzada** [RocketChat/Rocket.Chat.ReactNative#3334]
Hy guys I want to contribute to the implementation of webrtc with a call kit instead of JITSI I just need some help with sockets so can I also use @rocketchat/emitter lib in mobile if yes then just give me some guide so I can start and make Complete Calling app like WhatsApp

**Comment by diegolmello** [comment]
Hey, @shaheem-khanzada.
That would be amazing, but what about Android?
Also, I wonder how it would behave on the web.

**Comment by shaheem-khanzada** [comment]
@diegolmello I will try to use the same functionality as we have on the web and it will work on android and ios and also on web if web users enabled a webrtc service, and for showing call screen in ios we will use callkit and in android, we will use connectionService

**Comment by shaheem-khanzada** [comment]
@diegolmello just guide me how can i send and receive events in mobile and i will handle rest

**Comment by diegolmello** [comment]
Great.
There's not many events.
We just generate a URL and call Jitsi with it.
This is where we generate the URL https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/callJitsi.js#L38
Everything else is handled by Jitsi.

**Comment by shaheem-khanzada** [comment]
@diegolmello check this https://github.com/RocketChat/Rocket.Chat/blob/157b882d38b34b7b79dea527316554fe33f70891/app/webrtc/client/WebRTCClass.js

check `class WebRTCTransportClass extends Emitter` this class we have all the methods i want that in mobile 

and jitsi is diffrent and in webrtc we handle all things

**Comment by diegolmello** [comment]
I don't know how that would behave on mobile or if we need it at all.
Can you do a proper research on what to do?

**Comment by shaheem-khanzada** [comment]
@diegolmello I did my research I need the events to send data like (SDP, candidate, answer) because webrtc is peer to peer but in order to start  call we need a signaling server like sockets and on Rocket chat web I found this class with all the methods implemented just ready to use, but my question is how we can use them and in for that, I need your help

**Comment by shaheem-khanzada** [comment]
@diegolmello and in order to use webrtc like web to mobile or mobile to the web we need to use same methods with same data struct

**Comment by diegolmello** [comment]
You should check how Jitsi handles it https://github.com/jitsi/jitsi-meet

**Comment by shaheem-khanzada** [comment]
@diegolmello jitsi also use a signaling server behind the scene and that's why we have limited options

Rocket web got the webrtc we just need to use the same things in mobile 
Example of some methods in web version

    `sendCandidate(data) {
		data.from = this.webrtcInstance.selfId;
		data.room = this.webrtcInstance.room;
		this.log('WebRTCTransportClass - sendCandidate', data);
		Notifications.notifyUser(data.to, WEB_RTC_EVENTS.WEB_RTC, WEB_RTC_EVENTS.CANDIDATE, data);
	}

	sendDescription(data) {
		data.from = this.webrtcInstance.selfId;
		data.room = this.webrtcInstance.room;
		this.log('WebRTCTransportClass - sendDescription', data);
		Notifications.notifyUser(data.to, WEB_RTC_EVENTS.WEB_RTC, WEB_RTC_EVENTS.DESCRIPTION, data);
	}

	sendStatus(data) {
		this.log('WebRTCTransportClass - sendStatus', data, this.webrtcInstance.room);
		data.from = this.webrtcInstance.selfId;
		Notifications.notifyRoom(this.webrtcInstance.room, WEB_RTC_EVENTS.WEB_RTC, WEB_RTC_EVENTS.STATUS, data);
	}
`

**Comment by diegolmello** [comment]
This is on VideoConf' squad backlog
