### ISSUE TITLE
Application extensions and any libraries they link to must be built with the `APPLICATION_EXTENSION_API_ONLY` build setting set to YES. (in target 'ShareRocketChatRN' from project 'RocketChatRN')

### ISSUE THREAD

**Issue by khalednailigit** [RocketChat/Rocket.Chat.ReactNative#3339]
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RocketChatRN.xcworkspace -configuration Debug -scheme RocketChatRN -destination id=0367AC53-C7C4-4DED-9A69-5EBED357BF3E

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
error: Application extensions and any libraries they link to must be built with the `APPLICATION_EXTENSION_API_ONLY` build setting set to YES. (in target 'ShareRocketChatRN' from project 'RocketChatRN')
warning: no rule to process file '/Users/macbookpro/Desktop/prod/Rocket.Chat.ReactNative/node_modules/react-native-config-reader/ios/RNConfigReader.xcworkspace/contents.xcworkspacedata' of type 'text' for architecture 'x86_64' (in target 'RNConfigReader' from project 'Pods')
warning: no rule to process file '/Users/macbookpro/Desktop/prod/Rocket.Chat.ReactNative/node_modules/react-native-config-reader/ios/RNConfigReader.xcodeproj/project.pbxproj' of type 'text.pbxproject' for architecture 'x86_64' (in target 'RNConfigReader' from project 'Pods')
/Users/macbookpro/Desktop/prod/Rocket.Chat.ReactNative/ios/RocketChatRN.xcodeproj: warning: GLKit is deprecated. Consider migrating to MetalKit instead. (in target 'RocketChatRN' from project 'RocketChatRN')

**Comment by joaohenrifranco** [comment]
I solved the same problem opening Xcode project settings and changing the `Require Only App-Extension-Safe API` option to `Yes`

<img width="645" alt="Captura de Tela 2021-09-27 às 16 34 07" src="https://user-images.githubusercontent.com/14077663/134973276-27d94d3e-0112-4b93-b581-41c65c693749.png">
