### ISSUE TITLE
error Failed to build iOS project when whitelabeling mobile apps

### ISSUE THREAD

**Issue by khalednailigit** [RocketChat/Rocket.Chat.ReactNative#3347]
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RocketChatRN.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace RocketChatRN.xcworkspace -configuration Debug -scheme RocketChatRN -destination id=0367AC53-C7C4-4DED-9A69-5EBED357BF3E

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete

**Comment by bigfudge99** [comment]
try to build the app with xCode. there you can get specific logs of the issue. also try with xCode 12.4, newer version doesn't work.

**Comment by diegolmello** [comment]
We released 4.19.0 yesterday https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/4.19.0
Make sure you update your branch and follow whitelabel docs https://developer.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps
