### ISSUE TITLE
fabric-ios and/or fabric-android problem

### ISSUE THREAD

**Issue by irepan** [RocketChat/Rocket.Chat.ReactNative#335]
Hi, 

I have cloned the most recent Rocket.Chat.ReactNative version, at the Develop branch, honestly I need a little more documentation on it, but anyway, following the steps at the README.md, there is a step:

> Configuration
> 
>  $ npm run fabric-ios --key="YOUR_API_KEY" --secret="YOUR_API_SECRET"
>  $ npm run fabric-android --key="YOUR_API_KEY" --secret="YOUR_API_SECRET"
> 

As a I am unable to find further documentation, I figured out the key and secret are gotten from fabric.io but not sure about that, anyway, when I try those commands I get:

```
MacBook-Pro-de-Irepan:Rocket.Chat.ReactNative irepan$ npm run fabric-ios --key="xxxxxxxxxxxxxxxxxxxxxxxxx" --secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

> rocket-chat-reactnative@0.0.1 fabric-ios /Users/irepan/Documents/Workspaces/Nivel-7/Rocket.Chat.ReactNative
> ./scripts/fabric-ios.sh

Usage: yarn fabric-ios --key="YOUR_API_KEY" --secret="YOUR_API_SECRET"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rocket-chat-reactnative@0.0.1 fabric-ios: `./scripts/fabric-ios.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rocket-chat-reactnative@0.0.1 fabric-ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/irepan/.npm/_logs/2018-06-21T19_12_29_834Z-debug.log

```

Do somebody have a suggestion on this?

**Note:** I have substituted the actual key and secret to x.

**Comment by diegolmello** [comment]
Hi, @irepan.
This script was developed when we were using yarn and still works using yarn.
I'll fix it soon to work with npm as well.
Until then you can read what those scripts do.

At iOS, we are editing `Info.plist` and creating a file `Fabric.sh`.

```
/usr/libexec/PlistBuddy -c "Set Fabric:APIKey ${key}" ./ios/RocketChatRN/Info.plist
echo "./Fabric.framework/run ${key} ${secret}" > ./ios/RocketChatRN/Fabric.sh
```

Try running these comands or changing the files manually.
Let me know if everything works.

**Comment by irepan** [comment]
Thank you,

anyway, I installed yarn, and trying the solution, so the big question here would be, am I ok with the key and secret from fabric.io?

**Comment by diegolmello** [comment]
Yes, you only need to create your own Fabric.io account and grab your keys.
It's pretty easy.
