### ISSUE TITLE
Create team, members not added at creation

### ISSUE THREAD

**Issue by fidelsam1992** [RocketChat/Rocket.Chat.ReactNative#3353]
### Description:

At team creation, the selected members are not added to the team.
### Environment Information:

- Rocket.Chat Server Version: 3.14.0
- Rocket.Chat App Version: single_server
- Device Name: iOS - Android

### Steps to reproduce:

1. Create team
2. Select Members
3. Choose name
4. Click Create
5. Team is created but selected members are not added to the new team

### Expected behavior:

Expect to add the selected members at creation

### Actual behavior:

Members are not added to the team

### Additional context:

I noticed on `rocketchat.js` that the params passed to the `createTeam` function are not correct

Original params

```
const params = {
			name,
		        users,
			type: type ? TEAM_TYPE.PRIVATE : TEAM_TYPE.PUBLIC,
			room: {
				readOnly,
				extraData: {
					broadcast,
					encrypted
				}
			}
		};
```

Fixed params

```
const params = {
			name,
			members: users,
			type: type ? TEAM_TYPE.PRIVATE : TEAM_TYPE.PUBLIC,
			room: {
				readOnly,
				extraData: {
					broadcast,
					encrypted
				}
			}
		};
```

But this still didn't fix the issue of the members

**Comment by diegolmello** [comment]
@fidelsam1992 can you try that on an up-to-date server?
That's probably fixed already.
Thank you.
