### ISSUE TITLE
[Regression] Image uploads are pixelated and low quality when opened

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#3364]
### Description:

https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2975 broke images from displaying in their full quality when they are opened up.

### Environment Information:

- Rocket.Chat Server Version: 3.18.0
- Rocket.Chat App Version: 4.19.0
- Device Name: Note 10+ 5G
- OS Version: Android

### Steps to reproduce:

1. Take a screenshot on your phone
2. Upload the screenshot as an attachment
3. Tap the uploaded image

### Expected behavior:

High-quality screenshot

![image](https://user-images.githubusercontent.com/6295044/131784944-29d2f435-5147-40d5-866d-3ce9032a37e1.png)

### Actual behavior:

![225-2250225_rocket-chat-logo-black-and-white-rocket-chat-logo-png](https://user-images.githubusercontent.com/6295044/131785388-0ec0cdff-3846-4afc-b7d4-9253b92c1718.jpg)

Pixelated image. Can't read text.

**Comment by jacotec** [comment]
Confirmed for IOS also. Screenshots are unusable. Happens also with 4.17.
It's not an upload issue as the quality using the web client (also on the same device) is perfect.

**Comment by diegolmello** [comment]
Just saw Github mobile app didn't send my comment. I'm sorry about that.
That's an important performance improvement made on the server, but we couldn't land on the same mobile version.
We're working on that as we speak.
