### ISSUE TITLE
Rocket.chat app: can't access server instance on android 10 go

### ISSUE THREAD

**Issue by Benvorth** [RocketChat/Rocket.Chat.ReactNative#3368]
### Description:

Rocket.Chat App terminates after startup. 

Login to my server instance seems to load for some milisecs (was able to configure that after download from Play Store). 

### Environment Information:

- Rocket.Chat Server Version: 3.18.0
- Rocket.Chat App Version: 4.19.0
- Device Name: Hafury M20
- OS Version: Android 10 Go

### Steps to reproduce:

1. Download Rocket Chat App in Play Store
2. Run it and configure access to your server
3. Provide Username + Password and "login"
4. App terminates from now on, same on reboot

### Expected behavior:

Successful login to chat-screen like on other devices

### Actual behavior:

App terminates without further info

### Additional context:

Hafury M20 had 1 GB free ram and around 10 GB free storage left by the time I faced the error.

**Comment by diegolmello** [comment]
Thanks for opening, @Benvorth.
Can you try logging in on https://open.rocket.chat?

**Comment by Benvorth** [comment]
Yes, I am on...

**Comment by diegolmello** [comment]
@Benvorth Ok, maybe it's something on your server then.
Can you send me a test account on https://open.rocket.chat/direct/diego.mello?

**Comment by Benvorth** [comment]
Ah, sorry, I didn't get it... No, I cannot connect to https://open.rocket.chat with the Android 10 Go phone. Same as with my server: app terminates after login

**Comment by diegolmello** [comment]
@Benvorth Can you send us a bug report? https://developer.android.com/studio/debug/bug-report#bugreportdevice
You can DM me with the file.
We'll take a look at it asap.
Thank you.
