### ISSUE TITLE
Oauth login failure via ChromeOS Playstore app

### ISSUE THREAD

**Issue by leeIco3** [RocketChat/Rocket.Chat.ReactNative#3376]
### Description:
When trying to login to to self hosted or open workspace clicking the oauth google login generates the codes and opens in chrome and the request is returned to the app but the app then does nothing with the response, therefore failing to login.

Only seems to happen under Chrome OS using the mobile client via the playstore, have tried beta client and experimental with no success.

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:4.19.0.25555
- Device Name: 
- OS Version: ChromeOS 93.0.4577.69

### Steps to reproduce:

1. Click join a workspace
2. enter workspace to join or open workspace
3. click login
4. click continue with google 
5. browser opens and returns to app
6. app remains unchanged with "continue with google" option

### Expected behavior:

Expect for callback to be handled/received and generate login and proceed.

### Actual behavior:

App remains in unauthed state and leaves the button with continue with google inplace (still active and clickable)

### Additional context:

I assume the way the oauth is implemented needs to change to handle how chromeos is doing playstore apps now ? Ive tried on multiple chromeOS machines so its not specific to me and even the open workspace setup doesnt work with google login which removes the issue in our selfhosted version.

**Comment by MaxWaldorf** [comment]
I confirm the same issue on android and IOS with custom OAuth...

https://forums.rocket.chat/t/rocket-chat-4-0-android-mobile-app-4-20-0-26005/12329
