### ISSUE TITLE
Bugsnag error while running the project

### ISSUE THREAD

**Issue by rajoriaakash** [RocketChat/Rocket.Chat.ReactNative#3389]
### Description:

Can not run the project after following CONTRIBUTING.md, shows a problem with ':bugsnag_react-native'. 

### Steps to reproduce:

1. Clone repository by `git clone git@github.com:RocketChat/Rocket.Chat.ReactNative.git` .
2. Move to subfolder by `cd Rocket.Chat.ReactNative` .
3. Install dependencies with `yarn`.
4.Run `yarn android` command.

### Expected behavior:

The app should get running without any error according to Contribution guide.

### Actual behavior:

I am having the following error regarding bugsnag : 

![bugsnag_error](https://user-images.githubusercontent.com/59030114/133932668-8920562b-34bd-4172-9d92-76e81f271921.JPG)

**Comment by ankar84** [comment]
@rajoriaakash hello!
What was a fix for your problrm?

**Comment by rajoriaakash** [comment]
> @rajoriaakash hello!
> What was a fix for your problem?

It was some problem with my network so I tried to download it again whenever I encountered an error and all the files finally downloaded after 5-6 times :).
