### ISSUE TITLE
Bugsnag api key is required in info.plist?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#3398]
Hi!

I try build custom Rocket.Chat app with push notifications.
I cant build without bugsnag api. This is required?
Can i build without this? I dont need Bugsnag

**Comment by diegolmello** [comment]
Hey.
Yes, it's needed and you can follow instructions on our documentation https://developer.rocket.chat/mobile-app/mobile-app-white-labelling
If you want to build without it, you need to remove the lib yourself.

**Comment by arpsyapathy** [comment]
@diegolmello 
Hi Diego!
Can you tell me which library to remove and how to do it please?

**Comment by arpsyapathy** [comment]
@diegolmello 
Diego, can you help in this question?
We need remove bugsnag from our whitelabel please.
How to do it?

Thank you advance

**Comment by emikolajczak** [comment]
Hi,
If you want remove bugsnag from your project on booth RocketChatRN and Rocket.Chat targets you have to:
1. Go to "Build phases" tab
2. Remove task for Bugsnag build (last on list)

**Comment by emikolajczak** [comment]
I have prepared fix for this bug
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3421

**Comment by DevAhmedRagab** [comment]
You should remove these from your project:
`@bugsnag/react-native`
`@bugsnag/source-maps`
and remove the imports from the code.
