### ISSUE TITLE
Emojis go crazy hehehehe

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#3401]
Emojis overlap each other very abnormally.

 I noticed this error from some versions back both in the production app and in the experimental one, only now it is displayed more frequently

 Device: Xiaomi Redmi Note 6 Pro
 App Version: 4.20.0.25939 Experimental
 RC version: 3.18.1

![IMG_20210923_234845.jpg](https://user-images.githubusercontent.com/35962168/134617751-7d10b0bb-5514-4d89-9686-d7a074a8a550.jpg)

**Comment by ankar84** [comment]
Just checked 4.20 experimental app and I don't see such problem on my side.
Try to clean cache maybe?

I see, that in a recent versions Emoji picker now have a bigger area (like on your screenshot). Before it was about 1/3 of chat height, now it's about 1/2 of chats height.

**Comment by diegolmello** [comment]
We haven't touch emojis for a while now.
It might be related to keyboard or OS really.
How can we reproduce it?

**Comment by aleadco** [comment]
Hola @diegolmello and @ankar84 

It is really difficult to reproduce this scenario, I have not been able to define a pattern that causes this behavior.  If I can assure you that it has happened to me on at least two different devices.  Samsung Galaxy S7 Edge with Android 8.0 and the Xiaomi Redmi Note 6 Pro.

 The most I can give you at this time is a small video where you can see some jumps that at times are seen when you slide the emoji selector.  This behavior is sometimes very violent and it tends to distort all the emojis inserted at the time you are writing the message.

https://user-images.githubusercontent.com/35962168/134736142-41bdf5b6-52c2-4776-8f79-927a4a6f4b65.mp4
