### ISSUE TITLE
Built .ipa installed but does not start on iOS 15. App needs update

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#3408]
Hi all!

i built my .ip from the documentation
Installed, but it does not start on iOS 15.

Error: "App needs update"

How fix this?

### Environment Information:

- Rocket.Chat Server Version: 3.16.1
- Rocket.Chat App Version: 4.19.0
- Device Name: iPhone 
- OS Version: iOs 15
- XCode: 13

### Steps to reproduce:

1. Install app from ipa (enterprise)
2. Try to run

**Comment by ankar84** [comment]
We had the same issue.
We fixed it by updating developer machine to Bug Sur and XCode to 13 version.

**Comment by arpsyapathy** [comment]
This dont resolve my problem :(

 @diegolmello
