### ISSUE TITLE
Switch push notification lib

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#342]
Our current push notification lib seems to be abandoned.
This can be seen at [#716](https://github.com/zo0r/react-native-push-notification/issues/716), [#575](https://github.com/zo0r/react-native-push-notification/issues/575) and [#727](https://github.com/zo0r/react-native-push-notification/issues/727).

[Wix's react-native-notifications](https://github.com/wix/react-native-notifications) seems to be the best alternative.

**Comment by mnlbox** [comment]
@diegolmello, @ggazzo I think [Onesignal](https://github.com/geektimecoil/react-native-onesignal/) also seems good alternative.
