### ISSUE TITLE
Mobile app crashes creating channels or teams if permission is revoked for the user

### ISSUE THREAD

**Issue by jsalatiel** [RocketChat/Rocket.Chat.ReactNative#3429]
### Description:
on our servers , only admins can create channels and teams. On web app and electron app, normal users ( not admin ) can only see "Direct Messages" and "Discussions" when tapping:
![image](https://user-images.githubusercontent.com/5522389/136246210-19f87a7d-5a91-4171-bd41-887c47e716ff.png)

Unfortunately, on mobile versions, they can see all options, and if they try to create a channel ou a team, the mobile app will crash.

![image](https://user-images.githubusercontent.com/5522389/136246572-8592c2c7-5bba-4aed-8ebf-5af25f1d74c1.png)

### Environment Information:

- Rocket.Chat Server Version: 3.18.2
- Rocket.Chat App Version: 4.19.0.25557
- Device Name:  iPhone
- OS Version:  Latest

### Steps to reproduce:

1. Leave create channel and create teams available only for admins
2. On the mobile client, tap this icon:
![image](https://user-images.githubusercontent.com/5522389/136246707-5a44dfad-42be-4bc5-9924-6f44d6afeae9.png)
3. Create channel and create teams will still be available and will lead to a crash if the user try to create.

### Expected behavior:

Those options should be hidden the same way they are on electron and web versions

### Actual behavior:

The options are shown and lead to a crash

### Additional context:

Also happens on android. ( 4.20 app version)
btw, missing PT-BR translation for "Create Teams"

**Comment by diegolmello** [comment]
Fixed on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3233
It'll be released on 4.21.0 late October.
