### ISSUE TITLE
how to generate debug apk without use development server

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.ReactNative#3435]
how to generate debug apk without use development server. unable to generate apk. can anyone help me out

**Comment by diegolmello** [comment]
You can follow the documentation here for whitelabel https://developer.rocket.chat/mobile-app/mobile-app-white-labelling
Or this documentation to run `develop` branch https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md#setting-up-a-development-environment
