### ISSUE TITLE
Whitelabel Doc Missing Logo Reference (Single Server Branch Specific)

### ISSUE THREAD

**Issue by GSLKim** [RocketChat/Rocket.Chat.ReactNative#3436]
### Description:

Whitelabel guide in the images section is missing a reference to update /app/static/images/logo.png

This is the logo used during the "loader" screen when conversations are being loaded from push notifications after the app loads but before the conversation loads.

### Environment Information:

- Rocket.Chat Server Version: All
- Rocket.Chat App Version: 4.20
- Device Name: Android
- OS Version: Android

### Steps to reproduce:

Get a notification, click it, see the icon.

### Expected behavior:

Should be added to the whitelabel guide so that the default logo can be adjusted to individual server branding.

### Actual behavior:

Whitelabel guide missed that asset.

**Comment by entrymaster** [comment]
Can I start my contributions journey with this?
