### ISSUE TITLE
Images in Attachment-Fields aren't shown

### ISSUE THREAD

**Issue by NecatiMeral** [RocketChat/Rocket.Chat.ReactNative#3461]
### Description:

When embedding a image to an attachments field, it won't get shown on the mobile app (iOS & Android).

### Environment Information:

- Rocket.Chat Server Version: 4.0.1
- Rocket.Chat App Version: 4.20.0.26006
- Device Name: iPhone 12 Pro
- OS Version: 15.0.2

### Steps to reproduce:

1. Use the API to post the following message:
```json
{
  "channel": "@YOUR_USERNAME",
  "color": "#22BB33",
  "text": "Pull request updated",
    "attachments": [
      {
        "title": "John Doe updated his Pull request",
        "title_link": "https://github.com/RocketChat/Rocket.Chat.ReactNative",
        "color": "#ff0000",
        "collapsed": false,
        "fields": [
          {
            "short": true,
            "title": "Status",
            "value": "![completed](https://shields.io/badge/-completed-22BB33)"
          },
          {
            "short": true,
            "title": "Owner",
            "value": "![John Doe](https://shields.io/badge/-John%20Doe-gray)"
          },
          {
            "short": true,
            "title": "Repository",
            "value": "![Framework](https://shields.io/badge/-Framework-gray)"
          },
          {
            "short": true,
            "title": "Created-On",
            "value": "![10/26/2021, 5:45:41 AM](https://shields.io/badge/-10/26/2021,%205:45:41%20AM-gray)"
          },
          {
            "short": false,
            "title": "Reviewers",
            "value": "![Someone](https://shields.io/badge/Someone-approved%20with%20suggestions-F0AD4E) ![]()"
          }
        ]
      }
    ]
  }

```

### Expected behavior:

I've expected to see the badges as in the browser or desktop app.
![image](https://user-images.githubusercontent.com/7882753/138827452-dfa4cad4-cb33-43eb-b0c1-5cb1cdfd3ff0.png)

### Actual behavior:

![image](https://user-images.githubusercontent.com/7882753/138827681-7ae26a4d-89e0-42e5-bf72-830098046d3c.png)

**Comment by entrymaster** [comment]
is this issue still persists? I would love to work on it !

**Comment by NecatiMeral** [comment]
Hi @entrymaster,

the issue still persists. 😄

**Comment by entrymaster** [comment]
Can u please be a little more detailed on how to clone this issue?

**Comment by NecatiMeral** [comment]
Hi, just create a server and post a message by using my posted payload. You have to adjust your username in the payload. Afterwards, use your mobile app to connect to your server.
You'll observe the broken rendering now.

**Comment by entrymaster** [comment]
I'm following [this](https://developer.rocket.chat/rocket.chat/rocket.chat-server/windows-10) to create a server. Can u guide me if i'm right !

**Comment by NecatiMeral** [comment]
I would recommend using the [docker compose](https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers/docker-compose) way of setting up a throwaway-server.

**Comment by entrymaster** [comment]
I successfully created server on localhost. But I wasn't able to add the server on app on emulator.

**Comment by entrymaster** [comment]
Can you assign this issue to me?

**Comment by NecatiMeral** [comment]
I cannot change the assignments. A Rocket.Chat maintainer has to do this.
