### ISSUE TITLE
groups.history or groups.messages, which is better?

### ISSUE THREAD

**Issue by ameer-taghavi** [RocketChat/Rocket.Chat.ReactNative#3479]
Why for fetching groups messages in app, `groups.history` api  was used?
in `groups.messages` api we have `total` &... for better pagination
what is different and which is better?

**Comment by diegolmello** [comment]
Hey, @ameer-taghavi!
`groups.history` is safer to use since it validates permissions and has some other business logics.
We've been thinking on deprecating a few apis and `groups.messages` might be one of them.
