### ISSUE TITLE
Empty screen using single server

### ISSUE THREAD

**Issue by YousefAlsbaihi** [RocketChat/Rocket.Chat.ReactNative#3484]
This was the same issue here [#3302](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3302)
but i still have the same issue

Description:
I did all steps of white-labeling from your website but it displays a blank screen with a header.

Environment Information:
Rocket.Chat App Version: 4.21.0.1
Device Name: iPhone 13
OS Version: 15.0
Steps to reproduce:
1.Just clone the repository with git clone git@github.com:RocketChat/Rocket.Chat.ReactNative.git.
2.Go to the folder with cd Rocket.Chat.ReactNative.
3.complete the steps of the
https://developer.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps

Expected behavior:
I expected the project to display a login screen to my server

Actual behavior:
![simulator_screenshot_E9BFA1C2-E8B7-4A34-91CC-690ACE12DC76](https://user-images.githubusercontent.com/19701357/140635917-e7a04688-22e4-49f6-acb8-272d85c547f5.png)

**Comment by artemChernitsov** [comment]
I have the same issue
