### ISSUE TITLE
RocketChat app crashes when connecting to server

### ISSUE THREAD

**Issue by pavii** [RocketChat/Rocket.Chat.ReactNative#3506]
### Description:

When trying to connect to my server using the RC mobile app the app crashes. I can connect to the server from the browser

### Environment Information:

- Rocket.Chat Server Version: 4.0.3
- Rocket.Chat App Version: 4.21.0.26581
- Device Name: Samsung S9, SM-G960F
- OS Version: Android 10

### Steps to reproduce:

1. Open App
2. Apply certificate
2. write server's URL
3. Click connect

### Expected behavior:

The login window should appear

### Actual behavior:

App crashes and force closes

### Further info

the server I am connecting to needs a certificate. So this happens when I apply client certificate (RSA 2048, custom CA)

the app works fine for Android 9

the app also crashes  Android 11

**Comment by diegolmello** [comment]
Hey, @pavii.
Can you give us more details on the error?
If it's ok to you, send me test credentials on https://open.rocket.chat/direct/diego.mello
Thanks!

**Comment by pavii** [comment]
Hi @diegolmello 
thank you for reply. At this point, it is difficult to provide you with test credentials. Is there any other way I can provide you additional info?

I downgraded RC app to 4.17.0.24391 and it works fine.

**Comment by diegolmello** [comment]
The other way would be you create a test server for us.
We don't have an easy way to test your use case right now, so it might take some time for us to be able to help you.
We'd appreciate if you help us on this.

**Comment by pavii** [comment]
Unfortunately, due to nature of my work environment and security concerns I am unable to provide you with test credentials :/

We might be able to provide a test server in the future, but currently we're extremely busy.

My current solution to this problem is using app 4.17
