### ISSUE TITLE
Splash scree n

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.ReactNative#353]
when the app running 
it build successful 
the splash screen show only and the app dont show any thing after this splash screen

**Comment by diegolmello** [comment]
Hi @mahmodsallam.
Did the bundle finished running on terminal?
What about your environment?

**Comment by superseby2** [comment]
@diegolmello I have actually the same issue. 
Using branch develop, build seems to finish successfully. App is deployed into emulator. 

In the logs, 
07-21 23:08:06.118  7662  7662 D ReactNative: ReactInstanceManager.ctor()
07-21 23:08:06.188  7662  7662 D ReactNative: ReactInstanceManager.createReactContextInBackground()
07-21 23:08:06.188  7662  7662 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
07-21 23:08:06.588  7662  7662 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
07-21 23:08:06.588  7662  7662 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
07-21 23:08:06.588  7662  7662 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
07-21 23:08:06.668  7662  7702 D ReactNative: ReactInstanceManager.createReactContext()
07-21 23:08:06.785  7662  7702 D ReactNative: Initializing React Xplat Bridge.
07-21 23:08:06.786  7662  7702 D ReactNative: Initializing React Xplat Bridge before initializeBridge
07-21 23:08:06.804  7662  7702 D ReactNative: Initializing React Xplat Bridge after initializeBridge
07-21 23:08:06.804  7662  7702 D ReactNative: CatalystInstanceImpl.runJSBundle()
07-21 23:08:06.805  7662  7707 D ReactNative: ReactInstanceManager.setupReactContext()
07-21 23:08:06.805  7662  7707 D ReactNative: CatalystInstanceImpl.initialize()

While the app displays the splashscrren and nothing else. No interaction available also.

Emulator side, I have tried with different Android SDK, with no chance.


 react-native info
Scanning folders for symlinks in /home/ubuntu/AndroidStudioProjects/Rocket.Chat.ReactNative/node_modules (17ms)

  React Native Environment Info:
    System:
      OS: Linux 4.9 Ubuntu 16.04 LTS (Xenial Xerus)
      CPU: x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      Memory: 206.26 MB / 7.48 GB
      Shell: Unknown - /bin/sh
    Binaries:
      Node: 10.7.0 - /usr/bin/node
      npm: 6.1.0 - /usr/bin/npm
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.1, 26.0.3, 27.0.3, 28.0.1
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4720617
    npmPackages:
      @storybook/react-native: ^3.4.8 => 3.4.8 
      react: ^16.4.1 => 16.4.1 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Thanx for any help !

**Comment by diegolmello** [comment]
@superseby2 Can you make sure Metro bundler is running? If not, you can run it manually with `npm start`.
