### ISSUE TITLE
[bug] Read messages marked as unread

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3539]
### Description:

That issue could be chat-engine problem, but not a mobile application problem. But it is really easy reproducible on mobile, so I make that issue here, on mobile repo. But if it appear to be chat-engine problem, that issue should be transferred to main repo.

### Environment Information:

- Rocket.Chat Server Version: 3.18.3
- Rocket.Chat App Version: 4.22
- Device Name: Samsung S8
- OS Version: Android 9

### Steps to reproduce:

1. Open mobile client of UserA and open DM chat on UserA and UserB
2. Turn ON airplane mode on smartphone
3. Send messages to UserA from UserB account (in same DM chat)
4. Turn OFF airplane mode on smartphone
5. Messages appears in chat, and all of them **not marked as unread** (which is right, because UserA read them - chat is opened on a screen)
6. Tap back to chat list view
7. That chat highlighted with unread messages with number of received amount of messages (that's wrong IMHO, because messages already read, when chat was open at step 5)
8. Tap that UserA and UserB DM chat
9. Messages marked unread in a second (red line). Again that's wrong! UserA already read that messages at step 5.

### Expected behavior:

Messages marked read when they appears in open chat, or Messages marked read when user close that open chat with received messages

### Actual behavior:

![0f580462a8822f2222ff31988ad643b04bf1099fa67c1efd0674cda837c19b68](https://user-images.githubusercontent.com/4023037/144547919-11eadbfc-8650-4f41-b6f5-deb598bb885a.gif)

**Comment by utkarshsinghinc** [comment]
I want to work this issues

**Comment by debdutdeb** [comment]
@ankar84 is this happening on the latest release as well?

**Comment by ankar84** [comment]
> @ankar84 is this happening on the latest release as well?

Yes, issue is still here on 4.25.0.29287 mobile version and 4.3.3 server version

**Comment by diegolmello** [comment]
It's planned to be fixed this sprint
