### ISSUE TITLE
since nov 22 update the +/voice record buttons sometimes don't change into a 'send' button

### ISSUE THREAD

**Issue by 0spinboson** [RocketChat/Rocket.Chat.ReactNative#3540]
### Description:

since nov 22 update the +/voice record buttons sometimes don't change into a 'send' button, at which point I can't send the text I typed. Killing and restarting the app tends to work, but often doesn't the first time, so high chance of failure. I know of 1 other user who has this issue as well.

### Environment Information:

- Rocket.Chat Server Version:
3.18.3, node v12.22.1
- Rocket.Chat App Version:
nov 22 2021 version
- Device Name: 
Poco x3 nfc
- OS Version: 
Android 11

### Steps to reproduce:

1. start app, enter text in any channel
2. try to hit 'send'
3. button absent

### Expected behavior:
+ & record button to change to 'send'

### Actual behavior:

This doesn't happen.

**Comment by AndreySemenov1** [comment]
The same issue on iOS.

The workaround is "clear chat", but I would like to do without it.

**Comment by AndreySemenov1** [comment]
Another workaround: enable message parser / join to chat , disable message parser.
