### ISSUE TITLE
Send a message end with symbol ~ cause app stuck 

### ISSUE THREAD

**Issue by LIM-SH** [RocketChat/Rocket.Chat.ReactNative#3542]
### Description:
In any kind of room, write a message that end with a symbol **~** and then press send will cause the mobile app (**single server branch**) stuck and no response.

### Environment Information:

- Rocket.Chat Server Version: 4.2
- Rocket.Chat App Version: 4.22.0 (**single server**)
- Device Name: OnePlus 7T
- OS Version: Android 11

### Steps to reproduce:

1.  Go to any room
2.  Write any message end with a symbol ~
3.  Press send

### Expected behavior:
Message will send and display on screen successfully.

### Actual behavior:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26838416/144751750-e72bc747-ba2e-4bf0-a459-c5aa6e8c6045.gif)

**Comment by ankar84** [comment]
Not reproduce on 4.19 and 4.22 versions of RC.RN application on 3.18.3 server.
And on open.rocket.chat (which is on 4.2 version) and with 4.22 client could not reproduce.

**Comment by LIM-SH** [comment]
> Not reproduce on 4.19 and 4.22 versions of RC.RN application on 3.18.3 server. And on open.rocket.chat (which is on 4.2 version) and with 4.22 client could not reproduce.

that's weird...
By the way, I just clone from latest "develop" branch and run in Android emulator, the app having the same issue too.

Here are steps
1. clone from https://github.com/RocketChat/Rocket.Chat.ReactNative.git
2. run npm install
3. replace bundle id
4. add google service json for experimental flavour
5. start emulator (Android 10)
6. run command "npm run android-whitelabel {bundle.id}"

Is there any step I do it wrongly?
