### ISSUE TITLE
Cound not get 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom'. 

### ISSUE THREAD

**Issue by 9nuh** [RocketChat/Rocket.Chat.ReactNative#3548]
I cant build Android. 
Build failed output:
Could not GET 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.6.0-libre/jitsi-meet-sdk-3.6.0-libre.pom'. Received status code 401 from server: Unauthorized

Please help.

**Comment by weixuefeng** [comment]
+1

**Comment by wuvae** [comment]
build.gradle file
  jitsi_version = isPlay ? "3.6.0" : "3.6.0-libre" 
  modify to
  jitsi_version = isPlay ? "3.6.0" : "2.10.0-libre"

**Comment by ah3nan** [comment]
+1

**Comment by godot007** [comment]
+1

**Comment by artemChernitsov** [comment]
+1

**Comment by artemChernitsov** [comment]
Hi Rocket.Chat team.
Can you please help with this issue? 
I can't update Android Build for my Self Hosted Rocket.Chat instance, because I have a similar issue.

**Comment by pavlof01** [comment]
+1

**Comment by cuongnn-smartosc** [comment]
Hi, I have the same issue when build with Android Studio, turn out I select wrong build Flavor in Android studio

**Comment by diegolmello** [comment]
@cuongnn-smartosc Nice catch!

Yes, we have a few build flavors and you'll probably want to use `play` instead of `foss`.
`foss` is the one that uses `libre` version of Jitsi, which is failing to you all.

Make sure you use `experimentalPlay*` or `officialPlay*`.
We use experimental on development, so you if you check the [yarn android](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/package.json#L13), you'll see we're running `npx react-native run-android --variant=experimentalPlayDebug`.
If you want to build release, you want to use `experimentalPlayRelease`.

**Comment by seregasoft** [comment]
```
Version: 4.30.0

npx react-native run-android --variant=experimentalPlayRelease

* What went wrong:
Could not determine the dependencies of task ':app:mergeExperimentalPlayReleaseAssets'.
> Could not resolve all task dependencies for configuration ':app:experimentalPlayReleaseRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.6.0.
     Required by:
         project :app > project :react-native-jitsi-meet
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.6.0.
         > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.6.0/jitsi-meet-sdk-3.6.0.pom'.
            > Could not GET 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.6.0/jitsi-meet-sdk-3.6.0.pom'. Received status code 401 from server: Unauthorized
```

**Comment by convertcompany** [comment]
Hi, i've been having the same problem as you @seregasoft, but i've managed to get it working doing the following.

1. Deleting gradle caches
```
rm -rf ~/.gradle/caches/
```

2. Replacing the following line in the file (/node_modules/react-native-jitsi-meet/android/build.gradle)
```
implementation ("org.jitsi.react:jitsi-meet-sdk:$jitsi_version")
```
with
```
implementation ("org.jitsi.react:jitsi-meet-sdk:+")
```
