### ISSUE TITLE
No new message notification when use mobile app

### ISSUE THREAD

**Issue by smallfish01** [RocketChat/Rocket.Chat.ReactNative#3550]
### Description:

I installed and use mobile app in my iPhone, when someone send message to me the mobile app now show new message counter, but I can see the new message when I open the APP, I have enabled notification and app background refresh in my iPhone.

I can see the notification when I use Windows client.

### Environment Information:

- Rocket.Chat Server Version:4.1.2
- Rocket.Chat App Version:4.22.0.27018
- Device Name: iPhone
- OS Version: 15.1.1

### Steps to reproduce:

1. User "admin" send message to me, I can see the message notification in my Windows client.
2. But I didn't see new message notification and counter in my phone.
3. I tried close and reopen APP, removed and installed again, but it don't work.

**Comment by debdutdeb** [comment]
Hi, closing in favor of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3551
