### ISSUE TITLE
Rocket.Chat mobile app no messages notification

### ISSUE THREAD

**Issue by smallfish01** [RocketChat/Rocket.Chat.ReactNative#3551]
### Description:

When someone send message to me from APP/Web, I can got notification from web and Windows client, but my iPhone APP didn't have any notification, please check the picture.

I have enabled all message notification in my iPhone.
![rc-2](https://user-images.githubusercontent.com/4077255/145751178-db4ba6d2-bf29-45b6-8cbd-9a317949f3a4.jpg)
 

![RC-1](https://user-images.githubusercontent.com/4077255/145751166-34c49d43-45a2-4d18-bc73-d54a70ae512c.jpg)

### Steps to reproduce:

1. Send message from web use other account to me.
2. I can got message notification from my Windows client.
3. No notification when I check iPhone APP.

### Expected behavior:

I expect there are message number notification in my iPhone APP when someone send message to me.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version:3.6.14

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by smallfish01** [comment]
Thanks you guys, so I will waitting the next version and try again.

**Comment by smallfish01** [comment]
> 

Hi Diegolmello,

Web page and Windows client is ok, just iPhone and Android APP cannot receive notification.

Thank you.

**Comment by diegolmello** [comment]
Have you tried the server above?
We use this server for our team communication and we know push notifications are working.

**Comment by smallfish01** [comment]
Hi Diegolmello,
Thanks for your replied. I just change my APP Rocket.Chat url to https://open.rocket.chat and have a try, looks ok, I can receive some of message notification in my phone, maybe it's related with Rocket.Chat version and network connection issues.

Thank you so much.

**Comment by khanhbao0508** [comment]
Hi @diegolmello, 
I have question in this setting. When I set "push notifications" from "all messages" to "Mentions" after that, I close the app and still get the message with no mention. Is that correct behavior in this setting? ( I tried in rocketchat app from app store android version 4.24.0.28001 and Server version 4.4 https://open.rocket.chat/)
