### ISSUE TITLE
how to schedule LDAP user account sync

### ISSUE THREAD

**Issue by smallfish01** [RocketChat/Rocket.Chat.ReactNative#3554]
### Description:

How to setup my Rocket.Chat server to schedule sync LDAP users from my Windows AD server?

### Environment Information:

- Rocket.Chat Server Version:4.1.2

### Steps to reproduce:

1. Administration--LDAP
2. Not found how to setup schedult LDAP users account sync or sync LDAP users account automatically.

### Expected behavior:

I expece Rocket.Chat server can be sync AD account automatically.

**Comment by diegolmello** [comment]
Hi, @smallfish01.
Follow https://docs.rocket.chat/guides/administration/settings/ldap
If you still have questions, the correct repo is https://github.com/RocketChat/Rocket.Chat

**Comment by smallfish01** [comment]
Hi Diegolmello, 
Thanks for your answer, I am sorry sent the wrong area.
