### ISSUE TITLE
ReactNativeJS: undefined is not an object (evaluating 'In[e]')

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.ReactNative#356]
Before writing an issue, please make sure you're talking about the native application and not the Cordova one. If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat.Android app version: ####

- Your Rocket.Chat server version: ####

- Device model (or emulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by diegolmello** [comment]
@mahmodsallam There's not enough information.

**Comment by mahmodsallam** [comment]
only red screen appears 
on the physical device 
and message on top of it 
undefined is not a function (evaluating in[e])
and i dont know what is this ???

**Comment by diegolmello** [comment]
@mahmodsallam Make sure you have [installed React Native](https://facebook.github.io/react-native/docs/getting-started.html) properly and followed [How to run](https://github.com/RocketChat/Rocket.Chat.ReactNative#how-to-run).

If error persists, try [creating a new application](https://facebook.github.io/react-native/docs/getting-started.html#creating-a-new-application) to make sure your environment is configured right.
