### ISSUE TITLE
Login fails silently without any error - 4.21 onward

### ISSUE THREAD

**Issue by AHKAH** [RocketChat/Rocket.Chat.ReactNative#3562]
### Description:

Hello All,

I have set up a rocketchat server using docker on Windows Server 2022. I have a website on IIS pointing to the docker rocketchat server using a reverse proxy provided by rewrite. Here is my web.config for the website that also contains the rewrite rules:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<system.web>

		<httpRuntime maxRequestLength="200000" maxQueryStringLength="200000" executionTimeout="200000" requestPathInvalidCharacters="" />
	</system.web>
	<system.webServer>

		<httpErrors errorMode="Detailed" />
		<rewrite>
			<rules>
				<clear></clear>
				<rule name="ReverseProxyInboundRule1" stopProcessing="true">
					<match url="(.*)"></match>
					<conditions logicalGrouping="MatchAll" trackAllCaptures="false"></conditions>
					<serverVariables>
						<set name="HTTP_X_ORIGINAL_ACCEPT_ENCODING" value="{HTTP_ACCEPT_ENCODING}"></set>
						<set name="HTTP_ACCEPT_ENCODING" value=""></set>
						<set name="Connection" value="upgrade" />
						<set name="Host" value="{HTTP_HOST}" />
						<set name="X-Real-IP" value="{REMOTE_ADDR}" />
						<set name="HTTP_X_FORWARDED_PROTO" value="https" />
					</serverVariables>
					<action type="Rewrite" url="http://127.0.0.1:3000/{R:1}"></action>
				</rule>
			</rules>

			<outboundRules>
				<rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1">
					<match filterByTags="A, Area, Base, Form, Frame, Head, IFrame, Img, Input, Link, Script" pattern="href=(.*?)http://127.0.0.1:3000/(.*?)\s" ignoreCase="false" negate="false"></match>
					<action type="Rewrite" value="href={R:1}https://chat.solidex.exchange/{R:2}"></action>
				</rule>
				<rule name="Restore-AcceptEncoding" preCondition="NeedsRestoringAcceptEncoding">
					<match serverVariable="HTTP_ACCEPT_ENCODING" pattern="^(.*)"></match>
					<action type="Rewrite" value="{HTTP_X_ORIGINAL_ACCEPT_ENCODING}"></action>
				</rule>
				<preConditions>
					<preCondition name="ResponseIsHtml1">
						<add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/(.+)"></add>
					</preCondition>
					<preCondition name="NeedsRestoringAcceptEncoding">
						<add input="{HTTP_X_ORIGINAL_ACCEPT_ENCODING}" pattern=".+"></add>
					</preCondition>
				</preConditions>
			</outboundRules>
		</rewrite>
		<urlCompression doStaticCompression="false" doDynamicCompression="false" />
	</system.webServer>
	<system.web>
		<customErrors mode="Off"></customErrors>
	</system.web>
</configuration>
```

In the code above, I had to disable compression as I would keep getting  500 Server error (gzip). Once I added the rules, Everything works, on all platforms , all browsers , even my phone's browsers. I can log in, and start messaging and chatting and video calling. 

### Environment Information:

- Rocket.Chat Server Version: 4.2.2
- Rocket.Chat App Version: 4.22.0.27.017
- Device Name:  Samsung Galaxy S20+ Ultra
- OS Version: Android 11

### Steps to reproduce:

1. Install the docker version using the generic compose file available at:
https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers/docker-compose
Good now you can access the rocket chat locally on 127.0.01:3000.
2. Now to make it available globally, We set up an empty website on IIS with bindings "chat.domain.com" as I want the chat subdomain point to the rocket chat.
3. We then add the URL Rewrite rules or simply add the content of the config file above to the web.config to the directory of the website. 
4. Add all the proper "allowed server variables" to the website's URL Rewrite section

### Expected behavior:

I expect that my phone logs into the server.

### Actual behavior:

On the android app, after you enter the server address and then enter your username and password, nothing happens. No error. No Message. It is as if you did not press "Login" button at all.

### Additional context:

-I have generated a certificate using certbot.
-I also use Cloudflare to protect against DDOS attacks.
-If you need , I can send you the server URL as well as an account.

### Stuff I have tried

-I have tried different devices even as far as emulators, no luck, android app fails to login
-enabling/disabling compression in web.config does not have any effect.
-enforcing only https by through IIS binding has no effect.

### Potential Bug

**After testing all the versions post 4.0 version of rocketchat for android. I can confirm that login works on version 4.20 but breaks in 4.21 onward.** 

Thank you,

**Comment by diegolmello** [comment]
Thanks for reporting, @AHKAH.
Can you send me test credentials at https://open.rocket.chat/direct/diego.mello?

**Comment by AHKAH** [comment]
> Thanks for reporting, @AHKAH. Can you send me test credentials at https://open.rocket.chat/direct/diego.mello?

After Diego pointing to a lack of activity on WebSocket, I review the IIS settings. "HTTP_SEC_WEBSOCKET_EXTENSIONS" must be clear on the reverse proxy settings. 

if you are using IIS to set up your server and use URL Rewrite make sure to clear HTTP_SEC_WEBSOCKET_EXTENSIONS header as well. I am attaching the working config file for website pointing to the backend localhost holding rocketchat.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<system.web>

		<httpRuntime maxRequestLength="200000" maxQueryStringLength="200000" executionTimeout="200000" requestPathInvalidCharacters="" />
	</system.web>
	<system.webServer>

		<httpErrors errorMode="Detailed" />
		<rewrite>
			<rules>
				<clear></clear>
				<rule name="ReverseProxyInboundRule1" stopProcessing="false">
					<match url="(.*)"></match>
					<conditions logicalGrouping="MatchAll" trackAllCaptures="false"></conditions>
					<serverVariables>
						<set name="HTTP_X_ORIGINAL_ACCEPT_ENCODING" value="{HTTP_ACCEPT_ENCODING}" />
						<set name="HTTP_ACCEPT_ENCODING" value="" />
						<set name="HTTP_SEC_WEBSOCKET_EXTENSIONS" value="" />
					</serverVariables>
					<action type="Rewrite" url="http://127.0.0.1:3000/{R:1}" logRewrittenUrl="true"></action>
				</rule>
			</rules>
			<outboundRules>
				<rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1">
					<match filterByTags="A, Area, Base, Form, Frame, Head, IFrame, Img, Input, Link, Script" pattern="href=(.*?)http://127.0.0.1:3000/(.*?)\s" ignoreCase="true" negate="false"></match>
					<action type="Rewrite" value="href={R:1}https://chat.solidex.exchange/{R:2}"></action>
				</rule>
				<rule name="Restore-AcceptEncoding" preCondition="NeedsRestoringAcceptEncoding">
					<match serverVariable="HTTP_ACCEPT_ENCODING" pattern="^(.*)"></match>
					<action type="Rewrite" value="{HTTP_X_ORIGINAL_ACCEPT_ENCODING}"></action>
				</rule>
				<preConditions>
					<preCondition name="ResponseIsHtml1">
						<add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/(.+)"></add>
					</preCondition>
					<preCondition name="NeedsRestoringAcceptEncoding">
						<add input="{HTTP_X_ORIGINAL_ACCEPT_ENCODING}" pattern=".+"></add>
					</preCondition>
				</preConditions>
			</outboundRules>
		</rewrite>
		<urlCompression doStaticCompression="false" doDynamicCompression="false" />
	</system.webServer>
	<system.web>
		<customErrors mode="Off"></customErrors>
	</system.web>
</configuration>
```
Thank you very much dear Diego for pointing out the issue!
