### ISSUE TITLE
Please publish "how to build" instructions

### ISSUE THREAD

**Issue by TheAssassin** [RocketChat/Rocket.Chat.ReactNative#3582]
### Description:

No matter how I try, I struggle to find out how to build this app (or, ideally, the `foss` build variant), for Android. I've spent many hours in the last weeks. Since the app has not been updated in F-Droid for over a year (unfortunately due to build issues as well, as far as I can see), I thought I'd try to build it myself, and eventually try to fix the builds over at F-Droid.

I documented my build approach in https://github.com/TheAssassin/rocketchat-android-libre-builds/blob/master/build.sh. I've extended that script quite a bit so far, adding more and more steps after researching how React "native" needs to be built. I'd like to have a script that builds an (unsigned? debug? doesn't really matter) APK which I can install on my devices.

See also #3548, I've run into the exactly same issue until I added that `bundle` command. I am currently stuck at a similarly *not so helpful* build message: https://github.com/TheAssassin/rocketchat-android-libre-builds/runs/4627585240?check_suite_focus=true#step:3:24827

(For the record: I also tried in Android Studio because, why not. Building there lead to exactly the same issues. I am relatively confident building manually with Gradle should work just fine.)

Please document both build dependencies (tools etc.) as well as instructions (e.g., commands needed to run) how to build this project. This application seems to be especially difficult to build compared to other React "native" apps, which do not yield obscure project specific error messages whose solution is not so obvious.

### Environment Information:

- Rocket.Chat Server Version: not applicable
- Rocket.Chat App Version: I tried to build 4.21.0, 4.22.0 and master
- Device Name: not applicable
- OS Version: not applicable

### Steps to reproduce:

Please see my repository at https://github.com/TheAssassin/rocketchat-android-libre-builds/. I build in a Docker environment, everything is documented in the scripts.

To run a build locally, execute `./build-in-docker.sh <some workdir>`. The script will build the Docker image, then spin up a Docker container mounting the current working directory (to access the `build.sh` script) as well as the workdir (some temporary dir, e.g., in a RAM disk, which will contain the build).

### Expected behavior:

not applicable

### Actual behavior:

not applicable (see the build logs over at https://github.com/TheAssassin/rocketchat-android-libre-builds/actions)

### Additional context:

- #3548
- #3462
- Rocket.Chat related issues on https://gitlab.com/fdroid/fdroiddata (issue search does not seem when not logged in)

**Comment by diegolmello** [comment]
Thank you. We'll take a look.

**Comment by TheAssassin** [comment]
I can't produce a build with any of those information. Believe me, I've tried for days. Hence I was asking for precise instructions how to create a libre/F-Droid APK, even if it's just "clone repo, run these five commands, done". I think you might be caught by "works for me", or know some secret steps that need to be run in order to make the build work.

I was hoping for some more guidance, since this would've been an opportunity to hand off the (apparently time consuming) maintainership of the app to contributors. This reply is not helpful at all at the moment, since I found those information before (I forgot to mention that I studied the CircleCI scripts extensively).

It's unfortunate there's no completely libre builds of the app. It's even more unfortunate that we can't easily create any for the community, which could be distributed on F-Droid. We'll have to consider switching to another chat solution, I guess, because I need mobile access to some servers, but I do not intend to use anything that contains FCM or other surveillance technology.

Should you be able to help me out a bit further here, I'm still willing to get things up and running on F-Droid again. As said, I can't figure out all these weird React "native" issues, they just make zero sense at all on a usability level. Building the app itself should not be an issue, it's the JS dependency hell that drives me nuts. In my experience, building classic Android apps is easier, and therefore creates less maintenance for the fine folks over at F-Droid.

P.S.: I'm interested in creating signed release APKs, not debug builds. I forgot to mention that the debug build stuff already has failed due to various errors. I think it's some combination of tooling mismatch (tools versions) and errors in the build process.

**Comment by diegolmello** [comment]
> Hence I was asking for precise instructions how to create a libre/F-Droid APK

We don't have it, because we haven't been supporting F-Droid for over a year now.

> As said, I can't figure out all these weird React "native" issues, they just make zero sense at all on a usability level. Building the app itself should not be an issue, it's the JS dependency hell that drives me nuts.

This whole process of creating/maintaining a version on F-Droid requires _at least_ intermediate knowledge of how React Native works, because you need to understand how it deals with native dependencies and how you can remove proprietary libs without breaking the app and the build. It's not easy and, again, we don't support it since 2020, so it's not documented.

**Comment by markus-gellrich** [comment]
😥
bye

**Comment by guhyeon** [comment]
I successed.

step
1. In gradle.properties, BugsnagAPIKey key set
2. In gradle.properties,, set keystore[KEYSTORE KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD]
3. cd android && ./gradlew assembleOfficialPlayRelease

then apk file will be generated in android/app/outputs

**Comment by yogesh6260** [comment]
> I've successed.
> 
> step
> 
> 1. In gradle.properties, BugsnagAPIKey key set
> 2. In gradle.properties,, set keystore[KEYSTORE KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD]
> 3. cd android && ./gradlew assembleOfficialPlayRelease
> 
> then apk file will be generated in android/app/outputs

but the apk is not running as expected!
