### ISSUE TITLE
webp image format is not supported on mobile

### ISSUE THREAD

**Issue by Arryboom** [RocketChat/Rocket.Chat.ReactNative#3583]
on ios system,the **webp format image** message is showed as blackscreen in channel,failed to preview or download too.
guess this happens on android too.
on web(pc broswer) webp image message is absolutely normally showed and previewed.

- Rocket.Chat Server Version: latest
- Rocket.Chat App Version:latest
- OS Version: ios

for example:
upload this image to any channel on your rocketchat server on pc broswer:

![https://i.ibb.co/YX3JhdC/999.webp](https://i.ibb.co/YX3JhdC/999.webp)  
>https://i.ibb.co/YX3JhdC/999.webp

**Comment by diegolmello** [comment]
Apple released support for WebP on iOS recently, but we don't support it yet.
It should work properly on Android.

**Comment by Arryboom** [comment]
> Apple released support for WebP on iOS recently, but we don't support it yet. It should work properly on Android.

OK,thanks,do user need to update their ios system at the same time to fix this issue in the future fixed release?

**Comment by diegolmello** [comment]
We don't have a proper fix at the moment.

**Comment by hetanthakkar1** [comment]
@diegolmello Can we use this library: https://github.com/TGPSKI/react-native-webp-support

**Comment by diegolmello** [comment]
> @diegolmello Can we use this library: https://github.com/TGPSKI/react-native-webp-support

There's no commits on that lib for 4 years.
Also, we use react-native-fast-image, so we should add support there.
