### ISSUE TITLE
[Bug] Android client hangs when open chat with crossed out text

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3592]
### Description:

That issue is reproducible on on Android and only with old parser.
When user open chat this crossed out text it totally hangs - no buttons works.

### Environment Information:

- Rocket.Chat Server Version: 4.2.2
- Rocket.Chat App Version: 4.23.0
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 11

### Steps to reproduce:

1. Go to account settings - Preferences - Global and disable message parser if it enabled
2. From another account write a message with crossed out text, like ~test~
3. Try to open that chat on Android RCRN client
4. App totally hang

### Expected behavior:

App works perfect despite any messages with any markdown

### Actual behavior:

Set this settings
![image](https://user-images.githubusercontent.com/4023037/148877581-a250684d-af9b-4f11-913a-4f404187e62b.png)

![20220110_181159](https://user-images.githubusercontent.com/4023037/148757109-8de60886-2746-4f9e-8f41-1e2cf95b8a6c.gif)

### Additional context:

It is old parser issue on mobile. Old parser will be deprecated soon, but still need to be resolved in mobile.

**Comment by ankar84** [comment]
@diegolmello interesting, but in Experimental app version 4.24.0 with old parser that issue is not replicated anymore.

**Comment by ankar84** [comment]
IDK actually, but what if https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3576 fixed that issue in 4.24?

**Comment by diegolmello** [comment]
@ankar84 Good call. I'm closing. Please reopen if you see it. Thanks!

**Comment by ankar84** [comment]
Still facing that issue in the development branch.
We build our Whitelabel app from develop branch and that issue is still there.

**Comment by diegolmello** [comment]
@ankar84 You told us it was working. What changed?

**Comment by ankar84** [comment]
> @ankar84 You told us it was working. What changed?

It working it official apps, but not working in our whitelabel app, which we build on develop branch.
From what branch build official apps?

**Comment by ankar84** [comment]
@diegolmello we found the root cause of that issue and you need to remember about that in future releases.
On MacOS we used `yarn` to manage packets, on Linux we used `npm` for that.
Your project have `yarn.lock` file to specify packet version for `yarn`, but there is no `packages-lock.json` file to specify packet version for `npm`.
So, `npm` uses latest versions of packets, and obviously there is a packet with that bug in latest version.
So be careful on updating packages and test cross-out text with old parser after update.
Issue is fixed for us, so I'm closing that issue.
Take care!
