### ISSUE TITLE
Cannot remove a user from the team

### ISSUE THREAD

**Issue by try-catch-stack** [RocketChat/Rocket.Chat.ReactNative#3599]
### Description:
The app throws an error when trying to remove a user from the team. It is possible to remove the same user using the web and desktop app tho.

### Environment Information:
 
- Rocket.Chat Server Version: 
- Rocket.Chat App Version:  4.23.0
- Device Name: LG G8X
- OS Version: Android 11

### Steps to reproduce:

1. Create a team and add some users.
2. Try to remove a user from the team.You'll get an error and the user will not be removed.

### Expected behavior:

The user should be removed from the team.

### Actual behavior:

![team](https://user-images.githubusercontent.com/77742477/149124225-41f1ed19-9550-498f-a411-29b405eaab2b.png)

**Comment by entrymaster** [comment]
Hey, I would like to work on the bug. Can you assign me this issue?

**Comment by try-catch-stack** [comment]
@diegolmello @GleidsonDaniel This is also a major issue that has to be solved.

**Comment by diegolmello** [comment]
@try-catch-stack can you or @entrymaster work on a fix? (no need to assign issues on Github btw)

**Comment by try-catch-stack** [comment]
Can you please confirm the issue as I have only tested on teams with 1-2 members?

**Comment by diegolmello** [comment]
@LevyCosta can you check, please?

**Comment by try-catch-stack** [comment]
@diegolmello  Update: The issue has been solved by https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3557 and it fixes the issue.
Closing the issue!
