### ISSUE TITLE
IOS white screen on simulator after building

### ISSUE THREAD

**Issue by ealbers** [RocketChat/Rocket.Chat.ReactNative#3613]
### Description:

After building Rocket.Chat IOS the app launches in the simulator but only displays the white screen. Metro gives the error: 0308010C:digital envelope routines:unsupported and TypeError: Cannot read properties of undefined (reading 'transformFile') at Bundler.js

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name:  iPhone 12
- OS Version:  iOS 15.2
- macOS Monterey
- XCODE version 13.2.1

### Steps to reproduce:

1. git clone git@github.com:RocketChat/Rocket.Chat.ReactNative.git
    cd Rocket.Chat.ReactNative
    yarn
2. npx pod-install
    yarn ios

### Expected behavior:

IOS app to launch in the simulator and allow to enter server and login information

### Actual behavior:

IOS launches and displays white screen

**Comment by Salmankhan033** [comment]
Have you solved the issue?

**Comment by apostolovskisimon** [comment]
Any update on this?

**Comment by warbeast456** [comment]
Got the same problem after updating npm and node.js. 

IMHO: react native environment is so unstable for iOS. God help us all

**Comment by warbeast456** [comment]
I fixed it by updating access permissions to "site-functions" directory

as described here: https://stackoverflow.com/questions/13762280/zsh-compinit-insecure-directories
