### ISSUE TITLE
How to use storybook?

### ISSUE THREAD

**Issue by markmadlangbayan** [RocketChat/Rocket.Chat.ReactNative#362]
So we're trying to use storybook, and followed the `README`.  Without modifying any code, it doesn't work.

```bash
$ npm run storybook
$ react-native run-ios
```
How can we configure Storybook correctly on this project?

Thanks!

**Comment by diegolmello** [comment]
@markmadlangbayan Our Storybook is very outdated.
We'll update it on next PRs.
