### ISSUE TITLE
Duplicate members in the memberlist of a Channel/Team

### ISSUE THREAD

**Issue by try-catch-stack** [RocketChat/Rocket.Chat.ReactNative#3638]
### Description:

Members section of channels or teams does not show all unique members and shows some users multiple times.

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name: 
- OS Version: 

### Steps to reproduce:

1. Got to members section of a channel/team.
2. Scroll down to the bottom and you'll see that some members are present multiple times while some are not even once (Got to know by crosschecking from the web app).

### Expected behavior:

All members of the channel/team should be displayed once.

### Actual behavior:

Some members are present multiple times while some are not even once (Got to know by crosschecking from the web app).

https://user-images.githubusercontent.com/77742477/150386592-ce3aab7f-dbdb-462c-8f31-c458f49ec235.mp4

**Comment by try-catch-stack** [comment]
> @try-catch-stack
> 
> > Got to know by crosschecking from the web app
> 
> Do you mean it happens on web too?

No it doesn't .
I meant to say that to verify that some members are not shown , I cross checked from the web

**Comment by try-catch-stack** [comment]
The bug is most probably related to the way members are fetched and the pagination( Offset and Page size).
I tried by changing the page size (count) to greater than the members present and got the correct result.

**Comment by diegolmello** [comment]
Got you.
I've tested on a few rooms and it's working.
Can you give us more details?

**Comment by try-catch-stack** [comment]
Working? You mean the bug is for real right?

As I said above , the rooms with members<25 (Page size of the fetched members) should not have this issue.

**Comment by diegolmello** [comment]
Ok, I was able to reproduce it on https://open.rocket.chat/channel/general

**Comment by diegolmello** [comment]
@try-catch-stack Can you work on a fix?

**Comment by try-catch-stack** [comment]
I tested the api endpoint `/channels.members` (Refered [this](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/channels-endpoints/members#example-call) ) using the same offset and count and this also happens to give duplicate results for example first we take 0 as offset and 25 as count and get a result . Then we take 25 as offset and 25 as count and this result contains some members which were also present in the first one.

**Comment by try-catch-stack** [comment]
> @try-catch-stack Can you work on a fix?

I have been trying to look for the fix for a while now and figured out this. I thought that some insights would help so created an issue here.

**Comment by ankar84** [comment]
Confirm that issue on latest 4.26.2
And here is a one more thing. When I scroll member list, I see some users 3 or 4 or even maybe 5 times, and in some moment user list is over, I see blank screen. And in that moment I guess another one set of duplicated users creates and I see them one more time. So, I never see other users.

**Comment by guilhermedfs** [comment]
Is this behavior still happening? If it does, can I pick this one?
