### ISSUE TITLE
Display of Images 

### ISSUE THREAD

**Issue by strike65** [RocketChat/Rocket.Chat.ReactNative#3642]
Hi there,

during a project by myself I realized that there is no way to apply scaling to an IImageElement in my App. 
This results in an "ugly" display (upscaling) of smaller images in the mobile app. It would be helpful if the dimensions of the image were respected in the display.

Regards!

strike65

**Comment by diegolmello** [comment]
@strike65 Thanks for your report. Can you follow the issue template and give us more details?
