### ISSUE TITLE
[BUG] Google OAth not working on the android application

### ISSUE THREAD

**Issue by samad-yar-khan** [RocketChat/Rocket.Chat.ReactNative#3644]
### Description:

Whenever the user triies to log into the Open Workspace Server using Google OAth, they are sent back to the login screen. The user is not authorized.  

 ### Environment Information:

- Rocket.Chat App Version: 4.23.0.27401
- Device Name: Redmi K20 Pro
- OS Version:  Android 10 QKQ1.190825.002

### Steps to reproduce:

1. Download and Open the android Application.
2. Click - Join Our Open Workspace 
3. Click on continue with Google 
4. Select your Google Account

### Expected behavior:

1. The application should authorize the user using the Gmail. 

### Actual behavior:

1. The user is sent back to the login screen. 

https://user-images.githubusercontent.com/70485812/150637302-59ce89aa-6802-46d7-a265-4dd939cee9a3.mp4

**Comment by try-catch-stack** [comment]
The issue has been solved by https://github.com/RocketChat/Rocket.Chat/pull/24381 . You can close the issue @samad-yar-khan .

**Comment by samad-yar-khan** [comment]
@try-catch-stack Thanks for notifying :) . Closed !
