### ISSUE TITLE
Mobile stops updating data & then user is signed out after X amount of time?

### ISSUE THREAD

**Issue by Gintasz** [RocketChat/Rocket.Chat.ReactNative#3655]
### Description:
I've started a self hosted rocketchat server (4.3.2). Migrated to wiredtiger. Mongodb 5.0

I use my admin account on web and mobile. I noticed this happened about 3 times now today. After having mobile app in background for some time, I reopen it, but nothing gets updated. If I enter a channel, I see spinner spinning. If I swipe-to-refresh in the channels list, I see "updating..." which doesn't finish. DMs are also not updating. Then after maybe 10 seconds, I get a message on mobile app "server logged you out", and I'm thrown right into the authentication screen to enter username and password. After signing in, everything immediatelly updates.

### Environment Information:

- Rocket.Chat Server Version: 4.3.2
- Rocket.Chat App Version: 4.24.0.28004
- Device Name: iPhone XR
- OS Version: iOS

### Additional context:

**Comment by ankar84** [comment]
Check these settings in Admin UI
![image](https://user-images.githubusercontent.com/4023037/151295317-a3025649-830d-4eae-aee5-49031357e818.png)
![image](https://user-images.githubusercontent.com/4023037/151295330-78d78835-7ab4-42c4-87cf-ddb267a8ac60.png)

**Comment by Gintasz** [comment]
This turned out to be because I had a bot signing in to my account every 30 seconds and doing some actions. I fixed it by moving the bot to a separate account.

**Comment by dudanogueira** [comment]
Link in forums for reference:
https://forums.rocket.chat/t/fixed-mobile-stops-updating-data-then-user-is-signed-out-after-x-amount-of-time-web-app-too/13111
