### ISSUE TITLE
Webrtc  Library for React Native

### ISSUE THREAD

**Issue by masterbater** [RocketChat/Rocket.Chat.ReactNative#370]
https://github.com/oney/react-native-webrtc.
Hi You might considering using this library
Are you already working on the audio and video call implementation for react native? I'm excited to see this feature. . I'm considering to add video and audio myself but i need dig up to rocket chat server code to see its implementation.

**Comment by diegolmello** [comment]
Hi, @masterbater.
I'm not working on it right now.
Do you want do it?
I can help you with server side stuff.

**Comment by bo17age** [comment]
Hello @diegolmello i would like to implement Video chat (using Jitsi as in Web version).
Is it ok and how to collaborate with you on this?

**Comment by diegolmello** [comment]
@bo17age Of course. Thanks!

**Comment by bo17age** [comment]
> @bo17age Of course. Thanks!

@diegolmello  I'm working on this now !

**Comment by diegolmello** [comment]
It'll be done in #711
