### ISSUE TITLE
iOS Clients can't auth at Iframe configured server

### ISSUE THREAD

**Issue by svartedauen** [RocketChat/Rocket.Chat.ReactNative#3710]
- Rocket.Chat Server Version: 3.18.3
- Rocket.Chat App Version: 4.24.0.28004
- Device Name: iPhone 12 Pro
- OS Version: iOS 15.3

### Steps to reproduce:

1. Install RChat 4.24.0.28004 on iOS 
2. Enter the URL (server address), click connect.
3. Name of Chat will be displayed, press Login. 
4. Click "Login"

### Expected behavior:
Authorization of the user on the server 

### Actual behavior:

The web client welcome message opens in an iFrame with the title SSO.
The user is not authorized.

![FEB56D9E-EF45-465A-B559-F4852022AD5F](https://user-images.githubusercontent.com/2248178/153412755-71870928-617f-4594-8b43-5986de2f5951.png)

### Additional context:

Authorization via IFrame is configured on the server.
BTW: Authorization in Android and native Windows application works correctly.

**Comment by diegolmello** [comment]
@svartedauen Thanks for reporting.
Version 3.18 very old though.
Can you update to make sure it's not fixed already?

**Comment by svartedauen** [comment]
>Can you update to make sure it's not fixed already?
Okay, today we have already scheduled the maintance for the update. I would not create a ticket if I did not see that authorization works in Android.

**Comment by diegolmello** [comment]
You can send a test user to my personal account on https://open.rocket.chat/direct/diego.mello
We've been focusing our efforts to finish the Migration to Typescript this month, but I can add it to next sprint.

**Comment by svartedauen** [comment]
Unfortunately, authorization in the our rocket chat is possible only through the corporate portal by Iframe. I am not allowed to create an account in corporate portal for third parties and this complicates the situation.

Tell me, is it possible to test the work through iframe authorization in the iOS client on any alternative environment on your own?

**Comment by diegolmello** [comment]
I understand.
We don't have enough create the reproducible example on our own.
Can you setup an env for us? Maybe a cloud trial https://cloud.rocket.chat/.
We can take a look at it next sprint.

**Comment by svartedauen** [comment]
I'm sorry, I'm having trouble deploying due to lack of time. Time is wasted on current work.

**Comment by diegolmello** [comment]
@svartedauen That's cool! Just pay attention we didn't touch anything on that part of the code.
