### ISSUE TITLE
The full name is not displayed

### ISSUE THREAD

**Issue by oinadmin** [RocketChat/Rocket.Chat.ReactNative#376]
![photo_2018-07-23_09-53-23](https://user-images.githubusercontent.com/39171599/43061982-fd7d3f90-8e5f-11e8-9650-e5c85acc0dbb.jpg)
In desktop client all normal
![rok](https://user-images.githubusercontent.com/39171599/43061903-a9ef4a44-8e5f-11e8-8502-6faead2b2390.jpg)

**Comment by diegolmello** [comment]
@oinadmin There's a setting we didn't implement yet.
I'll do it in a few days.

**Comment by oinadmin** [comment]
ok, thank you

**Comment by oinadmin** [comment]
Answer please when this will be implemented

**Comment by diegolmello** [comment]
@oinadmin It's on master and Google Play already. Check it out!
