### ISSUE TITLE
Can't send voice message from iPhone

### ISSUE THREAD

**Issue by kodaf1** [RocketChat/Rocket.Chat.ReactNative#3763]
### Description:

I can't send voice messages longer than 2 minutes from iPhone 12. 

### Environment Information:

- Rocket.Chat Server Version: 4.4.2
- Rocket.Chat App Version: 4.24.0.28004
- Device Name: iPhone 12
- OS Version: IOS 15.0.2

### Steps to reproduce:

1. Record voice message longer than 2 minutes to any chat.
2. Try to send it
3. You should get error "Error uploading filename"

### Expected behavior:

Voice message should be sent.

### Actual behavior:

Error.
![image](https://user-images.githubusercontent.com/56591637/154873656-e9523290-e876-4655-8f4b-eeae1603b2e3.png)

### Additional context:

Everything is ok on PC version. 
Files max size is set to -1.

**Comment by fiberson** [comment]
I have same problem

**Comment by diegolmello** [comment]
Maybe server is limiting the file size?

**Comment by kodaf1** [comment]
> Maybe server is limiting the file size?

As I wrote in issue file size limit is set to -1(unlimited) and everything is ok on PC.

**Comment by fiberson** [comment]
Guys?

**Comment by diegolmello** [comment]
I just did that on https://open.rocket.chat.
