### ISSUE TITLE
Messages are not always properly refreshed since RC mobile v4.25.0

### ISSUE THREAD

**Issue by stefanandres** [RocketChat/Rocket.Chat.ReactNative#3811]
### Description:

After upgrading the iOS RC client to 4.25.0 newly sent messages are not always being automatically refreshed in the client.

After manually refreshing (i.e. by pulling down) new messages appear though.

### Environment Information:

- Rocket.Chat Server Version: 4.5.0 (also happened with 4.4.x)
- Rocket.Chat App Version: 4.25.0
- Device Name: iPhone
- OS Version: iOS 15.3.1

### Steps to reproduce:

1. Write messages
2. See that they do not appear

### Expected behavior:

New messages are always being refreshed

### Actual behavior:

New messages are not being show.

### Additional context:

I've found out that I have a lot of HTTP 400 in the webserver log (nginx) regarding the 

/api/v1/chat.syncMessages endpoint:

From 700 requests:
500 requests got HTTP 200.
200 requests got HTTP 400

200er lines are looking quite normal:
```
"x.x.x.x - - [03/Mar/2022:14:49:49 +0000] \"GET /api/v1/chat.syncMessages?roomId=NPHxM4PGcGHsazaEb&lastUpdate=2022-02-24T14%3A49%3A49.262Z HTTP/2.0\" 200 49389 \"-\" \"RC Mobile; ios 15.3.1; v4.25.0 (29369)\" 224 0.221 [rocketchat-chat-sandres-rocketchat-http] [] 172.25.4.21:3000 49432 0.221 200 b58d0a230ee8364e2d7050dbc4517b82\n"
```

The 400er always look like this:
```
"x.x.x.x - - [03/Mar/2022:14:58:26 +0000] \"GET /api/v1/chat.syncMessages?roomId=NPHxM4PGcGHsazaEb&lastUpdate=undefined HTTP/2.0\" 400 127 \"-\" \"RC Mobile; ios 15.3.1; v4.25.0 (29369)\" 65 0.009 [rocketchat-chat-sandres-rocketchat-http] [] 172.25.6.29:3000 143 0.010 400 ba32aadf8e70870e7272ce81d6249d72\n"
```

I.e. the lastUpdate parameter is set to `undefined`. There is also a matching log line in the node js logs:
```
"{\"level\":35,\"time\":\"2022-03-03T14:14:35.929Z\",\"pid\":1,\"hostname\":\"chat-sandres-rocketchat-5574fdc76d-bc87v\",\"name\":\"\",\"name\":\"API\",\"method\":\"GET\",\"url\":\"/api/v1/chat.syncMessages?roomId=NPHxM4PGcGHsazaEb&lastUpdate=undefined\",\"userId\":\"ASegbpbFmiwFdCBY2\",\"userAgent\":\"RC Mobile; ios 15.3.1; v4.25.0 (29369)\",\"host\":\"chat.sandres.de\",\"remoteIP\":\"x.x.x.x\",\"err\":{\"type\":\"errorClass\",\"message\":\"The \\\"lastUpdate\\\" query parameter must be a valid date. [error-roomId-param-invalid]\",\"stack\":\"Error: The \\\"lastUpdate\\\" query parameter must be a valid date. [error-roomId-param-invalid]\\n    at Object.get (app/api/server/v1/chat.js:79:11)\\n    at app/api/server/api.js:425:96\\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)\\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\\n    at packages/simple_json-routes.js:100:9\",\"isClientSafe\":true,\"error\":\"error-roomId-param-invalid\",\"reason\":\"The \\\"lastUpdate\\\" query parameter must be a valid date.\",\"errorType\":\"Meteor.Error\"},\"status\":400,\"responseTime\":3,\"msg\":\"The \\\"lastUpdate\\\" query parameter must be a valid date. [error-roomId-param-invalid]\"}\n"
```

This is quite a small server with 2 users, but both users experience this issue (which makes the server quite unusable)

**Comment by cuongnn-smartosc** [comment]
In additions to above, when you delete the message, it does not automatically disappeared. You can replicated by trying to delete multiple messages.

Thanks

**Comment by gerzonc** [comment]
Can you share more details about this in order to reproduce it? I tried to replicate the issue but I was unable to.

**Comment by diegolmello** [comment]
I was also unable to reproduce it.
We thought about making sure we don't send those `undefined` requests, but we'd only be hiding the real issue.
@stefanandres Is there any other thing you do with the app before the actions you wrote on `Steps to reproduce`?

**Comment by MattiasMentzer** [comment]
Another step to reproduce is to write some messages as user A in a channel from any client. Then open the app on the iPhone of user B and most of the time these new messages are not displayed or only a few of the new messages (not all).

When you are in a direct interaction (user A and B online and writing) also most of the messages are not displayed to the other user. You always have to refresh within the channel by pulling up to get new messages.

**Comment by MattiasMentzer** [comment]
Maybe. Let us wait until @stefanandres adds some information to it. For my understanding it is the same issue. But maybe we mixed things up a little.

Is there any ETA on a new version of the mobile app for the Apple AppStore and is there a beta (via Testflight)?

**Comment by stefanandres** [comment]
>  @stefanandres Is there any other thing you do with the app before the actions you wrote on Steps to reproduce?

Not really. Usually I just keep one channel open. The other person types something and the messages do not appear. It doesn't even matter if the app is in foreground or if I open it back from the background.

You can see in the screenshot below that the nodejs is still getting those lastUpdate=undefined calls and then stacktraces with the 4.25.0 client.

![Screenshot 2022-03-22 at 13 52 03](https://user-images.githubusercontent.com/2674469/159486113-086e4dfa-01da-4475-835c-2aa1c07fc3f1.png)

If there is any pre-release I can install on the iPhone I could do this as well.

**Comment by diegolmello** [comment]
@stefanandres I just submitted for review on TestFlight.
Make sure you join beta here https://docs.rocket.chat/quick-start/mobile-and-desktop-apps/rocket.chat-desktop-and-mobile-apps#rocket.chat-experimental-beta

**Comment by stefanandres** [comment]
Alright, I have it installed and will see if the error still persists.

**Comment by stefanandres** [comment]
At least those lastUpdate=undefined calls are still present:
```
  | {"log":"{\"level\":35,\"time\":\"2022-03-22T13:12:21.554Z\",\"pid\":1,\"hostname\":\"x-rocketchat-6b7775c99c-c5csl\",\"name\":\"API\",\"method\":\"GET\",\"url\":\"/api/v1/chat.syncMessages?roomId=NPHxM4PGcGHsazaEb\u0026lastUpdate=undefined\",\"userId\":\"ASegbpbFmiwFdCBY2\",\"userAgent\":\"RC Mobile; ios 15.4; v4.25.0 (29369)\",\"host\":\"x.de\",\"remoteIP\":\"x.x.x.x\",\"err\":{\"type\":\"errorClass\",\"message\":\"The \\\"lastUpdate\\\" query parameter must be a valid date. [error-roomId-param-invalid]\",\"stack\":\"Error: The \\\"lastUpdate\\\" query parameter must be a valid date. [error-roomId-param-invalid]\\n    at Object.get (app/api/server/v1/chat.js:79:11)\\n    at app/api/server/api.js:425:96\\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)\\n    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)\\n    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)\\n    at packages/rocketchat_restivus/lib/route.coffee:59:33\\n    at packages/simple_json-routes.js:100:9\",\"isClientSafe\":true,\"error\":\"error-roomId-param-invalid\",\"reason\":\"The \\\"lastUpdate\\\" query parameter must be a valid date.\",\"errorType\":\"Meteor.Error\"},\"status\":400,\"responseTime\":2,\"msg\":\"The \\\"lastUpdate\\\" query parameter must be a valid date. [error-roomId-param-invalid]\"}\n","stream":"stdout","time":"2022-03-22T13:12:21.554984853Z"}
-- | --
```

This seems almost always seem to happen when:
- Open app
- Open channel
- Put app to background (i.e. swiping up) 
- Short press power button iPhone
- Open app
- See lastUpdate=undefined call in log

Due to not enough activity on the server, I couldn't check if the messages not refreshing behaves differently with the beta app yet.

**Comment by stefanandres** [comment]
The beta from yesterday seems to have fixed the undefined calls and medsage refreshed though. I assume the issue is fixed now, I will close the issue when it doesn't happen for a 1-3 days.

Thanks! :)
