### ISSUE TITLE
Deleted message will not go away

### ISSUE THREAD

**Issue by cuongnn-smartosc** [RocketChat/Rocket.Chat.ReactNative#3852]
### Description:

Try to delete multiple messages, the app stop updating the message list

### Environment Information:

- Rocket.Chat Server Version: 4.5
- Rocket.Chat App Version: 2.25
- Device Name: iOS
- OS Version: 

### Steps to reproduce:

1. Type something in the chat
2. Select any message and hit delete
3. The message list does not update (sometime it does)

### Expected behavior:

The delete message will be disappeared in the message list

### Actual behavior:

Message still displayed

### Additional context:

If you pull up to fresh, the deleted message will be gone

**Comment by diegolmello** [comment]
I was not able to reproduce it. Can you share more details?
