### ISSUE TITLE
Bypass Server Screen

### ISSUE THREAD

**Issue by skhizerabass** [RocketChat/Rocket.Chat.ReactNative#386]
I just want to bypass (remove) the server screen 
I already have a server and i want user to connect to that server directly.

I tried to add my server in lib/Realm.js . But each time i write my server i get error in log .
Realm Method not found
realm.write(() => {
  	realm.create('servers', { id: 'myserver', current: true }, true);
this was the code i uncommented it

But i really have no idea about Bypassing my server screen.
Please if anyone can help me out in this it will be of great help.

**Comment by diegolmello** [comment]
Hi, @skhizerabass.
The code in charge of server creation is this: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/sagas/selectServer.js#L59

Your code is open source?
I could take a look into it.

**Comment by skhizerabass** [comment]
import { Component } from 'react';
import { Linking } from 'react-native';
import { Navigation } from 'react-native-navigation';
import store from './lib/createStore';

import { appInit } from './actions';
import database from './lib/realm';
import { iconsLoaded } from './Icons';
import { registerScreens } from './views';
import { deepLinkingOpen } from './actions/deepLinking';
import parseQuery from './lib/methods/helpers/parseQuery';
import I18n from './i18n';
import { initializePushNotifications } from './push';
import { connect } from 'react-redux';


const startLogged = () => {
	Navigation.startSingleScreenApp({
		screen: {
			screen: 'RoomsListView',
			title: I18n.t('Messages')
		},
		drawer: {
			left: {
				screen: 'Sidebar'
			}
		},
		animationType: 'fade'
	});
};

const startNotLogged = (route) => {
	Navigation.startSingleScreenApp({
		screen: {
			screen: route,
			title: route === 'NewServerView' ? I18n.t('New_Server') : I18n.t('Servers')
		},
		animationType: 'fade'
	});
};



const hasServers = () => {
	const db = database.databases.serversDB.objects('servers');
	return db.length > 0;
};

const handleOpenURL = ({ url }) => {
	if (url) {
		url = url.replace(/rocketchat:\/\/|https:\/\/go.rocket.chat\//, '');
		const regex = /^(room|auth)\?/;
		if (url.match(regex)) {
			url = url.replace(regex, '');
			const params = parseQuery(url);
			store.dispatch(deepLinkingOpen(params));
		}
	}
};


registerScreens(store);
iconsLoaded();

/** @extends React.Component */
export default class App extends Component {

	constructor(props) {
		super(props);
		store.dispatch(appInit());
		store.subscribe(this.onStoreUpdate.bind(this));
		initializePushNotifications();

		Linking
			.getInitialURL()
			.then(url => handleOpenURL({ url }))
			.catch(e => console.warn(e));
		Linking.addEventListener('url', handleOpenURL);
	}

	onStoreUpdate = () => {
		const { root } = store.getState().app;

		if (this.currentRoot !== root) {
			this.currentRoot = root;
			if (root === 'outside') {
				if (hasServers()) {
				} else {
					database.databases.serversDB.write(() => {
						database.databases.serversDB.create('servers', { id: 'http://myserver.test:3000', current: true }, true);
					});
				
				}
				startNotLogged("ListServerView")
			} else if (root === 'inside') {
				startLogged();
			}
		}
	}

	setDeviceToken(deviceToken) {
		this.deviceToken = deviceToken;
	}
}


This is the code i am using. Now this code is creating server in database for me .But i am not able to switch to LoginSignupView. If you can guide me to directly connect with this server and switch to the LoginSignupView. I want to finish this ListServerView

**Comment by skhizerabass** [comment]
@diegolmello  Can you please guide me how can i connect directly to my server and take user to LoginSignupView directly.

**Comment by diegolmello** [comment]
@skhizerabass Take a look at `single-server` branch.

**Comment by skhizerabass** [comment]
ok Thank you for the reply

**Comment by skhizerabass** [comment]
@diegolmello  Can you test this branch. 
It doesn't work and throws warning.
ReactNative : Disconnected.

Also note this. If you use ListServerView once and try this trick you mentioned. It works only with that, But if you uninstall the application and install solely with these changes it won't work.
I have already tried this before and also tried your branch.
Thank you.

**Comment by skhizerabass** [comment]
![screen shot 2018-07-30 at 8 12 07 pm](https://user-images.githubusercontent.com/15678235/43406330-6c4cf9da-9435-11e8-9a48-d6c07e5e2074.png)

**Comment by diegolmello** [comment]
@skhizerabass Did you set your server on `app.json`?
It's working here.
Can you debug to see what's going on for you?

**Comment by skhizerabass** [comment]
Yes i set that up.
Can you try it with uninstalling the previous version. 
and try the fresh installation ?

**Comment by skhizerabass** [comment]
![whatsapp image 2018-07-30 at 22 33 56](https://user-images.githubusercontent.com/15678235/43413200-d7d18064-9448-11e8-9ccb-a206d997ccad.jpeg)

Once You Logout this is the error it throws.
Can you check this ?
Thanks

**Comment by mnlbox** [comment]
@skhizerabass any news?
