### ISSUE TITLE
can't connect to a server on subpath

### ISSUE THREAD

**Issue by stinkydiver73** [RocketChat/Rocket.Chat.ReactNative#388]
I have a server on subpath (https://....ddns.net/rchat), works with the web and the native app, this client just says :"is not a valid Rocket.Chat instance".  (The server is behind nginx)

**Comment by diegolmello** [comment]
I'll take a look

**Comment by stinkydiver73** [comment]
It's not updated on Google Play for me.

**Comment by diegolmello** [comment]
@stinkydiver73 Can you ping me at open.rocket.chat with details about your server?
With access to one user I can help you more.

**Comment by stinkydiver73** [comment]
details sent. As you will see, now i have a cname for Rocket.Chat, so this subpath feature is not important anymore (a .club domain is $1.17/year). It have problem with zapier too (it's not cross checked without subpath).

**Comment by diegolmello** [comment]
Probably fixed at #551
