### ISSUE TITLE
Notification is not working

### ISSUE THREAD

**Issue by skhizerabass** [RocketChat/Rocket.Chat.ReactNative#389]
Can't send or receive any notification. Followed the instructions But still no success in fixing the notification issues.

**Comment by skhizerabass** [comment]
>  
> 
> java.lang.Exception: FATAL: Failed to fetch a fresh new token, instanceId=dhL1f6J8CNA
>         at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:99)
>         at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77)
>         at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66)
>         at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23)
>         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.os.HandlerThread.run(HandlerThread.java:61)
>      Caused by: java.io.IOException: INVALID_SENDER
>         at com.google.android.gms.iid.zzaf.zzi(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.zze(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
>         at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:95)
>         at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77) 
>         at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66) 
>         at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23) 
>         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
>         at android.os.Handler.dispatchMessage(Handler.java:102) 
>         at android.os.Looper.loop(Looper.java:148) 
>         at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by diegolmello** [comment]
Hi, @skhizerabass.
As the error says, you set an invalid sender id.

**Comment by skhizerabass** [comment]
@diegolmello I have already double checked my sender ID which i got from the console.  It still gives me this error
