### ISSUE TITLE
Improved Navigation in the App

### ISSUE THREAD

**Issue by gdelavald** [RocketChat/Rocket.Chat.ReactNative#39]
Look into possible refactor or replacements for the current navigation library

**Comment by mnlbox** [comment]
I already worked with [react navigation](https://reactnavigation.org/) and it's very lite and powerful for me.

**Comment by gdelavald** [comment]
@mnlbox Bingo! We just moved into react-navigation as well, still fixing some issues but it looks very good indeed.
