### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by khodge281** [RocketChat/Rocket.Chat.ReactNative#3901]
Why cant my phone alert me to let me know i have a new message on rocket chat. No matter what I do, I can not get any kind of ring tone or alert. I just have to look at my phone about every 5 minutes and that is just ay too counterproductive.  I need an answer right away NOT in two or 3 days. I am working AWAY from my computer and this is a pain in the ass.

**Comment by diegolmello** [comment]
There's not enough info to help you, but here's a few reasons:
- You need to register your server.
- Make sure your messages follow this workflow https://whimsical.com/notification-workflow-PRwN4MWNsxSwqHjHXaPUuC

**Comment by khodge281** [comment]
I am not sure how much more info I can give, other than I receive alerts on my DESKTOP when I get a message but NOT on my phone. The message DOES come to my phone, but I can not get it to ring or alert when I get a message.
I am going to ask my office manager if he can check and make sure our server is properly registered and then we can go from there.

Thanks

**Comment by NoxInmortus** [comment]
I have the same issue. I don't have any push notification on my phone using RocketChat reacNative app (as well as Experimental version).

I can also add that when trying to access the Notification menu on my phone, it does not open but loads indefinitely.

And it's been some time.

**Comment by diegolmello** [comment]
@NoxInmortus What's your device?
Can you check if you receive push notifications on https://open.rocket.chat?

**Comment by diegolmello** [comment]
I was about to say that.
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3901#issuecomment-1067971992

We only send push notifications to registered servers and we have some limitations https://docs.rocket.chat/guides/administration/admin-panel/settings/push-notifications-admin-guide
