### ISSUE TITLE
Incorrect link in documentation Mobile App White Labelling - colors.js

### ISSUE THREAD

**Issue by seregasoft** [RocketChat/Rocket.Chat.ReactNative#3933]
### Description:

Incorrect link in documentation.

### Environment Information:

- Any browser.

### Steps to reproduce:

1. On page https://developer.rocket.chat/mobile-app/mobile-app-white-labelling#general
2. Click on "Change app colors on" [colors.js](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/single-server/app/constants/colors.js)

### Expected behavior:

Open target page.

### Actual behavior:

Error 404.

**Comment by diegolmello** [comment]
I'm going to update it on next week's release.
You can refer to https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/single-server/app/constants/colors.ts in the meantime.

**Comment by diegolmello** [comment]
Submitted a fix for docs team. Thanks!
