### ISSUE TITLE
Scroll issues in channels screen

### ISSUE THREAD

**Issue by nucleartux** [RocketChat/Rocket.Chat.ReactNative#3968]
### Environment Information:

- Rocket.Chat Server Version:  idk
- Rocket.Chat App Version: 4.25.0
- Device Name: iPhone X
- OS Version: ios 15.4

### Steps to reproduce:

1. Channels
2. Scroll deep down

### Expected behavior:

List shows items correctly.

### Actual behavior:

Scroll glitches and blank spaces:

https://user-images.githubusercontent.com/199706/160274338-4759cb21-4844-419b-b8c0-7b59909c4c7c.mov

**Comment by samay-kothari** [comment]
Hi,
I think its a ReactNative specific issue, which happens when the number of list items are large. Most of the precautions mentioned here are being taken care of.
Check this: https://reactnative.dev/docs/optimizing-flatlist-configuration
