### ISSUE TITLE
[bug] Thread navigation issue on tablets

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#3969]
### Description:

Probably that bug is only tablet issue.
When user opens some thread in chat and then navigate to another chat in sidebar, he can't return to first chat.

### Environment Information:

- Rocket.Chat Server Version: 4.3.3
- Rocket.Chat App Version: 4.25.0.29396
- Device Name: iPad Pro
- OS Version: 15.3.1

### Steps to reproduce:

1. Go to some thread in chatA on iPad in tablet view
2. Tap on any other chat in sidebar
3. Tap in chatA in sidebar
4. Nothing happens - chatA don't opens

### Expected behavior:

User should be able to open chatA after navigated another chat

### Actual behavior:

https://user-images.githubusercontent.com/4023037/160352181-c346707b-cfbf-41de-abdb-99b8855e09ae.MP4

### Additional context:

No

**Comment by samay-kothari** [comment]
Hi @ankar84 
I was able to reproduce the bug.
On investigating more, the problem that is happening is, user is not unsubscribing from the room when directly navigating from a thread to a different room.
So when we try to go the chat again, it's already subscribed to that, and we are unable to go back to it.

**Comment by samay-kothari** [comment]
Hi @ankar84 and @diegolmello,
I have made a PR that fixes the issue (see the screen recording attached in the PR), the only doubt is the existence of a corner case where we have a user having more than one RoomSubscriptions, if it should not happen in any ideal scenario, then the fix is fine.

**Comment by skadefro** [comment]
I have also had this for a long time.
I can reproduce it 100% of the times, like in the step by step guide by @ankar84 
Ipad air, gen 7, 
IoS 15.4.1 ( and many version before that )
Rocket chat client: 4.26.2.30993
Rocket chat server: 4.6.3 (and many version before that )
