### ISSUE TITLE
Collapsible Messages broken in V. 4.26.0.30766 on iOS

### ISSUE THREAD

**Issue by strike65** [RocketChat/Rocket.Chat.ReactNative#3971]
### Description:

PDF-Attachments can not be opened an viewed. Nothing happens, when interacting with the attachement.

### Environment Information:

- Rocket.Chat Server Version: 4.3
- Rocket.Chat App Version: 4.26.0.30766
- Device Name: iPhone
- OS Version: latest iOS

### Steps to reproduce:

1. Upload a PDF to a channel
2. Open that channel
3. try to open the PDF -> nothing happens (collapsible message doesn't work)

### Expected behavior:

You can view the PDF on your mobile device.

### Actual behavior:

You see nothing! Well... you see the chat.

**Comment by ToqQrrl** [comment]
The iOS client shows the messages as if they were always collapsed … and the consequence of this is that it is now impossible to see the entire message since this update.

**Comment by diegolmello** [comment]
We've been working on a fix on #3973.
We're going to make sure it's merged and released on the final 4.26.
The plan is to have it released Today, but we depend on Apple review.

**Comment by Magelo** [comment]
> We've been working on a fix on #3973. We're going to make sure it's merged and released on the final 4.26. The plan is to have it released Today, but we depend on Apple review.


Good news! But I don't understand the part mentionning "final 4.26"... I installed the version offered on the Apple App Store, it's not the final 4.26?

Some messages from applications like Uptime Kuma can't be expand. Seems linked to the message structure, other like Emby, docker Watchtower are not affected (rocket.chat don't offer to collapse message)
