### ISSUE TITLE
Single-Server 4.26.1 error: "Type Error: undefined is not a function"

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#3990]
### Description:

Single-Server 4.26.1 IOS-version won't run. After the splash screen the app hangs with a white "your workspace" screen, the Metro window shows an error "TypeError: undefined is not a function"

<img width="982" alt="2022-03-30_08-59-08" src="https://user-images.githubusercontent.com/3321655/160771249-0153e743-16e4-4dde-b2aa-f8e8e7efa564.png">

### Environment Information:

- Rocket.Chat Server Version: 4.5.4
- Rocket.Chat App Version: 4.26.1
- Device Name: iPhone Simulator
- OS Version: IOS 14.5

### Steps to reproduce:

1. Check out and Whitelabel the Single-Server branch
2. Compile for IOS
3. App won't run due to this error

### Expected behavior:

The app should work

### Actual behavior:

See above

### Additional context:

XCode 12.5.1
npm: 6.14.13
node: 14.17.1
CocoaPods: 1.11.3

**Comment by MuRF2** [comment]
I have the same problem for the Android build.

**Comment by diegolmello** [comment]
We updated `single-server` branch to 4.26.2.
Can you try again?

**Comment by jacotec** [comment]
@diegolmello Unfortunately still the same in 4.26.2 :-(

A patch/hotfix will be highly appreciated, so we can finally compile this version. :-)

**Comment by diegolmello** [comment]
@jacotec I tested here it worked just fine.
Are you sure you did everything right?

**Comment by mikerogerz** [comment]
Same issue here as well, on Android. Also unable to see where the origin of the issue is within the metro window.

**Comment by diegolmello** [comment]
I had an issue like that on the update to 4.26.1 and it took me a while find the reason, as it's too vague.
Let's see if someone else from the team is able to reproduce it.

**Comment by seregasoft** [comment]
Same issue on single-server branch 4.26.2 on Android and iOS.

iOS simulator:

```
 DEBUG  [bugsnag] Loaded!
 ERROR  [TypeError: _userPreferences.default.setBoolAsync is not a function. (In '_userPreferences.default.setBoolAsync(_localAuthentication.BIOMETRY_ENABLED_KEY, isBiometryEnabled)', '_userPreferences.default.setBoolAsync' is undefined)]
```

**Comment by diegolmello** [comment]
Yes, that's the issue I had the other day and it's there still 🤔 
We don't need to call async functions anymore.
I'm going to submit a PR with a fix in a sec.

**Comment by MuRF2** [comment]
After a fresh pull, the android app works again.

**Comment by jacotec** [comment]
Works for me as well! Thanks, @diegolmello
