### ISSUE TITLE
iOS recent build has broken client certificate functionality

### ISSUE THREAD

**Issue by ispcolohost** [RocketChat/Rocket.Chat.ReactNative#3994]
### Description:

I unfortunately do not have the exact prior version of the iOS Rocket.Chat app to report as my userbase is mostly set to auto update and all have begun breaking, including my own phone and tablet.  I know 4.25.0.29369 worked though.

We operate an on-prem Rocket.Chat server, but I should make it clear that this issue is occurring before any packets are exchanged with the server.  The on-prem server has a valid CA-issued (Sectigo) SSL cert on it.  Separate from that system, an Apache web server exists on the public internet with an interface on the WAN, and in the DMZ where the Rocket.Chat server lives.  The Apache server also serves the same CA-issued SSL certificate.  The server is configured to do client certificate validation, so requests must arrive with a client cert issued by our CA for it to permit them through.

Our staff who would like to interact with the system from mobile devices are issued a client SSL certificate via an internal certificate authority.  The results in staff being given a password protected PKCS#12 format file.  In iOS Rocket.Chat prior to what I think it at least 30766 and 30850 (it was known to still work in 4.25.0.29369), staff would click "Apply Your Certificate" on the screen where you enter your workspace URL, select the p12 file, give the pass phrase, then put our server's domain name and connect.  It would connect through the proxy and prompt for user/pass, the user would be connected because the requests would arrive with the client cert and be allowed through the reverse proxy.

With at least 30766 and newer, but perhaps some other version after 29369 if there was one, the client certificate is no longer sent.  The result is you enter the workspace URL, click connect, and receive "Oops!  An SSL error has occurred and a secure connection to the server cannot be made."  tcpdump on the server side shows no client certificate being sent, so the connection fails.

Our Android users have not encountered this; I had one check version and they're on 4.26.1.30852.

### Environment Information:

- Rocket.Chat Server Version: 3.12.0
- Rocket.Chat App Version: 4.26.1.30850
- Device Name: Apple iPad Pro
- OS Version: 15.4 (but had been 15.3.x when problem began)

### Steps to reproduce:

1. Have the web server in front of Rocket.Chat require  client certificates, and "Apply Your Certificate" on the initial screen of the iOS App 4.26.1.30850.
2. Enter your workspace URL
3. Click Connect

### Expected behavior:

App sends client certificate with the request, server permits it, connection succeeds.

### Actual behavior:

tcpdump on web server target side shows request coming in without client certificate, it requires one so the connection fails, app reports "Oops!  An SSL error has occurred and a secure connection to the server cannot be made."

### Additional context:

Version 4.25.0.29369 had been working.

**Comment by gerzonc** [comment]
Hi @ispcolohost! This is a known issue that's been worked on #3992 and we will release a patch containing it!
