### ISSUE TITLE
have document?pod is null and can not install by iOS. npm install node_modules is error!what can I do?

### ISSUE THREAD

**Issue by 13559953270** [RocketChat/Rocket.Chat.ReactNative#4004]
### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name: 
- OS Version: 

### Steps to reproduce:

1. 
2. 
3.

**Comment by GleidsonDaniel** [comment]
Follow the issue template please. :)
Thanks.
