### ISSUE TITLE
Execution failed for task ':app:processBugsnagE2eFossReleaseManifest'

### ISSUE THREAD

**Issue by Abhishekpatel123** [RocketChat/Rocket.Chat.ReactNative#4008]
### Environment Information:

- Rocket.Chat Server Version:4.5.0 
- Rocket.Chat App Version: 4.24
- Device Name: Mobile
- OS Version: 2004.4lts

### Expected behavior:
I am building APK 

### Actual behavior:
I am building APK for android in React Native CLI but during the building process. I am getting errors:
```
Execution failed for task ':app:processBugsnagE2eFossReleaseManifest'.
 Bugsnag: Your AndroidManifest.xml is missing one or more of
  apiKey/versionCode/buildUuid/versionName/package, which are required to upload to bugsnag.
  apiKey=null
  versionCode=999999999
  buildUUID=beab08fe-8a94-4edf-bb62-ff84eef7bd8f
  versionName=4.24.0
  applicationId=com.8chat
```

![Screenshot (470)](https://user-images.githubusercontent.com/68077909/161380000-0b2e9a36-92f0-4b88-858b-7e89e7079d57.png)

### I have followed this https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3422 but it's not working

Thank you advance

**Comment by yoshida-git-ai** [comment]
I have a similar error message

**Comment by diegolmello** [comment]
You need to add your Bugsnag API Key or remove Bugsnag
