### ISSUE TITLE
[Solved] Unable to login to any Rocket.Chat server using iOS build 4.26.2.30993

### ISSUE THREAD

**Issue by homberger** [RocketChat/Rocket.Chat.ReactNative#4017]
### Description:

Suddenly I am unable to connect to any Rocket.Chat Server, even the open one.

### Environment Information:

- Rocket.Chat Server Version: any version
- Rocket.Chat App Version: 4.26.2.3993 from Apple AppStore
- Device Name: iPhone SE 2020 MX9T2ZD/A
- OS Version: iOS 15.4.1

### Steps to reproduce:

1. Open Rocket.Chat app on iPhone
2. Try to connect to open workspace or any server address

### Expected behavior:

Show login form

### Actual behavior:

App tries to connect forever. No error message. No timeout.

### Additional context:

App language is german.

https://user-images.githubusercontent.com/681335/161733219-7628ee9f-8ee2-4fe6-823a-b28759cd8b9c.MP4

**Comment by diegolmello** [comment]
Can you try deleting and reinstalling again?

**Comment by homberger** [comment]
@diegolmello 
After reinstalling the app I was able to connect to any workspace again. I lost all configured servers, which is sad. I can live with that, though.  :)

Thank you!
