### ISSUE TITLE
Application crashes when dragging URL in pinned messages menu

### ISSUE THREAD

**Issue by MHFDoge** [RocketChat/Rocket.Chat.ReactNative#4032]
### Description:

Ran across this bug the other day, not quite sure that it's intended behavior. "Dragging" a URL in the pinned messages menu causes the application to crash.

### Environment Information:

- Rocket.Chat Server Version: 4.6.0
- Rocket.Chat App Version: 4.26.2.30995
- Device Name: Samsung Galaxy S21 Ultra
- OS Version: Android 12

### Steps to reproduce:

1. Pin a message containing a link to a room.
2. From mobile, navigate to the room's pinned messages menu.
3. Hold the link part of the pinned message and drag outside of its normal selection area.
4. Release your finger from the screen.
### Expected behavior:

Unknown, anything other than what it does now which is crash.

### Actual behavior:

The application crashes.

### Additional context and information:
Attached is a video as well as a picture of the stacktrace as I unfortunately could not copy the text from said trace.
https://user-images.githubusercontent.com/46448580/162214209-c7ad66ba-2f2e-4353-8290-4dc1a2c43f86.mp4
![Screenshot_20220407-084439_Market Feedback Agent.jpg](https://user-images.githubusercontent.com/46448580/162214070-6b96fee1-0be0-4ea6-8e73-fd1c724e6cf1.jpg)

**Comment by diegolmello** [comment]
I was not able to reproduce it
