### ISSUE TITLE
Emoji format in notifications

### ISSUE THREAD

**Issue by ahmedibrahim404** [RocketChat/Rocket.Chat.ReactNative#4068]
### Description:
When sending any messages containing emojis, it's not parsed when showed in notifications
![80df6d8a-6709-44be-b22d-8c05c3053ac7](https://user-images.githubusercontent.com/34144004/164024101-252cb0f0-be42-4017-88c8-5ff8a91128d1.jpeg)

### Environment Information:

- Rocket.Chat Server Version:Latest
- Rocket.Chat App Version:Latest
- Device Name: Samsung
- OS Version: Android

### Steps to reproduce:

1. Send any message containing an emoji
2. Wait for a notification to deliver, and see how it appears in it

### Expected behavior:
The emoji text should be parsed to emoji image

### Actual behavior:
The emoji appears in plain text

**Comment by diegolmello** [comment]
We can't display custom emojis there.
