### ISSUE TITLE
Cannot login(join) to open workspace on ios with https

### ISSUE THREAD

**Issue by LugovayaOksana** [RocketChat/Rocket.Chat.ReactNative#4072]
### Description:
I have a server using http. After building the release version, I can log in using my server. But I can't join the official open workspace. This issue only affects ios. On android I can use http and https, but on ios I can't use https. 
When I click on the "Join our open workspace" button, the loader appears and nothing else happens. The app gets stuck on the first screen and won't move to the second screen.

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version: 4.26.2
- Device Name: iPhone 12
- OS Version:  15.4.1

### Steps to reproduce:

1. Open app.
2. Click on "Join our open workspace"

### Expected behavior:

After pressing the "Join our open workspace" button, a second screen should open.

### Actual behavior:

When I click on the "Join our open workspace" button, the loader appears and nothing else happens.

<p align="cpa">
  <img src="https://user-images.githubusercontent.com/47504845/164163045-eeb555e0-3209-44fe-9cc9-2f66339613b6.jpg" width="200" title="hover text">
</p>

**Comment by diegolmello** [comment]
Hey. Are you building from `develop` branch?

**Comment by LugovayaOksana** [comment]
Yes. I am building from develop branch. On android i can join to open workspace with https://open.rocket.chat
On ios I cant do this. Nothing happens when I click to button, to join to open workspace

**Comment by LugovayaOksana** [comment]
> Hey. Are you building from `develop` branch?
Yes. I am building from develop branch. On android i can join to open workspace with https://open.rocket.chat/
On ios I cant do this. Nothing happens when I click to button, to join to open workspace
