### ISSUE TITLE
Can we sync Rooms chat when we receive a notification

### ISSUE THREAD

**Issue by skhizerabass** [RocketChat/Rocket.Chat.ReactNative#408]
I have noticed that if we open a notification . Server takes sometime to load that message in a room. Is there any solution to sync it once we get the notification . 
Thank you

**Comment by skhizerabass** [comment]
I want it to sync at a time I receive the notification

**Comment by diegolmello** [comment]
@skhizerabass It's already in sync. If you've received a notifications you don't have a opened connection anymore. When you tap on it, app opens a new connection then it requests room's messages.
