### ISSUE TITLE
Channel mentions are not rendered as expected if the slug startsWith an underscore

### ISSUE THREAD

**Issue by debdutdeb** [RocketChat/Rocket.Chat.ReactNative#4081]
### Description:

The title ^

### Environment Information:

- Rocket.Chat Server Version: Open Server (so, 4.6.1)
- Rocket.Chat App Version: 4.26.1.30852
- Device Name: poco m4 pro
- OS Version: android 11

### Steps to reproduce:

1. create a channel with a name that starts with '_', e.g. '_testofsomething'
2. mention the channel on a message, e.g. 'please join #_testofsomething'

### Expected behavior:

On web client:

![image](https://user-images.githubusercontent.com/76006232/164712623-d139a0d1-8590-4916-9fb3-506e30f42377.png)

### Actual behavior:

On mobile client:

![IMG_20220422_174716](https://user-images.githubusercontent.com/76006232/164712758-82e9b1a0-1163-468b-b61a-3b6abb373a6b.jpg)

**Comment by aleadco** [comment]
Try disabling the message parser, remember https://github.com/RocketChat/Rocket.Chat/issues/23080
