### ISSUE TITLE
(RC experimental) Emoji typing errors

### ISSUE THREAD

**Issue by aleadco** [RocketChat/Rocket.Chat.ReactNative#4109]
RC mobile: 4.26.2.30995
![20220422_202406.jpg](https://user-images.githubusercontent.com/35962168/165004710-59afedbe-d6f4-461e-86df-f20c01e67ed0.jpg)

RC mobile experimental: 4.27.0.31805
![20220422_202808.jpg](https://user-images.githubusercontent.com/35962168/165004760-bbf1b118-bbcf-499e-be6f-0b2d15597200.jpg)

**Comment by diegolmello** [comment]
Let's focus on the issue on the other repo, since it's a markdown issue
