### ISSUE TITLE
install dependency error

### ISSUE THREAD

**Issue by pipipapi** [RocketChat/Rocket.Chat.ReactNative#4110]
when i run yarn command , this error occur below:

➜  Rocket.Chat.ReactNative git:(develop) yarn
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[##########################################################################################################################################################] 2386/2388

error Couldn't find match for "1264ac7b1c13d9be3e2f67eec6702a3132f4fac2" in "refs/heads/improve/remove-edited-indicator,refs/heads/master,refs/tags/v2.0.1,refs/tags/v2.0.2,refs/tags/v2.1.0,refs/tags/v2.2.0,refs/tags/v2.2.1,refs/tags/v2.2.2,refs/tags/v2.3.0,refs/tags/v4.1.2,refs/tags/v4.1.3,refs/tags/v4.1.4,refs/tags/v4.2.0,refs/tags/v4.2.1,refs/tags/v4.2.2,refs/tags/v4.2.3,refs/tags/v4.2.4,refs/tags/v4.3.0,refs/tags/v4.3.1,refs/tags/v4.3.3,refs/tags/v4.3.4" for "https://github.com/RocketChat/commonmark-react-renderer.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
➜  Rocket.Chat.ReactNative git:(develop)

why?

**Comment by GleidsonDaniel** [comment]
Follow the issue template please. Thanks.
