### ISSUE TITLE
IoS notification count will not reset

### ISSUE THREAD

**Issue by skadefro** [RocketChat/Rocket.Chat.ReactNative#4151]
### Description:
Today rocket chat suddenly refuse to set notification count for rocket chat to 0.
I depend heavily on this, so in frustration I uninstalled rocket chat, and installed it again.
After logging in, it still showed 0 notification, but after opening the app and closing it again, it's again stuck in showing 1 notification even thou everything is showing as read, both in the app, and if i access rocket chat in browser on my PC.
### Environment Information:

- Rocket.Chat Server Version: 4.6.3
- Rocket.Chat App Version: 4.27.0.31974
- Device Name: Ipad
- OS Version: IoS 15.4.1

### Actual behavior:
![Image (1)](https://user-images.githubusercontent.com/4155937/166099341-132baf0a-324c-47fc-bc69-4f41f722e9ff.jpeg)
![Image](https://user-images.githubusercontent.com/4155937/166099346-548983a6-3db9-48bb-9875-b95237c9b2d5.jpeg)
![Image (2)](https://user-images.githubusercontent.com/4155937/166099343-418ce1c8-b668-4bbb-8ca8-4107c8fbf088.jpeg)

**Comment by phriedrich** [comment]
I see the same behavior. Did not happen before 4.27.0

**Comment by diegolmello** [comment]
Hey. It's on our radar and it could have been introduced on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/3958
The backend is in charge of sending the unread count to us. We just display it.
So it could be something on their side as well.
We need to evaluate.

**Comment by phriedrich** [comment]
Possible that these are related. It just occurred directly after (auto-) updating the client to 4.27.0.

**Comment by GleidsonDaniel** [comment]
I think I know what happens hahaha.
If the person has 0 badges the logic does not happen (because 0 === false) and they always have a fixed badge. 
:)
