### ISSUE TITLE
User Status always online

### ISSUE THREAD

**Issue by saadqbal** [RocketChat/Rocket.Chat.ReactNative#416]
-Rocket.Chat server version: 0.67.0
- Remote Mongodb with Replication enabled
--
**My Rocket chat version is 0.67.0**

I have setup a remote Mongodb and enabled Replication on it
The user shows Status online even if the user logs out
or even if the app is completely deleted from the phone.

I haven't made any changes to the server code.

Can anyone help?

**Comment by diegolmello** [comment]
@saadqbal Does it happen on the web too?

**Comment by saadqbal** [comment]
Yup. On the web too

**Comment by diegolmello** [comment]
This issue is related to the [server repo](https://github.com/RocketChat/Rocket.Chat).
I'm closing this issue.

Can you open it there or check if anyone is suffering from the same behaviour?
Thanks!
