### ISSUE TITLE
App does not load

### ISSUE THREAD

**Issue by DieMichii** [RocketChat/Rocket.Chat.ReactNative#4165]
### Description:

If you want to open the Android App there is just a "lädt..." ("loading...") screen. Sometimes it helpes if you close and restart the app, but not always. The problem appears on different Android devices with different Android versions.

### Environment Information:

- Rocket.Chat Server Version: **will be added soon**
- Rocket.Chat App Version: newest available in the Play Store
- Device Name: several
- OS Version: several Android

### Steps to reproduce:

1. open the App

### Expected behavior:

The App is loaded and shows the chats

### Actual behavior:

There is just a loading screen.

### Additional context:

Using self hostet Rocket Chat

**Comment by diegolmello** [comment]
Hey, @DieMichii.
That's not enough information.
Can you elaborate?

As testing, can you uninstall your app completely and try again?
You can create an account on our community server to test it: https://open.rocket.chat

Thanks!
