### ISSUE TITLE
Animated GIFs from Photos on iOS upload as JPGs and are static.

### ISSUE THREAD

**Issue by fc757** [RocketChat/Rocket.Chat.ReactNative#4178]
We've been having an issue with animated gifs and Rocket.Chat. If you upload a photo in the iOS Rocket.Chat application from Photos, it uploads as a JPG and is not animated.

If you save the GIF from Photos to your iCloud drive and upload it from Files it is uploaded as a GIF and it animates properly.

If you use Safari on iOS and upload from Photos, it animates as expected and is uploaded a GIF. The aspect ratio for images is also a lot better in Safari as opposed to the App. See below:

![safari](https://user-images.githubusercontent.com/4654695/167313324-f41b5f55-1068-45a5-8758-c16942474517.jpg)
![ios](https://user-images.githubusercontent.com/4654695/167313326-7ee4a32d-6683-4c41-a689-771c26ea2ea4.jpg)

Please let me know if there is any information I can provide to help troubleshoot and hopefully resolve the issue.

**Comment by stefanandres** [comment]
I've noticed the same. This actually was working before the code rebuild for the ".heic pictures are not being shown on non-iOS devices" feature happened.
