### ISSUE TITLE
File sharing cannot be used for uploading in the IOS APP. show error uploading

### ISSUE THREAD

**Issue by wlsdk0125** [RocketChat/Rocket.Chat.ReactNative#4179]
File sharing cannot be used for uploading in the IOS APP. show error uploading
But it can use the choose file function to upload
![image](https://user-images.githubusercontent.com/50854371/167365340-e3c9b2a8-ad43-4710-8bb5-637e0441f0f4.png)

**Comment by diegolmello** [comment]
Can you try uploading on https://open.rocket.chat?
