### ISSUE TITLE
[NEW] When clicking on #referenced-channel, go to the channel view OR the channel info view

### ISSUE THREAD

**Issue by dudanogueira** [RocketChat/Rocket.Chat.ReactNative#4201]
### Description:

When you click on a referenced channel (eg. #support), you will be directed to the info page of that channel. This was decided as a safe place to direct, as the user may or may not be on that channel already, or may or may not have permission to enter it.

It would be great to have the best of both: If the user is already on that channel, it will be directed to the channel directly. 
Otherwise, when the user isn't on that channel, it will be directed to the channel info page.

### Environment Information:

- Rocket.Chat Server Version: 4.7.0
- Rocket.Chat App Version:  4.28.0
- Device Name: Android
- OS Version: Xiaomi Latest

### Steps to reproduce:

1. make sure you are not on #channel-test
2. post a message anywhere with a reference to #channel-test
3. click on #channel-test
4. you should be presented with the channel info view
5. join the channel
6. go back to the message posted in step 2
7. click again on a reference to #channel-test

### Expected behavior:

You should be directed to the channel

### Actual behavior:

You are directed to the channel info view again, adding 1 unnecessary "tap" between you and the desired channel

### Additional context:

This will improve UX, as you are expecting to go directly to the channel, if you are already on that channel.

**Comment by sven-thiele** [comment]
This is extremly useful when you have communities expanding into other channels where there may be higher value information / engagement or indeed direct them to messages in an easy to follow manner

**Comment by debdutdeb** [comment]
> This is extremly useful when you have communities expanding  
I saw this and immediately knew who the commenter was 🙈

**Comment by sven-thiele** [comment]
> I saw this and immediately knew who the commenter was 🙈

Am I that obvious!!!

**Comment by sven-thiele** [comment]
Whoop - yes. Thanks everyone. This will make a big difference to user experince.
