### ISSUE TITLE
Generating the release AAB

### ISSUE THREAD

**Issue by Salmankhan033** [RocketChat/Rocket.Chat.ReactNative#4209]
I generate the release AAB but which Abb I will upload to store.
there are many abb files generated ?

<img width="578" alt="Screenshot 2022-05-20 at 1 55 17 PM" src="https://user-images.githubusercontent.com/58082294/169496762-62ce75cd-6ef5-4bb1-93f3-9f5375d7af5b.png">

**Comment by GleidsonDaniel** [comment]
Follow the issue template please and read the docs: https://developer.rocket.chat/mobile-app/mobile-app-white-labelling

Tks
