### ISSUE TITLE
Can't build simulator iOS in Mac air m1

### ISSUE THREAD

**Issue by sonvp** [RocketChat/Rocket.Chat.ReactNative#4212]
My Setup

App Version: 4.28.0
Mac Air M1.
[x ] I have tested with the latest version
[x ] I can simulate the issue easily.

My command use build it.

rm -rf node_modules
yarn
cd ios
arch -x86_64 pod deintegrate && npx pod-install
yarn ios

Current Behavior

Can't build simulator for ios. It show errow below.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/8717317/169675788-888bed51-61d7-4896-965d-07a4d01123e2.png">

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/8717317/169676036-90ea4819-96d7-4dbc-b40b-496c1cd6c247.png">

**Comment by diegolmello** [comment]
I run it with Rosetta and without `arch -x86_64` on my M1.
Working fine.
