### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code.

### ISSUE THREAD

**Issue by zohaib319** [RocketChat/Rocket.Chat.ReactNative#4293]
Hello RocketChat Developers, 

I am trying to white label the android and iOS applications from Rocket Chat. Android is working fine after all the implementation. 

I am running into a problem on iOS. I believe this is related to Bugsnag. Here is the log report. React Native source map is failing the upload process and is timing out.  

I have tried changing some configuration related to bugsnag source maps uploading. I disabled the source map upload in Build Phases, but it keeps on giving me the same error. I have no prior experience in react native and this is my first time working on a react native codebase. I have worked on iOS & Android Native and any help from your side is appiriciated.

ℹ Preparing upload of React Native source map (dev / ios)
› Reading source map "/var/folders/sz/jj5jd6j54kd505vxsyxvlk1h0000gn/T//bcd7e9d7452d009ff844f5acf22fb2f3-main.jsbundle.map"
› Reading bundle file "/Users/macbook/Library/Developer/Xcode/DerivedData/RocketChatRN-adkttzebukwzincfwduuaihsdgwi/Build/Products/Debug-iphoneos/main.jsbundle"
ℹ Applying transformations to source map
› Ensuring sourcesContent field is populated
› Stripping project root from sources
› Initiating upload to "https://upload.bugsnag.com/react-native-source-map"

 ERROR  The request timed out.

 Connection timed out

  at ClientRequest.<anonymous> (/Users/macbook/Rocket.Chat.ReactNative-develop/node_modules/@bugsnag/source-maps/dist/Request.js:190:21)
  at Object.onceWrapper (node:events:641:28)
  at ClientRequest.emit (node:events:527:28)
  at TLSSocket.emitRequestTimeout (node:_http_client:771:9)
  at Object.onceWrapper (node:events:641:28)
  at TLSSocket.emit (node:events:539:35)
  at TLSSocket.Socket._onTimeout (node:net:516:8)
  at listOnTimeout (node:internal/timers:559:17)
  at processTimers (node:internal/timers:502:7)

**Comment by GleidsonDaniel** [comment]
You need to add your Bugsnag API Key or remove Bugsnag.

**Comment by Salmankhan033** [comment]
I put the same API key I was used in the free trial account now it was expired.
The app runs on the simulator but can't build an archive 
see the image and help me, please!

<img width="965" alt="Screenshot 2022-06-08 at 7 36 04 PM" src="https://user-images.githubusercontent.com/58082294/172645825-733f125f-9705-473b-a407-f0b0dad5c191.png">

**Comment by zohaib319** [comment]
> You need to add your Bugsnag API Key or remove Bugsnag.

I have already added API key from bugsnag. This error is popping out with the api key added. Can you provide more information on how I can remove bugsnag completely from this project.

Thanks for you help. I appreciate your help on this.

**Comment by ravimaru2022** [comment]
I am still facing this issue while preparing archive file. Debug build works fine as expected but the release build replicate this issue in iOS platform.

**Comment by Salmankhan033** [comment]
> I am still facing this issue while preparing archive file. Debug build works fine as expected but the release build replicate this issue in iOS platform.

Add bugsnag API key if you didn’t pay then pay bugsnag then it will work

**Comment by ErickVal** [comment]
cant understood, we cant use trial version?
