### ISSUE TITLE
Android - Unread counter on icon not cleared

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.ReactNative#4296]
### Description:

When new message arrived, on desktop icon appears unread count.
When you go to the app from push notification, everything is ok, counter is removed from icon.
But when you go to the app direct from desktop icon, nothing change, unread counter is still visible, despite all messages were written.
This situation happens only on Android, on iOS is fine.

### Environment Information:

- Rocket.Chat Server Version: 4.3.3
- Rocket.Chat App Version: 4.27.1 (single-server branch)
- Device Name: All Android
- OS Version: All Android

### Steps to reproduce:

1. Receive messages on Android device
2. Unread messages count is visible on desktop icon
3. Go to the application direct through desktop icon
4. Unread messages count is still visible

### Expected behavior:

Unread messages count cleared and not visible

### Actual behavior:

Unread messages count is still visible

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1099#issuecomment-818713858
