### ISSUE TITLE
Is it ready for production?

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat.ReactNative#43]
Hi guys,
Thanks for all of this work.
What is the state of this project? Is it ready for production? I can't find any information about this in README.md

I found this repo accidentally (please pin it to organization for others)

**Comment by gdelavald** [comment]
@mnlbox Hey, this is still a work in progress, we are planning on releasing soon. We'll update the repo readme accordingly. 
Thanks for the interest :)

**Comment by mnlbox** [comment]
Thanks @gdelavald,
I really happy to see RC to move to ReactNative :+1: 
Is it possible to say about release date for first stable version?

**Comment by gdelavald** [comment]
We'll update the readme with the release and roadmap.

**Comment by cyclops24** [comment]
@gdelavald I can't see release and roadmap information in readme file. Are you sure?

**Comment by mnlbox** [comment]
@gdelavald, @ggazzo any news about roadmap?

**Comment by alexfdz** [comment]
+1
Waiting for the roadmap to evaluate the use if RC in our product.

@gdelavald @ggazzo Any timeline for the update?

**Comment by mnlbox** [comment]
@gdelavald one year later... :disappointed: :thinking:
