### ISSUE TITLE
Rocket.Chat not working in Yandex Browser

### ISSUE THREAD

**Issue by svartedauen** [RocketChat/Rocket.Chat.ReactNative#4326]
### Description:

Some employees of our company cannot enter the web version of the rocket chat through the Yandex browser. It just shows a gray screen. However, through firefox, chrome and chromium everything is fine.

### Environment Information:

- Rocket.Chat Server Version: 4.8.1
- Rocket.Chat App Version: -
- Device Name:  -
- OS Version: Windows and MacOS

### Steps to reproduce:

1. Go to yandex browser
2. Enter chat.sparm.com
3. Auth

### Expected behavior:

After auth we have chat rooms with welcome page

### Actual behavior:

After auth we have gray screen

### Additional context:

However, through firefox, chrome and chromium everything is fine.
At part of second we see chat rooms with welcome page, but then we see only gray screen.

**Comment by GleidsonDaniel** [comment]
This is a web issue and not a mobile app issue, open it again in the repo: https://github.com/RocketChat/Rocket.Chat

**Comment by svartedauen** [comment]
There is already such a ticket, thanks https://github.com/RocketChat/Rocket.Chat/issues/25600
