### ISSUE TITLE
Post extra step of yarn to set up android development environment in CONTRIBUTING

### ISSUE THREAD

**Issue by RcleydsonR** [RocketChat/Rocket.Chat.ReactNative#4341]
### Description:

It is necessary to run the `yarn start` command in another terminal before the `yarn android` command to have the application running in an android development environment, this step is not included in the contributing document: "[Setting up a development environment](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md)"

### Environment Information:

It isn't necessary, but it's important to point out that this is a necessary step to run in an android environment.

### Expected behavior:

After following the tutorial from the contributing guide, don't expect to face any problems running the android development environment.

### Actual behavior:

![image](https://user-images.githubusercontent.com/74625814/177234171-cb5b1ebf-622b-4f80-8164-83e9fe978b53.png)
Command hangs on 'Starting JS server...'

### Additional context:

When I was following the tutorial to upload the development environment, I faced a problem when trying to run in android emulator because the tutorial only suggests using the `yarn android` command, not specifying the need to run the `yarn start` command to start the metro which is the javascript bundler, and is needed to run the application.

**Comment by GleidsonDaniel** [comment]
It is not necessary to run `yarn start` before running `yarn android`.
Your terminal probably doesn't have "access" to open another terminal.
