### ISSUE TITLE
[BUG] Markdown render not correct

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat.ReactNative#435]
Hi guys, It seems markdown render not correct in React Native version.

- Your Rocket.Chat.Android app version:
#### Latest

- Your Rocket.Chat.iOS app version:
#### Latest

- Your Rocket.Chat server version:
#### 0.70.0-develop

- Device model (or emulator) you're running with:
#### LG Q6 - Android 7.1.1

send message contain markdown (for example `*hi* RC`) it's showing well in web version as a `bold` text but in React Native version it's showing simple.

**Comment by diegolmello** [comment]
#174
