### ISSUE TITLE
ios app can't play voice messages from android and ios app

### ISSUE THREAD

**Issue by wifidong** [RocketChat/Rocket.Chat.ReactNative#4350]
### Description:
The ios app cannot play the voice messages from the ios and android apps, but it can play the voice messages from the web page, but the time of the received voice messages is displayed incorrectly, all showing 0:00. This problem is normal for other client tests!

### Environment Information:

- Rocket.Chat Server Version:4.8.1
- Rocket.Chat App Version:4.28.0.33048
- Device Name: All ISO device tests fail to play voice messages
- OS Version: ios

### Steps to reproduce:

1. Android or ios Rocket.Chat app sends voice to another ios terminal
2. Play voice in ios Rocket.Chat app
3. At this time, the length of the voice message on the ios app side is displayed as 0:00  It is normal to view on the Android app side

ISO app Voice message display：
![苹果](https://user-images.githubusercontent.com/52428146/178096731-84694c9c-35ea-4444-90eb-504794f44ce2.jpg)

android app Voice message display：
![安卓](https://user-images.githubusercontent.com/52428146/178096848-185ab19a-7fb5-4312-bd4c-78d1d332ca20.jpg)

### Expected behavior:

At present, all other clients have been tested, and everything is normal when playing voice messages. Only the ISO app side has the problem that voice messages cannot be played.
### Actual behavior:
Hope to fix this
thank you very much！

**Comment by diegolmello** [comment]
@LevyCosta

**Comment by GleidsonDaniel** [comment]
@yatounoneko @wifidong 
A question about this error: Are you using the rocket server or a private server?

**Comment by yatounoneko** [comment]
> @yatounoneko @wifidong A question about this error: Are you using the rocket server or a private server?
@GleidsonDaniel Question about my private server, but i test the rocket server is normal. Just iOS client have this issues.... 
Not just audio, but video files as well.

**Comment by GleidsonDaniel** [comment]
> 

@yatounoneko  okay, just for confirm.
On the open server you can load video or audio, but on a private server you can't? (That's assuming you're on ios or ios.)

**Comment by yatounoneko** [comment]
> @yatounoneko okay, just for confirm. On the open server you can load video or audio, but on a private server you can't? (That's assuming you're on ios or ios.)

Yes, you're right. If you want to test, I can send my site link for you in open.rocket.chat messages or E-mail.

**Comment by GleidsonDaniel** [comment]
It can probably be a problem with the server, if you can send me the server link.
Just enter the rocket chat server and send me via DM.
daniel.silva my user.

**Comment by yatounoneko** [comment]
> It can probably be a problem with the server, if you can send me the server link. Just enter the rocket chat server and send me via DM. daniel.silva my user.

Alread sent a messages to open.rocket.chat. Thanks~

**Comment by bingovivi** [comment]
From 4.8.1 to 4.8.4 , This problem has always bothered me. This question has always bothered me. Did you solve this problem please? My ios can't play any audio.

请问你找到解决这个问题的方法吗？谢谢！

> > It can probably be a problem with the server, if you can send me the server link. Just enter the rocket chat server and send me via DM. daniel.silva my user.
> 
> Alread sent a messages to open.rocket.chat. Thanks~

**Comment by wifidong** [comment]
This problem has been fixed in the latest version 4.30

**Comment by yatounoneko** [comment]
> This problem has been fixed in the latest version 4.30

nope... 4.30 audio is fixed but video problem persist.

![IMG-20220928-WA0000](https://user-images.githubusercontent.com/22129910/192661042-6f284eb3-5511-4a56-86ca-446d4e39ce48.jpg)
