### ISSUE TITLE
Can't connect to RC through Gitlab Oauth 

### ISSUE THREAD

**Issue by Katsuyu** [RocketChat/Rocket.Chat.ReactNative#4354]
### Description:

Before upgrading to RocketChat v4.8.1 (previously in 4.4.X) we couldn't connect through Gitlab Oauth (gitlab self hosted) because of an issue (https://github.com/RocketChat/Rocket.Chat/issues/23613) that has been fixed on RC 4.5.2.
Now that we use RocketChar 4.8.1, we can connect through Gitlab Oauth on the desktop app but it is still impossible with iOS and Android app since it automatically redirect to gitlab.com instead of our own gitlab URL

### Environment Information:

- Rocket.Chat Server Version: 4.8.1
- Rocket.Chat App Version: 4.28.0.33046 (Android) /  4.28.0.33048 (iOS)
- Device Name: OnePlus 9 Pro / Iphone 11
- OS Version: Android 11 Oxygen OS build 11.2.8.8.LE15BA

### Steps to reproduce:

- Try to connect to a rocketchat instance that has a Gitlab Oauth with self hosted Gitlab
- Connect with Gitlab 
- Get stuck in the wrong gitlab url page

### Expected behavior:

Should be redirected to the login page of my self hosted gitlab instance.

### Actual behavior:

- Get stuck on this page to gitlab.com, instead of my self hosted gitlab URL.
![292381442_604801684290098_7750065793581607085_n](https://user-images.githubusercontent.com/38114297/178280821-e7056034-bf0a-4e32-8eea-1ae0fe06e2d3.jpg)

**Comment by NoxInmortus** [comment]
I have the issue as well on Gitlab CE 15.1 and RocketChat 4.7.4

**Comment by NoxInmortus** [comment]
Still not working on 4.8.2
