### ISSUE TITLE
Handle deleted messages

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat.ReactNative#436]
Hi guys, I'm trying to remove some message from web version but message still show in React Native version. I try to close and re-open app and logout and re-connect to server then after open my chat page message updated successfully. I think we need some real-time update check here.

- Your Rocket.Chat.Android app version:
#### Latest

- Your Rocket.Chat.iOS app version:
#### Latest

- Your Rocket.Chat server version:
#### 0.70.0-develop

- Device model (or emulator) you're running with:
#### LG Q6 - Android 7.1.1

- Steps to reproduce:
1. Do some chat
2. Remove from Web version
3. Message still there in React Native version

**/CC:** @ggazzo , @diegolmello

**Comment by diegolmello** [comment]
@mnlbox Your server delete messages completely (without showing "Message removed"), right?
That's a setting we're not following in the app yet.

**Comment by mnlbox** [comment]
@diegolmello Yes I think I delete message with these two scenario:
1. **purne message** button in rooms or channel
2. Through API (`clearHistory`)

I can check remove button on each message if you want man.

**Comment by mnlbox** [comment]
@diegolmello any news?

**Comment by mnlbox** [comment]
@diegolmello Thanks man :wink:
