### ISSUE TITLE
Android app crashing if the data becomes out of sync with the server

### ISSUE THREAD

**Issue by looeee** [RocketChat/Rocket.Chat.ReactNative#4368]
### Description:

I made an attempt to update to 5.0.0-RC7 earlier today. 
Before doing so I took a snapshot of my server. 
I completed the update and sent one message to a friend to confirm that it was working. The message contained this:

😮 

I then ran into some database migration issues and rather than try to solve them I decided to restore the old snapshot and go back down to 4.8.1, 

As part of  restoring that snapshot, the old database which doesn't contain this message was restored. 

After restoring, I opened the Android app. I can still see the 😮 message, and then there's a "Updating..." message as it checks the server, and then a hard crash and app closes. When I try to open the app again, it just crashes. The same for my friend who also saw that message. 

To overcome this I had to clear all data from the app and log in again. Now it seems to be working. 

### Environment Information:

- Rocket.Chat Server Version: 4.8.1
- Rocket.Chat App Version: 4.28.0

### Steps to reproduce:

1. Restore an old version of the database on the server
2. Open the app and attempt to access a now deleted message. 

### Expected behavior:

The data in the app should reflect the restored server data.

### Actual behavior:

Hard crash

**Comment by GleidsonDaniel** [comment]
https://open.rocket.chat/channel/react-native?msg=C3jGDhzsiCiin45fZ

**Comment by diegolmello** [comment]
You can also download Rocket.Chat Experimental on Google Play in the meantime

**Comment by looeee** [comment]
> Note: Version 5.0.0 it's in pre-release, it is expected that in a version that is not stable there will be bugs :)

I'm pretty sure this is nothing to do with the 5.0.0. The crashing was happening after I reverted to 4.8.1 and the database got out of sync.
