### ISSUE TITLE
App crashes on emojis and some image uploads

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat.ReactNative#4369]
### Description:

When some emojis or images are uploaded to a channel, if the channel is displayed on the Android app, it crashes completely. The only solution so far is to identify the offending emoji/image, delete it from the channel, and then issue  a "Clear Server Cache" on the Android app.

### Environment Information:

- Rocket.Chat Server Version: 5.0.0-develop (8838e5e20)
- Rocket.Chat App Version: 4.28.0.33046
- Device Name: Samsung Galaxy S20
- OS Version: Android 12 (One UI 4.1)

### Steps to reproduce:

1. Be in a conversation (tried on DM channel)
2. Post an emoji or upload an image
3. Try to access the conversation via the Android app
4. The app will crash

### Expected behavior:

The app should not crash.

### Actual behavior:

The app crashes:

![image](https://user-images.githubusercontent.com/14616851/179353026-e0c53e1e-5951-4bf8-9a22-29ef969b13bd.png)

**Comment by GleidsonDaniel** [comment]
Related: #4368
