### ISSUE TITLE
[Improvment] Show room Topic and Announcement in room info page

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat.ReactNative#437]
Hi guys,

It seems that now `Room Info` page is very empty (just showing time zone) I think add Topic and Announcement can be very useful there.

Thanks for your attention.

**Comment by diegolmello** [comment]
@mnlbox `Room Info` is different to direct and other room types.
Direct shows the user role and timezone.
Other room types shows description, topic and announcement.
![image](https://user-images.githubusercontent.com/804994/45486840-e3a09580-b732-11e8-8388-6ba73ead88f5.png)

**Comment by mnlbox** [comment]
@diegolmello why dm and other not same?
In web version we also have topic and announcment for dm?

**Comment by mnlbox** [comment]
@diegolmello Any idea?

**/CC:** @ggazzo
