### ISSUE TITLE
[BUG] Can't send voice message

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat.ReactNative#438]
Hi guys, I'm trying to send some voice message but app return this error to me:
```
Error uploading 1536826202864.aac
Try again
```

- Your Rocket.Chat.Android app version:
#### Latest

- Your Rocket.Chat.iOS app version:
#### Latest

- Your Rocket.Chat server version:
#### 0.70.0-develop

- Device model (or emulator) you're running with:
#### LG Q6 - Android 7.1.1

- Steps to reproduce:
1. Click voice message button in message (room) page
2. Click OK icon after record some voice
3. You can see that error now. :wink:

**Comment by diegolmello** [comment]
@mnlbox It's working here. Can you send your error stack?

**Comment by DiegoNascimento1** [comment]
I also have this error, someone managed to solve?
