### ISSUE TITLE
[Improvment] Keep single server up-to-date (merge/rebase code + config docs)

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat.ReactNative#439]
Hi guys,
[Single server branch](https://github.com/RocketChat/Rocket.Chat.ReactNative/tree/single-server) can be very useful for many people like me. I suggest to keep it up-to-date and merge/rebase main branch with that.
Also I think we need some extra info in ReadMe file because based on [ReadMe](https://github.com/RocketChat/Rocket.Chat.ReactNative#running-single-server):

> Running single server
> If you don't need multiple servers, there is a branch single-server just for that. ReadMe will guide you on how to config.

But I can't find any docs about this in wiki or ReadMe files.

**Comment by diegolmello** [comment]
@mnlbox There isn't much info to add at Readme, but it's there.
> Set your server URL in app.json

If you want to keep single server up-to-date, you can help us opening PRs to do it so.

**Comment by diegolmello** [comment]
@mnlbox single-server branch was just updated
