### ISSUE TITLE
Crash on ios 15.6

### ISSUE THREAD

**Issue by Salmankhan033** [RocketChat/Rocket.Chat.ReactNative#4411]
Installing on ios 15.6 or iPhone 8, then enter login credential then it crashed  

<img width="1236" alt="Screenshot 2022-08-05 at 8 01 26 PM" src="https://user-images.githubusercontent.com/58082294/183105223-a28fc2d2-b95d-43b6-9b84-3bbcee6c57e4.png">

**Comment by diegolmello** [comment]
Not enough info.
