### ISSUE TITLE
Log in bug: Having to uninstall app on IOS

### ISSUE THREAD

**Issue by artutava** [RocketChat/Rocket.Chat.ReactNative#4431]
### Description:

After logging in a workspace the chat works for a while. But it gets logged out randomly after some days, and when I try to recconect to the workspace, it starts loading forever. The only workaround is unninstalling and reinstalling the app.

### Environment Information:

- Rocket.Chat Server Version: 5.0.0-rc.12
- Rocket.Chat App Version: IOS 4.29.0.34197
- Device Name: IPHONE 12
- OS Version: IOS 15.4.1

### Steps to reproduce:

1. Install rocket chat on ios and connect to a self hosted server
2. Use it for a few days
3. Once it apparently logs out, it still sends notifications, but when you click on the notifications or open the app it will start in log in screen (form to fill workspace url)
4. After inserting the url it will load forever
5. Reinstalling the app solves the issue until it happens again...

**Comment by jeremyevans6** [comment]
This is a significant problem. Occurs on my UTD snap server + the current RN app.

**Comment by diegolmello** [comment]
> pointing to a recent release

@jeremyevans6 Recent release of mobile app or server?

**Comment by ankar84** [comment]
Confirm that issue but only for iOS.
Users make a lot of request about that, but only iOS users. 
I have no Android user request about that issue at all.
Reinstall of application form AppStore fix that issue.
Important details.
We have KeyCloak as OAuth2 authentication system.
Server version 4.8.2
RCRN app version 4.27



> But it gets logged out randomly after some days

This is by design. Check Admin UI - Accounts. Default 90 days as I remember it clear.
![image](https://user-images.githubusercontent.com/4023037/186851175-75d923fe-b6ce-4ef1-876a-d833e3321890.png)

**Comment by diegolmello** [comment]
Thanks for pointing that out.
We have some users on Open server reporting that on iOS as well.
Do you recall if it would happen prior to 4.27?

**Comment by ankar84** [comment]
> Thanks for pointing that out.
> We have some users on Open server reporting that on iOS as well.
> Do you recall if it would happen prior to 4.27?

No. 4.27 was first version where users start complying about that problem.
But we don't release every single version of our application, so if I remember right, previous our version before 4.27 was 4.23.

**Comment by ankar84** [comment]
4.30 still have that bug

**Comment by shevchukma** [comment]
I confirm frequent complaints with this problem on IOS. Rocket Chat version 4.8.6, client 4.30

**Comment by diegolmello** [comment]
I'll leave it open.
4.33 is going to be released end of November.
Let's keep an eye on it and please let us know in case it happens again.
