### ISSUE TITLE
No visible @interface for 'SecureStorage' declares the selector 'getSecureKey:'

### ISSUE THREAD

**Issue by FatihDursunUzer1** [RocketChat/Rocket.Chat.ReactNative#4443]
### Description:

I cloned Rocket-Chat Single Server branch when Rocket-Chat app version 4.22.0.
And I changed icons, app names etc...
I published the application to app store and google play store.
Then, I disconnect from rocket-chat single server branch and i pushed to my azure devops.
I pulled the project to other folder from my Azure Devops and i worked yarn and pod install. Then , i try build for ios. But compiler threw exception 
'/react-native/Libraries/Network/RCTHTTPRequestHandler.mm:136:34: No visible @interface for 'SecureStorage' declares the selector 'getSecureKey:''

and When i check my folders(my pushed folders and i pulled folders from azure devops) i saw RCTHTTPRequestHandler.m file is different from my other RCTHTTPRequestHandler.m.

I think source of the problem is .patch files. Because my pushed RCTHTTPRequestHandler.m includes .patch file codes but my pulled RCTHTTPRequestHandler.m not include .patch file codes.

Therefore, i runned postinstall command but i think it's not worked. Because my RCTHTTPRequestHandler.m folders are still different from each other

This is my pulled code from azure devops and i worked yarn and pod install
<img width="1435" alt="Screen Shot 2022-08-17 at 13 56 17" src="https://user-images.githubusercontent.com/60691319/185102061-0f891803-b781-4716-b792-3177f54388a3.png">

And this code is pulled from rocket-chat single server branch. This project is worked with any problems but other project threw exceptions.
![Screen Shot 2022-08-17 at 14 02 16](https://user-images.githubusercontent.com/60691319/185103066-5d4561b9-8584-4278-ac9a-944aa3a9d4d2.png)

How can ı fix this problem. Can you help me?

### Environment Information:

- Rocket.Chat Server Version: 4.5.2
- Rocket.Chat App Version: 
- Device Name: Macbook
- OS Version: Monterey 12.4, IOS Emulators(IPhone 12, IPhone 12 PRO)

### Steps to reproduce:

1. 
2. 
3.

**Comment by diegolmello** [comment]
Nothing we can do from here.
You need to use a newer version.
