### ISSUE TITLE
"Also send thread message to channel" option ignored on mobile app

### ISSUE THREAD

**Issue by krenuser** [RocketChat/Rocket.Chat.ReactNative#4453]
### Description:

**"Also send thread message to channel behavior**" option is ignored in mobile app when refreshing chat history.
I've selected not to display thread messages in a channel:
- in "My Account" settings (for my messages)
- in "Administration > Accounts > Default User Preferences" (for other's messages)

After that users have posted some messages to a thread.
Desktop app works fine and don't display these thread messages, still mobile app displays all of them in main channel.

Adding `"tshow": false` to the message structure in MongoDB doesn't fix the problem, messages are still displayed in main channel on mobile app.

### Environment Information:

- Rocket.Chat Server Version: 5.0.4
- Rocket.Chat App Version: 4.29.0.34199
- Device Name: HONOR View20 PCT-L29
- OS Version: Android 10

### Steps to reproduce:

1. Disable displaying thread messages through **Administration > Accounts > Default User Preferences**
2. Send any message to a thread

### Expected behavior:

Thread messages are not displayed in main channel (on any platform).

### Actual behavior:

Thread messages still displayed in mobile app (sometimes it happens after refreshing chat history with swipe up).

**Desktop app: (no any thread message in main channel)**
![bug_screen_1](https://user-images.githubusercontent.com/32645945/185788129-cf75d909-a459-4d7d-ba5d-34fe9f0ee930.png)

**Mobile app: (all thread messages are displayed in main channel)**
![bug_screen_2](https://user-images.githubusercontent.com/32645945/185788127-fc854d61-561f-4070-af82-33eb5bef0e6f.png)

### Additional context:

none

**Comment by CHerSun** [comment]
I've got the same problem - mobile app shows all thread messages in main chat. Tested this a lot today - looks like mobile app just ignores checkbox "also send to channel" and shows everything, unlike desktop.

**Comment by diegolmello** [comment]
Folks, I linked a PR there that's going to fix this issue. We're going to make sure it lands on next version of the app, coming out in the upcoming weeks.
