### ISSUE TITLE
Update profile fails

### ISSUE THREAD

**Issue by b90g** [RocketChat/Rocket.Chat.ReactNative#4467]
### Environment Information:

- Rocket.Chat Server Version: 5.0
- Rocket.Chat App Version: 4.29
- Device Name: Shiftphone
- OS Version: LineageOS 19.20220824-nightly (Android 12)

### Steps to reproduce:

1.  Click on profile
2.  Change name field
3.  Save

### Expected behavior:

Name changes in chat across sessions

### Actual behavior:

App confirms the changes were made successfully, but are not applied on the server.

### Additional context:

In a browser session i was able to change my Name. (so its not the server config, i believe.)

Can provide video demo  in CEST office times.

**Comment by diegolmello** [comment]
I can reproduce the issue.
I'm adding to next sprint.
Thanks for reporting.
