### ISSUE TITLE
Rocket.Chat iOS App, strange user/channel sort when sharing data

### ISSUE THREAD

**Issue by mrwee** [RocketChat/Rocket.Chat.ReactNative#4477]
### Description:

On iOS you can share/send pictures/text etc. via misc. installed apps. E.g. in Safari I can share the link to a website
![image](https://user-images.githubusercontent.com/6720774/187488757-c5969bc4-87f6-4604-ae1e-b0ec1055c532.png)
Sharing is done in multiple steps:

1) Select to share
2) Select e.g. Rocket.Chat
3) Select user/channel
4) Send the data

But at step 3 where I select user/channel the list is sorted in a very strange way. It does not follow the general sort method selected in the app. This is not very good user experience as it take a while to find what you're looking for and is quite confusing.

### Environment Information:
Server Setup Information:
    Version of Rocket.Chat Server:
    Deployment
    Version: 4.8.2
    Apps Engine Version: 1.32.0
    Node Version: v14.18.3
    Database Migration: 265 (August 10, 2022 9:09)
    MongoDB: 5.0.6 / wiredTiger (oplog Enabled)

Client Setup Information
    iOS App 4.29.0.34197
    Operating System: iOS 15.6.1

### Steps to reproduce:
1) Select to share from e.g. Safari
2) Select Rocket.Chat
3) Select user/channel. Now you see the strangely sorted list
4) Send the data

### Expected behavior:
As a user, I expect the same sorting/display methos as selected under "Display/Display, Display/Sort by, and Display/Group by"

### Actual behavior:
Cannot disclose as I'm not keen on sharing userlist here.

**Comment by diegolmello** [comment]
Hello.
The behavior on that view is to sort from newest to oldest showing last 20 chats, because it's usually where you're going to share to.
You can always use search to find other rooms.
