### ISSUE TITLE
@ mentions also lists user outside the channel / Direct Message

### ISSUE THREAD

**Issue by mrwee** [RocketChat/Rocket.Chat.ReactNative#4478]
### Description:

In the iOS App, Windows Desktop App as well as when browsing to the Rocket.Chat server, I can mention another user by starting with '@'.  My expectation is that this will bring up a list of users / user (If direct messaging), present in that channel / Direct Message.

However it brings up ALL users on the server, which does not make sense since they might not have access to that particular channel. From a user perspective it's confusing to see users who does not belong or have access.

### Environment Information:
Server Setup Information:
    Version of Rocket.Chat Server:
    Deployment
    Version: 4.8.2
    Apps Engine Version: 1.32.0
    Node Version: v14.18.3
    Database Migration: 265 (August 10, 2022 9:09)
    MongoDB: 5.0.6 / wiredTiger (oplog Enabled)

Client Setup Information
    iOS App 4.29.0.34197 /  Operating System: iOS 15.6.1
    Windows App: 3.8.9 (Windows 11)

### Steps to reproduce:

1. Go to any channel
2. Write @ and a letter. This will bring up a list of users matching that letter. It does mention "Not in channel" at users who are not members, but that's confusing.

### Expected behavior:

@ should only show members of the channel / Direct Message to minimize confusion and not compromize usernames which the user shouldn't be able to see.

### Actual behavior:

As stated in "Steps to reproduce"

**Comment by diegolmello** [comment]
Duplicated https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3681
