### ISSUE TITLE
Wrong link to meet in mobile app

### ISSUE THREAD

**Issue by Fedosds** [RocketChat/Rocket.Chat.ReactNative#4480]
### Description:

After creating a JITSI meeting link in the PC app, when opening the meeting invitation in the phone app, the link is invalid.
PC link: meet.company.com\user1xuser2
Link opens on phone: meet.company.com\user1%20x%20user2
The application inserts extra spaces in the link.

### Environment Information:

- Rocket.Chat Server Version: 4.8
- Rocket.Chat App Version: 3.8.9 on PC Win10, 4.29.0.34199 on Android

### Steps to reproduce:

1. User1 go to direct messages with User2
2. Click on Call --> Start video call
3. User2 in mobile app click to blue button "Click to join"
4. Opens mobile browser with wrong link 

### Expected behavior:

Opens correct link and start conversation

### Actual behavior:

![Screenshot_2022-08-31-10-49-07-320_chat rocket android](https://user-images.githubusercontent.com/63261657/187627649-516f31bc-a207-4c6e-8e4c-16b0e838d5d6.jpg)

> The conference ymm x fiva has not started yet

**Comment by mikailyusuf** [comment]
Hi @Fedosds, i have checked the issue you raised on

-  Rocket.Chat Server Version: 4.8

- Rocket.Chat App Version: 3.8.9 on PC Win10, 4.32.0.999999999 on Android,
