### ISSUE TITLE
You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without 'android:exported' property set. This file can't be installed on Android 12 or higher. See: developer.android.com/about/versions/12/behavior-changes-12#exported

### ISSUE THREAD

**Issue by Doan-RIOT** [RocketChat/Rocket.Chat.ReactNative#4481]
### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name: 
- OS Version: 

### Steps to reproduce:

1. 
2. 
3. 

### Actual behavior:

<img width="878" alt="Screen Shot 2022-08-31 at 17 42 21" src="https://user-images.githubusercontent.com/46195209/187660950-98027b44-d0df-4c44-a7f2-55ac28e6d2c2.png">

<img width="922" alt="Screen Shot 2022-08-31 at 17 42 56" src="https://user-images.githubusercontent.com/46195209/187660984-94d6a5b3-08cb-4e14-927a-88dd1f24aafc.png">

**Comment by Doan-RIOT** [comment]
Hope everybody help please

**Comment by Doan-RIOT** [comment]
<img width="1195" alt="Screen Shot 2022-08-31 at 17 51 25" src="https://user-images.githubusercontent.com/46195209/187662404-13bd2061-4510-48bb-b8d4-92ccddfca696.png">

**Comment by diegolmello** [comment]
I tried to fix this issue, but I couldn't find the filter.
That's why I set 30 for now.
It's not breaking anything.
If you find it, contribute with a PR please.
