### ISSUE TITLE
Link preview and Autolinker not working in mobile client.

### ISSUE THREAD

**Issue by pendragon86** [RocketChat/Rocket.Chat.ReactNative#4482]
### Description:

The behavior of embedded link previews is not the same between the regular browser client and the official mobile (Android/iPhone) client. What I’m seeing is that when I paste a directly-linked image (ending in .jpg or similar), the browser client will display a preview for it properly. In the mobile client, there will be no preview shown.

The Autolinker function is similarly inconsistent, and changing the Regex field doesn’t seem to have any effect. A good example is direct links for https://i.redd.it/ images. These are hyperlinked and previewed properly on the desktop client, no issues there. However, on the mobile client these links are NOT hyperlinked and no preview is shown. I’ve tried editing the RegEx field in Settings to account for i.redd.it links, nothing I do seems to make a difference. I’ve tried restarting the RocketChat instance after changing it, no difference.

SOME links do get a preview properly in the mobile client, but not direct image links. If I link http://dilbert.com/, for example, that gets a preview in the mobile client just fine. YouTube videos get an embed preview as well.

I'm mainly testing on my Android phone, but I've done a few side tests with an iPhone and run into the same problem. I have also tested with the browser client through Chrome on the Android phone, and it behaves as I would expect.

### Environment Information:

- Rocket.Chat Server Version: 4.8.3
- Rocket.Chat App Version: 4.29
- Device Name: Pixel 6 Pro
- OS Version: Android 13

### Steps to reproduce:

1. Go to a channel and post a direct url to an image. In my example, https://i.redd.it/t2mul61342l91.jpg
2. In the browser client, observe that the url is hyperlinked and a link preview is shown.
3. In the mobile client, observe that the url is bare, no hyperlink, no link preview shown.

### Expected behavior:

I should expect link preview and autolinker behavior to be consistent between the browser and mobile clients.

**Comment by ankar84** [comment]
Confirm that issue with current reproduce steps on 4.30 release too

**Comment by svartedauen** [comment]
Hello, we are reproducing the same issue for our internal use. Our domain links like https://i.sparm.com/ are not clickable active links. Looking forward to a fix. Chat became difficult to use.

Our version of chat server is 4.8.0, iOS 4.31.0.35532

**Comment by svartedauen** [comment]
Added: This bug reproduced on links that start with https://i.{DOMAIN}
