### ISSUE TITLE
 Suddenly Gray Screen on Android App - 4.29.0.34199

### ISSUE THREAD

**Issue by gabeyww** [RocketChat/Rocket.Chat.ReactNative#4486]
### Description:

I’ve suddenly started getting just a gray SSO screen on my Android app for my self-hosted RocketChat server. I’ve cleared the data, completely removed and reinstalled, installed on other Android devices… nothing. It works fine on web browsers on the Android device and Windows. I’m sure I mucked up a setting somewhere, but I have reset all setting pages to their default and still get this.

I have the logs on debug mode and they don't appear to log any errors when this happens (logs attached).

It temporarily flashes the workspace, then goes to a blank "SSO" screen.

### Environment Information:

- Rocket.Chat Server Version: 5.02 on Ubunto 22.04 installed via snap and accessible via Apache reverse proxy
- Rocket.Chat App Version: 4.29 and up
- Device Name: Several different Android devices
- OS Version: 12/13

### Steps to reproduce:

1. Launch web app
2. Logon to the server (https://chat.gabeww.com)
3. Briefly see the workspace, then sent to a gray screen

### Actual behavior:

![image](https://user-images.githubusercontent.com/78660920/188142329-6062661c-0664-4a42-b458-155c8fdeb153.png)

[2022 09 22 RocketChat.txt](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/9477834/2022.09.22.RocketChat.txt)

**Comment by diegolmello** [comment]
Hey.
"Suddenly" after updating mobile or server?
4.29 is out for some time.

**Comment by gabeyww0** [comment]
Nevermind, y'all, I figured it out! It has to do with initially having TOTP enabled, then disabling it.  I turned it back on with all of the options disabled and this stops happening:

![image](https://user-images.githubusercontent.com/78660920/188151760-58c94a0c-295f-469c-b0a4-a0530df77aa4.png)

Thanks for your response @diegolmello
