### ISSUE TITLE
Slash commands do not work with server version 5.1.0

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat.ReactNative#4491]
### Description:

Hello Devs.

After upgrading the Server to 5.1.0 slash commands do not work anymore. No /shrug, no /poll, no /remind. Did not test more slash commands. It's odd because I have configured to servers and the one running 4.8.3 runs slash commands just fine.

### Environment Information:

- Rocket.Chat Server Version: 5.1.0
- Rocket.Chat App Version: 4.30.0
- Device Name: Pixel 6
- OS Version: Android 12

### Steps to reproduce:

1. Go to a channel
2. Type /shrug
3. Nothing happens.

### Expected behavior:

ASCII shrug appears.

### Actual behavior:

Nothing happens.

**Comment by himpierre** [comment]
Would be nice to have a release with this fix @diegolmello. 

cheers, t.

**Comment by diegolmello** [comment]
We're about to merge it and, yeah, it's going to land the release ;)
