### ISSUE TITLE
iOS app — Oops! too many HTTP redirects

### ISSUE THREAD

**Issue by fvlasie** [RocketChat/Rocket.Chat.ReactNative#4494]
### Description:

When trying to log in to my server I get the message: Oops! too many HTTP redirects

### Environment Information:

- Rocket.Chat Server Version: 4.8.3
- Rocket.Chat App Version: 4.29.0.34197
- Device Name: iPad
- OS Version: 15.6.1

### Steps to reproduce:

1. Open the Rocket.Chat iOS app
2. Enter workspace URL
3. Tap Connect

### Expected behavior:

Workspace is opened

### Actual behavior:

I get the message: Oops! too many HTTP redirects.

### Additional context:

I have set up the nginx reverse proxy on the server according to the directions on the install page.  https://docs.rocket.chat/quick-start/environment-configuration/configuring-ssl-reverse-proxy

I also have another reverse proxy redirecting traffic from my external IP. Both ports 80 and 443 are forwarded directly from Apache to nginx. I have also added ws forwarding.

Both the web and desktop apps work without any issues.

**Comment by diegolmello** [comment]
This is a very common configuration, so it's very likely a misconfiguration on your server.
