### ISSUE TITLE
Can't login in mobile app since 5.1.0 server version

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#4496]
### Description:

We updated our test environment to latest 5.1.0 release version and now we can't login to that server from mobile.
We use LDAP integration (Active Directory).
We try both - default login form and our KeyCloak login - result is the same - all works perfect on computer and nothing happens on mobile app.

### Environment Information:

- Rocket.Chat Server Version: 5.1.0
- Rocket.Chat App Version: 4.29.0.34197
- Device Name: iPhone 13
- OS Version: 15.6.1

### Steps to reproduce:

1. Setup LDAP and Rocket.Chat integration
2. (Optional) Setup KeyCloak OUath2 provider integrated with same LDAP
3. Try to login with LDAP account via default form and via KeyCloak login form in mobile app
4. Nothing happens

### Expected behavior:

Successful login via default form and via KeyCloak

### Actual behavior:

Nothing happens

### Additional context:

Server logs
{"level":50,"time":"2022-09-06T05:35:34.423Z","pid":10,"hostname":"7182fc806afc","name":"LDAP","err":{"type":"Error","message":"User not found","stack":"Error: User not found<br>    at server/lib/ldap/Manager.ts:163:11<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"User not found"} 
{"level":50,"time":"2022-09-06T05:35:34.432Z","pid":10,"hostname":"7182fc806afc","name":"System","msg":"Exception while invoking method login 'User not found [403]'"}

**Comment by dudanogueira** [comment]
Hi! Thanks for pointing this out.

Our team is looking into it and we should have a fix on the way soon :)

**Comment by ankar84** [comment]
Really strange, but now both authentication variant works perfect. Looks like it was problem on our side, maybe my collogue did some temporary changes.
So, closing this.
