### ISSUE TITLE
How to get all messages that are failed to send?

### ISSUE THREAD

**Issue by prieyudaarvis** [RocketChat/Rocket.Chat.ReactNative#4505]
### Description:

Sometimes message are failed to send due to connection and something. I want to create auto-send feature which needs to populate all not sented messages, so I need to populate it first. But how I do it?

### Environment Information:

- Rocket.Chat Server Version: 
- Rocket.Chat App Version: 4.23.0
- Device Name: * 
- OS Version:  *

### Steps to reproduce:

1. open many chat rooms
2. sent a messages (turn off internet or something, we need to make it failed to sent)

**Comment by diegolmello** [comment]
I think you could start by understanding how the JS SDK works.
It should be able to, after reconnected, send the failed requests again.
