### ISSUE TITLE
[feature request] add notifcation support for FOSS variant on F-Droid by adding ntfy support

### ISSUE THREAD

**Issue by foss-** [RocketChat/Rocket.Chat.ReactNative#4507]
**Currently**

As per https://f-droid.org/en/packages/chat.rocket.android/ info `Note: This FOSS build variant currently lacks any push notification support.`

Sadly this also applies to the Google PlayStore (retrieved via Aurora Store) version when running it on LineageOS 19.1. Assuming this is related to the missing Google technology (FCM) which is currently a requirement as per https://docs.rocket.chat/guides/mobile-guides/push-notifications#configuring-for-android

**Expected**

If Rocket.Chat supported https://github.com/binwiederhier/ntfy notifications should be possible without Google or Apple which would be a big win and allow for notifications even for the F-Droid Rocket.Chat app.

### Environment Information:

- Rocket.Chat Server Version: 5.1.0
- Rocket.Chat App Version: 4.30.0
- Device Name: Xiaomi 10T Lite
- OS Version: LineageOS 19.1

### Expected behavior:

Notifications

### Actual behavior:

No notifications

**Comment by ankar84** [comment]
Related to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3241
