### ISSUE TITLE
Notifications not sent to all devices 

### ISSUE THREAD

**Issue by Salmankhan033** [RocketChat/Rocket.Chat.ReactNative#4509]
Hi!
There is an issue in notifications I follow documentation and put all data but did not send notifications to all devices.
as you see in the first image the alert is only sent to three or 4 devices.
and personally, I install it on 2 devices but they didn't receive any notifications.
please see the certificate data that it's good, without this data have the same issues then I put the certificate's data now also same issues.
we use our own server.
I don't know where we are doing mistakes Please help.
Thanks!

<img width="770" alt="Screenshot 2022-09-08 at 10 49 35 AM" src="https://user-images.githubusercontent.com/58082294/189044465-2386e9f0-0eef-4a92-8995-1c1d0687772d.png">
<img width="391" alt="Screenshot 2022-09-08 at 10 47 31 AM" src="https://user-images.githubusercontent.com/58082294/189044504-7be826f7-5013-4a93-bcb6-a3f2dc268c9d.png">

**Comment by diegolmello** [comment]
Hey @Salmankhan033.
I think your configuration is wrong on iOS.
You're not supposed to paste the whole command on `apn passphrase (and dev)`, but actually entering the passphrase you created while running the command.

**Comment by Salmankhan033** [comment]
@diegolmello The. certificate format is good?
Do they have line breaks?
