### ISSUE TITLE
Android app can't play audio messages

### ISSUE THREAD

**Issue by alpresci** [RocketChat/Rocket.Chat.ReactNative#4534]
### Description:

after the latest android app update (9th of September, v 4.30.0.35195) the Huawei P30 phones we have (3 different ones) cannot play audio messages anymore, not even those recorded by the user on the phone.
The Desktop apps (on several PC and MAC) CAN listen to those same audio messages.
On the phones they seem empty or 0 seconds long.

Before the latest android app, the phones never had a problem.

I tried to clear the local server cache and to restart the app on every phone but it did not help.

thank you for your help!
Alex

### Environment Information:

- Rocket.Chat Server Version: 4.8.2
- Rocket.Chat App Version:  4.30.0.35195 (Android)
- Device Name:  Huawei P30
- OS Version: android 11

### Steps to reproduce:

1. in rocket.chat either from the phone or desktop app record and send a voice message

### Expected behavior:

phone should be able to listen to the audio

### Actual behavior:

the desktop version can play it normally, the phone version always sees it as 0:00 long EVEN the phone that has sent it.

### Additional context:

all the previous Android installations never showed this problem. Nothing was changed on the server side.

**Comment by diegolmello** [comment]
Hey @alpresci.
Does your workspace URL ends in a port? `something:3000`?
We have a task on the backlog to fix it.

If not, can you send me a test user on your workspace? https://open.rocket.chat/direct/diego.mello

**Comment by diegolmello** [comment]
@alpresci we're quite aware of it and we're going to focus on it on next sprint.
We're going to update this issue with a PR soon.

**Comment by stmaick5** [comment]
I dont think there is another solution than moving the instance to the standard https port 443. That is what worked for me
When you change the port in the proxy settings of your apache/nginx vhost to 443 instead of 8443 then the audio messages work again. Of course all users have to join the new domain in the app :(

**Comment by alpresci** [comment]
> @alpresci we're quite aware of it and we're going to focus on it on next sprint. We're going to update this issue with a PR soon.

thank you!
I cannot change the port on the server so I would be very happy to receive good news. thank you again  for the help!
