### ISSUE TITLE
IOS client can't play video

### ISSUE THREAD

**Issue by wifidong** [RocketChat/Rocket.Chat.ReactNative#4535]
### Description:
Playing video messages on the iOS side keeps showing loading and cannot be played. The same video message is played normally on both Android and PC.

### Environment Information:

- Rocket.Chat Server Version:5.12
- Rocket.Chat App Version:4.30
- Device Name: iPhone Pro 13 max
- OS Version: ios

Play video on iOS
https://user-images.githubusercontent.com/52428146/190700965-89f4e38a-51ed-4b2f-bdcf-4ec04a4d3332.MP4

Play video on Android
https://user-images.githubusercontent.com/52428146/190699094-162ae241-cfe2-4e1d-8736-3a618d35d3c7.mp4

Play video on PC
https://user-images.githubusercontent.com/52428146/190700841-fb9b222e-9faa-4a11-9fb3-8ef2a707bccd.mp4

**Comment by diegolmello** [comment]
Can you reproduce it on https://open.rocket.chat?

**Comment by wifidong** [comment]
> Can you reproduce it on https://open.rocket.chat?

ok i'll test it
