### ISSUE TITLE
Audio messages with non-unique filenames are broken in Android and iOS

### ISSUE THREAD

**Issue by pbirkants** [RocketChat/Rocket.Chat.ReactNative#4548]
### Description:

If multiple messages with audio files having the same filename have been sent, the first file is repeated in all of the messages.

### Environment Information:

- Rocket.Chat Server Version: 5.1.2
- Rocket.Chat App Version: 4.30.0
- OS Version: Android 11 and iOS

### Steps to reproduce:

1. Via web interface, record a voice message (or upload audio file).
2. When prompted, leave the default filename "Audio record.mp3", and send.
3. Repeat steps 1-2 several times with different messages (different durations) and with or without changing filenames.
4. Try to play back voice messages in mobile app.

### Expected behavior:

Each unique message is playable and displays the correct duration.

### Actual behavior:

Web interface works as expected:
![rocket_web](https://user-images.githubusercontent.com/370651/191590166-9fb6ebc2-817d-4bdf-9952-53cb4ca74943.png)

In the mobile app, for each pair of unique filenames, only the first message is displayed and playable:
![rocket_android](https://user-images.githubusercontent.com/370651/191590211-1115d730-dbed-4b00-97a4-812317c6011e.png)
(note: the duration displayed for the second message differs from the first, but still is wrong and the same audio file is played)

### Additional context:

This behaviour was observed both in Android and iOS versions, and also reproduced on a fresh server install.
The problem also occurs across different channels and senders in the same server, but not across multiple servers.
Voice messages recorded in mobile app work fine, because the filename contains timestamp.

**Comment by diegolmello** [comment]
Related to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4534

We've been working on both issues.
Thanks for reporting.
