### ISSUE TITLE
App Performance Problem on newer Android Versions (12 & 13)

### ISSUE THREAD

**Issue by sgaebel** [RocketChat/Rocket.Chat.ReactNative#4551]
### Description:

The RocketChat Android App is very slow/unresponsive on newer Android Versions. I have two users of my companies whitelabel build on Pixel 6 / Android 13 with this issue, though according to this [thread](https://forums.rocket.chat/t/android-rocket-chat-sluggish-after-update/14832) it seems to affect Android 12 as well.

### Environment Information:

- Rocket.Chat Server Version: 5.1
- Rocket.Chat App Version: 4.30.0.33
- Device Name: Google Pixel 6
- OS Version: Up-to-date (at time of writing) Android 13

### Steps to reproduce:

1. Start App
2. Login to the server
3. After a few actions (scrolling or entering a channel) the app starts to slow down massively and stops being responsive
4. Minimising the app and then switching back to it briefly resets the "timer" until it starts to slow again

### Expected behavior:

3. App might lag a bit if content is being loaded from the server, but should otherwise have no trouble to quickly react to user input.

### Actual behavior:

See above: the app starts to slow down massively and stops being responsive.

### Additional context:

In our previous (ancient v4.23, yes we should do more regular updates...) build this issue didn't exist. Also, [as mentioned at the top](https://forums.rocket.chat/t/android-rocket-chat-sluggish-after-update/14832), the issue seems to exist for regular non-whitelabel builds as well.
I'm posting this as an issue as it affects useability and to make sure the problem is on your radar, but feel free to close if this is the wrong place for it.

**Comment by diegolmello** [comment]
Fixed on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4536
