### ISSUE TITLE
App very slow on android 13

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat.ReactNative#4558]
### Description:

Hello Devs. Just upgraded my device to android 13 (pixel 6). Now the app is very slow. It even freezes sometimes. The app starts ok but when opening a channel the message slide in with jerky movement. Giphys entered with app giphy stop moving after playing a few times.

### Environment Information:

- Rocket.Chat Server Version: 5.1.3
- Rocket.Chat App Version: 4.30.0
- Device Name: Pixel 6
- OS Version: Android 13

### Steps to reproduce:

1. Open App
2. Open channel
3. Messages slide in with very jerky movement

### Expected behavior:

Everything runs smooth.

### Actual behavior:

Everything is very slow.

**Comment by diegolmello** [comment]
Fixed on #4536

**Comment by himpierre** [comment]
@diegolmello Thanks! Question. Could we have a minor release for that? App is more or less unusable at the current state. 

cheers, t.
