### ISSUE TITLE
Messages attributed to wrong user

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#4559]
### Description:

Under certain circumstances, messages sent by the app user are shown as originating from another user.

### Environment Information:

- Rocket.Chat Server Version: 5.1.3
- Rocket.Chat App Version: 4.30.0.35195
- Device Name: Huawei ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

You need two different users.

1. In a desktop browser, open Rocket.Chat and login with one of the users. Navigate to an arbitrary channel.
2. Open the Rocket.Chat app and login with the other user. Navigate to the same channel as in step 1.
3. Submit a message from the app.
4. Prepare another message in the app, but do not submit it right now.
5. Send a message from the desktop browser.
6. Submit the message prepared in step 4. It is important to submit the message before the message from step 5 is displayed in the app.
7. Submit another message from the app.

### Expected behavior:

The messages from steps 4, 6, and 7 are shown as originating from the user that uses the app.
The message from step 5 is shown as originating from the user that uses the desktop browser.

In the desktop browser this works as expected:

![image](https://user-images.githubusercontent.com/404840/192111153-a9bce9d9-e8dd-4744-aeca-47b5005ac453.png)

### Actual behavior:

The message from step 4 is attributed to the app user.
The messages from steps 5, 6, and 7 are attributed to the user of the desktop browser.

![image](https://user-images.githubusercontent.com/404840/192111176-a8e3b462-006f-49f1-92f6-87152bfd91ab.png)

When navigating to the channel list and then back to the channel, the messages are shown correctly:

![image](https://user-images.githubusercontent.com/404840/192111229-8a465da8-8b0b-440d-8b41-3b6975e336cb.png)

**Comment by diegolmello** [comment]
Thanks for reporting, @paulchen.
We're going to try to reproduce it.
