### ISSUE TITLE
Sharing files audio or video from a direct Messages to another user

### ISSUE THREAD

**Issue by ricardorvieira** [RocketChat/Rocket.Chat.ReactNative#4563]
### Description:

Sharing messages with attachments or audio files between direct rooms, It only loads the Rocket.Chat logo but doesnt open the file.

### Environment Information:

- Rocket.Chat Server Version: 5.1.2
- Rocket.Chat App Version: 4.30
- Device Name: IOS
- OS Version: iOS 16

**Comment by GleidsonDaniel** [comment]
closed by: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5363
