### ISSUE TITLE
RC removing from local network hyperlinks Backslashes 

### ISSUE THREAD

**Issue by hw-p** [RocketChat/Rocket.Chat.ReactNative#4566]
### Description:

RC removing from local network hyperlinks Backslashes 

### Environment Information:

- Rocket.Chat Server Version: 5.13
- Rocket.Chat App Version: latest or browser
- Device Name: localhost
- OS Version: W10 - OS not relevant

### Steps to reproduce:

1. post local network path
2. example `\\Server\logs$\`
3. RC show message in Channel \Serverlogs$\ - RC removed backslashes

### Expected behavior:

1. post local network path
2. example  `\\Server\logs$\ `
3. RC show message in original form `\\Server\logs$\`

### Actual behavior:

1. post local network path
2. example `\\Server\logs$\`
3. RC show message in Channel \Serverlogs$\ - RC removed backslashes

### Additional context:

as workaround Im using INLINE Code

I am not sure, if this is configuration problem or RC bug.

**Comment by hw-p** [comment]
prolly same Issue #26907

**Comment by diegolmello** [comment]
Yes, it's an issue on Markdown parser. You can track progress there.
