### ISSUE TITLE
Status messages are cut off with ellipsis "..."

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#4578]
### Description:

Status messages are cut off with an ellipsis "...", so you can't view the entire message on mobile.

### Environment Information:

- Rocket.Chat Server Version: 5.1.2
- Rocket.Chat App Version: Version 4.32.0 Updated on Sep 28, 2022
- OS Version: Android 12.0

### Steps to reproduce:

1. Have someone set their status to something like, "This is a very important message, please remember to do the dishes"
2. Try to read the important message on mobile.

### Expected behavior:

You should be able to read their entire status message by tapping into their name, maybe even by holding over the status text, etc.

### Actual behavior:

Impossible to read the entire message. It's cut off.

![image](https://user-images.githubusercontent.com/6295044/192929265-12e50782-bf12-4877-85f1-35825c270c9f.png)
![image](https://user-images.githubusercontent.com/6295044/192929275-f9fda155-f3f7-40f4-a097-8a3acbd41868.png)
![image](https://user-images.githubusercontent.com/6295044/192929289-03ad4941-301c-499a-9570-c93d41310fbb.png)

**Comment by ankar84** [comment]
Agree. Should be the way to get full status even it is very long. In a profile only for example.
