### ISSUE TITLE
Empty message is displayed when it contains only a link

### ISSUE THREAD

**Issue by steve-todorov** [RocketChat/Rocket.Chat.ReactNative#458]
- Your Rocket.Chat.Android app version: ####
Experimental version (2018-09-19)

- Your Rocket.Chat server version: ####
0.69.1

- Device model (or emulator) you're running with: ####
Android 7.1

- Steps to reproduce:
1. Create a testing channel
2. Send the following message: [ abc ] ( somewhere ) <- remove white space
3. Results in a message which contains nothing in the android app. However, if you open it on PC or the web chat - it properly shows the link

**Comment by diegolmello** [comment]
@steve-todorov Thanks for reporting :)

**Comment by marceloschmidt** [comment]
@diegolmello that's the issue I also reported on our channel :)
