### ISSUE TITLE
Build failed with expo module core

### ISSUE THREAD

**Issue by Mrezagolbaba** [RocketChat/Rocket.Chat.ReactNative#4584]
![image](https://user-images.githubusercontent.com/9501814/193137456-105f8d3e-79d5-4357-a70c-c554f89d8a47.png)

### Description:

I have an issue when I want to run application with yarn iOS 

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version: 4.31.0
- Device Name: iOS
- OS Version: 10.15.7
- Xcode version: 12.4 (12D4e)

**Comment by diegolmello** [comment]
I'm pretty sure it's your Xcode version.
Update to 13+ (I'm using 13.4)

**Comment by Mrezagolbaba** [comment]
I can't do that because I use a Macbook pro. 2012 and my final code is 12.4 (12D4e), is there any solution?
