### ISSUE TITLE
Can't Load App on Android 12 Emulator

### ISSUE THREAD

**Issue by amanahmedrn** [RocketChat/Rocket.Chat.ReactNative#4587]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeExperimentalPlayDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:experimentalPlayDebugRuntimeClasspath'.
   > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.7.0.
     Required by:
         project :app > project :react-native-jitsi-meet
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.7.0.
         > Could not get resource 'https://github.com/RocketChat/jitsi-maven-repository/raw/master/releases/org/jitsi/react/jitsi-meet-sdk/3.7.0/jitsi-meet-sdk-3.7.0.pom'.
            > Could not GET 'https://raw.githubusercontent.com/RocketChat/jitsi-maven-repository/master/releases/org/jitsi/react/jitsi-meet-sdk/3.7.0/jitsi-meet-sdk-3.7.0.pom'.
               > raw.githubusercontent.com
      > Could not resolve org.jitsi.react:jitsi-meet-sdk:3.7.0.
         > Could not get resource 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.7.0/jitsi-meet-sdk-3.7.0.pom'.
            > Could not GET 'https://www.jitpack.io/org/jitsi/react/jitsi-meet-sdk/3.7.0/jitsi-meet-sdk-3.7.0.pom'. Received status code 401 from server: Unauthorized

### Environment Information:

-"react-native": "RocketChat/react-native#0.68.2",
- Device Name:  Pixel 4 API 31 Android 12

### Steps to reproduce:

1. git clone  https://github.com/RocketChat/Rocket.Chat.ReactNative.git rchat
2.  cd rchat
3. yarn
4. yarn android

**Comment by ydhnwb** [comment]
How you aolve this problem @amanahmedrn ? I have samw issue
