### ISSUE TITLE
Image upload show in mobile app has lower quality than in web

### ISSUE THREAD

**Issue by liv1n9** [RocketChat/Rocket.Chat.ReactNative#4589]
### Description:
Uploaded image show in mobile app has smaller size than the one in web

### Environment Information:

- Rocket.Chat Server Version: 4.8.6
- Rocket.Chat App Version: 4.16.2
- Device Name: Samsung Galaxy Note 9
- OS Version: Android 10

### Steps to reproduce:

1.  Upload an jpg file with size 5MB from mobile app
2.  Uploaded image show in mobile is low quality. Save this image to mobile, the saved file size is 1KB
3.  Go to web and see the same uploaded image. Image in web has better quality and it's size after downloading is 1MB

### Expected behavior:
Uploaded image show in mobile has same quality versus in web

### Actual behavior:

Uploaded image show in mobile has lower quality than in web

**Comment by diegolmello** [comment]
Hey. You should always try the latest version available.
We're on 4.31.0 already.
