### ISSUE TITLE
Push notifications did not received in IOS 

### ISSUE THREAD

**Issue by Salmankhan033** [RocketChat/Rocket.Chat.ReactNative#4599]
Notifications work on android devices but did not on IOS mobile
I am using iPhone 7 Plus for testing
App version:4.31.0
server Version: 5.1
[Webmin](https://www.webmin.com/)
Please see the below screenshots, where I did a mistake 
<img width="1066" alt="Screenshot 2022-10-08 at 1 02 17 AM" src="https://user-images.githubusercontent.com/58082294/194644674-03837c19-89ad-4ec1-994c-eb6b42bdbc0a.png">
<img width="570" alt="Screenshot 2022-10-08 at 1 02 01 AM" src="https://user-images.githubusercontent.com/58082294/194644678-c6f6d813-2e1a-4c58-8a45-44d6aaf379db.png">
<img width="758" alt="Screenshot 2022-10-08 at 1 01 51 AM" src="https://user-images.githubusercontent.com/58082294/194644683-43ba7dde-fb2d-4d93-b94c-51e101a72afd.png">
<img width="866" alt="Screenshot 2022-10-08 at 1 01 22 AM" src="https://user-images.githubusercontent.com/58082294/194644684-0b6626a7-3115-4eae-84ce-9305d83ccac6.png">
<img width="750" alt="Screenshot 2022-10-08 at 1 01 07 AM" src="https://user-images.githubusercontent.com/58082294/194644686-3cf6936a-db29-4125-ba3a-56e9f6292abc.png">
<img width="780" alt="Screenshot 2022-10-08 at 1 00 45 AM" src="https://user-images.githubusercontent.com/58082294/194644696-bc14b0e1-072d-4032-a5b9-b7d7a514d299.png">

**Comment by Salmankhan033** [comment]
@diegolmello Hi
without any solution/help, you close it :(

**Comment by diegolmello** [comment]
It's not an issue on the repo and you're flooding on all communication channels.
Keep it on a single thread and hire a dev  from #dev if you need.
Thanks.

**Comment by Nam-Anh-99** [comment]
@Salmankhan033 me too, Did you push successfully?

**Comment by Salmankhan033** [comment]
@Nam-Anh-99 yes, I was successfully set it

**Comment by Nam-Anh-99** [comment]
where did you go wrong?
![Screen Shot 2022-10-27 at 16 41 13](https://user-images.githubusercontent.com/69841173/198251081-9b664a5e-6e4f-464e-a43b-9df0f2b9dbb1.png)
![Screen Shot 2022-10-27 at 16 41 31](https://user-images.githubusercontent.com/69841173/198251087-d904c472-e286-4657-af3b-511d4530a249.png)

**Comment by Salmankhan033** [comment]
Off the production mode.
And test it hopefully it will work

**Comment by Salmankhan033** [comment]
You put already in right format.
--- BEGIN CERTIFICATE  etc is a part of key and certificate.
May be you did some things wrong on certification creations.
Contact me on Roct.Chat (userName: Salmankn033)or
salmankn033@gmail.com
I will help you.

**Comment by say2alihassan** [comment]
Hey bro did you receive notification? @Nam-Anh-99 @Salmankhan033 
I’m facing same issue

**Comment by say2alihassan** [comment]
Hi bro yes

**Comment by shakibgithub944** [comment]
![Longshot-20240306182127](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/108364116/59d032ca-f0b7-4884-830a-77ade80059b6)

1. Here i Can't get any push notification in ios.
2. Do i need to change https://gateway.rocket.chat gateway?

How I fix it? I'm suffering last 7 days with this problem

**Comment by say2alihassan** [comment]
No you don’t need to change anything
This is my mail contact me here
***@***.***

**Comment by shakibgithub944** [comment]
@say2alihassan  Bro i can't see you email here

![Uploading Screenshot 2024-03-06 at 7.59.17 PM.png…]()

**Comment by say2alihassan** [comment]
Can you please send you WhatsApp number?

**Comment by shakibgithub944** [comment]
8801817628246

**Comment by Salmankhan033** [comment]
> @Salmankhan033 Hay bro I'm getting same issue last 7 days. Can you help me please? I can't find you in rocketchat

 contact me here _salmankn033@gmail.com_ , I will help you.

**Comment by Salmankhan033** [comment]
> @say2alihassan @Salmankhan033 can you help me to solve the push notification?

yes.

**Comment by say2alihassan** [comment]
Sure
