### ISSUE TITLE
When the video call is connected, the screen will be blank

### ISSUE THREAD

**Issue by 337077418** [RocketChat/Rocket.Chat.ReactNative#4601]
When the video call is connected, the screen will be blank, and during the call between device A and device B, when device B exits and enters again, sometimes there will be three users A, B and B in the room

**Comment by diegolmello** [comment]
That's most probably a Jitsi issue.
I'll leave it open anyway.

**Comment by 337077418** [comment]
> 


in addition
I'm developing my own video-conference Android-App and using the jitsi-sdk. But I want to set the back camera of my Smartphone as default. The user can change it once the conference is launched, but my goal is to change it before the conference begins without user interactions.

I tried CameraCaptureController.java

@OverRide
protected VideoCapturer createVideoCapturer() {
String deviceId = ReactBridgeUtil.getMapStrValue(this.constraints, "deviceId");
String facingMode = ReactBridgeUtil.getMapStrValue(this.constraints, "facingMode");
return createVideoCapturer(deviceId, facingMode);
}

to this

@OverRide
protected VideoCapturer createVideoCapturer() {
String deviceId = ReactBridgeUtil.getMapStrValue(this.constraints, "deviceId");
String facingMode = ReactBridgeUtil.getMapStrValue(this.constraints, "facingMode");
return createVideoCapturer(deviceId, "environment");
}

---But it didn't work

.........................1......................
// Unconditionally express the desires/expectations/intents of the app and
// the user i.e. the state of base/media. Eventually, practice/reality i.e.
// the state of base/tracks will or will not agree with the desires.
dispatch(setAudioMuted(audioMuted));
dispatch(setCameraFacingMode(CAMERA_FACING_MODE.ENVIRONMENT));
dispatch(setVideoMuted(videoMuted));
----------2---------
// FIXME Technically, _VIDEO_INITIAL_MEDIA_STATE is a constant internal to the
// feature base/media and used in multiple files so it should be in
// constants.js. Practically though, VideoMediaState would then be used in
// multiple files as well so I don't know where and how to move it.
/**

Initial state for video.
@type {VideoMediaState}
*/
export const _VIDEO_INITIAL_MEDIA_STATE = {
available: true,
facingMode: CAMERA_FACING_MODE.ENVIRONMENT,
muted: 0,
---But it didn't work please！help help help

**Comment by diegolmello** [comment]
Probably fixed, since we changed the Android way to use Jitsi.
