### ISSUE TITLE
 I need to add a video call after A hangs up B and both parties exit the video room and return to the chat interface, what should I do?

### ISSUE THREAD

**Issue by 337077418** [RocketChat/Rocket.Chat.ReactNative#4620]
Please tell me, I need to add a video call after A hangs up B and both parties exit the video room and return to the chat interface, what should I do? I can't find any Jitsi callbacks that can handle this requirement

**Comment by GleidsonDaniel** [comment]
Do you want to create a video call automatically when both people leave a video call?

One point is that most of the time the call is still open, why not "go back" to the last call?
