### ISSUE TITLE
Add limit to number of characters user can enter in the status screen 

### ISSUE THREAD

**Issue by hakeem-gitstart** [RocketChat/Rocket.Chat.ReactNative#4624]
### Description:
User can enter an infinite amount of character in the status TextInput field 

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name: 
- OS Version: 

### Steps to reproduce:

1. Click on the Hamburger button  
2. On the Edit Status screen, click on your status
3. You can enter an unlimited number of text in the textInput field 

### Expected behavior:
User status should be limited to a certain amount of characters

**Comment by GleidsonDaniel** [comment]
Limiting is not correct, as there is no accepted standard for a number, for you 100 characters is enough, for other users it may be 1000 characters.

However, we are working on a solution to facilitate viewing when the message is too long.
