### ISSUE TITLE
[bug] Black screen on second call join

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat.ReactNative#4628]
### Description:

When user join second Jitsi call in a row - user gets black screen. And now way to exit call (except close the app)

### Environment Information:

- Rocket.Chat Server Version: 4.8.6
- Rocket.Chat App Version: 4.33.0.35817 (but 4.32 involved for sure and probably first version with issue)
- Device Name: Xiaomi Mi 9 SE
- OS Version: Android 11

### Steps to reproduce:

1. Go to chat A and click `Click to Join button` (that is a first call)
2. Stop first call
3. Go to chat B and click `Click to Join button` (that is a second call)
4. See black screen with no buttons

### Expected behavior:

Normal Jitsi call experience

### Additional context:

4.32 first version with that bug

**Comment by GleidsonDaniel** [comment]
Fixed on #4619

**Comment by ankar84** [comment]
my issue could be a duplicate of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4601 but there not clear description, so I'm not 100% sure.

**Comment by ankar84** [comment]
@GleidsonDaniel probably proper fix is https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4680
Am I right?

**Comment by ankar84** [comment]
@GleidsonDaniel actually #4619 [don't fix](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4619#issuecomment-1327012403) that black screen bug on a second call
Please test it on Android device on your side.

**Comment by diegolmello** [comment]
What about this?
