### ISSUE TITLE
app:processE2eFossDebugGoogleServices'

### ISSUE THREAD

**Issue by HBrites9** [RocketChat/Rocket.Chat.ReactNative#4645]
Hello im getting app:processE2eFossDebugGoogleServices and i alredy have the file....
![Screenshot from 2022-11-02 15-56-22](https://user-images.githubusercontent.com/77410712/199539482-5e75db44-6798-4f7c-b363-ee630fcc2351.png)

**Comment by diegolmello** [comment]
Follow issue template.
