### ISSUE TITLE
Links without schema are not clickable and no preview is generated

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#4674]
### Description:

Links without schema are not clickable and no preview is generated.

### Environment Information:

- Rocket.Chat Server Version: 5.3.0
- Rocket.Chat App Version: 4.32.0.35745
- Device Name: Huawei ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Write a message containing a link without schema (e.g. [github.com/RocketChat/Rocket.Chat/](https://github.com/RocketChat/Rocket.Chat/) ).

### Expected behavior:

The link is clickable and a preview is generated, as it is the case when the link contains a schema:

![Screenshot_20221110_202044](https://user-images.githubusercontent.com/404840/201187004-76971219-b0b9-4edf-9ff0-76e2f3a1f1f3.jpg)

### Actual behavior:

The link is not clickable and no preview is generated:

![Screenshot_20221110_202242](https://user-images.githubusercontent.com/404840/201187510-03c405e8-67f6-45ec-a35f-a94b0638a218.jpg)

I would expect this to work as the link looks like a link that is clickable.

### Additional context:

This may be somehow related to the behaviour of the web app, cf. https://github.com/RocketChat/Rocket.Chat/issues/27235

In the web app, the link is clickable, but no preview is generated as well.

**Comment by diegolmello** [comment]
Thanks for opening.
Yes, it's the same issue, because we're using the same markdown parser.
Fixing it should fix both clients.
I'm closing this issue, because the web folks are in charge of the parser.
