### ISSUE TITLE
Files are not deleted from mobile app

### ISSUE THREAD

**Issue by limpep** [RocketChat/Rocket.Chat.ReactNative#4676]
### Description:
When a user deletes a media from the desktop app/website and access it via the mobile app. The file is still there and available on the users device

### Steps to reproduce:
Turn off Allow Save Media to Gallery

Upload a file
Delete it on the desktop/web 
Open up the mobile app
Click on files in the Room that the media was deleted in
You can still see the file there

### Expected behavior:

Files should be deleted on all instances.

### Actual behavior:
Media is still visible in the file section of the room.

### Server Setup Information:
 Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-52-generic x86_64)
Version
5.2.0
Apps Engine Version
1.35.0
Node Version
v14.19.3
Database Migration
281 (November 9, 2022 10:50 AM)
MongoDB
4.4.15 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (08f03cc9d)
Branch: HEAD

**Comment by diegolmello** [comment]
Hey.
If I got it right, it's an issue related to history sync and not specifically for files. Is that it?

Because every time you delete any message from other clients, they should get deleted on mobile as well.
Attachments shouldn't be different.

Let me know if I missed something.
Thanks!

**Comment by limpep** [comment]
Hi. both file and sync history is available to view on Android app after deleting them from the desktop/webiste..

**Comment by diegolmello** [comment]
@limpep Ok, so it's not a file issue.
How can we reproduce it?
It could happen because of specific settings.

Can you reproduce it on https://open.rocket.chat?

Send me a test user on your server at https://open.rocket.chat/direct/diego.mello, if it's possible for us to try it there.

**Comment by limpep** [comment]
I have a fresh install using snap.

Upload a file to a room
Delete it on the desktop/web
Open up the mobile app (Android)
Click on files in the Room that the media was deleted in
You can still see the file there
