### ISSUE TITLE
Whitelabel single-server android build fails

### ISSUE THREAD

**Issue by marc-simon** [RocketChat/Rocket.Chat.ReactNative#4681]
### Description:
I'm trying to build a whitelabel version. I've followed the instructions to build but i've ran into an error when I tried to run
`yarn android-whitelabel com.custom.customchat`

>  ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found

It seems to be an error related to iOS although I'm trying to build for android but it looks like something needed.

It could be related to this but couldn't find any clear solution for this.
https://github.com/facebook/react-native/issues/34102

I've checked the package.json and it's using a custom react-native version ("react-native": "RocketChat/react-native#0.68.2",)

Can you please guide me on how to solve this error.

### Environment Information:

- Rocket.Chat Server Version: NA
- Rocket.Chat App Version: single-server (commit hash: 1548c1535)
- Device Name: MacBook Pro (Intel)
- OS Version: Ventura 13.0.1 (22A400)

### Steps to reproduce:

follow Whitelabel documentations
do yarn
do yarn android-whitelabel com.custom.customchat

### Expected behavior:

Should be compiled successfully

### Actual behavior:

> Task :expo-modules-core:buildCMakeDebug
C/C++: ninja: Entering directory `/Users/marc/Documents/custom/custom-app/node_modules/expo-modules-core/android/.cxx/Debug/1l654r42/armeabi-v7a'
C/C++: In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.cpp:3:
C/C++: In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
C/C++: ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
C/C++: In file included from ../../../../src/main/cpp/ExpoModulesHostObject.cpp:3:
C/C++: In file included from ../../../../src/main/cpp/ExpoModulesHostObject.h:5:
C/C++: In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
C/C++: ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
C/C++: In file included from ../../../../src/main/cpp/JavaScriptModuleObject.cpp:3:
C/C++: ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
C/C++: In file included from ../../../../src/main/cpp/JNIInjector.cpp:3:
C/C++: In file included from ../../../../src/main/cpp/JSIInteropModuleRegistry.h:6:
C/C++: ../../../../src/main/cpp/JavaScriptModuleObject.h:7:10: fatal error: 'react/bridging/LongLivedObject.h' file not found
C/C++: In file included from ../../../../src/main/cpp/MethodMetadata.cpp:1:
C/C++: ../../../../src/main/cpp/MethodMetadata.h:8:10: fatal error: 'react/bridging/LongLivedObject.h' file not found

> Task :expo-modules-core:buildCMakeDebug FAILED

**Comment by diegolmello** [comment]
It's a C++ issue. Not iOS.
It's working on our laptops and CI.

**Comment by marc-simon** [comment]
Okay. Thanks.
Worked for me after deleting node_modules and doing a fresh install. 

Closing the issue.

**Comment by arun1989** [comment]
@marc-simon  Can you plz tell me which android version you used i am facing same issue but still same issue after trying all the possible ways .

<img width="1323" alt="Screenshot 2022-12-22 at 7 44 48 AM" src="https://user-images.githubusercontent.com/12507057/209137167-9c8c9d7c-cafc-4095-a5e2-27598272ec7a.png">
