### ISSUE TITLE
Task 'experimentalPlayRelease' not found in root project 'RocketChatRN'.

### ISSUE THREAD

**Issue by Salmankhan033** [RocketChat/Rocket.Chat.ReactNative#4686]
In the android directory, I run  `./gradlew experimentalPlayRelease` but can't make a build, and give the below error.
I cloned the 4.31.0  version.
I am working on *develop branch* 

<img width="1225" alt="Screenshot 2022-11-15 at 10 43 58 PM" src="https://user-images.githubusercontent.com/58082294/201989509-623fafaa-8a7a-45c7-bbe1-27b8c258baf8.png">

<img width="771" alt="Screenshot 2022-11-15 at 3 25 12 PM" src="https://user-images.githubusercontent.com/58082294/201896028-6b3c5126-812d-489c-a333-1373524c55a4.png">

**Comment by diegolmello** [comment]
You're not running any task.
If you want to build something, the command should start with `assemble` or `bundle`.
