### ISSUE TITLE
Mobile Notifications won't Sound

### ISSUE THREAD

**Issue by haobinnan** [RocketChat/Rocket.Chat.ReactNative#4693]
I now have Rocket.Chat on my Android phone.
When a new message comes in, I don't get any type of notification (sound).
I’ve tried changing the notification preferences via Profile > Setting (top right corner) >Notifications > Alert (change  Default to All Messages). 
However, the setting couldn’t be saved successfully, for it turns back to “Default” automatically.
Moreover, I also pushed notification settings for Android suggested by this page:
https://docs.rocket.chat/guides/mobile-guides/push-notifications/mobile-device-settings

Still the notifications do not work correctly.

Could you please tell how to troubleshoot the issue?

![6E68F260984FBB6DB2AACBCC280F943F](https://user-images.githubusercontent.com/31329170/202339074-f0c0f0d1-c88d-4c60-8616-b53112bef001.jpg)
![image](https://user-images.githubusercontent.com/31329170/202339418-6305cf82-b03a-4e49-bc4a-4c4d6b77f43a.png)
![image](https://user-images.githubusercontent.com/31329170/202339596-c5de321b-5878-4c0c-8e3e-c7ef19774c45.png)

**Comment by zufanka** [comment]
+1 

We don't get the mobile notifications to appear at all

**Comment by diegolmello** [comment]
Hey.
Is your server using Rocket.Chat gateway?
If so, is it registered to receive push notifications?
Is there enough push quota?

If it's not using our gateway, is it properly configured?

To test if there's any specific behavior on your device, you can create two accounts on https://open.rocket.chat and try push notifications.

**Comment by haobinnan** [comment]
![QQ截图20221118113751](https://user-images.githubusercontent.com/31329170/202612728-2528def5-e129-489c-86c3-cc9dc8cec78c.png)
![QQ截图20221118113803](https://user-images.githubusercontent.com/31329170/202612733-80b97b0e-baa0-44c9-bb2d-12c71fa13e47.png)
![QQ截图20221118113827](https://user-images.githubusercontent.com/31329170/202612735-277704ef-d12e-4e65-a4e6-4eafb0ee1f14.png)
![QQ截图20221118113851](https://user-images.githubusercontent.com/31329170/202612738-5dc5dcb9-561a-4858-ac20-4f4d38e78025.png)
![QQ截图20221118113901](https://user-images.githubusercontent.com/31329170/202612741-68c44356-e967-496f-91b4-4c342d5221c7.png)
![QQ截图20221118113910](https://user-images.githubusercontent.com/31329170/202612743-fb7eff2f-a21a-4bef-be1c-84e3c84c3918.png)

**Comment by haobinnan** [comment]
![QQ截图20221118120656](https://user-images.githubusercontent.com/31329170/202625144-399a02f4-a108-4b28-a5a6-6c75afae8f87.png)

**Comment by diegolmello** [comment]
"No tokens for this user" means the user didn't login from the Rocket.Chat mobile app or it doesn't support FCM (no Google Play).
Did you test the open server like I mentioned above?
