### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [RocketChat/Rocket.Chat.ReactNative#4696]
### Description:

I tried to build 4.32.0 for F-Droid. The build failed due to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4481. I saw that it's fixed by https://github.com/RocketChat/jitsi-maven-repository/pull/6 but I can't find where the updated binarie come from. https://github.com/RocketChat/jitsi-meet/tree/mobile is not updated. How should I build the new jitsi libs? Thanks!

**Comment by diegolmello** [comment]
We removed Jitsi from Android.

**Comment by linsui** [comment]
I'm not sure what it means. 4.33.1 builds for me and should be published soon. So we don't need to build jitsi-meet anymore?

**Comment by diegolmello** [comment]
We removed the native integration. It should open on webview or redirect to the Jitsi app.
