### ISSUE TITLE
cant see/use OAuth login methods

### ISSUE THREAD

**Issue by szampardi** [RocketChat/Rocket.Chat.ReactNative#4697]
### Description:

Everything works as expected on browser, but logging into RocketChat on mobile (Android), with both RocketChat and RocketChat Experimental apps, OAuth provider login buttons aren't visible anymore and login is only doable with the usual username or email + password method.  

### Environment Information:

- Rocket.Chat Server Version: 5.3.1
- Rocket.Chat App Version: 4.33.0.36182 (experimental) and 4.32.0.35745
- Device Name: Pixel 5
- OS Version: Android 13

### Steps to reproduce:

1. Enter workspace URL
2. Click Connect
3. Only "Login" button is visible, leading to standard username or email + password login

### Expected behavior:
There should be buttons for additional auth methods I have set up in the instance.

### Actual behavior:
No buttons are visible, standard username or email + password login method is enforced.

**Comment by diegolmello** [comment]
It's very likely to a misconfiguration on your server.
Can you see the other login methods on web?

You can try https://open.rocket.chat for reference

**Comment by szampardi** [comment]
hi Diego,

I can indeed see "Continue with Github" and "Continue with Google" on the public instance, but I am not using those on my private one - instead it's the Nextcloud and Custom Oauth that are not usable. The fact that the Oauth options work on browser, also that I have never made any changes to the configuration (except for client/secret IDs) in quite a long time (1-2 years) and it has always worked fine, kind of excludes configuration issues on my side from my point of view.


Thanks for youe time!

**Comment by diegolmello** [comment]
I see.
We didn't change anything related to login services on mobile apps as well.
Do you recall when was the last version of mobile and server that this was working?
It's odd you mentioned the buttons aren't _visible_ on mobile apps, so it's not even a matter of fixing something on a specific OAuth logic.
It could be a matter of not fetching the settings properly or something like that.
