### ISSUE TITLE
failed call on android

### ISSUE THREAD

**Issue by Nam-Anh-99** [RocketChat/Rocket.Chat.ReactNative#4709]
### Description:

When pressing the call button on the actions screen, the application is thrown out (on ANDROID). 

### Environment Information:

- Rocket.Chat App Version: 4.31.0
- React-native: RocketChat/react-native#0.68.2
- React: 17.0.2

### Steps to reproduce:

1. Go to 'Actions Screen' 
2. Click on 'Voice call or Video call' 

### Expected behavior:

Show call screen

### Actual behavior:

Pressed the call button and was thrown out of the phone screen 
On ios still works normally

**Comment by diegolmello** [comment]
Can you try again on 4.33.1?
We changed lots of things on Video Conf.
