### ISSUE TITLE
Quoted E2EE message not displayed

### ISSUE THREAD

**Issue by teach404W** [RocketChat/Rocket.Chat.ReactNative#4732]
### Description:

The last update (4.5.0) added  Quotes on E2EE Messages (https://github.com/RocketChat/Rocket.Chat/pull/26303).

Its working in the browser version but a message with quote (E2EE) doesnt show up in the ReactNative App. Before just the quote was missing but now the whole message is missing.

### Environment Information:

- Rocket.Chat Server Version: 5.4.0
- Rocket.Chat App Version: 4.33
- Device Name:  iPhone 13
- OS Version:  16

### Steps to reproduce:

1. quote message in e2ee channel / dm in browser
2. message doesnt appear in the app view

### Expected behavior:

Quoted message should be visible. Atleast the written message without the quote

### Actual behavior:

Message + quote not visible

### Additional context:
Before 5.4.0 atleast the message without the quote was visible. Now nothing is visible inside the app

**Comment by Misterr-H** [comment]
hi @teach404W 
tried to reproduce your issue.
find out things are just working fine with react native app
![WhatsApp Image 2022-12-09 at 1 55 42 PM](https://user-images.githubusercontent.com/55010619/206658151-4e230d4a-9e0c-4c49-bc9c-3501f5f4a059.jpeg)

ps:- quoted message in dm in browser

**Comment by teach404W** [comment]
I dont see an encryption key symbol next to your message. Are your sure, that you enables end 2 end encryption for this conversation?

**Comment by diegolmello** [comment]
@teach404W We don't show the icon on mobile (we should, but that's another topic).
Can you test this?
- Create an e2ee room and send some messages
- Open on mobile without entering your e2e password (they should be encrypted)
- Enter the password and try again

Let us know what happens for quotes (screenshots welcome).
Thanks!

**Comment by teach404W** [comment]
First: There is an small key indicator next to the message for encrypted messages (see screenshot below) thats why i thougt your room isnt encrypted.

So i created the new room and i cant the encrypted quotes. But i can see the message now but the quote is still missing.

Appview:
![2022-12-10 13-31-16-0](https://user-images.githubusercontent.com/94044406/206855266-5cc45768-1cd1-4f8d-86fd-7e1b86ca0221.png)

Webview:
![grafik](https://user-images.githubusercontent.com/94044406/206855190-38af9ce9-42c8-4b01-ab2d-4652f863191b.png)

**Comment by diegolmello** [comment]
Thanks for sharing!

> We don't show the icon on mobile

You're right. I was talking the other about how we don't show auto translate icon there and mentioned it by mistake.
