### ISSUE TITLE
Room header doesn't show selected icon

### ISSUE THREAD

**Issue by phriedrich** [RocketChat/Rocket.Chat.ReactNative#4733]
### Description:

Room header doesn't show selected icon but it's working correctly in the sidebar.

### Environment Information:

- Rocket.Chat Server Version: 5.4.0
- Rocket.Chat App Version: 4.33.0.36480
- Device Name: iPad Mini 6, iPhone SE2
- OS Version: iPadOS 16.1.1, iOS 16.1.2

### Steps to reproduce:

1. Open Room with set icon

### Expected behavior:

Room should show the selected icon in the header next to the name like it does with users.

### Actual behavior:

Icon is not shown instead the generic colored tile with a letter is used.

<img width="643" alt="Missing-Avatar" src="https://user-images.githubusercontent.com/470153/205914442-9675a4d6-7870-4b3b-8f92-d6dcff23cf93.png">

**Comment by diegolmello** [comment]
Possible regression after #4702 @reinaldonetof
