### ISSUE TITLE
emoji picker partially broken

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat.ReactNative#4734]
### Description:

While long pressing a text message the options menu opens. At the top the emoji picker appears. When you try to tip on the emoji with the plus sign the menu suddenly disappears preventing me from reacting on messages with an emoji. But I can use emojis that I have used frequently from that menu.

### Environment Information:

- Rocket.Chat Server Version: 5.4.0
- Rocket.Chat App Version: 4.33.0
- Device Name:  Pixel 6
- OS Version: Android 13

### Steps to reproduce:

1. Long press text message to open options menu
2. Try to react with emoji via emoji with plus sign
3. Menu disappears.

### Expected behavior:

I should be able to react with emojis.

### Actual behavior:

Not possible.

**Comment by diegolmello** [comment]
Hey. We're taking a look into it. Thanks!
