### ISSUE TITLE
Single-server whitelabel build gets stuck on Your Workspace view.  iOS Only.

### ISSUE THREAD

**Issue by jim0020** [RocketChat/Rocket.Chat.ReactNative#4743]
### Description:

When running the Whitelabel Single-Server code on iOS, the app gets stuck a blank body Your Workspace screen.  The header containing the text "Your Workspace" is displayed, as well as the Version number at the bottom of the screen. But there no other UI elements displayed (Login Button, ect).

### Environment Information:

- Rocket.Chat Server Version: 3.11.1
- Rocket.Chat App Version: 4.33.1
- Device Name: iPhone 13
- OS Version: iOS 15.5

### Steps to reproduce:

1. Build and launch the app from the terminal command line with 'yarn ios'
2. See the splash screen, then the blank 'Your Workspace' view appears.

### Expected behavior:

The 'Your Workspace' view has the UI elements to enter your username, password, Login button amd other associated UI elements.

### Actual behavior:

On Android it works as expected, on iOS the body of the view is blank.

![image](https://user-images.githubusercontent.com/833366/207170724-ba00abe8-d068-4acf-8589-bdd928e19b13.png)

### Additional context:

The problem seems to be in app/lib/services/connect.ts, line 391.  The call to RNFetchBlob.fetch to get the api info JSON never gets a response.  NOTE: This problem is in iOS only, Android works fine here.  The iOS info.plist setting for App Transport Security is set to Allow Arbitrary Loads = YES.

![Screen Shot 2022-12-12 at 5 52 08 PM](https://user-images.githubusercontent.com/833366/207172217-2aa003b1-0267-4465-aaad-45afc3aa3c17.png)

**Comment by jim0020** [comment]
Additional infomation:  I have also tried replacing the call to RNFetchBlog.fetch with React.fetch with no change to the result.  The fetch still receives no response and the WorkspaceView body is still blank.

I have seen mentions that perhaps the Expo library is to blame in that it is interfering with the response promise.  I'll go back and try to find a link for that.

I am using XCode 13.4.1 for my iOS build.

**Comment by reinaldonetof** [comment]
Hello, @jim0020 
Can you share the server within the app.json?

Also, can you check if there is an `Exception Domains - localhost` in `App Transport Security Settings`?

**Comment by jim0020** [comment]
HI.  I’ve tried two servers, ours @ https://chat.joancusec.org/ <https://chat.joancusec.org/> and yours https://open.rocket.chat <https://open.rocket.chat/>  Both have the same result, no response to the /api/info GET request.

Here is a snippet from my ios/RocketChatRN/info.plist :

	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>rocket.chat</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
			<key>joancusec.org</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>


I’m have XCode 13.4.1, but am doing the buiids using the command line: 
	yarn ; npx pod-install ; yarn ios

Also I am not seeing any connection related errors in the js console output, nor in the Simulator and System log.  My firewall app (Little Snitch) shows the request going out and the response coming back, but the response just disappears.

Jim

**Comment by reinaldonetof** [comment]
Hey, @jim0020 

Actually, you don't need to add the servers inside the ExceptionDomains, because they are `https`. I recommend you discard those changes into info.plist, or if you want here is how the NSAppTrasporstSecurity is written:
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

About your problem, ensure that the server within the `app.json` is written as "server": "https://chat.joancusec.org", as you can see we aren't adding the slash after the `.org`. The same if you try to connect for open.rocket.chat, "server": "https://open.rocket.chat"

**Comment by jim0020** [comment]
Ok, I’ll remove the entries from info.plist.

Regarding the ’server’  field in the app.json file, I do not have a slash at the end of my url.

**Comment by jim0020** [comment]
Checked the URL in app.json, there is no endling slash.  I have console.debug output that shows the correct URL, https://open.rocket.chat/api/info.

I removed the unnecessary NSAppTransportSecurity entries from info.plist.

No change in the behavior, still no response to the fetch, and therefore no Login UI elements on iOS.  Android still works fine.

**Comment by dardanbujupaj** [comment]
Encountered the same issue while upgrading from 4.17.

I was able to pin the same issue as @jim0020, a hanging `RNFetchBlob.fetch` on the `Your workspace` page while requesting server here in [connect.ts](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/ccbc84f9a8a008199ef9f82729b24f04214a6a50/app/lib/services/connect.ts#L391)

The issue only appears to happen when updating from and old version (4.17 in my case) to a current version and it is gone, when deleting the app and reinstalling it. But this seems a lot to ask from users when updating to a new version IMHO.

I tried to replace `RNFetchBlob.fetch` with ReactNative `fetch`, which didn't work either. This suggests, this might be an issue with ReactNative itself, right?

Nevertheless, I found a solution which is a bit ugly, but it does the job in my case (this could maybe interest you @jim0020 ):

I replaced given `RNFetchBlob.fetch`-call with a `XMLHttpRequest` in `connect.ts`:

````
// Workaround for stuck fetch request on 'Your workspace' after 4.34 update
// should be reverted, when upstream is fixed
const fetchWorkaround = (url: string) =>
	new Promise((resolve, reject) => {
		const xhr = new XMLHttpRequest();
		xhr.addEventListener('readystatechange', e => {
			if (xhr.readyState !== 4) {
				return;
			}
			if (xhr.status === 200) {
				resolve(xhr.responseText);
			} else {
				reject(e);
			}
		});
		xhr.open('GET', url);
		xhr.send();
	});

async function getServerInfo(server: string) {
	try {
		const response: any = await fetchWorkaround(`${server}/api/info`);

		try {
			// Try to resolve as json
			const jsonRes: { version?: string; success: boolean } = JSON.parse(response);
			if (!jsonRes?.success) {
````

**Comment by dardanbujupaj** [comment]
Nevermind my comment above. This doesn't work either. Also checked with 4.34.0.

**Comment by diegolmello** [comment]
I just tested here and it's working fine.

- checkout `single-server` branch
- apply google files
- run without changing anything else
- it opens fine pointing to Open server

**Comment by dardanbujupaj** [comment]
@diegolmello sure it works fine when setting it up from scratch, but in my case I'm updating an older app (currently 4.17). If the old version is installed on an iPhone and I update to 4.34 an empty screen is shown.

Reproduction:
- Install old version of app (e.g. 4.17)
- login to to server
- update app to 4.34
- open app -> empty screen
- delete and reinstall 4.34 app -> login works


We have quite a userbase so there's no way we can tell them all to delete and reinstall the app instead of updating...

**Comment by jim0020** [comment]
@dardanbujupaj @diegolmello

What versions of the build tools and target iOS versions are you using?

My build was built from scratch and run on an iPhone Simulator (iPhone 13, iOS 15.5).  I wanted to target the latest iOS (iOS 16) but I needed to upgrade to XCode 14 to do that.   When compiling with XCode 14, the code crashed immediately on launch, but don't have a stack trace :-( .  So I downgraded XCode back to v13.4.1, which means the highest iOS I could target was iOS 15.

FWIW, Android 11, API level 30 ran fine right out of the box.

BTW, my build system is MacOS Monterey, v12.8.

I tried replacing the problematic RNFetchBlob.fetch call with a React.fetch, but had the same result.  No response, and no errors in the log.

**Comment by jim0020** [comment]
@dardanbujupaj @diegolmello 

It should not have anything to do with changing bundle id's, or signatures, or could it?  Just trying to think what might be different.

**Comment by diegolmello** [comment]
It can't be something on `fetch`. We're using the same logic for everyone else.

> I suspect it's not the RocketChat code, but a conflict in some of the node libraries

Node is used only during development. After the app is on release mode, it's all about native libs and JS. Either way, I'm using node 14.20.0, if you want to try it.

Also both Xcode 13 and 14 work fine for me.
I'm right now on Ventura, but it was working fine on Monterey.

Can you try following my steps above? Without changing anything else from the code?
You can get the `GoogleService-Info.plist` from here and you should be able to build https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/ios/GoogleService-Info.plist

What about develop branch? Does it work?

**Comment by jim0020** [comment]
@diegolmello @dardanbujupaj 

Cloned the single-server @ v4.34.0.1 repo into a new directory.  Had to change the team, bundle ids, app group id, keychain shariing id, and the code signing identity for it to compile and run.  Did yarn, npx pod-install, yarn ios.  Same result, blank body on the WorkspaceView.  XCode 13.4.1

**Comment by jim0020** [comment]
@diegolmello @dardanbujupaj 

I may have found my problem!  the file ios/RocketChanRM/Info.plist has a key named KeychainGroup.  It did not match the Keychain Group value set using the XCode UI (by opening RocketChanRN.xcworkspace). It doesn't appear to be set by the XCode UI.  When I change that value to match the Keychain Group I was setting in the Project Targets -> Signing & Capabilities tab  (for each of the targets: RocketChatRN, ShareRocketChanRN, NotificationService, and Rocket.Chat) the Workspace View body now properly displays the login UI elements.

**Comment by diegolmello** [comment]
Ok. Is there something missing on the documentation? https://developer.rocket.chat/mobile-app/mobile-app-white-labelling/ios-app-white-labelling

**Comment by jim0020** [comment]
@diegolmello 

Ouch.  No, it's in the documentation.  Very Sorry, my bad.  Apparently I can't follow directions.  Missed the editing the Info.plist and .entitlements step.   Thanks for the help.

Hope this helps @dardanbujupaj

**Comment by dardanbujupaj** [comment]
@diegolmello @jim0020 thanks for the advice. Unfortunately this did not work for me.
I reviewed the whole whitelabelling document again, and every setting is correct.
Also it doesn't really make sense that it's because of misconfiguration, as it's only after I install the updated version while having the current version installed. When I delete and reinstall the app it works just fine.

Any other ideas?

**Comment by barestu** [comment]
Hi @dardanbujupaj, have you found the solution to your problem?
I'm using the single-server branch & I also got a similar issue where the users updated the app from 4.23 to 4.32. The app screen is blank on 'Your Workspace' & the code is stuck on `getServerInfo` request that not finishing. This issue can be bypassed by uninstalling & installing the app again.

I already tried clearing the MMKV storage, AsyncStorage, and WatermelonDB, but still got a blank screen.

**Comment by dardanbujupaj** [comment]
> Hi @dardanbujupaj, have you found the solution to your problem? I'm using the single-server branch & I also got a similar issue where the users updated the app from 4.23 to 4.32. The app screen is blank on 'Your Workspace' & the code is stuck on `getServerInfo` request that not finishing. This issue can be bypassed by uninstalling & installing the app again.
> 
> I already tried clearing the MMKV storage, AsyncStorage, and WatermelonDB, but still got a blank screen.

Hey. Sorry for the late reply. I've already written it last week, but it seems I forgot to press send...

I was able to solve it. It turned out before upgrading the app group/keychain groups weren't changed. So I reverted them back to their original value in all targets (e.g. `$(AppIdentifierPrefix)chat.rocket.reactnative`)

It seems that additionally to having the same values in all targets it's important that these don't change between updates.
