### ISSUE TITLE
I have a issue when try to run  ./gradlew assembleRelease

### ISSUE THREAD

**Issue by T941** [RocketChat/Rocket.Chat.ReactNative#4744]
* What went wrong:
Execution failed for task ':app:processE2eFossReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:D:\Rocket.Chat.ReactNative\android\app\src\main\res\values\styles.xml:16:5-20:13: AAPT: error: resource drawable/ic_launcher_foreground (aka chat.rocket.reactnative:drawable/ic_launcher_foreground) not found.

Could anyone support to investigate this issue and how to fix it.
Thank you very much.

**Comment by diegolmello** [comment]
You need to take the product flavors in consideration https://developer.rocket.chat/mobile-app/mobile-app-white-labelling/android-app-white-labelling

You probably want to run `assembleExperimentalPlayRelease`
