### ISSUE TITLE
F-Droid build has been unusable for a while

### ISSUE THREAD

**Issue by Eesun5ae** [RocketChat/Rocket.Chat.ReactNative#4747]
### Description:

F-Droid version still suffers from this bug that was solved a few months ago: #4551 

It has not been updated since.

Solution would be to just release a new version on F-Droid to have a usable version again.

### Expected behavior:

Release on F-Droid gets updated

### Actual behavior:

No new F-Droid release since the fix in #4536 was merged.

**Comment by diegolmello** [comment]
We're going to release a new version in a few days.
