### ISSUE TITLE
versionName is "4.33.1" in 4.34.0 tag and release

### ISSUE THREAD

**Issue by xl32** [RocketChat/Rocket.Chat.ReactNative#4753]
I built the 4.34.0 version from releases and see that Android manifest contains version 4.33.1.1.
Tags changeset https://github.com/RocketChat/Rocket.Chat.ReactNative/compare/4.33.1...4.34.0 does not contains any version bump.
Please apply a fix (probably within the 4.34.1 release) to fix numeration.

**Comment by diegolmello** [comment]
Thanks for reporting.
We're on it.

**Comment by diegolmello** [comment]
Done.
