### ISSUE TITLE
please  Task :app:processBugsnagE2e-foss-releaseManifest FAILED

### ISSUE THREAD

**Issue by 337077418** [RocketChat/Rocket.Chat.ReactNative#4754]
What command do I use to package the apk? I tried      gradlew assembleRelease

but 

> Task :app:processBugsnagE2e-foss-releaseManifest FAILED
Execution optimizations have been disabled for task ':app:processBugsnagE2e-foss-releaseManifest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'E:\RocketChat\Rocket.Chat.ReactNative\android\app\build\intermediates\merged_manifest\e2eFossRelease\processE2eFossReleaseMainManifest\AndroidManifest.xml'. Reason: Task ':app:processBugsnagE2e-foss-releaseManifest' uses this output of task ':app:copyE2eFossReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

FAILURE: Build failed with an exception.

**Comment by diegolmello** [comment]
https://developer.rocket.chat/mobile-app/mobile-app-white-labelling/android-app-white-labelling

`assembleExperimentalPlayRelease`
