### ISSUE TITLE
Can not build the project apk in Android Studio

### ISSUE THREAD

**Issue by greenh2** [RocketChat/Rocket.Chat.ReactNative#4758]
I have downloaded the React Native project v4.32.0

I tried to run the project using Android Studio but it is producing lot of errors.

I tried to run the same project using VS Code it runs on the Android Device without any issue, But when i try to build the release APK by the following command it gives me lot of errors.

cd android
./gradlew assembleRelease 

If anyone can reproduce the steps and can tell me what has to be done to run the project and build APK from Android Studio without errors.

I am using React-native 1.2.0 version

Android Studio Dolphin 2021.3.1

Gradle Plugin Version 7.0.4

buildToolsVersion 31.0.0 
minSdkVersion   23 
compileSdkVersion   31
targetSdkVersion    31
glideVersion    4.11.0
kotlin_version  1.6.10
kotlinVersion   1.6.10
supportLibVersion   28.0.0
libre_build null
jitsi_url   https://github.com/RocketChat/jitsi-maven-repository/raw/master/releases
jitsi_version   3.7.0 

I have

java 17.0.4.1 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)

and also i tried with older version of JAVA by adding in android - app - build.gradle file

android {    
    ............     
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }    
 .................
 }

But can not able to run the project on Android Device.

I just want to try and build the release APK of this project myself.

**Comment by diegolmello** [comment]
If you're starting now, you should download the latest version.
We're on 4.34.0.
