### ISSUE TITLE
Google UGC guidelines require accepting the app's terms of user/user policy

### ISSUE THREAD

**Issue by Chirtep** [RocketChat/Rocket.Chat.ReactNative#4762]
### Description:

We (the BCS-TEKHNOLOGII team) faced a problem with publishing an updated Android version of RC. After submiting the app's bundle from internal testing to review, we've received a notification from Google which messaged us that publishing is prohibited. The reason was in violating Google UGC guidelines. By sending an appeal we've received more concrete explanation:

Google's [User Generated Content](https://support.google.com/googleplay/android-developer/answer/9876937) policy requires to

> All users MUST accept the app's terms of user/user policy provided by the developer before app usage.

They expect us to place some modal window, notification or something like that, which contains info block with accepting terms of user/user policy in this section:

![ru bcstech chat](https://user-images.githubusercontent.com/77800075/208877416-51aac889-2d61-4468-a256-780dfab06f57.png)

This issue probably related with #4745

@diegolmello, probably we should add this feature into the app's code, because for now we (me and @ankar84) have no opportunity for updating our RC app for Android.

Hope for rapid resolve on this problem.
 
### Expected behavior:

The app's new version is published in Play Market without any problem.

### Actual behavior:

App's new version publishing is prohibited.

**Comment by diegolmello** [comment]
Hey. Yeah, we talked with Google team a few weeks ago about moderation specifically https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4745

On this issue, I think it's a matter of appealing and showing them the register page.
![image](https://user-images.githubusercontent.com/804994/208916581-d614b2d7-b655-42f8-a355-a380ecc637ba.png)

**Comment by Chirtep** [comment]
> Hey. Yeah, we talked with Google team a few weeks ago about moderation specifically #4745
> 
> On this issue, I think it's a matter of appealing and showing them the register page. ![image](https://user-images.githubusercontent.com/804994/208916581-d614b2d7-b655-42f8-a355-a380ecc637ba.png)

In our case, the registration of new users is disabled, so we can't show the registration section just like that. However, we have found a way out of the situation based on your answer.

As a suggestion for the future: perhaps it is worth moving the block with the phrase about agreeing to the Terms of Service and Privacy Policy to the application login section (where the certificate block is now located)? It'll help everyone, who, like us,  disabled registry of new users through the registration view and now facing trouble with Google policies.

**Comment by diegolmello** [comment]
Sure. Let's do that. Thanks for the suggestion!
