### ISSUE TITLE
Video not showing on iOS when using latest versions of jitsi-meet

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat.ReactNative#4775]
### Description:

When updating jitsi-meet to version 2.0.8138, we found that the video is not displayed on iOS. We attribute this to the disabling of the deprecated streaming methods removed in this [commit](https://github.com/jitsi/jitsi-meet/pull/12499). Now the _sendMultipleVideoStreams: false_ option is not supported.

### Environment Information:

- Rocket.Chat Server Version: 5.3.5
- Rocket.Chat App Version: 4.34
- Device Name: Iphone 11
- OS Version: 14

### Steps to reproduce:

1. Make a call through the Rocket Chat mobile app.
2. Ask the other person to turn on the camera or share the screen.
3. Video not showing when used in jitsi-meet version 2.0.8138

### Expected behavior:

The video is displayed.

### Actual behavior:

Video is not displayed.

**Comment by seconp** [comment]
hello what is your version of react native？0.68？

**Comment by seconp** [comment]
I want to install an environment to run the source code,but I have a lot of problem, can u tell me your environment version?thank u.

**Comment by shevchukma** [comment]
> hello what is your version of react native？0.68？

Hello.
How can I find out the version of react native?
I had this problem reproduced a week ago on the Rocket Chat app from the Appstore.
I think the application version was 4.34. Rocket.Chat 5.3.5 server was running on Oracle 8.7 in docker. Jitsi in Ubuntu 22.04.1.
List of jitsi apps:
_dpkg -l | grep jitsi
ii jitsi-meet 2.0.8138-1 all WebRTC JavaScript video conferences
ii jitsi-meet-prosody 1.0.6854-1 all Prosody configuration for Jitsi Meet
ii jitsi-meet-web 1.0.6854-1 all WebRTC JavaScript video conferences
ii jitsi-meet-web-config 1.0.6854-1 all Configuration for web serving of Jitsi Meet
ii jitsi-videobridge2 2.2-63-g252d14bc-1 all WebRTC compatible Selective Forwarding Unit (SFU)
ii lua-basexx 0.4.1-jitsi1 all baseXX encoding/decoding library for Lua
ii lua-cjson:amd64 [2.1.0.10-jitsi1](https://2.1.0.10-jitsi1/) amd64 JSON parser/encoder for Lua_

This is a completely fresh installation, with minimal configuration changes.

**Comment by shevchukma** [comment]
> hello what is your version of react native？0.68？

@seconp now, our developer said that our app is using react-native#0.68.2. But this problem was not only in our application, but also in Rocket.Chat.

**Comment by saghul** [comment]
What version of the Jitsi Meet SDK are you using?

**Comment by GleidsonDaniel** [comment]
@shevchukma Can you check if this update works again?
https://github.com/jitsi/jitsi-meet/issues/12732

**Comment by shevchukma** [comment]
> What version of the Jitsi Meet SDK are you using?

How can I check it? I'm using the official Rocket.Chat version 4.34.0.36627 from the [App Store](https://apps.apple.com/ru/app/rocket-chat/id1148741252).

**Comment by shevchukma** [comment]
> Can you check if this update works again?
@GleidsonDaniel the version of Jitsi has not changed. I checked, on the application version 4.34.0.36627. No changes. Iphone does not see video from other participants.
Package versions:
ii  jitsi-meet                            2.0.8138-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody                    1.0.6854-1                              all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                        1.0.6854-1                              all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config                 1.0.6854-1                              all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge2                    2.2-63-g252d14bc-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)
ii  lua-basexx                            0.4.1-jitsi1                            all          baseXX encoding/decoding library for Lua
ii  lua-cjson:amd64                       2.1.0.10-jitsi1                         amd64        JSON parser/encoder for Lua

**Comment by saghul** [comment]
> > What version of the Jitsi Meet SDK are you using?
> 
> 
> 
> How can I check it? I'm using the official Rocket.Chat version 4.34.0.36627 from the [App Store](https://apps.apple.com/ru/app/rocket-chat/id1148741252).

I don't know what version the rocket chat app uses, hopefully someone can clarify that here.

**Comment by GleidsonDaniel** [comment]
> > Can you check if this update works again?
> > @GleidsonDaniel the version of Jitsi has not changed. I checked, on the application version 4.34.0.36627. No changes. Iphone does not see video from other participants.
> > Package versions:
> > ii  jitsi-meet                            2.0.8138-1                              all          WebRTC JavaScript video conferences
> > ii  jitsi-meet-prosody                    1.0.6854-1                              all          Prosody configuration for Jitsi Meet
> > ii  jitsi-meet-web                        1.0.6854-1                              all          WebRTC JavaScript video conferences
> > ii  jitsi-meet-web-config                 1.0.6854-1                              all          Configuration for web serving of Jitsi Meet
> > ii  jitsi-videobridge2                    2.2-63-g252d14bc-1                      all          WebRTC compatible Selective Forwarding Unit (SFU)
> > ii  lua-basexx                            0.4.1-jitsi1                            all          baseXX encoding/decoding library for Lua
> > ii  lua-cjson:amd64                       2.1.0.10-jitsi1                         amd64        JSON parser/encoder for Lua

You said you updated your server here:
> When updating jitsi-meet to version 2.0.8138

And I said in the message that another user said that updating the server to version X solved the problem:
https://github.com/jitsi/jitsi-meet/issues/12732

We didn't update anything in iOS, but you said you updated your server.
Wouldn't it be simpler to update it one more time and fix the problem like the other user?

**Comment by GleidsonDaniel** [comment]
> What version of the Jitsi Meet SDK are you using?
3.6.0

@saghul We are waiting for that sdk to be released so we can update to a new version 😂
https://github.com/jitsi/jitsi-meet/pull/11959
It's not charging or anything, but anything new? 👀

**Comment by shevchukma** [comment]
> And I said in the message that another user said that updating the server to version X solved the problem: [jitsi/jitsi-meet#12732](https://github.com/jitsi/jitsi-meet/issues/12732)
> 
> We didn't update anything in iOS, but you said you updated your server. Wouldn't it be simpler to update it one more time and fix the problem like the other user?

Apparently these are different problems. I have the latest version and the problem is present in it.

**Comment by 6bIBAET** [comment]
I'm have the same issue with RocketChat app on iOS devices after update self-hosted Jitsi Server. The RocketChat client does not show other users and does not stream video when using a self-hosted Jitsi server, but if you open this conference in any browser on iOS, or any PC browsers, or in PC RocketChat app then everything works fine. The official Jitsi app from Apple App Store works without problems with same self-hosted Jitsi server. RocketChat for android also work fine.

RocketChat iOS app version is 4.34.0.36627.
RocketChat self-hosted server version is 5.4
Jitsi server have a latest version:
jitsi-meet						2.0.8138-1
jitsi-meet-prosody				1.0.6854-1
jitsi-meet-tokens				1.0.6854-1
jitsi-meet-turnserver			1.0.6854-1
jitsi-meet-web					1.0.6854-1
jitsi-meet-web-config			1.0.6854-1
jitsi-videobridge2				2.2-63-g252d14bc-1

**Comment by ankar84** [comment]
I will try to explain that issue to everyone here.
RocketChat iOS application still using very old Jitsi SDK version 3.6.0
That version obviously doesn't support multistream and all other modern Jitsi features.
Last version of Jitsi server that will works with RC app for iOS is 2.0.7439-1
Starting with 2.0.8138 Jitsi server version RC app of iOS will not show camera and ScreenSharing because of old Jitsi SDK in it.
Android doesn't have such problem because in new version (as I remember right 4.33) RocketChat team removed Jitsi SDK and Jitsi calls now processing in WebView.

And as a conclusion - @GleidsonDaniel is right that proper way of fix is updating Jitsi SDK in RC mobile app for iOS. Or removing of Jitsi SDK as that done for Android, but as I know team meet some problems in Jitsi calls using WebView on iOS (Safari issues).
Actually https://github.com/jitsi/jitsi-meet/issues/12732 is a different issue, where other participants don't get iOS video (and looks like Jitsi Meet app for iOS is used, which working perfect with all server versions - old and new), but that particular issue is that RocketChat mobile app for iOS don't show other participants video (camera and SS).

So, hope @saghul will have enough time to wrap https://github.com/jitsi/jitsi-meet/pull/11959 soon!

**Comment by GleidsonDaniel** [comment]
@shevchukma and @ankar84 what is the origin of your jitsi server?
Did you fork our fork (https://github.com/RocketChat/jitsi-meet), or are you using the original Jitsi repo as the basis for your server?

**Comment by ankar84** [comment]
> @shevchukma and @ankar84 what is the origin of your jitsi server? Did you fork our fork (https://github.com/RocketChat/jitsi-meet), or are you using the original Jitsi repo as the basis for your server?

Hey @GleidsonDaniel 
We are using original Jitsi Meet server installed by debian packages. Whole Jitsi code is original. We just can change some settings to corresponding our needs.
