### ISSUE TITLE
The screen goes to sleep during a call

### ISSUE THREAD

**Issue by shevchukma** [RocketChat/Rocket.Chat.ReactNative#4777]
### Description:

In some versions of android, when a call is displayed through Webview, the phone screen goes to sleep. You need to touch the screen so that it does not turn off.

### Environment Information:

- Rocket.Chat Server Version: 5.3.5
- Rocket.Chat App Version: 4.33.0

### Steps to reproduce:

1. Just make a call using Rocket.Chat+webview, not Jitsi.

### Expected behavior:

The phone does not go to sleep.

### Actual behavior:

The phone goes into sleep mode.

### Additional context:

I don't know exactly what version of Android was used, but we've received a few of these from users.

**Comment by diegolmello** [comment]
Ok, we're going to take a look into it
