### ISSUE TITLE
404 Error while Audio/Video calling in Android (Also ON PLAY STORE APP)

### ISSUE THREAD

**Issue by greenh2** [RocketChat/Rocket.Chat.ReactNative#4782]
I am using the latest react-native version 4.34.0, after i build and installed the release APK version on Android device.

After user Login is done and user makes a audio/video call using -

Rocket Chat Workspace URL the call gets connected. 
But If i use my workspace URL, i am not able to make any calls to another user (Everything else works fine only call has some issue)
Error page displays
**404 Not Found
You can create a new conversation here** 

Screenshot Image
https://www.pastiebin.com/63ad172c1c5a5

The same issue comes out if you Download and install the **latest Rocket.Chat APK from Play Store**,
And use any other Workspace URL instead on Rocket.Chat Workspace URL.
However in older version of Rocket.Chat APK their is no such issue.

Is their any issue with the existing code?

**Comment by GleidsonDaniel** [comment]
What are the versions of your servers?

**Comment by greenh2** [comment]
> @greenh2 I had this issue I am not sure why it is happening but in the JitsiMeetView.android.tx file in the views folder the webview component's source is source={{ uri: `${this.url}&config.disableDeepLinking=true` }}. This errors for me but when I deleted the &config.disableDeepLinking=true, it works as well as if you were to change the & to a #. this may not be the best solution but it got it to a working state for me.

Thanks but, 
when I tried deleting the &config.disableDeepLinking=true, it displays the page as shown in the image
User will then have to either click **Launch in Web** to make the audio/video call.  However this will not be **user friendly**.  Hoping for some better answers.


> What are the versions of your jitsi servers?

Rocket Chat server version 3.14.5

![Inkedrcjitsi123](https://user-images.githubusercontent.com/121014218/210502010-7364512f-551d-41cf-b3ef-847927246930.jpg)

**Comment by GleidsonDaniel** [comment]
> Rocket Chat server version 3.14.5

Jitsi Server version, not rocket.chat server version.
To connect on Jitsi server you need to deploy a server a put the setting on app instaled on rocket.chat.
Whats the version of the server that generate that url.

**Comment by GleidsonDaniel** [comment]
Finally i found this issue!
Probably in the next version the fix for it should be released.

**Comment by greenh2** [comment]
@GleidsonDaniel Great will wait for the next release, but earlier releases was not having any such issue. Thanks

**Comment by GleidsonDaniel** [comment]
> @GleidsonDaniel Great will wait for the next release, but earlier releases was not having any such issue. Thanks

Yes, the issue was "added" in some versions ago, because we were updating everything related to jitsi, but we forgot to remember that there are people who use the server in old versions that don't have these considerations.
