### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by pratikGajeragithub** [RocketChat/Rocket.Chat.ReactNative#4784]
Build the app in iOS but there is one error reflect everytime. Error are :- FBReactNativeSpec 
command phasescriptexecution failed with a nonzero exit code
![image](https://user-images.githubusercontent.com/102503822/209808853-11e8a8f7-68e1-49a3-9cfc-12e8b5f660d6.png)

**Comment by GleidsonDaniel** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4293
