### ISSUE TITLE
Login with client credential can not fetch image

### ISSUE THREAD

**Issue by Iamnvincible** [RocketChat/Rocket.Chat.ReactNative#4785]
I am using the android app with client credential(a certificate), when I login to my own Rocket Chat server, it just cannot display any image,such as user avatar, in chat pictures.

I tried to check my nginx log, when these image requests came, nginx didn't output a record with client credential Info, while the login requests came with that info.

If I clear app cache in settings, surprisingly, these images appears immediately, although not every image displays every time after I clear cache.

If I disable client credential verification on nginx, every thing works properly.

I guess that when you login first time, some ,even all image requests were failed to attach client credential info. I have looked into SSLpinning code, it seems all react native requests were attached with certificate info. I am new to android and react native app development, code looks very complicated, so I am here looking forward to your opinions.

**Comment by diegolmello** [comment]
Can you give us more details?
It's going to be hard to reproduce it.

**Comment by Iamnvincible** [comment]
Of course, I wrote that message on GitHub app without much space.

### Description:
I am using Rocket Chat  Standalone version with client certificate verification on nginx. And when I use Rocket Chat Android App to connect my server, users' avatar and images in chat history can not display after I logged in. If I go to settings and clear local cache, app will retrive messages and images immediately, and avatars and images can show up. But some avatar may still be blank.


### Steps to reproduce:

- Deploy Rocket Chat standalone version on my Debian 10 server according to [doc](https://docs.rocket.chat/quick-start/deploying-rocket.chat/other-deployment-methods/manual-installation/debian-based-distros/debian)
- Generate self-signed CA, SSL certificate and client certificate
- Configure nginx to serve proxy, with `ssl_verify_client on;` to enable client verification.
- Import client certificate, a `.p12` file to my Android phone. And, CA cert must be imported too.
- Install Rocket Chat Android app on my Android phone.
- Open the app, and choose `Apply Your Certificate` link on app and choose the cert imported before.
- Enter my workspace URL and tap connect


### Expected behavior:

After connect to workspace, there is a place which should display a Rocket Chat Icon just like app icon.
And after I logged in, users' avatar should display.

### Actual behavior:

On android (4.34.0.36626), after connect to workspace, the icon cannot display, just a capital `C` took that place.
And when I logged in, users' avatar and images in chat history cannot display. 
When I clear local cache, some, maybe all, images can display.


### Server Setup Information:

    Version of Rocket.Chat Server: 5.4
    Operating System: android 
    Deployment Method: Debian manually
    Number of Running Instances: 1

### Client Setup Information

android (4.34.0.36626)

### Additional context

If I clear app storage, in Android System setting, this can happen again, every time.
And today, I tried iOS, images can display normally, what a surprise.

**Comment by Iamnvincible** [comment]
same as issue #4192
