### ISSUE TITLE
Malformed reply message in rooms and chats with unicode or spaces in names

### ISSUE THREAD

**Issue by q210** [RocketChat/Rocket.Chat.ReactNative#479]
Hello, thank you for this work.

In our local Rocket.Chat server deployment we've allowed Russian names for chat rooms and channels via `UTF8 Names Validation` setting in Admin  panel (we've set its value to `[0-9а-яА-Яa-zA-Z-_.\s?!]+`)

This led to the following issue in RN client:
When replying to messages in rooms and channels with russian characters in the room name from RN client you'll see just white placeholder instead of replied message text

![screen shot 2018-10-10 at 00 51 08 copy](https://user-images.githubusercontent.com/1160116/46704238-bf04e400-cc32-11e8-9adb-f4ddf78af68b.png)

After a small investigation we've found that at least this specific problem was fixed after wrapping result in this line 
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/2d7360f0773fb1204603f152b6cbd84bfef8d94b/app/lib/rocketchat.js#L669
in `encodeURI` call (without it function in question could return malformed URI like `https://example.ru/group/2 редиз?msg=FeeadasdaaaAA` - with spaces and unicode symbols in path).
Patched line is looking like this:
```
return encodeURI(`${ server }/${ roomType }/${ room.name }?msg=${ message._id }`);
```

I'm posting this as an issue and not as PR, because I think there could be more similar bugs lurking around unicode in room names and this issue can be a cause to check the code base for them. If I'll have time this month, I'll do it myself and post a proper PR.

**Comment by diegolmello** [comment]
@q210 Thanks for this report! It'll be very helpful if you fix this (and another errors you find) since it's cyrillic and I wouldn't be able to find errors.

**Comment by q210** [comment]
@diegolmello  I'm fairly sure this bug will be reproducible with any non-ascii room name (or even just room name with spaces), but I'll try
