### ISSUE TITLE
Is the project grown enough so that we rebuild our client R.C-based app using the React Native project?

### ISSUE THREAD

**Issue by MehdiMahmoudi** [RocketChat/Rocket.Chat.ReactNative#48]
Hi everyone,

We are considering rewriting our client application (which is a fork from Rocket.Chat) to React Native based on this project.
Knowing that the backend of the RC Meteor app is wired to the rest of our platform with extra customizations to the chat use cases (groups/channels linked to projects and teams, directing to our video call app – similar ton Appear, …etc.), do you think that investing in a RN rewrite is a good bet?

Based on the current status of the project, do you think this is also viable in terms of schedule? (we saw this topic: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/43)

**Comment by gdelavald** [comment]
Hey, as this project is still in early phase, we don't recommend it's usage at the current state.
We'll update the readme with the release dates and roadmap as soon as possible.
