### ISSUE TITLE
Android App Notification issue

### ISSUE THREAD

**Issue by greenh2** [RocketChat/Rocket.Chat.ReactNative#4802]
Rocket Chat App Latest Version 4.34.0 - (Android)
Official Play Release APK

While App is in Background -
Device does not Notify when any user sends message (APP NOTIFICATIONS NOT WORKING), No Notification Sound 

And While using the App also their is no notification/sound of any message ?
  
Tried with older versions as well same issue.

**Comment by greenh2** [comment]
@diegolmello  It works with https://open.rocket.chat but how should i do it for workspace URL

**Comment by diegolmello** [comment]
If it works on Open, it means for sure it's something on your workspace.
Your workspace needs to be registered and have enough push quota to receive push notifications.
If these are correct, it could be a setting inside Rocket.Chat.
Follow this workflow to understand what might be happening https://whimsical.com/notification-workflow-PRwN4MWNsxSwqHjHXaPUuC
