### ISSUE TITLE
Changing devices will no longer send encrypted messages

### ISSUE THREAD

**Issue by 337077418** [RocketChat/Rocket.Chat.ReactNative#4803]
A sends a message to B, and both parties set E2E. However, when A changes the device and re-enters the E2E password, the messages of A and B will no longer be encrypted messages

Today, I forgot my login password because I cleaned my mobile phone, so I used the background to change my login password, and then logged in to enter the app to enter the E2E password. All messages between me and the user 400137 are clear text and no longer encrypted. I can also log in with another device to reproduce this
![Screenshot_20230112-152057_Find Me](https://user-images.githubusercontent.com/10607980/212003746-0f6d4011-7521-4657-b2c1-fb1522f55b02.jpg)

**Comment by 337077418** [comment]
> Today, I forgot my login password because I cleaned my mobile phone, so I used the background to change my login password, and then logged in to enter the app to enter the E2E password. All messages between me and the user 400137 are clear text and no longer encrypted. I can also log in with another device to reproduce this ![Screenshot_20230112-152057_Find Me](https://user-images.githubusercontent.com/10607980/212003746-0f6d4011-7521-4657-b2c1-fb1522f55b02.jpg)

A sends a message to B, and both parties set E2E. However, when A changes the device and re-enters the E2E password, the messages of A and B will no longer be encrypted messages

**Comment by 337077418** [comment]
> { "s95WjokG9DjgLKs7dtMNKaoC8zvCCbybjo": { "ready": false, "roomId": "s95WjokG9DjgLKs7dtMNKaoC8zvCCbybjo", "userId": "tMNKaoC8zvCCbybjo", "establishing": false, "keyID": "", "sessionKeyExportedString": "", "roomKey": {}, "readyPromise": { "promise": { "_h": 1, "_i": 0, "_j": null, "_k": { "onRejected": null, "promise": { "_h": 0, "_i": 0, "_j": null, "_k": null } } } } }

When I open a new call C, the message will be encrypted normally：

{"ready":true,"roomId":"Edx2XHBmNeNfeTT7ctMNKaoC8zvCCbybjo","userId":"tMNKaoC8zvCCbybjo","establishing":false,"keyID":"eyJrdHkiOiJv","sessionKeyExportedString":"{\"kty\":\"oct\",\"alg\":\"A128CBC\",\"k\":\"Jkqhiz-VMWzFjsYnmxYtDA\",\"ext\":true,\"key_ops\":[\"encrypt\",\"decrypt\"]}","roomKey":{},"readyPromise":{"promise":{"_h":1,"_i":1,"_k":null}}}}

**Comment by diegolmello** [comment]
Can you try Rocket.Chat Experimental from Google Play?
We just released a new version containing https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4763

**Comment by 337077418** [comment]
> 你能试试 Google Play 上的 Rocket.Chat Experimental 吗？ 我们刚刚发布了一个包含[#4763的新版本](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4763)



> 你能试试Google Play上的Rocket.Chat Experimental吗？ 我们刚发布了一个包[#4763的新版本](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4763)



> 你能试试Google Play上的Rocket.Chat Experimental吗？ 我们刚发布了一个包[#4763的新版本](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4763)

Sorry, the client version I used: 4.35.0 Server version: 6.0 To reproduce this bug, you only need to log in once with another device and reset the E2E password. You will no longer be able to send encrypted information

**Comment by 337077418** [comment]
> 你能试试 Google Play 上的 Rocket.Chat Experimental 吗？ 我们刚刚发布了一个包含[#4763的新版本](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4763)


Sorry, this problem has not been solved. Repeat step 1. Log in to user A on device 1, initiate encrypted chat with user B, and then reset the E2E password on device 1 and user 2. After that, they can no longer send encrypted information between them

**Comment by 337077418** [comment]
https://user-images.githubusercontent.com/10607980/212297439-e2d240c1-ad9e-42ee-8f81-6766d62d886c.mp4

**Comment by diegolmello** [comment]
I'm not able to reproduce it on https://open.rocket.chat.
Can you try there?

> Client version: 4.35.0
What's the build version? It should be 36968 or higher.

**Comment by 337077418** [comment]
> I'm not able to reproduce it on https://open.rocket.chat. Can you try there?
> 
> > Client version: 4.35.0
> > What's the build version? It should be 36968 or higher.

https://open.rocket.chat/ Can't open encrypted chat, I use https://github.com/RocketChat/Rocket.Chat Running server

**Comment by 337077418** [comment]
> I'm not able to reproduce it on https://open.rocket.chat. Can you try there?
> 
> > Client version: 4.35.0
> > What's the build version? It should be 36968 or higher.

Unable to open encrypted chat. It seems that the server you provided does not have the settings to open encrypted chat. I use https://github.com/RocketChat/Rocket.Chat Running server

**Comment by 337077418** [comment]
> > 我无法在https://open.rocket.chat上重现它。你可以在那里试试吗？
> > > 客户端版本：4.35.0
> > > 构建版本是什么？它应该是 36968 或更高。
> 
> https://open.rocket.chat/。无法打开加密聊天。您提供的服务器似乎没有打开加密聊天的设置。我使用https://github.com/RocketChat/Rocket.Chat运行服务器
> 
> 1、重复步骤1：设备1登录用户A，设备2登录用户B。发送端到端加密聊天消息后，切换设备登录。设备1登录用户B后，设备2登录用户B用户 A 并重置端到端密码。问题再次出现。
> 
> 并且不能显示他们的历史加密信息/
> 
> 2.0、找不到收到的文件路径
> 
> 2.1、今天发现一个新问题。发送一些文件类型的消息时，用户点击会议闪回。例如，XXX.info 文件

If you can, please provide an email. I will send the complete video. The video file is too large

**Comment by 337077418** [comment]
[SVID_20230115_150329_1.zip](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/10419636/SVID_20230115_150329_1.zip)

**Comment by 337077418** [comment]
Today, there are new bugs reset login password in the background - clear chat room in the background - app reset E2E password

Send Message Crash



The reason is that the login password of a testing machine was forgotten, and the background management was used to reset the password for it. After it logged in and reset the E2E password, it opened the message list. The sent messages were all clear text messages, and the historical encrypted messages were no longer displayed. Then the background was used to clear its chat room, and then a new chat window was opened. The sending message app crashed

**Comment by 337077418** [comment]
> Today, there are new bugs reset login password in the background - clear chat room in the background - app reset E2E password
> 
> Send Message Crash
> 
> The reason is that the login password of a testing machine was forgotten, and the background management was used to reset the password for it. After it logged in and reset the E2E password, it opened the message list. The sent messages were all clear text messages, and the historical encrypted messages were no longer displayed. Then the background was used to clear its chat room, and then a new chat window was opened. The sending message app crashed

It is suggested to add a log upload function to facilitate developers to troubleshoot problems

**Comment by 337077418** [comment]
I'm sure that just resetting the user's login password in the background will cause a series of bugs: 1. Reset the E2E password, the window with historical information, and sending messages is no longer encrypted chat. 2. Click a new chat window, and the first time you send messages will crash: java.lang.String cannot be cast to com.facebook.react.bridge.ReadableNativeMap

**Comment by 337077418** [comment]
> I'm sure that just resetting the user's login password in the background will cause a series of bugs: 1. Reset the E2E password, the window with historical information, and sending messages is no longer encrypted chat. 2. Click a new chat window, and the first time you send messages will crash: java.lang.String cannot be cast to com.facebook.react.bridge.ReadableNativeMap ![Screenshot_20230118-153324_ DEBUG RocketChat Experimental](https://user-images.githubusercontent.com/10607980/213110913-809e222c-263e-4573-bbcf-ef7d465ad86a.jpg)

{"_h":0,"_i":0,"_j":null,"_k":null}-----{"ready":false,"roomId":"2RCmn5HM3ryZNLoyFZf3JW6yyJw4GLFL93","userId":"Zf3JW6yyJw4GLFL93","establishing":false,"keyID":"","sessionKeyExportedString":"","roomKey":{},"readyPromise":{"promise":{"_h":1,"_i":0,"_j":null,"_k":{"onRejected":null,"promise":{"_h":0,"_i":0,"_j":null,"_k":null}}}}}

**Comment by 337077418** [comment]
Find the cause of the problem in the database, e2e.public_ The value stored in the key field is different from that of normal user. The value of abnormal user is String, and that of normal user is json

**Comment by paviad** [comment]
Thank you @337077418 I have been banging my head against this problem for days!

I would like to clarify that the bad entry is the user key `e2e.public_key` which for bad users is not a JSON value but rather a string value. This Mongo command will yield the bad users `db.users.find({'e2e.public_key':{$regex:/^"/}},{username:1,_id:0})`

I am still investigating what part of the code causes these bad keys to be stored...

**Comment by paviad** [comment]
I actually think there is more to this than my fix. My fix does NOT solve the issue of switching devices, although it does solve another major issue.

The problem with switching between a mobile device and a browser is currently hard to solve. It stems from the fact that crypto code on the browser uses [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) while crypto on mobile uses [react-native-simple-crypto](https://www.npmjs.com/package/react-native-simple-crypto) - these two libraries are NOT compatible.

It all boils down to the mechanism by which the user's E2E password is converted to a key, the two libraries produce different keys for the same password.

There are two ways to solve this, the hard but right way, and the quick and dirty way:

## Correct

Implement the _SubtleCrypto_ library fully in react native, this is a major undertaking, but if done will make the two devices completely compatible.

## Quick and Dirty

Weaken the cryptographic strength of the key derivation mechanism, and implement it in such a way that is identical in browser and mobile.

I do hope the community somehow achieves the 1st option.

**Comment by paviad** [comment]
I believe I have found the issue, it is a bug in the Rocket Chat adaptation of the library `react-native-simple-crypto` - I have submitted a PR here: https://github.com/RocketChat/react-native-simple-crypto/pull/4

**Comment by mmaass** [comment]
> I believe I have found the issue, it is a bug in the Rocket Chat adaptation of the library `react-native-simple-crypto` - I have submitted a PR here: [RocketChat/react-native-simple-crypto#4](https://github.com/RocketChat/react-native-simple-crypto/pull/4)

Thanks. I've also lost 2-3 days until i found the issue and your solution. Our problem was that keypairs generated with Android would not work on iOS. The decryption of the E2EKey of a subscription (encrypted room key) resulted in an empty string. Can confirm your fix solves this.
