### ISSUE TITLE
Increase border radius on MessageAvatar as small

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#4808]
#### Overview
We need to render all avatars with border radius 4.
We did it to almost all components of the app recently, but `<Avatar small />` is still as 2.

We need to evaluate other places, but removing this line [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/a1580811ed20b9f806aa6066a27ea70f3e80cb42/app/containers/message/MessageAvatar.tsx#L21) might fix it.

#### To be done
- When small, apply border radius = 4

**Comment by Bhishek-Parmar** [comment]
Hello @diegolmello, I would definitely like to improve it. We want to render avatars with a border radius of 4 regardless of the value of the small prop. 

Should I change:
` borderRadius={small ? 2 : 4}`
 
to:
` borderRadius =4` 
or should I still use the ternary operator to handle both true/false values? 
I am looking forward to a quick reply.

**Comment by diegolmello** [comment]
Hey @Bhishek-Parmar!
Yes, you can just make it fixed 4.
Thanks!

**Comment by Bhishek-Parmar** [comment]
Thanks for reply.

Might be silly to ask but I am facing this problem while doing git commit (it stucks there)
![Screenshot 2023-01-16 192715](https://user-images.githubusercontent.com/92162796/212695373-dc40ed88-ec3b-4391-b306-e10fa11e4cb5.png)

**Comment by Hasnaat-Iftikhar** [comment]
I want to work on this issue. Please assign me this issue If this is still open. Thank you!

**Comment by Gua00va** [comment]
Hey!! I want to work on this issue. Can you assign it to me?
