### ISSUE TITLE
Apply "Sentence case" to titles and actions

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#4811]
Rocket.Chat uses [Sentence case](https://convertcase.net/sentence-case/) as a standard. We need to apply that to our mobile apps as well.

As a first step on this effort, we’re going to do it only on the files we’re sure about: the latin languages (es, pt, it) + english.

Evaluate case by case in order to prevent changing settings or given names cases, like Rocket.Chat.

**Comment by priyanshusaini105** [comment]
claim

**Comment by priyanshusaini105** [comment]
> Rocket.Chat uses [Sentence case](https://convertcase.net/sentence-case/) as a standard. We need to apply that to our mobile apps as well.
> 
> As a first step on this effort, we’re going to do it only on the files we’re sure about: the latin languages (es, pt, it) + english.
> 
> Evaluate case by case in order to prevent changing settings or given names cases, like Rocket.Chat.



> Rocket.Chat uses [Sentence case](https://convertcase.net/sentence-case/) as a standard. We need to apply that to our mobile apps as well.
> 
> As a first step on this effort, we’re going to do it only on the files we’re sure about: the latin languages (es, pt, it) + english.
> 
> Evaluate case by case in order to prevent changing settings or given names cases, like Rocket.Chat.

claim

**Comment by jainromil56** [comment]
Hi @diegolmello,
Do we need to change list items and titles which we display in app if that's the case then we might need to put conditions for specific languages as you mentioned or should we put this changes directly to components i.e. .tsx files but that won't be language specific
Please let me know if I am wrong

**Comment by thapar-vansh** [comment]
Hey @diegolmello , can you please review my pr .Thanks !

**Comment by abhinavvsinhaa** [comment]
Hey @diegolmello, can I contribute to this issue? As I'm just starting out my with open source development.

**Comment by Aditya-eddy** [comment]
claim

**Comment by diegolmello** [comment]
Already fixed
