### ISSUE TITLE
Set download file path

### ISSUE THREAD

**Issue by ldm0330** [RocketChat/Rocket.Chat.ReactNative#4813]
I want to copy the file sent to me on my mobile phone, but I can't find the file in Huawei's mobile phone. Where can I specify the path to download the file in the code? Thank you very much for your help

- Rocket.Chat Server Version:5.4.1
- Rocket.Chat App Version:4.35
- Device Name: HUAWEI P40
- OS Version: HarmonyOS 3.0

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/fbb05fa0d3b9a903c1e724edc703e610c437439d/app/views/AttachmentView.tsx#L144
