### ISSUE TITLE
apk build doesn't  work 

### ISSUE THREAD

**Issue by MahmoudMamdoouh** [RocketChat/Rocket.Chat.ReactNative#4814]
Gives me the below error

<img width="1597" alt="Screenshot 2023-01-15 at 2 31 36 PM" src="https://user-images.githubusercontent.com/88037883/212540778-06e830c3-022f-4217-a31c-a1d1ecc00dd5.png">

**Comment by diegolmello** [comment]
Firebase is misconfigured apparently.

**Comment by MahmoudMamdoouh** [comment]
@diegolmello  any help on what to do
it works fine with when building "android-whitelabel" but otherwise it doesn't 
even in ./gradlew assembleDebug  or Release

**Comment by diegolmello** [comment]
`./gradlew assembleDebug or Release`

It won't work like that.
The project has multiple build flavors.
When you run android-whitelabel, you're running `experimentalPlayDebug`.
If you're looking for release, then use `experimentalPlayRelease`.

**Comment by MahmoudMamdoouh** [comment]
and if i want to build an apk to share what do I do ??
