### ISSUE TITLE
Error running Rocket chat app on M1 devices

### ISSUE THREAD

**Issue by MuhtasimTanmoy** [RocketChat/Rocket.Chat.ReactNative#4821]
### Description:

While building this project, it throws errors in `NotificationService`.

<img width="293" alt="Screenshot 2023-01-17 at 12 17 27 PM" src="https://user-images.githubusercontent.com/19208687/212823799-e9508c6c-6dbd-4257-8d7c-907b958d3d40.png">

Though this is solved by manually linking the framework in `Build Phases -> Link Binary With Libraries -> Selecting Exav.xcframework` and consequently, another one named `ExFileSystem.xcframework`.

But eventually got stuck in this error

<img width="293" alt="Screenshot 2023-01-17 at 1 14 36 PM" src="https://user-images.githubusercontent.com/19208687/212833305-770e2d27-4a70-47cf-945a-bf435b00b054.png">

### Environment Information:

- Rocket.Chat Server Version: 5.4.1 ( N/ A )
- Rocket.Chat App Version: 4.35.0
- Device Name: Simulator iOS 14
- OS Version: MacOS Ventura Version 13.0.1

### Steps to reproduce:

I followed these steps to run the `RocketChat` iOS app
```
yarn
cd ios
npx pod-install
yarn ios
```

### Expected behavior:

Should build and run in simulator

### Actual behavior:

Build got stuck at `Library not found for -lPods-defaults-NotificationService` error

### Additional context:
- Running the same codebase in mac-intel produced no error
- In `Pods -> Products` the following files are marked red
<img width="366" alt="Screenshot 2023-01-17 at 1 21 23 PM" src="https://user-images.githubusercontent.com/19208687/212834473-1f09e166-7805-4bed-95bd-0ff18cc124d2.png">

### What I am looking for:
- Solution to this error
- What configurations I need to change to make it work and why?
- Supporting documents that clearly describes this build process

**Comment by diegolmello** [comment]
Can you try on Node 14.20.0?

**Comment by MuhtasimTanmoy** [comment]
I am using `Node v14.21.2`. Do I specifically have to use `14.20.0`?

**Comment by diegolmello** [comment]
Not really. One of the common issues is using a Node version without M1 support, forcing the use of Rosetta.
Your version might work already.

**Comment by MuhtasimTanmoy** [comment]
Forcing the use of Rosetta worked for me. Though wondering why it didn't work otherwise. Thanks anyway.
