### ISSUE TITLE
Channel member list doesn't show all members by default

### ISSUE THREAD

**Issue by krumelmonster** [RocketChat/Rocket.Chat.ReactNative#4822]
### Description:

In the mobile apps, when choosing "Members (999 members)" from the channel actions, only online members are listed/searched. It is possible to list/search all members by pressing the small funnel icon in the upper right corner, then choosing "All" but this setting does not persist and the icon is easily overlooked.

### Environment Information:

- Rocket.Chat Server Version: 5.4
- Rocket.Chat App Version: 4.43.0.36626

### Steps to reproduce:

1. Open a channel in a mobile app
2. press the channel name in the header to open channel actions menu
3. choose "Members (999 Members)"

### Expected behavior:

all 999 users are shown, especially when using the search function; If only a subset of users is shown, there has to be some clear visual indication of that.

### Actual behavior:

 - Not all 999 Members will be shown but only those online
 - Search will only search through online users

### Additional context:

This menu is used by moderators to ensure that a specific user is (not) present in a channel. The current behavior can easily lead to moderators wrongfully assuming a person wasn't in a channel, therefore failing to remove them from the room or vice versa, asking someone to join who was already present.

**Comment by diegolmello** [comment]
We changed this recently on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4757
The common complain was the other way around.
We're going to work on improving the UX.
Showing the users' presence and adding a visual indicator of the filter might help.

**Comment by diegolmello** [comment]
@krumelmonster I'm wrong, actually. We fixed it on #4757. It should land on next version. Thanks!
