### ISSUE TITLE
Mobile large Voice messaging error uploading

### ISSUE THREAD

**Issue by HazemHeakal** [RocketChat/Rocket.Chat.ReactNative#4824]
### Description:

voice message from browser mp3 and uploaded how ever the size of it but from mobile app m4a and not uploaded if it more than 1min
The same with file upload if it's more than 1MB

### Environment Information:

- Rocket.Chat Server Version: 5.4.1
- Rocket.Chat App Version: 1.36.0
- Device Name: VPS
- OS Version: Ubuntu 20.04.5 LTS (Focal Fossa)

`Deployment
Version  5.4.1
Apps Engine Version 1.36.0
Node Version  v14.18.3
MongoDB  5.0.14 / wiredTiger (oplog Enabled)`

### Steps to reproduce:

1. Open mobile app
2. select user and start voice record 
3. Keep record for more than 1 min then you will fetch upload error

### Expected behavior:

Sending the voice or file 

### Actual behavior:
![WhatsApp Image 2023-01-17 at 18 52 50](https://user-images.githubusercontent.com/56660650/212962040-fd0f16b7-c5b7-45b3-8ecc-46ee4968b64a.jpg)

### Additional context:

Also i noticed that when i try to send long voice from app I have to ways to send 
1- account chat that give me an error
![WhatsApp Image 2023-01-17 at 18 52 50](https://user-images.githubusercontent.com/56660650/212962240-cacc0efa-b744-4d47-a65e-4d52c8f97f09.jpg)

2- Second the admin panel that work with long voice message
![2](https://user-images.githubusercontent.com/56660650/212962384-4723ec2f-9a35-4258-a967-6513c50d8002.jpg)

**Comment by GleidsonDaniel** [comment]
It's working normally, it's probably a problem with your server.
Test on open server that should work. (https://open.rocket.chat/)

![Screenshot 2023-01-17 at 18 30 19](https://user-images.githubusercontent.com/18687097/213016505-d79dd8c0-b1c4-4a7c-8e11-67901b240353.png)
