### ISSUE TITLE
ios app crash by yarn ios in macbookpro m2 13.1

### ISSUE THREAD

**Issue by Mrezagolbaba** [RocketChat/Rocket.Chat.ReactNative#4825]
### Description:

When you want to run application by yarn ios it shows this error

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version:
- Device Name: Macbook pro M2
- OS Version: 13.1

### Steps to reproduce:

1.cd in root project
2. yarn && cd ios && pod install
3. yarn ios

### Expected behavior:

run appliaction 

### Actual behavior:
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/9501814/212964280-d423bc76-b3c9-424e-91ec-af60de11e505.png">

**Comment by diegolmello** [comment]
Not an issue on the repo.
