### ISSUE TITLE
SSO login broken

### ISSUE THREAD

**Issue by pbenkoe** [RocketChat/Rocket.Chat.ReactNative#4834]
### Environment Information:

- Rocket.Chat Server Version: 5.4.1
- Rocket.Chat App Version: 4.34.0
- Device Name: iPhone (any)
- OS Version: iOS 16.2 (+ any?)

### Steps to reproduce:

1. Try to log in via SSO through the app
2. Enter workspace URL
3. Click connect, then login

### Expected behavior:

SSO Login webpage is loaded within the webview

### Actual behavior:

Blank webview is shown

### Additional context:

This used to work, but only broke maybe last month in December. Our users just started to reporting now, saying they weren't able to login ever since December or so, and are using the browser for now.

The Rocket.Chat Login webpage is shown if I access it from the browser. The blank page only shows up in the app.

Let me know if you need anything else I can provide.
Thank you!

**Comment by diegolmello** [comment]
FIxed on https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/3a1b06b86c191d355da30bf4dc44612b26e8fe14

**Comment by iooner** [comment]
> few weeks.
For a login broken ? What!?

**Comment by wget** [comment]
@diegolmello Thanks I see that the 4.35 published is fixing the issue.

But please put the right label on the PR :) This is not a simple fix, but a regression fix ^^
![Screenshot_20230124_210442](https://user-images.githubusercontent.com/2997662/214397540-9d5b4ac5-e14d-4728-9e05-b7a3222a984a.png)
