### ISSUE TITLE
App incorrectly showing info of a deleted room

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#4861]
### Description:

When following a link to a room that has been deleted, a confusing room info page is shown.

### Environment Information:

- Rocket.Chat Server Version: 5.4.1
- Rocket.Chat App Version: 4.35.0.37286
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Write a message in one channel highlighting a second channel.
2. In a browser, delete the second channel.
3. In the app, click on the channel highlight from step 1.

### Expected behavior:

The app tells me that this channel does not exist (anymore).

### Actual behavior:

The app shows an information page for the non-existing channel containing no information:

![Screenshot_20230124_212517_chat rocket android](https://user-images.githubusercontent.com/404840/214402705-5273e861-88e4-41e1-b57e-1a2b1c6b09d2.jpg)

**Comment by diegolmello** [comment]
Hey!
It looks like we're redirecting without confirming the room exists.
At the time the message was created, the room existed, so the backend added the room object to the message.
This is the logic in charge of rendering the `#` as highlighted or not. If you mention a room that doesn't exist, it's going to render as normal text.

However after you deleted the room, the object remain on the message and we're still able to click it.
We need to check if the room can be opened before navigating.
That should be done in 2 steps:
- Verify existence in local db first
- Fetch the content on backend

@paulchen Thanks for reporting! 👏🏼 👏🏼 👏🏼

**Comment by Aryan6290** [comment]
Hi! can you assign this to me?

**Comment by eliaslma** [comment]
Hey, can I work on this issue? @diegolmello
