### ISSUE TITLE
Whitelabel single-server android build failed

### ISSUE THREAD

**Issue by victorhodi** [RocketChat/Rocket.Chat.ReactNative#4867]
### Description:

**I'm trying to build a whitelabel version. I've followed the instructions to build but i've ran into an error when I tried to Build by android studio**

### Environment Information:

    Rocket.Chat App Version: 4.34.0
    OS Version: Windows 10
    glideVersion 7.6
    java version "19.0.2"

### Steps to reproduce:

1. yarn
2. build OfficialFossRelease variant

### Actual behavior:

> Task :expo:compileReleaseKotlin FAILED
e: C:\Users\user\Documents\Rocket.Chat.ReactNative-single-server\node_modules\expo\android\src\main\java\expo\modules\ReactNativeHostWrapperBase.kt: (50, 3): 'getUIImplementationProvider' overrides nothing
e: C:\Users\user\Documents\Rocket.Chat.ReactNative-single-server\node_modules\expo\android\src\main\java\expo\modules\ReactNativeHostWrapperBase.kt: (50, 76): Unresolved reference: UIImplementationProvider
e: C:\Users\user\Documents\Rocket.Chat.ReactNative-single-server\node_modules\expo\android\src\main\java\expo\modules\ReactNativeHostWrapperBase.kt: (51, 12): Not enough information to infer type variable T
e: C:\Users\user\Documents\Rocket.Chat.ReactNative-single-server\node_modules\expo\android\src\reactNativeHostWrapper68\expo\modules\ReactNativeHostWrapper.kt: (8, 38): Unresolved reference: RedBoxHandler
e: C:\Users\user\Documents\Rocket.Chat.ReactNative-single-server\node_modules\expo\android\src\reactNativeHostWrapper68\expo\modules\ReactNativeHostWrapper.kt: (34, 36): Unresolved reference: RedBoxHandler
e: C:\Users\user\Documents\Rocket.Chat.ReactNative-single-server\node_modules\expo\android\src\reactNativeHostWrapper68\expo\modules\ReactNativeHostWrapper.kt: (35, 12): Not enough information to infer type variable T

**Comment by badams77-cpu** [comment]
Was Having same problem, I had a different version of React Native in the package.lock as compared to
the version in android/build.gradle, and its 
  resolutionStrategy {
    force 'com.facebook.react:react-native:0.xx.y'
  }
}

Fixing this worked.
