### ISSUE TITLE
Verifying token error

### ISSUE THREAD

**Issue by alexhaiduk** [RocketChat/Rocket.Chat.ReactNative#4879]
### Description:

 При создании видио-конференции (jitsi) из приложения iOS на канале чата постоянно ошибка авторизации, в логах jitsi пишет не верный token. Если с браузера Safari на iOS создавать видео-конференцию, то все работает. С Android систем такой проблемы нет, и с любого браузера или десктопного приложения тоже без ошибок.

When creating a video conference (jitsi) from an iOS application on a chat channel, an authorization error is constantly occurring, an incorrect token is written in the jitsi logs. If you create a video conference from the Safari browser on iOS, then everything works. With Android systems, there is no such problem, and with any browser or desktop application, there are no errors either.

### Environment Information:

- Rocket.Chat Server Version: 4.5.5 (also tested on 5.4.2)
- Rocket.Chat App Version: 4.35.1.37441
- Device Name: iPhone (iOS)
- OS Version: 16.1 и 12.5.6

### Steps to reproduce:

1. Открываем канал (любой) в приложении на iPhone
    Open a channel (any) in the application on the iPhone
2. Создаем видео-конференцию или подключаемся к созданной
    Create a video conference or join an existing one

### Expected behavior:

Должны присоединится или создать видео-конференцию из приложения.
Must join or create a video conference from the application.

### Actual behavior:

Получаем ошибку авторизации (часть лога jitsi):
We get an authorization error (part of the jitsi log):
...
Feb 01 15:40:27 mod_bosh        info    New BOSH session, assigned it sid '******************'
Feb 01 15:40:27 general warn    Error verifying token err:not-allowed, reason:Invalid json
...
...
eb 01 15:39:07 mod_bosh        info    New BOSH session, assigned it sid '*************************'
Feb 01 15:39:07 general warn    Error verifying token err:not-allowed, reason:token required
...

### Additional context:

Такой проблемы не было в версии приложения 4.35.0
This problem was not in version 4.35.0 of the application

sorry for bad English

**Comment by diegolmello** [comment]
Can you translate that to english?

**Comment by GleidsonDaniel** [comment]
I tested calls with and without jwt here, entering an already created one and creating one from within the app and they all worked normally.
The strange thing is that you said that it worked in version 4.35.0, since it was exactly in that version that we launched the update for the new sdk and the sending of a token to the jitsi sdk was not configured (In that case it shouldn't work, because no token was passed).

What version of the server are you using (jitsi server).

@alexhaiduk

**Comment by alexhaiduk** [comment]
Jiitsi-meet version:
jitsi-meet-prosody/stable,now 1.0.6155-1
jitsi-meet-tokens/stable,now 1.0.6155-1
jitsi-meet-turnserver/stable,now 1.0.6155-1
jitsi-meet-web-config/stable,now 1.0.6155-1
jitsi-meet-web/stable,now 1.0.6155-1
jitsi-meet/stable,now 2.0.7287-1
jitsi-videobridge2/stable,now 2.1-681-g3544ed05-1
on Ubuntu-server 20.04

and checked on update:
jitsi-meet-prosody/stable,now 1.0.6943-1
jitsi-meet-tokens/stable,now 1.0.6943-1
jitsi-meet-turnserver/stable,now 1.0.6943-1
jitsi-meet-web-config/stable,now 1.0.6943-1
jitsi-meet-web/stable,now 1.0.6943-1
jitsi-meet/stable,now 2.0.8252-1
jitsi-videobridge2/stable,now 2.2-69-gad606ca2-1
on Ubuntu-server 20.04

The situation is the same for this issue on iOS, everything else works.
We also checked on docker-jitsi-meet (stable 8252 on ubuntu-server 20.04), and everything works fine there.
The problem turned out to be jitsi-meet.
Thank you.

**Comment by GleidsonDaniel** [comment]
No problem, at least it solved the problem.
