### ISSUE TITLE
[BUG] When the Light Mode Status Bar is not Readable

### ISSUE THREAD

**Issue by omertahaoztop** [RocketChat/Rocket.Chat.ReactNative#4889]
### Description:

When the entering any channel on dark mode status bar is readable, but when using light mode Status bar is not readable. This behavior is same in single server and official app.

#### Dark Mode:

![darkmode](https://user-images.githubusercontent.com/26715379/216463401-216933ed-7582-4c10-8858-c960e75350b7.jpg)

#### Light Mode:

![lightmode](https://user-images.githubusercontent.com/26715379/216463511-573272b3-8ba9-4f20-816c-9ddcb3a187ab.jpg)

### Environment Information:

- Rocket.Chat Server Version: 4.8.7
- Rocket.Chat App Version: 4.35.1 Single Server
- Device Name:  Android
- OS Version:  Android 12

**Comment by diegolmello** [comment]
I'm not able to reproduce it. Can you give us the steps to do it?

**Comment by omertahaoztop** [comment]
In my friend's phone(Android 12) if you switch to light mode Status bar is not readable like screenshot.

But in my phone (Android 11) everything is ok and readable. 

What is your Android version?

**Comment by thgoebel** [comment]
I have the same issue on Android 13 (with LineageOS 20).
On a clean install, not even logging in to the server, right after opening RocketChat for the first time.

Steps:

1. OS in light mode.
2. Open RocketChat => status bar text is light (but should be dark)
3. Change OS to dark mode via Quick Settings Tile
4. RocketChat status bar text is now light ✅ 
5. Change OS to light mode
6. RocketChat status bar text is now dark ✅ 
7. Close RocketChat and remove it from Recent Apps
8. Open RocketChat again
9. RocketChat status bar text is now light again (but should be dark)

Android 13
RocketChat 4.37.1 from F-Droid.

**Comment by thgoebel** [comment]
I still have this issue. The steps from my previous comment still work, exactly the same buggy behaviour. 

- Android 13
- RocketChat 4.40.0 with the apk downloaded [from the Github release](https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/4.40.0).
