### ISSUE TITLE
Android white label app with push notifications

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.ReactNative#4893]
### Environment Information:

- Rocket.Chat Server Version: 5.4.x
- Rocket.Chat App Version: 4.35.x single-server

Hi,

So I have followed the documentation of [building the Android white label app](https://developer.rocket.chat/mobile-app/mobile-app-white-labelling/android-app-white-labelling). Have build offiialplayrelease and experimental too.

According to the docs, I have to create a project on Firebase and copied over the `google-services.json` file to app, compiled the app with. All good so far.

Next went to Rocket chat administration Push section, entered the [server key and sender ID](https://developer.rocket.chat/mobile-app/mobile-app-white-labelling/configuring-push-notifications). Disabled the gateway.

Tried to test the app, no notifications at all. Then I went ahead to tested the app by sending a test notification from Firebase which the app received on all devices. But on tapping, the app opens and then close with a stack trace. And Firebase shows no messages are read or opened.

Is this the right setup?
![Screenshot_20230206_153413](https://user-images.githubusercontent.com/1280585/216949601-bc41bda8-e059-4017-b16b-496c9cdef650.png)

![Screenshot_20230206_153506](https://user-images.githubusercontent.com/1280585/216949824-db6bb666-687c-410b-bf59-78a7b4e99ae6.png)

As RC is using legacy Firebase API, where server key and sender ID are entered in RC Push section. But `google-services.json` has none of these values.

I found this [SO post](https://stackoverflow.com/questions/73103326/push-notifications-not-working-on-white-label-rocket-chat-app), but no clear explanation at least for me.

At this point I am not sure what I am missing or doing wrong.

Any help would be appreciated.

**Comment by mmarif4u** [comment]
Thanks.

This is the current `google-services.json` downloaded from Firebase (truncated).

```
{
  "project_info": {
    "project_number": "3435345435",
    "project_id": "dummy-app",
    "storage_bucket": "dummy-app.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:3435345435:android:dummy",
        "android_client_info": {
          "package_name": "chat.rocket.dummy"
        }
      },
      "oauth_client": [
        {
          "client_id": "3435345435-dummy.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "dummy"
        }
      ],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": [
            {
              "client_id": "3435345435-dummy.apps.googleusercontent.com",
              "client_type": 3
            }
          ]
        }
      }
    }
  ],
  "configuration_version": "1"
}
```

Is there a document which highlight what part to remove and add etc?

**Comment by mmarif4u** [comment]
I am also trying to catch the error/info related to push on the server via logs, but I don't see anything related to it.

`snap logs -f rocketchat-server.rocketchat-server`

**Comment by mmarif4u** [comment]
So I get this from the logs now (truncated), does it alarm anything. I see success 1 in it but still no luck.

```
{"level":20,"time":"2023-02-06T15:25:25.209Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"Sending notification {\"createdAt\":\"2023-02-06T15:25:25.205Z\",\"createdBy\":\"<SERVER>\",\"sent\":false,\"sending\":0,\"from\":\"push\",\"title\":\"admin12\",\"text\":\"hee\",\"userId\":\"JTDFy6WfMLNNFrsGf\",\"payload\":{\"host\":\"https://domain.com/\",\"messageId\":\"7ff9n5jjWotu5ku5x\",\"notificationType\":\"message\",\"rid\":\"JTDFy6WfMLNNrsGfXWNFojQqWcY8ahzkT\",\"sender\":{\"_id\":\"XWFojQqWcY8ahzkT\",\"username\":\"admin12\",\"name\":\"Administrator\"},\"senderName\":\"admin12\",\"type\":\"d\"},\"badge\":3,\"sound\":\"default\",\"notId\":799791387,\"apn\":{\"category\":\"MESSAGE\"},\"gcm\":{\"image\":\"https://domain.com/images/logo/android-chrome-192x192.png\",\"style\":\"inbox\"}}"} {"level":20,"time":"2023-02-06T15:25:25.210Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"send message \"admin12\" to userId 'JTDFy6fMLNNFrsGf'"} {"level":20,"time":"2023-02-06T15:25:25.224Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"send to token {\"gcm\":\"enGX9CZYQe6XhB_Y:APAC38gqNHPhWfwhYZFp8wSwjtu4TQ2M0Hvr1RyKUAdOQ4fmiBqY_N6o-pxgJ6fivI650zjyIQ\"}"} {"level":20,"time":"2023-02-06T15:25:25.225Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"send to token {\"gcm\":\"enGX9uOKzhB_Y:APA91bFZqNHPhWfwhYZ0A0ZI1wcSh3vr1RyKUAdOQ4fmiBqY_N6o-pxgJ6fivI650zjyIQ\"}"} {"level":20,"time":"2023-02-06T15:25:25.227Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"sendGCM [\"enGX9ZhB_Y:APA91bFZCnTq7Q17uECKNFp8wSwjtu4TQ2M0Hvr1RyKUAdOQ4fmiBqY_N6o-pxgJ6fivI650zjyIQ\"] {\"createdAt\":\"2023-02-06T15:25:25.205Z\",\"createdBy\":\"<SERVER>\",\"sent\":false,\"sending\":0,\"from\":\"push\",\"title\":\"admin12\",\"text\":\"hee\",\"userId\":\"JTDFy6WfMLNNFrsGf\",\"payload\":{\"host\":\"https://domain.com/\",\"messageId\":\"7ff5jjWotu5ku5x\",\"notificationType\":\"message\",\"rid\":\"JTDFyMLNNFrsGfXWNFojQqWc8ahzkT\",\"sender\":{\"_id\":\"XFojQq8ahzkT\",\"username\":\"admin12\",\"name\":\"Administrator\"},\"senderName\":\"admin12\",\"type\":\"d\"},\"badge\":3,\"sound\":\"default\",\"notId\":799791387,\"apn\":{\"category\":\"MESSAGE\"},\"gcm\":{\"image\":\"https://domain.com/images/logo/android-chrome-192x192.png\",\"style\":\"inbox\"},\"image\":\"https://domain.com/images/logo/android-chrome-192x192.png\",\"style\":\"inbox\"}"} {"level":20,"time":"2023-02-06T15:25:25.229Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"For devices running Android 8.0 or later you are required to provide an android_channel_id. See https://github.com/raix/push/issues/341 for more info"} {"level":20,"time":"2023-02-06T15:25:25.231Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"Create GCM Sender using \"Aif2uuqwy1neSv_WumEheJfgfdgdfgfdgoj5\""} {"level":20,"time":"2023-02-06T15:25:25.232Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"A:Send message to: enGX9CZY1wcSh3Zw0mo2J5hirAg5TZQAKdmNOXnu4TQ2M0Hvr1RyKUAdOQ4fmiBqY_N6o-pxgJ6fivI650zjyIQ"} {"level":20,"time":"2023-02-06T15:25:25.235Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"Sent message \"admin12\" to 0 ios apps 1 android apps"} {"level":20,"time":"2023-02-06T15:25:25.260Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"GUIDE: The \"appTokensCollection\" - No APN clients have registered on the server yet..."} {"level":20,"time":"2023-02-06T15:25:25.423Z","pid":14102,"hostname":"App8gb4n","name":"Push","msg":"ANDROID: Result of sender","result":{"multicast_id":6383613512634623000,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1675697125375858%1bcce30034af1a"}]}}
```

**Comment by mmarif4u** [comment]
I don't know if this will help or would cause any issue, the server is behind Apache reverse proxy.

**Comment by diegolmello** [comment]
> Is there a document which highlight what part to remove and add etc?

You should download and paste the file without changing the content.

> Tried to test the app, no notifications at all. Then I went ahead to tested the app by sending a test notification from Firebase which the app received on all devices.

When you login from the app, it sends the device push token to Rocket.Chat, which is going to be used to send the push notifications to FCM. Login and debug if the push token is actually there.

If the logs from RC are saying the push notification was delivered, you'll have to debug your app with logcat to understand if there's any issues with the app.
