### ISSUE TITLE
F-Droid build crashes on launch

### ISSUE THREAD

**Issue by tensor5g** [RocketChat/Rocket.Chat.ReactNative#4897]
### Description:

The latest build released on F-Droid from about 2 days ago (4.35.1 according to app info) crashes immediately upon launch. I've tried reinstalling and restarting phone, but this hasn't worked. Google play version appears to work fine.

### Environment Information:

- Rocket.Chat App Version: 4.35.1
- OS Version: Android 13

### Steps to reproduce:

1. Install rocket.chat from F-Droid
2. Launch app

**Comment by saenglert** [comment]
Same issue here using LineageOS 19.

**Comment by alexander-prock** [comment]
Same issue on latest GrapheneOS (Android 13). I tried downgrading to app version 4.35.0 via F-Droid, but this version has the issue too. However, version 4.34.0 works for me.

**Comment by e-jim** [comment]
The issue persists in 4.36.0

**Comment by merkste** [comment]
Same here (Moto G7 plus, Android 10,  Rocket.Chat 4.35.1). Interestingly, the Google PlayStore version works.

**Comment by diegolmello** [comment]
@haarp That's it. Can you contribute with a PR?

**Comment by linsui** [comment]
The problem is introduced by https://github.com/RocketChat/Rocket.Chat.ReactNative/commit/23f716c280e261e82b4387cb5046e1c70ace77bb. I'll update our patch accordingly.

**Comment by diegolmello** [comment]
Thanks, @linsui!

**Comment by linsui** [comment]
The fixed version is available now.
