### ISSUE TITLE
app crash when search 

### ISSUE THREAD

**Issue by dano0b** [RocketChat/Rocket.Chat.ReactNative#491]
- Your Rocket.Chat.Android app version: 1.4.1.4576

- Your Rocket.Chat server version: cloud rocket.chat

- Device model (or emulator) you're running with: Nokia 8 - Android 8.1.0

- Steps to reproduce: click search icon

App crashes directly when trying to search

**Comment by diegolmello** [comment]
@dano0b Thanks. I'll fix it soon.

**Comment by diegolmello** [comment]
@dano0b Just submitted 1.4.2 to Google Play. It should appear in a few.
Let me know if it's working for you.

**Comment by dano0b** [comment]
Sorry for the late response(Bangkok Timezone...), search works again. Thanks @diegolmello
