### ISSUE TITLE
Add support for tasks and unordered list markdown

### ISSUE THREAD

**Issue by imf-ali** [RocketChat/Rocket.Chat.ReactNative#4927]
### Description:
Tasks and unordered list does not appear in correct format as that in RC web app.

### Environment Information:

- Rocket.Chat Server Version: open.rocket.chat (6.0.0)

### Steps to reproduce:

1. Tasks should display in expected form
2. Unordered list should display in expected form 

### Expected behavior:
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/42451210/221556723-06e154fc-e985-47e3-82bf-ccc14eba280f.png">

### Actual behavior:
![WhatsApp Image 2023-02-27 at 17 22 36](https://user-images.githubusercontent.com/42451210/221556989-9ce2b4e1-3475-4ec6-92d5-41943111e0ff.jpeg)

**Comment by imf-ali** [comment]
Hey @diegolmello,
Can you please have a look at this issue, and assign it to me? I want to take this up.

**Comment by imf-ali** [comment]
@diegolmello any update on this?

**Comment by GleidsonDaniel** [comment]
@imf-ali if you want to work on this task just open a PR fixing the issue.
