### ISSUE TITLE
(Bug): Room Info Page Links are not highlighed

### ISSUE THREAD

**Issue by AmanNegi** [RocketChat/Rocket.Chat.ReactNative#4933]
### Description:

In the App when we open the Room Info Page, we are presented with a Description, Topic, and other items. Here some links are present in the text, which are not easily visible as links. 

### Environment Information:

- Rocket.Chat Server Version: 6.0
- Rocket.Chat App Version: 4.35.1.374443
- Device Name: Realme 7 Pro
- OS Version:  Android 12

### Steps to reproduce:

1. Open the App and Join any Random Room in my case I joined (gsoc2023)
2. Open the Room and Click on The Room name at the top which will lead you to the actions page.
3. In the Actions Page Click on the Room name and you will be presented with a few details.
4. In the case of (gsoc2023) you can see the text that says `See Project Ideas` and `How to Start?`. These both are links however they are differentiable from normal text.

> DEMO: 
![usetldr_nw_u_2215329_vdo_gif_TlRIfa0szt](https://user-images.githubusercontent.com/37607224/221834924-5b2e3ce1-40f5-4b22-84a8-d8f891c58b1a.gif)

### Expected behavior:

It would be really great if the links are highlighted/underlined or just stands apart from normal text. So that user can figure out that it's a link.

**Comment by GleidsonDaniel** [comment]
Already has a fix for this #4905
