### ISSUE TITLE
npm i error

### ISSUE THREAD

**Issue by coderDancer** [RocketChat/Rocket.Chat.ReactNative#4935]
![image](https://user-images.githubusercontent.com/22238447/222403146-90dc1d0d-2c53-44a8-804b-7f727461cd19.png)
When installing dependencies, the non-npm dependencies in package.json are not pulled down

**Comment by GleidsonDaniel** [comment]
use yarn

**Comment by coderDancer** [comment]
> use yarn

Thanks
