### ISSUE TITLE
Cannot install Rocket.Chat Android App on SAMSUNG Galaxy A52s 5G (Android 13)

### ISSUE THREAD

**Issue by Jasonnor** [RocketChat/Rocket.Chat.ReactNative#4944]
### Description:

Cannot install Rocket.Chat Android App on SAMSUNG Galaxy A52s 5G (Android 13).

### Environment Information:

- Rocket.Chat Server Version: N/A
- Rocket.Chat App Version: 4.36.0
- Device Name: SAMSUNG Galaxy A52s 5G
- OS Version: Android 13

### Steps to reproduce:

1. Go to [GitHub Release](https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/4.36.0), and download [android-official-release.apk](https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/download/4.36.0/android-official-release.apk)
2. Install on Android device

Or

1. Install Rocket.Chat App on [Google Play](https://play.google.com/store/apps/details?id=chat.rocket.android&hl=en&gl=US)

### Expected behavior:

Successfully install or update.

### Actual behavior:

Display "App not installed as package appears to be invalid" (應用程式套件無效，因此未能完成安裝。)

#### Mobile information

```
One UI 5.0
Android 13
Google Play system update: 2022/10/1
Baseband version: A528BZTU1DWA4
Core version: 5.4.147-qgki-25752227-abA528BZTU1DWA4 #1 Tue Jan 10 12:07:22 KST 2023
Version number: TP1A.220624.014.A528BZTU1DWA4
Android SE status: Enforcing SEPF SM-A528B_12_0001 Tue Jan 10 12:08:51 2023
Knox version: Knox 3.9 Knox API level 36 HDM 2.0-5
```

#### Screenshot

- Install / update from APK file
![333941080_220206267189315_6688743582997069918_n](https://user-images.githubusercontent.com/7609173/222651137-d2d42708-0535-4fc7-85d2-8e9f88501c16.jpg)
- Install from Google Play
![332924245_733527298487787_90361355840751433_n](https://user-images.githubusercontent.com/7609173/222651169-ead704c3-5970-44a6-823d-df51c6aaec5c.jpg)

**Comment by diegolmello** [comment]
Thanks for opening, but I can't see anything on metrics.
Installs look ok.
Can you send me a crash report on https://open.rocket.chat/direct/diego.mello?
https://developer.android.com/studio/debug/bug-report

**Comment by Jasonnor** [comment]
@diegolmello 
Thank you for your assistance, but I have discovered that the issue can be resolved by performing a complete uninstallation and reinstalling the latest APK. 
I apologize for forgetting to verify my previous version of Rocket.Chat before uninstalling it. 😥
The only information that can be confirmed is that the previous version was either version 4.33 or earlier, as I attempted to upgrade to version 4.34 and was still unable to resolve the issue. If you believe there are no further concerns, please feel free to close this issue. 
Thank you again for your help! 🙏
