### ISSUE TITLE
Links don’t work on iOS with Safari or builtin browser

### ISSUE THREAD

**Issue by ansiwen** [RocketChat/Rocket.Chat.ReactNative#4945]
### Description:

It seems like Rocket-Chat always creates so-called protocol-relative URLs from hostnames (which by itself is considered an anti-pattern nowadays), for example typing `google.com` in a message always creates a link like `//google.com`. If the app settings are set to use the built-in browser, it crashes with these links. If it is using Safari, it simply does nothing. Only when setting it to Chrome, the links work.

### Environment Information:

- Rocket.Chat Server Version: 5.4.3
- Rocket.Chat App Version: 4.36.0
- Device Name: iPhone 12 mini
- OS Version: iOS 16.3.1

**Comment by GleidsonDaniel** [comment]
Fixed on #4899
