### ISSUE TITLE
Duplicate interface definition for class 

### ISSUE THREAD

**Issue by VinodComlink** [RocketChat/Rocket.Chat.ReactNative#4959]
### Description:

Getting the Duplicate interface definition for class.

### Environment Information:

- Rocket.Chat Server Version:  
- Rocket.Chat App Version:  4.36.0
- Device Name:  Simulator
- OS Version: 16.2

### Steps to reproduce:

yarn ios

### Expected behavior:

App should nuild and install

### Actual behavior:

It failed with issues

### Additional context:

![Screenshot 2023-03-09 at 6 18 16 PM](https://user-images.githubusercontent.com/32677695/224029986-b23853c9-9423-4482-bf9b-cf5058eebe6f.png)

**Comment by diegolmello** [comment]
If you're on `develop` branch without touching anything, it's something on your env.
Either a misconfiguration, cache or Xcode.

**Comment by VinodComlink** [comment]
I am on master branch.

**Comment by VinodComlink** [comment]
![Screenshot 2023-03-09 at 6 47 31 PM](https://user-images.githubusercontent.com/32677695/224034968-900c3d70-5ed2-4a49-9a5d-75064166390b.png)

**Comment by VinodComlink** [comment]
let me try this quickly

**Comment by VinodComlink** [comment]
Same issue on the develop branch as well 

![Screenshot 2023-03-09 at 7 38 56 PM](https://user-images.githubusercontent.com/32677695/224050334-715057ad-3548-494d-9595-adce1f2b63ae.png)

**Comment by diegolmello** [comment]
It's definitely something on your environment.
If you're on M1, search for issues related to your CPU.
Make sure you're running a compatible version of Node as well.

**Comment by VinodComlink** [comment]
I am on node versions- v18.15.0
Not having M1.

Please suggest where I can get the node version capability for each release.

**Comment by diegolmello** [comment]
I meant Node version depending on the CPU.
If you're on Intel, you should be fine.

**Comment by VinodComlink** [comment]
Yes, I am on intel.  I just a saw something while installing the pods. Coupold that lean the issue ?

 
![Screenshot 2023-03-10 at 5 10 45 PM](https://user-images.githubusercontent.com/32677695/224307207-64b701a5-b94e-4203-a600-0ca4d0d33eb4.png)

**Comment by VinodComlink** [comment]
When I tried to install the pods using root it won't allow and when I shift to admin right user it gives this permission related error. Pleas suggest -

![Screenshot 2023-03-10 at 5 12 11 PM](https://user-images.githubusercontent.com/32677695/224307402-5c21e19c-3c50-4b60-93a6-102e7e3db4bd.png)

**Comment by GleidsonDaniel** [comment]
What is your Xcode version?

**Comment by VinodComlink** [comment]
Version 14.2 (14C18)

**Comment by GleidsonDaniel** [comment]
Did you try `pod deintegrate` and `pod install` again?

**Comment by GleidsonDaniel** [comment]
Another thing when cloning a project from scratch RN does this error happen?

**Comment by VinodComlink** [comment]
Yes, While installing the pods back getting a permission related issue - 

```
Patching imports for file: /Users/vinodjat/Rocket.Chat.ReactNative/node_modules/react-native-config-reader/ios/RNConfigReader.h
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EACCES: permission denied, open '/Users/vinodjat/Rocket.Chat.ReactNative/node_modules/rn-extensions-share/ios/ReactNativeShareExtension.h'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/vinodjat/Rocket.Chat.ReactNative/node_modules/rn-extensions-share/ios/ReactNativeShareExtension.h'
}

Node.js v18.15.0
expo_patch_react_imports! took 0.317 seconds to transform files.
Pod installation complete! There are 92 dependencies from the Podfile and 112 total pods installed.

```

**Comment by VinodComlink** [comment]
> Another thing when cloning a project from scratch RN does this error happen?

I got a fresh clone from your git.

**Comment by GleidsonDaniel** [comment]
So your pod installation is in error, it won't work at all.
Fix this error above and see if you continue with this problem reported here.

**Comment by VinodComlink** [comment]
All the permissions related issue have fixed now and able to install pod successfully. However trying to run the app now and getting different error now -

![Screenshot 2023-03-11 at 4 14 55 PM](https://user-images.githubusercontent.com/32677695/224479919-6b0575be-1c23-445d-93b4-0dba3bee2679.png)
