### ISSUE TITLE
Android whitelabel

### ISSUE THREAD

**Issue by androidappsergio** [RocketChat/Rocket.Chat.ReactNative#4960]
### Description:

Hello,
I want to run my white-label app for Android and I haven't any problem with the guide https://developer.rocket.chat/mobile-app/mobile-app-white-labelling/android-app-white-labelling , finally I run my white-label with the experimentalPlayRelease without problems, butI have two questions:

1) I have used "develope" branch is this correct ? What branch I have to use ? Is "develope" branch an stable branch for white-label (experimentalPlayRelease)? ( I haven't used single-server because I have my own server)

2) If I want to upload to Google Play my white-label app I have to compile experimentalPlayRelease is that ok? Or I have to compile with another BuildVariant ? At the moment I have compiled and I have upload version in GooglePlay with experimentalPlayRelease and there is not issue. 

### Environment Information:

- Rocket.Chat App Version: experimentalPlayRelease whitelabel

Thanks in advance

**Comment by diegolmello** [comment]
Hey.

> I haven't used single-server because I have my own server

The official app supports multiple workspaces at the same time. If you're building a whitelabel app, you probably want your app to connect only to your workspace. That's why you need single-server branch.

> I have to compile experimentalPlayRelease is that ok

That's correct.

**Comment by androidappsergio** [comment]
Thanks, but the branch..... It doesn't matter what branch I'm in ? I have seen master, develope,.....From which branch do I build my app?

**Comment by diegolmello** [comment]
You `single-server`

**Comment by androidappsergio** [comment]
Sorry I did not explain myself well, but I need multi-server....If I compile with single-server automatically user will be in rocketChat server and I want the user can put my server (chat.myenterprise.es) or another.... 

If at the end I compile with single-server where I have to change the server so that the user will be in my server  (chat.myenterprise.es) ?

**Comment by diegolmello** [comment]
You'll have to implement it yourself

**Comment by androidappsergio** [comment]
Ok Diego, the last question: I don't want to implement it ...so I will use multi-server, what branch is the stable for it for white-label: master, develope.......any ?
