### ISSUE TITLE
Branch in white-label

### ISSUE THREAD

**Issue by androidappsergio** [RocketChat/Rocket.Chat.ReactNative#4979]
### Description:

Im building my white-label app but I have a doubt....

What branch I have to use when I build a white-label app ? The guide tell me about to use the single-server branch but I wan't to use it because I need multi-server. 

Is there any stable branch a part form single-server that is stable for this purpose ? develope, master,.......?

Thanks

**Comment by diegolmello** [comment]
You already asked this question https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/4960
Stop duplicating issues.
