### ISSUE TITLE
About the problem that Android RocketchatRN 4.36 cannot compile

### ISSUE THREAD

**Issue by YICONG0603** [RocketChat/Rocket.Chat.ReactNative#4981]
### Description:
When I compiled Rockechat.RN 4.36 with RN 0.71, the terminal issued many errors and deprecated function errors, most of which came from network reasons and (failed to download dependencies) FACEBOOK plugin reasons, I tried more than 20 recompilations (by means of DEBUG) Finally, the compilation was successful, but it could not run, (both ADV and physical machine were tested); helplessly, I returned from RN0.71 to RN0.68, and continued to try several times to compile, but this still appeared A non-running error. I hope the developer can help me, can you give me a list of component dependencies that can be successfully compiled and run?

### Environment Information:

- Rocket.Chat Server Version: Null
- Rocket.Chat App Version:4.36
- Device Name: Android
- OS Version: ubuntu
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
- info Fetching system and libraries information...
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.08 GB / 7.53 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
  Languages:
    Java: 11.0.18 - /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: RocketChat/react-native#51266d5ab8b4c3f04c0e8f207ea5db6056647104 => 0.68.6 
  npmGlobalPackages:
    *react-native*: Not Found
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
1.Android SDK Platform 33
2.Google APIs Intel x86 Atom System Image
3.SDK Tools 33.0.0

### Steps to reproduce:

1.Go to Rocket.Chat.ReactNative-4.36.0 folder
2. open terminal ：yarn
3. and next : yarn android

### Expected behavior:

Rocketchat.RN should work fine，and enter the login interface.
### Actual behavior:

ADV crash after startup 

### Additional context:

PIC
![2023-03-15 18-07-45 ](https://user-images.githubusercontent.com/124908098/225277610-eb5a04eb-dabf-4480-a833-2e26201c2434.png)

![Screenshot_20230315_181348](https://user-images.githubusercontent.com/124908098/225278897-cfdc113f-6831-42f9-a849-a7ec79f80604.png)

**Comment by diegolmello** [comment]
We don't support RN 0.71 yet. I've been working on it.
Same thing related to Android SDK 33.

Clone the repo on another folder and try `develop` branch again, so you're sure you didn't change anything.
