### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by rahulcomlink** [RocketChat/Rocket.Chat.ReactNative#4983]
### Description:

Application failed to build with below error related to Bug_snag

```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
root project 'RocketChatRN' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61
```

### kotlin version gradle

kotlin_version = "1.6.10"
kotlinVersion = '1.6.10'

we are also tried kotlin version 

kotlin_version = "1.5.31"
kotlinVersion = '1.5.31'

### Environment Information:

- Rocket.Chat Server Version: 
- Rocket.Chat App Version: 4.36.0
- Device Name: Vivo1920
- OS Version:  Android11

**Comment by rahulcomlink** [comment]
The supported version is 1.6.10, if you are trying to run an old version of the app we do not support old versions.

**Comment by diegolmello** [comment]
@rahulcomlink This is a Runtime error. There's probably a crash happening.
You can check it with logcat.

**Comment by rahulcomlink** [comment]
@diegolmello I am unable to run & build single server branch code & unable to yarn install 

could you please list out the environment detail : 

React native Version : 
Gradle version : 
Yarn Version : 
Kotlin version : 
class path of android : 

<img width="962" alt="Screenshot 2023-04-06 at 11 50 55 AM" src="https://user-images.githubusercontent.com/95681028/230288498-d6ad94d6-e13d-4eb6-ae56-f056c61917ff.png">

**Comment by diegolmello** [comment]
You shouldn't worry about most items on this list.
React Native, Gradle and Kotlin versions are specified on the repo and shouldn't be changed.
If you are changing them that might be the reason for failure.

Android path is either correctly set or not.
Yarn version doesn't really change much, but I'm using v1.22.19.
