### ISSUE TITLE
Notification push click issue

### ISSUE THREAD

**Issue by Rotomeca** [RocketChat/Rocket.Chat.ReactNative#4993]
### Description:

When you click on a push notification of a single-server application, instead of going into the conversation, it opens the application on a white screen.

### Environment Information:

- Rocket.Chat Server Version:5.4
- Rocket.Chat App Version: 4.34.0.5
- Device Name: Galaxy Z flip 4
- OS Version: Android 13/One UI 5.1

### Steps to reproduce:

1. Get a notification push
3. Click on the notification
4. And we are in the white screen

### Expected behavior:

Go to the discussion.

### Actual behavior:

![image](https://user-images.githubusercontent.com/28726532/226633331-61bae3f8-7f8c-4456-bef5-fe7822edbb63.png)

**Comment by diegolmello** [comment]
Make sure to point Site_URL to the correct workspace URL.
If it's still not working.
Debug this file https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/sagas/deepLinking.js

**Comment by Rotomeca** [comment]
How I test push notification in debug mode ?
