### ISSUE TITLE
single server freeze at debugging on connect

### ISSUE THREAD

**Issue by Rotomeca** [RocketChat/Rocket.Chat.ReactNative#5004]
### Description:

When I go on the dev menu, clic on "debug", when I connect, the app freeze and there are no error message. 

### Environment Information:

- Rocket.Chat Server Version: 5.4
- Rocket.Chat App Version: 4.34.0.5
- Device Name: Galaxy Z flip 4
- OS Version: Android 13/One UI 5.1

### Steps to reproduce:

1. Build the app with experimentalPlayDebug variant
2.  Show dev menu
3.  Clic on debug
4. Log

### Expected behavior:

Log on my rooms list and continue debugging

### Actual behavior:
Freeze on this page

![Screenshot_20230330_155649_Apitech_Continuum 1](https://user-images.githubusercontent.com/28726532/228860154-d0358736-102b-40b0-b1aa-dcb233360d23.jpg)

**Comment by Rotomeca** [comment]
Additional context:
It work when debug is not enabled

**Comment by diegolmello** [comment]
Are you using Flipper? https://blog.logrocket.com/debugging-react-native-apps-flipper/

**Comment by Rotomeca** [comment]
No, I use VSCODE with react native tool and I have disabled all breakpoint

**Comment by GleidsonDaniel** [comment]
This is a common RN error, there are actually several issues about this problem, this one for example is a current one:
https://github.com/facebook/react-native/issues/34615

In your case I'm pretty sure it won't work in Vscode because our app uses hermes, it should only work in flipper.

**Comment by Rotomeca** [comment]
Okay, I'll try hermes and I'll give a feedback when i'll test.

**Comment by Rotomeca** [comment]
I don't find how use flipper instead of hermes
