### ISSUE TITLE
How to use combination of Realtime and REST API ?

### ISSUE THREAD

**Issue by yatendra2001** [RocketChat/Rocket.Chat.ReactNative#5006]
**I am finding it quite challenging to figure out how to decide when to use Realtime API and REST API.**

Can anyone brief me on how React Native currently use these combinations and **how you guys decide when to use which one?**

I tried to figure it out and found React Native App also works similarly to [embedded chat](https://github.com/RocketChat/EmbeddedChat). It initializes the rocket chat SDK ([permalink](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/b51d7eeab3fc276098d136e291cfca9d14fdefb9/app/lib/services/sdk.ts#L16)) to use in the app. This SDK is used further for performing real-time functions lik

• connecting with rocket chat servers. ([permalink](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/b51d7eeab3fc276098d136e291cfca9d14fdefb9/app/lib/services/connect.ts#L52))
• Login using OTP, username password, OAuth etc. ([permalink](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/b51d7eeab3fc276098d136e291cfca9d14fdefb9/app/lib/services/connect.ts#L277))

It also leverages the rocket chat REST API to perform multiple chat features like creating channels, joining Room, reporting messages, and more. ([github](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/services/restApi.ts))

But I need more clarity in order to build a Flutter SDK for Rocket Chat.

Would highly appreciate it if anyone could help.

**Comment by diegolmello** [comment]
Hey @yatendra2001.
There's _ideal_ vs _current_ IMO.

The _ideal_ would be to use realtime only for events that need to update the UI over time, like user interactions (typing, uploading...), user presence, etc.

The _current_ is not there yet. Rocket.Chat was leveraging Meteor, which suggests you to use DDP for everything and that's what we did for quite some time.
We're still in the process of migrating to the ideal scenario.

In your case, I recommend you to use our repo as a guideline for what you need to do.
Most of the calls are already using the new way.

Our docs are helpful as well https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints

**Comment by yatendra2001** [comment]
Hey @diegolmello , Thanks!

This address most of my doubts. By recommending to use your repo, you mean Rocket.Chat.ReactNative repo right?
