### ISSUE TITLE
Can't build iOS single-server whitelabel

### ISSUE THREAD

**Issue by JakobZeller** [RocketChat/Rocket.Chat.ReactNative#5007]
### Description:

The iOS build fails and does not produce a running App. 

### Environment Information:

- Rocket.Chat Server Version: not relevant
- Rocket.Chat App Version: 4.36.0
- There is no target device, since the build fails.

Development Environment:
- Device Name: Mac mini (M1, 2020) 
- OS Version: macOS 12.1
- IDE + Version: 
  - XCode 13.4.1
  - VS Code 1.63.2

### Steps to reproduce:

1. pull the project and check out the single-server branch (https://developer.rocket.chat/mobile-app/mobile-app-white-labelling)
2. follow the iOS App White Labelling instructions on https://developer.rocket.chat/mobile-app/mobile-app-white-labelling/ios-app-white-labelling
3. "yarn ios" fails

Alternative for follow-up attempts:
1. rm -rf node_modules 
2. cd ios && pod deintegrate && cd ..
3. yarn 
4. npx pod-install 
5. yarn ios

### Actual behavior:

Build fails with the following problems shown in the terminal:

	The following build commands failed:

    EmitSwiftModule normal arm64 (in target 'react-native-jitsimeet-custom' from project 'Pods')
    CompileSwift normal arm64 /ProjectPath/Rocket.Chat.ReactNative/node_modules/@socialcode-rob1/react-native-jitsimeet-custom/ios/JitsiMeetViewController.swift (in target 'react-native-jitsimeet-custom' from project 'Pods')
    CompileSwift normal arm64 /ProjectPath/Rocket.Chat.ReactNative/node_modules/@socialcode-rob1/react-native-jitsimeet-custom/ios/JitsiMeetViewManager.swift (in target 'react-native-jitsimeet-custom' from project 'Pods')
    CompileSwift normal arm64 /ProjectPath/Rocket.Chat.ReactNative/node_modules/@socialcode-rob1/react-native-jitsimeet-custom/ios/JitsiMeetUtil.swift (in target 'react-native-jitsimeet-custom' from project 'Pods')
    CompileSwift normal arm64 /ProjectPath/Rocket.Chat.ReactNative/node_modules/@socialcode-rob1/react-native-jitsimeet-custom/ios/JitsiMeet.swift (in target 'react-native-jitsimeet-custom' from project 'Pods')
    CompileSwift normal arm64 /ProjectPath/Rocket.Chat.ReactNative/node_modules/@socialcode-rob1/react-native-jitsimeet-custom/ios/RNJitsiMeetView.swift (in target 'react-native-jitsimeet-custom' from project 'Pods')
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'react-native-jitsimeet-custom' from project 'Pods')
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'WatermelonDB' from project 'Pods')
	(8 failures)

### Additional context:

I followed the white labeling guide step by step and was able to successfully build the Android version.

**Comment by diegolmello** [comment]
You're almost there.
These env issues are common, so let's work on what's happening for you and update docs later, ok?

- Make sure you're on ruby 2.7.4.
- Run `pod deintegrate && bundle exec pod install` on `ios` folder.

**Comment by JakobZeller** [comment]
My installed ruby version is 2.7.8p255 and I had to run `pod deintegrate && bundle install && bundle exec pod install`. Unfortunately i got the same issues.

Afterwards I switched to ruby 2.7.4, cleaned the workingspace (https://stackoverflow.com/questions/74422258/rescue-in-block-in-activate-dependencies-could-not-find-rexml-0-among) und ran the provided commands again. Now I am getting build failures for JitsiMeetSDK. It seems like i have to upgrade my macOS + XCode versions.

`/Rocket.Chat.ReactNative/node_modules/@socialcode-rob1/react-native-jitsimeet-custom/ios/JitsiMeet.swift:2:8: failed to build module 'JitsiMeetSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.`

Apparently you need XCode v14.1 (macOS v13+) for Swift v5.7. I will upgrade my OS + XCode accordingly and update this post afterwards.

**Comment by GleidsonDaniel** [comment]
Only Xcode solves it, no need to update the system.

**Comment by JakobZeller** [comment]
"Xcode 14 requires a Mac running macOS Monterey 12.5 or later."

Unfortunately i am running macOS 12.1. So in my case i have to upgrade the OS.

**Comment by JakobZeller** [comment]
Final solution:

make sure to use 
1. macOS 12.5+
2. Xcode 14.1+
3. Ruby 2.7.4
4. dont change name, share and displayName in app.json
