### ISSUE TITLE
[Bug] Rocket.Chat mobile app oauth trouble

### ISSUE THREAD

**Issue by zebesh** [RocketChat/Rocket.Chat.ReactNative#5016]
### Description:

We set up Keycloak as Oauth. Authorization works in clients on desktops, in the browser. But on mobile devices the following happens:
After entering a login and password in the OUATH window, a redirect on the page with the text: login Completed. Click here to close this window. It does not happen about clicking, and when you press the cross goes to the tantle window of the logon chat.

### Expected behavior:

The application is authorized

### Server Setup Information:

- Version of Rocket.Chat Server: 4.0.1
- Operating System: ubuntu
- Deployment Method: docker
- Number of Running Instances: 2
- NodeJS Version: v12.22.1
- MongoDB Version: 4.2.17 / wiredTiger (oplog Enabled)

### Client Setup Information

- Mobile App: 4.20
- Operating System: Android 10

**Comment by diegolmello** [comment]
@Darkless012 We're going to need more info to fix this issue, since we have several types of login and they should all be working fine.
Usually when we receive reports like yours, it's a misconfiguration on admin panel.

**Comment by 3ronco** [comment]
For me as well this is still an issue:
```
Rocket.Chat Version: 6.6.0
     NodeJS Version: 14.21.3 - x64
    MongoDB Version: 5.0.24
        Commit Hash: 92a307ec3d
```
with Android App Version 4.46.1.57002

No OAuth Button for login and the following log message when trying to connect:
```
{"level":40,"time":"...","pid":9,"hostname":"...","name":"DeprecationWarning","section":"API","msg":"The parameter \"query\" in the endpoint \"/api/v1/settings.public\" is deprecated and will be removed on version 7.0.0"}
```

**Comment by diegolmello** [comment]
@3ronco 

> No OAuth Button for login in the mobile app only

This is not the issue people are mentioning on this issue. What's your login service configuration? I'm interested on how does it render on web, but not on mobile.

> following log message when trying to connect

That's just a deprecation warning.

**Comment by 3ronco** [comment]
@diegolmello 
ooops sorry, how do i ended up here?! (maybe too much tabs)
Obivously i meant #2109

**Comment by diegolmello** [comment]
@3ronco It's ok.
