### ISSUE TITLE
Android 13 Themed Icon Support

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [RocketChat/Rocket.Chat.ReactNative#5050]
Why not add support for the themed icon Android feature for a nice modern touch? Rocket chat is only of the only apps which doesn't use the modern icon theme.

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by diegolmello** [comment]
Hey @ae5960e8-a6fc-491f-b252-898ecf59af95!
That's the plan, but first we need to target Android SDK 33 and update React Native version, which we're doing right here https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4984
Thanks for reporting!

**Comment by thgoebel** [comment]
Afaik you don't need to target 33. You only need the `<monochrome>` in your `<adaptive-icon>`. Devices running 33 will pick it up, lower devices will ignore it, no matter what targetSdk you have.

**Comment by diegolmello** [comment]
Thanks, we'll give it a try!
