### ISSUE TITLE
Task :app:processBugsnagExperimental-foss-releaseManifest FAILED

### ISSUE THREAD

**Issue by seniorwebdev01** [RocketChat/Rocket.Chat.ReactNative#5067]
I tried to generate the bundle of the react-native version but when following error occurred?
How to fix this issue?

> Task :app:processBugsnagExperimental-foss-releaseManifest FAILED
Execution optimizations have been disabled for task ':app:processBugsnagExperimental-foss-releaseManifest' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'E:\Projects\2023-05-05-chatapp\Rocket.Chat.ReactNative (3)\Rocket.Chat.ReactNative\android\app\build\intermediates\merged_manifest\experimentalFossRelease\processExperimentalFossReleaseMainManifest\AndroidManifest.xml'. Reason: Task ':app:processBugsnagExperimental-foss-releaseManifest' uses this output of task ':app:copyExperimentalFossReleaseBundledJs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processBugsnagExperimental-foss-releaseManifest'.
> Bugsnag: Your AndroidManifest.xml is missing one or more of
  apiKey/versionCode/buildUuid/versionName/package, which are required to upload to bugsnag.
  apiKey=null

**Comment by diegolmello** [comment]
There's not enough info to help you.
Make sure to follow our docs https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/CONTRIBUTING.md#how-to-run
