### ISSUE TITLE
Webview does not cache jitsi meet static files and javascript

### ISSUE THREAD

**Issue by shiryov** [RocketChat/Rocket.Chat.ReactNative#5119]
### Description:

When the user starts a call in the application, content is downloaded from the jitsi server each time.
The user watches a white webview screen for about a minute while it's all loading

Every time I make a call, I see this in the jitsi nginx logs: 
```
GET /libs/app.bundle.min.js?v=6991 HTTP/1.0" 200 4915918 
GET /libs/lib-jitsi-meet.min.js?v=6991 HTTP/1.0" 200 823241
```

### Environment Information:

- Rocket.Chat Server Version: 5.4.9
- Rocket.Chat App Version: 4.39.0
- Useragents where was it seen:
(Linux; Android 12; SM-A315G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Mobile Safari/537.36
(iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1
- Device Name: Android POCO X3 Pro, Iphone8
- OS Version: iOS 16.3, Android 12

### Steps to reproduce:

1. Make a new call
2. Press call button

### Expected behavior:

The call starts quickly

### Actual behavior:

It takes time for the call to start

### Additional context:

```
"GET /libs/app.bundle.min.js?v=6991 HTTP/1.0" 200 4915918 
"GET /libs/lib-jitsi-meet.min.js?v=6991 HTTP/1.0" 200 823241
"GET /libs/excalidraw-assets/vendor-220a1bb1bd422d754c5d.js HTTP/1.0" 200 553015 
"GET /libs/lib-jitsi-meet.e2ee-worker.js HTTP/1.0" 200 18355 
"GET /pwa-worker.js HTTP/1.0" 200 3358 
"GET /static/close2.html HTTP/1.0" 200 11323 
"GET /static/close.js HTTP/1.0" 200 1966 
"GET /css/all.css HTTP/1.0" 206 1 
"GET /pwa-worker.js HTTP/1.0" 200 3358 
```

**Comment by ankar84** [comment]
It would be great if that Jitsi scripts cached by RCRN application.
Our users have a lots of meetings on mobile in RCRN application and every call their smartphones must download same 6MB of JS files

**Comment by shiryov** [comment]
This is entirely a matter of nginx configuration, it was enough to enable the cache of versioned files 
[cache all versioned files](https://github.com/jitsi/jitsi-meet/blob/65450e36efb966447b3e183be4d396c56ca1bbcb/doc/debian/jitsi-meet/jitsi-meet.example#L110)
