### ISSUE TITLE
Desktop Notifications option in Preferences in Profile is not saved in UI

### ISSUE THREAD

**Issue by dimazhiv** [RocketChat/Rocket.Chat.ReactNative#5137]
### Description:

Notification preferences  "Desktop Notifications" is applied correctly but is not saving in UI.

### Environment Information:

- Rocket.Chat Server Version: 6.3 (open.rocket.chat or any server)
- Rocket.Chat App Version: 4.39.0.43600 (ios)
- Device Name: any
- OS Version: any android and ios

### Preconditions:
You are logged in to any server (open.rocket.chat for instance)
Main "Chat" screen is displayed

### Steps to reproduce:

1. Tap Menu button
2. Tap Profile button
3. Tap preferences button (in top right corner)
4. Tap Notifications 
5. Tap Alert in "Desktop Notifications"
6. Tap any not selected option for instance: "All Messages"
7. Tap Back button
8. Tap Notifications

### Expected behavior:

"All Messages" option is displayed in "Desktop Notifications"

### Actual behavior:

"Default" option is displayed in "Desktop Notifications"

### Additional context:

Option is definitely changed for user and it is fetched correctly from the server but UI shows it incorrectly.

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/29423826/3ed5c910-e0d7-4b8f-8437-f080ffc6fe99

**Comment by reinaldonetof** [comment]
Thanks for your report! Yes, this is a known issue and we are enforced to resolve it. ASAP this issue will e fixed.
