### ISSUE TITLE
Build Rocket Chat React Native  Project on Windows Failed with an Exception

### ISSUE THREAD

**Issue by yogesh6260** [RocketChat/Rocket.Chat.ReactNative#5169]
### Rocket.Chat.ReactNative app not running on android phone while building with windows.

As mentioned in Contribution docs, I completely setup the dev environment.
The error I got when I run 'yarn android' which is mentioned in contribution docs. Everything is compiled smoothly, all the stages are working, The INITIALIZATION, CONFIGURATION,  But at the time of EXECUTING, It will throw error and said BUILD FAILED.

The error I attached in the image of my terminal, Please, look into it and anyone in the community can help me and try to resolve this issue and tell me what should I need to change to my setup and environment to work this.

![Screenshot (39)](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/75936948/9d5a3d2e-b424-449b-aa81-4c593894534e)

I didn't get any solution even from official React Native issues, they said to post the problem in the project discussion section, that's why I posted this issue here. Please, tell me how to resolve ASAP.

**Comment by diegolmello** [comment]
`cmake is not recognized`

Looks like a problem on your env configuration. https://stackoverflow.com/questions/19176029/cmake-is-not-recognised-as-an-internal-or-external-command

**Comment by yogesh6260** [comment]
Not Resolved got error mentioned in #5104
