### ISSUE TITLE
Image not showing up in the documentation. [Updating the readme file]

### ISSUE THREAD

**Issue by rohan9024** [RocketChat/Rocket.Chat.ReactNative#5187]
### Description:

![image](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/64919642/fa29f4b5-795f-4554-8771-d32436cf613a)

These are the two images I have found which are not displaying -->
1.  [![Project Dependencies](https://david-dm.org/RocketChat/Rocket.Chat.ReactNative.svg)](https://david-dm.org/RocketChat/Rocket.Chat.ReactNative)
2. [![Codacy Badge](https://api.codacy.com/project/badge/Grade/bb15e2392a71473ea59d3f634f35c54e)](https://www.codacy.com/app/RocketChat/Rocket.Chat.ReactNative?utm_source=github.com&utm_medium=referral&utm_content=RocketChat/Rocket.Chat.ReactNative&utm_campaign=badger)

Also, the link for blog is not appropriate, this is the link provided in the readme.md --> https://www.rocket.chat/case-studies

But instead it should be --> https://www.rocket.chat/blog

### Steps to reproduce:

1. Go to https://github.com/RocketChat/Rocket.Chat.ReactNative
2. Scroll down to the readme.md section

### Expected behavior:

The image should show up for readme file.

I would like to work on this. Please provide me the image url which is to be displayed.

**Comment by Amdadullah-Raihan** [comment]
Hello there! I attempted to solve the issue, but was unsuccessful due to the non-functioning image URLs.
