### ISSUE TITLE
single-server android target-api level at 31, playstore needs target-api level 33

### ISSUE THREAD

**Issue by lukasresch** [RocketChat/Rocket.Chat.ReactNative#5199]
Playstore policy is to keep the target-api level only a maximum of two versions behind the current Android version.
single-server branch is still at api level 31 instead of 33.

**Comment by diegolmello** [comment]
And that's the version we target https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/2379e8814490c639941ca04fe59e3bad0c188783/android/build.gradle#L12
