### ISSUE TITLE
SAML Login flow no longer works

### ISSUE THREAD

**Issue by krzys-h** [RocketChat/Rocket.Chat.ReactNative#5216]
### Description:

We use Rocket.Chat with Keycloak as an authentication provider via SAML. Today, the mobile app randomly logged me out, and I discovered that the login flow no longer works. After completing the SSO flow, the browser version opens in the SSO window and the login does not complete in the app. Other members of the organization reported that it's broken for them as well. I'm not sure what changed - it could be either a recent server update (we updated from 6.2.0 around 3 weeks ago), or some mobile app update. There were no other recent changes to the configuration. I tried on both Experimental and normal versions of the app, neither works.

### Environment Information:

- Rocket.Chat Server Version: 6.3.1
- Rocket.Chat App Version: 4.40.0, 4.41.0
- Device Name: Samsung Galaxy S20+ (plus at least 2 other members of our org with different devices)
- OS Version: Android 13 (plus at least 2 other members of our org with different devices)

### Steps to reproduce:

1. Configure SAML login with Keycloak
2. Try to log in in the mobile app

### Expected behavior:

The login flow works and you proceed to the app.

### Actual behavior:

The browser version of the app opens in the SSO window, login does not complete.

![Screenshot_20230920_122420_RocketChat Experimental](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/1517255/12e16f00-b4cf-4ed5-8639-c4831977bb70)

### Additional context:

Worked in the past with the same configuration, this is a regression.

**Comment by GleidsonDaniel** [comment]
Update your server version:
https://github.com/RocketChat/Rocket.Chat/pull/30128
https://github.com/RocketChat/Rocket.Chat/releases/tag/6.3.2
