### ISSUE TITLE
Image Attachments are not using CDN_PREFIX

### ISSUE THREAD

**Issue by nmagedman** [RocketChat/Rocket.Chat.ReactNative#5237]
### Description:

The RC server has a setting called `CDN_PREFIX` which, on the web client, causes assets such as FileUploads (image attachments) to be served via a CDN rather than directly from the RC servers.  The mobile app does not honor `CDN_PREFIX` and requests the images directly from RC.  This puts unnecessary load on the RC servers and leaves the CDN under-utilized.

### Environment Information:

- Rocket.Chat Server Version: 6.3.3
- Rocket.Chat App Version: 4.40.0.47248
- Device Name: iPhone SE
- OS Version: iOS 17.0 (21A329)

### Steps to reproduce:

This can be demonstrated in two ways:
1. iOS App Privacy Report
2. Add logging to the RC server 

#### iOS App Privacy Report

iOS supports some (very limited) monitoring of an app's network activity.  You can get a list of which domain names an app has accessed recently.  Launch the RC mobile app and view some messages that have image attachments and then look at the list of domains that have been recently accessed.  We should expect that both the RC server domain and the CDN domain will be in the list.  Instead we only see the former.

To access the list (instructions based on iOS 17), go to:

1. Settings App
1. Privacy & Security
1. App Privacy Report (found all the way down the page)
1. § APP NETWORK ACTIVITY
1. Show All
1. Rocket.Chat
1. § DOMAINS CONTACTED DIRECTLY BY APP
1. See that the RC server (e.g. `rc.seekingalpha.com`) is present but the CDN (e.g. `rc-cdn.seekingalpha.com`) is not

#### Add logging to the RC server 

1. The RC server currently does not log requests to `/file-upload/:upload_id/:filename`.  We will add some simple logging of the request and its headers.  Using RC 6.3.3 as a base, apply the following patch

    ```diff
    diff --git a/apps/meteor/app/file-upload/server/lib/requests.ts b/apps/meteor/app/file-upload/server/lib/requests.ts
    index 91bb50b179..c88ee45fb2 100644
    --- a/apps/meteor/app/file-upload/server/lib/requests.ts
    +++ b/apps/meteor/app/file-upload/server/lib/requests.ts
    @@ -2,8 +2,22 @@ import { WebApp } from 'meteor/webapp';
    import { Uploads } from '@rocket.chat/models';

    import { FileUpload } from './FileUpload';
    +import { Logger } from '../../../../server/lib/logger/Logger';

    WebApp.connectHandlers.use(FileUpload.getPath(), async function (req, res, next) {
    +	const log = new Logger('FileUpload').logger.child({
    +		url: req.url,
    +		headers: req.headers,
    +	});
    +
    +	log.http({
    +		stage: 'start',
    +	});
    +
      const match = /^\/([^\/]+)\/(.*)/.exec(req.url || '');

      if (match?.[1]) {
    ```

2. Using a web browser, request an attached image both from the RC server _directly_ and via the _CDN_.  e.g.:

    * https://rc.seekingalpha.com/file-upload/9pY…763/screenshot.png?source=requested-manually-from-rc
    * https://rc-cdn.seekingalpha.com/file-upload/9pY…763/screenshot.png?source=requested-manually-from-cdn

3. Compare the log entries for these two requests.  In the case of the [Fastly CDN](https://www.fastly.com/), we see that requests that come to RC _via Fastly_ include numerous HTTP headers that are not present on _direct_, non-CDN requests:

    ```
    x-forwarded-host: rc-cdn.seekingalpha.com, rc-cdn.seekingalpha.com
    fastly-ssl: 1
    fastly-client-ip: 1234:5678::90ab
    fastly-orig-accept-encoding: gzip
    fastly-client: 1
    fastly-ff: SwZ…
    cdn-loop:  Fastly, Fastly, Fastly, Fastly
    ```

    We can use the presence or absence of these headers to determine whether a request is coming via the CDN or hitting the RC server directly.

4. Launch the RC mobile app and view some messages that have image attachments.  Looking at the log entries for requests from our user-agent (e.g. `Rocket.Chat/4.40.0 (iPhone; iOS 17.0; Scale/2.00)`) we do not find any of the CDN markers present.

---

I conclude that the mobile app is definitively _not_ making use of the CDN which the server is configured to use, and which the web app does in fact use.

### Expected behavior:

The app should use the `CDN_PREFIX`, `CDN_PREFIX_ALL`, and `CDN_JSCSS_PREFIX` server configuration settings to serve file uploads as well as all other assets (e.g. JS and CSS files)

### Actual behavior:

At the very least, _image attachments_ are not using the CDN.  I have not confirmed other assets.

### Additional context:

I don't see any reference to these server config settings anywhere in the `Rocket.Chat.ReactNative` repo.  Nonetheless,  Tech Support (see Desk ticket [#77526](https://desk.rocket.chat/portal/en/ticket/413244000132097277)) asserts in the name of the Mobile app engineering team that the mobile app _does_ in fact use the CDN.  However, all the evidence before me indicates the opposite.

**Comment by diegolmello** [comment]
We're going to investigate, @nmagedman.
Thanks for reporting!

**Comment by nmagedman** [comment]
Thank you, @diegolmello !   Any updates?   Are you able to repro?
