### ISSUE TITLE
List of all crashes & bugs I found on react native app.

### ISSUE THREAD

**Issue by FaizanZahid** [RocketChat/Rocket.Chat.ReactNative#524]
Rocket chat server version: 0.69.2
React native app version: 1.5.1.4854

Bugs:

1.  I don't understand why this app is a bit slow and lags, for e.g when i type a msg, the plus icon on right takes few seconds to be change into the play send icon. So sometimes i type fast and press the button but that button state is still plus instead of send. Messenger by fb is also on react native and its very fast. any way we can make it fast too?
2. No way to upload videos to the chatrooms, the only option i see is to upload images, the phone directory doesn't show any videos, please allow it to let us upload any file type e.g pdf, videos, mp3 etc. Kotlin app allows this i guess.
3. Tapping on user profile should show more details e.g their bio, their followers, their location, their, custom fields, their pictures gallery Like instagram.
4. When i im in a room, and i tap on the 3 dots for more actions and contextual user profile menu shows, i tapped back on top left and app crashed.
5. A user sent me a video, but  when i play that video, it says vid unvailable and only a black screen shows. Unable to play recevied vids on the app itself. I think some video formats dont work for e.g .wmv format.
6.  When in the global general channel where there r so many files, i tap on files and i m slowly scrolling down, i see 2 bugs, after some scroll it starts showing same images again, it restarts the scrolls, 2nd bug, when i scroll very fast to go at bottom, the whole screen goes white with small scroll bar on right side, i cant see the new infinite scroll files, it only shows me first 20-25 files after that i cant see files nor i can scroll down, it just goes white. Try it urself. it should be scrollable like a fb newsfeed with ajaxify lazy loading scroll on files as we scroll down.
7. Tapping on user profile or name anywhere should open user info screen where we can see more details, chat for that user, his/her images, his bio, his status, his feed, his followers, i mean it should be a full profile page like whatsapp,
8. If i get too many DM msgs, then my DM list gets too long, if i scroll too long, then i have to scroll ll the way again to top manually, it should have a scroll to top button on DM list as well as when scrolling via old msgs.
9.  I opened a DM by tapping on an old DM, then the app crashed.
10. RC react native keeps on crashing randomly when i use it aggressively or when i go from one screen to another very fast, the app crashes. may be memory leak issue or too much memory? or stackoverflow? :P 
11. Tapping on a push notifcation should take me directly to a chat room using deep link instead of sending me to chat home each time.

i'd love to see react native version to have audio and video calls and beat slack, whatsapp in terms of features. i m sure RC has potential and it can rock the open source community. Hats off to all your hard work.

**Comment by diegolmello** [comment]
Hi, @FaizanZahid.
Thanks for opening this issue.
I'm closing it and breaking it down.
