### ISSUE TITLE
No incoming audio in Jitsi Meet conferences on Android

### ISSUE THREAD

**Issue by shiryov** [RocketChat/Rocket.Chat.ReactNative#5253]
### Description:

When you connect to a Jitsi call from a mobile application 4.40 on Android, you cannot hear other participants in the conference. This is reproduced both without a headset (phone speaker) and with a connected headset. There is silence on the phone.The sound level of other participants is set to maximum. The video streams from others is working, other conference participants (on desktop applications or in the browser) can hear you well.

### Environment Information:

- Rocket.Chat Server Version: 6.3.3
- Rocket.Chat App Version: 4.40.0.47250
- Device Name: Android POCO X3 Pro, various other Android users phones
- OS: Android 12 and others

### Steps to reproduce:

1. Open Jitsi Meet call in 4.40 application

### Expected behavior:

Audio from other participants is present

### Actual behavior:

There is silence on the phone

### Additional context:

With the Jitsi Meet application installed, the sound is present. 
This issue is not reproduced in the mobile browser and in previous version 4.39
This issue is reproduced on open.rocket.chat

**Comment by GleidsonDaniel** [comment]
I tested it on two different devices and the audio worked normally.
I was only able to simulate the error on the simulator, but only the first time the app is installed and in subsequent sessions the audio works normally again.

When leaving and returning to the call, does the audio work?

It's probably a permissions issue, however I wasn't able to reproduce the error more than once, so I'll need your help to better understand the error.

**Comment by shiryov** [comment]
@GleidsonDaniel 
When leaving and returning to the call, audio worked once! but other times problem repeated.
I turned off various power saving features on Android and made sure that Rocket.Chat app all the necessary permissions.
Also, in app there is animation when the desktop participant speaks, but there is no sound at all.
Volume level at maximum.
Also I tried the same on an old Galaxy S8 Android 9 phone, but everything is completely bad there... I can’t see the other participants in the conference, I’m alone in it all the time.
all these tests i make on open.rocket.chat

**Comment by Chirtep** [comment]
@GleidsonDaniel @shiryov it happens, when you remove this prop 

`mediaPlaybackRequiresUserAction={false}`

from WebView component in app/views/JitsiMeetView/index.tsx file and add this one:

`allowsInlineMediaPlayback`

I remember that you add this one to fix iOS calls, and it works for this purpose, but it also actually breaks calls on some Android versions at the same time.

We need a solution that will make calls work on all platforms. I hope this information will help to solve the problem quickly.

**Comment by GleidsonDaniel** [comment]
Yes, that's right, I was testing it on Friday.
Today a fix comes out.

**Comment by GleidsonDaniel** [comment]
![Screenshot_2023-10-09-14-47-28-784_chat rocket reactnative](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/18687097/4cd9da6a-52c5-4a03-9fe6-ba14c3640b3f)

A comment for anyone who comes here to this issue to report something similar.
If you do not select any of the options when starting a call for the first time, the audio will not come from anywhere, and unfortunately this is not something that the rocket.chat app can handle, it is how the Jitsi app works.
