### ISSUE TITLE
Aggressively navigation causes memory leak and other glitches

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#527]
Reported on #524 

> RC react native keeps on crashing randomly when i use it aggressively or when i go from one screen to another very fast, the app crashes. may be memory leak issue or too much memory?

It also may causes unexpected header icons showing, e.g. rooms list icons showing inside room

**Comment by FaizanZahid** [comment]
Yes, i can related to this. totally happening to me as well. Why is this app a bit slow?

**Comment by diegolmello** [comment]
When I was [updating dependencies](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/587) I found a [bug on react-native-navigation](https://github.com/wix/react-native-navigation/issues/4651).

**Comment by diegolmello** [comment]
I found also a minor leak from inline requires.
I fixed it on #594.

There's still job to do on navigation, but it appears to be faster.

**Comment by diegolmello** [comment]
Quick update: guys from Wix tracked this to JSC here: https://github.com/react-native-community/jsc-android-buildscripts/issues/84
