### ISSUE TITLE
Cannot open own profile

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5287]
### Description:

From the message view of a channel, I am unable tap on the avatar or on the username of my own messages to show my profile. I can open other users' profiles this way. In the browser, I can open my own profile. In my opinion, this inconsistent behaviour is unintuitive.

### Environment Information:

- Rocket.Chat Server Version: 6.4.2
- Rocket.Chat App Version: 4.41.0.49563
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Open the app and navigate to any channel.
2. Write a message and submit it.
3. Tap on the avatar or on the username of the message created in step 2.

### Expected behavior:

My profile is shown.

### Actual behavior:

Nothing happens.

**Comment by tanmaysinghx** [comment]
I am working on it.
