### ISSUE TITLE
Using /me when quoting a message creates a reply

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5300]
### Description:

When quoting a message and starting the text with `/me`, a reply will be created instead of a message including a quote.

### Environment Information:

- Rocket.Chat Server Version: 6.4.3
- Rocket.Chat App Version: 4.42.0.50842
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Write a message.
2. Write a second message quoting the first one. Start the text of this message with `/me`.

### Expected behavior:

In step 2, a message is created including a quote containing the message from step 1.

### Actual behavior:

The message from step 2 becomes a reply to the message from step 1.

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/404840/25d8909c-43a8-4f49-bff5-2e190a120bfb

### Additional context:

In the browser version of Rocket.Chat, this works as expected.

**Comment by diegolmello** [comment]
I'm not entirely sure what's supposed to happen, but this is me on web.

![image](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/804994/b8ef2f00-4e63-41ac-8ad3-b3a90361afd5)

**Comment by paulchen** [comment]
> I'm not entirely sure what's supposed to happen, but this is me on web.
> 
> ![image](https://user-images.githubusercontent.com/804994/278638153-b8ef2f00-4e63-41ac-8ad3-b3a90361afd5.png)

I also noticed that the behaviour of the web version is unexpected for me, which is why I opened an issue for that as well: RocketChat/Rocket.Chat#30779

**Comment by Himanshu-kiran** [comment]
@paulchen Can you please clarify the expected behaviour little bit more.?

**Comment by paulchen** [comment]
Actually, using the most recent version (4.47.0.58919) of the app, I can't reproduce the problem anymore. The app exhibits the same behaviour as the browser version:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/404840/ff0f1386-76bf-445a-9faf-8ab4c6d44480

Therefore, I now close this issue.
