### ISSUE TITLE
User suggestions not available when using a slash command

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5301]
### Description:

When composing a message, no usernames will be suggested when starting the message with a slash command.

### Environment Information:

- Rocket.Chat Server Version: 6.4.3
- Rocket.Chat App Version: 4.42.0.50842
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Start composing a message with a slash command, like `/me`, `/shrug` etc.
2. After a space, type `@` and wait for username suggestions to appear.

### Expected behavior:

Username suggestions are shown.

### Actual behavior:

No usernames are suggested.

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/404840/f0c46945-54ad-45c6-aa30-dbc9644f26b4

### Additional context:

In the browser version of Rocket.Chat, this works as expected.

**Comment by diegolmello** [comment]
I've been working on the new message composer here https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5205
I'll fix it there.
Expect a fix by the end of the year.
