### ISSUE TITLE
Display site name instead of site URL

### ISSUE THREAD

**Issue by achilles-kosun** [RocketChat/Rocket.Chat.ReactNative#531]
I think it's more sense to show site name than site URL, And that's what PC version do.

If you guys think so, I will create a PR for this.

**Comment by diegolmello** [comment]
@achilles-kosun Where are you planning to do that?
Can you send a pic?

**Comment by achilles-kosun** [comment]
@diegolmello  Of course sure!

<img width="382" alt="iphone x - 12 1 2018-11-07 13-48-56" src="https://user-images.githubusercontent.com/44356695/48113159-85a4b000-e294-11e8-804e-3166aca7bc94.png">
<img width="538" alt="iphone x - 12 1 2018-11-07 13-51-00" src="https://user-images.githubusercontent.com/44356695/48113160-85a4b000-e294-11e8-9bcb-ad876c0e04ec.png">
<img width="538" alt="iphone x - 12 1 2018-11-07 13-52-03" src="https://user-images.githubusercontent.com/44356695/48113163-863d4680-e294-11e8-9037-8edd2dcab8d2.png">

**Comment by diegolmello** [comment]
@achilles-kosun I'm working on the new authentication layout right now and I'll do it myself.
Thanks anyway :)

**Comment by achilles-kosun** [comment]
@diegolmello  that's great!

**Comment by diegolmello** [comment]
Fixed at #536
