### ISSUE TITLE
Unknown emoji large_blue_circle

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5320]
### Description:

The app suggests the emoji `:large_blue_circle:` which is Rocket.Chat does not support.

### Environment Information:

- Rocket.Chat Server Version: 6.4.4
- Rocket.Chat App Version: 4.42.0.50842
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

1. Type `:large` in a message. Observe the emoji suggestions.
2. Use emoji search and type `large` there. Observe the suggestions.

### Expected behavior:

`:large_blue_circle:` never shows up.

### Actual behavior:

Step 1:

<img src="https://user-images.githubusercontent.com/404840/280560140-f134b429-ad2e-499a-8612-4640606b81e8.png" width="50%" height="50%">

Step 2:

<img src="https://user-images.githubusercontent.com/404840/280560161-3ef8f7c8-7c08-4827-a7a7-35db9e5c105d.png" width="50%" height="50%">

### Additional context:

Probably the problem is that Rocket.Chat should support `:large_blue_circle:`, but doesn't. In that case an issue for the repository RocketChat/Rocket.Chat should be opened.

The browser version does not show `:large_blue_circle:`:

![image](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/404840/de238c58-9866-4a47-94a6-3e8133e2548c)

![image](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/404840/b017197b-3a7b-4aa1-af77-19d0166c8392)

**Comment by brf153** [comment]
@paulchen should I remove :large_blue_circle: from suggestion?

**Comment by GleidsonDaniel** [comment]
Probably the second option, if it works on the web it should work on mobile.

**Comment by brf153** [comment]
@GleidsonDaniel oki

**Comment by paulchen** [comment]
> Probably the second option, if it works on the web it should work on mobile.

However, in the web version, `:large_blue_circle:` is not available at all.

**Comment by brf153** [comment]
@paulchen I think we can close this issue now. @GleidsonDaniel thank you for merging the pr.

**Comment by GleidsonDaniel** [comment]
Another thing, if you put closes or removes and the # of the PR you are resolving in front, it automatically closes with the merge of your PR.
Example:
resolve: #5320
