### ISSUE TITLE
Android - Sharing not working

### ISSUE THREAD

**Issue by aenonGit** [RocketChat/Rocket.Chat.ReactNative#5325]
### Description:

In Android 13 the permission for READ_EXTERNAL_STORAGE is ignored and replaced with a fine grained list of permissions. This only applies for new installations since the removed permission (READ_EXTERNAL_STORAGE) is still granted if it was granted before upgrading to targetSdk 33.

### Environment Information:

- Rocket.Chat Server Version:
- Rocket.Chat App Version: latest
- Device Name: Samsung S20 FE
- OS Version: 13

### Steps to reproduce:

1. Make a fresh install on a new device with Android 13 on board.
2. Try to share something to Rocket

### Expected behavior:
Get the list of chats to select the destination

### Actual behavior:
The missing permission view is shown without the app to ask for the permission, since it is ignored

### Additional context:
I'm not sure the permission is required for the sharing feature, but maybe is something related to RN, if so a possible solution is to include in the Manifest both old permission with `android:maxSdkVersion="32"` and all other new permissions. Then in the Share class request the proper permission based on Android version and file type. Digging firther into the code, the problem is very likely in the usage of `expo-file-system` library, whose doc by the way, has not been updated with the new Android permissions.

**Comment by Fortyseven** [comment]
Not sure if this is entirely related, but I came here while trying to figure this out: I can share images from the device if I do it from inside the app, but if I try to use the share functionality from another app TO RocketChat, I get this:

![image](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/156409/89c3c1c2-3342-47f3-9237-46bca2d4f0a2)

Device:
- Samsung Galaxy S22 Ultra
- Android 13
- App Ver: 4.42.0.50842 (Workspace: 6.3.0)

**Comment by aenonGit** [comment]
yes, that's exactly the scenario
