### ISSUE TITLE
Touching a received notification does not bring to an updated list of messages

### ISSUE THREAD

**Issue by superseby2** [RocketChat/Rocket.Chat.ReactNative#535]
- Your Rocket.Chat ReactNative App version : 1.5.1.4877
- Your Rocket.Chat server version:  0.71.1

- Device model (or emulator) you're running with:  Android 7.0

Issue : when touching a RocketChat Android notification, the App loads OK, the channel list shows a new message icon on the expected channel. But when entering inside the channel, sometimes, but most of the time, the list is not refreshed with the new messages. And it is never refresh from this point until force-closing the app.

**Comment by diegolmello** [comment]
@superseby2 Thanks for opening this issue. I'll take a look 👊

**Comment by diegolmello** [comment]
@superseby2 Can you try again at 1.6.1?

**Comment by cdhowie** [comment]
@diegodorgam The update did not fix the issue. If anything, it made it substantially worse.

**Comment by superseby2** [comment]
Since last update. Every thing works like a charm. Thanks guys and sorry for the late reply !
