### ISSUE TITLE
Attachment Images  Fail to Display 

### ISSUE THREAD

**Issue by herolzwcj** [RocketChat/Rocket.Chat.ReactNative#5378]
Environment Information:

- Rocket.Chat Server Version:6.5
- Rocket.Chat App Version:4.43.0
- Device Name: iphone
- OS Version: 17.1.1

Apps before 4.4 were able to open photos normally. Unable to open properly after updating to 4.4. (My RC version is 4.5.1, and I have now upgraded to 6.5.0)

 Steps to reproduce:
![微信图片_20231202084057](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/96873523/73232d6b-31fc-4b70-a3ed-7ef138eea7ab)

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/96873523/686ce313-0e92-4103-be25-70b65bef31d6

**Comment by pranavkonidena** [comment]
Hey, I have experience in flutter app dev.. have made 4-5 apps.. Have set up this app locally however , I am a bit confused as to which creds I shud use when it is asking me for workspace url? Shud i create a workspace and use it or is there some default testing workspace urls?

**Comment by reinaldonetof** [comment]
> Hey, I have experience in flutter app dev.. have made 4-5 apps.. Have set up this app locally however , I am a bit confused as to which creds I shud use when it is asking me for workspace url? Shud i create a workspace and use it or is there some default testing workspace urls?

Hey @pranavkonidena here isn't the best place to ask about it. However, the default workspace is open.rocket.chat, also you can follow the documentation: https://docs.rocket.chat/

**Comment by reinaldonetof** [comment]
Hey @herolzwcj, some questions:
- Is this error happening with the mobile app version greater than or equal to 4.40, while the server version was 4.5.1? Or begins after you upgraded the server version?
- The problem occurs only with those images and on that channel? Or it's happening with any channel and with any image?

**Comment by herolzwcj** [comment]
This error occurs in mobile application versions greater than or equal to 4.40. When it was first discovered, the server version was 4.5.1. The problem still persists after upgrading the server version
The problem occurs on any channel and any image.

> 在 2023年12月4日，22:42，Reinaldo Neto ***@***.***> 写道：
> 
> Is this error happening with the mobile app version greater than or equal to 4.40, while the server version was 4.5.1? Or begins after you upgraded the server version?
> The problem occurs only with those images and on that channel? Or it's happening with any channel and with any image?

**Comment by herolzwcj** [comment]
hello,This error occurs in mobile application versions greater than or equal to 4.40. When it was first discovered, the server version was 4.5.1. The problem still persists after upgrading the server versionThe problem occurs on any channel and any image.在 2023年12月4日，22:42，Reinaldo Neto ***@***.***> 写道：﻿
Hey @herolzwcj, some questions:

Is this error happening with the mobile app version greater than or equal to 4.40, while the server version was 4.5.1? Or begins after you upgraded the server version?
The problem occurs only with those images and on that channel? Or it's happening with any channel and with any image?

**Comment by herolzwcj** [comment]
The file name is the default name for taking photos with iPhone cameras,thanks发自我的 iPhone在 2023年12月5日，21:19，Reinaldo Neto ***@***.***> 写道：﻿
@herolzwcj can you share those filenames?

**Comment by herolzwcj** [comment]
hello @reinaldonetof 

I don't know how to debug the server, you can use the following user information for testing.

Sev: http://58.23.108.7:2999
UID: test
PWD: test123456
Thanks

**Comment by herolzwcj** [comment]
hello @reinaldonetof

I don't know how to debug the server, you can use the following user information for testing.
And I found that this issue only occurs on iPhone. It's normal on my iPad. 

Sev: http://58.23.108.7:2999/
UID: test
PWD: test123456

Thanks

**Comment by herolzwcj** [comment]
@reinaldonetof  I have resolved this issue, it was caused by an upgrade. Thank you
