### ISSUE TITLE
Create direct messages is not allowed

### ISSUE THREAD

**Issue by brf153** [RocketChat/Rocket.Chat.ReactNative#5384]
### Description:

I am trying to make a direct message directly from a user's info but it gives me an error stating `Create direct messages is not allowed`

### Environment Information:

- Rocket.Chat Server Version: 6.5
- Rocket.Chat App Version: latest(dev mode) and mobile app version(4.43)
- Device Name: Samsung Galaxy M13 
- OS Version: Ubuntu 22.04 
- Android version: 13

### Steps to reproduce:

1.  Go to any room
2.  Click on a user's profile to open user info
3.  Click on the direct message icon

### Expected behavior:

I want to send a direct message to the user

### Actual behavior:

![WhatsApp Image 2023-12-08 at 14 47 04](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/107868772/3421f779-e1af-4aeb-a893-ccfe07d8a92e)

**Comment by brf153** [comment]
@reinaldonetof can I work on this issue?

**Comment by reinaldonetof** [comment]
@brf153 this depends the permission `'create-d'` within the server.
