### ISSUE TITLE
Redirect to App if App is installed in Mobile

### ISSUE THREAD

**Issue by SanjaySargam** [RocketChat/Rocket.Chat.ReactNative#5401]
### Environment Information:

- Rocket.Chat Server Version: 
- Rocket.Chat App Version: 4.43.0.52295
- Device Name: Realme 9
- OS Version: Android

### Steps to reproduce:

1. Click on [open.rocket.chat](https://open.rocket.chat)

### Expected behavior:

It should redirect to app if app is installed in mobile

### Actual behavior:

It is redirecting to web browser

**Comment by SanjaySargam** [comment]
If it is a valid issue then I'd love to work on this

**Comment by diegolmello** [comment]
It's not an issue and it's not something you can implement with your level of access.

**Comment by SanjaySargam** [comment]
@diegolmello Ok no worries

Can you please send debug apk of app ?
