### ISSUE TITLE
There is no Hungarian language (Android app 4.44.0.53875)

### ISSUE THREAD

**Issue by ZsiGiT** [RocketChat/Rocket.Chat.ReactNative#5415]
### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 4.44.0.53875
- Device Name: Armor 21
- OS Version: Android 13

### Steps to reproduce:

1.  Android app -> "hamburger menu"
2. Settings
3. Language

**Comment by diegolmello** [comment]
Thanks for letting us know, @ZsiGiT.
Last time I heard of Hungarian was on https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5294, but it wasn't finished.
Someone added it to Lingohub, but it doesn't add the link to it.
I'm going to do it.

**Comment by ZsiGiT** [comment]
I made the Lingohub translation, and I believe the translation is complete. 

Please add the link.

I don't know how github contribution works. :( That's why I made the translation on lingohub.

**Comment by diegolmello** [comment]
Thanks for your contribution!
No worries, maybe @brf153 or @jsathu07 would like to add the missing change? :)

**Comment by ZsiGiT** [comment]
Thanks to everyone.

**Comment by brf153** [comment]
@diegolmello I will do it.

**Comment by mayo7e** [comment]
if these is sti up for grabs, i will  like to work on it, my first contribution , more to come..

**Comment by mayo7e** [comment]
Hello everyone! I've come up with an idea to translate content into Yoruba, a language spoken by nearly 45 million people worldwide. I would really appreciate some advice on the best approach for this. If this piques the team's interest, I'd love to discuss it further. Thank you
