### ISSUE TITLE
[iOS White-Label] Error when building the iOS app - Database WatermelonDB

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat.ReactNative#5418]
### Environment Information:

- Rocket.Chat App Version: 4.43.1
- Device Name: Iphone 13 Emulator
- OS Version: MacOS 12.7.1

### Steps to reproduce:

1. Exec yarn ios 

### Expected behavior:

Build successfully

### Actual behavior:

Error build - Failed to build iOS project

### Additional context:

I'm getting an error when trying to build, see the error:

❌  /Users/aclink/Desktop/chat-react/ios/Shared/RocketChat/Database.swift:36:38: value of type 'Database' has no member 'queryRaw'

      if let results = try? database.queryRaw("select * from subscriptions where id == ? limit 1", [rid]) {
                            ~~~~~~~~ ^~~~~~~~



❌  /Users/aclink/Desktop/chat-react/ios/Shared/RocketChat/Database.swift:54:38: value of type 'Database' has no member 'queryRaw'

      if let results = try? database.queryRaw("select * from subscriptions where id == ? limit 1", [rid]) {
                            ~~~~~~~~ ^~~~~~~~


![Captura de Tela 2023-12-19 às 10 37 20](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/789b3434-5302-42ce-9823-fddc9901d079)
![Captura de Tela 2023-12-19 às 12 12 32](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/ed552dd7-b5b7-4af4-92d3-3378a3e2bb8f)
![Captura de Tela 2023-12-19 às 12 12 51](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/eb4a208c-e0f1-40e3-9a7d-59c2e64bc4f9)
![Captura de Tela 2023-12-19 às 12 13 06](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/2a0c0ed3-7fc6-4619-a041-8fdc5ffa7463)
![Captura de Tela 2023-12-19 às 12 15 03](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/c2763726-9919-42e8-ab4e-1a3f34b7dc91)

**Comment by diegolmello** [comment]
Hey Guilherme.
Make sure [this patch](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/patches/%40nozbe%2Bwatermelondb%2B0.23.0.patch) is applied. It should've been applied automatically by running yarn, but maybe something wrong happened.
You can check it against watermelondb lib on `node_modules` folder.

**Comment by guilhermecfviana** [comment]
@diegolmello Thanks!!

**Comment by GuHuailing** [comment]
Value of type 'Database' has no member 'queryRaw'
I cited #5877 and still encountered this problem. Clicking the patch shows 404. The watermelonDB version is "@nozbe/watermelondb": "0.25.5"
> Hey Guilherme. Make sure [this patch](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/patches/%40nozbe%2Bwatermelondb%2B0.23.0.patch) is applied. It should've been applied automatically by running yarn, but maybe something wrong happened. You can check it against watermelondb lib on `node_modules` folder.
