### ISSUE TITLE
[App White-Label] Notification doesn't work on iOS

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat.ReactNative#5419]
### Description:

I configured it using the APNs certificate both in Firebase and in the rocket.chat server administrator panel and I do not receive notifications on iOS. Note: On Android it is already working normally.

### Environment Information:

- Rocket.Chat App Version: 4.43.0.1
- Device Name: Iphone 15 Pro Max
- OS Version: iOS 17.2

### Steps to reproduce:

1. I accessed the rocket.chat server and configured the APNs for the push notification certificates

![Captura de Tela 2023-12-20 às 11 49 27](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/33f19ca4-83a3-4e86-8745-2b509661fef5)

![Captura de Tela 2023-12-20 às 11 51 19](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/8ca010d0-6a3a-4317-a5d5-51f1827a10c6)

![Captura de Tela 2023-12-20 às 11 52 21](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/817abd25-0de3-4c55-a7c5-b9f3a3eba470)

![Captura de Tela 2023-12-20 às 11 53 37](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/91c12033-52f9-4c39-a265-77b13ae814e9)

2. At developer.apple.com I configured APN certificates

![Captura de Tela 2023-12-20 às 11 57 00](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/533db6b8-e071-4098-a988-cf3689057688)

![Captura de Tela 2023-12-20 às 11 58 49](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/c358423e-ba83-492d-b54d-d92205897a3e)

3. In firebase I configured APN certificates

![Captura de Tela 2023-12-20 às 11 55 14](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/3464bb4d-d32c-48fe-bc52-3471a4820e28)

4. In xcode I added the GoogleService-info.plist file

![Captura de Tela 2023-12-20 às 12 00 33](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/57a63fdf-8de7-4661-9d74-954c9cd1508d)

5. I built the IPA and submitted it to the TestFlight application

![Captura de Tela 2023-12-20 às 12 13 34](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/17053653/68bd3dc3-059d-4274-aeea-a9fcd8946aad)

### Expected behavior:

Receive push notifications on iPhone successfully!

### Actual behavior:

I'm not receiving push notifications on my iPhone.

**Comment by GleidsonDaniel** [comment]
After changing the keys, did you restart the server?
This is probably something related to the keys, on iOS it's quite annoying.

**Comment by guilhermecfviana** [comment]
Hello @GleidsonDaniel !
After changing the keys, did you restart the server?
- Yes.

In this test I am using the app on an iPhone in TestFlight, push notifications should work like this normally, right?

**Comment by GleidsonDaniel** [comment]
It should work.
@diegolmello deals more with this iOS certificate problem, he has already helped some people, he is the right person to help you.
Did you follow this white label doc step by step?
https://developer.rocket.chat/open-source-projects/mobile-app/mobile-app-white-labelling/ios-app-white-labelling
https://developer.rocket.chat/open-source-projects/mobile-app/configuring-push-notifications

**Comment by guilhermecfviana** [comment]
Yes, I follow these @diegolmello tutorials, but I'm not receiving push notifications in the iOS app.

In the Android app, push notifications work normally.

**Comment by diegolmello** [comment]
Hey @guilhermecfviana.
iOS push notifications can be hard to setup sometimes.
A couple of things:
- You don't have to setup APNS on Firebase. Rocket.Chat sends push notifications directly to APNS, not Firebase -> APNS.
  * This will also impact Google json on Xcode. That's only for analytics. Forget about it for push.
- Read the push code on backend to understand it and add log it. APNS might be rejecting your requests.
- Use this tool to understand if the app is correctly setup https://github.com/onmyway133/PushNotifications

**Comment by guilhermecfviana** [comment]
Hi @diegolmello ,
With your information I was able to make push notifications work on iOS. Thank you very much!
