### ISSUE TITLE
Broken Link in README: Blog Redirects to 404

### ISSUE THREAD

**Issue by Amitlpu-840** [RocketChat/Rocket.Chat.ReactNative#5421]
### Description:
I noticed that the link to the blog in the README is currently broken, leading to a 404 error. I attempted to access the blog section by clicking on the provided link, but it seems to be misconfigured or no longer available.

### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 4.44.0.53875
- Device Name: Armor 21
- OS Version: Android 13

### Steps to reproduce:

1. Go to -> README
2. Click -> blog

### Expected behavior:
It should redirect to blog of rocket chat

### Actual behavior:
Redirecting to https://www.rocket.chat/case-studies?utm_source=github&utm_medium=readme&utm_campaign=community resulting 404

<img width="1439" alt="Screenshot 2023-12-21 at 2 19 24 AM" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/77196415/4fa4b8ab-0975-465c-9e27-9a456d6df10e">

**Comment by Amitlpu-840** [comment]
Hi community, I would like to fix this. please confirm once if https://www.rocket.chat/blog is the desired link for blog?

**Comment by diegolmello** [comment]
Hey. Thanks for opening this issue. You can change to this one:
https://www.rocket.chat/blog?utm_source=github&utm_medium=readme&utm_campaign=community

**Comment by Amitlpu-840** [comment]
Thanks @diegolmello. Can you please correct these also. I'll be including this in pull request.
Project Dependencies icon -> https://api.codacy.com/project/badge/Grade/bb15e2392a71473ea59d3f634f35c54e
Codacy Badge icon -> https://david-dm.org/RocketChat/Rocket.Chat.ReactNative.svg
<img width="998" alt="Screenshot 2023-12-21 at 10 59 28 PM" src="https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/77196415/77b1dbbd-e8c8-45b9-a866-29047527a368">

**Comment by diegolmello** [comment]
You can remove both

**Comment by diegolmello** [comment]
You can even remove codecov and codefactor
