### ISSUE TITLE
fix: Add text `Call Started!` in push notification when a group call is made

### ISSUE THREAD

**Issue by brf153** [RocketChat/Rocket.Chat.ReactNative#5429]
### Description:

Add text in push notifications when a group call is made.

### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 4.44.0.53875
- Device Name: Samsung Galaxy M13 5G
- OS Version: 13

### Steps to reproduce:

 Just check the notification when someone makes a text message in a group. 

### Expected behavior:

Expected to show some text like `Call Started!`

### Actual behavior:

Shows empty message in the notifications tab
![WhatsApp Image 2023-12-24 at 20 38 13 (1)](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/107868772/8cb1ce96-fdba-4862-9174-653ce8ebc4a8)

Shows my name in the notification rather than showing Call Started!
![WhatsApp Image 2023-12-24 at 20 42 42](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/107868772/a504b067-a2be-4846-9dfb-ef86e8f1d3a1)

**Comment by brf153** [comment]
@diegolmello can I work on this issue?

**Comment by diegolmello** [comment]
@brf153 I'm not sure what's the bug here, since there was a bug on backend sending unnecessary push notifications on video conf. We should wait for @GleidsonDaniel to properly address this issue.

**Comment by GleidsonDaniel** [comment]
This is not a bug in the mobile app, the message is sent via the backend.
I even think this has already been resolved, it just hasn't been deployed. (Or just resolved to direct message)
