### ISSUE TITLE
No Option to Preview Audio before sending

### ISSUE THREAD

**Issue by SanjaySargam** [RocketChat/Rocket.Chat.ReactNative#5444]
### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 
- Device Name: Realme 9
- OS Version: Android

### Steps to reproduce:

1. Go to Chat
2. Start recording

### Expected behavior:

Preview Audio before sending

### Actual behavior:

No Option to Preview Audio before sending
![WhatsApp Image 2023-12-28 at 4 01 56 PM](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/65113071/009b4be4-dd90-4928-87fd-0593d31677de)

**Comment by SanjaySargam** [comment]
If this issue is accepted then I'd love to work on it

**Comment by diegolmello** [comment]
I've been working on it here https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5205
