### ISSUE TITLE
[NEW] In-app notifications

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#545]
Subscribe to socket notifications and raise local notifications

**Comment by shubhsherl** [comment]
Hi, I am currently working on React-Native. Would like to contribute. :)

**Comment by diegolmello** [comment]
@shubhsherl Wonderful!
Do you have any native skills? That's ok if don't have it.
I'm just wondering what task I can assign to you.

**Comment by shubhsherl** [comment]
I have been contributing to rocketchat.android and exploring other areas... currently I am working on a project in react native...

**Comment by diegolmello** [comment]
@shubhsherl Can you work on #391?
On android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java, we build our current push notification.
We need to group notifications by room.

**Comment by shubhsherl** [comment]
@diegolmello Sure, I will start on it soon.

**Comment by diegolmello** [comment]
@shubhsherl Hi. How is your progress? Do you need help?

**Comment by shubhsherl** [comment]
@diegolmello Hi, sorry for the delay, I could not start on this, I will begin as soon as I finish my other works.
