### ISSUE TITLE
Feat: Add Leave Channel/Team option in right/left swipe

### ISSUE THREAD

**Issue by SanjaySargam** [RocketChat/Rocket.Chat.ReactNative#5455]
### Description:

In the web app, we can leave the channel/team directly by clicking three dots. In the App, we can hide, add to favorites, and unread.  Similarly, we can include an option to leave the channel/team by right/left swipe. 

### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 4.44.0+
- Device Name: Realme 9
- OS Version: Android

### Steps to reproduce:

1. Right/Left Swipe the channel/team

### Expected behavior:

Have Button to leave channel/team directly

### Actual behavior:

No Button to leave channel/team directly

### Additional context:

Web App:
![WhatsApp Image 2024-01-04 at 4 51 59 PM](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/65113071/452b0d2f-8553-455a-9e69-b508d408c73b)

**Comment by SanjaySargam** [comment]
I'd love to work on it if this feature is accepted

**Comment by GleidsonDaniel** [comment]
It is necessary to check with the team whether this behavior is really necessary.
In the mobile app, the flows are expected to be different.

**Comment by SanjaySargam** [comment]
> It is necessary to check with the team whether this behavior is really necessary. In the mobile app, the flows are expected to be different.

Sorry. I thought this feature would be better. No worries. Next time, I'll consider checking with the team about new feature/ any issue. 
Thanks!
