### ISSUE TITLE
 Displaying dropdown does not close automatically in ThreadMessage.

### ISSUE THREAD

**Issue by anirbanpaulcom** [RocketChat/Rocket.Chat.ReactNative#5479]
### Description:

In the ThreadMessages section, displaying options are available. However, after selecting any of these options (all, following, unread), the dropdown does not close.

### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 4.45.0
- Device Name: Redmi note 5 pro
- OS Version: Android

### Steps to reproduce:

1. Go to Chat section
2.  Click on Thread message icon on top right
3.  Click on filter icon under the search Icon

### Expected behavior:

dropdown should be close automatically after selecting  those options.

### Actual behavior:

dropdown does not close automatically after selecting it.

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/af3c9f0f-f076-4a6a-bfd4-a14d1c0a8475

**Comment by anirbanpaulcom** [comment]
fix: #5480

**Comment by SanjaySargam** [comment]
@GleidsonDaniel Fixed in #5463 . Kindly close this issue
