### ISSUE TITLE
Bug: Text is showing instead of emoji in notification

### ISSUE THREAD

**Issue by SanjaySargam** [RocketChat/Rocket.Chat.ReactNative#5498]
### Description:

Show a emoji instead of emoji text in notification

### Environment Information:

- Rocket.Chat Server Version: 6.6.0
- Rocket.Chat App Version: 4.45.0.55377
- Device Name: Realme 9
- OS Version: Android

### Expected behavior:

Emoji is showing in notification

### Actual behavior:

Emoji is not showing in notification

### Additional context:

Here `:rocket:` is showing instead of 🚀 

![WhatsApp Image 2024-01-19 at 12 01 23 PM](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/65113071/9a224258-f71f-4ca8-9331-171e2487a19f)

**Comment by diegolmello** [comment]
We have plans to parse emojis to unicode before saving to backend database.
That's going to fix this issue.

**Comment by SanjaySargam** [comment]
Cool Thanks!
