### ISSUE TITLE
Feat: capture new image option while editing profile picture

### ISSUE THREAD

**Issue by Amitlpu-840** [RocketChat/Rocket.Chat.ReactNative#5518]
### Description:
While editing profile, user can change his/her profile pic via image upload, album or avatar URL.
An option to capture a new profile picture can be added.

### Environment Information:

- Rocket.Chat Server Version: 6.6.0
- Rocket.Chat App Version: 4.46.0.56378
- Device Name: Realme Narzo 50
- OS Version: Realme UI 4.0

### Steps to reproduce:

1. Go to profile
2. Press on edit

### Expected behavior:

User should have option to able to click a new picture also.

### Actual behavior:
there is only upload, select from album and URL options available

![WhatsApp Image 2024-01-28 at 11 57 39](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/77196415/988e7d73-603a-4f41-ad15-78b66eff2ae2)

**Comment by Amitlpu-840** [comment]
Hii @diegolmello, can you please confirm if I am on the right path and should I work on it? 
I'll be adding the 'new image' option above upload avatar, utilizing react-native-image-crop-picker library.

**Comment by diegolmello** [comment]
Sure. You can work on it. Name it "Take_a_photo".
