### ISSUE TITLE
Opening channel through notification is very slow

### ISSUE THREAD

**Issue by skhizerabass** [RocketChat/Rocket.Chat.ReactNative#552]
Opening channel through notifications take a lot of time and sometime it doesn't even open a channel nor updates it.

**Comment by diegolmello** [comment]
Probably related to #549 
I'll release it in 1.6.1.

**Comment by skhizerabass** [comment]
I believe it is not related to the new react native navigation. I am facing same issue with the old one .  There is something else that is making issues.

**Comment by diegolmello** [comment]
@skhizerabass Just released 1.6.1.
Update your app and try again.
