### ISSUE TITLE
swipe functionality for Quote replying to a message

### ISSUE THREAD

**Issue by anirbanpaulcom** [RocketChat/Rocket.Chat.ReactNative#5537]
### Description:

make swipe functionality for Quote replying to a message.

### Environment Information:

Rocket.Chat Server Version: 6.5.0
Rocket.Chat App Version: 4.47.0
Device Name: Redmi note 5 pro
OS Version: Android

### Steps to reproduce:

1.  Go to Messages
2.  On long Press on Message
3.  'Quote' Option

### Expected behavior:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/77116611-63df-4bf7-9bbd-cb299e5764e2

### Actual behavior:
On long-press on a message, a modal opens, and when you click on the 'Quote' option within the modal.

**Comment by anirbanpaulcom** [comment]
Hey @diegolmello  @GleidsonDaniel , could you please confirm if this feature is needed? Should I work on it?

**Comment by Amitlpu-840** [comment]
hey @anirbanpaulcom, I believe issue #5478 is similar to this.

**Comment by GleidsonDaniel** [comment]
It has already been reported
