### ISSUE TITLE
fix: message view auto scrolls up when swiped up

### ISSUE THREAD

**Issue by preeesha** [RocketChat/Rocket.Chat.ReactNative#5551]
### Description:

When the chat is at its bottom, if user swipes up a couple of times (3-4, sometimes 2 also), the message view scrolls up.

### Environment Information:

- Rocket.Chat Server Version: 6.6.0
- Rocket.Chat App Version: 4.47.0.99999
- Device Name: Realme 7
- OS Version: Realme UI 3.0

### Steps to reproduce:

1. Open any chat view
2. Swipe up a couple of times
3. Observe chat going up

### Expected behavior:

This is an unexpected behaviour. Chat must remain at the bottom.

### Actual behavior:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/126406840/23f446d4-9f21-4da8-ad61-3c8dff61a3f5

**Comment by preeesha** [comment]
@GleidsonDaniel, @diegolmello Please let me know your views on this one. I would love to work on this.

Thanks for your time and consideration
Prisha Gupta

**Comment by GleidsonDaniel** [comment]
I managed to reproduce it, but I don't think it's something simple to solve hahaha.
However, nothing stops you from wanting to work on it 😅.

**Comment by preeesha** [comment]
Can you please tell me the steps to reproduce it? I would love to give it a full try.

**Comment by deepak0x** [comment]
hey @preeesha 
is this issue still open ?
if yes i would like to work on it....
