### ISSUE TITLE
Dark Level Visible When "Light" Theme Is Selected

### ISSUE THREAD

**Issue by anirbanpaulcom** [RocketChat/Rocket.Chat.ReactNative#5563]
### Description:
When the selected theme is set to "Light," the "Dark_level" section is still visible.

### Environment Information:

Rocket.Chat Server Version: 6.5.0
Rocket.Chat App Version: 4.47.0
Device Name: Redmi note 5 pro
OS Version: Android

### Steps to reproduce:

1.  Go to Settings
2.  Click on Theme 
3. Choose Light theme

### Expected behavior:

![Screenshot from 2024-02-13 18-36-22](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/3b2ce5f4-282e-4007-b5b4-00fcb79ebb32)
![Screenshot from 2024-02-13 18-35-57](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/721bd15e-1e2f-4fc2-9a47-43d0a501b961)
![Screenshot from 2024-02-13 17-55-07](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/0d256911-9685-4228-80fc-5d2cffb6cd04)

### Actual behavior:

![Screenshot from 2024-02-13 17-55-21](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/9ec5733e-b7a7-4b93-ba96-def3b8554c89)

**Comment by harshdew02** [comment]
I am working on this issue.

**Comment by Himanshu-kiran** [comment]
I am also trying to look into this issue.

**Comment by anirbanpaulcom** [comment]
Hey @diegolmello , @GleidsonDaniel  , Could you please take a look at this PR? Fix : #5564

**Comment by diegolmello** [comment]
That's not an issue.
We just show the user the available dark levels.
If we wanted to fix, it would not be a matter of hiding. We would have to change the copy as well to `Level`.
Also, it should be possible to change level on Automatic with Appearance Schedule enabled.
I'm closing for now.
