### ISSUE TITLE
Save Button Should be Unfocused Until Status Value Changes

### ISSUE THREAD

**Issue by anirbanpaulcom** [RocketChat/Rocket.Chat.ReactNative#5565]
### Description:
 The Save button should only become focused when there is a change in the status.

### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 4.47.0
- Device Name: Redmi note 5 pro
- OS Version: Android

### Steps to reproduce:

1. Go to  "Edit Status"
2.  Observe the Save Button

### Expected behavior:
The Save button should remain unfocused until there is a change in the value of the status. Once the status value changes, the Save button should become focused.

### Actual behavior:
![WhatsApp Image 2024-02-13 at 7 19 16 PM (1)](https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/0cbea77f-242b-4498-8f2f-07a7c52cae6b)

**Comment by anirbanpaulcom** [comment]
@diegolmello , @GleidsonDaniel  Please let me know if this functionality is required or not.

**Comment by groom115** [comment]
Hii @anirbanpaulcom , Can you assign me this ticket. I am wiling to contribute

**Comment by diegolmello** [comment]
@anirbanpaulcom When you say `unfocused` you mean `disabled`.
Yes, it's a valid improvement.

**Comment by groom115** [comment]
@diegolmello Can you assign this ticket to me?

**Comment by anirbanpaulcom** [comment]
Hey @diegolmello , Could you please take a look at this PR?  Fix : #5569

**Comment by Rohit3523** [comment]
This feature was added with https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/5569
