### ISSUE TITLE
While Editing a Quoted Message, it Displays Permalink with Original Content

### ISSUE THREAD

**Issue by anirbanpaulcom** [RocketChat/Rocket.Chat.ReactNative#5567]
### Description:

While editing a quoted message in the input box, it displays the permalink with the original message content.

### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 4.47.0
- Device Name: Redmi note 5 pro
- OS Version: Android

### Steps to reproduce:

1.Quote a message.
2.Edit the quoted message.
3.Observe that the input box displays both the permalink and the original content.

### Expected behavior:

While editing a quoted message, only the original content should be shown in the input box, excluding the permalink.

### Actual behavior:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/912dfd34-707e-478b-820d-8868753ad38a

**Comment by diegolmello** [comment]
It's the same behavior on web. It's a markdown.
I think there's no easy way to solve that without creating a column on Message entity on backend. Closing for now.
