### ISSUE TITLE
Copying a Quoted Message Includes Permalink with Original Content

### ISSUE THREAD

**Issue by anirbanpaulcom** [RocketChat/Rocket.Chat.ReactNative#5568]
### Description:

When copying a  quoted message, the copied content includes both the permalink with the original content of the quoted message.

### Environment Information:

- Rocket.Chat Server Version: 6.5.0
- Rocket.Chat App Version: 4.47.0
- Device Name: Redmi note 5 pro
- OS Version: Android

### Steps to reproduce:

1.Quote a message.
2.Copy the quoted message.
3.Paste the copied content.
4. Observe that the pasted content includes the permalink.
### Expected behavior:
When copying a quoted message, only the original content should be copied without including the permalink.

### Actual behavior:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/130109852/78ceb5df-0848-485b-84c2-93ba412918d9

**Comment by diegolmello** [comment]
Similar to #5567
