### ISSUE TITLE
Can not connect server via http

### ISSUE THREAD

**Issue by achilles-kosun** [RocketChat/Rocket.Chat.ReactNative#557]
In the local development, I can't use http://localhost:3000 as the server.

I thinks it's because here:
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/bef34f7f96b48454999f18752289ace76e056794/app/lib/rocketchat.js#L183

`useSsl` hardcode with `true`. 

Can we detected `useSsl` by the provided url ?

```javascript
const useSsl = url.startsWith('https')
```

**Comment by diegolmello** [comment]
@achilles-kosun Sure! I'll fix that in a few days.

**Comment by achilles-kosun** [comment]
Fixed in #558
