### ISSUE TITLE
Setting up push notifications for Android

### ISSUE THREAD

**Issue by nsakapeter** [RocketChat/Rocket.Chat.ReactNative#566]
@diegolmello Please how do I get push notification up and running for this react native application. I
1. Updated the GCM App ID and API key on the server
2. restarted the server.

When I click on the "send test push to my user" on the rocketchat admin, it says the notification has been sent to 1 device but I actually don't get any notification on my device.

I tried logging out and logging back in on the app but no success at getting a notification delivered to my device. I tried turning on and off the default gateway(gateway.rocket.chat) but not success as well.

**Comment by diegolmello** [comment]
@nsakapeter What's your app version? Are you running from the stores?

**Comment by nsakapeter** [comment]
@diegolmello I am running version 0.66.3. No I downloaded an instance and uploaded it crashlytics for Beta Testing

**Comment by diegolmello** [comment]
@nsakapeter Did you change your app bundle id? If so, please change it here as well: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/rocketchat.js#L470

**Comment by nsakapeter** [comment]
@diegolmello I just updated that but it still doesn't work. However, I fount out that the registerPushToken is not successfully called when the user logs in on the app. I know this because the _raix_push_app_tokens on the database is not updated with the token details.

**Comment by diegolmello** [comment]
@nsakapeter That's odd, because it works fine on https://open.rocket.chat.
Can you try it under 0.72~0.73?

**Comment by Vacak7** [comment]
> @nsakapeter Did you change your app bundle id? If so, please change it here as well: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/rocketchat.js#L470

Hi, can you tell me what exactly we have to change here plz?

**Comment by diegolmello** [comment]
@Vacak7 This issue is outdated (bundleid is set automatically nowadays).
If you're having trouble, open another issue.
I'm closing this one.

**Comment by diegolmello** [comment]
@Vacak7 Also, we'll release FCM support monday.
