### ISSUE TITLE
unblockUser or blockUser doesn't work

### ISSUE THREAD

**Issue by SteveUNSW** [RocketChat/Rocket.Chat.ReactNative#569]
As above, try to block or unblock a user.

Steve

**Comment by SteveUNSW** [comment]
More investigation from me:

It's because the member object is empty.

Hence memeber._id is undefined. 

unBlockUser and blockUser use rid and member_.id to toggle between them.

Steve

**Comment by diegolmello** [comment]
@SteveUNSW Thanks. I'll take a look.

**Comment by diegolmello** [comment]
Fixed on #568
