### ISSUE TITLE
feature: multiple message selection, allowing users to forward and delete messages 

### ISSUE THREAD

**Issue by EgorFrom** [RocketChat/Rocket.Chat.ReactNative#5696]
Hi!

I would like to suggest a PR that introduces a feature for multiple message selection, allowing users to forward and delete messages similarly to how it's done in Telegram. This feature aims to enhance the user experience by providing more flexibility and control over message management.

Would this be a valuable addition to the project? If so, I can proceed with the implementation and submit the PR for your review.

Best regards, Egor

video with my solution:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/31363936/5366c60c-7ef6-4db3-a38f-bf0a7a2ed67a

**Comment by andys448** [comment]
Hi @EgorFrom 
Can you share code for this feature? :)

**Comment by EgorFrom** [comment]
@andys448 Hi! There was some confusion. I am discussing with the team and the client the possibility of publishing the solution, and I will get back to you with an answer later.
