### ISSUE TITLE
Cannot connect to my server

### ISSUE THREAD

**Issue by cyberb** [RocketChat/Rocket.Chat.ReactNative#571]
Cannot connect to my server instance with Rocket.Chat Experimental (React Native) on Android.

Error message: "Credentials were rejected"

Regular android app is fine.

Server version: 0.71.1
App version: 1.7.0

Server nginx config: https://github.com/syncloud/rocketchat/blob/master/config/nginx.conf

Front-end nginx config: https://github.com/syncloud/platform/blob/master/config/nginx/public.conf#L104

**Comment by diegolmello** [comment]
HI, @cyberb.
Thanks for opening this issue.
Today we check for x-instance-id on headers, but I saw that your nginx don't forward it.
This is not a mistake in your config, I'll change the way we check for a valid server by doing a fetch on the api.
I'll let you know when it's ready (probably on 1.7.1 later this week).
Cheers.

**Comment by cyberb** [comment]
Do you plan to release this to Google Play?

**Comment by diegolmello** [comment]
@cyberb i'll release to the stores tomorrow

**Comment by cyberb** [comment]
Still cannot login with 1.7.1

Nginx log:
````
[25/Dec/2018:10:32:25 +0000] "POST /api/v1/login HTTP/1.1" 401 115 "-" "okhttp/3.11.0"
````

Regular adroid client:
````
[25/Dec/2018:10:28:56 +0000] "POST /api/v1/login HTTP/1.1" 200 590 "-" "RC Mobile; Android 7.0; v3.1.1
````

**Comment by AnBo83** [comment]
Same here, credentials rejected on 0.73.2.
I think it is related on LDAP, because before enabling LDAP, login is possible...

**Comment by cyberb** [comment]
We are also using LDAP, so probably related.

@diegolmello  Please reopen the issue.

**Comment by cyberb** [comment]
Could you tell which Android app version this will be included in?

**Comment by diegolmello** [comment]
@cyberb 1.8.0. I'm releasing it right now.
