### ISSUE TITLE
Error opening the emoji keyboard

### ISSUE THREAD

**Issue by naman1608** [RocketChat/Rocket.Chat.ReactNative#5714]
### Description:

Getting a Render Error when clicking on the emoji in the keyboard which should open the emoji keyboard.

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/74304916/0fd1bf1a-734a-49da-9775-a5d17e26683b

### Environment Information:

- Rocket.Chat Server Version: 6.8.0
- Rocket.Chat App Version: 4.50.0
- Device Name: iPhone SE
- OS Version: iOS 17.5

### Steps to reproduce:

1. Join any workspace and then open a channel
2. Click on the empty space in the text field at the bottom
3. Click on the emoji icon

### Expected behavior:

Emoji keyboard to be opened

### Actual behavior:

Render error with log:
Error: NativeViewGestureHandler must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.

### Additional context:

I think some component is being imported from 'react-native-gesture-handler' which is causing this error.

**Comment by diegolmello** [comment]
Just tested develop branch in release mode it looks like it's working.

**Comment by naman1608** [comment]
How to run in release mode?
