### ISSUE TITLE
When the network is weak, the webSocket does not automatically reconnect, and gets stuck in Updating

### ISSUE THREAD

**Issue by nguyenhuynhdeveloper** [RocketChat/Rocket.Chat.ReactNative#5719]
When the network is weak, the webSocket does not automatically reconnect, and gets stuck in Updating,
Please help me

**Comment by reetp** [comment]
You haven't filled out a bug template.

Nonetheless I am not sure there is anything you can do except get better signal.

Please ask for support in https://open.rocket.chat
