### ISSUE TITLE
Marking read messages on android app does nothing

### ISSUE THREAD

**Issue by p-stathas** [RocketChat/Rocket.Chat.ReactNative#5743]
### Description:

Marking read direct messages

### Environment Information:

- Rocket.Chat Server Version: 6.7.1
- Rocket.Chat App Version: 4.49.1.61642
- Device Name: Moto g power (2021)
- OS Version: Android

### Steps to reproduce:

1. Log into rocket chat app on android
2. Mark a read direct message as unread (long press and click "mark unread")

### Expected behavior:

Show that it is unread with a blue numbered bubble

### Actual behavior:

Takes you back to the messages list and does not mark it as unread

**Comment by diegolmello** [comment]
Thanks for reporting. It's fixed on 4.49.2. We released it earlier today.
