### ISSUE TITLE
App crashes when Remote JS Debugging turned on

### ISSUE THREAD

**Issue by sd1998** [RocketChat/Rocket.Chat.ReactNative#576]
Steps to reproduce:
(i) Run the app on (ios or android)
(ii) Enable Remote JS Debugging

The app crashes with an error in the realm.js library.

**Comment by sd1998** [comment]
@diegolmello The fix to this would be either to downgrade real.js from 2.19.1 to 2.17.0 or [this](https://github.com/realm/realm-js/issues/2088#issuecomment-443181759). What should I do?

**Comment by diegolmello** [comment]
@sd1998 Hi, thanks for opening this issue.
What do you need from Remote JS debugging?
Logging or inspect code?
Logging: we already use Reactotron for this and it works in a better way.
Inspect code: it's a problem.
Even when Remote JS debugging was working for us, Realm used to slow down everything.
Realm guys said this is a [React Native issue](https://github.com/realm/realm-js/issues/491#issuecomment-350718316)

We are planning to replace Realm with Watermelon DB, so don't worry about it and try Reactotron for logging.

**Comment by saadqbal** [comment]
Hey @diegolmello do you have any rough timeline when are you going to shift to WatermelonDB?

**Comment by diegolmello** [comment]
@saadqbal Nope. It'll take a few months until we switch databases.
