### ISSUE TITLE
I have an integration problem. Can I integrate Rocket. Chat RN into my own RN application?

### ISSUE THREAD

**Issue by alleniver** [RocketChat/Rocket.Chat.ReactNative#577]
- Your Rocket.Chat.Android app version: 1.6.0 (single-server branch)
- Your Rocket.Chat.iOS app version:1.6.0
- Your Rocket.Chat server version: 0.66.0+
- Device model (or emulator) you're running with: Android All Version And iOS All Version.

Hi，Everyone.
is RocketChat RN can be packaged as a component ? And I Can use yarn or npm to Install it to My RN Exists Project. 

Because if I integrate directly into the existing RN App, the amount of engineering will be very large, and many components we use conflict, such as redux, I use redux-chunk, but RC uses redux-sega, there are same other components ; 

And if you import the current example into an existing project, the code is very difficult to manage.

If RC can be packaged into a component using 
**https://github.com/frostney/react-native-create-library**, I think it will be more convenient to use and easier to integrate into existing apps.

I found a component **https://github.com/mongrov/roverz**, but this component has not been updated to the latest version in time. I am afraid that it is more difficult to maintain after using this. This is the best official to do.

**Comment by alleniver** [comment]
I have found many similar components in the past six months, but since I saw Rocket Chat RN, I intend to use this as a solution for LiveChat in the application. But now I have encountered this problem, I do not know how to solve it?

**Comment by diegolmello** [comment]
@alleniver It's not possible to use RocketChat RN as a component.
