### ISSUE TITLE
Please pay attention to the react-navigation branch, which has not been updated for a long time.

### ISSUE THREAD

**Issue by alleniver** [RocketChat/Rocket.Chat.ReactNative#579]
- Your Rocket.Chat.Android app version: 1.6.0 (single-server branch)
- Your Rocket.Chat.iOS app version: 1.6.0
- Your Rocket.Chat server version: 0.66.0+
Device model (or emulator) you're running with: Android All Version And iOS All Version.

hello,i am use react-navigation in my project,i want to integrate RC to my project,but the RC was use react-navigation-native component,components are not compatible now,i watched the navigation branch but the branch has  not been updated for a long time,Can you update it? because react-navigation is also a very good component, there are a lot of stars, it is also very good to use, and the update is very diligent.

**Comment by alleniver** [comment]
many people use React Navigation. If you want to integrate RC immediately, you must change React Navigation to React-Navigation-Native. This workload can be very large. So do you think about?

**Comment by alleniver** [comment]
It is possible to use React-Navigation at a speed that is not as fast as Native. But sometimes the urgency of the project is more important than speed.

**Comment by alleniver** [comment]
I upgraded the Navigation branch, and in the next days I had to apply all the remaining patches, which was time-consuming.

**Comment by diegolmello** [comment]
Duplicated #366 
See https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/366#issuecomment-404846282
