### ISSUE TITLE
Excuse me, which file do I need to modify to change the Android app's packaged server address to my own server address?

### ISSUE THREAD

**Issue by yuhvv** [RocketChat/Rocket.Chat.ReactNative#5800]
Excuse me, which file do I need to modify to change the Android app's packaged server address to my own server address?

**Comment by GleidsonDaniel** [comment]
Just follow the white label doc:
https://developer.rocket.chat/docs/android-app-white-labeling

**Comment by yuhvv** [comment]
> Just follow the white label doc: https://developer.rocket.chat/docs/android-app-white-labeling
I can't find the location to modify the server address.

**Comment by GleidsonDaniel** [comment]
> > Just follow the white label doc: https://developer.rocket.chat/docs/android-app-white-labeling
> > I can't find the location to modify the server address.

https://developer.rocket.chat/docs/mobile-app-white-labeling

> General White Labeling
> Create an account on [Bugsnag](https://www.bugsnag.com/).
> 
> Set server, appGroup, and appStoreId in the [app.json](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/single-server/app.json#L5) file.
> 
> appGroup must be the same App Group created for the iOS app
> 
> Change app colors in the [colors.ts](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/constants/colors.ts) file

.

**Comment by yuhvv** [comment]
> 只需按照白标文档进行操作：https://developer.rocket.chat/docs/android-app-white-labeling

If you're using Android Studio to package an app, how do you modify the server address?
