### ISSUE TITLE
Cannot connect to my server instance

### ISSUE THREAD

**Issue by AnBo83** [RocketChat/Rocket.Chat.ReactNative#581]
Cannot connect to my server instance with Rocket.Chat Experimental (React Native) on Android.
Error message: "Credentials were rejected"

Login to the server is no longer possible after enabling LDAP authentication. Disabling LDAP authentication does not solve the problem, everything is fine before activation.

Regular android app is fine.

- Your Rocket.Chat.Android app version: 1.71
- Your Rocket.Chat server version: 0.73.2 (Docker Image)

- Steps to reproduce:
Enable LDAP Auth, no login is possible.

**Comment by semack** [comment]
+1. The same configuration.
