### ISSUE TITLE
App is asking for some chats for E2EE key even if E2EE is disabled on server

### ISSUE THREAD

**Issue by TimmiORG** [RocketChat/Rocket.Chat.ReactNative#5822]
### Description:

The app is asking for E2EE password since the update to RocketChat 6.10.2.
E2EE is deactivated on server side and browser is showing the chats without E2EE password request.
This is not shown on all channels. But I have a private, a public and direct message (between three persons) which I receive the request on the app.

### Environment Information:

- Rocket.Chat Server Version: 6.10.2 -> shown in App as 6.10.0
- Rocket.Chat App Version: 4.50.1.63100
- Device Name:  Pixel 7 Pro
- OS Version:  Android 14

### Steps to reproduce:

1. Open effected chat in the app

### Expected behavior:

App should show the messages.

### Actual behavior:

App is showing the request to enter E2EE password

### Additional context:

Please let me know if you need anything else.

**Comment by diegolmello** [comment]
Hey @TimmiORG.
Maybe those rooms were encrypted before and these leftovers could be causing this?

Can you do a test for me?
- Create a private room non-e2ee with two users
- Send messages with both users
- Turn on e2ee and enable it on the room
- Send more messages
- Turn e2ee off on the server
- Check the room if the warning is there

Here's the condition to render that prompt:
- https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/bb59d980b23484a7897611de77d6847bcfad77f4/app/views/RoomView/index.tsx#L1470
- https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/bb59d980b23484a7897611de77d6847bcfad77f4/app/lib/encryption/utils.ts#L129

It would require just a change.
- Check for `state.settings.E2E_Enable` like here https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/bb59d980b23484a7897611de77d6847bcfad77f4/app/lib/encryption/utils.ts#L125 and apply both on [isMissingRoomE2EEKey](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/bb59d980b23484a7897611de77d6847bcfad77f4/app/lib/encryption/utils.ts#L101) and [isE2EEDisabledEncryptedRoom](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/bb59d980b23484a7897611de77d6847bcfad77f4/app/lib/encryption/utils.ts#L118)

**Comment by TimmiORG** [comment]
Hi @diegolmello ,

at least one of the rooms is quite new and for sure without E2EE. Also I'm quite sure that there was never E2EE enabled on the server.

Would it be possible to check this inside the mongoDB?

I have no app access to my test server so testing would be not that easy.

Best regards
Timmi

**Comment by diegolmello** [comment]
> Would it be possible to check this inside the mongoDB?

Yes, but I don't have the knowledge to help you with that.

Perhaps you can send me a test user in a room impacted by this bug? diego.mello@rocket.chat

**Comment by TimmiORG** [comment]
Hi @diegolmello ,

I'm sorry but this would not be possible with the test use either.

**Comment by TimmiORG** [comment]
OK on some rooms I have found a activated key icon on the top of the screen. If this is available I can turn of the E"EE on the room.
Than there is the following message:
 "Disable encryption
 Disabling E"EE compromises privacy. You
 can re-enable it later if needed. Proceed
 with caution."
 
 After hitting disable I can see the room normally.

On some rooms the key icon is grey. There is a message showing for a short time after I enter the E2EE password dialogue and cancel it.

Hope this helps.

I guess there was an issue in older RocketChat versions how the rooms have been created.

**Comment by diegolmello** [comment]
You need permission to tap the key icon, that's why it might show as grey to you on some rooms

**Comment by TimmiORG** [comment]
Hi @diegolmello 
yes looks like the owner of the room has the button enabled.
Any idea how to continue?

The issue is not happening on new rooms. So it has to be something from the older versions.

**Comment by diegolmello** [comment]
Removing e2e keys from Subscription collection on mongo could help, but I don't know the root cause.

**Comment by TimmiORG** [comment]
I'm happy to share the details from the db if you share how to query the settings of the rooms from it. ;)

**Comment by diegolmello** [comment]
Open a ticket. It'll be helpful to move this forward.

**Comment by diegolmello** [comment]
Awesome, @TimmiORG.
Thanks for letting us know.
