### ISSUE TITLE
White label application failing to build

### ISSUE THREAD

**Issue by MisterCode415** [RocketChat/Rocket.Chat.ReactNative#5873]
### Description:
White Label IOS cannot compile, results in error:

`LIBCLANG FATAL ERROR: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)
** BUILD FAILED **

The following build commands failed:
	ScanDependencies /Users/papaviking/Library/Developer/Xcode/DerivedData/RocketChatRN-dcegzihscxiegmguwonxpsvxvzsl/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/RNImageCropPicker.build/Objects-normal/arm64/ImageCropPicker.o /Users/papaviking/sites/single-server/node_modules/react-native-image-crop-picker/ios/src/ImageCropPicker.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNImageCropPicker' from project 'Pods')
	SwiftCompile normal arm64 Compiling\ AppleAuthenticationButton.swift,\ AppleAuthenticationExceptions.swift,\ AppleAuthenticationModule.swift,\ AppleAuthenticationRequest.swift,\ AppleAuthenticationRequestOptions.swift,\ AppleAuthenticationUtils.swift,\ ButtonStyle.swift,\ ButtonType.swift /Users/papaviking/sites/single-server/node_modules/expo-apple-authentication/ios/AppleAuthenticationButton.swift /Users/papaviking/sites/single-server/node_modules/expo-apple-authentication/ios/AppleAuthenticationExceptions.swift /Users/papaviking/sites/single-server/node_modules/expo-apple-authentication/ios/AppleAuthenticationModule.swift /Users/papaviking/sites/single-server/node_modules/expo-apple-authentication/ios/AppleAuthenticationRequest.swift /Users/papaviking/sites/single-server/node_modules/expo-apple-authentication/ios/AppleAuthenticationRequestOptions.swift /Users/papaviking/sites/single-server/node_modules/expo-apple-authentication/ios/AppleAuthenticationUtils.swift /Users/papaviking/sites/single-server/node_modules/expo-apple-authentication/ios/ButtonStyle.swift /Users/papaviking/sites/single-server/node_modules/expo-apple-authentication/ios/ButtonType.swift (in target 'ExpoAppleAuthentication' from project 'Pods')
	CompileSwift normal arm64 (in target 'ExpoAppleAuthentication' from project 'Pods')
	Building workspace RocketChatRN with scheme RocketChatRN and configuration Debug
(4 failures)`

### Environment Information:
M2 Chip on Sonoma, Xcode 16 (16A242d)
repo branch `single-server` at `5225e5edd`

### Steps to reproduce:
1. run: yarn ios

**Comment by leonardo-mazzitelli** [comment]
I found the same problem with my old application of react-native, the pod is generated for xcode 13, but de xcode 16 fails...

**Comment by MisterCode415** [comment]
I downgraded to Xcode 15.4 and it builds OK, so similar experience...

**Comment by niggeulimann** [comment]
there are already two other related tickets: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5886 & https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5877
Please upvote for more attention!
