### ISSUE TITLE
Xcode 16.0 : unexpected service error: The Xcode build system has crashed

### ISSUE THREAD

**Issue by AdnanAliShabir** [RocketChat/Rocket.Chat.ReactNative#5886]
### Description:

Xcode 16.0 : unexpected service error: The Xcode build system has crashed

### Environment Information:

- Rocket.Chat Server Version: 
- Rocket.Chat App Version: 4.52.0 
- Device Name: iPhone 15 pro
- OS Version: 17.5

### Steps to reproduce:

Build iOS app in xc0de 16

### Expected behaviour:

Build project. 

### Actual behavior:

Project build failed.

**Comment by niggeulimann** [comment]
there are two other related tickets: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5877 & https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/5873
Please upvote for more attention!
