### ISSUE TITLE
Release 4.53.0 missing on GitHub

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5895]
### Description:

Today, I observed small differences when using the app. I went to the settings to notice that it was updated to 4.53.0.66079 from 4.52.0.65591. I navigated to GitHub in order to find out what was changed, just to notice that the GitHub repository doesn't know about 4.53.0 and lists 4.52.0 as the most recent release.

### Environment Information:

- Rocket.Chat Server Version: 6.12.1
- Rocket.Chat App Version: 4.53.0.66079
- Device Name: Pixel 8
- OS Version: Android 14

### Steps to reproduce:

1. Navigate to https://github.com/RocketChat/Rocket.Chat.ReactNative/releases

### Expected behavior:

Release 4.53.0 is listed there.

### Actual behavior:

Release 4.52.0 is the most recent release.

![image](https://github.com/user-attachments/assets/8d31e401-9a8e-4d93-88a6-f8e47c6add80)

**Comment by diegolmello** [comment]
Yeah, I had to leave early last week.
Finishing the release right now.
