### ISSUE TITLE
Direct message room name can be edited

### ISSUE THREAD

**Issue by deathbarn** [RocketChat/Rocket.Chat.ReactNative#5904]
### Description:

When logged in as an admin user, the direct message room name can be edited.

### Environment Information:

- Rocket.Chat Server Version:6.12.0
- Rocket.Chat App Version:4.53.0
- Device Name: SH-53A
- OS Version: Android11

### Steps to reproduce:

https://github.com/user-attachments/assets/7c621f63-bff8-4710-a8ca-3e2217eddc65

### Expected behavior:

The room name should not be editable.

### Actual behavior:

The room name can be edited.

**Comment by Rohit3523** [comment]
@diegolmello can you please confirm if this is a bug or intentional behaviour

**Comment by diegolmello** [comment]
@Rohit3523 Probably a bug. Can you fix it?

**Comment by Rohit3523** [comment]
> @Rohit3523 Probably a bug. Can you fix it?

Yeah I can give it a try 🙂
