### ISSUE TITLE
React Native yarn build work on Debug but not in Release. 

### ISSUE THREAD

**Issue by matanswisa** [RocketChat/Rocket.Chat.ReactNative#5909]
I cloned the repository of rocket chat made some changes in the UI , all I try to do now is to build the release version of the app so I'll have the apk itself.
However I faced a lot of issues and error during my tries , on a Debug mode it works fine but it doesn't help because I need the release apk.

I'm facing errors with the  Bugsnag so I tried to remove it completely , then one of my tries indeed worked the apk was created , but once you enter the app it crashed immediately.

error log:
> Task :app:processExperimentalFossReleaseMainManifest
/home/cyberdev/Documents/test-rocket-chat/Rocket.Chat.ReactNative/android/app/src/main/AndroidManifest.xml:24:5-80:19 Warning:
        application@android:allowBackup was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present
/home/cyberdev/Documents/test-rocket-chat/Rocket.Chat.ReactNative/android/app/src/main/AndroidManifest.xml Warning:
        provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present

> Task :app:processBugsnagExperimental-foss-releaseManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processBugsnagExperimental-foss-releaseManifest'.
> Bugsnag: Your AndroidManifest.xml is missing one or more of
  apiKey/versionCode/buildUuid/versionName/package, which are required to upload to bugsnag.
  apiKey=null
  versionCode=999999999
  buildUUID=f8a85e92-ee08-4bcc-a5db-4d53051a1ea5
  versionName=4.54.0
  applicationId=chat.rocket.reactnative
  Manifest file = /home/cyberdev/Documents/test-rocket-chat/Rocket.Chat.ReactNative/android/app/build/intermediates/merged_manifest/experimentalFossRelease/AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4m 4s
1412 actionable tasks: 1399 executed, 13 up-to-date

I feel lost and really appreciate your help

**Comment by diegolmello** [comment]
https://developer.rocket.chat/docs/mobile-app-white-labeling

**Comment by matanswisa** [comment]
I will try thank you

**Comment by matanswisa** [comment]
![Screenshot from 2024-10-14 16-37-34](https://github.com/user-attachments/assets/25914551-1450-4478-90e2-82d0b225e8ab)

I followed your tutorial about white label but still I got error on the release version , 
in the package.json I changed the android-whitelabel to - 
`"android-whitelabel": "npx react-native run-android --main-activity chat.rocket.reactnative.MainActivity --mode=experimentalPlayRelease --appId",`
from debug to release , in debug it works but not in release.

**Comment by matanswisa** [comment]
@diegolmello I will appreciate your help
