### ISSUE TITLE
undefined is not an object (evaluating 'U.startApp')

### ISSUE THREAD

**Issue by tushar-patil-android** [RocketChat/Rocket.Chat.ReactNative#591]
As per document followed all the steps but got this error after run app on android device.

Environment details -
react-native-cli: 2.0.1
npm: 6.4.1
node: v8.12.0 

![error](https://user-images.githubusercontent.com/13730671/51962122-084c9e00-2485-11e9-91ab-9df450a40ec7.png)

**Comment by diegolmello** [comment]
@tushar-patil-android Can you post logs?

**Comment by tushar-patil-android** [comment]
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process chat.rocket.reactnative.debug. Make sure to call FirebaseApp.initializeApp(Context) first. at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.1:219) at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source) at com.wix.reactnativenotifications.gcm.FcmToken.refreshToken(FcmToken.java:73) at com.wix.reactnativenotifications.gcm.FcmToken.onAppReady(FcmToken.java:63) at com.wix.reactnativenotifications.gcm.FcmInstanceIdRefreshHandlerService.onHandleIntent(FcmInstanceIdRefreshHandlerService.java:23) at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:157) at android.os.HandlerThread.run(HandlerThread.java:61)
--


![screenshot_2019-01-31-12-57-43-129_com miui bugreport](https://user-images.githubusercontent.com/13730671/52038428-4797ef00-2558-11e9-819a-cb6b07eeba04.png)

**Comment by diegolmello** [comment]
@tushar-patil-android Hi.
It seems you have installed an updated version of react-native-notifications.
They're implementing gcm -> fcm migration and it's causing this error for you.
Try following our `package-lock` or using `react-native-notifications@1.1.23`.

**Comment by diegolmello** [comment]
Is this related? https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/517
