### ISSUE TITLE
Build app fails

### ISSUE THREAD

**Issue by jadeye** [RocketChat/Rocket.Chat.ReactNative#5910]
### Description:

Hello everyone,
I'm trying to build `react-native` app.
I'm running into issues with both:
1. `react-native-gesture-handler` - cannot seem to get the import statement:
```
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.swmansion.gesturehandler.RNGestureHandlerPackage;
``` 
and implementation path:
```
implementation 'com.swmansion:gesture-handler:2.14.0'
implementation 'com.swmansion:react-native-gesture-handler:2.14.0'
implementation 'com.github.software-mansion:react-native-gesture-handler:2.14.0'
``` 

I'm using `2.14.0` as was described here [https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation/](url):
`To use the version of react-native-gesture-handler that is compatible with your Expo project, run npx expo install react-native-gesture-handler`

and 2.
`Rocket.Chat.ReactNative/android/app/src/main/java/chat/rocket/reactnative/MainApplication.kt:38:63 Type mismatch: inferred type is ArrayList<ReactPackage!>! but Application! was expected`
Code is:

```
override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
        // _this = this
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              add(RNCViewPagerPackage())
              add(SSLPinningPackage())
              // new RNGestureHandlerPackage()
              // add(RNGestureHandlerPackage())
              addAll(AdditionalModules().getAdditionalModules(this))
            }

        override fun getJSIModulePackage(): JSIModulePackage {
            return WatermelonDBJSIPackage()
        }

        override fun getJSMainModuleName(): String = "index"

        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }

``` 
where line `addAll(AdditionalModules().getAdditionalModules(this))` was originally `addAll(AdditionalModules().getAdditionalModules())`

Anyone encounter this when trying to run `./gradlew build`??
Thank you

### Environment Information:

- Rocket.Chat Server Version: irrelevant
- Rocket.Chat App Version: 6.12.0
- Device Name: AVD Medium Phone API 35-ext13
- OS Version:

**Comment by anhtukhtn** [comment]
I encountered the same error, and here's how I resolved it:
- Using `yarn android-whitelabel` as mentioned in https://developer.rocket.chat/v1/docs/android-app-white-labeling.
- For release mode, change  `--mode=experimentalPlayDebug` to  `--mode=experimentalPlayRelease`
