### ISSUE TITLE
[Android] After upload a new picture in the ProfileView the button is disable.

### ISSUE THREAD

**Issue by AugustoAleGon** [RocketChat/Rocket.Chat.ReactNative#593]
Before writing an issue, please make sure you're talking about the native application and not the Cordova one. If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat.Android app version:  Latest

- Your Rocket.Chat.iOS app version: ####

- Your Rocket.Chat server version: open.rocket.chat

- Device model (or emulator) you're running with: Emulator or Android 
For android : Xiaomi Redmi 5A - Android 7.1.2

- Steps to reproduce:

Upload a new picture from your gallery or take a picture and crop it. After that the button should be enable.

**Comment by diegolmello** [comment]
Duplicated #586
