### ISSUE TITLE
Channels interfere with one another?

### ISSUE THREAD

**Issue by davidlougheed** [RocketChat/Rocket.Chat.ReactNative#618]
I'm in both the open.rocket.chat and a private server. They both have a #general channel, and messages seem to go between the two (so when I'm on the private server, messages appear from open.rocket.chat in the GUI). 

I've attached some screenshots of the channels and within the channel in question.

![screen1](https://user-images.githubusercontent.com/357970/52497622-7d665480-2ba4-11e9-9848-d16c4a521822.png)
![screen2](https://user-images.githubusercontent.com/357970/52497621-7d665480-2ba4-11e9-9ec2-ba4f5175ad88.png)

**Comment by diegolmello** [comment]
@davidlougheed Can you check if it happens in this version? https://5667-99262683-gh.circle-artifacts.com/0/tmp/build/outputs/apk/release/app-release.apk

**Comment by davidlougheed** [comment]
@diegolmello I'll give it a shot. It only shows up occasionally so it may take a while to see if it's still occurring.

**Comment by diegolmello** [comment]
@davidlougheed This version will be released Feb 13.
If you find something wrong, tell me.

**Comment by davidlougheed** [comment]
Still happens (iOS, built from latest source). Get an alert a bunch, plus the interfering channels thing (I think when new messages arrive while I'm on the 'other' server). If the APK diverges from the current latest code then that's my bad (I don't have an android phone myself but I'm getting a friend to test it).

<img width="518" alt="screen shot 2019-02-08 at 2 59 40 pm" src="https://user-images.githubusercontent.com/357970/52503106-8eb65d80-2bb2-11e9-9a10-312fd4b400e0.png">

<img width="347" alt="screen shot 2019-02-08 at 2 59 10 pm" src="https://user-images.githubusercontent.com/357970/52503107-8eb65d80-2bb2-11e9-81ff-72f43c7e01b1.png">

**Comment by diegolmello** [comment]
@davidlougheed I'm not sure what this last screenshots supposed to mean.
Let me know if you find the reason for this bug and we can fix it in this release.
Thanks.

**Comment by davidlougheed** [comment]
@diegolmello sorry the last screenshot is a different thing, probably a dev debug popup. ill edit it out since it's not relevant to the issue
