### ISSUE TITLE
Code styling is not monospaced/padded

### ISSUE THREAD

**Issue by davidlougheed** [RocketChat/Rocket.Chat.ReactNative#625]
Code styling is missing monospaced fonts / padding on my phone (versus the desktop web version) on the latest TestFlight version (1.9.0.5693) on iOS.

Compare the following:

![img_f8e3b330285a-1](https://user-images.githubusercontent.com/357970/52663872-a56ff380-2ed5-11e9-9690-a3b126e0b7fd.jpeg)

<img width="999" alt="screen shot 2019-02-12 at 2 52 33 pm" src="https://user-images.githubusercontent.com/357970/52663959-dfd99080-2ed5-11e9-8978-c7322a288389.png">

**Comment by davidlougheed** [comment]
issue: padding is due to nested `<Text>`, which is well-documented (and not a React native bug). The solution here would be to switch some container types in the react native markdown renderer to use `<View>`, which may take a while to implement/test.

**Comment by diegolmello** [comment]
@davidlougheed Markdown is, basically, nested `<Text>`s.
Be careful: In some cases, a `<View>` inside a `<Text>` will raise error.
If you find any case with `<View>` working inside a `<Text>`, make sure it works both on iOS and Android.
We had several issues about this some time ago.

**Comment by emrecio** [comment]
Is there any move on this, still a problem in Zoom (quite embarrassingly when sharing code with other affiliates)
