### ISSUE TITLE
Migrate to WatermelonDB

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#627]
Realm was [never a perfect fit for us](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/576) (neither [React Native](https://github.com/realm/realm-js/issues/2239)) and we've been searching for database alternatives.
[WatermelonDB](https://github.com/Nozbe/WatermelonDB) was launched a few months ago and it seems to be the path to follow.

I've been working on Jitsi integration on past days and got stuck in [this issue](https://github.com/realm/realm-js/issues/2193).
I think it's time to finally do it.

**Comment by Yarkhan** [comment]
Sorry for going off topic here. Apart from the Jitsi integration, what else else motivated you guys to switch from Realm to WatermelonDB? Any other benefits in mind?

Personally, I've been having quite a few problems with Realm. Slow debugging, memory leaks in dev mode and core features not being available yet to JS, among others.

**Comment by lorek123** [comment]
can be closed because of: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1171
