### ISSUE TITLE
Android client crashes just after load

### ISSUE THREAD

**Issue by semack** [RocketChat/Rocket.Chat.ReactNative#633]
- Rocket.Chat.Android app version: 1.9.0
- Self-hosted Rocket.Chat server version: 0.74.0
- Device: Meizu M6
- Steps to reproduce:
Android client had started -> showed the green label "Connected" on the top of the screen -> loaded channel list and just it has appeared on the screen, the app is crashing and closing.

**Comment by diegolmello** [comment]
@semack I searched for errors in M6 on Fabric.
If I got luck, this is your error.

<img src="https://user-images.githubusercontent.com/804994/52949502-383be280-335b-11e9-86cf-a08549a6cde2.png" />

If you're admin, can you try disabling custom emojis and open the app just for testing?

**Comment by semack** [comment]
@diegolmello, I am admin but, unfortunately, I didn't find the option to disable custom emoji, where I should look at?
I've tried to disable emoji in my account but the app still crashes.

**Comment by diegolmello** [comment]
@semack I'll take a look this week and build a test version.
Join #react-native channel on open.rocket.chat to receive a link.

**Comment by semack** [comment]
@diegolmello  I am there. Thanks!
