### ISSUE TITLE
single-server checkout not working on iPad

### ISSUE THREAD

**Issue by mananpatel13589** [RocketChat/Rocket.Chat.ReactNative#639]
single-server checkout not working on iPad. After splash screen it shows only black screen. 

In any iPhone screen its working fine.

**Comment by diegolmello** [comment]
@mananpatel13589 This app isn't iOS universal yet.
Are you willing to contribute?

**Comment by mananpatel13589** [comment]
@diegolmello Thanks.
I will see if I can help :-)
