### ISSUE TITLE
Error type 3 when i start in emulator (Activity class  does not exist.)

### ISSUE THREAD

**Issue by tinarsoft** [RocketChat/Rocket.Chat.ReactNative#663]
- Your Rocket.Chat Experimental app version: latest version
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: emulator android 6.0 on ubuntu

i receive this error when i  run "yarn android"
Starting the app on emulator-5554 (/home/m45/App/android-sdk-linux//platform-tools/adb -s emulator-5554 shell am start -n chat.rocket.reactnative/chat.rocket.reactnative.MainActivity)...
Starting: Intent { cmp=chat.rocket.reactnative/.MainActivity }
Error type 3
Error: Activity class {chat.rocket.reactnative/chat.rocket.reactnative.MainActivity} does not exist.

**Comment by diegolmello** [comment]
@tinarsoft Did you run `yarn` before `yarn android`?

**Comment by tinarsoft** [comment]
yes, i did

**Comment by diegolmello** [comment]
@tinarsoft I think the app was installed, but the activity wasn't found and didn't started automatically.
Search for `[DEVELOP] Rocket.Chat Experimental` in the applications.

**Comment by tinarsoft** [comment]
yes , its installed but its not run

null is not an object (evaluating 'u.startApp')

i think navigation is not adapt for android

**Comment by diegolmello** [comment]
Closing. This is posted on #react-native on open server too.

**Comment by weijia-yu** [comment]
@diegolmello I have the same issue on develop branch, what should we do? I simply just init the project and follow the steps

**Comment by delkant** [comment]
> yes , its installed but its not run
> 
> null is not an object (evaluating 'u.startApp')
> 
> i think navigation is not adapt for android
@tinarsoft  how did you solve this problem? I have the same issue, only having problems on android.

@diegolmello 
> Closing. This is posted on #react-native on open server too.

I am not so sure what this means, do you have a link or any information that can help with this? thanks.

**Comment by diegolmello** [comment]
@delkant Go to https://open.rocket.chat and join #react-native channel.
