### ISSUE TITLE
Add support for scroll down when reading up old messages

### ISSUE THREAD

**Issue by pranay414** [RocketChat/Rocket.Chat.ReactNative#675]
It would be good if we have a scroll button which appears at the bottom when reading up old messages. I found this on Rocket.Chat iOS app and I think this can be a good feature for React Native too.
![1a](https://user-images.githubusercontent.com/16045021/53753657-c9709480-3ed7-11e9-87f8-1b2e1e59ac2d.jpeg)

**Comment by pranavpandey1998official** [comment]
@pranay414 can I work on this

**Comment by pranay414** [comment]
Yes, go on @pranavpandey1998official
