### ISSUE TITLE
Misaligned server name after navigating

### ISSUE THREAD

**Issue by davidlougheed** [RocketChat/Rocket.Chat.ReactNative#676]
- Your Rocket.Chat Experimental app version: 1.10.0
- Device (or Simulator) you're running with: iPhone 8

The server name dropdown gets misaligned when clicking on a channel and then navigating back.

Screen recording: http://dlougheed.com/rocketchat.MP4
Picture:
![image](https://user-images.githubusercontent.com/357970/53780544-f2daf180-3ed2-11e9-8d14-11b747e48d2f.png)

**Comment by diegolmello** [comment]
@davidlougheed Thanks for opening, but it's just in beta.

**Comment by diegolmello** [comment]
Fixed on #680
