### ISSUE TITLE
Some emojis are not rendering properly

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat.ReactNative#682]
- Your Rocket.Chat Experimental app version:1.10.0.9
- Your Rocket.Chat server version: 
- Device (or Simulator) you're running with: redmi note 4 android API 7

screen shots

![whatsapp image 2019-03-06 at 7 11 23 pm](https://user-images.githubusercontent.com/44601530/53885725-749e5c80-4044-11e9-8234-2d7a1cd20e90.jpeg)

![whatsapp image 2019-03-06 at 7 09 45 pm](https://user-images.githubusercontent.com/44601530/53885727-75cf8980-4044-11e9-95f2-f61b6c6f2aaf.jpeg)

**Comment by pranavpandey1998official** [comment]
@diegolmello we are currently using react-emojione library for rendering emojis but problem with this is that it is made for react not react native, it returns a react-element the work around applied in the project is that it has a function that returns Unicode for the emoji it works fine for most of them but in case of these elements it is returning Unicode of different elements for example digit_ zero returns '0' instead of 0️⃣ (Keycap Digit Zero) work around this is to use other package i would recommend https://www.npmjs.com/package/react-native-emoji

**Comment by pranavpandey1998official** [comment]
@diegolmello do you have any other solution in mind ??

**Comment by diegolmello** [comment]
@pranavpandey1998official Our emoji picker lacks tone select as well.
`react-native-emoji` don't seem to be the solution for that.
Or you can prove me I'm wrong 😄 

Note: emoji pickers tend to be slow when opened (several views drawn at the same time) and these libs tend to add too much code to bundle size (+500KB or more).

The awesome solution would be to always add custom emojis to the native emoji picker selector (as native keyboard), but I'm not sure this is possible.
