### ISSUE TITLE
[NEW] More options in Setting Layout

### ISSUE THREAD

**Issue by sk1410** [RocketChat/Rocket.Chat.ReactNative#683]
We can have more option in the Settings Layout.

-  About us 

- Contact us 

- License

@diegolmello Can I work on this ?

**Comment by Jaya738** [comment]
Can I work on this? I am currently working on React

**Comment by sk1410** [comment]
@Jaya738 I almost completed this issue. I will raise a PR by today. Please check some other high priority issues.:)

**Comment by pranavpandey1998official** [comment]
#803
