### ISSUE TITLE
 When will the next stable version be released?

### ISSUE THREAD

**Issue by alleniver** [RocketChat/Rocket.Chat.ReactNative#684]
I like this chat solution very much and have done a lot of comparisons. I think it's very perfect. I see that you are updating every day, so ask when will the next stable version be released, and I can integrate and update it at that time?

**Comment by diegolmello** [comment]
@alleniver By `stable` you mean when it'll be released a new version on the stores?
If so, next week.
I'll start pushing released versions to master too.
Then master will always be stable.
