### ISSUE TITLE
Cannot set invisible status

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat.ReactNative#691]
- Your Rocket.Chat Experimental app version: 1.10.0.99
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: Redmi note 4 API 7

Try setting your status to invisible it won't set but if you check it on the web it is chaged by actions on the app, it seems that upcomming calls from sever are not handled correctly for this ,

**Comment by diegolmello** [comment]
@pranavpandey1998official Yeah, it seems the app isn't receiving its own `offline` status
