### ISSUE TITLE
the URL is invalid

### ISSUE THREAD

**Issue by lienftech** [RocketChat/Rocket.Chat.ReactNative#695]
I try to enter my server url in emulator to connect, and then alert a error box like images.
how can i fix? 
My server is configured SSL and connect well in real IOS device
![Capture](https://user-images.githubusercontent.com/48079146/54100661-390fe380-43f2-11e9-884d-5428bf1e38a7.PNG)

**Comment by pranavpandey1998official** [comment]
@lienftech can you share your servel URL so we could reproduce the issue and can take a better look at ir

**Comment by lienftech** [comment]
@pranavpandey1998official this is my server URL rchat.ftech.ai

**Comment by pranavpandey1998official** [comment]
@lienftech is this still a issue with new version can you try using http://rchat.ftech.ai as server url and then see if it works
