### ISSUE TITLE
null is not an object (evaluating 'U.startApp')

### ISSUE THREAD

**Issue by weijia-yu** [RocketChat/Rocket.Chat.ReactNative#697]
- Your Rocket.Chat Experimental app version: 
`develop branch`
` eb4b1553bf4bed65cce9ca201652143e8f778943`
- Your Rocket.Chat server version: 
`develop branch` 
`eb4b1553bf4bed65cce9ca201652143e8f778943`
- Device (or Simulator) you're running with: 
Simulator Emualtor Nexus 5X API 28 x86
Android Studio version: 3.2.1

**Detail**
My app can run on other simulators such as `Pixel 2 XL API 26` and `Pixel 2 XL API 26`.
But it shows null is not an object `(evaluating 'U.startApp')` on `Nexus 5X API 28 x86`

**Comment by malivp3494** [comment]
Can you please provide error log?

**Comment by didacroyo** [comment]
Is it related to issue #591 ?

**Comment by pranavpandey1998official** [comment]
will be Fixed in #896

**Comment by Exordian** [comment]
i still hit this bug using the latest 'develop' branch (currently on 1a6011e9d11b98281b559ed7dfe87d7e96f9d989 )

**Comment by arminfelder** [comment]
I solved this issue by deleting the android/app/src/main/assets/index.android.bundle
then run react-native start and copy the new bundle file with:
curl "http://localhost:8081/index.android.bundle?platform=android" -o "android/app/src/main/assets/index.android.bundle"
