### ISSUE TITLE
Use react-native-tab-view on EmojiPicker

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#698]
https://github.com/ptomasroos/react-native-scrollable-tab-view isn't maintained as it should.

**Comment by malivp3494** [comment]
I'd like to take a shot at this.

**Comment by diegolmello** [comment]
@malivp3494 Fine! Good luck 😊

**Comment by pranavpandey1998official** [comment]
@diegolmello I have implemented it but performance is not satisfactory with this, takes too much time to load ,

**Comment by diegolmello** [comment]
@pranavpandey1998official Don't delete your branch. Open a PR anyway.

@malivp3494 Did you gave it a shot?

**Comment by pranavpandey1998official** [comment]
@diegolmello it's too far gone.. 😞 maybe I'll implement it again and then make a PR.

**Comment by Prateek93a** [comment]
Can I work on this one?

**Comment by Prateek93a** [comment]
On it

**Comment by Prateek93a** [comment]
@diegolmello Sir, while working on the issue, I found that I was unable to log into the console for debugging. I used log statements with remote js debugging on, but still I could not see any output in the console. Can please guide me where I am making mistake. I tried react-native log-android also, but for some reason I am not getting the required output.

**Comment by Prateek93a** [comment]
@diegolmello The gif shows the implemented react-native-tab-view. I have used lazy loading  for improving the performance. When I swipe across the screens, it works fine, but when I click on a screen which has not been loaded yet, then the screen hangs a bit, as in the Gif.
Sir, is there a way to improve the performance further? or if this is fine for now, should I raise the PR?
![20191002_111707](https://user-images.githubusercontent.com/44807945/66021129-292f2c80-e507-11e9-8f46-1ce0b7b5f03d.gif)

**Comment by diegolmello** [comment]
@Prateek93a Create a PR and I can help you from there.
