### ISSUE TITLE
Audio recorder

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat.ReactNative#70]
https://github.com/jsierles/react-native-audio
https://github.com/futurice/react-native-audio-toolkit

**Comment by saketkumar95** [comment]
@ggazzo Are you working on this? Or should I work and complete this? :)

**Comment by kb0304** [comment]
The current implementation gives an error for mp3 file as `react-native-video` returns `naturalSize.duration` as `-0.001` for it.

@rodrigok @saketkumar95
I would like to work on it. Could you please assign me this issue.
