### ISSUE TITLE
Report Message

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#701]
Add a message action to report it.

https://rocket.chat/docs/developer-guides/rest-api/chat/reportmessage/

**Comment by weijia-yu** [comment]
I'm on it

**Comment by pranavpandey1998official** [comment]
@weijia-yu are you working on it?

**Comment by pranavpandey1998official** [comment]
@diegolmello I am taking this issue .. so do you want to give user ability to write report text .. because Rocket.chat.Android are just reporting message with same text ??

**Comment by diegolmello** [comment]
@pranavpandey1998official https://rocket.chat/docs/developer-guides/rest-api/chat/reportmessage/

As description send "Message reported by user"
