### ISSUE TITLE
[NEW] Mark room as read/unread

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#709]
<img src="https://user-images.githubusercontent.com/804994/54431277-beeaa200-4704-11e9-9ac1-5478a7729b22.png" width="350" />
<img src="https://user-images.githubusercontent.com/804994/54431298-cc079100-4704-11e9-9c2e-13acaf7a9c64.png" width="350" />

**Comment by pranavpandey1998official** [comment]
@diegolmello I could not find api call in the documentation can you refer me the required doc

**Comment by diegolmello** [comment]
@pranavpandey1998official Here: https://rocket.chat/docs/developer-guides/rest-api/subscriptions/read/
