### ISSUE TITLE
[NEW] Jitsi integration

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#711]

**Comment by lienftech** [comment]
hi, is video call and audio call working?

**Comment by diegolmello** [comment]
@lienftech No. This issue is to track future development. It's also described on readme.

**Comment by lienftech** [comment]
@diegolmello : thanks, can i know when release?

**Comment by diegolmello** [comment]
@lienftech I can't give you a date, but it'll be done in a few months.

**Comment by lienftech** [comment]
@diegolmello thanks
