### ISSUE TITLE
[NEW] Upload files

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#713]

**Comment by bahramsport** [comment]
how can upload file other than jpeg ? i need upload pdf , zip , ... file

**Comment by diegolmello** [comment]
@bahramsport that's why this issue is opened. It's not implemented yet.

**Comment by valdirluiz** [comment]
I have the same problem

**Comment by zdumitru** [comment]
Any update on this? Quite a critical issue not working for a long time.

**Comment by diegolmello** [comment]
@valdirluiz @zdumitru This is not implemented yet. Are you guys willing to help?
I can guide you through it.

**Comment by diegolmello** [comment]
#882
