### ISSUE TITLE
Could not install the app on the device,Android emulator running or a device connected and have set up your Android development environment:

### ISSUE THREAD

**Issue by roony4** [RocketChat/Rocket.Chat.ReactNative#717]
When I'm going to run this application having this error.How I solve this.?
(I tried connect my smartphone and android studio emulator.)

`Microsoft Windows [Version 10.0.17763.316]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\gsoc\rocketchatrn\Rocket.Chat.ReactNative>react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
The project name '@remobile/react-native-toast' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/4.4/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).

> Configure project :@remobile/react-native-toast
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at runOnAllDevices (D:\gsoc\rocketchatrn\Rocket.Chat.ReactNative\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (D:\gsoc\rocketchatrn\Rocket.Chat.ReactNative\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (D:\gsoc\rocketchatrn\Rocket.Chat.ReactNative\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

D:\gsoc\rocketchatrn\Rocket.Chat.ReactNative>`

**Comment by diegolmello** [comment]
@roony4 Try running from command line with `react-native run-android`.
`@remobile/react-native-toast` often triggers errors on Android Studio.

If you're wondering how to fix it and keep using Android Studio, you can do this.
```gradle
// settings.gradle

// include ':@remobile/react-native-toast'
// project(':@remobile/react-native-toast').projectDir = new File(rootProject.projectDir, '../node_modules/@remobile/react-native-toast/android')
include ':react-native-toast'
project(':react-native-toast').projectDir = new File(rootProject.projectDir, '../node_modules/@remobile/react-native-toast/android')

// app/build.gradle

// implementation project(':@remobile/react-native-toast')
implementation project(':react-native-toast')
```

**Comment by diegolmello** [comment]
Tell me exactly what you did

**Comment by roony4** [comment]
> Tell me exactly what you did


$ git clone  https://github.com/RocketChat/Rocket.Chat.ReactNative.git 
$ cd Rocket.Chat.ReactNative
$ yarn global add react-native-cli
$ yarn

connected my phone to pc enabling debug mode

$ react-native run-android

**Comment by real-player** [comment]
I have the same problem as yours. I deleted my build cache files by executing 
$ cd android && gradlew clean
command in cmd at Rocket.Chat RN directory.

**Comment by pranavpandey1998official** [comment]
No longer seems to be an issue just do steps by @real-player it will be solved
