### ISSUE TITLE
Unable to re-enable room notification after disabling them in the app

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat.ReactNative#718]
- Your Rocket.Chat Experimental app version: 1.10.0.6193
- Your Rocket.Chat server version: 0.74.2 (snap)
- Device (or Simulator) you're running with: Huawei Y6 Pro 2017, Android 7.0

**Description**
Open a room menu, tap in `Disable notifications` and you're unable to enable them again in the app.

**Comment by diegolmello** [comment]
@TheMythPT It's working here.
There's a passing integration test for it.

**Comment by TheMythPT** [comment]
Unfortunately doesn't work with me with the beta from Play Store.

**Comment by diegolmello** [comment]
@TheMythPT Very odd. Can you try it on `https://open.rocket.chat`?

**Comment by TheMythPT** [comment]
Sure thing. Just let me be sure of the correct instance version.

**Comment by TheMythPT** [comment]
Odd. seems to work in the official server. perhaps the other server I'm joining is using another version or something. I'll check further with admins so I can keep this updated.

**Comment by diegolmello** [comment]
@TheMythPT Nice!
Thanks for testing and letting me know anyway.
Maybe there's a setting/permission I can add to prevent users from doing this.

**Comment by TheMythPT** [comment]
![Screenshot_20190314-131656](https://user-images.githubusercontent.com/25697531/54356284-8773eb00-465b-11e9-9703-a39ca562797b.png)
as it seems is the latest version and snap. it's weird that the behaviour in their instance and in the official one is so different.

**Comment by diegolmello** [comment]
@TheMythPT it works correctly on web?
![image](https://user-images.githubusercontent.com/804994/54359073-9dc07d80-4640-11e9-95cb-ccc5cbfa5224.png)
