### ISSUE TITLE
[I18N] pt-PT Translations

### ISSUE THREAD

**Issue by TheMythPT** [RocketChat/Rocket.Chat.ReactNative#719]
I'd be very appreciated if you could create a pt-PT file with the original strings (in English) so I could translate the project.

Cheers!

**Comment by diegolmello** [comment]
@TheMythPT Just create a new file `pt-PT.js` like `pt-BR.js`.
Here's a similar PR: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/641

**Comment by TheMythPT** [comment]
Well, I was feeling lazy! 😂😂
I'll do it then. 👍
