### ISSUE TITLE
Last message in chat lists differs from the one inside the channel

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat.ReactNative#723]
- Your Rocket.Chat Experimental app version: 1.10.0.6193
- Your Rocket.Chat server version: Official Rocket.chat instance
- Device (or Simulator) you're running with: Huawei Y6 Pro 2017, Android 7.0

**Description**
The app seems to not be making any update of the `last message` in the chat list.

**Screenshots**
Last message in the chat list (#support channel):

![lastmessage_chatlist](https://user-images.githubusercontent.com/25697531/54379350-878adf80-4689-11e9-89d0-147afd00edc6.png)

Last message inside the channel:
![lastmessage_channel](https://user-images.githubusercontent.com/25697531/54379579-f8ca9280-4689-11e9-8689-52b7de11aaad.png)

**Comment by diegolmello** [comment]
@TheMythPT Thanks for opening.
We should do the same logic as here: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/message/Markdown.js#L37

We could also do this to parse emojis like (`:joy:` to 😂): https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/message/Markdown.js#L36

Remember to DRY.
