### ISSUE TITLE
When changing app language, old messages indicators / actions are kept in the default language (EN)

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [RocketChat/Rocket.Chat.ReactNative#724]
- Your Rocket.Chat Experimental app version: 1.10.0.6193
- Your Rocket.Chat server version: Official Rocket.chat instance
- Device (or Simulator) you're running with: Huawei Y6 Pro 2017, Android 7.0

**Description**
When changing app language, older messages aren't _re-translated_

**Screenshots**
![messages_language_change](https://user-images.githubusercontent.com/25697531/54379789-5c54c000-468a-11e9-89d6-3cbf3512bfc7.png)

**Comment by diegolmello** [comment]
@TheMythPT Yes, this is a trouble one.
It's hard to reload every component on the app after changing language.
I think we should show navigate to AuthLoadingView and back.
This would show a splash screen and go back to rooms list.
