### ISSUE TITLE
[IMPROVEMENT] Tap on avatar/username/channel to show info

### ISSUE THREAD

**Issue by TheMythPT** [RocketChat/Rocket.Chat.ReactNative#729]
This would simplify a lot the life of app users

**Comment by diegolmello** [comment]
@TheMythPT Totally! A normal press could open RoomInfoView and a long press could open an action sheet with "New Message" and "Info". Maybe "Video call" and "Audio call" (in the future).

**Comment by weijia-yu** [comment]
I can take this one

**Comment by weijia-yu** [comment]
@diegolmello Right now, when we long press the message, it will pop up message actions, should we just add an option "Direct Message"?

**Comment by diegolmello** [comment]
@weijia-yu We don't want to create DMs every time.
We should navigate to RoomInfoView and have an option there to Message.
Like this:
<img src="https://user-images.githubusercontent.com/804994/59459446-35c23480-8df3-11e9-9669-9f72b3327c88.png" width="350" />

Feel free to open two PRs instead of one:
- One just to add "Message" option to RoomInfoView
- One to navigate on username/channel press

**Comment by weijia-yu** [comment]
@diegolmello 
so

1. Current user room info only has an avatar and timezone, we wanna add "Message"

2. Currently, if we long press avatar in the channel message, it will detect as long press message. Instead, when we long press users in channel message, it should pop up an actions including "New Message" and "Info"?

**Comment by diegolmello** [comment]
@weijia-yu 

1. That's it
2. Nope. Single taps on avatar/markdown tags (`@username`/`#channel`) must navigate to RoomInfoView directly. No need for another actions sheet.

**Comment by weijia-yu** [comment]
@diegolmello when will the user click channel avatar? Channel won't appear in chat message, will it? Or in room list, when you click channel avatar, it will go to room info

**Comment by diegolmello** [comment]
@weijia-yu 

> when will the user click channel avatar?
Never on the avatar, but the channel name can appear on the message, like `#general`

> Channel won't appear in chat message, will it? 
Yes, and the user may tap on it.

> Or in room list, when you click channel avatar, it will go to room info
What do you mean by `room list`? RoomsListView won't be changed.

Rules:
- The user may tap on any avatar and it should navigate to RoomInfoView
- The user may tap on any username/channel tag parsed by markdown (`@username`/`#channel`) and it should navigate to RoomInfoView
- RoomInfoView must have a "Message" button to navigate to the room:
  - if username: create a DM (if it needed)
  - if channel: navigate to the channel

**Comment by pranavpandey1998official** [comment]
#1097
