### ISSUE TITLE
Custom fields on wrong servers

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#752]
- Your Rocket.Chat Experimental app version: 1.10.1

If you log into a server with custom fields, they will appear in the other servers as well.
![image](https://user-images.githubusercontent.com/804994/54750425-67da4680-4bb6-11e9-85c2-5ec10afbd71b.png)

**Comment by adityarajsinghvi** [comment]
@diegolmello  can you please explain it in more detail?

**Comment by diegolmello** [comment]
@adityarajsinghvi Configure Custom Fields on two different servers and go to User Info.

**Comment by bhanujggandhi** [comment]
@diegolmello If this issue is not resolved. Can you please guide me through this? I want to work on it

**Comment by diegolmello** [comment]
It's really old and I don't know if it's still an issue, but the steps remain the same: configure Custom Fields on 2 different servers and go to user info.

Example:
- Server A
Configure "job title" as string

- Server B
Configure "city name" as string

**Comment by bhanujggandhi** [comment]
Sure! I'll look if this still is a issue

**Comment by bhanujggandhi** [comment]
@diegolmello I don't think, user profile reducer is dependent on any server. It is a separate reducer that updates user info accordingly. Can you please look in it?
