### ISSUE TITLE
[NEW] When room name is too big to fit screen, allow dragging the name to view the rest

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat.ReactNative#754]
Check the title area of this reddit app:

![2019_03_20_15_29_45](https://user-images.githubusercontent.com/1986378/54710452-75e08680-4b26-11e9-81ae-1d52f0aa3fc6.gif)

**Comment by diegolmello** [comment]
@marceloschmidt Nice!

We need to limit the container's width based on the current orientation of the screen (`currentWidth - (header button * 3)`) and add a horizontal ScrollView here:
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/RoomView/Header/index.js#L185

There's already a `width` prop in the component, so it's easy as `this.props.window.width` :)
