### ISSUE TITLE
Swipe right gesture to reply message

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#764]
We should swipe right gesture on messages to trigger reply action.
In the same way Whatsapp does.

**Comment by pranavpandey1998official** [comment]
do you want UI to be the same as that of WhatsApp??

**Comment by diegolmello** [comment]
@pranavpandey1998official Yes.

**Comment by Prateek93a** [comment]
@diegolmello If this feature is not being worked on, I would like to work on it. My implementation->

![ezgif com-crop(12)](https://user-images.githubusercontent.com/44807945/72628149-c2c60100-3973-11ea-925e-0a253a4bea0a.gif)

I have also used Swipeable library and hooks. I have added Reply feature in left to right swipe and Add Reaction feature on right to left swipe as shown in above gif.
