### ISSUE TITLE
Remove emoji keyboard from iOS

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#770]
We must remove emoji keyboard from iOS and keep only on Android.
iOS native lib must be removed too.

We must create storyboooks to ensure everything is working on both platforms.
```
Messagebox.android.js
Messagebox.ios.js
index.js
```

**Comment by IlarionHalushka** [comment]
in progress

**Comment by IlarionHalushka** [comment]
@diegolmello  Do you want to develop a completely new component for iOS MessageBox without using KeyboardAccessoryView from react-native-keyboard-input?

**Comment by diegolmello** [comment]
@IlarionHalushka it don’t need to be a completely rewrite. You just need to transform the current messagebox code into a container (with all the logic) and create two new layout files for iOS and Android. Android will remain exactly as it is now and iOS won’t have emoji anymore and it’ll have “plus” button on the left and audio/send on the right (toggling between audio and send by checking if the input is empty).

**Comment by djorkaeffalexandre** [comment]
@diegolmello [PR920](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/920) closes that?

**Comment by diegolmello** [comment]
@djorkaeffalexandre You're right. Good job!
Weird notation tough.
#920: hashtag is so much prettier 😂
