### ISSUE TITLE
[NEW] Show unread count in room's back button

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#778]
<img src="https://user-images.githubusercontent.com/804994/55497513-e358e080-5617-11e9-8273-2d29e7bf3714.png" width="350" />

**Comment by djorkaeffalexandre** [comment]
@diegolmello Count unread chats or count of unread messages?

**Comment by diegolmello** [comment]
@djorkaeffalexandre The same calculation [web](https://github.com/RocketChat/Rocket.Chat) does.
