### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#786]
It's a serious amount of work, but we should add Typescript to keep our app maintainable.
Hopefully it won't have any performance impact or new bugs, but we should do it anyway.

React Native supports Typescript without any harm since 0.57.

We need to do it in baby steps to guarantee not to break anything.
- [ ] Setup: it shouldn't be hard, but we need to make sure everything is working afterwards (app, jest, storybook, detox, release mode, ci)
- [ ] Convert OnboardingView: this is one of the smallest views we have and it's the first one in the navigation stack. Easier to migrate and to test
- [ ] Convert other files module by module (Auth, Rooms, Room, etc).

**Comment by ebouJ** [comment]
@diegolmello I am fairly comfortable with typescript. I can on this task.

**Comment by diegolmello** [comment]
@ebouJ Nice! Go on 👍

**Comment by G2Jose** [comment]
I'd love to work on this as well! Has any work been done on this already?
