### ISSUE TITLE
Show 'Send' button when draft message exists

### ISSUE THREAD

**Issue by IlarionHalushka** [RocketChat/Rocket.Chat.ReactNative#789]
Steps to reproduce: 
1. Open Room View screen
2. Type in 'New Message' input: 'draft message'
3. Click 'back' in header
4. Return back to the same Room View screen 

Expected: Draft message is displayed and the button on the right is 'Send'
Actual: Draft message is displayed but the button on the right is 'Microphone', which makes it not possible to send the draft right away after opening Room View screen.

Video: https://drive.google.com/file/d/1ubWcdFQo-L6z0r2wXb-NgbkqzZ2qvo6u/view?usp=sharing

- Your Rocket.Chat Experimental app version:  branch develop 1.11.0.100
- Your Rocket.Chat server version: open.rocket.chat
- Device (or Simulator) you're running with: simulator iOS iPhone X

**Comment by pranavpandey1998official** [comment]
its fixed
