### ISSUE TITLE
Getting error while adding my server url in sign in your server page.

### ISSUE THREAD

**Issue by samirchauhan** [RocketChat/Rocket.Chat.ReactNative#802]
- Your Rocket.Chat Experimental app version: 1.11.0
- Your Rocket.Chat server version: 0.74.3
- Device (or Simulator) you're running with: Device

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

Getting error Oops! The URL you entered is invalid. Check it and try again, please!

**Comment by pranavpandey1998official** [comment]
I will be needing more info , can you tell me your server URL

**Comment by samirchauhan** [comment]
yes it is chat.oyamohali.org

**Comment by diegolmello** [comment]
@samirchauhan @pranavpandey1998official We always work to keep everyone's data incognito and we'll understand if you don't want to post your server url here, but we need more info to fix your issue.

Other options:
- Send your server url to me (`@diego.mello`) at https://open.rocket.chat
- Simulate a similar server on a free cloud (heroku, etc) and post the link here

**Comment by pranavpandey1998official** [comment]
@samirchauhan  try with http://chat.oyamohali.org

**Comment by pranavpandey1998official** [comment]
thanks for reporting

**Comment by samirchauhan** [comment]
Same error with http also.

**Comment by pranavpandey1998official** [comment]
Sorry but I could excess it with http://chat.oyamohali.org

**Comment by pranavpandey1998official** [comment]
come to our IRC channel open.rocket.chat so we could discuss it more

**Comment by pranavpandey1998official** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/1d9acdb700c5f854e4dbd9bd61074ab90a29c7b8/app/views/NewServerView.js#L142
@diegolmello I think problem is here we are always adding https and not even concedering http
