### ISSUE TITLE
Change "SettingsView" layout

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#803]
We need to add more settings too, but this layout isn't good.

### SettingsView needs:
- Contact us
- Language
- Theme
- Share this app
- License
- Version (it's on SidebarView now and it should be here)
- Server version
- Send crash report

<img src="https://user-images.githubusercontent.com/804994/55877694-1bf53e80-5b71-11e9-8125-edd9b219338a.jpeg" width="350" />

### We need to create a LanguageView similar to this:
<img src="https://user-images.githubusercontent.com/804994/55877586-c91b8700-5b70-11e9-9400-e6a7471e4ac5.jpeg" width="350" />

**Comment by pranavpandey1998official** [comment]
I would suggest that by selecting desired language we should redirect user to chat Stack so hole view could be reloaded

**Comment by diegolmello** [comment]
@pranavpandey1998official Good point. We should do that.
