### ISSUE TITLE
Upload files using endpoint rooms.upload

### ISSUE THREAD

**Issue by AugustoAleGon** [RocketChat/Rocket.Chat.ReactNative#806]
- Your Rocket.Chat Experimental app version: 1.10
- Your Rocket.Chat server version: ###
- Device (or Simulator) you're running with: Simulator

I got an error message when I am sending the data form in the endpoint `rooms.upload/:rid`.
I am doing the following:

```
import { create } from 'apisauce';

		const api = create({
			baseURL: `${ appConfig.server }/api/v1`,
			headers: {
				'X-Auth-Token': authToken,
				'X-User-Id': userId,
				'Content-Type': 'multipart/form-data; boundary=--------------------------f2ee26fd9d793455',
				'Process-Data': false
			}
		});
		const body = new FormData();
		body.append('file', file);
		body.append('msg', msg);
		body.append('description', description);

		const result = new Promise((resolve, reject) => {
			api.post(`/rooms.upload/${ rid }`, body).then((response) => {
				console.tron('This is my response', response);
				resolve(response);
			}).catch((error) => {
				console.tron('Request has failed: ', error);
				reject(error);
			});
		});
```

**Comment by pranavpandey1998official** [comment]
can you post the error too...

**Comment by diegolmello** [comment]
This is not a RN issue. If you're having trouble, refer to the main RC repo as this is an api question.

**Comment by AugustoAleGon** [comment]
It is a RN issue. Because In web the FormData works correctly.

**Comment by AugustoAleGon** [comment]
My response from the server is: 
```
Status Code: 400
success
false
error
File required
```

**Comment by KMtheStarter** [comment]
> My response from the server is:
> 
> ```
> Status Code: 400
> success: false
> error: File required
> ```

Did you solve this problem?
Although my code is built in javascript, I met same issue.

**Comment by AugustoAleGon** [comment]
@KMtheStarter Yeah, I solved. Check the implementation of https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/sendFileMessage.js I realized that the best way to send files is via JS and not libraries.
