### ISSUE TITLE
Show channel's avatar on discussions

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#809]
We should be looking for channel avatar instead of generating a letter for the discussion.
This is better for ux and it'll be helpful when we implement "Change channel's avatar" feature.

Reference: https://github.com/RocketChat/Rocket.Chat/pull/14053

**Comment by weijia-yu** [comment]
@diegolmello Is this issue ready to work on ? Or we need to wait for the implementation of "Change channel's avatar" feature. 

Is there an endpoint to retrieve a channel's avatar already?

**Comment by diegolmello** [comment]
@weijia-yu Yep. It's available to work on. There's no endpoint so far.

**Comment by weijia-yu** [comment]
@diegolmello so discussion will be created based on the channel. Instead of using discussion's first letter as the avatar, we should use the channel's avatar as the discussion avatar?

**Comment by weijia-yu** [comment]
I will take this

**Comment by weijia-yu** [comment]
@diegolmello Discussion's avatar also fetches from the server from a url, https://open.rocket.chat/avatar/@test?format=png&width=50&height=50&rc_token=wNFj067SOaVCxYyNXgJTskzXUVmcHri8yqAYzhvHoA8&rc_uid=x3GuhZRdGm46JWyqt

test is a discussion I generated, and the url is from the server

**Comment by devyaniChoubey** [comment]
@diegolmello can i work on this issue?
