### ISSUE TITLE
Localize dates

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#817]
All our date formats are fixed right now.
We need them to follow user's settings.

**Comment by aryankoul** [comment]
@diegolmello i would like to work on this issue.

**Comment by diegolmello** [comment]
@aryankoul Go on :)

**Comment by aryankoul** [comment]
@diegolmello we need to set the date format according to the language selected?

**Comment by diegolmello** [comment]
@aryankoul Yes, something like this: https://momentjs.com/docs/#/i18n/

**Comment by djorkaeffalexandre** [comment]
@diegolmello I think
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1043
and
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1066
Closes this. Right?
