### ISSUE TITLE
[BUG] Reply on images, audio files doesn't work.*

### ISSUE THREAD

**Issue by IlarionHalushka** [RocketChat/Rocket.Chat.ReactNative#828]
Steps to reproduce:
- go to Room View
- long press on message with image/audio
- click Reply action in actionsheet

Expected: reply modal above message input appears.
Actual: nothing happens.

- Your Rocket.Chat Experimental app version: 1.12.0.6971
- Your Rocket.Chat server version: open.rocket.chat
- Device (or Simulator) you're running with: Iphone SE

**Comment by pranavpandey1998official** [comment]
@IlarionHalushka  i would like to work on this

**Comment by diegolmello** [comment]
@pranavpandey1998official I'll do it. I'll have to change other things as well.
