### ISSUE TITLE
Can't able to start the app. 

### ISSUE THREAD

**Issue by bhanu2795** [RocketChat/Rocket.Chat.ReactNative#834]
@leefaus @davidlougheed 

I simply clone the project and run 'npm i' with node version 10.13
and then run 'react-native run-ios' but it failed.
below is the screenshot.

![Screenshot 2019-04-18 at 10 35 42 PM](https://user-images.githubusercontent.com/16860884/56378428-ac471980-622a-11e9-997a-eed007fab47d.png)

- Your Rocket.Chat Experimental app version: ####
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by IlarionHalushka** [comment]
Are you sure you have all the dependencies installed? 
You can follow this guide: https://facebook.github.io/react-native/docs/getting-started.html
Choose tab 'React Native CLI Quick start'.

After you are done with setup follow the instructions from Rocket.Chat.ReactNative docs:
$ git clone git@github.com:RocketChat/Rocket.Chat.ReactNative.git
$ cd Rocket.Chat.ReactNative
$ yarn global add react-native-cli
$ yarn

**Comment by bhanu2795** [comment]
Yeah installed but got 1 one the following error in the terminal console.
![Screenshot 2019-04-19 at 2 28 54 PM](https://user-images.githubusercontent.com/16860884/56416803-93cd1280-62af-11e9-8ad2-72c602df417e.png)

**Comment by IlarionHalushka** [comment]
Why are you running `npm i`, it is not mentioned anywhere?
This project uses `yarn`
and what's your version of python? mine is 2.7.15

**Comment by bhanu2795** [comment]
Its phython 3.7 npm also works instead of yarn

**Comment by djorkaeffalexandre** [comment]
Same problem.

**Comment by djorkaeffalexandre** [comment]
This problem no block ```react-native run-ios```.
Run ```react-native run-ios```, this command build & run the app.

**Comment by SWKende** [comment]
I have a question.I've been stuck here too long.And i found “yarn config delete proxy” try to resolve,but Its not worked for me :(
![image](https://user-images.githubusercontent.com/24774398/57668477-0aa0c580-763a-11e9-92c4-977a2a9c0023.png)
