### ISSUE TITLE
React Native App doesn't log in or register to my server

### ISSUE THREAD

**Issue by saleseekr** [RocketChat/Rocket.Chat.ReactNative#839]
Hi, I installed Rochet.Chat server and through web interface all goes well. But when I am using RocketChatRN app and trying to log in or register user, there are two ways:

1) If I am entering incorrect user name or password, it says me about wrong credentials (that means that it sees my server).
2) But when I am using proper credentials, it just does nothing. The button is showing spinning stuff for a pair of seconds and that is all.

At that time “adb logcat *:E” is showing only
E/NativeCrypto(14035): ssl=0xb92cfd10 cert_verify_callback x509_store_ctx=0x80bb2f30 arg=0x0 E/NativeCrypto(14035): ssl=0xb92cfd10 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA

When I am trying to use this app for connecting https://open.rocket.chat, it is working! So finally it doesn’t work only on mobile app and only with my server.

Can anybody show me a direction to dig? which another logs should I look or where to find a clue?

**Comment by pranavpandey1998official** [comment]
Send your server URL to me (@pranav.pandey) at https://open.rocket.chat

**Comment by saleseekr** [comment]
> Send your server URL to me (@pranav.pandey) at https://open.rocket.chat

Thanks, added you to private channel there

**Comment by diegolmello** [comment]
@saleseekr Make sure websocket is enabled.
