### ISSUE TITLE
After deleting and re-creating the chat is duplicated

### ISSUE THREAD

**Issue by giterium** [RocketChat/Rocket.Chat.ReactNative#860]
- Your Rocket.Chat Experimental app version: 1.11.0.6782
- Your Rocket.Chat server version: 0.74.3
- Device (or Simulator) you're running with: iphone x

After deleting and re-creating the direct chat is displayed twice for a while. Sometimes it takes a lot of duplicates.

**Comment by giterium** [comment]
![IMG_0660](https://user-images.githubusercontent.com/16814062/56967955-e8ec0c80-6b6a-11e9-8dc1-6c3e1a0414ea.JPG)

**Comment by diegolmello** [comment]
@giterium How do you simulate this?
What 'deleting and re-creating direct' means?

**Comment by giterium** [comment]
1. Delete direct chat. 
2. Create a direct chat which is deleted.

**Comment by diegolmello** [comment]
@giterium How are you deleting a direct chat?

**Comment by giterium** [comment]
In Rocket Chat Electron via chat menu

**Comment by giterium** [comment]
On the main client is the same
https://github.com/RocketChat/Rocket.Chat.iOS/issues/2681

**Comment by giterium** [comment]
Probably the case in the server. Only that to do it is unclear. The duplicates don't disappear.

**Comment by diegolmello** [comment]
> In Rocket Chat Electron via chat menu

Where? Admin? Please, explain in details.

**Comment by giterium** [comment]
In the chat itself. In the section Information about the chat. There is a delete button.

**Comment by giterium** [comment]
![test](https://user-images.githubusercontent.com/16814062/56970245-66198080-6b6f-11e9-8cc7-36cd764e3057.jpg)

**Comment by diegolmello** [comment]
@giterium Rocket.Chat Electron version? Screenshot after clicking "info", etc...

**Comment by giterium** [comment]
2.15.2 version. Why do you need a screenshot?

**Comment by giterium** [comment]
There is something unusual inside? :D

**Comment by diegolmello** [comment]
@giterium Because "info" shows only for group/channel messages for me.
I'm still unable to simulate.

**Comment by giterium** [comment]
The user has rights "delete-p" and "edit-room"?

**Comment by diegolmello** [comment]
`delete-p` is for private, not direct.
But yes, I'm logged in as admin and I can't simulate 🤔

**Comment by giterium** [comment]
![1](https://user-images.githubusercontent.com/16814062/56977405-ca434100-6b7d-11e9-821f-458d8c7ad898.jpg)

**Comment by giterium** [comment]
I have this in all direct chats

**Comment by giterium** [comment]
Maybe it's not direct? :D

**Comment by giterium** [comment]
I just select a user from the directory and click on it

**Comment by diegolmello** [comment]
@giterium Fine. I'll take a look soon. Thanks for opening :)

**Comment by giterium** [comment]
room
![room](https://user-images.githubusercontent.com/16814062/56977857-db408200-6b7e-11e9-82a0-640ea940930b.jpg)
chat
![chat](https://user-images.githubusercontent.com/16814062/56977869-e1366300-6b7e-11e9-931c-52995edb204c.jpg)
Thank you :)
