### ISSUE TITLE
Add sending photos in all formats

### ISSUE THREAD

**Issue by giterium** [RocketChat/Rocket.Chat.ReactNative#861]
- Your Rocket.Chat Experimental app version: 1.11.0.6782
- Your Rocket.Chat server version: 0.74.3
- Device (or Simulator) you're running with: iphone

IPhone saves photo in HEIC format. They can not be sent.

**Comment by djorkaeffalexandre** [comment]
Hi @giterium, What version of your iOS?

**Comment by giterium** [comment]
12.2

**Comment by djorkaeffalexandre** [comment]
Hi @giterium , can you take a screenshot or gif and put here?

**Comment by giterium** [comment]
![IMG_0816](https://user-images.githubusercontent.com/16814062/57599488-8712a600-755f-11e9-9cbb-12031867580c.JPG)

**Comment by giterium** [comment]
Can be manually changed to jpg to send

**Comment by martinhoess** [comment]
I don't know why this is closed. Shure you can change iOS to use JPG instead of HEIC, but the iOS default is HEIC.
It also looks like there's an easy way: https://github.com/react-native-community/react-native-image-picker/issues/872

**Comment by Newar417** [comment]
Still an issue in the latest version.
