### ISSUE TITLE
Paste is not working on Android

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#872]
Known RN issue: https://github.com/facebook/react-native/issues/23653

**Comment by diegolmello** [comment]
#896 may fix

**Comment by lorek123** [comment]
still an issue

**Comment by larryhayes7** [comment]
The only way until a fix is in place for this to work is to type a character then backspace then paste in the copied text

**Comment by lorek123** [comment]
https://gist.github.com/ilya-uryupov/7bc9515c6d315d4919ff56ebf4e20411 this was mentioned here: https://github.com/facebook/react-native/issues/23653 as hack that fixes the issue, maybe this will help ;)

**Comment by diegolmello** [comment]
@lorek123 I saw that hack, but I'm sure there's a better way to do it 😕

**Comment by wreiske** [comment]
Me waiting for paste fix....

![image](https://media.giphy.com/media/3o7TKILKwQCtphbl7y/giphy.gif)
