### ISSUE TITLE
Pull to refresh on rooms list and room

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#884]
We should add pull to refresh on RoomsListView and RoomView to force an update.

#### RoomsListView:
- Pull down to refresh. Above search?
- Fetch all rooms and subs without date: `Promise.all([this.sdk.get('subscriptions.get'), this.sdk.get('rooms.get')])`
- Save new `serversDB.servers.roomsUpdatedAt = new Date()`

#### RoomView:
- Pull up to refresh. Between list and Messagebox.
- Run `loadMessagesForRoom` without date

**Comment by marceloschmidt** [comment]
It should ignore any cache and reload everything as if the user is logging in again. Reload rooms, reload messages, even reload avatars.

**Comment by diegolmello** [comment]
@marceloschmidt I disagree. This is a very expensive task to do in a simple pull to refresh.
What you're suggesting is something like "Clear all my local data from this server".
About avatars: react-native-fast-image don't do it yet, but here's a PR: https://github.com/DylanVann/react-native-fast-image/pull/425
If this is something we can't wait, we may want to create a fork.

**Comment by lolimay** [comment]
> #### RoomsListView:
> * Pull down to refresh. Above search?

I noticed that youtube, twitter and facebook's activity indicators are all below search.

> * Fetch all rooms and subs without date: `Promise.all([this.sdk.get('subscriptions.get'), this.sdk.get('rooms.get')])`
> * Save new `serversDB.servers.roomsUpdatedAt = new Date()`

Can we just simply reuse the `roomsRequest()` action when user pulls down like this?
````js
_onRefresh = async() => {
	this.setState({ refreshing: true });
	await reduxStore.dispatch(roomsRequestAction());
	this.setState({ refreshing: false });
}
````
What's the difference between `fetching all rooms and subs with updatedSince` and `fetching all rooms and subs without date`?

**Comment by diegolmello** [comment]
> I noticed that youtube, twitter and facebook's activity indicators are all below search. I suggest keeping consistent with them.

Youtube and Twitter's search on iOS is on header, but ours is on the list.
That's why I'm not sure where's the best place.
Note: Our search is on the header on Android and on the list on iOS.

> What's the difference between fetching all rooms and subs with updatedSince and fetching all rooms and subs without date?

This is a query. If you request with `updatedSince` it'll do a filter.
