### ISSUE TITLE
Saving an image to the album

### ISSUE THREAD

**Issue by djorkaeffalexandre** [RocketChat/Rocket.Chat.ReactNative#888]
Save to the album doesn't works.

![](https://i.imgur.com/uHsJmOM.jpg)

**Comment by djorkaeffalexandre** [comment]
Need to use a new zoom view lib or create a component to save images and display that looks like this:

![](https://i.imgur.com/y6pKXYW.jpg)

**Comment by ccfiel** [comment]
Hello. Any updates in this?  ☺️

**Comment by djorkaeffalexandre** [comment]
Hello @ccfiel ! We prefer to first change the image preview #903 and after that create a "save to album" feature.

**Comment by ccfiel** [comment]
@djorkaeffalexandre thanks for the update!

**Comment by gyverchang** [comment]
This is a huge bummer. Also, any plans to have the image attachments to be downloaded automatically for future references? When viewing file list on the app, images have to be downloaded again  from the server and all we see are empty thumbnails without any indication on whether it is being loaded or not.

**Comment by Prateek93a** [comment]
@diegolmello Sir I have implemented the save to function, but on the existing zoom library that is being used in the app. However the same code can be used if some other image-zoom gallery or custom component is implemented. 
Currently the feature looks as follows->

1)Using toast- problem here is that the toast box appears below the image so one needs to close the image modal to see the toast. Also we will need to add translations for 'Saved to gallery'.
![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/44807945/70209504-707ba880-1756-11ea-868b-a280296c8c76.gif)



2)Using Alert- 
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/44807945/70209537-838e7880-1756-11ea-9b19-f149c3e14dee.gif)


A loader can be added with both to enhance user experience. So if the above Gifs look fine, shall I raise the PR, and which should I use Alert or toast? or should I wait until another image-zoom library is implemented?

**Comment by diegolmello** [comment]
Use toast and add that key to en.js.
Also, you don’t need to ask to open your PR.
You’re helping us and I’m always glad to review/help you merge it.
Thanks.

**Comment by Prateek93a** [comment]
@diegolmello Thanks Sir. Actually I meant that if we will be implementing a different component for image viewing then I can directly use the code there, that is why I asked.
 And thanks for the support Sir :)
