### ISSUE TITLE
[BUG] Join room button doesn't disappear 

### ISSUE THREAD

**Issue by IlarionHalushka** [RocketChat/Rocket.Chat.ReactNative#901]
Steps to reproduce:
1. open public room (not joined previously) 
2. open room Actions
3. go back to Room View
4. click `Join room` button

Expected: button should disappear.
Actual: button stays there. 

Note: after going back to Room List View and returning back to same public room - the use is joined. 
Skipping step (2) and (3) and clicking `Join room` right away makes the button disappear.

Video: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25078524/57934204-cfb3c180-78c7-11e9-8e15-c9303c57e118.gif)

- Your Rocket.Chat Experimental app version: 1.14.0.100
- Your Rocket.Chat server version: 1.1.0-develop
- Device (or Simulator) you're running with: Simulator Iphone 7, device Iphone SE

**Comment by Prateek93a** [comment]
Can I take this up?

**Comment by IlarionHalushka** [comment]
go ahead 👍

**Comment by Prateek93a** [comment]
@IlarionHalushka Ok Sir

**Comment by djorkaeffalexandre** [comment]
Fixed by #1769.
