### ISSUE TITLE
[IMPROVEMENT] Add loading indicator on OAuth

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#904]
If we tap on Facebook login, for example, the webview takes a few seconds to load FB login, but shows a white screen instead of a loading indicator.

We need to add something like this to track loading state:
https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onloadprogress

**Comment by rasos** [comment]
#270

**Comment by weijia-yu** [comment]
I will work on this
