### ISSUE TITLE
[BUG] Wrong user agent on OAuth

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#905]
WebView is showing weird content on OAuthView.
It seems to be introduced on #800.

**Comment by pranavpandey1998official** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4
