### ISSUE TITLE
Draft Message do not go away when you remove the whole message

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat.ReactNative#923]
- Your Rocket.Chat Experimental app version: 1.14.0.8021
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

go to any channel
write something on message box
go out of channel
now go back and remove the whole saved message 
go back 
go to channel again the removed message comes back

**Comment by diegolmello** [comment]
It's just remove last condition here: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/RoomView/index.js#L230

We should add e2e tests to prevent regression.

**Comment by weijia-yu** [comment]
I will take this one @diegolmello
