### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by Perflyst** [RocketChat/Rocket.Chat.ReactNative#926]
The current [Rocket.Chat.Android](https://github.com/RocketChat/Rocket.Chat.Android) got already added to the F-Droid repo.

I would also like to see this new app for RocketChat on F-Droid.

**Comment by diegolmello** [comment]
@Perflyst Thanks for opening.
Sure. Let's do it!

**Comment by lorek123** [comment]
Kotlin app used to be on F-Droid: https://f-droid.org/en/packages/chat.rocket.android/ (actually it's still there, but it was not updated for a while)
You should consider adding this app to it before you move with replacing Kotlin app with ReactNative one as in https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

**Comment by Atrate** [comment]
@diegolmello How's thia going?

**Comment by lorek123** [comment]
@Atrate it seems that someone is working on this: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1489

**Comment by djorkaeffalexandre** [comment]
I'll close this.
All tracking about F-Droid build will be done at #2096, feel free to add questions.
Thanks.
