### ISSUE TITLE
App crashes if I switch off mobile data

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat.ReactNative#938]
- Your Rocket.Chat Experimental app version: 1.14.0.99
![WhatsApp Image 2019-05-30 at 12 32 53 AM](https://user-images.githubusercontent.com/44601530/58583822-7dcd4d00-8272-11e9-9ad1-574db4f47d81.jpeg)

**Comment by diegolmello** [comment]
@pranavpandey1998official How to reproduce? It happens on production?

**Comment by pranavpandey1998official** [comment]
@diegolmello nope didn't crash the app on beta .. 
To Reproduce
just disconnect to internet and do anything that needs internet like going to any room

**Comment by diegolmello** [comment]
@pranavpandey1998official When it happen again on production, try to isolate the error and grab the log.

**Comment by pranavpandey1998official** [comment]
https://github.com/infinitered/reactotron/issues/786
