### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.ReactNative#94]
- [x] cancel edit message

- [x] typing(false) on send message

- [x] message action trigger (hold) is a little weird 

- [x] better strings on actions

**Comment by rodrigok** [comment]
Show alert saying `copied to clipboard` when hit the option `permalink`.

Would be better to rename:
- `Permalink` to `Copy Permalink`
- `Copy` to `Copy Message`
- `Star Message` to `Star`
- `Pin Message` to `Pin`

**Comment by rodrigok** [comment]
When navigate back while editing a message the text keeps yellow

**Comment by ggazzo** [comment]
about the last one, I think it`s related with` cancel edit message`

**Comment by diegolmello** [comment]
- [ ] settings being flushed on simulator reload
