### ISSUE TITLE
Error sending images

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat.ReactNative#943]
- Your Rocket.Chat Experimental app version: 1.13
- Your Rocket.Chat server version: 1.0.3
- Device (or Simulator) you're running with: Android (Redmi note 4)

Image filename recognition and sending them not working (server has disabled filetype checking)
![Screenshot_2019-05-31-12-17-49-657_chat rocket reactnative](https://user-images.githubusercontent.com/11560794/58699739-891d9700-839e-11e9-9bb5-ddb9fda7d63f.png)
![Screenshot_2019-05-31-12-19-10-621_chat rocket reactnative](https://user-images.githubusercontent.com/11560794/58699747-9044a500-839e-11e9-8dde-88355a0757d7.png)
It not depends on image name

**Comment by IlarionHalushka** [comment]
Thanks for submitting a bug report.
Do you have Rocket Chat server running locally or deployed? If deployed - please give us the url.
What is your Android OS version?

**Comment by dusatvoj** [comment]
Rocket server is running on https://im.blahobyty.cz. My android version is 7.0 (With xiaomi's MIUI 10.2 Global)

**Comment by IlarionHalushka** [comment]
I reproduced the bug, but haven't found the root cause.
Occurs only on Android and only on your server, but doesn't occur on iOS\web.
And also ok when Android + other server 🤔

**Comment by dusatvoj** [comment]
Hmm, what about filetype settings on servers? We have empty rules (for accepting everything).

**Comment by IlarionHalushka** [comment]
Just tested with empty value in `Accepted Media Types` and the results are still the same...

**Comment by IlarionHalushka** [comment]
can you try putting `image/*,audio/*,video/*,application/zip,application/x-rar-compressed,application/pdf,text/plain,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document` in `Accepted Media Types` input and test uploading on your phone again?

**Comment by dusatvoj** [comment]
It's still broken but I will request other people on our server to test it if it's server or client issue

**Comment by dusatvoj** [comment]
Btw... In stable app it's OK so it would be a client app bug

**Comment by dusatvoj** [comment]
Now we are running on RC v1.1.3 and it's solved ... IDK Why, but it works :D
