### ISSUE TITLE
Unable to select MP4 file as attachment

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#950]
- Your Rocket.Chat Experimental app version: **1.14.0.9999999999**
- Your Rocket.Chat server version: **1.1.1 , and open.rocket.chat**
- Device (or Simulator) you're running with: **SAMSUNG-SM-N920V (Android 7.0)**

![image](https://user-images.githubusercontent.com/6295044/58722524-a6a22f00-83a5-11e9-93b6-1e6e3b519ff2.png)

The upload dialog should respect the server's allowed file types.

**Comment by diegolmello** [comment]
Hey, man.
Thanks for reporting.
It's not implemented yet.
I'm almost sure this PR will do the job: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/882
I'm closing this one.
