### ISSUE TITLE
Only last message showing

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#951]
- Your Rocket.Chat Experimental app version: **1.14.0.9999999999**
- Your Rocket.Chat server version:  **1.1.1 , and open.rocket.chat**
- Device (or Simulator) you're running with: **SAMSUNG-SM-N920V (Android 7.0)**

![image](https://user-images.githubusercontent.com/6295044/58722698-17e1e200-83a6-11e9-90a1-a5ea1c60368c.png)

Every room and direct message right now on my phone are only showing the last message, like the picture above.

**Comment by diegolmello** [comment]
Let me know if it's still happening.
