### ISSUE TITLE
Can’t click channels or mentions

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.ReactNative#966]
- Your Rocket.Chat Experimental app version: 1.15.0
- Your Rocket.Chat server version: 1.2.0-develop (open)
- Device (or Simulator) you're running with: iOS 12 on iPhone XS 

![2C591461-4951-4FE4-80B9-D0BBD5E001E9](https://user-images.githubusercontent.com/51996/59082607-94e6ed00-88b9-11e9-9106-7eecb8029d01.jpeg)

I can’t click either one of these.  Even though #general highlights I can’t seem to click it.  Mention doesn’t highlight at all

**Comment by pranavpandey1998official** [comment]
#1097
