### ISSUE TITLE
[Feature Request] Compiling the app to only allow a single server

### ISSUE THREAD

**Issue by DonaldTsang** [RocketChat/Rocket.Chat.ReactNative#985]
This might sound weird, but assume that I start my own server, I would like to make the Mobile client to only access my server, or at least treat my server as "first class" such that I can distribute the compiled app binaries to my fans/users.
Is it possible to make a config file for this?

**Comment by pranavpandey1998official** [comment]
We have a single server branch for this things , #972 tries to update that you can use it after it merges

**Comment by DonaldTsang** [comment]
Looking good, might want to put this in ReadMe. Also is it possible to do it also on android (https://github.com/RocketChat/Rocket.Chat.Android/issues/2376), electron (https://github.com/RocketChat/Rocket.Chat.Electron/issues/1257) or even the web version?

**Comment by pranavpandey1998official** [comment]
This repo uses react native so you have both Android and iOS app.. I don't know about the other repo better contact them , I will add this to the readme , as of now I am closing this
