### ISSUE TITLE
[NEW] Mark message as unread

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#989]
Similar to #709, we should have an option to mark the message as unread.

You need to:
- Add "Mark as unread" option on MessageActions (fired on message long press)
- Call `subscriptions.unread` with `firstUnreadMessage._id`: https://rocket.chat/docs/developer-guides/rest-api/subscriptions/unread/
- Go to rooms list (otherwise you'll mark the rooms as read again)

**Comment by diegolmello** [comment]
@weijia-yu Can you work on this?

**Comment by weijia-yu** [comment]
@diegolmello yes

**Comment by peterchiuglg** [comment]
it doesn't work
