### ISSUE TITLE
Feature request: attach files to chat

### ISSUE THREAD

**Issue by mmnaseri** [RocketChat/Rocket.Chat.ReactNative#994]
- Your Rocket.Chat Experimental app version: 1.15.0
- Your Rocket.Chat server version: 1.0.3
- Device (or Simulator) you're running with: Pixel 3a running Android 9

In the Kotlin client, I'm able to attach files to the chat, but in the ReactNative client I can only attach photos. Choosing to attach from library restricts the file view to photos, meaning for instance that I cannot attach PDF files or GIF files this way.

**Comment by diegolmello** [comment]
Dup of #713

**Comment by diegolmello** [comment]
@mmnaseri Thanks for opening.
You can track #882
